### ISSUE TITLE
Problems to iniciate the program

### ISSUE THREAD

**Issue by sandokanci** [gephi/gephi#1000]
hi, i think that is amazing program, but i can problem to start, the program close to the begining i have to macintosh os yosemite 10.10.1
Thanks

**Comment by Arrvi** [comment]
It fails on Java 8. Change jdkhome in etc/gephi.conf

Details: #997

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
