### ISSUE TITLE
unable to install on mac OSX yosemite

### ISSUE THREAD

**Issue by alecsphys** [gephi/gephi#1003]
Hi,

I downloaded the gephi version 0.8.2 beta for my mac and after double click on the executable Gephi try to open itself but after few seconds it quits. 

Alessandro

**Comment by timcroydon** [comment]
Seems to be a reliance on Java 1.6, which is removed from Mavericks/Yosemite. Try this guide: http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version, which is compatible with latest OS X and reopen if you still have issues. Thanks.
