### ISSUE TITLE
gephi impossible to open

### ISSUE THREAD

**Issue by sophiecrevecoeur** [gephi/gephi#1006]
Hello,
I used to work with gephi for two years and it recently stop working. Last time I tried to open gephi, the gephi Icon appears on my desktop for one minute and then disappears. Then I tried to uninstall gephi in order to reinstall a new version,I removed the .gephi located in the appData (roaming) but when I reinstall the new version the same problem happened again. I don't know what to do to get gephi working again on my computer and I need it for my network analysis. I used windows 7. Thanks for helping.
Sophie

**Comment by williballenthin** [comment]
Have you upgraded to Java 8? I see the same issue when using Java 8, but when reverting to Java 7, Gephi starts up just fine.

See #997

**Comment by sophiecrevecoeur** [comment]
Thank you for you comment. I reinstalled Java7 and now Gephi is working like before. Thank you very much for solving my problem

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
