### ISSUE TITLE
Request new feature

### ISSUE THREAD

**Issue by f4ntom3l** [gephi/gephi#1007]
Hi guys,

I am in my final year and I would like for my project to create a new feature for the application.
If anyone have any ideas for new features, please let me know. 

Thanks,

Andrei

**Comment by Frodox** [comment]
@f4ntom3l take a look at [Roadmap](https://github.com/gephi/gephi/wiki/Roadmap) and [Idea-list](https://github.com/gephi/gephi/wiki/Idea-List).
