### ISSUE TITLE
Problems running Gephi (may be due to Java version?)

### ISSUE THREAD

**Issue by mfms-ncsu** [gephi/gephi#1010]
Hi,

I tried running Gephi a couple weeks ago and it just hung when I loaded a graph (after it told me the number of vertices and edges). At that time I was running Java 7 on a Mac OS 10.10 (Yosemite). I now have Java 8 and it doesn't do anything at all. Do I have to go back to Java 6 to run Gephi?

**Comment by askucher** [comment]
+1  on mac

java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**Comment by gdoubleu** [comment]
Yes you do need 1.6. I ran into the same thing as you, if you make abstraction of the OSX version, this article (http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/) helps with having 1.6 work just for Gephi.

**Comment by mfms-ncsu** [comment]
Thanks a lot. That appears to have done the trick.

---
Matthias F. (Matt) Stallmann, mfms@ncsu.edu
+1 919 515-7978 http://people.engr.ncsu.edu/mfms
Computer Science, 2252 EB II, 890 Oval Drive, Raleigh NC 27695-8206

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
