### ISSUE TITLE
Gephi with Mac 

### ISSUE THREAD

**Issue by Haifaalshehri** [gephi/gephi#1012]
I am in terrible with Gephi, I need very urgent answer. 
I download first time and it was work, then i update java copy after that no way to open. i don't know what i can do

Thanks

**Comment by jackiekazil** [comment]
I had the same problem. I documented the solution here: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
