### ISSUE TITLE
Gephi doesn't start

### ISSUE THREAD

**Issue by ManuelMittler** [gephi/gephi#1015]
Hi, i just downloaded Gephi beta and after a loading screen nothing happens

**Comment by ManuelMittler** [comment]
I am using Windows 7 64bit

**Comment by alex-roc** [comment]
Same issue in Windows 8.1 32-bit, Java 8 (jre1.8.0_31)

**Comment by withforesight** [comment]
I had the same problem.  What worked for me was downloading the snapshot version from here:
https://github.com/gephi/gephi   (under Nightly Builds) 

Also unzipped the snapshot  out-side of normal c:\program files ....  
Maybe the "stable" version has some permission issue or a there is a bug in the installer.  

In any case the snapshot version worked for me.

**Comment by ManuelMittler** [comment]
thanks a lot withforesight, the nightly build seems to work :)

**Comment by withforesight** [comment]
Happy to help.  Hope the official release gets fixed soon...

Mike Behar

**Comment by esevece** [comment]
Thanks @withforesight!

**Comment by florenxe** [comment]
Thanks this worked just fine for me! am using windows8.1 64-bits

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
