### ISSUE TITLE
crash on Intel(R) HD Graphics Family

### ISSUE THREAD

**Issue by zocchi** [gephi/gephi#1017]
Hi, i must point a crash on my graphic card intel family
probably an openGL issue; i have already upgraded my driver but Gephi crash immediately at startup. No error message before.

PCI\VEN_8086&DEV_0A16&SUBSYS_198F103C&REV_09

Suggestions?
Many thanks

**Comment by duncdrum** [comment]
I have no clue about that card, but you might want to include your OS, Gephi version, and Java Version so that other can help you find a solution.

**Comment by zocchi** [comment]
Hi,
OS: Windows 8.1
Gephi version: 0.8.2.0 (but I also tried with 0.8.1 and 0.8,0 and I experience the same problem)
Java version: 8, update 31 (build 1.8.0_31-b13)

Anyway, after taking a look at the information on the website, the problem seems to be  due to an incompatibility matter with the openGL. My card supports version 4.1 while Gephi seems to need 1.5 (does it make any sense to you?).

Thank you for your help

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
