### ISSUE TITLE
App Became Unresponsive

### ISSUE THREAD

**Issue by nickvido** [gephi/gephi#1021]
Launched Gephi 0.8.2 on Windows 7 64bit
Added a node, resized it
Added another node
Right clicked second node and selected 'delete'
Switched views from Overview to Data Laboratory
Window became unresponsive
Now window is all black
Had to kill it with task manager

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
