### ISSUE TITLE
Macbook app crashes - app hang

### ISSUE THREAD

**Issue by socialspace** [gephi/gephi#1027]
Hi I have tried to load a very small network 270 nodes - 150 edges using neo4j plugin - still Gephi cannot run with this - application hangs when trying to visualize - I can connect to NEO4J and see the nodes and  edges count - but cannot do anything else.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
