### ISSUE TITLE
i can not load up Gephi

### ISSUE THREAD

**Issue by 5474103** [gephi/gephi#1028]
Hello , i downloaded Gephy and it shows on my desktop but when i dubble click it does not open - why?

Thanks

arza

**Comment by suzizecat** [comment]
See #997, i think it's the same issue...

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
