### ISSUE TITLE
Can't move the graph

### ISSUE THREAD

**Issue by suzizecat** [gephi/gephi#1032]
Hello,

I'm running the 0.9-SNAPSHOT version of gephy (because i can't launch the 0.82 one , cause of #997 ) on Windows 8.1 with Java 8u31.

Gephi start perfectly but it's impossible to move the graph by dragging it with the right button of my mouse... And, it's impossible to select nodes (but i'm not sure it's possible, i'm novice :sob: ).

By the way, i'm using a gaming mous (MadCatz R.A.T 5) with multiples buttons and using a driver... Maybe this is the problem, but i don't think so...

Regards,
Julien FAUCHER

**Comment by sbrl** [comment]
Yep, I have this problem too.
Is there a workaround, like the option to export the graph as one massive image?

**Comment by eduramiba** [comment]
Hi,
Sorry, Gephi 0.9 snapshot is still not ready to be used.
I will write here when it's actually usable.
