### ISSUE TITLE
Problem with Gephi

### ISSUE THREAD

**Issue by vivianabo** [gephi/gephi#1033]
Dear all,
I installed Gephi and I fund some problems.
I lunch the program and after few seconds the icon disappears and nothing works.
I tried already to download previous versions, to restart windows and to update java, but nothing changes.
Can you help me?
thanks 
Viviana

**Comment by markgorzynski** [comment]
Same here - just installed both Gephi and Java on Win 8.1 and it crashes on install.

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
