### ISSUE TITLE
gephi shouldn't delete files when it can't open them.

### ISSUE THREAD

**Issue by filterfish** [gephi/gephi#1041]
I tried to open a `.gml` file and a `.dot` file and both time gephi errored (there was no indication in the UI apart from the red dot in the bottom right corner — really, really not good UI design). But the best thing is that it removed both files. Seriously! I've repeated this quite a few time now and every single fucking time it removed the file.

Removing files it claims to support them can only be described as a *spectacularly* fail.

**Comment by luileito** [comment]
Same here :disappointed_relieved:

**Comment by filterfish** [comment]
You really can't be arsed to respond to a bug like this; reported by multiple people? Wow.

Good luck. If you can't get this right why the bloody fucking hell do you expect me to think you'll get anything else right.

**Comment by filterfish** [comment]
Sorry @luileito for closing this ticket but I think it's time to move on :)

**Comment by eduramiba** [comment]
If i remember correctly, it's deleting files under temp directory as it thinks they were generated by gephi itself. Is that right?
Otherwise it would be much worse.
