### ISSUE TITLE
Release 0.8.3 with the startup fix

### ISSUE THREAD

**Issue by abitrolly** [gephi/gephi#1043]
Gephi is increasingly being used in academia and courses, but the 0.8.2-beta can not be run on latest Java because of http://samebug.io/stacks?x=3954&s=8c92e488-cf1f-4fc1-a188-33435b290efb

It will worth to release new 0.8.3 with this fix - http://hg.netbeans.org/jet-main/rev/3238e03c676f Is there anything (donations, technical side, organizational) that can help this?

**Comment by eduramiba** [comment]
Related issue: #748

**Comment by eduramiba** [comment]
The fix will be released in 0.9.
