### ISSUE TITLE
Gephi Forum Broken - no one can register after Jan 1 2015

### ISSUE THREAD

**Issue by gnomic** [gephi/gephi#1047]
see https://forum.gephi.org/viewtopic.php?f=4&t=3739 for details. No resolution.

**Comment by drevicko** [comment]
If you follow the link to see about the ip address/domain being blocked, you get this:

    http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st

pointing to this:

    http://www.ahbl.org/content/changes-ahbl

It seems abhl.org has ceased providing the spam domain service, though they indicate they may be proceeding in some other/limited/private way.

**Comment by imsm-assistant** [comment]
Still not possible to register.. So Gephi does not want to fix the problem or is there another reason?

**Comment by eduramiba** [comment]
Hi,
We are working on this and the forum will be available soon.

**Comment by eduramiba** [comment]
We activated the new forum, could you please test you can register and login?

**Comment by eduramiba** [comment]
I see you were able to register and login, closing this :)
