### ISSUE TITLE
Wiki "forbidden access" ?

### ISSUE THREAD

**Issue by stampf** [gephi/gephi#1050]
When I try to access to https://wiki.gephi.org/index.php/Import_CSV_Data I get a "403 Forbidden access" ?

Same thing with https://wiki.gephi.org/

**Comment by travisfw** [comment]
@mbastian is gephi dead?

**Comment by eduramiba** [comment]
Hi,
Sorry, the wiki is in process of migration to github: https://github.com/gephi/gephi/wiki
New entry for that is now at https://github.com/gephi/gephi/wiki/Import-CSV-Data

**Comment by mbastian** [comment]
Closing as resolved, all content is on wiki now. Warning though as we still need to update some of it based on the new 0.9 version.
