### ISSUE TITLE
cannot choose chinese fonts in preview. 

### ISSUE THREAD

**Issue by azalea-du** [gephi/gephi#1058]
The labels of my graph are in Chinese. When I view them in both "preview" and "overview" are normal, but if I exported the pdf in "preview" panel, the Chinese characters failed to be exported. They messed up.

The steps:
I changed the font in "preview" under "Nodel Labels" -> "Font", but there are only 5 selections under "Preview Setting - Font": Dialogue, SansSerif,  Serif, Monospaces, DialogInput.   If I chose "SansSerif", the Chinese character is normal in preview. But messy in the exported pdf. And "NULL Pointer Exception" when exporting to SVG.

In "Overview", I could access a list of fonts, such as Microsoft YaHei and so on.

What can I do to export Chinese characters in pdf? Thanks.

The version I use is 0.8.2. JDK 1.7. WIndows 7.

Thanks.

**Comment by duncdrum** [comment]
chinese characters work for me provided that the length of the strings remains short. Could you maybe post a screenshot of what exactly is "messy". Can you see if the pdf has embedded fonts or if it is substituting fonts? How do you view the pdf? Acrobat reader?

**Comment by azalea-du** [comment]
Thanks for the reply. I have fixed this problem. This is because pdf has not embedded the fonts. 

To fix:
1. Add the codes as below before PdfExporter:
File dir = new File("c:/windows/fonts");
for(File f : dir.listFiles())
      FontFactory.register(f.getAbsolutePath());
		
Font font = new Font("SimSun", Font.PLAIN, 12);

2. Must use PdfExporter.
ExportController ec = Lookup.getDefault()
				.lookup(ExportController.class);
PDFExporter pDFExporter = (PDFExporter) ec.getExporter("pdf");
		
pDFExporter.setLandscape(true);
pDFExporter.setWorkspace(workspace);
File file = new File("***.pdf");

FileOutputStream fos = new FileOutputStream(file);
pDFExporter.setOutputStream(fos);
pDFExporter.execute();

**Comment by echocityu86** [comment]
Hi, can you please tell me where do you add the code? I met with the same problem when exporting a network with Chinese labels.
Thank you very much.

**Comment by duncdrum** [comment]
@echocityu86 could you please post a link to your gephi file so we can try to reproduce this. 
Could you also post your OS, JAVA, GEPHI, and default pdf reader, do you use Chinese as the primary language on your system?

@mbastian I think this issue should be re-opened, to make sure that Gephi uses the right default fonts on CJK systems, or always embedds fonts in pdf exports. Especially on win systems there are some differences with the system fonts depending on the primary language settings. I think this might be the cause of this.

**Comment by echocityu86** [comment]
@duncdrum  Thank you for you reply.
I use Gephi 0.8.2 in windows 8 system, Java 7, English as the primary language(don't use Chinese because there have been some display problems in the filter section when use Chinese as the display language). I've been trying to figure out this problem for a while, but still no solution.

**Comment by duncdrum** [comment]
@echocityu86 just to make sure your windows primary language is Chinese (simplified or traditional?). Gephi uses english in the UI, and you try to view the pdf in ?

Could you send me a link to a sample gephi file that has this problem? Could you also attach a pdf that shows the problem.

**Comment by echocityu86** [comment]
Hey, Duncan,

Attached is the one of the data set I'm working on.
The problem is, when I set the windows primary language as Chinese, the
filter function in Gephi won't work -- I want to filter out node within a
certain degree range, while in Chinese system, the degree range bar cannot
show the number.
I view the phf in Adobe reader, and attached is the exported pdf file. It
show the nodes and edges well, just no labels.

Best,

Jing



On Sun, Nov 22, 2015 at 2:44 PM, Duncan Paterson <notifications@github.com>
wrote:

> @echocityu86 <https://github.com/echocityu86> just to make sure your
> windows primary language is Chinese (simplified or traditional?). Gephi
> uses english in the UI, and you try to view the pdf in ?
>
> Could you send me a link to a sample gephi file that has this problem?
> Could you also attach a pdf that shows the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gephi/gephi/issues/1058#issuecomment-158722806>.
>



-- 
Dr. LIU Jing/劉 璟
Department of Media and Communication
City University of Hong Kong
Phone: 852-68059266

**Comment by wybert** [comment]
> Thanks for the reply. I have fixed this problem. This is because pdf has not embedded the fonts.
> 
> To fix:
> -- Add the codes as below before PdfExporter. The directory is the os fonts.
> 
> File dir = new File("c:/windows/fonts");
> for(File f : dir.listFiles())
> FontFactory.register(f.getAbsolutePath());
> 
> Font font = new Font("SimSun", Font.PLAIN, 12);
> 
> -- Must use PdfExporter.
> 
> ExportController ec = Lookup.getDefault()
> .lookup(ExportController.class);
> PDFExporter pDFExporter = (PDFExporter) ec.getExporter("pdf");
> 
> pDFExporter.setLandscape(true);
> pDFExporter.setWorkspace(workspace);
> File file = new File("***.pdf");
> 
> FileOutputStream fos = new FileOutputStream(file);
> pDFExporter.setOutputStream(fos);
> pDFExporter.execute();

Actually, if you use `png` as the output format, it will be work
