### ISSUE TITLE
Edge colors are unnecessarily dark

### ISSUE THREAD

**Issue by deckar01** [gephi/gephi#1060]
**Behavior:** When a graph is visualized, with no nodes highlighted, the original colors are darkened significantly. When a node is highlighted it's edges are the correct color and all non-adjacent edges and nodes are made transparent.

![screen shot 2015-06-03 at 11 00 07 am](https://cloud.githubusercontent.com/assets/3108007/7965610/3c9fd6fa-09e4-11e5-8ac0-cddf6a1942c1.png)
![screen shot 2015-06-03 at 11 00 46 am](https://cloud.githubusercontent.com/assets/3108007/7965611/3ca0bdd6-09e4-11e5-87c1-4c9d7fbf72e2.png)

**Issue:** Adjusting the color in this way destroys information particularly in graphs with large, subtle color palettes. I have no way to view the entire graph with its original colors intact.

**Expected Behavior:** When a graph is visualized, with no nodes highlighted, the original colors are displayed exactly as they are defined in the graph file. When a node is highlighted it's edges and adjacent nodes stay the same color, and only the non-adjacent nodes and edges are made transparent.

**Suggested Implementation:** I would recommend not darkening the nodes and edges ever. Any information that can be gained by highlighting a node can be done so without altering the default colors assigned to the graph's nodes and edges. If it is determined that this behavior is still desirable I would recommend adding a setting called "Dim graph colors until highlighted" and have it disabled by default. If it is insisted that this remain the default behavior then it could be enabled by default.

**Additional Considerations:** A significant portion of the population has some degree of color vision deficiency. Simply darkening colors hinders the ability of this group to differentiate many colors. Darkened blue gets confused with purple. Darkened red, green, and yellow get confused with eachother and brown.

**Final Thoughts:** Visualizing a graph is a scientific tool. No scientific tool should arbitrarily add some constant to all of your data, truncate floating point values, or shift a graph across its axis only to fix it when it is highlighted. Modifying the color of a graph in its default state is equally as destructive. The purpose of visualizing a graph is to convey large, complex data in the most digestible form possible. Destroying the color information in its default state violates this fundamental principal, because it forces one to return to analyzing a graph node by node instead of clearly viewing the graph in its entirety.

**Comment by jacomyma** [comment]
You are totally right, the color management of nodes and edges has to be fixed. It is already on our road map. You will have to wait until version 0.9 or 1.0 though. More about this in an upcoming blog post.

**Comment by mbastian** [comment]
I agree as well and I'm working on fixing this. Just to clarify, this issue only concerns edge color because as far as I know the node color is respected (except for the node border which is darkened, on purpose).

**Comment by deckar01** [comment]
Just installed 0.9.0 and it looks great! Thanks for everyone's hard work.
