### ISSUE TITLE
Interface flickers and renders on window blur and focus

### ISSUE THREAD

**Issue by deckar01** [gephi/gephi#1061]
When focusing, blurring, or dragging the window in OSX, the entire window repaints unnecessarily.

[![screen shot 2015-06-03 at 12 37 01 pm](https://cloud.githubusercontent.com/assets/3108007/7967062/78bcc8ba-09ed-11e5-9ffe-2190f1ca1a05.png)](https://youtu.be/32yQaRG4BWU)
[YouTube: gephi render bug (unlisted)](https://youtu.be/32yQaRG4BWU)

**Comment by mbastian** [comment]
AFAIK that has been fixed in the 0.9 release. Please confirm.

**Comment by deckar01** [comment]
Looks great! Thank you.
