### ISSUE TITLE
The Mac OS X (10.9.5 (13F1077)) crashes before opening

### ISSUE THREAD

**Issue by talbarda** [gephi/gephi#1062]
The Gephi application isn't opening on my MAC (my version is 10.9.5 and it is happening also on my friend's MAC with 10.0.3 version)

From the "Console" application you can see the message:
6/7/15 10:04:49.875 AM com.apple.launchd.peruser.501[381]: (org.gephi.148224[3069]) Exited with code: 2

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
