### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Adrianww** [gephi/gephi#1063]
Hello!

I had already installed Java, then installed Gephi. Launching the application and then nothing happens. My system runs Intel Core i5 Pro 4th gen with 8GB of RAM and licensed Windows 7 (64bit).

Can you help me solve this?

Thanks!

**Comment by morzproject** [comment]
Currently Gephi is not fully compatible with Java 8. Uninstall Java 8 and install previous version (Java 7). http://download.oracle.com/otn/java/jdk/7u76-b13/jre-7u76-windows-i586.exe

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
