### ISSUE TITLE
Gephi Streaming API wiki 403 Forbidden

### ISSUE THREAD

**Issue by wangray** [gephi/gephi#1065]
Trying to access the wiki for the Gephi Streaming API, getting a 403 Forbidden error.  https://wiki.gephi.org/index.php/Graph_Streaming#Plugin_interface

**Comment by emiguelt** [comment]
Still unaccesible.... any help please?

**Comment by eduramiba** [comment]
Sorry, wiki migration problems. This is now available at https://github.com/gephi/gephi/wiki/GraphStreaming
