### ISSUE TITLE
I can't get Gephi to open up on my laptop after downloading it. 

### ISSUE THREAD

**Issue by paulsonne** [gephi/gephi#1066]
It just starts to open and then doesn't go past the gephi start up graphic.  Please help!!

**Comment by morzproject** [comment]
Please see #1063

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
