### ISSUE TITLE
Broken Links on Contribute Page

### ISSUE THREAD

**Issue by Deshna** [gephi/gephi#1067]
There are a lot of broken links on the Contribute to Gephi page.
https://gephi.github.io/users/contribute/

Listing some of them:
https://wiki.gephi.org/index.php/Gephi_Developer_Handbook
https://wiki.gephi.org/index.php/Documentation_Wishlist
https://wiki.gephi.org/
https://gephi.github.io/users/marketing/spread-students/
https://gephi.github.io/users/marketing/spread-dev/
https://wiki.gephi.org/index.php/Localization
http://gexf.net/explorer/
https://wiki.gephi.org/index.php/Ideas
https://wiki.gephi.org/index.php/HowTo_report_a_bug

You have an amazing community. Are there any parts in the documentation you would like some help?

**Comment by mbastian** [comment]
Fixed, thanks for reporting! The website needs an overhaul content update so that's just a short-term fix.
