### ISSUE TITLE
how to make bar chart in gephi

### ISSUE THREAD

**Issue by abdulmajid398** [gephi/gephi#1069]
I a doing some e work on visualizations and need to plot bar charts from csv in gephi.
if you have some link do sent me please i shall be thankful to you.

**Comment by morzproject** [comment]
Gephi is a network visualization tool, I cannot generate bar charts.

**Comment by jockeyyan** [comment]
As I know Gephi couldn't make bar chart, maybe you should try some other tools or make some plugins.
