### ISSUE TITLE
Gephi dies in Windows 8.1

### ISSUE THREAD

**Issue by mbilger** [gephi/gephi#1072]
I have used Gephi with Windows 7 but since upgrading to 8.1 it just dies when I start it. Any solution?

**Comment by blaiseyuri** [comment]
Try following these instructions

https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by mbilger** [comment]
Finally got to it. Works fine now -

thanks!

Mark


________________________________

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
