### ISSUE TITLE
Subgraph attributes hide first node attributes

### ISSUE THREAD

**Issue by bminano** [gephi/gephi#1075]
When loading a graph with a subgraph having attributes, the first node of the subgraph does not load correclty its attributes.
When showing the attributes it appears empty.
![captura de pantalla de 2015-07-08 10 49 18](https://cloud.githubusercontent.com/assets/5592320/8566556/2c3969ac-255f-11e5-91f4-f3441eb61beb.png)

The graph used is as follows:
digraph g {
  subgraph cluster_0 {
    label="p0";
    n0 [stateAvg=1];
    n1 [stateAvg=0.57906];
    n2 [stateAvg=0.63874];
    n3 [stateAvg=0.56205];
    n4 [stateAvg=0.61574];
    n5 [stateAvg=0.57295];
    n6 [stateAvg=0.58893];
    n7 [stateAvg=0.57386];
    n8 [stateAvg=0.64304];
    n9 [stateAvg=0.61665];
    n10 [stateAvg=0.56415];
    n11 [stateAvg=0.57813];
    n12 [stateAvg=0.58567];
    n13 [stateAvg=0.5686];
    n14 [stateAvg=0.5705];
    n15 [stateAvg=0.56554];
    n16 [stateAvg=0.57735];
    n17 [stateAvg=0.56387];
    n18 [stateAvg=0.58023];
    n19 [stateAvg=0.5623];
  }

  n0 -> n2;
  n0 -> n8;
  n0 -> n9;
  n1 -> n17;
  n1 -> n18;
  n1 -> n2;
  n1 -> n3;
  n1 -> n7;
  n1 -> n9;
  n1 -> n11;
  n2 -> n0;
  n2 -> n1;
  n2 -> n18;
  n2 -> n4;
  n2 -> n6;
  n2 -> n7;
  n3 -> n1;
  n3 -> n13;
  n3 -> n17;
  n3 -> n5;
  n4 -> n2;
  n4 -> n8;
  n4 -> n9;
  n5 -> n17;
  n5 -> n3;
  n5 -> n8;
  n5 -> n10;
  n6 -> n12;
  n6 -> n2;
  n6 -> n11;
  n7 -> n1;
  n7 -> n12;
  n7 -> n13;
  n7 -> n15;
  n7 -> n19;
  n7 -> n2;
  n7 -> n9;
  n7 -> n10;
  n8 -> n0;
  n8 -> n12;
  n8 -> n16;
  n8 -> n4;
  n8 -> n5;
  n8 -> n9;
  n9 -> n0;
  n9 -> n1;
  n9 -> n13;
  n9 -> n14;
  n9 -> n18;
  n9 -> n4;
  n9 -> n7;
  n9 -> n8;
  n9 -> n11;
  n10 -> n14;
  n10 -> n5;
  n10 -> n7;
  n11 -> n1;
  n11 -> n13;
  n11 -> n18;
  n11 -> n6;
  n11 -> n9;
  n12 -> n6;
  n12 -> n7;
  n12 -> n8;
  n13 -> n16;
  n13 -> n17;
  n13 -> n19;
  n13 -> n3;
  n13 -> n7;
  n13 -> n9;
  n13 -> n11;
  n14 -> n19;
  n14 -> n9;
  n14 -> n10;
  n15 -> n18;
  n15 -> n7;
  n16 -> n13;
  n16 -> n17;
  n16 -> n8;
  n17 -> n1;
  n17 -> n13;
  n17 -> n16;
  n17 -> n18;
  n17 -> n3;
  n17 -> n5;
  n18 -> n1;
  n18 -> n15;
  n18 -> n17;
  n18 -> n2;
  n18 -> n9;
  n18 -> n11;
  n19 -> n13;
  n19 -> n14;
  n19 -> n7;
}

**Comment by mbastian** [comment]
I fixed this to provide a minimum functionality but it won't properly deal with all cluster attributes.

This will work though and properly import all nodes and attributes:
```digraph g {
    subgraph cluster_0 {
        n0 [foo=a];
        n1 [foo=b];
    }
    n0 -> n1;
}```
