### ISSUE TITLE
Unable to start Gephi under Windows

### ISSUE THREAD

**Issue by ZeweiSong** [gephi/gephi#1076]
I've installed Gephi but it failed to start under Windows 8 (There is a starting window, then it disappeared). I've tried to update jave to its latest version.

**Comment by songjinghe** [comment]
I guess you are using java8, isn't it ? Gephi only support java6 or java7~

**Comment by songjinghe** [comment]
check out these instructions
https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
