### ISSUE TITLE
Gephi no se ejecuta

### ISSUE THREAD

**Issue by sercarfe** [gephi/gephi#1078]
Hola, 

Mi nombre es Sergio.

Tengo instalado Gephi 0.8.2 en una computadora con Windows 7, Java DKE 8.45.

Cuando intento iniciar Gephi, solo me levanta la pantalla de inicio y luego se cierra.

Les agradecería me indicaran que puedo hacer

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
