### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by klsheehan** [gephi/gephi#1079]
the initializing screen pops up for about 10 seconds then closes and nothing else happens

**Comment by duncdrum** [comment]
please check these instructions or previous posts about identical behaviour. 
https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
