### ISSUE TITLE
DHNS View Destructor, graph-event-bus,attribute-event-bus threads is not close

### ISSUE THREAD

**Issue by sunqing** [gephi/gephi#1080]
I already clean the workspace, close the project and close the workspace， 
but DHNS View Destructor, graph-event-bus,attribute-event-bus this three threads is also not closed.
And its number is more and more. This will lead system threads number to MAX LIMIT.

**Comment by mbastian** [comment]
This has been resolved with Gephi 0.9+. Please try again with the latest toolkit release (0.9.1).
