### ISSUE TITLE
GraphML Importer doesn't recognize node attributes

### ISSUE THREAD

**Issue by richknepper** [gephi/gephi#1084]
When using pygraphml to create a graphml file, on import, the gephi 0.8.2beta importer reports "Attribute class not found or unknown" for each node attribute.  GraphML that generates this error is visible at https://gist.github.com/richknepper/f01b28de5fd105c7034c

**Comment by mbastian** [comment]
This issue arise because pygraphml omits the "for" attribute in the <key>. The value has to either be "node" or "edge" for Gephi to be valid. GraphML's DTD indicated the default value should be "all", which most likely mean that the attribute key is added to both nodes and edges.
