### ISSUE TITLE
How to import connections

### ISSUE THREAD

**Issue by MuriloHMoreira** [gephi/gephi#1086]
Hi, I have a problem when importing data from a .csv file.
I want to create a graph that contain the connections between different countries. So my source .csv file is like this 
![image](https://cloud.githubusercontent.com/assets/13623822/9036880/1684d616-39bc-11e5-9c19-844a304182c3.png)

How can i make the connections? Do I connect ABCDE with ABCDE? Because when I try to do this I only have the nodes of the first column.

Thank you for your help!

**Comment by eduramiba** [comment]
Hi,
Please follow https://github.com/gephi/gephi/wiki/Import-CSV-Data and http://gephi.github.io/users/supported-graph-formats/spreadsheet/
