### ISSUE TITLE
Wrong density calculation

### ISSUE THREAD

**Issue by davanT420** [gephi/gephi#1088]
Graph density seems to be calculated wrongly in the calculateDensity method; the line

result = (multiplier * edgesCount) / (nodesCount * nodesCount - nodesCount);

should be:

result = (multiplier * edgesCount) / (nodesCount * (nodesCount - 1));

For reference, see
(a) (python) networkx density implementation for undirected graphs:
d = 2m/(n(n - 1)) with m being edge count for the graph, n node count
url: http://networkx.readthedocs.org/en/stable/reference/generated/networkx.classes.function.density.html?highlight=density

(b) R/IGraph implementation definition:
The density of a graph is the ratio of the number of edges and the number of possible edges.
Personal note: the number of possible edges in a network with n nodes is n(n-1)

(c) wikipedia definition: https://en.wikipedia.org/wiki/Dense_graph

url: https://github.com/gephi/gephi/blob/f8c032d38b0b2ba6b9dbcb41ed8c0a2d472ab620/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/GraphDensity.java

calculateDensity method (line 95-107):

public double calculateDensity(Graph graph, boolean isGraphDirected) {
double result;
double edgesCount = graph.getEdgeCount();
double nodesCount = graph.getNodeCount();
double multiplier = 1;
if (!isGraphDirected) {
multiplier = 2;
}
result = (multiplier * edgesCount) / (nodesCount * nodesCount - nodesCount);
return result;
}

**Comment by DavidBruchmann** [comment]
Without having read your links I state that the following 2 lines have the same result:
1) (nodesCount * nodesCount - nodesCount)
2) (nodesCount * (nodesCount - 1))
at least for nodesCount >= 0

when I enter 5 for nodesCount:
1) (5 * 5 - 5) = 25 - 5 = 20
2) (5 * (5 - 1) = 5 * 4 = 20

when I enter -1 the results are different:
1)  (-1 * -1 -(-1)) = 1 + 1 = 2
2)  (-1 * (-1 -(-1)) = -1 * 0 = 0

**Comment by davanT420** [comment]
You are correct. The number of possible edges between n nodes is not n(n-1) btw, but n(n-1)/2.

**Comment by DavidBruchmann** [comment]
I made a fault in the last example with -1 for nodesCount:
2) (-1 * (-1 -1) = -1 * -2 = 2
if minus values are possible there you've still to verify a bit more values (-2, -3, ...)

I stumbled upon the first two formulas of your post and haven't verified the rest.
