### ISSUE TITLE
Colours in Partition Tab

### ISSUE THREAD

**Issue by ConnorHayward** [gephi/gephi#1091]
Just a small feature request.

In the partition tab, colours are automatically assigned, and the only way to customise them is by using the chart. This makes it difficult to ensure colours match over multiple graphs, if the same things are being shown. Would it be possible to add an RGB or other typed input?

**Comment by mbastian** [comment]
You can do that by right-clicking on the chart icon (the colored rectangle). The right click opens a more sophisticated color picker.
