### ISSUE TITLE
Gephi 0.82 Issues on OS X 10.10.4

### ISSUE THREAD

**Issue by dbl001** [gephi/gephi#1095]
Built from source on OS X 10.10.4.  Numerous exceptions (see trace below).

CDavid-Laxers-MacBook-Pro:application davidlaxer$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
David-Laxers-MacBook-Pro:application davidlaxer$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /Users/davidlaxer/Downloads/apache-maven-3.2.1
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
David-Laxers-MacBook-Pro:application davidlaxer$ 

David-Laxers-MacBook-Pro:application davidlaxer$ mvn nbm:cluster-app nbm:run-platform
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gephi-app 0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- nbm-maven-plugin:3.13.3:cluster-app (default-cli) @ gephi ---
[INFO] Integrity verification passed.
[INFO] Created NetBeans module cluster(s) at /Users/davidlaxer/gephi/modules/application/target/gephi
[INFO] 
[INFO] --- nbm-maven-plugin:3.13.3:run-platform (default-cli) @ gephi ---
[INFO] Executing: /bin/sh -c /Users/davidlaxer/gephi/modules/application/target/gephi/bin/gephi --userdir /Users/davidlaxer/gephi/modules/application/target/userdir -J-Dnetbeans.logger.console=true -J-ea --branding gephi --jdkhome /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
[INFO] -------------------------------------------------------------------------------
[INFO] >Log Session: Sunday, August 16, 2015 4:47:16 PM PDT
[INFO] >System Info: 
[INFO]   Product Version         = Gephi 0.9-SNAPSHOT 201403101706
[INFO]   Operating System        = Mac OS X version 10.10.4 running on x86_64
[INFO]   Java; VM; Vendor        = 1.8.0_05; Java HotSpot(TM) 64-Bit Server VM 25.5-b02; Oracle Corporation
[INFO]   Runtime                 = Java(TM) SE Runtime Environment 1.8.0_05-b13
[INFO]   Java Home               = /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
[INFO]   System Locale; Encoding = en_US (gephi); UTF-8
[INFO]   Home Directory          = /Users/davidlaxer
[INFO]   Current Directory       = /Users/davidlaxer/gephi/modules/application
[INFO]   User Directory          = /Users/davidlaxer/gephi/modules/application/target/userdir
[INFO]   Cache Directory         = /Users/davidlaxer/gephi/modules/application/target/userdir/var/cache
[INFO]   Installation            = /Users/davidlaxer/gephi/modules/application/target/gephi/bin
[INFO]                             /Users/davidlaxer/gephi/modules/application/target/gephi/etc
[INFO]                             /Users/davidlaxer/gephi/modules/application/target/gephi/gephi
[INFO]                             /Users/davidlaxer/gephi/modules/application/target/gephi/platform
[INFO]                             /Users/davidlaxer/gephi/modules/application/target/gephi/platform
[INFO]   Boot & Ext. Classpath   = /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/classes:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/System/Library/Java/Extensions/AppleScriptEngine.jar:/System/Library/Java/Extensions/dns_sd.jar:/System/Library/Java/Extensions/j3daudio.jar:/System/Library/Java/Extensions/j3dcore.jar:/System/Library/Java/Extensions/j3dutils.jar:/System/Library/Java/Extensions/jai_codec.jar:/System/Library/Java/Extensions/jai_core.jar:/System/Library/Java/Extensions/mlibwrapper_jai.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/System/Library/Java/Extensions/vecmath.jar
[INFO]   Application Classpath   = /Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/boot.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/org-openide-modules.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/org-openide-util-lookup.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/org-openide-util.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/boot_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/boot_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/boot_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/boot_zh_CN.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-modules_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-modules_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/lib/tools.jar
[INFO]   Startup Classpath       = /Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/core.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/org-openide-filesystems.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/core_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/core_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/core_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/core_zh_CN.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/Users/davidlaxer/gephi/modules/application/target/gephi/gephi/core/locale/core_gephi.jar
[INFO] -------------------------------------------------------------------------------
[INFO] WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
[INFO] INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
[INFO] 	org.openide.util.lookup [8.24.1 201403101706]
[INFO] 	org.openide.util [8.37.1 201403101706]
[INFO] 	org.openide.modules [7.42.1 201403101706]
[INFO] 	org.netbeans.api.annotations.common/1 [1.23.1 201403101706]
[INFO] 	org.openide.filesystems [8.10.1 201403101706]
[INFO] 	org.openide.awt [7.61.1 201403101706]
[INFO] 	org.netbeans.api.progress/1 [1.37.1 201403101706]
[INFO] 	org.openide.dialogs [7.36.1 201403101706]
[INFO] 	org.openide.nodes [7.38.1 201403101706]
[INFO] 	org.openide.windows [6.70.1 201403101706]
[INFO] 	org.netbeans.modules.editor.mimelookup/1 [1.35.1 201403101706]
[INFO] 	org.openide.text [6.61.1 201403101706]
[INFO] 	org.netbeans.swing.tabcontrol [1.50.1 201403101706]
[INFO] 	org.netbeans.swing.outline [1.29.1 201403101706]
[INFO] 	org.openide.explorer [6.56.1 201403101706]
[INFO] 	org.openide.actions [6.34.1 201403101706]
[INFO] 	org.netbeans.modules.queries/1 [1.38.1 201403101706]
[INFO] 	org.openide.loaders [7.56.2 201403101706]
[INFO] 	org.openide.io [1.44.1 201403101706]
[INFO] 	org.netbeans.swing.plaf [1.36.1 201403101706]
[INFO] 	org.netbeans.spi.quicksearch [1.22.1 201403101706]
[INFO] 	org.netbeans.modules.templates/1 [1.2.1 201403101706]
[INFO] 	org.netbeans.bootstrap/1 [2.67.1 201403101706]
[INFO] 	org.netbeans.core.startup/1 [1.53.1 201403101706]
[INFO] 	org.netbeans.modules.settings/1 [1.44.1 201403101706]
[INFO] 	org.netbeans.modules.sendopts/2 [2.30.1 201403101706]
[INFO] 	org.netbeans.modules.sampler [1.9.1 201403101706]
[INFO] 	org.netbeans.modules.progress.ui [1.28.1 201403101706]
[INFO] 	org.netbeans.modules.keyring [1.19.1 201403101706]
[INFO] 	org.netbeans.core/2 [3.45.1 201403101706]
[INFO] 	org.netbeans.modules.options.api/1 [1.39.1 201403101706]
[INFO] 	org.netbeans.modules.options.keymap [1.30.1 201403101706]
[INFO] 	org.netbeans.modules.masterfs/2 [2.46.1 201403101706]
[INFO] 	org.netbeans.modules.masterfs.nio2 [1.11.1 201403101706]
[INFO] 	org.netbeans.libs.jna/1 [1.35.1 201403101706]
[INFO] 	org.netbeans.modules.masterfs.macosx [1.9.1 201403101706]
[INFO] 	org.netbeans.modules.keyring.fallback [1.3.1 201403101706]
[INFO] 	org.netbeans.modules.keyring.impl [1.18.1 201403101706]
[INFO] 	org.netbeans.modules.autoupdate.services [1.45.1 201403101706]
[INFO] 	org.netbeans.modules.autoupdate.ui [1.40.1 201403101706]
[INFO] 	org.netbeans.modules.autoupdate.cli [1.8.1 201403101706]
[INFO] 	org.netbeans.core.windows/2 [2.75.1 201403101706]
[INFO] 	org.netbeans.modules.applemenu/1 [1.32.1 201403101706]
[INFO] 	org.netbeans.libs.jna.platform/1 [1.5.1 201403101706]
[INFO] 	org.netbeans.core.ui/1 [1.40.1 201403101706]
[INFO] 	org.netbeans.core.network [1.4.1 201403101706]
[INFO] 	org.netbeans.core.nativeaccess/1 [1.26.1 201403101706]
[INFO] 	org.netbeans.core.multitabs/1 [1.7.1.1 1 201403101706]
[INFO] 	org.netbeans.core.io.ui/1 [1.25.1 201403101706]
[INFO] 	org.gephi.core.library.wrapper [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.ui.library.wrapper [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.utils [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.lib.validation [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.utils.longtask [0.8.2 0.9-20150816 201508161556]
[INFO] 	org.gephi.project.api [0.8.2 0.9-20150816 201508161556]
[INFO] 	org.gephi.graph.api [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.ui.utils [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.ui.components [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.workspace.ui [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.db.drivers [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.io.importer.api [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.mostrecentfiles.api [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.desktop.project [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.welcome.screen [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.visualization.api [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.tools.api [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.gleem [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.dynamic.api [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.visualization [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.statistics.api [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.statistics.plugin [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.statistics.plugin.ui [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.settings.upgrader [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.project.ui [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.io.processor.plugin [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.processor.plugin.ui [0.8.2 0.9-20150816 201508161558]
[INFO] 	org.gephi.preview.api [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.preview.plugin [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.io.exporter.api [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.io.exporter.preview [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.preview.export.ui [0.8.2 0.9-20150816 201508161557]
[INFO] 	org.gephi.perspective.api [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.layout.api [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.layout.plugin [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.io.importer.plugin [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.io.generator.api [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.io.generator.plugin [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.io.exporter.plugin [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.import.plugin.ui [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.gephi.branding [0.8.2 0.9-20150816 201508161556]
[INFO] 	org.gephi.generator.plugin.ui [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.export.plugin.ui [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.directory.chooser [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.desktop.statistics [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.recent.files [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.progress [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.io.export [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.preview [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.desktop.perspective [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.layout [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.desktop.import [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.desktop.generate [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.context [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.branding [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.appearance.api [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.desktop.appearance [0.8.2 0.9-20150816 201508161559]
[INFO] 	org.gephi.appearance.plugin [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.appearance.plugin.ui [0.8.2 0.9-20150816 201508161600]
[INFO] 	org.gephi.algorithms.plugin [0.8.2 0.9-20150816 201508161558]
[INFO] INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Mac
[INFO] INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading failed! Trying fallback resolver.
[INFO] INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
[INFO] INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded. Fallback provider was successful.
[INFO] INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
[INFO] INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
[INFO] INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
[INFO] GL_VENDOR: NVIDIA Corporation
[INFO] GL_RENDERER: NVIDIA GeForce 9600M GT OpenGL Engine
[INFO] GL_VERSION: 2.1 NVIDIA-10.0.31 310.90.10.05b12
[INFO] Current Version is target
[INFO] WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.gephi.ui.upgrader.Upgrader.getCurrentVersion(Upgrader.java:123)
[INFO] Diagnostic information
[INFO] Input arguments:
[INFO] 	-Djdk.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
[INFO] 	-Dnetbeans.dirs=/Users/davidlaxer/gephi/modules/application/target/gephi/bin:/Users/davidlaxer/gephi/modules/application/target/gephi/etc:/Users/davidlaxer/gephi/modules/application/target/gephi/gephi:/Users/davidlaxer/gephi/modules/application/target/gephi/platform:
[INFO] 	-Dnetbeans.home=/Users/davidlaxer/gephi/modules/application/target/gephi/platform
[INFO] 	-Dcom.apple.mrj.application.apple.menu.about.name=gephi
[INFO] 	-Xms64m
[INFO] 	-Xmx512m
[INFO] 	-Xverify:none
[INFO] 	-Dsun.java2d.noddraw=true
[INFO] 	-Dsun.awt.noerasebackground=true
[INFO] 	-Dnetbeans.indexing.noFileRefresh=true
[INFO] 	-Dplugin.manager.check.interval=EVERY_DAY
[INFO] 	-Dnetbeans.logger.console=true
[INFO] 	-ea
[INFO] 	-XX:+HeapDumpOnOutOfMemoryError
[INFO] 	-XX:HeapDumpPath=/Users/davidlaxer/gephi/modules/application/target/userdir/var/log/heapdump.hprof
[INFO] Compiler: HotSpot 64-Bit Tiered Compilers
[INFO] Heap memory usage: initial 64.0MB maximum 455.5MB
[INFO] Non heap memory usage: initial 2.4MB maximum -1b
[INFO] Garbage collector: PS Scavenge (Collections=21 Total time spent=0s)
[INFO] Garbage collector: PS MarkSweep (Collections=2 Total time spent=0s)
[INFO] Classes: loaded=5976 total loaded=5976 unloaded 0
[INFO] INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 8,589,934,592
[INFO] INFO [null]: Total physical memory 8,589,934,592
[INFO] WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
[INFO] WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
[INFO] WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.home has been obsoleted in favor of InstalledFileLocator/Places at org.netbeans.Clusters.relativeDirsWithHome(Clusters.java:137)
[INFO] DATABRIDGE:
[INFO]  Removed Edges: 0
[INFO]  Added Edges: 0
[INFO]  Removed Nodes: 0
[INFO]  Added Nodes: 0
[INFO] DATABRIDGE:
[INFO]  Removed Edges: 0
[INFO]  Added Edges: 26
[INFO]  Removed Nodes: 0
[INFO]  Added Nodes: 34
[INFO] # Nodes loaded: 34
[INFO] # Edges loaded: 78
[INFO] DATABRIDGE:
[INFO]  Removed Edges: 0
[INFO]  Added Edges: 52
[INFO]  Removed Nodes: 0
[INFO]  Added Nodes: 0
[INFO] INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled
[INFO] DATABRIDGE:
[INFO]  Removed Edges: 0
[INFO]  Added Edges: 0
[INFO]  Removed Nodes: 0
[INFO]  Added Nodes: 0
[INFO] SEVERE [org.openide.util.Exceptions]
[INFO] java.lang.IllegalArgumentException: The default value type cannot be cast to the type
[INFO] 	at org.gephi.graph.store.TableImpl.checkDefaultValue(TableImpl.java:191)
[INFO] 	at org.gephi.graph.store.TableImpl.addColumn(TableImpl.java:59)
[INFO] 	at org.gephi.io.processor.plugin.AbstractProcessor.flushColumns(AbstractProcessor.java:75)
[INFO] 	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:94)
[INFO] 	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:279)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:520)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:97)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:180)
[INFO] Caused: java.lang.RuntimeException
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:183)
[INFO] [catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:273)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] java.lang.RuntimeException: java.lang.IllegalArgumentException: The default value type cannot be cast to the type
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:183)
[INFO] 	at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:273)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.IllegalArgumentException: The default value type cannot be cast to the type
[INFO] 	at org.gephi.graph.store.TableImpl.checkDefaultValue(TableImpl.java:191)
[INFO] 	at org.gephi.graph.store.TableImpl.addColumn(TableImpl.java:59)
[INFO] 	at org.gephi.io.processor.plugin.AbstractProcessor.flushColumns(AbstractProcessor.java:75)
[INFO] 	at org.gephi.io.processor.plugin.DefaultProcessor.process(DefaultProcessor.java:94)
[INFO] 	at org.gephi.io.importer.impl.ImportControllerImpl.process(ImportControllerImpl.java:279)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:520)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:97)
[INFO] 	at org.gephi.desktop.importer.DesktopImportControllerUI$3.run(DesktopImportControllerUI.java:180)
[INFO] 	... 6 more
[INFO] WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.gephi.branding.desktop.reporter.ReportController.logMessageLog(ReportController.java:284)
[INFO] Warning: Could not get charToByteConverterClass!
[INFO] 
[INFO] Response from server:
[INFO] mail sent
[INFO] SEVERE: 
[INFO] java.lang.ArithmeticException: / by zero
[INFO] 	at org.gephi.statistics.plugin.Modularity.computeModularity(Modularity.java:498)
[INFO] 	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:465)
[INFO] 	at org.gephi.statistics.plugin.Modularity.execute(Modularity.java:454)
[INFO] 	at org.gephi.statistics.StatisticsControllerImpl.execute(StatisticsControllerImpl.java:161)
[INFO] 	at org.gephi.statistics.StatisticsControllerImpl$3.run(StatisticsControllerImpl.java:147)
[INFO] [catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:273)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] 
[INFO] Response from server:
[INFO] mail sent
[INFO] Disabling snapshot
[INFO] SEVERE [global]
[INFO] java.lang.RuntimeException: Waited 5000ms for: <6b29c0b2, 6058b23d>[count 2, qsz 0, owner <AWT-EventQueue-0-Display-.macosx_nil-1-EDT-2>] - <DisplayAnimator>
[INFO] 	at jogamp.common.util.locks.RecursiveLockImpl01Unfairish.lock(RecursiveLockImpl01Unfairish.java:198)
[INFO] 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:606)
[INFO] 	at org.gephi.visualization.swing.GraphDrawableImpl.display(GraphDrawableImpl.java:251)
[INFO] 	at org.gephi.visualization.scheduler.CompatibilityScheduler$1.run(CompatibilityScheduler.java:97)
[INFO] [catch] at org.gephi.visualization.scheduler.BasicFPSAnimator.run(BasicFPSAnimator.java:34)
^CDavid-Laxers-MacBook-Pro:application davidlaxer$

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
