### ISSUE TITLE
Visualization Missing Nodes From .gexf File

### ISSUE THREAD

**Issue by nbuhagiar** [gephi/gephi#1096]
Looking into the .gexf file below, I should have 17 nodes labelled as "Retweeters".

![retweet_viz_file](https://cloud.githubusercontent.com/assets/10453145/9335665/5255a542-45a3-11e5-8ac7-6f705be329ed.png)

However, when I visualize this on Gephi, there seem to be only 9 "Retweeters" present. Any idea what the cause of this could be?

Below is a filtered visualization of my network:

![retweet_viz_visualization](https://cloud.githubusercontent.com/assets/10453145/9335678/5e51874e-45a3-11e5-86d6-3d207aa0fbf8.png)

**Comment by eduramiba** [comment]
Are there any errors in the import report tab?
How many nodes does it show in "Context" window?

**Comment by nbuhagiar** [comment]
In the 'Issues' section of 'Import Report', there are several instances of, for example, 'Unknown node id, creates node from id=`485'' for several different id numbers. It also gives a WARNING that there is an 'Undefined GEXF version. Parser 1.3 is used.'.

![import_report](https://cloud.githubusercontent.com/assets/10453145/9508445/6a5bc708-4c23-11e5-93ed-54dd2826ca1c.png)

It also shows 208 nodes in the 'Context' window.

Thank you very much for your help!

**Comment by eduramiba** [comment]
Oh, then the file is bigger than that.
Can you share your file for testing?

**Comment by nbuhagiar** [comment]
I can't seem to attach the file to this message, but the contents of the file are shown below. Thanks again for your help!

<gexf xmlns="http://www.gexf.net/1.2draft" xmlns:viz="http://www.gexf.net/1.2draft/viz">
<meta lastmodifieddate="2013-11-21">
<creator> Kevin Ryczko </creator>
<description> Social Network Visualization </description>
</meta>
<graph mode="static" defaultedgetype="directed">
<nodes>
<node id="192" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="456" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="500" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="65" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="365" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="23" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="1" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="37" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="41" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="240" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="27" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="222" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="254" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="12" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="109" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="273" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="149" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="346" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="314" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="350" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="417" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="98" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="19" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="276" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="126" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="231" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="487" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="714" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="114" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="340" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="118" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="726" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="90" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="218" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="100" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="617" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="82" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="117" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="32" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="357" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="230" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="711" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="237" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="889" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="891" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="69" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="104" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="376" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="635" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="37" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="46" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="590" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="324" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="177" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="358" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="650" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="583" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="138" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="39" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="264" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="583" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="171" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="82" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="211" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="179" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="338" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="608" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="516" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="651" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="237" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="654" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="304" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="337" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="301" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="564" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="407" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="377" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="441" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="157" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="62" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="580" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="70" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="102" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="104" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="423" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="411" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="251" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="606" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="65" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="321" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="773" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="134" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="233" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="180" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="85" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="118" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="55" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="220" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="349" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="463" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="177" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="136" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="82" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="591" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="402" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="182" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="507" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="296" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="52" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="350" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="136" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="853" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="476" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="211" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="352" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="257" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="291" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="420" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="52" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="132" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="215" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="788" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="410" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="894" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="31" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="117" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="251" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="118" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="142" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="189" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="101" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="429" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="335" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="745" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="747" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="434" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="567" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="379" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="325" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="349" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="104" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="95" label="Retweeters">
<viz:size value="2.5"/>
</node>
<node id="192" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="1" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="548" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="324" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="390" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="103" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="421" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="138" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="778" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="7" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="676" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="463" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="240" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="177" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="210" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="836" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="823" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="32" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="256" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="33" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="193" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="772" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="71" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="521" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="202" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="558" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="754" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="51" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="116" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="407" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="760" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="282" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="444" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="831" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="768" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="194" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="5" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="229" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="871" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="709" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="426" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="140" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="113" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="625" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="178" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="147" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="245" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="631" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="376" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="217" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="606" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="289" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="65" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="99" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="227" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="165" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="325" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="6" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="487" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="9" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="743" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="427" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="358" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="14" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="243" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="213" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="726" label="Non-Retweeters" >
<viz:size value="2.0"/>
</node>
<node id="5" label="Main-Tweeter" >
<viz:size value="3.0"/>
</node>
</nodes>
<edges>
<edge id="0" source="420" target="5"/>
<edge id="1" source="485" target="5"/>
<edge id="2" source="135" target="5"/>
<edge id="3" source="138" target="5"/>
<edge id="4" source="42" target="5"/>
<edge id="5" source="524" target="5"/>
<edge id="6" source="589" target="5"/>
<edge id="7" source="46" target="5"/>
<edge id="8" source="626" target="5"/>
<edge id="9" source="659" target="5"/>
<edge id="10" source="117" target="5"/>
<edge id="11" source="119" target="5"/>
<edge id="12" source="189" target="5"/>
<edge id="13" source="221" target="5"/>
<edge id="14" source="95" target="5"/>
<edge id="15" source="258" target="5"/>
<edge id="16" source="230" target="5"/>
<edge id="17" source="167" target="5"/>
<edge id="18" source="8" target="5"/>
<edge id="19" source="294" target="5"/>
<edge id="20" source="615" target="5"/>
<edge id="21" source="619" target="5"/>
<edge id="22" source="624" target="5"/>
<edge id="23" source="273" target="5"/>
<edge id="24" source="52" target="5"/>
<edge id="25" source="56" target="5"/>
<edge id="26" source="409" target="5"/>
<edge id="27" source="346" target="5"/>
<edge id="28" source="157" target="5"/>
<edge id="29" source="62" target="5"/>
<edge id="30" source="140" target="5"/>
<edge id="31" source="205" target="5"/>
<edge id="32" source="143" target="5"/>
<edge id="33" source="475" target="5"/>
<edge id="34" source="125" target="5"/>
<edge id="35" source="578" target="5"/>
<edge id="36" source="100" target="5"/>
<edge id="37" source="198" target="5"/>
<edge id="38" source="40" target="5"/>
<edge id="39" source="874" target="5"/>
<edge id="40" source="14" target="5"/>
<edge id="41" source="239" target="5"/>
<edge id="42" source="398" target="5"/>
<edge id="43" source="243" target="5"/>
<edge id="44" source="469" target="5"/>
<edge id="45" source="187" target="5"/>
<edge id="46" source="60" target="5"/>
<edge id="47" source="381" target="5"/>
<edge id="48" source="319" target="5"/>
<edge id="49" source="456" target="192"/>
<edge id="50" source="500" target="192"/>
<edge id="51" source="365" target="65"/>
<edge id="52" source="23" target="65"/>
<edge id="53" source="37" target="1"/>
<edge id="54" source="41" target="1"/>
<edge id="55" source="240" target="1"/>
<edge id="56" source="27" target="1"/>
<edge id="57" source="222" target="1"/>
<edge id="58" source="254" target="1"/>
<edge id="59" source="12" target="1"/>
<edge id="60" source="109" target="1"/>
<edge id="61" source="273" target="1"/>
<edge id="62" source="149" target="1"/>
<edge id="63" source="346" target="1"/>
<edge id="64" source="314" target="1"/>
<edge id="65" source="350" target="1"/>
<edge id="66" source="417" target="1"/>
<edge id="67" source="98" target="1"/>
<edge id="68" source="19" target="1"/>
<edge id="69" source="276" target="1"/>
<edge id="70" source="126" target="1"/>
<edge id="71" source="231" target="1"/>
<edge id="72" source="487" target="1"/>
<edge id="73" source="714" target="1"/>
<edge id="74" source="114" target="1"/>
<edge id="75" source="340" target="1"/>
<edge id="76" source="118" target="1"/>
<edge id="77" source="726" target="1"/>
<edge id="78" source="90" target="1"/>
<edge id="79" source="218" target="1"/>
<edge id="80" source="617" target="100"/>
<edge id="81" source="82" target="100"/>
<edge id="82" source="117" target="100"/>
<edge id="83" source="32" target="100"/>
<edge id="84" source="357" target="100"/>
<edge id="85" source="230" target="100"/>
<edge id="86" source="711" target="100"/>
<edge id="87" source="237" target="100"/>
<edge id="88" source="889" target="100"/>
<edge id="89" source="891" target="100"/>
<edge id="90" source="69" target="100"/>
<edge id="91" source="104" target="100"/>
<edge id="92" source="376" target="100"/>
<edge id="93" source="635" target="100"/>
<edge id="94" source="46" target="37"/>
<edge id="95" source="590" target="37"/>
<edge id="96" source="177" target="324"/>
<edge id="97" source="358" target="324"/>
<edge id="98" source="650" target="324"/>
<edge id="99" source="39" target="138"/>
<edge id="100" source="264" target="138"/>
<edge id="101" source="583" target="138"/>
<edge id="102" source="171" target="138"/>
<edge id="103" source="82" target="138"/>
<edge id="104" source="211" target="138"/>
<edge id="105" source="179" target="138"/>
<edge id="106" source="338" target="138"/>
<edge id="107" source="608" target="138"/>
<edge id="108" source="516" target="138"/>
<edge id="109" source="651" target="138"/>
<edge id="110" source="237" target="138"/>
<edge id="111" source="654" target="138"/>
<edge id="112" source="304" target="138"/>
<edge id="113" source="337" target="138"/>
<edge id="114" source="301" target="138"/>
<edge id="115" source="564" target="138"/>
<edge id="116" source="407" target="138"/>
<edge id="117" source="377" target="138"/>
<edge id="118" source="441" target="138"/>
<edge id="119" source="157" target="138"/>
<edge id="120" source="62" target="138"/>
<edge id="121" source="580" target="138"/>
<edge id="122" source="70" target="138"/>
<edge id="123" source="102" target="138"/>
<edge id="124" source="104" target="138"/>
<edge id="125" source="423" target="138"/>
<edge id="126" source="411" target="138"/>
<edge id="127" source="251" target="138"/>
<edge id="128" source="606" target="138"/>
<edge id="129" source="65" target="138"/>
<edge id="130" source="321" target="138"/>
<edge id="131" source="773" target="138"/>
<edge id="132" source="134" target="138"/>
<edge id="133" source="233" target="138"/>
<edge id="134" source="180" target="138"/>
<edge id="135" source="85" target="138"/>
<edge id="136" source="118" target="138"/>
<edge id="137" source="55" target="138"/>
<edge id="138" source="220" target="138"/>
<edge id="139" source="349" target="138"/>
<edge id="140" source="136" target="177"/>
<edge id="141" source="591" target="82"/>
<edge id="142" source="402" target="82"/>
<edge id="143" source="182" target="82"/>
<edge id="144" source="507" target="82"/>
<edge id="145" source="296" target="82"/>
<edge id="146" source="52" target="82"/>
<edge id="147" source="350" target="82"/>
<edge id="148" source="136" target="82"/>
<edge id="149" source="853" target="82"/>
<edge id="150" source="476" target="82"/>
<edge id="151" source="352" target="211"/>
<edge id="152" source="257" target="211"/>
<edge id="153" source="291" target="211"/>
<edge id="154" source="420" target="211"/>
<edge id="155" source="52" target="211"/>
<edge id="156" source="132" target="211"/>
<edge id="157" source="215" target="211"/>
<edge id="158" source="788" target="211"/>
<edge id="159" source="410" target="211"/>
<edge id="160" source="894" target="211"/>
<edge id="161" source="31" target="211"/>
<edge id="162" source="251" target="117"/>
<edge id="163" source="142" target="118"/>
<edge id="164" source="101" target="189"/>
<edge id="165" source="429" target="189"/>
<edge id="166" source="335" target="189"/>
<edge id="167" source="745" target="189"/>
<edge id="168" source="747" target="189"/>
<edge id="169" source="434" target="189"/>
<edge id="170" source="567" target="189"/>
<edge id="171" source="379" target="189"/>
<edge id="172" source="325" target="189"/>
<edge id="173" source="104" target="349"/>
<edge id="174" source="192" target="95"/>
<edge id="175" source="1" target="95"/>
<edge id="176" source="548" target="95"/>
<edge id="177" source="324" target="95"/>
<edge id="178" source="390" target="95"/>
<edge id="179" source="103" target="95"/>
<edge id="180" source="421" target="95"/>
<edge id="181" source="138" target="95"/>
<edge id="182" source="778" target="95"/>
<edge id="183" source="7" target="95"/>
<edge id="184" source="676" target="95"/>
<edge id="185" source="463" target="95"/>
<edge id="186" source="240" target="95"/>
<edge id="187" source="177" target="95"/>
<edge id="188" source="210" target="95"/>
<edge id="189" source="836" target="95"/>
<edge id="190" source="823" target="95"/>
<edge id="191" source="32" target="95"/>
<edge id="192" source="256" target="95"/>
<edge id="193" source="33" target="95"/>
<edge id="194" source="193" target="95"/>
<edge id="195" source="772" target="95"/>
<edge id="196" source="71" target="95"/>
<edge id="197" source="521" target="95"/>
<edge id="198" source="202" target="95"/>
<edge id="199" source="558" target="95"/>
<edge id="200" source="754" target="95"/>
<edge id="201" source="51" target="95"/>
<edge id="202" source="116" target="95"/>
<edge id="203" source="407" target="95"/>
<edge id="204" source="760" target="95"/>
<edge id="205" source="282" target="95"/>
<edge id="206" source="444" target="95"/>
<edge id="207" source="831" target="95"/>
<edge id="208" source="768" target="95"/>
<edge id="209" source="194" target="95"/>
<edge id="210" source="5" target="95"/>
<edge id="211" source="229" target="95"/>
<edge id="212" source="871" target="95"/>
<edge id="213" source="709" target="95"/>
<edge id="214" source="426" target="95"/>
<edge id="215" source="140" target="95"/>
<edge id="216" source="113" target="95"/>
<edge id="217" source="625" target="95"/>
<edge id="218" source="178" target="95"/>
<edge id="219" source="147" target="95"/>
<edge id="220" source="245" target="95"/>
<edge id="221" source="631" target="95"/>
<edge id="222" source="376" target="95"/>
<edge id="223" source="217" target="95"/>
<edge id="224" source="606" target="95"/>
<edge id="225" source="289" target="95"/>
<edge id="226" source="65" target="95"/>
<edge id="227" source="99" target="95"/>
<edge id="228" source="227" target="95"/>
<edge id="229" source="165" target="95"/>
<edge id="230" source="325" target="95"/>
<edge id="231" source="6" target="95"/>
<edge id="232" source="487" target="95"/>
<edge id="233" source="9" target="95"/>
<edge id="234" source="743" target="95"/>
<edge id="235" source="427" target="95"/>
<edge id="236" source="358" target="95"/>
<edge id="237" source="14" target="95"/>
<edge id="238" source="243" target="95"/>
<edge id="239" source="213" target="95"/>
<edge id="240" source="726" target="95"/>
</edges>
</graph>
</gexf>

**Comment by nbuhagiar** [comment]
Sure, you can find the see the file here:

https://github.com/nbuhagiar/miscellaneous/blob/master/retweet_viz.gexf

Thanks again for your help!

**Comment by eduramiba** [comment]
You have some duplicate ids in nodes, like for example:

<node id="177" label="Retweeters">
And later
<node id="177" label="Non-Retweeters" >

So, the last occurrence of their values is being used, and they are left as Non-Retweeters.
Maybe gexf importer should warn about duplicates.

All your Retweeters duplicated ids are:
192, 65, 1, 324, 583, 138, 463, 177

**Comment by nbuhagiar** [comment]
Oh, I didn't notice that. I'll look into it. Thanks for your help!

**Comment by eduramiba** [comment]
Great :)
