### ISSUE TITLE
Data laboratory is not working

### ISSUE THREAD

**Issue by faeza** [gephi/gephi#1097]
![gephi issue](https://cloud.githubusercontent.com/assets/11279049/9439351/8b26b8a8-4a7f-11e5-8219-a369cdc49325.PNG)

Hi
I am using Gephi 0.8.2 with java 7... it was working properly but now its data laboratory is not working.
KIndly help!
Regards

**Comment by eduramiba** [comment]
You probably closed the data laboratory window. Try to open it in Window
menu.

If the problem persists, try to remove your gephi user files(
http://gephi.github.io/users/install)

2015-08-24 12:46 GMT+01:00 faeza <notifications@github.com>:

**Comment by faeza** [comment]
Lol... Thanks, it worked.
