### ISSUE TITLE
Update visualization to JOGL 2.3.1

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1098]
Gephi 0.8.x still rely on the JOGL 1x library, which doesn't work with Java 7 or Java 8. JOGL 2x is compatible with the latest Java version and is maintained with regular releases.

Notable changes in JOGL's API:
- Rename packages to com.jogamp.*
- New NEWT canvas that runs opengl routines outside of the EDT

**Comment by techtonik** [comment]
:+1: Awesome! Thanks for pushing this project.
