### ISSUE TITLE
Remove support for hierarchical graphs

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1100]
It never was really working well and made the graph structure complicated. It should be rewritten from scratch, including the design. Removing all related features for now.

**Comment by Ninoninoninonino** [comment]
Are there alternative ways for continuing to use files that were intended for use with the hierarchical function (e.g. those from IssueCrawler)?

**Comment by eduramiba** [comment]
At the moment you will need to use Gephi 0.8.2 https://github.com/gephi/gephi/releases/tag/v0.8.2

**Comment by arnehaber** [comment]
Is it planned to readd/rework this feature in the future?

**Comment by eduramiba** [comment]
Maybe but it's not clear yet https://github.com/gephi/graphstore/pull/128
