### ISSUE TITLE
Exiting with abnormal code in Yosemite 10.10.5

### ISSUE THREAD

**Issue by glurmito** [gephi/gephi#1108]
Hello!

I've just downloaded the program and it won't start in my Yosemite 10.10.5

I'm seeing this error in the console: (org.gephi.140328[23740]): Service exited with abnormal code: 2

Any advise about how to debug it?

Thanks :-D

**Comment by eduramiba** [comment]
Probable duplicate of #748 
Please check these instructions http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/

**Comment by glurmito** [comment]
Adding manually the configuration for jdkhome in conf file it works perfectly.

Thank you so much for your help and your time. I'm closing it marking as duplicate as you suggest.
