### ISSUE TITLE
Gephi is not running

### ISSUE THREAD

**Issue by ezgielci** [gephi/gephi#1113]
I properly installed Gephi however it is not running when I open the software. After demonstrating the label of Gephi it is closed.

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
