### ISSUE TITLE
Multi-relation networks

### ISSUE THREAD

**Issue by andiracu** [gephi/gephi#1129]
Thank you very much for developing Gephi, which is truly amazing. Would it be possible to add support for multi-relation networks, i.e., networks in which the same two vertices may be connected to one another by two or more types of edges? Would it be also possible to add the option of using different vertex symbols in the same network? Thank you for the attention.

**Comment by mbastian** [comment]
Hi, multi-graph support is coming in the upcoming 0.9 release. You can have multiple edges between two nodes each with a different type/label (e.g a string or an integer). The support won't be great in the visualization (i.e. edge labels on top of each other) but that should hopefully come in a future release. At least you'll be able to import, manipulate and filter based on the edge type. For vertex symbols, we don't have some reserved type like edges but you can always use attributes and create your own type.

**Comment by andiracu** [comment]
Thank you!
