### ISSUE TITLE
Possible to just run server-side calculations?

### ISSUE THREAD

**Issue by emergingdzns** [gephi/gephi#1135]
Is it possible to use the Gephi system in an non-ui environment? What I really need is to be able to feed a bunch of data to the gephi system that normally you'd use to generate a graph, but instead I only need to be able to run the data through the HITs algorithm. I need to be able to run reports from the server.

I'm a PHP developer so I'll have to learn some Java I'm sure but it would be good if it's possible to run gephi from command line and get data dumped from gephi to an export file or something.

Would appreciate any advice on this.

Thanks!
Andrew

**Comment by eduramiba** [comment]
Hi Andrew,
The Gephi toolkit is what you need: http://gephi.github.io/toolki

**Comment by techtonik** [comment]
http://gephi.github.io/toolkit/
