### ISSUE TITLE
Is anyone working on Gephi for Java 8?

### ISSUE THREAD

**Issue by CoKieKola** [gephi/gephi#1136]
I'm using Gephi for a class but the workaround by asking students to download Java 6 is rather embarrassing. I'm looking forward to avoiding this issue coming up again.

**Comment by eduramiba** [comment]
Hi,
We are working on the next version (0.9), which includes the fix for this problem.

**Comment by DavidBruant** [comment]
Out of curiosity, what is the fix?

**Comment by jonathancardoso** [comment]
They will replace JOGL to version 2.0. See #748
