### ISSUE TITLE
Gephi installation page does not include instructions for Mac OS X Mavericks, Yosemite, or El Capitan

### ISSUE THREAD

**Issue by dhicks** [gephi/gephi#1142]
I spent the last several days trying to get Gephi to run on my laptop, running Mac OS X Yosemite.  I was having no luck until I stumbled across this blog post:  [http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/]()

The post explains that users of recent versions of Mac OS need to install a legacy version of Java, then modify Gephi's configuration file, in order for Gephi to run.  

The Gephi installation page ([http://gephi.github.io/users/install/]) does not even mention this problem, much less explain the solution.  Appropriate instructions should be added to the installation page.

**Comment by eduramiba** [comment]
Good suggestion, thank you.

I made these changes.
