### ISSUE TITLE
Gephi.app won't start from case-sensitive filesystem

### ISSUE THREAD

**Issue by hn3000** [gephi/gephi#1144]
Info.plist names the executable as "gephi" but the link under Contents/MacOS is called "Gephi". On a case-sensitive filesystem the App Bundle is shown as damaged.

**Comment by mbastian** [comment]
In which scenario one would have a case-sensitive filesystem?

**Comment by mbastian** [comment]
In any event, I fixed it but still not sure on which arch/os this is an issue.

**Comment by hn3000** [comment]
I have OS X installed on a case-sensitive partition to help me work on software that might later have to run on case-sensitive filesystems somewhere else.

**Comment by mbastian** [comment]
Ah I see, thanks for the explanation. This will be fixed in the next version then.
