### ISSUE TITLE
Gephi unable start libjogl_awt

### ISSUE THREAD

**Issue by radenjohannes** [gephi/gephi#1145]
Hey, i am mac user and i have installed java 7. but i cant open gephi, i have edit gephi.conf to change jdk path. 
But , still not working

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac
