### ISSUE TITLE
GEXF 1.3

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1152]
Let's craft a specification for the next GEXF version. Here are my thoughts:

* **Add an optional edge kind attribute**: This is the base of the property graph and defined some kind of label that defines the nature of the relationship. Unfortunately we already use type (for directed/undirected) and label (unique string for each edge) but "kind" seems clear enough.
* **Deprecated the “startopen” and “endpoint” attributes**: We want to simplify the usage of dynamics and after a quick survey it seems that these aren't really needed.
* **Add a “timerepresentation” enum in <graph>**: The value would either be “interval” or “timestamp”. Interval would the default so we’re backward compatible. This configures the way the time is represented and we choose not to mix the two so it's needs to be explicitly set.
* **Add a “timestamp” attribute to <graph>**: This allows to define a timestamp for the entire graph. That’s the corner stone of supporting collections of GEXF files where each is a slice with a timestamp value. Essentially, it means that each element in the graph exists at this timestamp. If the attribute columns are dynamic we would also set values at that time.
* As we want a “timestamp” attribute for <graph> we should revisit the meaning of the “start” and “end” attributes in <graph> as well. Right now, they define the dynamics' bounds but that could be inferred from the data as well by taking the min and max so I don't think it's very useful. Instead, it could define the interval for the entire graph like the new "timestamp" would do.
* **Add a “timestamps” attribute to node/edge**: Add an array of timestamps. Each of the element in the list should follow the format agreed on in "timeformat".
* **Add “timestamp” to <attvalue>**: Defines a unique time 't' for this attribute value.
* **Add "timezone" configuration**: Timezone can be defined as part of the timestamps themselves (e.g. 2015-01-01T13) but it should be possible to define a global timezone if this is omitted. By default, we would use the local user timestamp.
* **Add a new “hex” attribute to <viz:color>**: It would allow to use things like hex=“#FF00FF”. I would suggest to support alpha there as well.

**Comment by mbastian** [comment]
A question for the audience:

### Spells

We have the concept of <spells> to define complex topology over time (i.e. goes beyond a single start/end). Example:
```
<spells>
<spell start=”2009−01−01” end=”2009−01−15” />
<spell start=”2009−01−30” end=”2009−02−01” />
</spells>
```

I can see to alternatives to define a set of timestamps for an element:
1. Add an array of timestamps as an attribute. Example:
```
<node id=”0” label=”Hello” timestamps="[2009−01−01, 2009−01−02]" />
```
2. Follow the spell paradigm and do something like that:
```
<spells>
<spell timestamp="2009−01−30" />
<spell timestamp="2009−06−30" />
</spells>
```

To be consistent with 2. it would probably make sense then to add a timestamp attribute for a unique value. Example:
```
<node id=”0” label=”Hello” timestamp="2009−01−01" />
```

**Comment by duncdrum** [comment]
I prefer the arrays of timestamps, which makes it easier to construct the graph from other xml sources.  But i worry about the date format for non-Western sources, and historical sources (those pecksy 0 years according to historical and astrological calendars). 
Can you elaborate what speaks against arrays inside start and end attributes?
````xml
<node id="0" label="Hello" start="[2009, 2012] end="[2010, 2015]"/>
````
Can we include consistency check in the schema file to make sure that elements don't go back to the future?

what happens to edges in the second case? Would this correctly determine the degree of node0 at t2 (2010) as 1? 
````xml
<graph>
    <nodes>
        <node id ="0" timestamp="[2009, 2010, 2015]"/>
        <node id ="1" timestamp="[2009, 2010, 2015]"/>
        <node id ="2" timestamp="[2009, 2011]"/>
    </nodes>
    <edges>
        <edge id="a" source="0" target="1" timestamp="[2009, 2010, 2015]"/>
        <edge id="b" source="0" target="2" timestamp="[2009, 2011]"/>
        <edge id="c" source="1" target="2" timestamp="[2011]"/>
    </edges>
</graph>
````

**Comment by mbastian** [comment]
> But i worry about the date format for non-Western sources, and historical sources (those pecksy 0 years according to historical and astrological calendars). 

Can you add some details on this one? We follow the ISO 8601 up to milliseconds precision and I'm wondering if we're missing something.

> Can you elaborate what speaks against arrays inside start and end attributes?

To support that we would need to specifically define infinite bounds, which is something that is currently induced by ignoring a start or an end attribute. For instance, if you only define start=2009, it actually means [2009, +inf]. I also found this notation difficult to read as you sort of have two parallel arrays.

> Can we include consistency check in the schema file to make sure that elements don't go back to the future?

We're using RelaxNG for the schema definition. I'll look if something like that is possible. It would be nice to enforce that the end date should be superior to the start.

> what happens to edges in the second case? Would this correctly determine the degree of node0 at t2 (2010) as 1?

Yes, the degree would be 1 because edge "b" has no 2010 timestamp.

> while I'm at it is 0.9 scheduled to make use of the viz:shape attributes?

No, that's not currently in the works for 0.9. Still relevant but it will be added in further versions.

**Comment by DavidBruant** [comment]
It'd be cool if GEXF 1.3 were XML 1.1 documents. Not being so has been giving us a hard time https://github.com/MyWebIntelligence/MyWebIntelligence/issues/216#issuecomment-145256812

**Comment by mbastian** [comment]
@DavidBruant Thanks for the report, excuse me but I do not fully understand the problem you encountered and how XML 1.1 is the solution. Can you open a separate issue as this isn't related to GEXF 1.3. Thanks!

**Comment by mbastian** [comment]
I updated the specifications above with the addition of a **timezone** configuration.

**Comment by duncdrum** [comment]
@mbastian there was a switch from XSD 1.0 to 1.1(iso8601) with respect to the handling of year 0. Since many historical sources are using xml (eg. TEI) as input for generating a gexf graph. Since, Xquery or xslt implementations (or RDBMS xml exports) vary with regard to XSD 1.0, 1.1; users are likely to constructs a dynamic graph based on xml data that has year 0. 
I just want to raise awareness of the issue. Perfectly valid xml in one system could lead to invalid dates in gexf, which would be a a pity for those humanities scholars using it. This could be fixed via the relax schema, but I m strongly in favour to maintain support for historic dates, in dynamic gexf graphs.

**Comment by zackbatist** [comment]
It would be fantastic to have a geo-spatial component included in the new specifications. Exporting or converting graphs as spatial files has always been a pain, but this might be simplified by enabling optional fields dedicated to holding spatial information. Coordinate values pertaining to different coordinate reference systems might be best represented or stored in different forms (e.g. decimal degrees as decimal values, degrees/minutes/seconds as string values, etc), and the coordinate reference systems themselves should be specified. This might also be an opportunity to align with other geospatial standards already in place, by applying default coordinate reference systems (i.e. WGS 84) when none is specified.

I could envision a specification similar to [Geo] (http://microformats.org/wiki/geo), which is a semantic markup microformat in XML/XHTML that is widely used despite being referred to as a draft specification. I would also like to add a little disclaimer: I am not a geographer, and only have basic GIS skills, so consultation with a geographer would be advisable if moving forward with this idea.

**Comment by mbastian** [comment]
Some additional thoughts
* **idtype**: The current 1.2 specifications describe an idtype attribute one can set on graph to configure the type of element ids. This is actually something that we never implemented in the import/export and could now be done because GraphStore supports it. So I suggest to start supporting this and also add long in addition of string (default) and integer.
* **consistency between intervals and timestamps**: Both time representation should have the same feature. If we allow to define "timestamps" on elements we should also allow "intervals". Similarly if we keep the <spell> concept for intervals we should add support for timestamp spells as well.
* **slice mode**: To make the distiction between dynamic graphs contained into a single GEXF (i.e. our current 'dynamic' mode) and dynamic graphs contained in a collection of GEXF files I suggest to introduce an additional <graph> 'mode' attribute names 'slice'. The possible values are currently 'static' (default) and 'dynamic'.

**Comment by duncdrum** [comment]
Would it be possible to add an automated conversion of hierarchical graphs into collections of gexf files in the new slice mode. This would help with backwards compatibility, for people not following patch notes, and trying to open old graphs in 0.9.  Hierarchical graphs will be dearly missed :disappointed:

**Comment by mbastian** [comment]
I'm not sure I understand how hierarchical graphs could be transformed to slices. Slices are for dynamic graphs. We could imagine a backward compatibility for hierarchical graphs though by creating edges between nodes in the hierarchy. That should be possible and we could mark these edges with a special relationship label (e.g. "parent")

**Comment by duncdrum** [comment]
@mbastian having a special relationship label is pretty much what i was thinking as well. My idea was to treat the relationship between nodes and meta-nodes at different hierarchy levels as fake time slices. lvl1 = t1, lvl 2 = t2 ... .
 ````edge/@labe/="parent"```` should do the trick, and not require too much coding. I think that backwards compatibility warrants the effort.
I just have the strong feeling that this new slicing or collection of gexf files feature, could be made to replace hierarchical graphs. Even if my thoughts on how to implement this are way of.

**Comment by DavidBruant** [comment]
Should a `gephi/gexf` repo be created? Gexf specification seems to be big enough a project to deserve its own repo.

**Comment by gvegayon** [comment]
That sounds like a good idea to me. GEXF is already attracting a lot of
interest by itself (regardless of gephi) as many graph analysis tools are
including import/export capabilities using GEXF.

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by duncdrum** [comment]
I also think that it makes sense to have a separate GEXF repo

**Comment by mbastian** [comment]
I agree, I have all the relaxng source files etc. that should be made online and accessible. I'll do that soon after the release so we can have a GEXF 1.3 schema with documentation up-to-date. Would someone like to help in updating the schema files btw? I'm not familiar with RelaxNG much so there would be a learning curve for me to be able to update the schema files.

**Comment by duncdrum** [comment]
I have some (not much) relaxng experience, and would be happy to help

**Comment by mbastian** [comment]
Awesome, I'll create another ticket, closing this one as it has been implemented

**Comment by mbastian** [comment]
I created a new repository https://github.com/gephi/gexf, let's continue the discussion on this issue: https://github.com/gephi/gexf/issues/1
