### ISSUE TITLE
Nightly build teases my paranoia

### ISSUE THREAD

**Issue by blokhin** [gephi/gephi#1154]
![2015-10-21 01-27-39](https://cloud.githubusercontent.com/assets/177388/10623883/5f7c2710-7793-11e5-8005-d1d7df4b6ad9.png)

Sorry for bothering, guys, just making sure, everything is allright with the nightly build. This has happened while running the "gephi.exe".

**Comment by mbastian** [comment]
Interesting... I tracked down the issue and it seems to be related to some utility routine in the OpenGL library we're using. I'm following up with them here:
http://forum.jogamp.org/Why-is-IOUtil-testDirExec-needed-td4035542.html

**Comment by blokhin** [comment]
Confirmed at jogamp, this executable is required. False alarm, sorry.

**Comment by mbastian** [comment]
No need to be sorry, thanks for the report, we learnt something :) Too bad there isn't a solution at the moment.
