### ISSUE TITLE
Gephi XML parser fails when encountering U+0001

### ISSUE THREAD

**Issue by DavidBruant** [gephi/gephi#1164]
Related to https://github.com/MyWebIntelligence/MyWebIntelligence/issues/216#issuecomment-145256812
This issue was found in Gephi 0.8. I haven't tried on Gephi 0.9.

Try importing the following GEXF document in Gephi : 

```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2">
    <graph mode="static" defaultedgetype="directed">
        <attributes class="node">
            <attribute id="domain_title" title="domain_title" type="string"/>
        </attributes>
        <attributes class="edge">
            <attribute id="weight" title="weight" type="integer"/>
        </attributes>
        <nodes>
            <node id="n1" label="n1">
                <attvalues>
                    <attvalue for="domain_title" value="�a"/>
                <attvalues>
            </node>
        </nodes>
        <edges>
        </edges>
    </graph>
</gexf>
```

Note the funky character as attribute value, it's U+0001 (and this is where the XML parser trips).

This character is forbidden in XML 1.0 documents, but allowed in XML 1.1 documents. See https://en.wikipedia.org/wiki/Valid_characters_in_XML

**Comment by eduramiba** [comment]
It loads fine with 0.9.2-SNAPSHOT now that we detect UTF-8 encoding in the XML header https://github.com/gephi/gephi/issues/474
