### ISSUE TITLE
Graph configuration needs to be available in data laboratory

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1168]
Possibility to change:

Time representation (as long as the graph is empty)
Time format
Time zone

**Comment by mbastian** [comment]
We could potentially create a general workspace configuration panel if some other things come up

**Comment by eduramiba** [comment]
Yes, specially if the list of configs grows, for the moment only "Configuration" button exists in data laboratory.

**Comment by mbastian** [comment]
Yeah, in some way I don't like the idea of mixing datalab-related configurations such as "Visible graph only" and graph-level configuration such as time representation. But on the other hand I don't want two different places for configuration...

**Comment by eduramiba** [comment]
Right, at least these configs make some sense to be in data laboratory, where time related information will mostly be viewed.

**Comment by eduramiba** [comment]
Only support for time representation remaining
