### ISSUE TITLE
Gephi don't install, it only execute directly from the DMG image.

### ISSUE THREAD

**Issue by agabardo** [gephi/gephi#1172]
Hi all, I am new on MAC, so I am probably doing something wrong here. I am trying to Install Gephi so I can config to work with Java 6 on MAC. However, when I download the .dmg file it descompact (unzip) and show a Gephi Icon.. wich don`t work. No folder is created on the computer.
What I am missing in the instalation?

**Comment by duncdrum** [comment]
just drag the gephi icon into your application folder. If you don't have any other java installed, it should work if you double-click the icon in the application folder. If it doesn't work, make sure that you point gephi to apples java6 as described here in the issues section.

**Comment by agabardo** [comment]
Thank you, took me a while to figure that.
After doing this I was able to follow the tutorials and fix my Gephi on Yosemite…

Kind Regards
Ademir

**Comment by mbastian** [comment]
Thanks for helping out @duncdrum, closing.
