### ISSUE TITLE
Update version number on splash screen 

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi#1173]
The current 0.9-SNAPSHOT release (**THANK YOU, MATHIEU!!!**) still shows "0.8.2 beta" as version number on the splash screen.

**Comment by mbastian** [comment]
Good point, we shall definitely update that. The original graphic was done in Photoshop but I don't have Photoshop anymore :( anyone?

**Comment by jbliesener** [comment]
Do you still have the original photoshop file somewhere?

**Comment by jbliesener** [comment]
I'm working on a new GIMP-based splash screen. Almost ready, I'll be happy to provide it. Do you remember what fonts you used for the "Gephi" and "0.8.2 beta" texts?

**Comment by mbastian** [comment]
Cool, here's the photoshop file: https://www.dropbox.com/s/dk10nqh1gao5m5z/brand_final.psd?dl=0

I have a bunch of fonts associated with it, not sure which one I used but Photoshop should tell you. I can then provide the font file if needed.

**Comment by eduramiba** [comment]
I have access to photoshop and can update the old splash screen.

**Comment by eduramiba** [comment]
Non snapshot version available here https://www.dropbox.com/s/c4ztictqosvb2d8/splash09beta.png?dl=0
