### ISSUE TITLE
Labels of perspective buttons shouldn't overlap with their icon

### ISSUE THREAD

**Issue by jersub** [gephi/gephi#1176]
When the label is long enough, it overlaps with the related icon.

![perspective-labels-overlap](https://cloud.githubusercontent.com/assets/183685/10833251/dba7ab44-7e90-11e5-85a2-7bbcc03b513d.png)

Observed on current master under Linux with both Oracle JDK 7 and OpenJDK 8.

Is it observed under Windows and Mac OS as well?

**Comment by mbastian** [comment]
Probably, I think these buttons have fixed width, probably made in a hurry :/

**Comment by mbastian** [comment]
I won't have time to fix that for 0.9. Removing 0.9 milestone.

**Comment by mbastian** [comment]
Fixed as part of #2631
