### ISSUE TITLE
The workspace toolbar overlaps with the perspective buttons

### ISSUE THREAD

**Issue by jersub** [gephi/gephi#1177]
![workspace-overlap](https://cloud.githubusercontent.com/assets/183685/10833687/28957f78-7e94-11e5-9c05-2e6eb594bd9c.png)

Observed on current master under Linux with OpenJDK 8.

**Comment by mbastian** [comment]
Yeah, I suspected that.. It's hard to do this when height differs between platforms.

**Comment by mbastian** [comment]
I won't have time to fix that on my own for 0.9. I don't have a linux GUI computer anyway. Removing from 0.9 milestone.

**Comment by mbastian** [comment]
This is fixed since 0.9.3 as we use FlatLaf by default on all platforms. Closing.
