### ISSUE TITLE
This version of Gephi will not reder graphs in either the current OS X or RHEL 6 versions of the software

### ISSUE THREAD

**Issue by ajpowel** [gephi/gephi#1186]
Hello -

The current downloadable version of Gephi will not render graphs from .dot or .csv file types.  We've tried on OS X (multiple machines) & RHEL6, & no instance of the software runs.

On the OS X machine, there is this version of Java:

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

On the RHEL machine, there is this version of Java:

java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

Any help/Gephi fix up you could offer will be most appreciated!

**Comment by duncdrum** [comment]
@ajpowe this often works when I run into similar problems. E
ven with nothing rendered, can you try to export your file to gexf format? (under file -> export -> gexf (not .gephi). Does it work? or report errors?
Then close gephi, and open that file, see what happens. 
If you see no errors but still can't see a graph, you should look at the gexf file in a text or better xml editor.  Does the file look like it contains all the nodes and edges that it should. Can you validate the file?

**Comment by ajpowel** [comment]
Hi there -


I tried your suggestion w/ both .gefx & .gml formats, but neither worked : (


Any further suggestions?

Best, AJP


On 18 November 2015 at 00:15, Duncan Paterson <notifications@github.com>
wrote:

> @ajpowe this often works when I run into similar problems. E
> ven with nothing rendered, can you try to export your file to gexf format?
> (under file -> export -> gexf (not .gephi). Does it work? or report errors?
> Then close gephi, and open that file, see what happens.
> If you see no errors but still can't see a graph, you should look at the
> gexf file in a text or better xml editor. Does the file look like it
> contains all the nodes and edges that it should. Can you validate the file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gephi/gephi/issues/1186#issuecomment-157629079>.
>



-- 
Regards, AJP

**Comment by duncdrum** [comment]
@ajpowel can you open the gexf file in a text editor and see if the nodes and edges are present? Can you validate the file? 
Could you post a links to the dot and gexf files to see if we can reproduce?

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.

**Comment by ajpowel** [comment]
I did.  many thanks.  So far, it's great!

On 18 February 2016 at 15:14, Mathieu Bastian <notifications@github.com>
wrote:

> Closing old issue. Please try again with the recent 0.9.1 version and
> reopen if you still have issues. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gephi/gephi/issues/1186#issuecomment-185946502>.
>



-- 
Regards, AJP
