### ISSUE TITLE
Java warning

### ISSUE THREAD

**Issue by nccomfort** [gephi/gephi#1187]
Hi, small issue, but an easy fix: when I launch Gephi for the first time on a new machine, if I don't have Java installed, the program simply won't open. No explanation. In the next release, could you put in an error flag that brings up a message saying, "Gephi requires Java in order to run. Please install the latest version of Java" or some such? Thanks!

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
