### ISSUE TITLE
Trying to load graphml file and get "Edge types can only have a primitive type value"

### ISSUE THREAD

**Issue by Serinox** [gephi/gephi#1193]
To replicate  use the attached graph (called test.txt you'll need to rename it to test.graphml) and try to open in the Gephi 0.9 snapshot and you get a bunch of issues claiming "Edge types can only have a primitive type value" and the graph edges won't load but all of the nodes will appear.
[test.txt](https://github.com/gephi/gephi/files/44241/test.txt)

**Comment by mbastian** [comment]
Fixed in trunk. Thanks for reporting.
