### ISSUE TITLE
Gephi won't start in Windows 10

### ISSUE THREAD

**Issue by AndreasGephi** [gephi/gephi#1194]
Hi

I have installed Gephi in Windows 10 and it does not start. There is first picture saying that it is initializing and then it stops. 
Would you know how I sort this out?

Many thanks

A

**Comment by computermacgyver** [comment]
Sorry for the trouble. Please see #1188 for details on possible solutions.

**Comment by AndreasGephi** [comment]
Thank you for the prompt and helpful response!?

Andreas Andrikopoulos, PhD
Assistant Professor of Finance
Department of Business Administration
University of Aegean
8 Michalon street, 82100, Chios Island
Tel.: +30 22710 35158, Fax: +30 22710 35099, Skype: morahaza
www.ba.aegean.gr/andrikopoulos
________________________________
Από: Scott Hale <notifications@github.com>
Στάλθηκε: Σάββατο, 28 Νοεμβρίου 2015 11:10 πμ
Προς: gephi/gephi
Κοιν.: Andrikopoulos Andreas
Θέμα: Re: [gephi] Gephi won't start in Windows 10 (#1194)


Sorry for the trouble. Please see #1188<https://github.com/gephi/gephi/issues/1188> for details on possible solutions.

-
