### ISSUE TITLE
Impossible de se connecter au centre de mise à jour

### ISSUE THREAD

**Issue by Caddarik** [gephi/gephi#1196]
Bonjour,

J'ai GePhi 0.8.2 sur Windows 8.1
J'ai Java 7 (pour Gephi) et 8

Je n'arrive plus à mettre à jour Gephi.
Quand je fais :
Aide > Rechercher les mises à jour
Je vois qu'il y a 2 mises à jour (AttributesImpl et DBDriver) 
Lorsque je clique sur suivant, j'ai le message d'erreur : 
    Impossible de se connecter au centre de mise à jour

Dans les détails du message il y a : 

    Problème Réseau
    http://gephi.org/updates/official/0.8.2/attributes-0.8.2.nbm
    Certains modules d'extension n'ont pas été téléchargés. Le serveur est peut-être indisponible pour le moment. Réessayez plus tard.

De plus sous l'onglet Plugins il y a marqué : "Vide"
Alors que j'ai des plugins installés

**Comment by Caddarik** [comment]
Je précise que j'essaye depuis plusieurs jours

**Comment by HTrotignon** [comment]
Same kin of issue here.
I'm working on unix, everything was fine, but connection fails since about a week ago.

> Impossible de se connecter à Gephi Thirdparties Plugins. Cause : http://gephi.org/updates/thirdparty/0.8.2/catalog.xml

can't connect to gephi updates as well.
Is it related to the future release of gephi 0.9 ?

**Comment by mbastian** [comment]
This is fixed, it was related to domain configuration changes. Thanks for report.

**Comment by giannetti** [comment]
Hi there,
I'm getting a similar error with the new update URL you mention above: 

> Unable to connect to the New Provider because of Server returned HTTP response code: 403 for URL: http://gephi.org/updates/official/0.8.2/

Thoughts?

Thank you!
Francesca

**Comment by eduramiba** [comment]
Hi,
Unfortunately there are problems with https and github that make the old 0.8.2 URL not work, even though it's still correct.

Try adding these URLs to your Gephi 0.8.2 update center (Tools - Plugins - Settings - Add):
https://raw.githubusercontent.com/gephi/gephi/gh-pages/0.8.2/updates/catalog.xml
https://raw.githubusercontent.com/gephi/gephi-plugins/gh-pages/plugins/0.8.2/catalog.xml

**Comment by giannetti** [comment]
Thanks, Eduardo! Those URLs work for me.

**Comment by niz09ar** [comment]
Eduaramiba, you're the best !

**Comment by theWayofthecode** [comment]
This solved the problem for me. Thanks!
