### ISSUE TITLE
Graph pdf and svg export problem

### ISSUE THREAD

**Issue by Basosa** [gephi/gephi#1197]
I am using the visualization plugin and when I export a graph into pdf format, nodes don’t appear. I have the same issues with svg files export.

Can someone help me?

Thanks in advance

**Comment by computermacgyver** [comment]
Could you please indicate:
* What version of Gephi are you using?
* What operating system are you using?
* What version of Java is installed?

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.

**Comment by annmclark** [comment]
Hello -

I am having this exact same problem - the nodes disappear when I export to PDF and/or SVG.  Nodes do appear on PNG files.

[test12.pdf](https://github.com/gephi/gephi/files/1171216/test12.pdf)
![test10](https://user-images.githubusercontent.com/25087960/28544799-61fe5b8a-7079-11e7-8dcc-dc001c367933.png)

I'm using the following:

Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_141; Java HotSpot(TM) Client VM 25.141-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_141-b15
System: Windows 10 version 10.0 running on x86; Cp1252; en_US (gephi)
User directory: C:\Users\aclark\AppData\Roaming\.gephi\0.9.1\dev
Cache directory: C:\Users\aclark\AppData\Roaming\.gephi\0.9.1\dev\var\cache

Many thanks for any help you can give me.
