### ISSUE TITLE
Error loading edge weights

### ISSUE THREAD

**Issue by tom-christie** [gephi/gephi#1201]
I'm trying to load edges from a CSV file that looks like:

```
Source,Target,Type,Weight
A,B,Undirected,0.5
A,C,Undirected,0.666666666666667
A-D,Undirected,0.5
A,E,Undirected,0.428571428571429
...
```

The edge weights all show up as 1.  When I don't include the 'Type' column, they still show up 1 but as directed edges, but in that case if I load the spreadsheet a second time the weights update. Unfortunately the 'load a second time' hack doesn't work if I have the 'Type' column, meaning I can't have weights with undirected edges.

**Comment by eduramiba** [comment]
Fixed for 0.9.2
