### ISSUE TITLE
Gephi won't load on Yosemite 10.10.5

### ISSUE THREAD

**Issue by CyeCandy** [gephi/gephi#1202]

**Comment by computermacgyver** [comment]
Hi CyeCandy. What version of Gephi are you using and what version of Java do you have installed?

If you are using v0.8.2, you probably need to install Java 6 as noted on the install page. [The instructions here are for Leopard](http://gephi.org/users/install-java-6-mac-os-x-leopard/) and [the instructions here are for Mavericks](http://sumnous.github.io/blog/2014/07/24/gephi-on-mac/) but should give you some idea of what is needed for Yosemite.

Alternatively, you can try out the alpha/development version of Gephi (version 0.9) that is linked on the homepage of this GitHub repository. Please note, however, that as a development version it may have some bugs.

**Comment by CyeCandy** [comment]
Hi,

I'm using v0.8.2. I have tried the java workaround with no luck. I'll 
give version 9 a go.

Thanks for your help,

Julia

**Comment by CyeCandy** [comment]
Version 9 works - thanks!

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.
