### ISSUE TITLE
Partition Update

### ISSUE THREAD

**Issue by JoeViavattine** [gephi/gephi#1204]
Pre-import situation:  I had a network open with some partitions.  The nodes were partitioned by color.  I was using one of the partitions in a filter.  The partition folder was open in the filter tree.
Import: I imported some additional nodes along with a new attribute to indicate which were new nodes.
Post-import: The partition folder did not update with the new partition.  I opened the partition count folder in the filter tree and it had updated with the new partition attribute.
File close/open: A file save/close/open did refresh the partition folder in the filter tree.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
