### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by francescomolinari** [gephi/gephi#1212]
Hi, while trying to install Gephi on a MacBook OSX El Capitan 2,9 GHz Intel Core i7 I get the following error: Unable to load libjogl_awt.jnilib
Please advise, thanks
FM

**Comment by computermacgyver** [comment]
What version of Gephi are you using?

**Comment by francescomolinari** [comment]
I was trying to install 0.8.2 but the problem was solved with 0.9 - thanks
