### ISSUE TITLE
[0.9 nightly] Welcome window won't close on Linux

### ISSUE THREAD

**Issue by boogheta** [gephi/gephi#1216]

**Comment by computermacgyver** [comment]
Thank you for the report. Can you confirm what version of Java you have installed?

**Comment by boogheta** [comment]
I started it with --jdkhome /usr/lib/jvm/java-7-openjdk-amd64/

**Comment by mbastian** [comment]
Can't reproduce (don't have Linux GUI handy). But I tried something, please test again (in 15 minutes when the build has generated).

**Comment by jersub** [comment]
Can't reproduce before and after the fix, with both java-7-openjdk-amd64 and java-8-openjdk-amd64. I'm running Arch Linux with X11 + GNOME 3.

What's your Linux distribution and your desktop environment?

**Comment by boogheta** [comment]
Doesn't reproduce on mine either anymore
