### ISSUE TITLE
[0.9 nightly - Mac] Empty Nodes tab in Graph Window flyer menu

### ISSUE THREAD

**Issue by diegoantolinosbasso** [gephi/gephi#1220]
In the Macintosh version, in the graph window pane, when the menu on the bottom side of the window is unfolded, the "Nodes" tab is empty. "Label", "Edges" and "Global" are ok.

"Le menu nodes en bas, il est vide purée"

![headshots 2015-12-15 at 12 06 15](https://cloud.githubusercontent.com/assets/9825192/11809032/4cf3cbe0-a324-11e5-8c4c-5270cabd2a9e.jpg)

**Comment by mbastian** [comment]
That's actually a feature, not a bug :) It turns out that we removed the support for node models (3d, 2d) so there isn't just anything to configure yet. I'll either remove it or add something else.

**Comment by mbastian** [comment]
Ok, I remove it. Thanks.
