### ISSUE TITLE
[0.9 nightly - Mac] Colors in appearance window

### ISSUE THREAD

**Issue by diegoantolinosbasso** [gephi/gephi#1221]
Appearance of nodes and edges doesn't pre-calculate colors

**Comment by mbastian** [comment]
Can you be more precise? Thanks.

**Comment by diegoantolinosbasso** [comment]
I'm sorry.

In the appearance window, when mapping colors onto discrete type of either edges or nodes, the colors proposed are all 100% black. I still can change the color of a category by clicking. Yet there used to be a fancy palette of colors proposed on each refresh of categories.

**Comment by mbastian** [comment]
This is fixed, thanks for the suggestion.
