### ISSUE TITLE
No suitable driver found for jdbc:mysql://dbhost.com:3306/database_name

### ISSUE THREAD

**Issue by geekan** [gephi/gephi#1225]
#### Problem
I check those urls:
http://forum.gephi.org/viewtopic.php?t=2387
https://github.com/gephi/gephi/issues/789
https://github.com/gephi/gephi/issues/720
But "Help > Check for updates" not works, I check it and find "nexus.gephi.org" is gone, it says the url cannot be resolved.

Both tried with 0.8.2 and 0.9.

#### Update
Run with admin permissions could fix it. (win10)

**Comment by mbastian** [comment]
Hi, can you tell me the exact steps to reproduce this? Much appreciated

**Comment by geekan** [comment]
1. Download the *.exe installer and install it (on my win10)
2. Open it and and click "Help > Check for updates", and it says:  
    Checking for updates failed.  
    Check your network connection, verify that your proxy settings are configured correctly, or try again later.
3. Click "Tools > Plugins > Check for updates", and it says:
     Unable to connect to the Gephi Update Center because of Server returned HTTP response code: 500 for URL: http://nexus.gephi.org/nexus/content/repositories/snapshots/external/updates/updates.xml  
    Check your proxy settings or try again later. The server may be unavailable at the moment. You may also want to make sure that your firewall is not blocking network traffic.

**Comment by geekan** [comment]
I also try to get the url from a linode vps, but wget says its dns cannot be resolved.

**Comment by mbastian** [comment]
ok, but what does this have to do with mysql, I don't understand. The issue with the updates is unrelated to that.

**Comment by geekan** [comment]
You are right. This issue may be caused by dns, but I'm just trying to use gephi with mysql. :)
However, this error may block every new user trying to use gephi with mysql, isn't it?

**Comment by geekan** [comment]
A bit more procedure:  
I just download the software with both versions, and I find they both say "No suitable driver", then I find the old posts and try to get all available updates to fix it, however, the updates cannot be reached now because of dns issue..

**Comment by mbastian** [comment]
Sorry, but can you explain where this "No suitable driver" appears, what are the steps to get to that message?

**Comment by eduramiba** [comment]
I think 0.8.2 was released with the driver problem, and we published an update to fix it. But if the update center does not work they can't get the update.

**Comment by geekan** [comment]
Thanks!
I find the problem is caused of not using "admin permissions" in windows 10.
Run it with admin permissions will solve this problem.

BTW, I prefer gephi ask for "admin permissions" by default.
