### ISSUE TITLE
Gephi 0.8.2 beta does not run on OSX ElCapitan

### ISSUE THREAD

**Issue by jansbachelor** [gephi/gephi#1229]
Gephi 0.8.2 beta does not run on OSX ElCapitan - everytimes I start the exec gephi is loading changed objects and the icon appears in the dock but after same seconds the icon will disappear with no error message.

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac
