### ISSUE TITLE
Can't connect to thirdparty plugin repository

### ISSUE THREAD

**Issue by bgrayburn** [gephi/gephi#1237]
I get the following error when clicking check for updates from the plugins dialog. Not sure what could be causing this don't have any firewalls or anything set up. Any idea?
![image](https://cloud.githubusercontent.com/assets/3170676/11903850/1dfc461a-a58a-11e5-89b1-1193c54082da.png)

**Comment by amalic** [comment]
I have the same problem. When I visit the url via a browser I only get following xml-content.

`<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE module_updates PUBLIC "-//NetBeans//DTD Autoupdate Catalog 2.5//EN" "http://www.netbeans.org/dtds/autoupdate-catalog-2_5.dtd">
<module_updates timestamp="00/00/0/01/01/1970"></module_updates>`

I guess, the update site is broken.

**Comment by michaele4321** [comment]
I'm seeing the same problem. There are plugins that should be appearing but it seems the process that generated the autoupdate xml file is not working?

**Comment by michaele4321** [comment]
Just in case someone else has the same problem and reads this. It is possible to manually install plugins. See https://marketplace.gephi.org/how-to-install-a-plugin/ for instructions.

**Comment by IntoTheDigital** [comment]
I am seeing this exact same problem too.  Any updates?  I was hoping to teach Gephi to my students in the New Year, but at this rate I may have to cancel the class until these issues are fixed.  A shame, as it looks promising...

**Comment by eduramiba** [comment]
Plugins catalog is now hosted on github and an https problem makes it not possible to connect from 0.8.2. Not sure if it can be fixed for 0.8.2 without a new release.

You can still download them manually at https://marketplace.gephi.org

**Comment by IntoTheDigital** [comment]
Thanks @eduramiba I'm afraid my IT department refuses to install 0.8.2 because they don't want to use older versions of Java SDK.  Thus, I'm completely reliant on the new 0.9.1 beta, and while these issues persist this will cause problems... I'll wait a bit and see if things get better...

**Comment by eduramiba** [comment]
Closing old issue. Workaround for 0.8.2 explained at https://github.com/gephi/gephi/releases/tag/v0.8.2
