### ISSUE TITLE
Attributes not appearing in Size setting

### ISSUE THREAD

**Issue by swainjo** [gephi/gephi#1242]
Steps to replicate:

- Open attached .graphml file
- On Appearance tab select colour and drop down Attribute List - confirm PageRank in the dropdown
- Switch to Size tab and drop down Attribute List - PageRank not in list (along with other Attributes)

This works in previous version of Gephi with same file.

[MeatFreeDec16Dec16_94weak.graphml.zip](https://github.com/gephi/gephi/files/68394/MeatFreeDec16Dec16_94weak.graphml.zip)

**Comment by oxygala** [comment]
I am having the same issue. Eigenvector centrality does not appear under Attribute List of Size tab.

**Comment by FranciscoGutierrez** [comment]
Same issue but with betweenness and closeness centrality.

**Comment by jo-tud** [comment]
I still have this issue with custom node attributes. The attribute is visible in the data lab. It can be used for color but not for size of nodes. I'm using the latest snapshot (0.9.2).

**Comment by mvelasco93** [comment]
same as @jo-tud 
I have a numerical column which I want to use as the size of the node but it doesn't appear (only the statistical data appears)
