### ISSUE TITLE
Edge weights are not read (Gephi 0.9)

### ISSUE THREAD

**Issue by amsuarez** [gephi/gephi#1243]
Windows 7, Gephi 0.9

Given the following nodes file: 

id | label
------------ | -------------
 1 | bob
2 | mary

And the following edges file:

id|source|target|weight
---|---|---|---
1|1|2|0.93

The weight is read in as 1.0 irrespective of whether the "weight" field is checked on import. 

Full Gephi and System information below:
Product Version: Gephi 0.9.0 201510222201
Java: 1.8.0_65; Java HotSpot(TM) Client VM 25.65-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_65-b17
System: Windows 7 version 6.1 running on x86; Cp1252; en_US (gephi)

**Comment by amsuarez** [comment]
Issue reproducible on OSX within the following configuration.
Product Version: Gephi 0.9.0 201510222201
Java: 1.8.0_66; Java HotSpot(TM) 64-Bit Server VM 25.66-b17
Runtime: Java(TM) SE Runtime Environment 1.8.0_66-b17
System: Mac OS X version 10.7.5 running on x86_64; UTF-8; en_US (gephi)

**Comment by eduramiba** [comment]
Thanks for the report, working on a fix for this.
