### ISSUE TITLE
CSV import only show one node

### ISSUE THREAD

**Issue by yjm12321** [gephi/gephi#1247]
Hi, all, 

I'm new to the gephi, I run gephi 0.9.0 in windows and load csv file(include node and edge), but if only shows one node, without any edge. I try to open the Java.gexf(gephi gived) and output it in csv file format, and new a project to reload the csv, and it also don't work, How should I configure it? Or it's a bug in load csv file? I used gephi 0.8.2 and it's okay in this problem.

Hope you can help me . Thank you!

**Comment by eduramiba** [comment]
Can you upload the files to reproduce this?

**Comment by eduramiba** [comment]
Ok, it's not that only one node gets imported, but that all nodes are created in position 0, 0 and with the same size.
When visualizing this, it gives the impression that there is only one node, but if you check data laboratory, all the data is there.

Also, some layouts like force atlas 2 will fail if all node have a 0, 0 position (known old issue)

Proposed solution: add nodes to random coordinates instead of 0,0.
Current workaround: apply the random layout in overview.

**Comment by ghostlayer** [comment]
Hi,

I have the same problem. Tried on Mac El Capitan, Win7 and Win10. Gephi 8.2 was installed before, but fully removed on all OS. Opening Gexf files works. Problem happens with manual laboratory input and importing csv files. Workaround confirmed eduramiba. Only the random layout will solve the problem. Other layouts will fail and even closing and re-opening projects will fail till a full gephi restart.
[karate club table edges.csv.txt](https://github.com/gephi/gephi/files/69476/karate.club.table.edges.csv.txt)
[karate club table nodes.csv.txt](https://github.com/gephi/gephi/files/69477/karate.club.table.nodes.csv.txt)
![screenshot centered nodes](https://cloud.githubusercontent.com/assets/13457361/11952162/9ea3f4e8-a896-11e5-9797-cb979f997db7.png)

**Comment by eduramiba** [comment]
Great, note that after applying random layout then you will be able to apply any other layout normally.

**Comment by yjm12321** [comment]
Thank you for your good suggestion. I have solved it.

**Comment by FranciscoGutierrez** [comment]
Yes, applying a random layout seems to fix temporarily this problem. Many thanks.

**Comment by michael-imbeault** [comment]
Long term Gephi user and this one confused me for a good 5 min, it should be reverted to a random layout as in 0.8.2.

**Comment by eduramiba** [comment]
Yes this will be released in a hotfix soon.
