### ISSUE TITLE
Gephi 0.9 won't start

### ISSUE THREAD

**Issue by Schec** [gephi/gephi#1252]
I have Windows 7, Java 8 update 66 (two installations, one is labeled "64-bit"), and Gephi 0.9.0. I installed the Java and Gephi today.

When I try to open Gephi, the splash screen seems to get stuck at the Starting Modules... stage.

Attached is (I think) my log file.  Could you help me figure out what's going on here?

Thanks!

Jody

[messages.txt](https://github.com/gephi/gephi/files/87709/messages.txt)

**Comment by jotatx** [comment]
same issue.

**Comment by joffutt892** [comment]
Same problem.  not sure how to show log file or I would.  it's been sitting at "starting modules" for over 10 minutes.  I have gephi 0.9, java 8u66, win7 Enterprisex64

**Comment by danieldfjug** [comment]
same problem here

**Comment by eduramiba** [comment]
Tracking at #1631
