### ISSUE TITLE
SQL Server Connection Drivers

### ISSUE THREAD

**Issue by eerwee** [gephi/gephi#1255]
Hi Guys. Used the SQL Server divers a lot with 0.8 but this functionality seems to have been dropped. Any reason why? Any chance it may come back? 

Apologies if this is in the wrong place ,, don't have much experience with GITHUB

Thanks a lot

**Comment by mbastian** [comment]
Hi, in the last release we've decided to remove proprietary drivers SQL Server and Teradata as we had some trouble with the latter. The plan is to remove them from the release but create plugins for each, which is something easy to do. No ETA for that at this point.

**Comment by WormyOne** [comment]
Great work on the Gephi project generally; I'm delighted to see that despite things being quiet, effort was going into 0.9/0.91.

Like the OP, I had a workflow that entailed connecting to SQL Server;  I'd love to be able to get back to this in 0.91.  Any update on an ETA for core or plugin support?

Thanks

**Comment by eduramiba** [comment]
Will be addressed in #1648
