### ISSUE TITLE
Any node and edge label in preview window cannot display and output.

### ISSUE THREAD

**Issue by AssassinJY** [gephi/gephi#1260]
In 0.9.0 version，any node and edge label in preview window cannot display and output in my own projects。But the sample projects built-in are normol.

Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 10 version 10.0 running on amd64; GBK; en_CN (gephi)

**Comment by Yong2Zhang** [comment]
Hi, I met the same problem. 
This problem might be caused by the structure of NODES' file. If you built a "Lable" colum in your CSV talbe, you should copy values to  the default lable colum when you import the Node table to gephi 0.9. Good luck!
