### ISSUE TITLE
Can't update, connection errors

### ISSUE THREAD

**Issue by edh649** [gephi/gephi#1261]
I was having errors with weights not being imported when importing an edge .csv file. I read on another issue report that the fix is to update however it is not possible for me to update to the latest version.

Help > Check For Updates: gives the error 'Checking for updates failed.'
Tools > Plugins > Check For Updates: gives the error 'Unable to connect to the Gephi Update Center because of Received fatal alert: close_notify'.

Gephi 0.9.0 (as downloaded from Gephi website. No additional Plugins)
Windows 7 Home Premium 64-Bit

**Comment by mbastian** [comment]
Should be fixed now. Thanks.
