### ISSUE TITLE
Edges weight disappear

### ISSUE THREAD

**Issue by MartijnvanLaar** [gephi/gephi#1264]
While importing simple data, edges weight seem to disappear in 0.9.0, while this does not happen in 0.9-SNAPSHOT. In our data, multiple edges occur multiple times, but only unique edges are imported, ie. that avg degree and avg weighted degree are the same. See an example of our data below, together with the output of degree and weighted degree per node. 

[Bugreport example weighted degree.xlsx](https://github.com/gephi/gephi/files/77038/Bugreport.example.weighted.degree.xlsx)

[Bugreport example data.xlsx](https://github.com/gephi/gephi/files/77035/Bugreport.example.data.xlsx)

**Comment by MartijnvanLaar** [comment]
Seems to be underway in 0.9.1.

**Comment by inchiki** [comment]
I'm finding that importing an edge list from CSV in 0.9.0 stops the import at the first duplicate edge (instead of incrementing edge weight +1)

**Comment by mbastian** [comment]
Hi, can you please let us know if this bug still occurs in 0.9.1? Thx

**Comment by eduramiba** [comment]
There is currently an issue with edge weight summing in 0.9.1 spreadsheet import. See my comment https://github.com/gephi/gephi/issues/1251#issuecomment-190250518

**Comment by inchiki** [comment]
I think that other comment thread covers it now, thanks.

**Comment by eduramiba** [comment]
Closing old issue, fixed in #1251
