### ISSUE TITLE
Plugins update on 0.9

### ISSUE THREAD

**Issue by dnet5** [gephi/gephi#1265]
Hi,
I'm just wondering how the plugins wil be 'ported' to 0.9. By developers of each plugin or by gephi team?

I need Gephi Streaming fully functional again =/ Actually, I'm using 0.8.2 until it's ported to 0.9.

ps: just mailed the developer. If he answer me, I'll update this post.

Thanks in advance!

**Comment by mbastian** [comment]
We'll communicate on that shortly. I'm updating the tooling to make the migration easier and I'm close from finishing. After that, we'll invite plugin developers to migrate to 0.9, and we'll provide help. This gives some good context btw: https://gephi.wordpress.com/2015/12/16/plugin-development-gets-new-tools-and-opens-up-to-the-community/

**Comment by dnet5** [comment]
Thanks you, @mbastian. I'll keep an eye on that =)

BTW, I'm reading the post about the plugins. Congratulations for the improvements. I look forward to use this new platform and tools.

Regards!

**Comment by mbastian** [comment]
@panisson Is working on adapting the graph streaming plugin. Otherwise, we've send the following communication (http://us12.campaign-archive2.com/?u=76071fda34ad7c0c0195c2d3d&id=5d099e069d) to plugin devs and are working on resolving issues as they arise. Closing.

**Comment by dnet5** [comment]
Great! Thank you, @mbastian!
