### ISSUE TITLE
Graphical Issue with Labels in the Graph Area

### ISSUE THREAD

**Issue by sowi-it** [gephi/gephi#1268]
Hi Together

We have an issue with the Labels in gephi: While zooming out, a few of them turns to grey and then, when we're zooming out further, dissapears completely. When zooming in again, they become grey and later black (as it should be) again. Image for description: ![gephi_greyletters](https://cloud.githubusercontent.com/assets/16576785/12144032/3fb7470a-b485-11e5-8756-e5bef320f00e.png)

The problem appears on 2 different Computers.

The first Computer:
GPU: Intel HD4600 with the (newest) driver Version 10.18.14.4264. The GPU Supports OpenGL 4.3.

The second one is a laptop:
GPU: Intel HD5500 with the newest driver Version 15.36.28.4332. The GPU Support also OpenGL 4.3

On both runs Windows 7 Enterprise 64bit with the actual Java 8.66 Version. 

On another PC (specs like the first one), gephi runs absolutely fine.

By the Way: i would have posted this in your forum, but there is a problem with the registration: We cant registrate us there, because our IP is blacklisted.  I tested it from the net of my university and with my smartphone (on the Phone-net), both resulting in blocking and displaying the "your IP" with one assigned to cloudflare... 

Greetings 
Michael Schmid
University of berne

**Comment by jbliesener** [comment]
I was observing the same behavior, and it seems to be a memory issue and only occurred on bigger graphs or when the available memory was low due to many programs running. Can you try to increase Java memory a bit in gephi.conf and/or close some other programs and see what happens?

**Comment by sowi-it** [comment]
Hi jbliesener. Thx for the prombt answer. Unfortunately, the Memory increase doesn't help. Also the problem occures on any project, not only the big ones. It appears for example in the les Miserables demo project.

Any other suggestions?

**Comment by sowi-it** [comment]
We solved this problem by installing the old Gehpi 8.2 Version and Java 7.79.
