### ISSUE TITLE
screenshot in overview: Dialog shows "Saved in {0}"

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#1271]
When saving a screenshot, the confirmation dialog after the saving is done says:

"Saved in {0}"

-> need the path to the folder instead

minor bug ;-)

**Comment by eduramiba** [comment]
Is this with the camera button?
I get "Screenshot saved to ''the_file_name''"

**Comment by seinecle** [comment]
On my Gephi version localized in French, with the camera button indeed:
![image](https://cloud.githubusercontent.com/assets/1244100/12147467/54bf5f84-b499-11e5-8d37-645b4a22d645.png)

**Comment by eduramiba** [comment]
Oh, the apostrophe in the french translation isn't well escaped.

It should read Capture d'écran enregistrée dans...

I will fix it in https://www.transifex.net/projects/p/gephi for next release
Thanks for the report!
