### ISSUE TITLE
Color coding nodes/edges by label in Gephi 0.9? 

### ISSUE THREAD

**Issue by jkfitzg** [gephi/gephi#1273]
Hello, 

There doesn't appear to be a way to color code nodes or edges by their labels. In the previous version I did this by partitioning by label. In 0.9, I tried Appearance -> Attribute, but only Degree is an option. 

Thanks, 
Jamie

**Comment by fregolente** [comment]
I am having the same problem.

**Comment by SharanyaVR** [comment]
I am also having the same problem

**Comment by mbastian** [comment]
That's right. Workaround would be to duplicate the label column in Data Laboratory, right?

**Comment by eduramiba** [comment]
Same as #1275 Workaround is correct.
