### ISSUE TITLE
gephi forum problems

### ISSUE THREAD

**Issue by ghostlayer** [gephi/gephi#1274]
The forum on forum.gephi.org is using the lookup tool from http://www.ahbl.org/ to authenticate new forum users. This lookup tool is no longer available and will always return positive results on all IP's. It is not possible to register on the forum for new users, because of that. See: http://www.ahbl.org/lktool
and http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st.

Not sure if the forum is monitored, because spam messages seem to appear at the moment.

**Comment by mbastian** [comment]
Duplicate #1047
