### ISSUE TITLE
Color nodes according to a label

### ISSUE THREAD

**Issue by fregolente** [gephi/gephi#1275]
Please, how can I color the nodes according to the node's label?

thanks a lot
d.

**Comment by seinecle** [comment]
Hi,
A plugin I developed in Gephi 0.8 was doing something similar: 
https://marketplace.gephi.org/plugin/give-color-to-nodes/

I am going to update it for 0.9 but there is no timeline for this.

**Comment by inchiki** [comment]
I would love that plugin to work with Gephi 0.9.0 :)

**Comment by annak820** [comment]
me too! Very much looking forward to this in 0.9!

**Comment by eduramiba** [comment]
It's possible to duplicate the label column in data laboratory and use the now column in Appearance.
