### ISSUE TITLE
Mac bug stuck after going from data library to overview/preview

### ISSUE THREAD

**Issue by thierryvb** [gephi/gephi#1276]
This is a bug on Gephi Mac 0.9.0
I get stuck after going from data library to overview or to preview. Doesn't matter which file or what's in the data even if it's empty..

**Comment by Nyzl** [comment]
i'm also having this issue. Moving from the Data Lab to Overview causes the application to hang indefinitely.
Using OSX 10.11.2

**Comment by HLavoix** [comment]
I have the same problem, on OSX 10.9.5
Trying to go from data laboratory or preview to overview causes a "application not responding" problem (need to force quit)... I am glad I kept Gephi 0.8 :)

**Comment by chaoqing** [comment]
Same problem here. Gephi 0.9.0 with OS X 10.11.3 and JDK 1.8.0_60.

**Comment by mbastian** [comment]
This has been fixed in 0.9.1. Closing.
