### ISSUE TITLE
Tutorial for 0.9?  Where is partition?

### ISSUE THREAD

**Issue by lkettle** [gephi/gephi#1278]
I can't find a lot of features shown in your tutorial based on 0.7 
I have 0.9.  
How can I get partition stuff?
linda.kettle@uoit.net

**Comment by seinecle** [comment]
You can find it in the "Appearance" tab, where "ranking" and "partition" can be found by selecting the "Attribute" tab.
I suggest to ask this sort of questions on the Facebook group of Gephi (https://www.facebook.com/groups/gephi/), where you'll get quicker responses.
