### ISSUE TITLE
Data laboratory - Convert column to dynamic does not accept timestamps, only dates

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1283]
Need to use parseDateTimeOrTimestamp from Graphstore API

**Comment by eduramiba** [comment]
Fix this when a graphstore release includes commit https://github.com/gephi/graphstore/commit/a1abfc4381b62a654a94af844bcfda95e3fdc43e

**Comment by vcucu** [comment]
> parseDateTimeOrTimestamp

Can you please elaborate further on how to convert timestamp into a format that is recognized as dynamic? 
I imported the data using the ISO format and it is recognized as date and time. Is it maybe possible to preprocess the data in Python such that it will be recognized as dynamic by gephi?
Snapshot of my table:
![image](https://user-images.githubusercontent.com/26205022/51129225-321d8800-182a-11e9-9835-9800cc875464.png)

**Comment by eduramiba** [comment]
Hi, check https://gephi.org/users/supported-graph-formats/spreadsheet/ for dynamic format examples.
When importing a spreadsheet, it will detect the column type as dynamic if the format is correct.
