### ISSUE TITLE
Geo Layout plugin not working in Gephi 0.9

### ISSUE THREAD

**Issue by elvitaluz** [gephi/gephi#1285]
When running the Geo Layout, the network disappears and nothing is shown, even after changing the layout style.

You can find my network file here:
https://www.dropbox.com/s/n1l4trug8k5qdum/GeoLayout_network_citing.graphml?dl=0

**Comment by mbastian** [comment]
Hi, I've looked at your problem and it seems that the position calculation becomes invalid because some of your nodes have latitude over 90 or under -90. The code behaves normally otherwise.

**Comment by elvitaluz** [comment]
Actually, I've just confirmed that it only disappears when the default "Mercator" projection is selected.
If I choose any of the others, the graph does show up.

**Comment by mbastian** [comment]
That's because the center uses the averages, which ended up being NaN as well because some values are NaN. It actually doesn't display normally as some of the incorrect nodes aren't displayed.

**Comment by leninja** [comment]
Hi, 
I am facing a problem when running the Geo Layout in the Gephi 0.9 (I am using Windows 7 Entreprise ). 

When I choose the Geo Layout in Gephi (I left everything in default --> Scale: 1000; Projection: Mercator), and clicked in Run, I received the following message:

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
	at org.gephi.plugins.layout.geo.GeoLayout.goAlgo(GeoLayout.java:144)
	at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:185)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I've tried with other datasets (found here [http://www.martingrandjean.ch/gephi-introduction/#comment-3650]) and I got the same message. 

I uninstall the plugin and  I installed it again and I've tried with both datasets and I got the same message again.

I would like to know what that means and If there is a way to solve this problem. 

Thank you for your attention.

**Comment by jwscot** [comment]
Hi, I've been running Geo Layout with latitudes between -90 and 90, however it still behaves strangely.

The issue is that I have a column of nodes, where each node in the column should be equidistant. However, the nodes in become further apart towards either end of the column (screenshot attached).

![Screenshot 2021-10-11 at 19 01 34](https://user-images.githubusercontent.com/78442777/136834540-e61d8c62-bbd4-4671-a7e5-94160aca9485.png)
