### ISSUE TITLE
Silent fail on merge columns > create time interval

### ISSUE THREAD

**Issue by ToferC** [gephi/gephi#1288]
Tests conducted using parse string dates in format yyyy-MM-dd.

No column created.  No merge occurs.

**Comment by eduramiba** [comment]
Thanks for the report I am able to reproduce this.

**Comment by eduramiba** [comment]
You can get the updates in Tools - Plugins. But if you installed updates before this week, you need to uninstall and reinstall because I forgot to increment the version number of 1 module and it won't download again
