### ISSUE TITLE
Examples for gephi-toolkit 0.9.0

### ISSUE THREAD

**Issue by tombimbom** [gephi/gephi#1289]
Gephi toolkit 0.8.7 comes with some nice examples, but for a reason I have to use nightly build (0.9.0-SNAPSHOT) and these demo examples won't work on this version of gephi toolkit. Is there any chance I could get a working example for this version? Or any clues on how to make things work?

The main problem is "PApplet", which is no longer in use.

**The old way: (toolkit 0.8.7)**

    ProcessingTarget target = (ProcessingTarget) previewController.getRenderTarget(RenderTarget.PROCESSING_TARGET); 
    PApplet applet = target.getApplet(); 
    applet.init();

**The new way: (toolkit 0.9.0)**

    G2DTarget target = (G2DTarget) previewController.getRenderTarget(RenderTarget.G2D_TARGET); 
    ??? = target.getGraphics();

What is there to substitute it?
I'd appreciate any help. Thank you.

**Comment by eduramiba** [comment]
We still have to update the examples and do the actual 0.9 release, but I think you would do something like this:

```java
G2DTarget target = (G2DTarget) previewController.getRenderTarget(RenderTarget.G2D_TARGET);
```
But now the applet is managed differently, so either you can create your own class to pass events to the target, or just copy this one from Gephi itself (not included in the toolkit) https://github.com/gephi/gephi/blob/master/modules/DesktopPreview/src/main/java/org/gephi/desktop/preview/PreviewSketch.java and add it to your UI.

Maybe we will include a PreviewSketch class in the toolkit or similar so people don't have to copy & paste it.

**Comment by mbastian** [comment]
What is that you actually want to achieve? What were you doing with this PApplet before?

**Comment by tombimbom** [comment]
Thank you, PreviewSketch solved the problem! Now the reason why I'm doing this on 0.9.0 version is because I found out, that in this version directional zoom was implemented. Now that I have a working example, it appears that the zoom isn't directional at all.. any clues on why it isn't?

**Comment by eduramiba** [comment]
Directional zoom is implemented in overview only at the moment.

**Comment by tombimbom** [comment]
Ok, so I made the directional zoom myself. Now I'm stuck with the selectable node thing. The example you made, Eduardo, worked perfectly in toolkit 0.8.7 ([found in the forum] (https://forum.gephi.org/viewtopic.php?f=31&t=2344&start=10#p10050)). Any hints on making it work on toolkit 0.9.0? Thanks a lot!

**Comment by eduramiba** [comment]
Hi,
I think that example should work as is, with the only difference being the rendering of the dot in processing, that now should be done with java2d.

**Comment by tombimbom** [comment]
Dear Eduardo, is this achievable through PreviewSketch class or some other way? I'm so lost here..:/ In version 0.8.7 mouse events were sent to preview controller and everything worked fine. How about version 0.9.0 - should it work the same way? I even seem to be unable to get the Renderer to work.. Is there any chance you could try out your example on the new toolkit version? I'd appreciate that so much.. And I hope I wouldn't be the only one.

**Comment by eduramiba** [comment]
Hi,
I updated the demo and uploaded it early here https://github.com/eduramiba/gephi-toolkit/tree/preview-node-selection-example

[Official demos](https://github.com/gephi/gephi-toolkit-demos) will be updated once we release the new toolkit

**Comment by tombimbom** [comment]
Eduardo, thank you so much! You're a life savior. I really appreciate that very much.

**Comment by mbastian** [comment]
Hi, I updated the toolkit-demos for Gephi 0.9.1 including the Preview one. It's not perfect yet but it should work:
https://github.com/gephi/gephi-toolkit-demos
