### ISSUE TITLE
gephi.data.attributes & gephi.clustering API plugin errors

### ISSUE THREAD

**Issue by artephius** [gephi/gephi#1292]
Plugin installer won't let user install the following plugins from downloaded nbm files:
   * GCViz
   * Concentric Layout
   * Lineage
   * Clustering Chinese Whispers
   * NetworkSplitter3D

"Some plugins require plugin x to be installed"
where x = org.gephi.clustering.api  /  org.gephi.clustering.plugin  /  org.gephi.data.attributes.api

I've googled installing api's and plugins and found no help.
I'm not a developer, though I've done some work with netbeans on simple projects.

**Comment by eduramiba** [comment]
Hi, plugins for 0.8.2 cannot be installed in Gephi 0.9. They all need to be adapted.
The ones already adapted are available in the update center, but it's a work in progress.

**Comment by jimmytidey** [comment]
Any news on this?

**Comment by jimmytidey** [comment]
Thanks very much, looking forward to it. I was particularly interested in:

**Comment by eduramiba** [comment]
That one is not adapted by the author yet, but the 0.8.2 sources are here https://github.com/jaroslav-kuchar/Social-Network-Analysis

**Comment by sleepycat** [comment]
I thought I would take a stab at updating one of the plugins, and chose the markov clustering one to try. I ended up with those same errors. @eduramiba can you shed any light on those warnings?
Have `org.gephi.clustering.api` and `org.gephi.data.attributes.api` been replaced with something else?

```
[INFO] Start migrating ant-based plugin folder.
[INFO] Gephi version is defined as '0.9.1'
[INFO] Found 1 modules to migrate:
[INFO]   'MarkovClustering' will be migrated to 'modules/MarkovClustering'
[WARNING] The 'org.gephi.clustering.api' dependency in 'MarkovClustering' couldn't be migrated, please add it manually in 'modules/MarkovClustering'
[WARNING] The 'org.gephi.data.attributes.api' dependency in 'MarkovClustering' couldn't be migrated, please add it manually in 'modules/MarkovClustering'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.535 s
[INFO] Finished at: 2016-09-09T08:47:21-04:00
[INFO] Final Memory: 11M/112M
[INFO] ------------------------------------------------------------------------
```
It would be great to get some other clustering options working in Gephi again.

**Comment by eduramiba** [comment]
Yeah, attributes API no longer exists (it's part of Graph API).

The clustering API has been removed in 0.9 (see https://github.com/gephi/gephi/releases/tag/v0.9.0) and might come back in a later version.

**Comment by sleepycat** [comment]
In theory fixing this is mostly going to require changing `import org.gephi.data.attributes.api.AttributeColumn;` to `import org.gephi.equivalent.newThing`, right?
So I assume all these things need to be replaced:
```bash
import org.gephi.clustering.api.Cluster;
import org.gephi.clustering.spi.Clusterer;
import org.gephi.clustering.spi.ClustererBuilder;
import org.gephi.clustering.spi.ClustererUI;
import org.gephi.data.attributes.api.AttributeColumn;
import org.gephi.data.attributes.api.AttributeController;
import org.gephi.data.attributes.api.AttributeModel;
import org.gephi.data.attributes.api.AttributeOrigin;
import org.gephi.data.attributes.api.AttributeTable;
import org.gephi.data.attributes.api.AttributeType;
```
Are there docs on what replaces these things? Looking at the [API docs for the graph package](https://gephi.org/gephi/0.9.1/apidocs/org/gephi/graph/api/package-summary.html) it's not clear what is replacing things like AttributeColumn.
Same for clustering (`ClustererBuilder` and stuff). What actually replaces it now that it's removed?

**Comment by sleepycat** [comment]
I see in the release notes: "Remove ClusteringAPI from codebase. It needs a complete rewrite."
@eduramiba Does that mean that there is no migration path until the new clustering api is done?

**Comment by eduramiba** [comment]
AttributeColumn is now org.gephi.graph.api.Column and AttributeTable is now org.gephi.graph.api.Table. AttributeController and model no longer exist. Everything is accessed with GraphModel (getNodeTable for example).

About clustering API, it has no clear replacement, I think it relied on hierarchical graphs, which are no longer supported.

**Comment by jimmytidey** [comment]
Thanks for responding.

I used to be fine running 0.8.2 on Ubuntu, but now I've upgraded to 9 (lots of helpful bug fixes, thanks!) there seems to be a problem going back to 0.8.2. Gephi opens but I just get a blank grey screen and files won't open. 

I've tried fiddling about with plugins, but it says there is a proxy error when it tried to download plugins itself. I don't seem to be able to solve the problem downloading manually either.

**Comment by eduramiba** [comment]
Yeah that's a known problem for 0.8.2, check for a workaround http://gephi.forumatic.com/viewtopic.php?f=4&t=5223&p=12739#p12739

**Comment by jimmytidey** [comment]
I've just done that. It seems to be able to check the URLs for updates, but when I go to install a plugin I still get this error: 

`Networking problem in https://raw.githubusercontent.com/gephi/gephi-plugins/gh-pages/plugins/0.8.2/org-daniel-generator-bamodel-ageing.nbm`

**Comment by tautme** [comment]
I have 0.9.1 on a windows 10 machine and didn't see "social network analysis" in plugin download. Great to hear work is being done. I look forward to using SNA plugin.

**Comment by amirva** [comment]
Hi eduramiba,

I am trying to install Cycle Detection Plugin, but receiving the following error (asking for Attributes API 0.8.2 update). I am using Gephi 0.9.1. I appreciate any help.

![image](https://cloud.githubusercontent.com/assets/22475870/22123778/0b5e150a-de5b-11e6-80f7-530398cba4aa.png)

**Comment by eduramiba** [comment]
Hi, plugins for 0.8.2 cannot be installed in Gephi 0.9. They  need to be adapted.

**Comment by amirva** [comment]
eduramiba,

Thanks for the reply. So how we can adapt them? Or is older version of Gephi available to run this plugin?

**Comment by eduramiba** [comment]
Hi, the author of the plugin has to adapt the code, but you can use it in version 0.8.2 of Gephi without problems. Download it here https://github.com/gephi/gephi/releases/tag/v0.8.2

**Comment by amirva** [comment]
eduramiba,

Thanks for the fast reply. I installed Gephi 0.8.2, but I could not be able to open it up. I think it needs jdk1.7 which is not available in Oracle website anymore.

**Comment by jbliesener** [comment]
Check here: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html   (or google for "Java SE 7 Archive Downloads")

**Comment by jbliesener** [comment]
And a disclaimer: Be aware that Java 7 is no longer getting security updates...

**Comment by amirva** [comment]
Thanks jbliesener and eduramiba,

Now I am running Gephi 0.8.2 and Cycle detection plugin.
