### ISSUE TITLE
Ranking Module

### ISSUE THREAD

**Issue by jmclarkson007** [gephi/gephi#1300]
Hi Someone said it is in the Appearance window.
Where is it? Can you show me as I cannot find it anywhere in the Appearance window. Nor can I find the gemstone or the other functions.

See attached.

Don't put down this is not an issue please.
 It is an issue.

John

**Comment by computermacgyver** [comment]
Hi John, to veify, what version of Gephi are you using? I can't see the attachment.

**Comment by jmclarkson007** [comment]
The very latest - I downloaded it earlier today. 0.9.0

**Comment by eduramiba** [comment]
Hi John,
You need to choose nodes/edges, then check the "attribute" button and choose some column. Then ranking/partition will be automatically chosen depending on the column data, but you can switch it manually with the icon in the bottom left of the appeareance window.

![ranking](https://cloud.githubusercontent.com/assets/197285/12429045/6fbf6b0e-bee8-11e5-9986-c7e0f25b8d06.png)

Also make sure you have Gephi 0.9 updates installed (Tools - Plugins).

**Comment by jmclarkson007** [comment]
okay, thanks.

**Comment by jmclarkson007** [comment]
It just disappeared after I clicked it though

**Comment by jmclarkson007** [comment]
The Ranking doesn't actually pop up like it ought to.

**Comment by jmclarkson007** [comment]
Not like the older version

**Comment by eduramiba** [comment]
What do you mean by pop up? What is disappearing?

**Comment by jmclarkson007** [comment]
Well usually I would get something that looks like this:
![capture](https://cloud.githubusercontent.com/assets/16781191/12432136/69f589a2-bef1-11e5-8e90-10034ed2aec6.PNG)

But this doesn't appear.

**Comment by eduramiba** [comment]
What do you get? Can you get something like this?

![ranking](https://cloud.githubusercontent.com/assets/197285/12432339/00df49e4-befb-11e5-8933-4d0a18e58b05.png)

You should get that just by choosing the column and then click on "Switch to ranking"

**Comment by jmclarkson007** [comment]
Yes, I get that.

**Comment by jmclarkson007** [comment]
But when you say choosing the column? What do you mean? When I get the ranking symbol up and click it, it just vanishes. I want to choose Degrees then put in a lower and upper limit on the slider, like in the old version.

**Comment by jmclarkson007** [comment]
![capture2](https://cloud.githubusercontent.com/assets/16781191/12435727/47fa5e20-bf07-11e5-927f-cca0242b99c6.PNG)

**Comment by eduramiba** [comment]
Oh you want to rank the size and not color.
Then you have to click on the size button just like the old version. The only difference is the icon.

![ranking](https://cloud.githubusercontent.com/assets/197285/12435838/575674ea-bf10-11e5-9e52-aaf6541bbff9.png)

**Comment by jmclarkson007** [comment]
What happened to the slider?

**Comment by eduramiba** [comment]
Not sure about the slider, sorry.

**Comment by mbastian** [comment]
Slider was removing for the sake of simplicity as the same result can be achieved by first filtering based on that attribute and then apply ranking on the filtered graph.
