### ISSUE TITLE
Can't get Streaming tab in Gephi 0.9 for Max OSX

### ISSUE THREAD

**Issue by mindlessrabble** [gephi/gephi#1301]
I am trying to display graphs from Gremlin in an interactive mode in HTML5.  I found a number of tutorials that recommended using Gephi and directed what to do using the streaming tab.  However, it does not appear.

I tried adding the GraphStreaming plugin found here.  https://gephi.org/gephi-plugins-front/#/plugin/graph-streaming into Gephi 0.9.  

However, it gives me a message that the following plugins are required.

org.gephi.desktop.streaming
org.gephi.lib.jetty
org.gephi.streaming.api
org.gephi.streaming.impl
org.gephi.streaming.server

I haven't been able to find them.  

Any recommendations?

**Comment by eduramiba** [comment]
Hi,
Plugins for Gephi 0.8.2 won't work in 0.9.
We are working on adapting them at the moment.

**Comment by computermacgyver** [comment]
The streaming plugin has not yet been released for Gephi 0.9 yet (and the 0.8.2 version of the plugin will not run in Gephi 0.9). The streaming plugin is nearly updated for 0.9 --- see progress here https://github.com/gephi/gephi-plugins/pull/75 . Alternatively, you have the option to temporarily use version 0.8.2 of Gephi

@panisson
