### ISSUE TITLE
SigmaJs Plugin does not work with Gephi 0.9

### ISSUE THREAD

**Issue by tyloria** [gephi/gephi#1302]
The plugin Sigma JS has not been updated for Gephi 0.9 and does not work anymore

**Comment by computermacgyver** [comment]
Thanks. All of the plugins are in the process of being updated to the new version of Gephi.
SigmaJS is nearly updated, but still needs to be reviewed by the core Gephi team (see https://github.com/gephi/gephi-plugins/pull/74)

In the meantime, you can use the JSONExporter plugin (Tools->Plugins) to update the data.json file for any existing SigmaJS exports you have.

**Comment by tyloria** [comment]
Thanks for your quick reply! Awesome!

**Comment by computermacgyver** [comment]
Just to update you, @tyloria , that the plugin has now been incorporated into the newest version of Gephi and is available via Tools->Pluings.
