### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by dinos66** [gephi/gephi#1303]
Hello. 

Is it possible to provide timestamps via CSVs? If yes, could you please provide the format which we can use to enter the timestamp for the dynamic graphs?
I'm trying to use the following format (tried all TimestampFormatMaps) and a) the timestamp comes back empty, and b) It will only accept the first two rows (as soon as the timestamp changes, it drops the rest of the dataset):

Source,Target,Weight,Type,Timestamp
0,1,1,undirected,1861
0,2,2,undirected,1861
1,3,3,undirected,1862
3,4,4,undirected,1862
0,4,5,undirected,1863

I'm obviously doing something really wrong but I have no idea what it is.
Could you please help?

**Comment by computermacgyver** [comment]
I'm able to import the data you have with the following steps:
1) Open Gephi
2) File->New Project
3) Switch to "Data Laboratory", click "Import Spreadsheet"
4) Select the file and set "Edges table" for as table.
5) Click Next
6) For Timestamp, choose "TimestampSet"
7) Click Finish

(Strangely the weights are not being imported correctly, but the timestamps are fine.) Can you double check if selecting "TimestampSet" works on your machine?

**Comment by dinos66** [comment]
Thank you so much Scott for your prompt reply.
Although the "For Timestamp, choose "TimestampSet" suggestion, did solve the <empty> timestamp problem, it did not solve the cutting off of the dataset at the timestamp change problem. I guessed that it must be the duplicate edges in the next time stamp that is causing the problem (they are duplicate between timestamps, not in the same timestamp), so I tried adding an Id (string from a counter) to each edge, to no avail. 
Any ideas?
Thanking you in anticipation,Dino 

    On Wednesday, January 20, 2016 7:17 PM, Scott Hale <notifications@github.com> wrote:
 
 

 I'm able to import the data you have with the following steps:
1) Open Gephi
2) File->New Project
3) Switch to "Data Laboratory", click "Import Spreadsheet"
4) Select the file and set "Edges table" for as table.
5) Click Next
6) For Timestamp, choose "TimestampSet"
7) Click Finish(Strangely the weights are not being imported correctly, but the timestamps are fine.) Can you double check if selecting "TimestampSet" works on your machine?—

**Comment by computermacgyver** [comment]
I copied and pasted the data exactly from your opening post and didn't have the cutoff problem. This makes me wonder whether there might be a non-printable character that is causing trouble (i.e., is there a NULL, EOF, or other invisible character at the end of that line). See if you can spot anything in a text editor and/or I am happy to have a look at the file if you can make it available.

**Comment by dinos66** [comment]
Did you use the second example I uploaded where a duplicate edge appears between timestamps? (I also include it below). The fourth edge (Id.4) is the same with 1 but with a different timestamp. Nonetheless, it still causes a problem. I also checked the datasets for escape chars as you mentioned, but there appear to be none.

1,0,1,1,undirected,1861
2,0,2,2,undirected,1861
3,1,3,3,undirected,1862 - after this edge, nothing is imported
4,0,1,3,undirected,1862
5,3,4,4,undirected,1862
6,0,4,5,undirected,1863

Again, a million thanks for your prompt response.

**Comment by eduramiba** [comment]
Please keep in mind that timestamp sets won't be merged if the edge is repeated in the input CSV.
No special logic is applied for merging duplicated edges, apart from weight summing.

**Comment by dinos66** [comment]
Understood. As I explained earlier, edges are never repeated within the same timestamp. So they shouldn't be considered duplicates but evolving edges.
My question is: why are the following two considered a conflict?

Id,Source,Target,Weight,Type,Timestamp
1,0,1,1,undirected,1861
4,0,1,3,undirected,1862

**Comment by computermacgyver** [comment]
Ok. Yes, I see the trouble. I will leave it to the core team to decide if edges with the same source/target but different timestamps should be aggregated together.

In the meantime, here is one data format that will work to import your data. Use tab's to separate fields and then something like:

```
Id	Source	Target	Weight	Type	Timestamp
1	0	1	1	undirected	<[1861,1862]>
2	0	2	2	undirected	1861
3	1	3	3	undirected	1862
5	3	4	4	undirected	1862
6	0	4	5	undirected	1863
```
will import fine using the TimestampSet option.

**Comment by eduramiba** [comment]
Right, that's the format you should use if you have several timestamps.
Ideally you should never repeat edges.

Spreadsheet import is intended to be a very simple tabular import tool, what you want to see in data laboratory is what you should input.

**Comment by dinos66** [comment]
That's great to hear. Although I believe you've solved my problem. Any duplicate edges should be imported using an aggregation of timestamps. Excellent!
