### ISSUE TITLE
Unable to color nodes by partition colors using Modularity in Gephi 0.9 on OS X

### ISSUE THREAD

**Issue by rjurney** [gephi/gephi#1307]
The partition button simply does nothing for Modularity. I tested Connected Components and this works! But not modularity. This is really holding me up :(

Image attached:

![modularity_partition_color](https://cloud.githubusercontent.com/assets/42149/12463286/881eb954-bf77-11e5-98c2-3e27425a9073.png)

**Comment by supersambo** [comment]
I'm having the same issue on windows. I think this is because Modularity returns numeric variables. For now you could try copying the values in the data laboratory to a string column.

**Comment by rjurney** [comment]
Note: this is fixed on master! I built and launched from the latest source and this problem is fixed :)
