### ISSUE TITLE
Gephi forum disallows registration due to expired spam detection service

### ISSUE THREAD

**Issue by Jesdisciple** [gephi/gephi#1308]
I attempted to register to post on the forums and received this very unexpected message:

    Your IP [my IP address] has been blocked because it is blacklisted. For details please see
    http://www.ahbl.org/lktool?lookup=[my IP address].
    An entry on the blacklist may have several reasons:
    1. You are a well-known spammer.
    2. Last time a well-known spammer was using the dynamic IP address which you got from your ISP
    (Internet Service Provider), your e-mail address or the username you have choosen.
    3. Your ISP is well-known for a lot of spamming customers and is not fighting against spammers
    enough.

The linked page directed me to http://www.ahbl.org/content/last-notice-wildcarding-services-jan-1st which explains that the service has been discontinued. And from now on, everyone's a spammer, to (I suppose) avoid false negatives.

Please get someone to disconnect the forums from that service so I (and others) can register.

**Comment by ghostlayer** [comment]
I already opened this issue #1274. I tried emailing developers and website support also, but apparently no one related to the gephi projects cares about the forum. At the moment forum is broken and killed by spam.

**Comment by eduramiba** [comment]
Hi,
Apologies for the status of the forum. We need to clean it up a lot and do some maintenance tasks so it works properly.

Spammers have been a real pain in the forum so we focused our few resources in the development.

**Comment by mbastian** [comment]
Duplicate #1047
