### ISSUE TITLE
Windows Won't Get Past "Starting modules..."

### ISSUE THREAD

**Issue by JoeData892** [gephi/gephi#1311]
Hello:

I feel I have tried everything.  I am running Windows 7 64.  I have seen the multiple issues with Java.  I have run it with java home mapped to JDKv7u79 and JDKv8u71 (for both 32 and 64 bit).  None of them work.  It just sits with the splash window on "Starting Modules..." for ever.  I'm open to any suggestions.  Thank you.

**Comment by mbastian** [comment]
Hi, first which version of Gephi are you using? Then, can you copy here the content of the messages.log file, which should be located in `C:\Users\username\AppData\Roaming\.gephi\0.9.0\dev\var\log`. That should tell us what's going on. Also, make sure that you have updated graphics driver.

**Comment by jdstein** [comment]
I am having the same issue. If it is useful, I attaached my log file--although there are no errors in it.
[messages.txt](https://github.com/gephi/gephi/files/102015/messages.txt)

**Comment by JoeData892** [comment]
Hi Mathieu:

So my problems arise with 0.9.  I actually have 0.8.2 working.

But my messages.log file for 0.9 are attached.

Joe Offutt
joe.offutt@gmail.com

**Comment by mbastian** [comment]
Are you running the program as an administrator? I could potentially see a permissions issue here.

**Comment by JoeData892** [comment]
Thank Mathieu!  I know my company has some strict blocks, but typically we
can run anything as long as we run as administrator.  So I am pretty
cognizant of making sure I have admin rights when I run something, but I
will investigate that.  I am continuing to use 0.8.2, and it seems fine.
Wouldn't admin issues pop up with 0.8.2 as well if that was the problem?

Joe Offutt
joe.offutt@gmail.com

**Comment by rpkehoe** [comment]
Were you able to get this working Joe?  I am having the same issue, but am not able to run with admin rights.  Risk recently stripped that from everyone, haven't been able to get it back yet.

**Comment by JoeData892** [comment]
I have not.  I haven't been trying to fix it as much as the 0.8.2 beta works for me.  But I just tried the updated 0.9.1 (my original most was on 9.0), and it still doesn't work...

**Comment by rpkehoe** [comment]
Thanks for mentioning 0.8.2, I was able to get that up and running.

**Comment by carlosdand** [comment]
Hi, guys,
I've the same problem here (Windows 8.1 64). No perspective of solution yet? Thanks!

**Comment by kmkross** [comment]
I have the same issue when running Gephi 0.9.1 on Windows 10. As far as I know, it was working well a few months ago. 
I have since then downgraded Java to 7u79 and used Gephi 0.8.2. It works fine now. I have tried using the latest Gephi version with this older version of Java, but to no avail. I am not sure if Gephi 0.8.2 will work with Java 8, however.
It is not an ideal setup but will do while the issue is pending. I hope this helps the developers.

**Comment by carlosdand** [comment]
Good news: Gephi's new version worked again after installing the Java Development Kit 8 http://www.oracle.com/technetwork/pt/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by cristianomoliveira** [comment]
Thanks.

**Comment by eduramiba** [comment]
Tracking at #1631
