### ISSUE TITLE
Windows Defender Is Reporting Malware

### ISSUE THREAD

**Issue by tdouthat** [gephi/gephi#1316]
Has anyone else had this problem while trying to download?

**Comment by mbastian** [comment]
Yes, we had reports of this. It's nonsensical and Gephi binaries are 100% safe.

**Comment by tdouthat** [comment]
So what should I do?

**Comment by ghostlayer** [comment]
False positives can be submitted here:

https://www.microsoft.com/security/portal/submission/submit.aspx#

Be sure to select "I believe this file should not be detected as malware"

**Comment by tdouthat** [comment]
Could some one from Gephi contact them? https://www.microsoft.com/security/portal/developer/contactus.aspx. I have tried to follow your advice ghoststlayer, but it won't let me upload the EXE for its size.

**Comment by mbastian** [comment]
Cool, I'll contact them but they request the following information, can you help me?

`Which security software are you asking about?*	

Microsoft Security Essentials
Windows Defender (Windows 10)
Windows Defender (Windows 8)
Windows Defender (Windows XP/Vista/7)
System Center 2012 Endpoint Protection
Windows Server Antimalware
Microsoft Forefront Endpoint Protection 2010
Microsoft Forefront Client Security
Microsoft Forefront Server Security
Office 365 and Exchange Online Protection
Microsoft Forefront Protection for SharePoint
Windows Intune
Microsoft DaRT
Other`

`Can you provide the scan results?*	
To provide the results:
In your Microsoft security software, click on the History tab.
Click on All detected items.
Copy the name of the detection into the text box on the right.`

`What definition version are you using?*	
You should try the latest definition version before submitting your question. To provide the security software definition version currently installed in your PC:
In your Microsoft security software, click the arrow next to the Help button and then click About.
Select the definition information and press Ctrl+C.
Paste the information on the text box on the right.`

Also, as a general question does the problem arise with Gephi's installer or gephi's executable?

**Comment by tdouthat** [comment]
When I download, it stops the executable from running: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fVarpes.J!plock&threatid=2147706743&enterprise=0.

**Comment by mbastian** [comment]
Sorry but this link doesn't work :(

**Comment by tdouthat** [comment]
It opens for me, and I am not logged on. Strange. Basically, Windows Defender 10 thinks, rightly or wrongly, that the Gephi exe or download has Trojan: Win32/Varpes.J!plock.

**Comment by mbastian** [comment]
And which definition version are you using? Microsoft requires this information, here is how to pull it:

```
In your Microsoft security software, click the arrow next to the Help button and then click About.
Select the definition information and press Ctrl+C.
Paste the information on the text box on the right.`
```

**Comment by ghostlayer** [comment]
Tested both versions 0.9.0 and 0.9.1 both clean on Win10 pro with Defender. Did some research on Varpes.J!plock and it seems to be a browser hijacker. Seen postings that other downloaded executables (chromesetup.exe) also get triggered with the same Win32/Varpes.J!plock. Win32/Varpes.J!plock started around nov/dec 2015 so that could be the reason why more reports are popping up. All other scanners/virustotal come up clean so it seems that it is not gephi that triggers it, but it an infected browser that is downloading a random exe. 

@tdouthat you should take a look at your browsers plugins and settings, because probably something running as a malicious browser plugin:

https://www.malwarebytes.org/mwb-download/ (use the free version)
http://www.thewindowsclub.com/free-browser-hijacker-removal-tool

**Comment by heydenis** [comment]
I have exactly the same problem with W10 and Windows Defender. I checked my browser and run MWB.  The only time that windows defender trigs is when I am trying to install it.

I could just allow it from Windows Defenfer... bit scared tho.

**Comment by eduramiba** [comment]
Closing old issue
