### ISSUE TITLE
No Suitable driver found for jdbc:mysql://

### ISSUE THREAD

**Issue by AdamFermier** [gephi/gephi#1317]
Working on Gephi Version 0.90 and trying to connect to an edge list library (MySQL) - which I was able to do in Gephi Version 0.8.2 following the "instructions" found here: https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 - followed those same instructions with no luck.  

Any suggestions?

**Comment by computermacgyver** [comment]
Check out #1225 . Is the problem fixed if you right click Gephi and use the run as administrator option?

**Comment by AdamFermier** [comment]
Thanks!  That got the "Test Connection" to work - but when I go to pull the data (i.e., click ok button) window goes away - but the "import progress" in bottom RHS does not show up in Gephi 0.90 like it does for Gephi 0.8.2.

Almost there - any further suggestions?

**Comment by mbastian** [comment]
Weird, if you don't get an error here the query should have worked. Maybe the query just return nothing? Take a look at the message log (Windows > Output), maybe there's an error there somehow.

**Comment by mbastian** [comment]
Update?

**Comment by ShobhitSaxena29** [comment]
Hi I am also facing same problem, getting "No suitable driver found  for jdbc:mysql://localhost:3306/sys"

I have tried following: 
1. Help -> check for updates 
2. tools -> plugin -> check for updates 
3. Running Gephi with administrator rights (Run as Administrator)

I am using Gephi 0.9.1

Steps: 
1. File -> Import database -> edge list
2. Host: localhost
3. Port: 3306
4. database: sys
5. username/pswd: root/root 
6. hit on Test Connection 

and getting the error that driver not supported. 
Please help urgently...

**Comment by ShobhitSaxena29** [comment]
I have tried executing Gephi as admistrator. B7t no success.

**Comment by ShobhitSaxena29** [comment]
Have mentioned same in comments as well. Please help me urgently..

**Comment by eduramiba** [comment]
What is your java version? Is the mysql connector in your gephi installation? (```gephi\gephi\modules\ext\org.gephi.db-drivers\mysql\mysql-connector-java.jar```)

**Comment by eduramiba** [comment]
Also please post your log file, located at:

C:\Users\{username}\AppData\Roaming\.gephi\{gephi.version}\dev\var\log\messages.log

**Comment by ShobhitSaxena29** [comment]
I have Java 1.6 and 1.7 running in my system. Yes gephi\gephi\modules\ext\org.gephi.db-drivers\mysql\mysql-connector-java.jar is present.. let me get you the logs..

**Comment by ShobhitSaxena29** [comment]
[messages.txt](https://github.com/gephi/gephi/files/330080/messages.txt)

**Comment by eduramiba** [comment]
As I see, https://github.com/gephi/gephi/blob/0.9.1/modules/DBDrivers/src/main/java/org/gephi/io/database/drivers/MySQLDriver.java is not doing the typical ```Class.forName```, though it should not be necessary anymore with recent versions of java (according to https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html).

Can you try to update your Java version to a more recent version of Java 7?

Maybe we should add the ```Class.forName``` so it works in all cases.

**Comment by ShobhitSaxena29** [comment]
Really sorry, But I can`t change JAVA in my machine, is there any other workaround?

**Comment by eduramiba** [comment]
Maybe, let me try something, will write back.

**Comment by ShobhitSaxena29** [comment]
Thanks

**Comment by eduramiba** [comment]
Can you try to install the following nbm?
[db-drivers-0.9.1.nbm.zip](https://github.com/gephi/gephi/files/330175/db-drivers-0.9.1.nbm.zip)

Unzip it, then go to Tools - Plugins - Downloaded and locate the file manually and install it.

**Comment by ShobhitSaxena29** [comment]
ok Let me try this..

**Comment by ShobhitSaxena29** [comment]
It Worked.. Thanks a lot :+1:

**Comment by eduramiba** [comment]
Cool! Releasing it through update center then!
