### ISSUE TITLE
Gephi 0.9 doesn't display node attributes from a .gephi file saved by Gephi 0.8.2b

### ISSUE THREAD

**Issue by ypanagis** [gephi/gephi#1320]
I am having a graph with several node attributes and some of them are rather long `Strings`. I noticed that node attributes that are displaying correctly in Gephi 0.8.2 cannot get displayed at all with Gephi 0.9. 

I am [attaching] (https://github.com/gephi/gephi/files/107235/error0.9.gephi.zip) a small sample of the problematic file

I am using Gephi 0.9 on Windows 7 x64, in parallel with Gephi 0.8.2, and jre.1.8u25 64-bit

**Comment by mbastian** [comment]
Thanks for the report. That seems like I bug. I can reproduce it.
