### ISSUE TITLE
Cant open files into Gehpi

### ISSUE THREAD

**Issue by emily339** [gephi/gephi#1325]
I am very new to Gehpi, and so far I have been able to get excel files into gephi by opening them as opposed to the import spreadsheet tab. 

I just updated to 0.9.0, and now when I try to open a file into Gephi, nothing happens.

Help?!

**Comment by mbastian** [comment]
Excel files? You mean CSVs are we never supported Excel files.

**Comment by eduramiba** [comment]
Closing as excel files not supported. Other fixes for CSV to be done: #1251 #1431 #1454
