### ISSUE TITLE
Dynamic import from CSV - Gephi 0.9

### ISSUE THREAD

**Issue by Carromattsson** [gephi/gephi#1329]
Hello,

I just moved over to Gephi 0.9 and found that the csv import possibilities for dynamic graphs have completely changed, and I was hoping someone could explain the changes so that I can work around them. 

I've been building up a dataset over the past year using the dynamic interval format presented here - https://gephi.org/users/supported-graph-formats/spreadsheet/
Using Gephi 0.7 the csv import wizard would give me the option of importing columns as a time interval or a dynamic variable, which would nicely parse a csv file in the above format. The result would be a dynamic graph in Gephi, great. 

Those options are no longer available in the import wizard -- they have been replaced with "*var*[]" and "TimestepSet" and "Timestep*var*Map". None of these understand the format that worked in earlier versions. What format are these import functions expecting? What is the new incarnation of time interval?

Thank you,
Carolina

ps. This issue goes beyond csv files, but the reasons are harder to trace. Gephi 0.9 understands neither the .gephi nor the .gexf versions of my network that Gephi 0.7 saved. It throws a mountain of importing errors and depreciations regarding the time intervals and the dynamic variables.

pps. I meant to post this on the forum, but it thinks I'm a spammer :-\

**Comment by eduramiba** [comment]
Hi Carolina,
In 0.9 new workspaces have Timestamp time representation for dynamics by default, but you can change that to Interval in Data Laboratory - Configuration dialog (while the workspace is empty).

Then you will have IntervalSet and IntervalMap types available for colums, which are compatible with the format of old dynamic types. For example IntervalSet = TimeInterval and IntervalStringMap = Dynamic String.

More info on timestamps here https://gephi.wordpress.com/2015/11/02/announcing-gephi-0-9-release-date/

I created a related issue for this: #1332

About 0.7 .gephi files, I am not sure those can be opened, but you should be able to import .gephi files from 0.8.2 correctly.

**Comment by mbastian** [comment]
Hi Caroline, I must admit that we haven't really had time to update the documentation on dynamics in 0.9 as we're busy fixing some of the most urgent bugs. There are a lot of changes in this version indeed and I'm planning on writing about it soon. Stay tuned!

Regarding the importing issue, I remind seeing a report that time values were not properly imported from 0.8.2 .gephi files. I'll look into that and come back to you. About the gexf they should work fine regardless the deprecation messages. Could you post a sample here for reference? Thanks.

**Comment by Carromattsson** [comment]
That worked! Opening the Configuration dialog before loading anything gave me access to the drop-down option for the time representation, yay! 

Two followup issues:

* Even if you are in "Interval" mode the "Convert column to dynamic" process will make a "Timestamp" variable type column. (To me specifically, this means I can't copy over my imported dynamic weight column into the default one. I've missed it if there is a different way to change which column is used as the weight. Sidenote - I wasn't actually trying to join the two columns just messing around to figure out what was up :P )
<img width="718" alt="screen shot 2016-02-03 at 1 36 06 pm" src="https://cloud.githubusercontent.com/assets/8902506/12792716/2c538096-ca7b-11e5-8ef6-dcad96a7cb19.png">

* The Interval column looks weird, but it appears to have the data in it - see the attached photo. That's actually the same thing I noticed loading the .gexf and .gephi files I had. So that actually does work, the intervals just don't display right.
<img width="1377" alt="screen shot 2016-02-03 at 1 07 16 pm" src="https://cloud.githubusercontent.com/assets/8902506/12792413/b902565e-ca79-11e5-9a2d-80b67a9888c1.png">

**Comment by Carromattsson** [comment]
Here is one of the .gexf files that gave me lots of errors. The file could totally be poorly formatted, but that would be an issue with the earlier version of Gephi that I saved it from.  
[Version2.txt](https://github.com/gephi/gephi/files/116234/Version2.txt)

**Comment by eduramiba** [comment]
About the time interval graphics looking weird, I have seen that happen, it seems bounds don't get correctly updated after new interval values are set. Sometimes it works if you mess a bit with the table.

I created an issue for this: #1335

About merge into dynamic interval, I commented on #1334 and it was fixed on #1288 You can get the updates in Tools - Plugins. But if you installed updates before this week, you need to uninstall and reinstall because I forgot to increment the version number of 1 module and it won't download again.

**Comment by eduramiba** [comment]
Closing this as the only remaining issue is tracked in #1335
