### ISSUE TITLE
Unable to change the size of a node depending on different attributes

### ISSUE THREAD

**Issue by AritzBi** [gephi/gephi#1330]
In 0.9 and 0.9.1 is impossible to draw the nodes with different sizes depending on attributes. Even though I have in the data laboratory a few columns that represents different attributes, in the list where you have to choose on which attribute depends the size of the nodes, only the degree of the node is shown. 

However, this same feature but for coloring works properly.

**Comment by computermacgyver** [comment]
Thanks for the report. Nodes can only be resized to numeric values. Are the columns you refer to numeric (and specified as such)? Also make sure you have all the latest updates installed (help->check for updates): there have been some fixes around the data laboratory.

**Comment by AritzBi** [comment]
With the updates the issue has been fixed in Windows 8. However, in OS X Gephi is unable to check for updates :(

**Comment by mbastian** [comment]
@AritzBi Unable to check for updates? Any error you're getting?

**Comment by AritzBi** [comment]
@mbastian "Check your network connection, verify that your proxy settings are configured correctly, or try again later." 

However, if I go to preferences and I test the connection, the test works properly.

**Comment by ibcasxxf** [comment]
I have the same problem

**Comment by maia** [comment]
I hade the same issue of not being able to select columns for node sizing that were of type float. Updating solved the issue. I hope there will be a new downloadable release soon, as I assume I'm not the only one know didn't know about an update functionality rather hidden in the "Help" menu.

**Comment by mbastian** [comment]
Yes, there will be a new version soon. Closing.
