### ISSUE TITLE
Equal filter does not work with array columns

### ISSUE THREAD

**Issue by swedishmike** [gephi/gephi#1331]
I'm reporting this for version 0.9.0 running on Win10 64 bit. 

This might be a case of me not knowing how to use the software, but I tried following the instructions from 'Mastering Gephi Network Visualization' so it _should_ probably work... 

Steps to replicate:

1. Load the **Marvel Social Network**
2. Switch over to Data Laboratory
3. Select Create column with list of regex matching groups (using the Label column), enter 'Man' for Title and '\bMAN\b' in the Regular expression field. Hit ok. (You'll see the column created and matching fields populating where suitable)
4. Switch back to Overview and drag the Attributes / Equal filter for the 'Man' column to Queries and add MAN in pattern.

4 is where it fails, my 'Man' column is not visible under the Equal attribute. I can see it under Non-null and filter on that though.

I've tried with some other example files and seem to be having this issue with the 'Equal' attribute/filter across the field.

Is this behaving as expected or is this a bug?

Cheers, Mike

**Comment by mbastian** [comment]
Have you tried to hit `Reset` in the Filters interface?

**Comment by swedishmike** [comment]
I just tried that and that still gives the same behavior, or lack thereof.

**Comment by mbastian** [comment]
I see, right now we ignore the array-type columns in this filter. Let me see if we can add this.

**Comment by mbastian** [comment]
I added support for arrays in filter but right now it works only as an "equal", not as a "contains". We should probably add a separate filter for that. It means you'll need to use the same string like seen in the data laboratory in your filer, e.g "[MAN]". Hopefully with the regex support you can match elements within the array.
