### ISSUE TITLE
Plotting node graph with x and y co-ordates of nodes

### ISSUE THREAD

**Issue by JDharminSiddesh** [gephi/gephi#1340]
Hi I have a problem where i need to plot a node graph with x and y co-ordinates. 

based on guidance from here https://forum.gephi.org/viewtopic.php?t=1811 

which says the following

Install the plugin (you can find it in Gephi third party plugins named as 'Data Laboratory Helper'
Import your CSV data with the position columns
In data lab, click on more actions, then click on 'Set standard column'
Select your X position column in the first field, and 'X-Coordinate(Node table)' in the second field. Then click on 'Set column'
Repeat last step for Y position

 i am using the following plugin which was also specied in the same tutorial

 https://marketplace.gephi.org/plugin/recast-column/

On installing the plugin i am getting a page as this

![image](https://cloud.githubusercontent.com/assets/12684041/12839551/9779d0ce-cc00-11e5-83f2-b1e2bc536ca8.png)

on clicking on "more action"  button i am not able to find 'Set standard column' options there

Is this a version problem or am i using a wrong plugin??

help please

**Comment by eduramiba** [comment]
Hi,
Plugins for 0.8.2 cannot be installed in 0.9. Until this plugin is adapted for 0.9 you can use 0.8.2.
