### ISSUE TITLE
NullPointerException @ ApperanceModel

### ISSUE THREAD

**Issue by kowalski100** [gephi/gephi#1352]
I get NullPointerException at the following point.
`
AppearanceModel appearancemodel = Lookup.getDefault().lookup(AppearanceController.class).getModel(workspace);
`

OR

`
AppearanceModel appearancemodel = Lookup.getDefault().lookup(AppearanceController.class).getModel();
`

My Imports are:

```
import org.gephi.appearance.api.AppearanceController;
import org.gephi.appearance.api.AppearanceModel;
```

**Comment by mbastian** [comment]
Is this in the Toolkit?

**Comment by kowalski100** [comment]
Its in the plugins...
https://github.com/gephi/gephi/blob/master/modules/FiltersPlugin/src/main/java/org/gephi/filters/plugin/partition/PartitionBuilder.java#L96

**Comment by JavaCoreDeveloper** [comment]
I have solved this exception using AppearanceImpl class object which implements AppearanceModel interface.
AppearanceModelImpl am = Lookup.getDefault().lookup(AppearanceModelImpl.class);

But now i need a column object 
Partition p = am.getNodePartition(graph, (Column) attributeModel.getNodeTable().getColumn("modularity_class"));

How can i get Column Object from AttributeModel. Any help will be appreciated.

**Comment by eduramiba** [comment]
I understand you are using the toolkit.

In that case, try to lookup the AppeareanceController **before** you initialize any project or workspace, since the AppeareanceController is responsible of adding the AppeareanceModel to the workspace when the workspace is initialized.

**Comment by JavaCoreDeveloper** [comment]
I tried that before but that give me null pointer exception. But the problem i am having now is that i need to get Column object from attributeModel. is there any way to get it done.
Thanks for reply.

**Comment by eduramiba** [comment]
Hi,
Old Attributes API and model no longer exists. You can manage attributes directly with the graph, nodes and edges methods.

**Comment by JavaCoreDeveloper** [comment]
I need to use the AppearnceModelImp class method 
getNodepartition(Graph, Column)
 which takes Column object. For that i need to get Column Object. But graph method return attributeColumn object, which isn't cast to Column object . And then i need to process that partition object. Hope you are understanding the issue.

**Comment by eduramiba** [comment]
Make sure you are only using dependencies from 0.9.1 toolkit and not some other old toolkit, you can see here the new API returns Column https://gephi.org/gephi/0.9.1/apidocs/org/gephi/graph/api/Table.html

**Comment by JavaCoreDeveloper** [comment]
Hey, I need to get the Column Object from graph. But it returns nodeTable Object of type AttributeTable. And column object of type AttributeColumn. Both are of no use for me. I know Table can return me column. But if you can guide me to get Table or Column Object from graph. It would be very kind of you.

**Comment by eduramiba** [comment]
As you can see here https://gephi.org/gephi/0.9.1/apidocs/org/gephi/graph/api/Graph.html graph does not return that now. As a matter of fact, if you have any AttributeSomething in your classpath, you have wrong dependencies, since Attributes API was removed in 0.9.0

**Comment by JavaCoreDeveloper** [comment]
Okay thanks. By the way i'm using latest dependencies in my pom.xml file. gephi-version 0.9.0.

**Comment by eduramiba** [comment]
Can you show your pom dependencies?

**Comment by JavaCoreDeveloper** [comment]
```
<dependency>
			<groupId>gephi-toolkit</groupId>
			<artifactId>gephi-toolkit</artifactId>
			<version>1.0</version>
		</dependency>
		
		<dependency>
			<groupId>org.gephi</groupId>
			<artifactId>graph-api</artifactId>
			<version>0.9.0</version>
		</dependency>
```

gephi-tollkit dependency is in local jar file

**Comment by eduramiba** [comment]
Try to only have this single dependency:

```xml
<dependency>
    <groupId>org.gephi</groupId>
    <artifactId>gephi-toolkit</artifactId>
    <version>0.9.1</version>
</dependency>
```

**Comment by JavaCoreDeveloper** [comment]
```
AppearanceModelImpl am = Lookup.getDefault().lookup(AppearanceModelImpl.class);
	
	
		Partition p = am.getNodePartition(graph, (Column) attributeModel.getNodeTable().getColumn("modularity_class"));
```

Here is code in which i'm getting exception **classcastException**  while casting column parameter in getNodePartition function call.

**Comment by mbastian** [comment]
Hi, please open a ticket in the gephi/toolkit project. Consult the https://gephi.org/gephi/0.9.1/apidocs/ for details about the API.
