### ISSUE TITLE
New plugin

### ISSUE THREAD

**Issue by AmaniChou** [gephi/gephi#1357]
I want to develop a new metric. As I saw in this [link](https://gephi.org/docs/api/org/gephi/statistics/spi/package-summary.html), I need to add the attribute API as a dependency that I can't find in the new version. Any updated link ?

**Comment by mbastian** [comment]
Features of the AttributesAPI have been merged in the GraphAPI so things should be simpler. Consult the API Changed here for all the details: https://gephi.org/gephi/0.9.0/apidocs/index.html
The link you have is the previous 0.8.2 version

**Comment by AmaniChou** [comment]
Things are more clear now, thanks. I have another issue also related to the creation of the new plugin. I'm not sure whether to close this one and open a new one as I used a generic name. Here it is.
After downloading the [gephi-plugin](https://github.com/gephi/gephi-plugins), I can't add source package, it says that source packages are owned by project gephi and cannot be used, and I have to see issue 138310 for more details. But I can't find the related issue
