### ISSUE TITLE
[Feature request ?] Label wordwrap OR Label multiline support

### ISSUE THREAD

**Issue by DirectuX** [gephi/gephi#1368]
Hello, 

would these features be available ?

- **sizing and word-wrapping the text** of a label to fit the shape of the node (one can choose the words separator)

-  **word-wrapping the text** of a label to mimic the shape of the node and **size the node** to box the amount of text inside

OR

at least take in consideration a way to have carriage returns in labels

Thanks

**Comment by mbastian** [comment]
Duplicate of #787
