### ISSUE TITLE
Problem with Gephi 0.9 Filters

### ISSUE THREAD

**Issue by GitHubFDC** [gephi/gephi#1370]
I've noticed that in Gephi 0.9 the filters aren't working properly.  I can build the query with the query-builder UI, but I cannot change the values of the parameters for the queries.

To reproduce: launch Gephi, generate a random graph (nodes=50, probability of rewiring = 0.5), apply layout and node-coloring as desired, then try to filter on TOPOLOGY -> Degree Range.  On my system (Gephi 0.9.0 201510222201, Windows 7, Intel Core i7, Java 1.8.0_72), the user is unable to change the parameters for the degree range.  

I've tried creating other filters on other graphs and have consistently encountered the same problem.  However, I have not tested this on a machine with a more recent version of Windows or on a Mac.  I can perform those tests if needed.  

Attached is a screen-capture that might be helpful.

Thanks!
![gephifiltercapture](https://cloud.githubusercontent.com/assets/1275889/12957653/cd75a618-cffb-11e5-8c05-a4ac41fabb34.PNG)

Product Version: Gephi 0.9.0 201510222201
Java: 1.8.0_72; Java HotSpot(TM) Client VM 25.72-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_72-b15
System: Windows 7 version 6.1 running on x86; Cp1252; en_US (gephi)

**Comment by mbastian** [comment]
It's curious, the property panel just doesn't show up. Would you mind copy/pasting your log (Window > Output) here as well? Thanks.

**Comment by Bortseb** [comment]
I am having this problem now too.

here is the contents of my output log:

[INFO] Turning on modules: 
[INFO] 	org.openide.util.lookup [8.32.1 201510222201]
	org.openide.util [9.5.1 201510222201]
	org.openide.util.ui [9.4.1 201510222201]
	org.openide.modules [7.47.1 201510222201]
	org.openide.filesystems [9.8.1 201510222201]
	org.netbeans.api.annotations.common/1 [1.26.1 201510222201]
	org.openide.awt [7.65.1 201510222201]
	org.gephi.utils.longtask [0.9.0 0.9.0 201512201821]
	org.gephi.project.api [0.9.0 0.9.0 201512201821]
	org.gephi.graph.api [0.9.0.1 0.9.0 201602011848]
	org.gephi.core.library.wrapper [0.9.0 0.9.0 201512201821]
	org.gephi.utils [0.9.0 0.9.0 201512201821]
	org.gephi.lib.validation [0.9.0 0.9.0 201512201822]
	org.gephi.ui.utils [0.9.0 0.9.0 201512201824]
	org.netbeans.api.progress/1 [1.46.1 201510222201]
	org.netbeans.api.progress.nb [1.46.1 201510222201]
	org.openide.dialogs [7.41.1 201510222201]
	org.gephi.io.exporter.api [0.9.0 0.9.0 201512201821]
	org.gephi.desktop.io.export [0.9.0 0.9.0 201512201832]
	org.openide.nodes [7.42.1 201510222201]
	org.openide.windows [6.74.1 201510222201]
	org.gephi.preview.api [0.9.0.3 0.9.0 201602011849]
	uk.ac.ox.oii.sigmaexporter [0.9.0 0.9.0 201602111914]
	org.gephi.ui.propertyeditor [0.9.0 0.9.0 201512201829]
	org.gephi.layout.api [0.9.0.1 0.9.0 201602011850]
	uk.ac.ox.oii.jsonexporter.plugin [2.0.0 2.0.0 201602111914]
	org.netbeans.modules.editor.mimelookup/1 [1.39.1 201510222201]
	org.openide.text [6.66.1 201510222201]
	org.netbeans.swing.tabcontrol [1.54.1 201510222201]
	org.netbeans.swing.outline [1.32.1 201510222201]
	org.openide.explorer [6.61.1 201510222201]
	org.openide.actions [6.38.1 201510222201]
	org.netbeans.modules.queries/1 [1.42.1 201510222201]
	org.netbeans.api.templates [1.6.1 201510222201]
	org.openide.filesystems.nb [9.7.1 201510222201]
	org.openide.loaders [7.63.1 201510222201]
	org.netbeans.api.intent [1.1.1 201510222201]
	org.netbeans.api.io [1.2.1 201510222201]
	org.openide.io [1.48.1 201510222201]
	org.openide.filesystems.compat8 [9.7.1 201510222201]
	org.netbeans.swing.plaf [1.40.1 201510222201]
	org.netbeans.spi.quicksearch [1.26.1 201510222201]
	org.netbeans.modules.templates/1 [1.6.1 201510222201]
	org.netbeans.bootstrap/1 [2.74.1 201510222201]
	org.netbeans.libs.asm [5.2.1 201510222201]
	org.netbeans.core.startup.base [1.61.1.1 1 201510222201]
	org.netbeans.core.startup/1 [1.61.1.1 201510222201]
	org.netbeans.modules.settings/1 [1.48.1 201510222201]
	org.netbeans.modules.sendopts/2 [2.34.1 201510222201]
	org.netbeans.modules.sampler [1.13.1 201510222201]
	org.netbeans.modules.progress.ui [1.32.1 201510222201]
	org.netbeans.modules.keyring [1.23.1 201510222201]
	org.netbeans.core/2 [3.49.1 201510222201]
	org.netbeans.modules.options.api/1 [1.44.1 201510222201]
	org.netbeans.modules.options.keymap [1.36.1 201510222201]
	org.netbeans.modules.masterfs/2 [2.54.1.2 2 201510222201]
	org.netbeans.libs.jna/1 [1.41.1 201510222201]
	org.netbeans.modules.masterfs.windows [1.15.1 201510222201]
	org.netbeans.modules.masterfs.ui [2.2.1.2 201510222201]
	org.netbeans.modules.masterfs.nio2 [1.14.1 201510222201]
	org.netbeans.modules.keyring.fallback [1.7.1 201510222201]
	org.netbeans.modules.keyring.impl [1.23.1 201510222201]
	org.netbeans.modules.autoupdate.services [1.51.1 201510222201]
	org.netbeans.modules.autoupdate.ui [1.44.1 201510222201]
	org.netbeans.modules.autoupdate.cli [1.12.1 201510222201]
	org.netbeans.libs.jna.platform/1 [1.10.1 201510222201]
	org.netbeans.core.windows/2 [2.80.1 201510222201]
	org.netbeans.core.ui/1 [1.44.1 201510222201]
	org.netbeans.core.output2/1 [1.40.1 201510222201]
	org.netbeans.core.network [1.9.1 201510222201]
	org.netbeans.core.nativeaccess/1 [1.30.1 201510222201]
	org.netbeans.core.multitabs/1 [1.11.1.1 1 201510222201]
	org.netbeans.core.io.ui/1 [1.29.1 201510222201]
	org.gephi.layout.plugin [0.9.0 0.9.0 201512201829]
	org.icculus.chunky.gephigraphviz [1.0.0 1.0.0 201602111915]
	org.gephi.db.drivers [0.9.0 0.9.0 201512201823]
	org.gephi.io.importer.api [0.9.0 0.9.0 201512201823]
	org.gephi.ui.library.wrapper [0.9.0 0.9.0 201512201822]
	org.gephi.ui.components [0.9.0 0.9.0 201512201824]
	org.gephi.mostrecentfiles.api [0.9.0 0.9.0 201512201826]
	org.gephi.desktop.project [0.9.0.1 0.9.0 201602011850]
	org.gephi.welcome.screen [0.9.0 0.9.0 201512201827]
	org.gephi.datalab.api [0.9.0.3 0.9.0 201602011849]
	org.gephi.visualization.api [0.9.0 0.9.0 201512201822]
	org.gephi.tools.api [0.9.0 0.9.0 201512201826]
	org.gephi.gleem [0.9.0 0.9.0 201512201826]
	org.gephi.visualization [0.9.0.4 0.9.0 201602011850]
	org.gephi.algorithms.plugin [0.9.0 0.9.0 201512201826]
	org.gephi.tools.plugin [0.9.0 0.9.0 201512201827]
	org.gephi.statistics.api [0.9.0.1 0.9.0 201602011849]
	org.gephi.statistics.plugin [0.9.0 0.9.0 201512201825]
	org.gephi.appearance.api [0.9.0.3 0.9.0 201602011850]
	org.gephi.filters.api [0.9.0.1 0.9.0 201602011849]
	org.gephi.filters.plugin [0.9.0.2 0.9.0 201602011850]
	org.gephi.timeline.api [0.9.0.1 0.9.0 201602011850]
	org.gephi.statistics.plugin.ui [0.9.0 0.9.0 201512201825]
	org.gephi.settings.upgrader [0.9.0 0.9.0 201512201824]
	org.gephi.project.ui [0.9.0 0.9.0 201512201824]
	org.gephi.io.processor.plugin [0.9.0 0.9.0 201512201823]
	org.gephi.processor.plugin.ui [0.9.0 0.9.0 201512201823]
	org.gephi.preview.plugin [0.9.0.1 0.9.0 201602011849]
	org.gephi.io.exporter.preview [0.9.0.1 0.9.0 201602011849]
	org.gephi.preview.export.ui [0.9.0 0.9.0 201512201822]
	org.gephi.perspective.api [0.9.0 0.9.0 201512201832]
	org.gephi.linkfluence [1.0.9 0.9.0 201602111914]
	org.gephi.kbrace.filter [1.0.0 1.0.0 201602111914]
	org.gephi.io.importer.plugin [0.9.0.1 0.9.0 201602011851]
	org.gephi.io.generator.api [0.9.0 0.9.0 201512201828]
	org.gephi.io.generator.plugin [0.9.0 0.9.0 201512201828]
	org.gephi.io.exporter.plugin [0.9.0 0.9.0 201512201829]
	org.gephi.import.plugin.ui [0.9.0 0.9.0 201512201832]
	org.gephi.gephi.branding [0.9.0 0.9.0 201512201821]
	org.gephi.geometricTransformation [1.0 100511]
	org.gephi.geolayout.plugin [0.9.0 0.9.0 201602111914]
	org.gephi.generator.plugin.ui [0.9.0 0.9.0 201512201828]
	org.gephi.desktop.banner [0.9.0 0.9.0 201512201832]
	org.gephi.filters.plugin.ui [0.9.0 0.9.0 201512201833]
	org.gephi.filters.impl [0.9.0.1 0.9.0 201602011851]
	org.gephi.export.plugin.ui [0.9.0 0.9.0 201512201831]
	org.gephi.directory.chooser [0.9.0 0.9.0 201512201834]
	org.gephi.desktop.tools [0.9.0 0.9.0 201512201834]
	org.gephi.desktop.timeline [0.9.0 0.9.0 201512201834]
	org.gephi.desktop.statistics [0.9.0.1 0.9.0 201602011850]
	org.gephi.desktop.recent.files [0.9.0 0.9.0 201512201831]
	org.gephi.desktop.progress [0.9.0 0.9.0 201512201828]
	org.gephi.desktop.preview [0.9.0 0.9.0 201512201833]
	org.gephi.desktop.layout [0.9.0 0.9.0 201512201833]
	org.gephi.desktop.import [0.9.0 0.9.0 201512201833]
	org.gephi.desktop.generate [0.9.0 0.9.0 201512201829]
	org.gephi.desktop.filters [0.9.0.1 0.9.0 201602011851]
	org.gephi.desktop.datalab [0.9.0.6 0.9.0 201602011850]
	org.gephi.desktop.context [0.9.0 0.9.0 201512201827]
	org.gephi.desktop.branding [0.9.0 0.9.0 201512201828]
	org.gephi.appearance.plugin [0.9.0 0.9.0 201512201830]
	org.gephi.appearance.plugin.ui [0.9.0 0.9.0 201512201830]
	org.gephi.desktop.appearance [0.9.0 0.9.0 201512201830]
	org.gephi.datalab.plugin [0.9.0.1 0.9.0 201602011851]
	nl.cloudfarming.client.lib.platform.l10n [1.1 1.1-NB80 201411231331]
	edu.buaa.act.gephi.plugin.node.color.manager [1.0.0 1.0.0 201602111915]
	cz.cvut.fit.gephi.multimode [1.0.0 1.0.0 201602111914]
 
[INFO] System network proxy resolver: Windows 
[INFO] Windows system proxy resolver: auto detect 
[INFO] System network proxy reloading succeeded. 
[INFO] System network proxy - mode: direct 
[INFO] System network proxy: fell to default (correct if direct mode went before) 
[INFO] USG_LOOK_AND_FEEL 
[WARNING] Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5. 
[INFO] GL_VENDOR: NVIDIA Corporation 
[INFO] GL_RENDERER: GeForce GTX 560/PCIe/SSE2 
[INFO] GL_VERSION: 4.5.0 NVIDIA 358.91 
[INFO] GL_SURFACE_SCALE: 1 
[INFO] Diagnostic information
Input arguments:
	-Xms64m
	-Xmx512m
	-Xverify:none
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-XX:MaxPermSize=256m
	-Dnetbeans.user.dir=C:\Program Files (x86)\Gephi-0.9.0\bin
	-Djdk.home=C:\Program Files\Java\jre7
	-Dnetbeans.home=C:\Program Files (x86)\Gephi-0.9.0\platform
	-Dnetbeans.user=C:\Users\Rob's PC\AppData\Roaming\.gephi\0.9.0\dev
	-Dnetbeans.default_userdir_root=
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\Rob's PC\AppData\Roaming\.gephi\0.9.0\dev\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Dnetbeans.dirs=C:\Program Files (x86)\Gephi-0.9.0\platform;C:\Program Files (x86)\Gephi-0.9.0\gephi
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 64.0MB maximum 455.0MB
Non heap memory usage: initial 23.4MB maximum 304.0MB
Garbage collector: PS Scavenge (Collections=8 Total time spent=0s)
Garbage collector: PS MarkSweep (Collections=0 Total time spent=0s)
Classes: loaded=6251 total loaded=6251 unloaded 0
 
[INFO] Total memory 17,155,522,560 
[INFO] Total physical memory 17,155,522,560 
[WARNING] Not all children in Menu/Window/ marked with the position attribute: [cz-cvut-fit-gephi-multimode-MultiModeWindowTopComponent.shadow], but some are: [org-gephi-desktop-clustering-ContextTopComponent.shadow, org-gephi-desktop-datalab-DataTableTopComponent.shadow, org-gephi-desktop-filters-FiltersTopComponent.shadow, org-gephi-visualization-component-GraphTopComponent.shadow, org-gephi-desktop-layout-LayoutTopComponent.shadow, org-netbeans-core-io-ui-IOWindowAction.shadow, org-gephi-desktop-preview-PreviewTopComponent.shadow, org-gephi-desktop-preview-PreviewSettingsTopComponent.shadow, org-gephi-desktop-appearance-AppearanceTopComponent.shadow, org-gephi-desktop-welcome-WelcomeAction.shadow, org-gephi-desktop-statistics-StatisticsTopComponent.shadow, org-gephi-desktop-timeline-TimelineWindowAction.shadow, Separator4_1.instance, Separator3.instance, ConfigureWindow, org-netbeans-core-windows-actions-ResetWindowsAction.shadow, Separator4.instance, CloseWindowAction.shadow, GroupsMenuAction.shadow] 
[WARNING] Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url 
[WARNING] Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url 
[INFO] # Nodes loaded: 50 
[INFO] # Edges loaded: 65 
[SEVERE] null 
java.lang.AbstractMethodError
	at org.gephi.filters.FilterLibraryImpl.buildBuildersMap(FilterLibraryImpl.java:92)
	at org.gephi.filters.FilterLibraryImpl.getBuilder(FilterLibraryImpl.java:137)
	at org.gephi.desktop.filters.FilterPanelPanel$1.run(FilterPanelPanel.java:119)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by eduramiba** [comment]
This is probably due to the fact that we broke API compatibility in commit 4e427d38ad72310565a5ad5cd864e11faacecf8b after 0.9.0 release and having KBraces filter plugin installed, which was compiled with 0.9.0 release API.

**Comment by Brasidas66** [comment]
Exactly the same issue here, my filters have no parameters. I am working with Gephi 0.9 on a mac OS X 10.11.13. Have you heard of a solution?

**Comment by rbsam** [comment]
The solution I have found is to re-install version 0.9 without the update 0.9.0.4.
After installation it will prompt you to install the updates. I just say no for now, until a solution is found.
I tried to install the updates without the api for filters but it says that other updates require the api for filters.

**Comment by mbastian** [comment]
This issue has been fixed in Gephi 0.9.1. Closing.

**Comment by jimmymathews** [comment]
I seem to have this exact problem in Gephi 0.9.2. Unfixed?
