### ISSUE TITLE
Gephi 0.9 bug saving projects that are in Geo Layout?

### ISSUE THREAD

**Issue by ofr1tz** [gephi/gephi#1373]
After saving project files in Gephi 0.9 while in GeoLayout, I do not manage to load these project files anymore -- they seem to be corrupted. If I change the layout just before saving, there is no problem with the file. Possibly a bug?

Using gephi 0.9 on Windows 10.

**Comment by mbastian** [comment]
Yes, I can reproduce the issue. Thanks for the report.

**Comment by mbastian** [comment]
This is fixed by modifying the layout initialization code. When the layout is obtained from the builder the `setGraphModel()` method is now called before the

**Comment by mbastian** [comment]
Layout developers should 1. Avoid to call `resetPropertiesValues()` from the layout's constructor and 2. Make sure to use the local `graphModel` instead of obtaining a new one from `GraphController` if needed in `resetPropertiesValues`

**Comment by mbastian** [comment]
I updated the GeoLayout plugin to a new version with the workaround. Please try again.

**Comment by ofr1tz** [comment]
Thanks a lot, the problem is resolved with the update!
