### ISSUE TITLE
Gephi 0.9 is not launching on Windows 7

### ISSUE THREAD

**Issue by AnnieW2014** [gephi/gephi#1375]
Hi, I have downloaded and installed version 0.9 on my pc and Gephi won't start.  The orange scroll bar goes approximately 3/4 of the way and then it stays there.  I have tried this on a couple of pcs.  Is this a known issue with a fix?

Thank You

**Comment by mbastian** [comment]
What is your configuration and operating system?

**Comment by danieldfjug** [comment]
Same problem here. Gephi 0.9, Window 7 Enterprise (64 bit), SP1, 16 GB RAM, Stuck at "Starting modules..."

**Comment by mbastian** [comment]
What is your graphic card? Did you update the drivers?

**Comment by AnnieW2014** [comment]
CPU @ 3.2 GHz, 8G RAM, 64 bit,
Windows 7 Enterprise
Graphics: Intel HD Graphics 4600

Thank you very much!
Annie

**Comment by rpkehoe** [comment]
I am encountering the same issue as AnnieW2014, also on Windows 7 Ent, and Intel Graphics.  Tried 0.9 and 0.9.1 on Java 7 and 8.  Log does not provide anything useful.

**Comment by sleepycat** [comment]
The Netbeans project has a [bug](https://netbeans.org/bugzilla/show_bug.cgi?id=246262) that sounds like it might be relevant.

**Comment by rpkehoe** [comment]
Thanks @sleepycat, that bug report looked very promising, but it did not pan out.  I tried cleaning out AppData\Local\Temp, but Gephi still froze on "Starting Modules".  I also did a thread dump, and it did not show the same message referenced in the bug.  I have attached that dump if it is useful.

[gephi_thread_dump.txt](https://github.com/gephi/gephi/files/153473/gephi_thread_dump.txt)

**Comment by eduramiba** [comment]
Tracking at 1631
