### ISSUE TITLE
Parameters on Filters not appearing after updat 0.904

### ISSUE THREAD

**Issue by rbsam** [gephi/gephi#1376]
I just updated my Gephi 0.9 version with some gephi files sent by gephi itself on 02/13/16. Once I restarted the software the filters had no parameters anymore. It shows some log files but it didn't send.
I had to reinstall the 0.9 version to work again.

**Comment by Bortseb** [comment]
Same as #1370 ?

**Comment by eduramiba** [comment]
Duplicate of #1370
