### ISSUE TITLE
Overlapping nodes

### ISSUE THREAD

**Issue by mikedascalu** [gephi/gephi#1385]
After migrating to version 0.91 from 0.82, all manually generated graphs have all their nodes overlapped. I've tried different layouts, but nothing seems to change the way they are generated. The edges are there, but everything is merged in one central node.

Even this simple random graph is displayed wrongly (see attached pdf).

What is the problem? Am I doing something wrong? I've tried different approaches from all demos, but nothing has fixed this. Only a RandomGraph works well when generating graphs from Java code.

Thanks!
Mihai

		// Init a project - and therefore a workspace
		ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
		pc.newProject();
		Workspace workspace = pc.getCurrentWorkspace();

		// Get a graph model - it exists because we have a workspace
		GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel(workspace);
		DirectedGraph graph = graphModel.getDirectedGraph();
		PreviewModel model = Lookup.getDefault().lookup(PreviewController.class).getModel();
		AppearanceController appearanceController = Lookup.getDefault().lookup(AppearanceController.class);
		AppearanceModel appearanceModel = appearanceController.getModel();

		// Create random graph nodes and edges
		Node[] n = new Node[100];
		for (int i = 0; i < 100; i++) {
			n[i] = graphModel.factory().newNode(i + "");
			n[i].setLabel("Node " + i);
			graph.addNode(n[i]);
		}

		for (int i = 0; i < 1000; i++) {
			int j = (int) (Math.random() * 100);
			int k = (int) (Math.random() * 100);
			Edge e = graphModel.factory().newEdge(n[j], n[k], 0, 1.0, true);
			graph.addEdge(e);
		}

		Edge e = graphModel.factory().newEdge(n[99], n[0], 0, 1.0, true);
		graph.addEdge(e);

		// Count nodes and edges
		System.out.println("Nodes: " + graph.getNodeCount() + " Edges: " + graph.getEdgeCount());

		//run ForceAtlas 2 layout
		ForceAtlas2 layout = new ForceAtlas2(null);
		layout.setGraphModel(graphModel);
		layout.resetPropertiesValues();

		layout.setOutboundAttractionDistribution(false);
		layout.setEdgeWeightInfluence(1.5d);
		layout.setGravity(10d);
		layout.setJitterTolerance(.02);
		layout.setScalingRatio(15.0);
		layout.initAlgo();

		// Get Centrality
		GraphDistance distance = new GraphDistance();
		distance.setDirected(true);
		distance.execute(graphModel);

		// Rank color by Degree
		Function degreeRanking = appearanceModel.getNodeFunction(graph, AppearanceModel.GraphFunction.NODE_DEGREE,
				RankingElementColorTransformer.class);
		RankingElementColorTransformer degreeTransformer = (RankingElementColorTransformer) degreeRanking
				.getTransformer();
		degreeTransformer.setColors(new Color[] { new Color(0xFEF0D9), new Color(0xB30000) });
		degreeTransformer.setColorPositions(new float[] { 0f, 1f });
		appearanceController.transform(degreeRanking);

		// Rank size by centrality
		Column centralityColumn = graphModel.getNodeTable().getColumn(GraphDistance.BETWEENNESS);
		Function centralityRanking = appearanceModel.getNodeFunction(graph, centralityColumn,
				RankingNodeSizeTransformer.class);
		RankingNodeSizeTransformer centralityTransformer = (RankingNodeSizeTransformer) centralityRanking
				.getTransformer();
		centralityTransformer.setMinSize(3);
		centralityTransformer.setMaxSize(10);
		appearanceController.transform(centralityRanking);

		// Preview
		model.getProperties().putValue(PreviewProperty.SHOW_NODE_LABELS, Boolean.TRUE);
		model.getProperties().putValue(PreviewProperty.EDGE_COLOR, new EdgeColor(Color.GRAY));
		model.getProperties().putValue(PreviewProperty.EDGE_THICKNESS, new Float(0.1f));
		model.getProperties().putValue(PreviewProperty.NODE_LABEL_FONT,
				model.getProperties().getFontValue(PreviewProperty.NODE_LABEL_FONT).deriveFont(8));

		// Export
		ExportController ec = Lookup.getDefault().lookup(ExportController.class);
		try {
			ec.exportFile(new File("out/test.pdf"));
		} catch (IOException ex) {
			ex.printStackTrace();
			return;
		}

[test.pdf](https://github.com/gephi/gephi/files/138632/test.pdf)

**Comment by eduramiba** [comment]
Hi,
For performance reasons, nodes no longer have random positions on creation.
You will need to set their x and y coordinates.

This is the way it is done in datalab:
```java
//Set random position to the 
newNode.setX((float) ((0.01 + Math.random()) * 1000) - 500);
newNode.setY((float) ((0.01 + Math.random()) * 1000) - 500);
```

**Comment by mikedascalu** [comment]
Worked like a charm!

Thanks a lot and have a great weekend!
