### ISSUE TITLE
Add warning when element IDs match without special characters such as new lines

### ISSUE THREAD

**Issue by JohnKomov** [gephi/gephi#1388]
Hi. I found that 'JohnKomov' and 'JohnKomov\n' are the different names for merging code and the same ones for Gephi itself. The result of such duality is a Java Exception and two nodes with the same visible names and different sets of edges. Check out other non-alphabetical symbols too (I didn't check).

**Comment by mbastian** [comment]
I'm sorry but that is a input issue. We don't want to introduce rules such as cleaning '\n' from input ids or labels as it could introduce confusion. However, it could be added as a "Warning" for instance in the import report.

**Comment by mbastian** [comment]
We already have a import container validation step that is designed to iterate over all the elements and is capable of adding errors and warnings.

### Definition of done
- Add a new warning when element ids contain special characters.

The list of special characters is up for discussion. At the very list newline characters. Leading or trailing whitespaces might be nice as well.
