### ISSUE TITLE
Stuck on DOT import

### ISSUE THREAD

**Issue by praseodym** [gephi/gephi#1391]
When the [attached graph (DOT)](https://github.com/gephi/gephi/files/142297/model.zip) is opened in Gephi, it will be stuck importing forever (left it running for about 12 hours), seemingly without progress.

The problem occurs with this file on at least Gephi 0.9.2-snapshot and 0.9.1, Linux and Windows.

**Comment by eduramiba** [comment]
Confirmed, thanks for the report!

**Comment by eduramiba** [comment]
Please test with latest 0.9.2 snapshot when the new build is done.

**Comment by Biplobphukan007** [comment]
showing error.. cannot run program "dot".
