### ISSUE TITLE
RankingController cannot be resolved to a type

### ISSUE THREAD

**Issue by JavaCoreDeveloper** [gephi/gephi#1393]
The dependency i'm using is as follows.

`
<dependency>
            <groupId>org.gephi</groupId>
            <artifactId>gephi-toolkit</artifactId>
            <version>0.9.1</version>
</dependency>
`
I'm following the method given in release notes of **gephi-toolkit 0.9.1**. But of no use.
Kindly let me know how can i use it  Any help will be appreciated. Thanks in advance.

**Comment by eduramiba** [comment]
Hi,
Ranking and partition are now part of Appearance API https://gephi.org/gephi/0.9.1/apidocs/org/gephi/appearance/api/package-summary.html
