### ISSUE TITLE
getNeighbours of node in directed graph

### ISSUE THREAD

**Issue by AmaniChou** [gephi/gephi#1397]
when I use the getNieghbours method in a directed graph I get all the neighbours that connect to the node regardless the edges direction. 
I need to get two lists of node: one for the neighbours that are connected with an outcoming edge and one with an incoming edge.
Please let me know if there is any way to do it. 
Thanks

**Comment by eduramiba** [comment]
You need to call getDirectedGraph on GraphModel and then use methods there https://gephi.org/gephi/0.9.1/apidocs/org/gephi/graph/api/DirectedGraph.html
