### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by paulgrant999** [gephi/gephi#1403]
where the hell is the ability to import attributes in 9.0?  How hard would it be to map an incoming field to an attribute?  Stick an extra field for christs sake.  I shouldn't have to resort to  "recast-column" to do map a data field to a visualization attribute.  its fucking retarded.

and how the hell do you have a network visualization software, that doesn't bloody recognize Cartesian coordinates?  do the words "epic fucking fail" come to mind?

shit, at least let me export/import the damn attributes so I can modify them without having to write a fucking plugin!

it absolutely boggles the mind that this sort of basic functionality is missing in your 9.0 version; yet your 9.0 version is the one being pushed on the damn download page; I reverted back to your 8.2 beta, only to find that the damn repository for plugins isn't working.

so in clear terms:
- extend your import utility so you can map fields to attributes
- add an import/export XML feature that allows you to dump the attributes into an xml tree (think annotated data table by id) and then lets you reimport it (once you've merged/munged).

I'm off to download your beta again on the off-chance I can add the plugin manually, munge the data in the 8.2 version, and then re-open in 9.0.

WTF?

**Comment by eduramiba** [comment]
There are many ways to import data into Gephi: https://gephi.org/users/supported-graph-formats
GEXF is the most powerful and is XML.

Also I will close your issue as it's incorrect and incredibly rude.
