### ISSUE TITLE
Neo4j support

### ISSUE THREAD

**Issue by karthun** [gephi/gephi#1404]
Hi,

I am using the Neo4J database and I would like to connect to this database from gephi.

I found a Neo4J plugin but unfortunately I was not able to install it.

I am using Ne04J 2.3.2  and gephi 0.9.1

Regards
Cyrille Schlogel

**Comment by eduramiba** [comment]
Hi Cyrille,
The plugin at https://marketplace.gephi.org works only in Gephi 0.8.2.

The plugin still needs to be adapted to 0.9.1

**Comment by karthun** [comment]
Thanks! I have installed version 0.8.2 and I can now use the plugin.

**Comment by mbastian** [comment]
Closing old issue, a new Neo4j plugin was just developed and released. Checkout https://gephi.org/plugins/#/plugin/neo4j-plugin
