### ISSUE TITLE
Gephi doesn't handle newlines in GV files properly:

### ISSUE THREAD

**Issue by mik01aj** [gephi/gephi#1406]
For this file:

```
digraph {
"abc" [label="a
b
c"]
"abc" -> "def"
}
```

This is the GraphViz output:

![a](https://cloud.githubusercontent.com/assets/3027415/13427253/0e6e8402-dfb3-11e5-86a3-6b98d39a50be.png)

But Gephi can't read it properly:

![image](https://cloud.githubusercontent.com/assets/3027415/13427266/1f32f854-dfb3-11e5-8e80-167a2fd7d6c7.png)

And this is how the imported graph looks like:

![image](https://cloud.githubusercontent.com/assets/3027415/13427280/2f8c27ac-dfb3-11e5-9f47-e0fe930083bd.png)

**Comment by KyleBrooks242** [comment]
I've tried reproducing the problem with the same graph, it imports correctly. What version of Gephi are you using? The latest (version 0.9.2) does not have this issue.

**Comment by mik01aj** [comment]
I use `0.9.1`.

**Comment by wetneb** [comment]
Closing seems this seems to have been fixed in 0.9.2 as mentioned above.
