### ISSUE TITLE
0.8.2. Plugin Catalog Issues

### ISSUE THREAD

**Issue by venlogic** [gephi/gephi#1409]
The plugin catalog for 0.8.2 does not allow me to download the plugins.
I tried installing Circular Layout and got the message attached.
Regards,
Rob

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/994961/13484669/be56b39c-e0b4-11e5-856e-79c4bee0092f.png)

**Comment by wetneb** [comment]
Hi @venlogic, I think most of these plugins have been updated to later versions of Gephi, so I would recommend upgrading your Gephi install first.
