### ISSUE TITLE
Cannot translate node color attribute to graph from .gexf file.

### ISSUE THREAD

**Issue by akshayparopkari** [gephi/gephi#1414]
I am writing out all my graph node color hex numbers in a .gexf file via NetworkX's [write_gexf()](https://networkx.readthedocs.org/en/stable/reference/generated/networkx.readwrite.gexf.write_gexf.html#networkx.readwrite.gexf.write_gexf) function. When I import the file into Gephi 0.9.1 and check the nodes in my data table, I can view a "color" attribute for my nodes. I have specific colors for nodes based on various factors, and I need to color my nodes using the values from  "color" column. However, when I go into appearance window node attributes to color using the "color" column, it does not work. It seems as if the "color" column hex numbers are taken into the palette as labels, but their corresponding color bars do not reflect the hex number's color. Is there a way to read the "color" column from .gexf file and use the hex values as node colors? This issue might be similar to #1275 

Attached is the .gexf file that I am using for my graph.
[category_subset1.gexf.zip](https://github.com/gephi/gephi/files/159130/control.gexf.zip)

**Comment by vahidthegreat** [comment]
Hi bro. I have the same problem? How did you solve it finally?

**Comment by mbastian** [comment]
For the color to be recognised, it needs to be encoded in the **viz** section, see https://gexf.net/viz.html for details. I believe the NetworkX writer supports this now.
