### ISSUE TITLE
How to group all nodes from the same category as one big node in gephi 0.9?

### ISSUE THREAD

**Issue by dingdingxia** [gephi/gephi#1416]
Hi all, in gephi 0.8.2 there is a button "group" in the partition tab. However I cannot find it in gephi 0.9. I want to aggregate the individual nodes to group level. For example, if i have 20 boys and 18 girls, i just want to plot two nodes one presents boy and the other for girl. 

Thank you!

**Comment by eduramiba** [comment]
Hi,
Hierarchy support was removed in Gephi 0.9.0 for performance and simplicity improvements.
You can read all the changes here: https://github.com/gephi/gephi/releases/tag/v0.9.0

**Comment by dingdingxia** [comment]
Thank you! But may i ask why? Is it not a good practice to see the hierarchical structure?

**Comment by eduramiba** [comment]
It was very difficult to maintain and made the code too complex.

**Comment by dingdingxia** [comment]
I see. Thank you again!
