### ISSUE TITLE
Linux Tutorial

### ISSUE THREAD

**Issue by cschwem2er** [gephi/gephi#1417]
As several users report crashes when using Linux (#1192)  and a temporary fix was suggested by @3ruce, it would be very nice to have a short tutorial for two things:

1) How to add Gephi as a PPA repository, so that linux (ubuntu/ mint) users always get the latest version
2) How to enable options like "LIBGL_ALWAYS_SOFTWARE=1" without having to start Gephi via the terminal each time.

**Comment by wetneb** [comment]
Thanks for the suggestion! I think this would belong on the website so I have migrated this issue there:
https://github.com/gephi/gephi.github.io/issues/36
