### ISSUE TITLE
import spreadsheet (csv) The id class does not match with the expected type

### ISSUE THREAD

**Issue by eindzl** [gephi/gephi#1418]
Hello, 
I just moved to gephi 0.9.1 from gephi 0.8.2. I'm trying to add some columns to my nodes data table and I get the following error:

> java.lang.IllegalArgumentException: The id class does not match with the expected type (java.lang.Integer)
>   at org.gephi.graph.impl.NodeImpl.checkIdType(NodeImpl.java:248)
>   at org.gephi.graph.impl.NodeImpl.<init>(NodeImpl.java:38)
>   at org.gephi.graph.impl.GraphFactoryImpl.newNode(GraphFactoryImpl.java:99)
>   at org.gephi.datalab.impl.GraphElementsControllerImpl.buildNode(GraphElementsControllerImpl.java:394)
>   at org.gephi.datalab.impl.GraphElementsControllerImpl.createNode(GraphElementsControllerImpl.java:91)
>   at org.gephi.datalab.impl.AttributeColumnsControllerImpl.importCSVToNodesTable(AttributeColumnsControllerImpl.java:677)
> [catch] at org.gephi.datalab.plugin.manipulators.general.ui.ImportCSVUIWizardAction.performAction(ImportCSVUIWizardAction.java:112)
>   at org.gephi.datalab.plugin.manipulators.general.ImportCSV.execute(ImportCSV.java:62)
>   at org.gephi.datalab.api.DataLaboratoryHelper$5.run(DataLaboratoryHelper.java:325)

I don't understand what's happening. I'm creating the csv file exporting from gephi and then I add new data in Excel.
I have tried with example network Les Miserables and it works fine, so it is probably something in my network, but no clue on what can it be.
Only thing different I've noticed from gephi 0.8.2 is that node's Ids no longer have decimal point, before I had: 0.0, 1.0... now I have: 0, 1...
Any suggestions?
Thank you.

**Comment by eindzl** [comment]
I just realized when importing the Id column is marked as "Interger" in my network while in the example is marked as "string".

**Comment by eduramiba** [comment]
Hi,
The id type should be String, what steps do you follow before importing the CSV?

Do you open a gexf file or similar?

**Comment by eindzl** [comment]
Hi,
The file was a .gephi file created in gephi 0.8.2. To import the csv I press the "Import Spreadsheet" button in the "Data Table" tab and follow the steps.

However, I no longer use that file. I created a new one from scratch in gephi 0.9.1 and I don't have any problems now, so I think the problem was somehow related to the fact that the original network was created with the older version.

**Comment by eduramiba** [comment]
I see, then it seems that loading an old .gephi project file will cause the id column to be an integer instead of a String.
Thanks for the report!

**Comment by eduramiba** [comment]
Fixed, will be released with next updates.
