### ISSUE TITLE
Allow arbitrary names of columns when importing from CSV

### ISSUE THREAD

**Issue by darkoc** [gephi/gephi#1424]
At the moment, when you import nodes and edges from CSV files, columns such as Id, Label, Source, Target have to be present in the CSV.
Is there any particular reason why these columns can't be specified in the Import Wizzard by selecting which column contains Ids and so on?

**Comment by eduramiba** [comment]
These names are enforced for code simplicity, since changing the header of a CSV should be quick and easy.

**Comment by darkoc** [comment]
I understand that. I just feel that it would improve the user friendliness if this is flexible.
