### ISSUE TITLE
Error saving any dynamic network in gexf format

### ISSUE THREAD

**Issue by kbaltakys** [gephi/gephi#1426]
I want to save a dynamic network in Gephi, to gexf file format, however even if I try to save the most simple dynamic network, gexf file abruptly ends in the midle of first edge definition : `<edge id="0" source="0" target="1"`

I figured to make a small graph in Gephi, with 4 nodes:
![image](https://cloud.githubusercontent.com/assets/12213184/13772766/87acaaa6-ea9e-11e5-9835-15e70d7f7d1b.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13772782/9c1c796c-ea9e-11e5-89f5-09849fac1a4a.png)

One link:
![image](https://cloud.githubusercontent.com/assets/12213184/13772797/aed65cee-ea9e-11e5-97a2-b8757ffa9621.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13772837/e6bb2ae0-ea9e-11e5-88b0-52894d0eebe1.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13772849/fa9f84c0-ea9e-11e5-8ba2-d4e4e3e8cc03.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13773037/edd1f632-ea9f-11e5-94a4-c4ca2d034f70.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13772868/0efead24-ea9f-11e5-9621-52761eae5d90.png)

![image](https://cloud.githubusercontent.com/assets/12213184/13772885/284cdd64-ea9f-11e5-8de1-613a98d2eb06.png)

And then the whole output from in the gexf file is:

```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.3" version="1.3" xmlns:viz="http://www.gexf.net/1.3/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.3 http://www.gexf.net/1.3/gexf.xsd">
  <meta lastmodifieddate="2016-03-15">
    <creator>Gephi 0.9</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="undirected" timeformat="date" timerepresentation="interval" mode="dynamic">
    <attributes class="edge" mode="dynamic">
      <attribute id="weight" title="Weight" type="double"></attribute>
    </attributes>
    <nodes>
      <node id="0" label="0">
        <viz:size value="10.0"></viz:size>
        <viz:position x="-188.27417" y="121.794495"></viz:position>
      </node>
      <node id="1" label="1">
        <viz:size value="10.0"></viz:size>
        <viz:position x="-319.27448" y="451.20123"></viz:position>
      </node>
      <node id="2" label="2">
        <viz:size value="10.0"></viz:size>
        <viz:position x="471.24677" y="126.6817"></viz:position>
      </node>
      <node id="3" label="4">
        <viz:size value="10.0"></viz:size>
        <viz:position x="-309.86188" y="-274.00354"></viz:position>
      </node>
    </nodes>
    <edges>
      <edge id="0" source="0" target="1"
```

Am I doing something wrong or is this a bug?
I would like to use Gephi for the analysis and visualization of dynamic networks, but for that I need to be able to save the dynamics into a file :) Any suggestions are welcome.

**Comment by eduramiba** [comment]
Hi, there is currently a known bug when converting weight column to dynamic from Data laboratory.
Maybe you can workaround this by loading an empty gexf with dynamic weight.

**Comment by kbaltakys** [comment]
Could you explain a bit what you mean?

**Comment by eduramiba** [comment]
Yeah, I understand you want to create a dynamic network with dynamic weight and fill it manually from data laboratory.
If you convert the weight to dynamic it won't work correctly at the moment.

But I think you can workaround this problem by loading a gexf file without nodes or edges, but with dynamic weight, which works correctly.

Try loading this gexf:

```xml
<gexf xmlns="http://www.gexf.net/1.1draft"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.gexf.net/1.1draft
                             http://www.gexf.net/1.1draft/gexf.xsd"
      version="1.1">
  <graph mode="dynamic" defaultedgetype="directed">
    <attributes class="edge" mode="dynamic">
       <attribute id="weight" title="Weight" type="float"/>
    </attributes>
    <nodes>
    </nodes>
    <edges>
    </edges>
  </graph>
</gexf>
```

**Comment by kbaltakys** [comment]
But even if I load your minimal gexf, add a dynamic edge and try to save it, the same problem persits, i.e. gexf file ands in the middle of 1st edge definition 
```
    <edges>
      <edge id="0" source="0" target="1">
        <attvalues
```

Could you give me an example how the gexf file should look with dynamic edge weight with ``` timerepresentation='timestamp' ``` ?

**Comment by Jonty800** [comment]
I have this same issue when using dynamic weights for both DateTime and Double. Do you know when this is expected to be fixed?

**Comment by eduramiba** [comment]
@Jonty800 This should be fixed in 0.9.2 release, and probably as a 0.9.1 update maybe in 1-2 months.

**Comment by henisz** [comment]
Is this fixed? When I try to layout a graph with dynamic edge weights I get the following error message

java.lang.IllegalStateException: The weight is dynamic, call getWeight(timestamp) or getWeight(interval) instead
at org.gephi.graph.impl.EdgeImpl.getWeight(EdgeImpl.java:87)
at org.gephi.layout.plugin.forceAtlas2.ForceAtlas2.goAlgo(ForceAtlas2.java:199)
at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:184)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)

at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by eduramiba** [comment]
Not fixed yet, sorry, but it's in the list of next issues to fix.

**Comment by henisz** [comment]
Is there a way to visualize dynamic networks with time varying edge weights that doesn't crash the software? My data loads fine but as soon as I try to graph, it crashes. Is there any workaround?

**Comment by eduramiba** [comment]
@henisz I think the problem here is force atlas 2, not able to handle this. Can you open a separate issue? The workaround now would be not using force atlas 2

**Comment by henisz** [comment]
Tried multiple layouts. Similar errors. Which would you recommend?

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by Jonty800** [comment]
@henisz I'm actually going to painfully approach this by having a script which generates multiple gexf files, each representing a window of time, without dynamic edges. Then we can apply the Force Atlas manually to each file.

In my work, I need to produce modularity over time, and this doesn't work with dynamic weights either. So I guess this approach is best for my needs.

**Comment by eduramiba** [comment]
@henisz @Jonty800 Seeing this is also a common issue with layouts, I opened a high priority issue for 0.9.2 milestone: #1709
