### ISSUE TITLE
How imoprt file in gephi 9.1?

### ISSUE THREAD

**Issue by friggx** [gephi/gephi#1430]
I would like to write a plugin which just imported graphml the specified path, but on the 48 line - importController.process (container, proc, workspace);
I get an error NullPointerException
code ->

public class firstImporter {

    ProjectController pc;
    Workspace workspace;
    ImportController importController;
    Container container;
    ContainerLoader lController;
    Processor proc;
    Importer jhon;
    GraphModel graphModel;
    DirectedGraph graph;
    Project startproj;
    String pathPskov;

    public firstImporter(String path) {
        path = "C:\\Users\\Friggx\\NEW\\Graph\\smol.graphml";
        pc = Lookup.getDefault().lookup(ProjectController.class);
        workspace = pc.getCurrentWorkspace();
        importController = Lookup.getDefault().lookup(ImportController.class);

        try {
            File file = new File(path);
            container = importController.importFile(file);
            System.out.println(container.toString());
            container.getLoader().setEdgeDefault(EdgeDirectionDefault.UNDIRECTED);

        } catch (Exception ex) {
            ex.printStackTrace();
            return;
        }
        importController.process(container, proc, workspace);
        graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel();
        graph = graphModel.getDirectedGraph();
    }

}

**Comment by eduramiba** [comment]
It seems your Processor (proc) is not initialized.
You can use DefaultProcessor.

**Comment by friggx** [comment]
Thank you very much, but after starting with DefaultProcessor
the error refers to the tighter line: importController.process (container, new DefaultProcessor (), workspace);

With an error:
at org.gephi.project.impl.ProjectControllerImpl.newWorkspace (ProjectControllerImpl.java:182)
at org.gephi.io.processor.plugin.DefaultProcessor.process (DefaultProcessor.java:93)
at org.gephi.io.importer.impl.ImportControllerImpl.process (ImportControllerImpl.java:273)
at plag.FIrstImporter. <init> (FirstImporter.java:54)

code ->

public class FirstImporter {

     ProjectController pc;
     Workspace workspace;
     ImportController importController;
     Container container;
     ContainerLoader lController;
     Processor proc;
     Importer jhon;
     GraphModel graphModel;
     DirectedGraph graph;
     Project startproj;
     String pathPskov;
     public PskovImporter(String path)
    {
        path = "C:\\Users\\Friggx\\NEW\\Graph\\smol";
        pc = Lookup.getDefault().lookup(ProjectController.class);
        workspace = pc.getCurrentWorkspace();
        importController = Lookup.getDefault().lookup(ImportController.class);
        try {
            File file = new File("C:\\Users\\Friggx\\NEW\\Graph\\smol.graphml");
            container = importController.importFile(file);
            container.getLoader().setEdgeDefault(EdgeDirectionDefault.DIRECTED);
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("second");
            return;
        }
        importController.process(container, new DefaultProcessor(), workspace);  
        GraphController graphController = Lookup.getDefault().lookup(GraphController.class);
	graphModel = graphController.getGraphModel();
    }
}

**Comment by eduramiba** [comment]
I see, is ```workspace``` null?
You might need to create a project with the project controller before getting the current workspace.

**Comment by friggx** [comment]
You are very fast and cool, thanks, I will try

**Comment by friggx** [comment]
All works, thanks again!

code ->

public class FirstImporter {

    ProjectController pc;
    Workspace workspace;
    ImportController importController;
    Container container;
    ContainerLoader lController;
    Processor proc;
    Importer jhon;
    GraphModel graphModel;
    DirectedGraph graph;
    Project startproj;
    String pathPskov;

    public FirstImporter(String path) {
        path = "C:\\Users\\Friggx\\NEW\\Graph\\smol";
        pc = Lookup.getDefault().lookup(ProjectController.class);
        pc.newProject();
	pc.newWorkspace(pc.getCurrentProject());
        workspace = pc.getCurrentWorkspace();
        importController = Lookup.getDefault().lookup(ImportController.class);

        try {
            File file = new File("C:\\Users\\Friggx\\NEW\\Graph\\smol.graphml");
            container = importController.importFile(file);
            container.getLoader().setEdgeDefault(EdgeDirectionDefault.DIRECTED);

        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("second");
            return;

        }
        importController.process(container, new DefaultProcessor(), workspace);

        GraphController graphController = Lookup.getDefault().lookup(GraphController.class);
        graphModel = graphController.getGraphModel();

    }

}

**Comment by eduramiba** [comment]
Great :)
