### ISSUE TITLE
csv data missing some information

### ISSUE THREAD

**Issue by karlhjalte** [gephi/gephi#1431]
Data is exported from excel, and encoding is set to UTF8 (other encoding options also tried). However, some of my primary nodes are missing information when opened in gephi, while others have no problems. There are no special characters in the missing data. 

Attached is the node list in txt format, and a note on which nodes are missing additional information. 

I believe it to be a bug, and not just my own incompetence. 
[Note.txt](https://github.com/gephi/gephi/files/183809/Note.txt)
[node.txt](https://github.com/gephi/gephi/files/183814/node.txt)

**Comment by karlhjalte** [comment]
I should add, I am using Gephi 0.8.2, but the same problems does occur in some degree in the new 0.9 version but can be overrun by importing lists, save as gexf., start new project, and open gexf. 

So still not optimal.

**Comment by duncdrum** [comment]
I can reproduce this on 0.9.1 under OS X 10.11.3, I tried cleaning up the csv files in text editor, and libre office but not luck. Notice the preview of the second node screenshot. 
![screenshot 2016-03-21 20 10 55](https://cloud.githubusercontent.com/assets/6205362/13951839/7be16ef6-f033-11e5-9f44-30110ef8df07.png)

which misses affiliation information after import into gephi, as can be seen in data lab.
![screenshot 2016-03-21 20 11 15](https://cloud.githubusercontent.com/assets/6205362/13951860/9aba6bd4-f033-11e5-9414-b530dbe65adf.png)

**Comment by eduramiba** [comment]
I can confirm this problem, thanks for the report.

**Comment by eduramiba** [comment]
Hi,
This is actually not an issue.

If you filter in your nodes file by ID == 2 for example, you will find 2 rows, and the second one is missing all the attributes, so it just gets overwritten with empty info.

**Comment by eduramiba** [comment]
We should add a warning when we migrate the spreadsheet import to import API (see #1282).

**Comment by eduramiba** [comment]
Can you please try the latest nightly build (https://github.com/gephi/gephi#nightly-builds)? It should include these changes
