### ISSUE TITLE
Feature Request: Duplicate Workspace

### ISSUE THREAD

**Issue by duncdrum** [gephi/gephi#1436]
I could swear that there was a quick way of doing this in 0.8.2. It would be great if the Workspace Menu could get a duplicate workspace command. With large graphs, rectangle select, is not up to the task, of duplicating the current workspace, in a new one for further modelling without loosing the current state of the graph.

**Comment by mbastian** [comment]
Thanks @duncdrum you are totally correct. It had to be removed at some point as it wasn't working well I think.

We've brought it back and rewrote the feature. Now all settings and configurations of the current workspace are duplicated too.
<img width="233" alt="Screenshot 2022-11-09 at 20 19 45" src="https://user-images.githubusercontent.com/234813/200922044-90b50555-6e68-452b-8325-6642c0f840bd.png">

It will be included in the 0.10.0 release.
