### ISSUE TITLE
Phantom Panel

### ISSUE THREAD

**Issue by yhu9** [gephi/gephi#1440]
If I switch to data laboratory from the overview tab with the statistics tab open, the statistics tab will stay open on top of the overview tab. Then, if you close the statistics tab in the data laboratory tab and then switch back to the overview tab then you will get a phantom blank tab that will not disappear until exiting. I'm using Ubuntu 14.04.3 LTS.

**Comment by yhu9** [comment]
Also, I noticed that the modularity function in gephi changed over 0.8.2 to 0.9.1 in that they do not output the same result for an edge list I used before. Here it is in a .txt format.
[Tutorial3_JobScheduleTimesraw.txt](https://github.com/gephi/gephi/files/191366/Tutorial3_JobScheduleTimesraw.txt)

**Comment by eduramiba** [comment]
Do you use randomized modularity? Results will vary slightly.

**Comment by yhu9** [comment]
I did use random modularity and I did notice results of the same version changing slightly however, results from the 0.8.2 to 0.9.1 was a drastic change. The output of the modularity statistic went from finding several groups to finding no groups at all.

**Comment by eduramiba** [comment]
This seems to be the issue #1419

Can you check if it's still happening in 0.9.2 nightly build? (https://github.com/gephi/gephi#nightly-builds)

**Comment by eduramiba** [comment]
Closing old issue
