### ISSUE TITLE
Java error message when running Geo Layout

### ISSUE THREAD

**Issue by leninja** [gephi/gephi#1441]
Hi, 
I am facing a problem when running the Geo Layout in the Gephi 0.9 (I am using Windows 7 Entreprise).

After choosing the Geo Layout in Gephi (I left everything in default --> Scale: 1000; Projection: Mercator), and clicked in Run, I received the following message:

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
at org.gephi.plugins.layout.geo.GeoLayout.goAlgo(GeoLayout.java:144)
at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:185)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

I've tried with other datasets (found here [http://www.martingrandjean.ch/gephi-introduction/#comment-3650]). I followed the specifics parameters from the tutorial (Scale 20000 and projection Mercator), and I got the same message.

I uninstall the plugin and I installed it again and I've tried to run the Geo Layout again with both datasets, and I got the same message again.

I would like to know what that means and If there is a way to solve this problem.

Thank you for your attention.

**Comment by eduramiba** [comment]
This seems a column type validation bug. Please make sure that your longitued and latitude columns have Double type instead of String.

**Comment by leninja** [comment]
Yes, the wrong type of variable in latitude and longitude was causing the problem. 

Thank you so much for your help.

Cheers,

**Comment by eduramiba** [comment]
Fixed in https://github.com/gephi/gephi-plugins/pull/167
