### ISSUE TITLE
node size changed during gexf import

### ISSUE THREAD

**Issue by neil-rubens** [gephi/gephi#1445]
node size changed during gexf import via Gephi app (v. 0.9.1).

Bellow is a sample graph [gist](https://gist.github.com/neil-rubens/efdca499f84a5486ba3e2cf9501e4b8e)

node0 size: `4.0`
node1 size: `20`

When this graph is opened in Gephi app (**unchecking `auto-scale`**);
node1 size changes to `100`.
(could be confirmed via UI; and also exporting graph back to gexf (not using scaling options).

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.3" version="1.3" xmlns:viz="http://www.gexf.net/1.3/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.3 http://www.gexf.net/1.3/gexf.xsd">
  <meta lastmodifieddate="2016-04-01">
    <creator>Gephi 0.9</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="directed" mode="static">
    <nodes>
      <node id="0" label="0">
        <viz:size value="4.0"></viz:size>
        <viz:position x="362.0288" y="-316.0338"></viz:position>
      </node>
      <node id="1" label="1">
        <viz:size value="20.0"></viz:size>
        <viz:position x="-467.90503" y="91.55829"></viz:position>
      </node>
    </nodes>
    <edges></edges>
  </graph>
</gexf>
```

**Comment by smdabdoub** [comment]
I'd like to echo this problem.

I had three different node sizes in the gexf: 1, 25, and 60 and after import they had been changed to 4.0, 43.050846, and 100 respectively.
