### ISSUE TITLE
Streaming Graphs Do Not Appear in Overview

### ISSUE THREAD

**Issue by realkg** [gephi/gephi#1447]
I could be using this wrong, but I have assumed after viewing youtube videos that streamed graphs should appear in the overview.

I can see data (nodes/edges) appears in the Context window and the data appears in the data laboratory, but they do not appear in the overview. I can view a single node when I right click and select "Select on Overview" in the data laboratory.

I am using Gephi 0.9.1 201510222201   and Graph Streaming 1.0.0

**Comment by realkg** [comment]
I've been playing with this and made some progress. When I right click on "Select on Overview" in the data laboratory and switch the the overview tab, I can see a single node like I stated previously. When you take the Drag tool and move the node around, with Force Atlas running, the rest of the nodes and edges pop up as expected. I guess it is a issue with the initial field of view and all of the edges/nodes are stacked on top of each other.

**Comment by lvca** [comment]
Same problem on MacOSX, but even with the @realkg tricks I'm not able to render more than 1 node. I'm using the OrientDB plugin and I can see nodes and edges are loaded correctly (no errors in the report and in the top right area I can see thousands of vertices and edges loaded).

**Comment by dk766** [comment]
I have the same issue (graph data imported successfully but not displayed as a graph). 
I'm running gephi on Ubuntu.

**Comment by lvca** [comment]
I'm sorry guys, but I checked the output and it's correct. It looks like Gephi or the import plugin is broken and nobody cares anymore to get it working :-(

**Comment by eduramiba** [comment]
I have not been able to check this but it's possible that all the nodes are
being created in the default position (0, 0, 0) and very small size. Is
that the case? This could be worked around with random layout and fixed
size ranking of all nodes.

**Comment by dk766** [comment]
I have checked the work-around and for me it only works half way: I can make the labels visible but not the nodes or the edges.
![screenshot from 2016-08-22 11-00-35](https://cloud.githubusercontent.com/assets/18440862/17849152/c0bc527e-6857-11e6-9f44-a71aa27791ce.png)

I think you are right about the initial position but also the size seems disproportionately small related to the screen size.

Even if I could make everything visible its still not good enough since the point of streaming is to display dynamically changing data.

For tests I use the gs-gephi sample code http://github.com/graphstream/gs-gephi

**Comment by eduramiba** [comment]
Yeah, the streaming plugin should now use by default a random position for new nodes, and a size of 10.

Nodes with size = 1 (the default) will be hardly visible. Please try to set a bigger size.

The graph streaming API seems to support setting the initial size of nodes: https://github.com/gephi/gephi/wiki/GraphStreaming so a streaming client could do that until the streaming server includes this change.

I guess with gs-gephi you will need to use `xyz` and `size` attributes, but I am not sure.

**Comment by dk766** [comment]
Thanks for adding it to the Milestone.

**Comment by eduramiba** [comment]
Yeah the problem with random layout is it's not run in a loop.
The other option is to set random x, y, z from your streaming client when creating nodes.

**Comment by lvca** [comment]
Why even if coords are the same, after a layout of the graph they are still invisible?

**Comment by eduramiba** [comment]
That must be because of the default small size.

**Comment by william76** [comment]
This is kind of an old issue, but it's causing problems for me.  Does anyone know if there was anything done on this front?

**Comment by eduramiba** [comment]
@william76 it's planned for 0.9.2

**Comment by eduramiba** [comment]
Fixed in commit https://github.com/gephi/gephi-plugins/commit/755a8641735cba5ad51f846bd6e7433166c92088
Soon a new version of the plugin will be available

**Comment by eduramiba** [comment]
Please install the plugin update in Gephi 0.9.1, it should fix this issue.

When you create a node without a size, default size=10 will be used.
When you create a node without a position, a random one will be used.
