### ISSUE TITLE
Website registration blocks a WRONG IP !!!

### ISSUE THREAD

**Issue by rjalexa** [gephi/gephi#1449]
Dear friends,
I just tried joining the Forums but my registration was blocked with the following message:

"Your IP 188.114.102.118 has been blocked "

This is very strange since I have a public routable static IP address which is 2.236.244.225 (given by my ISP Fastweb here in Rome - Italy).

Can you please check and tell me if there's anything I can to to avoid this ?

Thank you in advance

**Comment by eduramiba** [comment]
Duplicate of #1047
