### ISSUE TITLE
0.9.1 SVG figure exported on a wrong position

### ISSUE THREAD

**Issue by naco-siren** [gephi/gephi#1450]
The graph is always located on the left-top corner, as is shown below:
![image](https://cloud.githubusercontent.com/assets/8222638/14231482/c71c1212-f9b7-11e5-936a-bcca96110322.png)

**Comment by duncdrum** [comment]
That is an odd canvas placement. I just did a couple of svg exports, and haven't seen this behaviour, could you share your files so we can try to reproduce this. Are you exporting from preview or from overview, what do you use to open the svg (illustrator? which version)

**Comment by mbastian** [comment]
Closing this old issue given that we haven't been able to reproduce it. Thank you nevertheless for reporting. Please re-open if it still applies.
