### ISSUE TITLE
Gephi crashes immediately when trying to load graph

### ISSUE THREAD

**Issue by carbonmetrics** [gephi/gephi#1451]
./gephi

gephi starts up, i can import a graphml, then the whole thing blows up:

```
java: ../../../../src/mesa/vbo/vbo_exec_draw.c:278: vbo_exec_vtx_unmap: Assertion `exec->vtx.buffer_ptr != ((void *)0)' failed.
./../platform/lib/nbexec: line 474: 20046 Aborted                 (core dumped) 

```

environment:

```
henk@henk-W330AU:~/Downloads/gephi-0.9.1/bin$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

henk@henk-W330AU:~/Downloads/gephi-0.9.1/bin$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:   vivid
```

**Comment by xileflix** [comment]
Same issue. I have

Same issue on Debian Jessie, with a Asus Zenbook UX301. System: 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.5-1~bpo8+1 (2016-02-23) x86_64 GNU/Linux

Java version: 
- java version "1.7.0_95" 
- OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
- OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Error code:
`/../platform/lib/nbexec: line 474:  7101 Aborted                 "/usr/lib/jvm/java-7-openjdk-amd64/bin/java" -Djdk.home="/usr/lib/jvm/java-7-openjdk-amd64" -classpath "/folder/gephi-0.9.1/platform/lib/boot.jar:/folder/gephi-0.9.1/platform/lib/org-openide-modules.jar:/folder/gephi-0.9.1/platform/lib/org-openide-util.jar:/folder/gephi-0.9.1/platform/lib/org-openide-util-lookup.jar:/folder/gephi-0.9.1/platform/lib/org-openide-util-ui.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ar_SA.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_bg.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ca.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_cs.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_de.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_es.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_fr.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_gl_ES.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_in_ID.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_it.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ja.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ko.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_nl_NL.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_pl.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_pt_BR.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_pt_PT.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ro.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_ru.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_si.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_sq.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_sv.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_tr.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_zh_CN.jar:/folder/gephi-0.9.1/platform/lib/locale/boot_zh_TW.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ar_SA.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_bg.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ca.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_cs.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_de.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_es.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_fr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_gl_ES.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_in_ID.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_it.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ja.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ko.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_nl_NL.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_pl.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_pt_BR.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_pt_PT.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ro.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_ru.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_si.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_sq.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_sv.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_tr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_zh_CN.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-modules_zh_TW.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ar_SA.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_bg.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ca.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_cs.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_de.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_es.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_fr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_gl_ES.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_in_ID.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_it.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ja.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ko.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_bg.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_ca.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_cs.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_de.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_es.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_fr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_it.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_ja.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_ko.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_pl.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_ro.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_ru.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_si.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_sv.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_tr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_nl_NL.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_pl.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_pt_BR.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_pt_PT.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ro.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_ru.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_si.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_sq.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_sv.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_tr.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-ui_ja.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-ui_ru.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_zh_CN.jar:/folder/gephi-0.9.1/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/java-7-openjdk-amd64/lib/dt.jar:/usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar" -Dnetbeans.running.environment=gnome -Dnetbeans.dirs="/folder/gephi-0.9.1/platform:/folder/gephi-0.9.1/gephi:" -Dnetbeans.home="/folder/gephi-0.9.1/platform" '-Xms64m' '-Xmx512m' '-Xverify:none' '-Dsun.java2d.noddraw=true' '-Dsun.awt.noerasebackground=true' '-Dnetbeans.indexing.noFileRefresh=true' '-Dplugin.manager.check.interval=EVERY_DAY' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home/user/.gephi/0.9.1/dev/var/log/heapdump.hprof" org.netbeans.Main --cachedir "/home/user/.gephi/0.9.1/dev/var/cache" --userdir "/home/user/.gephi/0.9.1/dev" "--branding" "gephi" 0<&0
user@BigChief:~/org/gephi-0.9.1/bin$ java -version
`
``

**Comment by boogheta** [comment]
Same here under a fresh install of linux Mint.
The app loads the graph data, gives the report, then crashes as soon as we validate and try to display it.

I tried with:
- Gephi 0.8.2, 0.9.0 alpha and 0.9.1
- openjdk-7 and openjdk-8
- oracle-java7 and oracle-java8

I have and AMD/ATI compatible card (lspci says  `VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Opal PRO [Radeon R7 M260] (rev ff)`) with the recommanded opensource driver `xserver-xorg-video-ati version 1:7.3.0-1ubuntu3.1`

Here's the report of Mr MyOGL: 
```
OS:
    Linux 3.19.0-32-generic amd64

Java:
    version: 24.95-b01
    OpenJDK 64-Bit Server VM, Oracle Corporation

OpenGL version:
    3.0 Mesa 10.5.9

Vendor:
    Intel Open Source Technology Center

Renderer:
    Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 

Shading language:
    1.30
```

**Comment by boogheta** [comment]
I successfully got it working using the proprietary drivers for my videocard `fglrx-updates version 2:15.201-0ubuntu0.14.04.1` although it causes some display instabilities in the system (multi-screen handling especially)

**Comment by axelmeunier** [comment]
Have the same issue as well.
`
java: ../../../../src/mesa/vbo/vbo_exec_draw.c :278 : vbo_exec_vtx_unmap:  l'assertion « exec->vtx.buffer_ptr != ((void *)0) » a échoué.`

Java version : 
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

I'm (still) running ubuntu 14.04 LTS.

**Comment by eduramiba** [comment]
All of this looks like bad graphic drivers, sometimes updating them fixes the problem.
Other possible solution is the one explained at https://github.com/gephi/gephi/issues/1462#issuecomment-211371947

**Comment by axelmeunier** [comment]
Thanks for pointing the graphic drivers... I have both nvidia and intel graphic cards. I tried with nvidia and now gephi works fine :) So i suppose i just have to update my intel drivers.
Cheers

**Comment by eduramiba** [comment]
Closing one of many issues about opengl.

**Comment by WenyinWei** [comment]
Surprisingly, I forced my computer to use NVIDIA driver and then the bug disappears. I guess there is something wrong with the Intel Integrated driver.
