### ISSUE TITLE
Suddenly not importing all of my edges

### ISSUE THREAD

**Issue by cdgoodwin** [gephi/gephi#1454]
I've been doing fine thus far, but yesterday I added about 50 edges to the 217 that I already had. When I saved the CSV and imported it to Gephi today, it will not import all the edges. On first try, it imported 115 of them only -- fewer than the total I had been able to import just fine prior to adding the new edges. 

I checked for trailing space, any odd irregularities, and can't come up with anything. It would almost make sense if it was only the new edges, but why would it suddenly not want to import the 102 that it had no problem with before? I changed the order, arranging by source, and with that it only gave me around 50 of my edges. When I changed the order by target, I got about 92.

Doesn't make a difference if I import nodes first or second, or don't import nodes at all, or if I create new nodes from the edge file. 

I'm sure it's something terribly simple, but I'm at a loss. Please help? I've uploaded the edges here (as an excel spreadsheet).

Thanks!

[Collab Edges 4.8 excel version.xlsx](https://github.com/gephi/gephi/files/210520/Collab.Edges.4.8.excel.version.xlsx)

**Comment by cdgoodwin** [comment]
I don't have a fix for this and I don't understand the problem, but when I grabbed an older version and copied the new data over again it imported all of it.

**Comment by eduramiba** [comment]
Thanks for the report, I can confirm there is a bug in spreadsheet import.

**Comment by eduramiba** [comment]
The problem with the file is that one edge exists both as directed and undirected, which causes an exception:

Clark County Public Health,Clark County Board of Health,Directed,2
Clark County Board of Health,Clark County Public Health,Undirected,1

When spreadsheet import is migrated to Import API (see #1282), we need to report a warning about this.
