### ISSUE TITLE
Node size options not available if node colour set to partition mode

### ISSUE THREAD

**Issue by Snurb** [gephi/gephi#1459]
Hi,

this is one of the stranger issues I've encountered: in the node size selection menu (Node, Attribute, and the size icon selected in the Appearance box in the left sidebar), attributes other than degree/indegree/outdegree - e.g. weighted degree, component ID, etc. - will only appear if in the node _colour_ options the mode of colour application is set to ranking (i.e. a gradual colour transition) rather than to partitions (i.e. discrete colours for each value). This is the case even if the specific attribute isn't even being used to determine node colours.

This seems very strange, since the node size is always a gradual scale, and shouldn't be influenced by whether ranking or partition is selected for node colour. Can you fix this, please ?

Axel Bruns

**Comment by natpoor** [comment]
Axel you just solved my problem!!! I thought maybe it was only in 0.9.1 but it happens in 0.9 as well. 
<img width="284" alt="screen shot 2016-05-02 at 2 03 33 pm" src="https://cloud.githubusercontent.com/assets/5871741/14962949/67ba32f8-106f-11e6-963c-557c9d27bf40.png">
<img width="277" alt="screen shot 2016-05-02 at 2 03 19 pm" src="https://cloud.githubusercontent.com/assets/5871741/14962951/67c42ed4-106f-11e6-8679-895ab77c1bcd.png">

**Comment by rhasarub** [comment]
I can confirm the issue for 0.9.1 on Windows 7. It's not only node size, though. 

From a fresh project, I import a nodes csv and import some columns as integer, double or float (no missing values). Without having made any change in the node color tab before (where all those columns can be selected), neither of them shows up in the node size selection, _nor do they show up in label size or color selection._  If I calculate additional values like PageRank, these do show up in all select boxes.

**Comment by rhasarub** [comment]
Here's a quick and dirty workaround I used. Maybe this helps somebody while the issue is not fixed: I have one column "size" in my data with Double values, which does not appear in the node size selection. I calculated a statistics measure with Double values _which I do not need for other reasons_ (e.g. Avg. Weighted Degree or PageRank). These columns were available in the node size menu. I then copied the values from the size column to this column, _et voilà_, I was able to use them for ranking sizes. 

![node_size](https://cloud.githubusercontent.com/assets/1244032/16011305/19f083e2-3185-11e6-9093-44732cad55cf.png)
![node_size3](https://cloud.githubusercontent.com/assets/1244032/16011313/1f9f8ab8-3185-11e6-8cb6-e16f4207e9aa.png)

**Comment by seakha** [comment]
Thanks for the quick and dirty solution. I tired to imitated the process by creating ad Double column and copy the values there (I also saw people on other thread said it works) but it did not work. Gephi 0.9 and 0.9.1 get better performance, but they have so many bugs makes them unreliable.

**Comment by kennell** [comment]
None of the workarounds described here worked for me. 

This is how i fixed it: 

1. Create dummy data by running dummy statistics as described in @rhasarub  comment. 
2. Go to the data laboratory, go to the Node tab, export everything to a .csv file. 
3. Open that file in any Spreadsheet software, manually copy the values you need (in my case Betweeness Centrality) to a unneeded column that appears in the GUI selection box (in my case Out-Degree).
4. In the data laboratory, import the modified file. You can now run the size ranking on the unneeded value you have overwritten.

**Comment by cladelpino** [comment]
@rhasarub work around works for me, but, not with PageRank. Only with "Average Degree", which creates columns in the data lab for the attributes that were already available in the first place (Degree, In Degree and Out Degree in my case). I didn't have to export-reimport as @kennell suggested, though. 

A peculiarity which is perhaps useful: After performing "average degree",  "Degree","In Degree" and "Out Degree" appeared duplicated in the attribute choosing dropdown for all node size,label size, etc.  

These dupplicates didn't appear in the data lab.

**Comment by aparamon** [comment]
Doesn't work for me on attached graph and "width" attribute.
