### ISSUE TITLE
parallel edges not summed when appending multiple gexf files

### ISSUE THREAD

**Issue by jpoko** [gephi/gephi#1460]
I am trying to load in multiple .gexf files, append them to one another, and have the edge weights sum when the Source and Target are the same (though the edge ID differs when coming from a different gexf file). I am using the newest Gephi version 0.9.1, have it selected to append the graph and the edge merge strategy set to 'sum.' 

It is similar to the issue raised in #1251 though for gexf files, not spreadsheets.

**Comment by eduramiba** [comment]
Hi,
This has been fixed for 0.9.2 Please try with the latest snapshot https://github.com/gephi/gephi#nightly-builds
