### ISSUE TITLE
Spaces in header columns of edge CSV file fails to load

### ISSUE THREAD

**Issue by pmcb55** [gephi/gephi#1461]
Hi,

It seems that if the header columns of an edge CSV file have spaces after the comma the CSV loader fails to recognise the required 'Source' and 'Target' columns. 

For instance, my initial CSV was this:
**Source, Target, Weight
1, 2, 0.1
1, 3, 0.3**

I initially thought the problem was with BOM's, but after much trial-and-error it turns out it was simply the space before the word 'Target'!

This could be very simply fixed in the code by just using '.trim()' on the column names. (Of course I can fix this myself now by just removing the spaces before column names in my header, but this is unnecessarily very confusing for newbies to Gephi whose CSV files have spaces after commas for readability).

Pat.

**Comment by seinecle** [comment]
I agree the trailing spaces could be trimmed for a better UX

**Comment by eduramiba** [comment]
The CSV and Spreadsheet import experience will be greatly improved with #1282 (including this) :)

**Comment by eduramiba** [comment]
Can you please try the latest nightly build (https://github.com/gephi/gephi#nightly-builds)? It should include these changes
