### ISSUE TITLE
Crash on file open

### ISSUE THREAD

**Issue by javiermv** [gephi/gephi#1462]
Gephi 0.9.1 crashes on file open under elementary OS Freya. Not usable.

**Comment by eduramiba** [comment]
Hi, can you provide some log file or crash report?

**Comment by javiermv** [comment]
Ups! Sorry about that. Here are the log and the console dump. ".txt" was added to please github.
Let me know if you want me to try something. Thanks!

[gephi-0.9.1-console-log.txt](https://github.com/gephi/gephi/files/223771/gephi-0.9.1-console-log.txt)
[messages.log.txt](https://github.com/gephi/gephi/files/223772/messages.log.txt)

**Comment by eduramiba** [comment]
It seems the file is loaded fine, so the problem is probably related to a graphic card drivers crash. Can you try to make sure you have the latest drivers? You can also try to force software opengl rendering with ```LIBGL_ALWAYS_SOFTWARE``` or similar.

**Comment by javiermv** [comment]
That is correct. With the Graph Window closed files seem to open properly or, at least, the app won't crash. Upgrading video drivers with ppa:oibaf/graphics-drivers didn't do the trick. I'll try your suggestion later. It'd be great if some try-catch magic could let the user know there's a problem with the graphic driver, isn't it?

**Comment by eduramiba** [comment]
In these cases some native library crashes (JOGL) occur, which can't be caught and stop the full JVM.

**Comment by javiermv** [comment]
You win, I loose. :o) But what about logging before and after trying to initialize such a library? If there's a failed previous atempt, maybe there could be a message to the user suggesting to use the software alternative. Too complicated?
I'll try the software solution as soon as I can, so as to share the results.

**Comment by eduramiba** [comment]
I guess we could do some checks but I am not sure if that's possible in many cases, as the crashes happen in unexpected places...

**Comment by javiermv** [comment]
LIBGL_ALWAYS_SOFTWARE=1 worked for me. Thanks!
