### ISSUE TITLE
No Suitable Driver Found for jdbc:postgresql

### ISSUE THREAD

**Issue by JoeViavattine** [gephi/gephi#1466]
I am getting this error when trying to create a connection to a postgresql database and clicking on the "test connection" button.  I've seen reference to similar errors for other programs and other databases, but not one for Gephi 0.9.1, PostgreSQL.  Thanks for any help that you can give.

Potentially useful info:
Product Version: Gephi 0.9.1 201510222201
Java: 1.7.0_67; Java HotSpot(TM) Client VM 24.65-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_67-b01
System: Windows 7 version 6.1 running on x86; Cp1252; en_US (gephi)

**Comment by eduramiba** [comment]
Related issue #1317
