### ISSUE TITLE
Impossible to color arcs with a color gradient with 0.9.1

### ISSUE THREAD

**Issue by cthovex** [gephi/gephi#1469]
I was used to color the arcs using the Weight value and a user-defined color gradient in 0.8.2.
Now with 0.9.1 the arcs are all colored with the highest color value of the user-defined color gradient, for instance all arcs are red if the gradient is blue (min value) to red (max value).

**Comment by eduramiba** [comment]
Confirmed, thanks for the report!

**Comment by eduramiba** [comment]
Fixed, to be released on next updates. It will also be available on [0.9.2-SNAPSHOT nightly build](https://github.com/gephi/gephi#nightly-builds) as soon as [travis build](https://travis-ci.org/gephi/gephi/builds/170917670) finishes.

**Comment by habibi-reza** [comment]
After installation Gephi-9.2-snapshot could not Draw gradient between two nodes. Why?

**Comment by eduramiba** [comment]
@habibi-reza This bug was about using a gradient-based ranking with a numeric column, where some nodes have low values, and others high (and many possible values in between). Not sure what you mean by gradient between two nodes.
Can you explain what you are trying to do and whether it works fine with 0.9.1?

**Comment by habibi-reza** [comment]
I have ranked the graph nodes and I don't know how can color the edges between two nodes based on ranking of two nodes by gradient coloring.
for instance:
![1](https://cloud.githubusercontent.com/assets/25146661/21977831/2af927b2-dbed-11e6-80dc-b36eb6655154.jpg)

**Comment by eduramiba** [comment]
Well, that has never been possible with Gephi. You can create a separate issue for that as a wishlist.
