### ISSUE TITLE
graphml `edgedefault` not handled to spec

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#147]
from http://graphml.graphdrawing.org/primer/graphml-primer.html#GraphGraph

	Graphs in GraphML are mixed, in other words, they can contain directed
	and undirected edges at the same time. If no direction is specified
	when an edge is declared, the default direction is applied to the edge.
	The default direction is declared as the XML Attribute edgedefault of
	the graph element. The two possible value for this XML Attribute are
	directed and undirected. Note that the default direction must be
	specified.

However, when specifying an edgedefault Gephi complains "Edge type doesn't
fit with default".

More importantly having a graph with `edgedefault="undirected"` but all edges
but one with `directed="true"` makes the unspecified edge directed as well. My
work around for now is to just not specify edgedefault for the graph, and manually
specifying `directed` as `true` or `false` for each edge - even though this doesn't
strictly follow the GraphML spec.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-11-16T22:02:30Z
 * owner: sebastien.heymann
 * assignee: mathieu.bastian
 * the launchpad url was https://bugs.launchpad.net/bugs/676272

**Comment by eduramiba** [comment]
Fix merged
