### ISSUE TITLE
In visulazation window, There is no node shape.

### ISSUE THREAD

**Issue by gogogo237** [gephi/gephi#1472]
missing node tab. There should be a option which I can choose for 3D node
![image](https://cloud.githubusercontent.com/assets/6381154/14773484/3f98b35e-0add-11e6-928b-f02d810fb365.png)

**Comment by eduramiba** [comment]
Duplicate of #1452

**Comment by gogogo237** [comment]
Thanks for your info! This is very helpful.

**Comment by eduramiba** [comment]
No problem, I hope we can bring back some of the features :)
