### ISSUE TITLE
Improve range slider user experience for manually setting values

### ISSUE THREAD

**Issue by cdgoodwin** [gephi/gephi#1476]
Under Filter/Topology/Degree Range, there is a slider that goes from 0 to the max number. At the moment, you can move the slider, but the number doesn't update until you stop dragging the marker. This makes it difficult to select a precise number (probably 1 or 2, usually). If the slider display would reflect the number as the marker is being moved, the use could land on the number they want easily.

I'm guessing this sort of slider is used for other tools too, and would recommend the same for those.

**Comment by alexbovet** [comment]
I just discovered that if you double click on the number you can actually input the exact value you want!

**Comment by eduramiba** [comment]
@alexbovet Right, maybe we should make this more obvious. I am thinking about only requiring a single click and showing a hand cursor when the mouse is over it.
Adding this to 0.9.2 milestone.

**Comment by alexbovet** [comment]
yes that would be nice. It would also be nice to somehow show if the range includes or not the boundaries. It's not always obvious.
