### ISSUE TITLE
Import wizard 0.9.1 now showing any options.

### ISSUE THREAD

**Issue by hvandenb** [gephi/gephi#1477]
Using File-->Import.. shows the following empty wizard.
![image](https://cloud.githubusercontent.com/assets/401017/14944174/e6e007dc-0fa8-11e6-81f1-7bff7d5ee05f.png)

> Product Version: Gephi 0.9.1 201510222201
> Java: 1.8.0_74; Java HotSpot(TM) 64-Bit Server VM 25.74-b02
> Runtime: Java(TM) SE Runtime Environment 1.8.0_74-b02
> System: Mac OS X version 10.11.4 running on x86_64; UTF-8; en_US (gephi)
> User directory: /Users/dddd/Library/Application Support/gephi/0.9.1/dev
> Cache directory: /Users/dddd/Library/Application Support/gephi/0.9.1/dev/var/cache

**Comment by eduramiba** [comment]
Hi,
This means there are no import plugins installed. It's a bit confusing and we should make it more clear in the UI.

**Comment by hvandenb** [comment]
That would help thanks.

**Comment by eduramiba** [comment]
Fixed for next version.

**Comment by mvelasco93** [comment]
![image](https://cloud.githubusercontent.com/assets/5703605/22407634/414d1168-e638-11e6-825e-200f062ffdad.png)

Reproduced. Installed all listed plugins and this is the one that appears. (I need to import a DOT file)

Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_112; Java HotSpot(TM) 64-Bit Server VM 25.112-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_112-b15

**Comment by eduramiba** [comment]
@mvelasco93 To import DOT files just use `File - Open...`

**Comment by mvelasco93** [comment]
@eduramiba it doesn't work

**Comment by eduramiba** [comment]
@mvelasco93 Does it show any error?
