### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by waynezhangnus** [gephi/gephi#1478]
after generating the network graph in overview, the preview window is not working to generate an output graph

**Comment by professorakhlaq** [comment]
I had the same problem, but thanks to Allah, I solved it. Go to main menu, Windows and then click preview. Also click Preview setting. Now press refresh on preview setting tab, you will find the preview.

**Comment by eduramiba** [comment]
Is the issue still happening?

**Comment by professorakhlaq** [comment]
Thanks a lot. I have solved the issue.

On 1 June 2016 at 12:47, Eduardo Ramos <notifications@github.com> wrote:

> Is the issue still happening?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gephi/gephi/issues/1478#issuecomment-222944791>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARHV9v71GdNVFI97gjqsTEaKI9CJYT5rks5qHVUtgaJpZM4IV8FZ>
> .
>



-- 
*Assalaam O Aliakum*




Thanks, Wassalaam O Aliakum


*Akhlaq Ahmad *
*Matric Number G1235263*
PhD Student,
KICT, IIUM,
Email: professorakhlaq@gmail.com , aajee@uqu.edu.sa

**Comment by MohammadHeydari** [comment]
In the Left corner of Preview windows, next to the Ratio Zoom Click to **Refresh.**
it worked for me
