### ISSUE TITLE
Gephi 0.9.1 Workspace

### ISSUE THREAD

**Issue by aerojohn** [gephi/gephi#1482]
I am running Gephi 0.9.1 on Mac Powerbook. After filtering, the filtered graph will not export to a new workspace. The task never completes according to the bar graph in the lower right corner of the screen. A new workspace tab appears, but the data table is empty.

**Comment by eduramiba** [comment]
Can you test with 0.9.2 snapshot? I think this should be now fixed

**Comment by yannickpulver** [comment]
I just installed 0.9.2. On my MacBook Pro, running MacOS Sierra, the problem remains unsolved. Still not able to export to a new workspace.

**Comment by Marmeladenbrot** [comment]
I have the same error with 0.9.2 on Windows 10 x64.
Apply filter, export to new workspace, "task never completes according to the bar graph in the lower right corner, new workspace tab appears, but the data table is empty" is exactly what is happening.

**Comment by eduramiba** [comment]
Keeping track of this in #1900
