### ISSUE TITLE
csv import error: found rows with empty source or target columns 

### ISSUE THREAD

**Issue by kristinara** [gephi/gephi#1489]
Hello: 

I updated to Gephi 0.9.1 from Gephi 0.8.2. Machine is IOS with El Captain version 10.11.4. 

In the old version, I was able to import .csv files with source and target columns (target columns would contain empty cells because in some cases the source didn't have a connection). I didn't have any problem uploading my file and running analysis. 

After the update, I now receive an error that says "found rows with empty source and/or target columns. The source column is not empty. Target column is empty in some rows because the source might doesn't have a connection in that particular instance. Again this issue did not occur with the old version of Gephi. 

Best, 
Kristina

**Comment by eduramiba** [comment]
Yeah, this is validated now as it was an old problem.
Not sure why you would have rows with an empty source or target.

**Comment by eduramiba** [comment]
The related commit is https://github.com/gephi/gephi/commit/42765948b47e67b1452a751bc267cf81f3d47fe1

**Comment by pabloivan** [comment]
Had the same error when working with metabolic networks represented as a reaction graph. Some of my nodes will be isolated from the network and this is OK. In fact, Cytoscape imports and represent these nodes, creating a node attributed IsolatedNode=yes in these cases. I think this is an issue that should be rolled back to what it was.

**Comment by eduramiba** [comment]
We could just actually remove this validation in the wizard.

**Comment by eduramiba** [comment]
@ishalev Make sure when you export from excel to CSV you don't have empty cells, as excel will export them to CSV as rows that look like `,,,,,`

**Comment by ishalev** [comment]
Yes, that solves the immediate problem, thanks for the suggestion.

I'd like for gephi to detect the empty rows and not import them, or for the
wizard not to fail if it detects empty rows. The current approach ensures
that a human has to perform a maintenance/cleanup task that is trivial to
automate.



Thank you,
Isaac Shalev
President
Sage70, Inc.
(917) 859-0151
isaac@sage70.com

Schedule a *free 60-minute consultation *now:
https://www.vcita.com/v/1c82bc52728f8e66/online_scheduling

**Comment by eduramiba** [comment]
@ishalev We could do that (show as warnings on import) once spreadsheet import is migrated to import API. See #1282

**Comment by malcolmlangford** [comment]
It has been impossible to delete the rows in the Excel file. I have tried everything that is advised on this problem but I am still sitting with a million+ rows in my Excel sheet,  and thus the .csv file. Is there another way to solve this problem in Gelphi?  Can we specify a range in Gelphi, like in Stata?
