### ISSUE TITLE
Add 'postProcess()' method to Preview's Renderer SPI

### ISSUE THREAD

**Issue by songjinghe** [gephi/gephi#1490]
In current gephi preview model, the render prcess are as follows:
1. call preProcess() (only one time for one refresh action)
2. call render() many time (on each object)
I wonder if we could add an postProcess method to be executed once after calling all render() method? this would benefit the algorithms who needs to modify the rendered image after rendering all items, for example, the heatmap algorithm need to draw the image using alpha first, then convert alpha to HSL.

**Comment by songjinghe** [comment]
well, I'm writing an heatmap preview plugin for gephi

**Comment by eduramiba** [comment]
Hi,
Were you able to do this?
Can you suggest the changes with a pull request?

**Comment by songjinghe** [comment]
Currently, I done this by rendering the heatmap in a separate new `BufferedImage`, then pass the image to `previewModel.getItems(Item.EDGE)[0]` (using `setData(String key, Object value)`, all these step are done in `preProcess()` method), then render that image in the `Render.render()` method. See the following three files for details.
https://github.com/TGraphDB/gephi-demo/blob/TGraphDemo/modules/TGraphDemo/src/main/java/edu/buaa/act/gephi/plugin/preview/HeatMapStatisticPreview.java
https://github.com/TGraphDB/gephi-demo/blob/TGraphDemo/modules/TGraphDemo/src/main/java/edu/buaa/act/gephi/plugin/task/RenderPreProcessSyncTask.java
https://github.com/TGraphDB/gephi-demo/blob/TGraphDemo/modules/TGraphDemo/src/main/java/edu/buaa/act/gephi/plugin/preview/HeatMapRenderer.java

The result is good, as a heatmap with 5000x5000 resolution can be rendered in 50ms (using the modified `LinearGradientInt` mapper), for effect please see [this video](https://youtu.be/nbWa_5OL3GU) (in the end)

Well, since this is a runnable work around, I think maybe this feature is not something that badly needed?
