### ISSUE TITLE
Some label characters fade away when zooming out!

### ISSUE THREAD

**Issue by pmcb55** [gephi/gephi#1494]
Hi,

I'm seeing change node label behaviour when zooming in and out of the 'Overview' view of my simple graph using the mouse wheel on Windows 7 Pro. Seemingly random characters from the node labels start to fade away as I zoom out, and fade back in again as I zoom in.

See the 3 attached screenshots that clearly show this behaviour at 3 different zoom levels. I haven't configured Gephi in any way - just downloaded 0.9.1 and loaded my simple node and edge CSV files.

Anyone else seeing this behaviour? I can upload my data files too if needed, but they're just basic CSV text files:

![gephi_1](https://cloud.githubusercontent.com/assets/961445/15535943/568d0726-2267-11e6-9716-f59088a0e68b.png)
![gephi_2](https://cloud.githubusercontent.com/assets/961445/15535942/568bf796-2267-11e6-9f0e-be677c784b2f.png)
![gephi_3](https://cloud.githubusercontent.com/assets/961445/15535941/568b8040-2267-11e6-99db-79c7fc83d21e.png)

**Comment by yaceben** [comment]
Had this issue on a computer (Windows 8.1 x64) with both integrated gpu(intel iris or whatever) and proper gpu(nvidia), problem only happens when using integrated gpu. Walkaround is to force gephi to load with nvidia gpu.Maybe a bug on intel opengl drivers?

**Comment by jefvana** [comment]
@yaceben Thanks for the tip, I have the same problem. I also have two gpu's installed, but Gephi sticks with the integrated one. How do I force Gephi to change?
![gephi1](https://cloud.githubusercontent.com/assets/20700097/17457165/de9c2432-5bef-11e6-85d9-11cf97a59e61.GIF)
![gephi2](https://cloud.githubusercontent.com/assets/20700097/17457166/de9f1f0c-5bef-11e6-9a16-88d7a35354e9.GIF)

**Comment by eduramiba** [comment]
Check https://knowledge.autodesk.com/support/infraworks-360/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-force-your-laptop-to-Run-with-Graphics-Processor-vs-the-default-Integrated-Graphics-for-InfraWorks.html

**Comment by jefvana** [comment]
Thanks Eduardo!

2016-08-06 20:05 GMT+02:00 Eduardo Ramos <notifications@github.com>:

**Comment by tlecomte** [comment]
I have the same problem on a machine which has a single Intel(R) HD Graphics 4600 gpu. Unfortunately I cannot easily switch to an NVidia gpu ;)

**Comment by MikeDC77** [comment]
Is there a solution to this problem for people who only have an integrated GPU? 

What GPU's have this problem? 

Some (most?) integrated gpu's seem to work just fine.

**Comment by eduramiba** [comment]
A solution is to be investigated for 0.9.2.
Meanwhile, if you use Linux, you can force software rendering.

**Comment by damense** [comment]
Looking forward to 0.9.2...

**Comment by eduramiba** [comment]
Please test with latest 0.9.2 snapshot when the current build is done!
