### ISSUE TITLE
import csv file to generate a gephi network

### ISSUE THREAD

**Issue by pythondata** [gephi/gephi#1496]
I am trying to import a csv file to build a gephi network, data like this
A, B
B, C
C, D
A, C
D, B
B, C

I am using node table but gephi does not combine all information for A, B, C, or D instead I got 4 nodes  than 4 nodes. This is happened in 0.9.1,0.9 version. Thanks.

**Comment by eduramiba** [comment]
Hi,
this looks like and edges table, where node ids are source and target. If you import it as nodes, there is only 4 different ids so that makes sense.

Your file should look like this and you should import it as edges table:

```
source,target
A,B
B,C
C,D
A,C
D,B
B,C
```

**Comment by eduramiba** [comment]
Did this work?

**Comment by eduramiba** [comment]
Closing old question.
