### ISSUE TITLE
GraphML parser flags "graph" level attributes as an error.

### ISSUE THREAD

**Issue by markharwood** [gephi/gephi#1497]
If a GraphML file declares an attribute for the type "graph" the code[ here](https://github.com/gephi/gephi/blob/master/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/ImporterGraphML.java#L586) flags a "severe" error in the load dialog  
![import report](https://cloud.githubusercontent.com/assets/170925/15614870/1572e648-2433-11e6-95c3-e959fe23d8d0.jpg)

Attributes in GraphML can be declared for `node`, `edge`, `graph` and `all` but this code throws an error if we pass an attrib of the type `graph`.

Tested the same GraphML file with Yed and it correctly parses and shows the different attributes grouped by node/edge/graph types:
![custom properties](https://cloud.githubusercontent.com/assets/170925/15614981/8b50e572-2433-11e6-91e3-825b06339041.jpg)

Example file: 

```
<graphml>
    <key id="d0" for="node" attr.name="myNodeAttr" attr.type="string">
        <default>0</default>
    </key>
    <key id="d1" for="graph" attr.name="myGraphAttr" attr.type="string">
        <default>no value</default>
    </key>
    <graph edgedefault="undirected">
        <data key="d1">myGraphValue</data>
        <node id="myNodeId">
            <data key="d0">myNodeValue</data>
        </node>
    </graph>
</graphml>
```

**Comment by eduramiba** [comment]
Hi,
Graph attributes are not supported in Gephi yet.

**Comment by jthrilly** [comment]
Just wanted to flag up that I came across this today, too. Graph level attributes are currently used as a way to store metadata and ego level data by several softwares.

Can I suggest that the parser be updated to at least recognize the validity of the attribute according to the spec, thereby downgrading the issue level from 'severe' to 'info'. The accompanying message could say something like "Graph level attributes not supported currently".

@eduramiba - any implementation plan? I can provide a PR if the above proposal works for you.

**Comment by mbastian** [comment]
I added a warning instead of an error, indicating graph attributes are not recognised (yet).
