### ISSUE TITLE
"Partition count" filter does not work

### ISSUE THREAD

**Issue by vberten** [gephi/gephi#1501]
It looks like the "Partition count" filter is not working with the last versions (I've tried different versions of the 0.9, including nightbuilds).

With several networks with partitions (data included or created via connected components or modularity), I tried to apply a "Partition count" filter. I can see the values, but when I change the slider (with mouse or by double-clicking on the numbers), nothing is filtered out if I click on "Filter". I use many other filters that perfectly work.

**Comment by BerRed** [comment]
I have exactly the same problem, no Partition filter is working with the new downloaded version 0.9.1. Any clue?

**Comment by MaciejWarchalowski** [comment]
Same problem here. Running 0.9.1.
