### ISSUE TITLE
average weight of duplicate and inverted edges 

### ISSUE THREAD

**Issue by anuragpassi** [gephi/gephi#1503]
Hello, my edgelist data has inverted edges (a->b,b->a) with different weights. The graph is undirected. I want to remove all but one edge and the weight should be the average of all the inverted edges between two nodes.

This is the test data

'DB2'   'DB1'    0.500000000000000
'DB1'    'DB2'    0.300000000000000
'DB3'    'DB4'    0.400000000000000
'DB3'    'DB2'    0.700000000000000
'DB2'    'DB3'    0.500000000000000
I want to get something like that

'DB2'    'DB1'    0.400000000000000 (1st and 2nd row)
'DB3'    'DB4'    0.400000000000000 (no duplicates)
'DB3'    'DB2'    0.600000000000000 (4th and 5th row)

Can you help me with this.

**Comment by eduramiba** [comment]
Are you importing spreadsheet data?
Maybe this works: import your data as is, then export a gexf file and import it again but in the import dialog choose undirected edges mode and merge by summing weights.

**Comment by anuragpassi** [comment]
I need to average the weights. Will this take care of parallel and inverted edges both?

**Comment by eduramiba** [comment]
I think then you can select merge by average but I'm not sure the options is available. Please report back if it works.

**Comment by eduramiba** [comment]
Did it work?

**Comment by eduramiba** [comment]
Should be working fine in 0.9.2 after #1282
