### ISSUE TITLE
Preview Screen is not responsive in Gephi 0.9.1

### ISSUE THREAD

**Issue by goodgogol** [gephi/gephi#1505]
Hi,

I am pretty new to gephi and using it to generate network graphs. While the graphs are being generated properly and can be seen in the overview tab, the preview screen remains empty and just shows a black screen. The export options are also failing ,possibly due to this(pdf /svg /Loxa Web Site export all shows a black screen and no graph).
Also i can't spot the partition and ranking options, just the layout and appearance panels are available.Maybe I'm missing something?
Would really appreciate any help in resolving these issues.

**Comment by eduramiba** [comment]
Hi, partition and ranking are now appearance.
About preview, is there any exception in your messages.log file?

Check https://github.com/gephi/gephi/wiki/Troubleshooting to find user directory

**Comment by goodgogol** [comment]
Hi,
Thanks a lot! Downloaded and reinstalled 0.91 and now the previews are working fine and so is the export.
However, still can't find partition and ranking options!

**Comment by eduramiba** [comment]
Hi,
Well appeareance is mostly the same, but the UI has changed slightly (check the icons at the top-right corner and specially the bottom-left icon which allows to switch between ranking and partition).

Also please note that there is a known bug: #1459

**Comment by goodgogol** [comment]
Thanks a ton !Got the ranking ans size options now and they are working fine.
Can you please let me know if this is the case with the OS X release as well?

**Comment by eduramiba** [comment]
Yeah it's the same

**Comment by darcyof** [comment]
Hi, I am also having a problem with the Preview screen.  I am able to make graphs in the overview but am getting only a grey screen on the preview tab.  There is not refresh button (or any other button).

any help will be much appreciated.

Thanks!

**Comment by muthulakshmi1990** [comment]
Hi, I am using Gephi0.9.1. I am trying to connect Titandb with gephi. I am able to see the data from Titandb to Gephi(using DataLaboratary tab in gephi). But I am not able to view graph in Overview or Preview tab in Gephi. Kindly help me to resolve my problem.

**Comment by saturnjiang** [comment]
Hi I am using Gephi0.9.1. when I import the csv data into the datalaboratary table, but I cannot see the graph in the Preview. The screen is black, after I zoom in or out, the graph can be shown shortly with nodes only, then the screen returnd to black. But when I import the data of examples, the preview is normal.
![black screen](https://cloud.githubusercontent.com/assets/25746920/22889965/285691dc-f20b-11e6-9608-72ebe7b9f19f.png)
![black screen2](https://cloud.githubusercontent.com/assets/25746920/22889972/2bb44cca-f20b-11e6-88b1-01873b190247.png)

**Comment by eduramiba** [comment]
HI @saturnjiang Your graph probably has a node with a huge size (much larger than other nodes) or maybe an edge with a huge weight.

**Comment by saturnjiang** [comment]
Thank you very much, I will try to check it!

**Comment by kcurrier** [comment]
Greetings--I'm having trouble with the Preview window after saving and re-opening a file. When I begin a new project, import data, and configure the Appearance, Layout and Preview settings, the preview works as expected. However, if I save and close the project, then re-open it, the Preview window no longer works (i.e. when I click Refresh I see what appears to be "Loading" flash on the screen for a few milliseconds and then get a blank Preview window.

This doesn't happen with the "Les Miserables.gexf" sample file. If I open this file, re-save it with a different name, then open that file, the preview works fine.

In the log it looks like there is a "Premature end of file" exception that I think is generated when Gephi is started. See attached messages.log file. 

On a possibly related side note, when I try to save a new preset in the Preview Settings window I can never find it again after closing and opening Gephi. It's no longer one of the dropdown menu options.

I'd appreciate any suggestions. Thanks.
[messages.txt](https://github.com/gephi/gephi/files/945511/messages.txt)

**Comment by eduramiba** [comment]
@kcurrier Does it work with 0.9.2 snapshot?

**Comment by kcurrier** [comment]
@eduramiba The same is happening with 0.9.2 snapshot, i.e. when I open my saved .gephi file and in the Preview window hit "Refresh" without first toggling the option to show edges, the preview window remains blank. However, the same workaround still works--I just have to remember to check the show edges option before hitting "Refresh", and I can see the graph. Then I can uncheck the show edges option, hit "Refresh" again, and it displays as expected, i.e. edges hidden.

**Comment by athmig** [comment]
No preview with toys snapshot: gephi-0.9.3-20180706.210318-103-linux. Refresh doesn't help either toggling the option to show edges. I can see the graph only by exporting it.

**Comment by DanyEle** [comment]
I'm having the same issue here in Gephi 0.9.2, with the graph not showing up in the Preview windows. Any solution? I can only see the graph by exporting it.

**Comment by racingkoala** [comment]
same here...

**Comment by racingkoala** [comment]
This https://github.com/gephi/gephi/issues/1478#issuecomment-220834617 solves the problem. But is it supposed to work like that? weird...

**Comment by Uzgraph** [comment]
I'm having the same issue here in Gephi 0.9.2, with the graph not showing up in the Preview windows. 
Refresh button in the left low window corner doesn't help ... but only in the new unsaved project ...
So to fix this I need 3 steps:
1) Save project;
2) Restart Gephi and open the file with project!
3) Press the Refresh button in the left low window corner.

**Comment by mbastian** [comment]
Closing this issue. Let us know if this is still happening with the latest version. We made some reliability improvements on this module since this was opened.
