### ISSUE TITLE
Undirected Average Path Length Not available

### ISSUE THREAD

**Issue by Mivalo** [gephi/gephi#1507]
If I select that I want to calculate the average path length (i.e. Betweenness etc.) and I select _UNdirected_ (see picture below):

![error_gephi](https://cloud.githubusercontent.com/assets/14978188/15723256/e8cf7aa8-2841-11e6-94d3-e88ac11072b2.PNG)

If I press OK, it still tells me that the network interpretation is _directed_:

![error_gephi_2](https://cloud.githubusercontent.com/assets/14978188/15723322/2d0d24c2-2842-11e6-8731-2a4a758bada5.PNG)

Moreover, the calculated centralities are indeed equal to the ones that are computed with the directed option chosen while the undirected centralities calculated  in gephi  0.8 are different.

**Comment by duncdrum** [comment]
Yeah same here. There is probably related issue where directed graphs are calculating undirected statistics  #1455. @eduramiba any idea whats going on. These seem like pretty major issues.

**Comment by FlxVctr** [comment]
Same here. Really concerning, because so many other statistics depend on this.

**Comment by bjoernross** [comment]
A workaround for now is to convert the directed network to undirected first, by exporting to GEXF and selecting "Undirected" when opening.

**Comment by mbastian** [comment]
Thanks for reporting, I confirmed the issue. This seems to have appeared in 0.9 when we transitioned to the new Graph API. It also affects other statistics (e.g. clustering coeff.)
