### ISSUE TITLE
bug when importing csv files by File|Open

### ISSUE THREAD

**Issue by gephimail** [gephi/gephi#1509]
I create the following .csv file in order to be modeled as a network by following the "mixed" example at https://gephi.org/users/supported-graph-formats/csv-format/ 
P;M;V
O;D;S
O;T;S

I expect that the corresponding graph would present a link between nodes T and S. However, when I open the .csv file with Gephi, the link isn't there (I obtain a network with only 7 links, the links between D and S, M and V are also missing)

**Comment by eduramiba** [comment]
Hi,
If you read this part:

> **Adjacency List**
> All edges can be written as node pairs. It’s also possible to write all node’s connection on the same line. The example below represents a graph with 3 edges: “a” -> “b”, “b” -> “c” and “b” -> “d” 
```
a;b
b;c;d
```

No link is created between c an d. So the first element in the line is linked to all others, but not all combinations.
