### ISSUE TITLE
self loops

### ISSUE THREAD

**Issue by gephimail** [gephi/gephi#1510]
I open this csv file with File|Open
;P;M;v;O;D;S;T
P;1;1;1;0;0;0;0
M;1;1;1;0;0;0;0
v;1;1;1;0;0;0;0
O;0;0;0;1;0.5;1;0.5
D;0;0;0;0.5;1;0.5;0
S;0;0;0;1;0.5;1;0.5
T;0;0;0;0.5;0;0.5;1

I uncheck the self loops option in the import window (more options) but the graph is rendered with strange triangles on the nodes where the self loops would be if the self loops option would be checked. The same happens in the export window: self loops are rendered as perpendicular lines even if they should be ignored

**Comment by eduramiba** [comment]
Fixed in 0.9.2 snapshot

**Comment by eduramiba** [comment]
Same as #1619
