### ISSUE TITLE
overview viewport too small

### ISSUE THREAD

**Issue by yaceben** [gephi/gephi#1518]
Overview viewport is too small for very large graphs, cannot do proper visualisation, most nodes will all end up doing a square border because they can't go any further (yes I need them to expand...).

Possible resolution I guess would be to replace coordinates to double instead of float ? Or maybe max_x, max_y, max_z too small ?

see included screenshot
![toosmall](https://cloud.githubusercontent.com/assets/19843412/15940599/196dce8c-2e53-11e6-8e14-9dfe126d014f.png)

**Comment by YasirArfat32** [comment]
Even I have the same issue. When the number of nodes and edges increase, moving around the viewport becomes impossible.

**Comment by eduramiba** [comment]
Hi,
I don't know the source of this old problem, but I also think it's worth fixing/improving.

**Comment by eduramiba** [comment]
Need to increase DEFAULT_OCTREE_WIDTH at https://github.com/gephi/gephi/blob/master/modules/VisualizationImpl/src/main/java/org/gephi/visualization/apiimpl/VizConfig.java as it affects the clamp done at https://github.com/gephi/gephi/blob/master/modules/VisualizationImpl/src/main/java/org/gephi/visualization/octree/Octree.java

But too large numbers make visualization not work.

Also should increase the farDistance for the camera at https://github.com/gephi/gephi/blob/90a5fe6fe3f07e50c6095a4209eb6cc56de574d2/modules/VisualizationImpl/src/main/java/org/gephi/visualization/swing/GLAbstractListener.java

Discarding for a proper revamp of visualization module in a future version.

**Comment by eduramiba** [comment]
The new engine fixes this https://github.com/gephi/viz-engine

**Comment by degrigis** [comment]
Hey @eduramiba! Would it be possible to have a build with the new engine to solve this issue? That would be EXTREMELY helpful! I saw this is part of the 0.93 milestones tho.

I've tried to compile Gephi myself and import the changes, but I'm having some trouble building the project because of expired certificates and stuff (I fought with Maven for a bit, but I'm not super familiar with this developing environment).

**Comment by mbastian** [comment]
Hi, in preparation of the 0.9.3 release I tried to address this by creating a new Preference. This viewport issue will be solved once we move to the new viz engine but that's not the case yet for the 0.9.3 so until then, I thought this workaround would help. 

One can now configure the viewport max size in the Preferences. By increasing the value, it will mitigate the problems.
<img width="359" alt="Screenshot 2022-03-09 at 20 41 52" src="https://user-images.githubusercontent.com/234813/157521029-4b149217-bc94-4a47-83b5-c36a2f060514.png">
