### ISSUE TITLE
Changing ego network filter options does not update context panel.

### ISSUE THREAD

**Issue by pgerbrands** [gephi/gephi#1521]
Before, when I would change the settings in the ego network filter (e.g. include/exclude ego or change the depth from 1 to 2) the context panel would update automatically. Today, after I saw quickly some NetBeans update screen pass by, the context panel does not update automatically anymore. I have to change the filter settings, save the file, close Gephi and re-open it again to see the updated amount of nodes and edges. Starting and stopping the filter, removing and re-adding the filter does not change the behavior, I have to close and re-open the application.

Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_91; Java HotSpot(TM) 64-Bit Server VM 25.91-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_91-b14
System: Windows 8.1 version 6.3 running on amd64; Cp1252; en_US (gephi)

I do not know how to identify what update was implemented in NetBeans (the screen appeared quickly)

**Comment by mbastian** [comment]
Hi, I can't reproduce the issue. Can you please try again with the latest update as well?

**Comment by pgerbrands** [comment]
Hi, I have updated my version and was not able to reproduce the error. If you have done something, thank you for fixing, otherwise, thank you for your support anyway.
