### ISSUE TITLE
"No suitable driver found for jdbc:mysql://localhost:3306/sys".. Do not close

### ISSUE THREAD

**Issue by ShobhitSaxena29** [gephi/gephi#1523]
PLEASE PROVIDE SOLUTION AND HELP ME TO GET OVER THIS.
#1522 was closed saying Duplicate of #1317
#1317 was closed refering #1522 
But no solution in either one. Please provide help.

"Hi I am also facing same problem, getting "No suitable driver found for jdbc:mysql://localhost:3306/sys"

I have tried following: 
1. Help -> check for updates 
2. tools -> plugin -> check for updates 
3. Running Gephi with administrator rights (Run as Administrator)

I am using Gephi 0.9.1

Steps: 
1. File -> Import database -> edge list
2. Host: localhost
3. Port: 3306
4. database: sys
5. username/pswd: root/root 
6. hit on Test Connection

and getting the error that driver not supported. 
Please help urgently..."

**Comment by eduramiba** [comment]
Actually #1317 is still open, that's why I closed the duplicate.

Please try to run gephi as administrator when you do the import, not only when you apply updates.

**Comment by ShobhitSaxena29** [comment]
I have tried when Gephi was launched as administrator but no success.
