### ISSUE TITLE
Adapt crash reporter to send data to a new service

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1530]
Since our self hosted report.php script is no longer available, we should send this data somewhere.

Some options:

* https://getsentry.com/for/open-source/

**Comment by mbastian** [comment]
This is great!

**Comment by eduramiba** [comment]
Yeah, the platform is pretty good :) I sent you an invite some time ago, were you able to check it out?

**Comment by mbastian** [comment]
Yes, I just got in. I'm actually familiar with the platform from work and I'm glad we'll be able to use it forward from the next release.

**Comment by eduramiba** [comment]
Cool! Do you have access to the Gephi organization?
