### ISSUE TITLE
Add Edge dialog only remembers source index

### ISSUE THREAD

**Issue by asr1** [gephi/gephi#1536]
If I am adding multiple edges to a graph, and select say source 112, target 116 and click okay, the next time I open the Add Edge dialog, Source will default to 112, but Target will default to the first node in my graph. 

Is it possible to have both Source and Target remember my previous selection? Or, failing that, to have neither remember? The inconsistency makes adding multiple edges frustrating. The ideal solution would be a setting, but I can't imagine that's high priority :).

**Comment by eduramiba** [comment]
Sure, adding this to the wishlist.
The explanation is that the feature comes from an old gephi version where repeated edges were not possible, but they are now since Gephi 0.9

**Comment by eduramiba** [comment]
Fixed, will be released with next updates. Also now keeps selection in each workspace.
