### ISSUE TITLE
Id sorted as text and not as number in Data Laboratory

### ISSUE THREAD

**Issue by vjandrea** [gephi/gephi#1540]
When i sort the Id column in Data Laboratory, values are sorted as text and not as number, so with 82 nodes at the bottom of the table i see: 78 - 79 - 8 - 80 - 81 - 82 - 9
Ids should be treated as integers.
Using 0.9.1 on Windows 7.

**Comment by eduramiba** [comment]
Hi,
The id column is of string type since Gephi 0.9.

**Comment by vjandrea** [comment]
Is there an option to force the Id to be treated as an integer?

**Comment by vjandrea** [comment]
Ok i found a workaround: i created an integer column named "NumID" and i just copy data there from the Id column.
