### ISSUE TITLE
Large files keep crashing 

### ISSUE THREAD

**Issue by hlmwhit5** [gephi/gephi#1541]
A graph with roughly 400 nodes and 1000 edges keeps crashing my pc. I am able to upload the data but when I go to manipulate the graph the system freezes and then crashes. Do you have any ideas what could be causing this? Are there any minimum system requirements for Gephi 0.9.1?

**Comment by eduramiba** [comment]
Does it crash with 0.9.2 snapshot? https://github.com/gephi/gephi#nightly-builds

**Comment by eduramiba** [comment]
Closing old issue
