### ISSUE TITLE
SVG File - edges missing

### ISSUE THREAD

**Issue by dieggsy** [gephi/gephi#1542]
It seems that when exporting a graph image as an svg file (with weighted edges), the thinnest edges don't show up at all in the svg file, even if they are visible in the preview. This can be somewhat solved by increasing the overall edge thickness, but that can lead to very thick edges if the range of weights is large.

**Comment by duncdrum** [comment]
I haven't encountered this problem could you maybe post a sample file, and provide some context i.e. what gephi version, OS, vector program...?

**Comment by therockmandolinist** [comment]
- Running Gephi 0.9.1 on OSX El Capitan 10.11.5 as well as Microsoft Windows 10 Enterprise Version 10.0.10586 Build 10586. (tried on both)
- Using the 'Rescale edges feature', but I'm not sure it's this feature so much as a large difference in edge thickness (60 vs 1) that's causing the issue. 
- Attached are three files - a sample gephi graph, a sample svg, and a sample pdf. The pdf does show edges, while the svg does not, for the same graph.
The only way I can get it to be visible in the SVG is if I scale it up, which leads to rather nasty huge sized edges. This is a sample graph, as I can't share my actual graph, but the behavior is exactly the same.

[Test.zip](https://github.com/gephi/gephi/files/374764/Test.zip)

**Comment by melounovnik** [comment]
I have exactly the same problem! :-(
Did you find a way to fix it?
Any help would be really appreciated.

**Comment by duncdrum** [comment]
@melounovnik  if i open  @therockmandolinist gephi file, i see the thinnest edges at 1px which is exported as stroke-width 0.0 in the svg.
```svg
<g id="edges">
        <path fill="none" stroke-width="0.0"
              d="M 30.267271,1.029200 C 29.679701,8.515335 17.569145,18.863180 10.083011,18.275610"
              class="0 1" stroke-opacity="1.0" stroke="#000000"/>
        <path fill="none" stroke-width="0.0"
              d="M 10.083011,18.275610 C 3.058615,20.723890 -11.150398,13.859720 -13.598680,6.835324"
              class="1 2" stroke-opacity="1.0" stroke="#000000"/>
        <path fill="none" stroke-width="0.0"
              d="M -13.598680,6.835324 C -17.775295,0.679669 -14.806736,-14.818738 -8.651081,-18.995354"
              class="2 3" stroke-opacity="1.0" stroke="#000000"/>
        <path fill="none" stroke-width="0.0"
              d="M -8.651081,-18.995354 C -4.656310,-25.353752 10.873445,-28.899193 17.231844,-24.904423"
              class="3 4" stroke-opacity="1.0" stroke="#000000"/>
        <path fill="none" stroke-width="1.0"
              d="M 17.231844,-24.904423 C 25.025654,-22.324783 32.846909,-6.764610 30.267271,1.029200"
              class="4 0" stroke-opacity="1.0" stroke="#000000"/>
    </g>
```
what are your edge width settings in the preview pane. These are separate from what happens in overview. I think the mistake is that you are overriding edge thickness for the export via the preview settings like this: 
![screenshot 2016-12-13 14 19 19](https://cloud.githubusercontent.com/assets/6205362/21141861/bce3397e-c13f-11e6-8374-2638ff342305.png)

**Comment by melounovnik** [comment]
@duncdrum Oh I see, so when I uncheck "rescale weight", there isn't any problem with exporting. I didn't realize that overriding edge thickness would be a problem, I thought that the minimum edge thickness for export would be set e.g. 1.0 in the svg.
Thanks a lot for your answer!

**Comment by mbastian** [comment]
Closing, as resolved
