### ISSUE TITLE
Set weights according to duplicate edges 

### ISSUE THREAD

**Issue by hlmwhit5** [gephi/gephi#1543]
I am using Gephi 0.9.1, I know its no longer a feature on this version but is there any way of getting the new version to sum the weights of my edges according to when duplicate edges are found?

I can't get the older versions of gephi to work on my computer.

Thanks

**Comment by eduramiba** [comment]
What kind of file are you importing?

**Comment by hlmwhit5** [comment]
An excel spreadsheet

Sent from my iPhone

On 21 Jul 2016, at 19:54, Eduardo Ramos <notifications@github.com<mailto:notifications@github.com>> wrote:


What kind of file are you importing?

**Comment by eduramiba** [comment]
Then please follow issue #1251 the bug is tracked there.

**Comment by hlmwhit5** [comment]
Sorry but I'm new to Gephi and I don't understand what to do?

**Comment by eduramiba** [comment]
Sorry, this is a known problem and needs to be fixed. I closed this issue as it's a duplicate of #1251

**Comment by hlmwhit5** [comment]
So is there no way of doing it currently?
________________________________

**Comment by eduramiba** [comment]
I think 0.9.0 with updates installed worked fine, but I am not sure.
