### ISSUE TITLE
Time frame import with several static files.

### ISSUE THREAD

**Issue by jiseokk** [gephi/gephi#1546]
I would like to import several static files, representing different time frames, and merge them within Gephi to create a dynamic graph. 

I have looked [here](https://github.com/gephi/gephi/wiki/Import-Dynamic-Data), and noticed that the "time frame" button in the import container window does not exist in the current version. I have also noticed that [this page](https://github.com/gephi/gephi/wiki/index.php#Use_Time_Frame_Import_with_several_static_files) does not exist. 

Is there still an easy way to do this? For reference, I would like to export static .gexf files from Python Networkx module.

**Comment by limw0601** [comment]
I found the same issue recently. Do you have solutions right now? Looking forward to your kindly help.

**Comment by mbastian** [comment]
Yes, this works differently in Gephi 0.9.1. Sorry but the documentation isn't up-to-date. We now allow multiple files to be selected and opened in Gephi's Open menu. Basically, if you import multiple of these static files with a `timestamp` property for each, and that you select "Merge" option in the Import report it will create a unique, dynamic graph.

Here is an example of 3 GEXF files, with 3 timestamps:
```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gephi.org/gexf/1.1draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gephi.org/gexf/1.1draft http://gephi.org/gexf/1.1draft.xsd" version="1.3">
    <graph mode="slice" defaultedgetype="directed" timerepresentation="timestamp" timestamp="1">
        <nodes>
            <node id="n0" label="Bob"/>
            <node id="n1" label="Jack"/>
        </nodes>
        <edges>
            <edge weight="1" source="n0" target="n1">
            </edge>
        </edges>
    </graph>
</gexf>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gephi.org/gexf/1.1draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gephi.org/gexf/1.1draft http://gephi.org/gexf/1.1draft.xsd" version="1.3">
    <graph mode="slice" defaultedgetype="directed" timerepresentation="timestamp" timestamp="2">
        <nodes>
            <node id="n0" label="Bob"/>
            <node id="n1" label="Jack"/>
            <node id="n2" label="Sue"/>
            <node id="n3" label="Beth"/>
        </nodes>
        <edges>
            <edge weight="1" source="n0" target="n1"/>
            <edge weight="1" source="n3" target="n2"/>
        </edges>
    </graph>
</gexf>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gephi.org/gexf/1.1draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gephi.org/gexf/1.1draft http://gephi.org/gexf/1.1draft.xsd" version="1.3">
    <graph mode="slice" defaultedgetype="directed" timerepresentation="timestamp" timestamp="3">
        <nodes>
            <node id="n0" label="Bob"/>
            <node id="n1" label="Jack"/>
            <node id="n2" label="Sue"/>
            <node id="n3" label="Beth"/>
        </nodes>
        <edges>
            <edge weight="1" source="n1" target="n2"/>
            <edge weight="1" source="n3" target="n0"/>
        </edges>
    </graph>
</gexf>
```

Notice the `graph` parameters needed for this to work: `mode="slice"`, `timerepresentation="timestamp"` and `timestamp="X"`. You can use different timestamp formats, or even intervals.

**Comment by ranxu103** [comment]
Hi I'm also trying to create dynamic network using multiple static files. However when I merge them together using the methods above, only attributes/ties from one file is shown and the rest is lost.. Any idea why this happens? Any suggestions and comments would be helpful. And I'm happy to send you the gexf files I'm using if you can take a look. Thanks!

**Comment by UQFG** [comment]
I have the same problem as ranxu103.

Only the edges from the first static file is imported and you cannot import subsequent files.

**Comment by eduramiba** [comment]
Please try with 0.9.2-SNAPSHOT, I think this is fixed https://github.com/gephi/gephi/blob/master/README.md#nightly-builds

**Comment by UQFG** [comment]
Using 0.9.2. I have tried to import multiple .csv files with a Timestamp. I do not get a "merge" option.

**Comment by eduramiba** [comment]
@UQFG can you show an screenshot of import report + steps followed?

**Comment by UQFG** [comment]
![3](https://user-images.githubusercontent.com/29367784/31367068-27f7eef2-adb8-11e7-9e77-0e3e67994453.JPG)
 I am probably importing something with the wrong settings, but I am not sure what.

**Comment by eduramiba** [comment]
It's there, the "Merge into new workspace" option. For correct timestamp format use a ISO 8601 compliant format.

**Comment by eduramiba** [comment]
@UQFG Also, mode and time representation cannot be imported that way in spreadsheet, since it can have only one value per graph. Time representation will be auto-detected based on file contents (you still can manually change it in the second step).

**Comment by UQFG** [comment]
![1](https://user-images.githubusercontent.com/29367784/31473775-ebc9558c-af39-11e7-9728-a5dbfcd6d39d.JPG)

This is what I get if I try to Merge into workspace. If I pick a different type of Timestamp import option (eg. timestampstring), it imports the values in timestamp column as <empty>

**Comment by UQFG** [comment]
If I go back to using an integer as a timestamp, it imports the timestamp but the Timeline is disabled. I can convert the column to dynamic, but not sure how to get it working exactly... I haven't been able to find info on how to convert it properly?

**Comment by eduramiba** [comment]
Yeah these timestamps are incorrect, you need yo import full date+time to be correctly parsed.
For example `2017-10-12T11:22`

**Comment by UQFG** [comment]
![1](https://user-images.githubusercontent.com/29367784/31524880-ce450dc8-afff-11e7-9c9a-3789f6b0ce68.JPG)

I don't have a date, and I need hours/minutes/seconds, not just hours/minutes.

If I import with the time format:
1000-01-01T00:00:00
...it will import without errors, but my timestamp column is empty (as above).

**Comment by eduramiba** [comment]
Right, Gephi does not support hours without dates at the moment.

It seems you have enabled time graphics, and almost all your values have the year 1000 and at least one other a very recent year, producing these very small graphics, try to disable the graphics in data laboratory configuration dialog and check the values.

**Comment by UQFG** [comment]
![capture](https://user-images.githubusercontent.com/29367784/31591042-79cff148-b25e-11e7-94c6-e8b0ec90af7a.JPG)

Ah yes, I can see the timestamp now. I still can't convert this timestamp column to dynamic, however.

**Comment by eduramiba** [comment]
It's already dynamic, just copy the data to the standard timestamp column (or directly name your column 'timeset' in CSV)

**Comment by UQFG** [comment]
Thank you very much - setting the name to "timeset" worked. Your prompt replies are very much appreciated from this novice Gephi user!

**Comment by UQFG** [comment]
Another question, sorry - is there any way of importing dynamic weights as well as time?
ie.
Time  Source  Target  Weight
0           A          B          5
1           A          B          10
2           A          B          5
etc. where the weight of the A->B edge would be twice as thick in Time 1 vs Time 0 and Time 2?

**Comment by eduramiba** [comment]
@UQFG Sure, just name your column timeset (standard time column id) and make sure the column type is TimestampSet

**Comment by UQFG** [comment]
If I import 2 .csv files with timestamp and weight, it imports the timestamp correctly but only the first weight is imported. ie. Timestamp 1 below the weight is 7, Timestamp 2 is supposed to be 16. I have also tried converting to .gexf files, but similarly Timestamp 2's weights are not imported.

![capture](https://user-images.githubusercontent.com/29367784/31868041-ccd3bb6c-b7dc-11e7-9536-c282404d726a.JPG)

**Comment by eduramiba** [comment]
@UQFG Right, you will need to make your weights dynamic in order to be merged. For example:

`[1, 7.0]`

**Comment by UQFG** [comment]
I have now realised that I do not actually need the "timeset" column at all in that case - the timestamp will be built in to the Weight column when I make that dynamic. Thank you very much, @eduramiba !

**Comment by eduramiba** [comment]
@UQFG Thanks for the suggestion, I will think wether it is doable in a simple format such as CSV. Maybe by allowing to mark the column as dynamic in the wizard UI with a checkbox if the timeset column is present.

It's possible with GEXF for example https://github.com/gephi/gexf/wiki/Advanced-Concepts by declaring attributes as dynamic and giving times associated with them. But in CSV we are limited to columns with values, so the only way to do it in CSV right now is to use the textual representation of dynamic data (`[1, 2.0]; [2, 1.5]`).

**Comment by markjhill** [comment]
Hey - I'm having an issue that broadly falls into this category. I've a number of CSVs (edge and node). Each represents a time-slice. I've created a column with the year for each time slice as <[1719]>. When I import the CSVs Gephi recognizes them as timesstamps and chooses timestampset. When they're merged into one workspace, however, the graph is not dynamic ("Timeline disabled"). The timestamp column looks like this: "<[1719.0, 1724.0, 1729.0]". That is, a year for each year that edge was found in (so there can be many years in the timestamp column). I've also tried to make them sequential (so 1720, 1721, 1722), but this didn't change the results. Any help on what I'm doing wrong?

**Comment by markjhill** [comment]
Hey - I'm having an issue that broadly falls into this category. I've a number of CSVs (edge and node). Each represents a time-slice. I've created a column with the year for each time slice as <[1719]>. When I import the CSVs Gephi recognizes them as timesstamps and chooses timestampset. When they're merged into one workspace, however, the graph is not dynamic ("Timeline disabled"). The timestamp column looks like this: "<[1719.0, 1724.0, 1729.0]". That is, a year for each year that edge was found in (so there can be many years in the timestamp column). I've also tried to make them sequential (so 1720, 1721, 1722), but this didn't change the results. Any help on what I'm doing wrong?

**Comment by eduramiba** [comment]
Are you naming you column 'timeset'? I think timline is currently limited to the default standard dynamic column, which has id 'timeset'.

**Comment by markjhill** [comment]
Thanks for your quick reply! 

Yes, I am.

**Comment by eduramiba** [comment]
Can you show a few screenshots of the steps you follow?

**Comment by markjhill** [comment]
Apologies! I'd confused "timeset" with "timestamp" in the CSV - so you were absolutely correct with your first suggestion. (Although my dataset is too large to actually animate it seems (java ends up crashing). I'll need to develop a new strategy for filtering.)

Thanks for your help!

**Comment by eduramiba** [comment]
Oh, it should not crash but we might have some stability issue. Try to increase memory available to Gephi too. https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by mbastian** [comment]
Closing as this looks resolved.

**Comment by abmohit** [comment]
why is the graph looking like this
<img width="1440" alt="Screenshot 2024-10-20 at 3 39 05 PM" src="https://github.com/user-attachments/assets/972bfa09-79c1-4e0d-b3c7-2574a4426286">
<img width="1440" alt="Screenshot 2024-10-20 at 3 40 22 PM" src="https://github.com/user-attachments/assets/0889a5b8-d2d5-482d-bb69-b964b732a8c0">
<img width="1440" alt="Screenshot 2024-10-20 at 3 40 31 PM" src="https://github.com/user-attachments/assets/2b4d7211-4803-4c86-b843-bee045def10d">
