### ISSUE TITLE
Constellation does not show up when clicking on the Overview button 

### ISSUE THREAD

**Issue by Jamestbw** [gephi/gephi#1547]
Hi officer,

I have just installed Gephi software on my Windows 10 computer. 
After launching the software, 
1. I created new project, 
2. I created nodes A,B, C
3. I created unidirectional edges A-B, A-C and B-C.

When I click on the Preview button, I was able to see the constellation on the screen. However, when I click on the Overview button, the screen keeps showing "Initializing..." but does not show the constellation and toolbars.

Please send reply to my email, jamestbw3005@gmail.com

Thank you and Regards,
James

**Comment by eduramiba** [comment]
Hi,
Please try to update your graphic card drivers.

**Comment by eduramiba** [comment]
Also please check #1192 for possible fix

**Comment by eduramiba** [comment]
Dit it work?

**Comment by eduramiba** [comment]
Closing as there are many other issues regarding thie problem with opengl
