### ISSUE TITLE
Cannot build: dependency issues

### ISSUE THREAD

**Issue by PhillHenry** [gephi/gephi#1551]
Cloning from https://github.com/gephi/gephi.git and building gives:

[ERROR] Failed to execute goal on project utils-longtask: Could not resolve dependencies for project org.gephi:utils-longtask:nbm:0.9.2-SNAPSHOT: The following artifacts could not be resolved: org.netbeans.api:org-openide-util-lookup:jar:RELEASE81, org.netbeans.api:org-openide-util:jar:RELEASE81: Could not find artifact org.netbeans.api:org-openide-util-lookup:jar:RELEASE81 in netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans/) 

Trying to access the repository in my browser just gives a blank page.

**Comment by eduramiba** [comment]
Closing as netbeans fixed this today.
