### ISSUE TITLE
SIGSEGV because of i965_dri.so

### ISSUE THREAD

**Issue by motatuc** [gephi/gephi#1552]
Hello

gephi 0.91 and the latest snapshot is always crashing after start.

Steps:
1) Start gephi
2) Open any sample gephi provides (or start new project and try to draw something)
3) Press ok
-> Crash

System: 
Ubuntu 16.04
Intel i7 6200 and HD Graphics 520

> ./gephi
> A fatal error has been detected by the Java Runtime Environment:
> SIGSEGV (0xb) at pc=0x00007fb30834bd8b, pid=29023, tid=140406801057536
> JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
> Problematic frame:
> C  [i965_dri.so+0x20ad8b]
> Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

For more information look at the attached file.
[hs_err_pid29023.txt](https://github.com/gephi/gephi/files/401780/hs_err_pid29023.txt)

**Comment by eduramiba** [comment]
You can try to use Oracle JDK and the suggested fix here #1192

**Comment by eduramiba** [comment]
Did it work?

**Comment by gohoyer** [comment]
I had the same problem and running gephi with `LIBGL_ALWAYS_SOFTWARE=1 ./gephi` did the trick for me.

**Comment by motatuc** [comment]
I was doing it the same way as @gohoyer described it.

**Comment by dannyman** [comment]
+1, and @gohoyer 's workaround works for me.

**Comment by eduramiba** [comment]
Closing old issue
