### ISSUE TITLE
OpenGL problem

### ISSUE THREAD

**Issue by RAnnunziata** [gephi/gephi#1558]
I have tried repeatedly to activate my Gephi acct but it never works. Help please
The reason I need the acct is I am having an issue with Gephi wherein it thinks I do not have the proper version of Open GL. Is there a fix other than adding a new graphics card. I have 30 computers in a lab and that would not be possible

**Comment by eduramiba** [comment]
Is that in the forum? What's the problem?

If you have two graphic cards Gephi may be picking the wrong one, try to force the correct one.
Also, please attach your messages.log (in user directory https://github.com/gephi/gephi/wiki/Troubleshooting) file so maybe we can find the problem.

**Comment by RAnnunziata** [comment]
![gephi error](https://cloud.githubusercontent.com/assets/20953307/17710124/dea1f1a6-63b9-11e6-94f0-1bbc9bcbcc71.jpg)
Only 1 graphics card. Intel on an HP Elitedesk 800G1

**Comment by eduramiba** [comment]
Also updating graphic drivers may help.

**Comment by RAnnunziata** [comment]
Already tried new driver. Is there a way to tell Gephi to use the intel graphics. Its as if Gephi is not seeing the controller

**Comment by eduramiba** [comment]
I think it just should use it. Did you try the ones at http://h20564.www2.hp.com/hpsc/swd/public/readIndex?sp4ts.oid=5387476 ?

**Comment by RAnnunziata** [comment]
yes

**Comment by eduramiba** [comment]
It seems it's not picking up the driver. What's on your device manager?

**Comment by RAnnunziata** [comment]
Device manager shows Intel HD Graphics 4600 which supports OpenGL version much higher than what gephi is reporting. Oddly enough I installed an OpenGL viewer and it also reports as Gephi does version 1.1

**Comment by eduramiba** [comment]
Seems to be this problem https://communities.intel.com/thread/64042
Not sure what's the solution though.

**Comment by RAnnunziata** [comment]
I find it odd that an OpenGL viewer also reports what Gephi does. OpenGL version 1.1. The issue would appear to be on Intel's end. Do you concur?

**Comment by eduramiba** [comment]
Yeah that's the case I think. You can try the diagnostics in that link.

**Comment by eduramiba** [comment]
Were you able to get it working?

**Comment by RAnnunziata** [comment]
Yes
The issue was a reg hack we had made that removed the contextual menu for changing resolutions when you right click on desktop

~Rick Annunziata
  Endpoint Systems Administrator | Clark University - Carlson Hall
  950 Main St | Worcester, MA 01610
  P: 508-793-7319<tel:508-793-7319> | F: 508-793-8823<tel:508-793-8823>
  http://www.clarku.edu/helpdesk

**Comment by eduramiba** [comment]
Cool :) Closing this then.
