### ISSUE TITLE
Partition filter doesn't work with edges

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#1564]
Version 0.9.0 and 0.9.1

**Comment by xyffar** [comment]
Has this been fixed? I downloaded the last milestone and it seems it hasn't.

**Comment by eduramiba** [comment]
I just tested and this does not seem to work correctly, reopening.

**Comment by ab1232** [comment]
I very much appreciate your attention to this matter. I really need this to work for an important project with large entries. I am aware that this can be also done manually, but would it be possible to give an estimated time to when this could potentially be fixed ?
