### ISSUE TITLE
Add option for minimum edge width in preview mode

### ISSUE THREAD

**Issue by alexbovet** [gephi/gephi#1568]
When exporting a weighted graph in SVG, using the rescale weight option seems to be rescaling the width between 0 (or at least a very small value) and a max value.

It would be nice to have control on the range used for the rescaling. (min and max)

I tried varying the range of the weights, but the rescale option seems to always give the same results. I guess it removes any offset in the weights distribution?

Thanks!

**Comment by melounovnik** [comment]
Totally agree. 
It also leads to a problem with not displaying edges of minimum weight in Inkscape for example...

**Comment by alexbovet** [comment]
any plan for implementing this?

**Comment by eduramiba** [comment]
Adding it to 0.9.2 milestone, no planned date yet though.

**Comment by H-Rao** [comment]
@eduramiba : Hello, Does "Fix Committed" mean "Resolved"?

**Comment by eduramiba** [comment]
Hi @H-Rao Yes, this was commited and released in 0.9.2

**Comment by H-Rao** [comment]
Thank you.
