### ISSUE TITLE
Writing to GEXF file

### ISSUE THREAD

**Issue by malihaz** [gephi/gephi#1569]
Hi all,
I m trying to visualize a digital library. I want to be able to update my Gexf file programmatically in order to add / remove nodes and edges whenever an admin adds some data to that library.  Currently i dont find any solution/ feature to achieve this functionality. Any help in this regard would be greatly appreciated.
Thanks.

**Comment by eduramiba** [comment]
Hi,
I recommend you to ask for help on the [Gephi Facebook group](https://www.facebook.com/groups/gephi/)

**Comment by malihaz** [comment]
Ok thanks
