### ISSUE TITLE
Windows 7 64bit, Gephi 0.9.1 freeze on Starting Modules

### ISSUE THREAD

**Issue by mingchau** [gephi/gephi#1573]
Attached the messages.log file.

I have did enough research, upgraded the graphic card driver to the latest.

Can not fix it. Can you please help?
[messages.log.txt](https://github.com/gephi/gephi/files/490928/messages.log.txt)

**Comment by eduramiba** [comment]
Does it work with administration privileges?

**Comment by mingchau** [comment]
Eduardo,
Thank you for your reply.
I tried with the administrator account, still doesn't work.
0.8.2 version works fine.
Is it a bug need to wait for the next version? 星期六, 24 九月 2016, 08:01下午 +08:00 发件人 Eduardo Ramos  notifications@github.com :

**Comment by mingchau** [comment]
OS:
Windows 7 6.1 x86 

Java:
version: 25.101-b13
Java HotSpot(TM) Client VM, Oracle Corporation 

OpenGL version:
4.5.13399 Compatibility Profile Context 15.200.1062.1004
Vendor:
ATI Technologies Inc.
Renderer:
AMD Radeon HD 8370D

**Comment by eduramiba** [comment]
You can try to update your graphic card drivers.

**Comment by mingchau** [comment]
I have already updated it to the latest, still not work.

**Comment by eduramiba** [comment]
Ok thanks, we will need to investigate problems with JOGL

**Comment by eduramiba** [comment]
Tracking at #1631
