### ISSUE TITLE
how to import single csv file in gephi for visualizing graph properties of edges and nodes

### ISSUE THREAD

**Issue by Kittydeena** [gephi/gephi#1577]
Hello
i am new to gephi, i would like to analyze this wiki-vote.txt data set from standford in gephi
this dataset only contain FROMNODEID and TONODEID coloumns,
how woud i load edges and nodes files from this single file to make it in graph format.
Normally what i read is that we have seprate node file and seprate edge list , once they are loaded only then graph i generated, can any one plz help me out with this...
what are steps to extract node and edges and make complete graph in gephi.

**Comment by eduramiba** [comment]
You can use gexf for example.
