### ISSUE TITLE
The issue about 'How to calculate the composed degree'

### ISSUE THREAD

**Issue by sfazei** [gephi/gephi#1579]
Hi dear,Thank for your precious time to look this request

I'm not a programmer but i do really want to use your software as an student who study the patent relationship. But here i find some problem when i use your great software.

Background: I'm studying patent relationship where i need to calculate the composed degree as a company not as a node,which means company have a lot of patent nodes,so i need mix a lot of nodes into one as a subject to analyze'

Problem:I can not find a function which can previously be found that you can mix a lot of nodes into a bigger node and do the analysis subsequently in a new version ,you may call it hierarchy? So , how can i figure out this problem with new version Gephi ? 

And sorry for my poor English , i'm not native speaker so if there is something i didn't express clearly,please note it .

Best Regards
Sebastian
Mail:zweizwk@126.com

**Comment by eduramiba** [comment]
Hi,
Hierarchy is no longer available in Gephi 0.9+
You will need to use Gephi 0.8.2. Make sure to install updates => check this for instructions https://github.com/gephi/gephi/releases/tag/v0.8.2
