### ISSUE TITLE
JOGL - Issue with jogl library in GEPHI

### ISSUE THREAD

**Issue by prabha123** [gephi/gephi#1580]
Currently, working in gephi for social network graph. Graph is still initializing in graph tool and it gives me the exception as

"java.lang.UnsatisfiedLinkError: Can't load library: C:\Program Files (x86)\Gephi-0.9.1\natives\windows-amd64\gluegen-rt.dll" and "java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile"

**Comment by eduramiba** [comment]
Does it work with admin privileges?
Otherwise you can try to reinstall Gephi or use the tar.gz distribution https://github.com/gephi/gephi/releases/download/v0.9.1/gephi-0.9.1-linux.tar.gz

**Comment by prabha123** [comment]
I installed on my lap, it works fine but in my desktop it's not also I tried re-installation.  I have checked all the dependencies, but I really don't know the real issue.

**Comment by eduramiba** [comment]
Did you try to run the tar.gz distribution?

**Comment by eduramiba** [comment]
Did it work?

**Comment by eduramiba** [comment]
Closing old issue
