### ISSUE TITLE
GraphML export: Gephi doesn't generate the id attribute on edges

### ISSUE THREAD

**Issue by NKame** [gephi/gephi#1585]
The GraphML format specifies that an edge can have an id in its "id" attribute (see http://graphml.graphdrawing.org/specification/element_edge.xsd.htm ). But in Gephi, the edge's id is stored in a custom attribute "edgeid". Tools like TinkerPop can't read the generated GraphML files directly because of this missing attribute, which is wrong by the way, but since we have the id, why not put it in it's designed place.

**Comment by eduramiba** [comment]
Thanks! Fixed in commit e13ce1addc50f04ec67192e3096b7d1b82345372
