### ISSUE TITLE
Unable to connect to the Gephi Update Center because of https://raw.githubusercontent.com/gephi/gephi/gh-pages/0.9.2-SNAPSHOT/netbeans_site/updates.xml

### ISSUE THREAD

**Issue by dragonxtek** [gephi/gephi#1595]
I compiled gephi (version 0.9.2-SNAPSHOT) and I try to update plugins.
If I choose No proxy, I pass the test connection
![selection_150](https://cloud.githubusercontent.com/assets/10552658/19398799/bd7998c8-9224-11e6-8d94-1f7fa7732bf0.png)

But, When I try to update I can't do it:
![selection_151](https://cloud.githubusercontent.com/assets/10552658/19398826/d97e72d2-9224-11e6-9b6b-434d9c2c6316.png)

I try to load [https://raw.githubusercontent.com/gephi/gephi/gh-pages/0.9.2-SNAPSHOT/netbeans_site/updates.xml](https://raw.githubusercontent.com/gephi/gephi/gh-pages/0.9.2-SNAPSHOT/netbeans_site/updates.xml) by the browser, but it doesn't load.
It exists?

**Comment by eduramiba** [comment]
Hi, this is normal, we only publish updates once a version is released.
