### ISSUE TITLE
Ubuntu 16.04.1 LTS, Crash at startup

### ISSUE THREAD

**Issue by jaschaknack** [gephi/gephi#1601]
Gephi crash immediately at startup. No error message before.

OS:
Ubuntu 16.04.1 LTS

OpenGL version, Vendor, Renderer:
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics
OpenGL core profile version string: 4.5.13448 Core Profile Context 16.30.3
OpenGL core profile shading language version string: 4.50

OpenJDK & Oracle JDK tested.
[hs_err_pid6125.txt](https://github.com/gephi/gephi/files/537769/hs_err_pid6125.txt)
[hs_err_pid4497.txt](https://github.com/gephi/gephi/files/537770/hs_err_pid4497.txt)

**Comment by eduramiba** [comment]
Seems a Linux graphic card drivers problem.
Please try the solution at https://github.com/gephi/gephi/issues/1192

```bash
LIBGL_ALWAYS_SOFTWARE=1 ./gephi
```

**Comment by jaschaknack** [comment]
Thank you for your response. I tried the possible solution you mentioned above but it does not solve the issue. I still get the same error.

# Problematic frame:
# C  [amdgpu_dri.so+0x23a0f72]

**Comment by eduramiba** [comment]
That's still a bad graphics driver crash.
Try with
`export LIBGL_ALWAYS_SOFTWARE=1`
Then in the same session:
`./gephi`

**Comment by jaschaknack** [comment]
Does not make a difference. Graphics Driver is working properly in other applications, just verified this.

**Comment by jaschaknack** [comment]
Gave it another try and it seems to work. Maybe this result is not representative as I'm now using the oibaf bleeding edge gpu drivers repository.
