### ISSUE TITLE
java.lang.NullPointerException when using PartitionElementColorTransformer

### ISSUE THREAD

**Issue by Kalethars** [gephi/gephi#1603]
Column TopoCol = graphModel.getNodeTable().getColumn("Topo");
Function colorPartition = appearanceModel.getNodeFunction(graph, TopoCol, PartitionElementColorTransformer.class);
Partition P = ((PartitionFunction) colorPartition ).getPartition();

For some data, these codes runs well.
But for other data, "java.lang.NullPointerException" for the third line.

**Comment by jbliesener** [comment]
Maybe there's no column called "Topo" on the datasets that don't work?

**Comment by eduramiba** [comment]
If what @jbliesener is not the problem, it may be related to this bug to be fixed https://github.com/gephi/gephi/issues/1459

**Comment by Kalethars** [comment]
@jbliesener Nope, "Topo" is a list of numbers. This list when be read as Double, and seems to have erros for some data. But after I create a new column to copy this list from Double to int, the error occurs no more. It's weird.

**Comment by eduramiba** [comment]
Oh I think what's happening is that appearance automatically chooses ranking instead of partition for that column if it's double. Try to use the `forcePartitionFunction` https://gephi.org/gephi/0.9.1/apidocs/org/gephi/appearance/api/AppearanceController.html

**Comment by Kalethars** [comment]
@eduramiba I and my friends meet the same question on Transformers, such as RankingElementColorTransformer, RankingNodeSizeTransformer. Also, if I use other columns, such as Modularity.MODULARITY_CLASS, the NullPointerException occurs sometimes.

**Comment by eduramiba** [comment]
Yeah I think you need to *force* the mode sometimes. This has been known as a problem and will probably change in next Gephi version.

**Comment by Kalethars** [comment]
@eduramiba Ok, thank you, I will try it. :-)

**Comment by Kalethars** [comment]
@eduramiba Hmm, excuse me, how to use forcePartitionFunction?
Add "appearanceController.forcePartitionFunction(colorPartition);" between line 2 and line 3?

**Comment by eduramiba** [comment]
@Kalethars I am not sure about the API, but I think you first need to call appearanceModel.getNodeFunctions()
This gives an array of functions, pass the correct one to `forcePartitionFunction` and then do your normal code. To identify the function for the correct column, cast each element in the array of functions to `AttributeFunction`.

**Comment by eduramiba** [comment]
Did it work? It will be easier in 0.9.2

**Comment by Kalethars** [comment]
@eduramiba 
oh, 0.9.2 released, I will try the new version. 👍

**Comment by Kalethars** [comment]
@eduramiba 
Seems 0.9.2 only for GUI, not for Java API.

**Comment by eduramiba** [comment]
Only 0.9.2-SNAPSHOT is available, not the final release. I triggered a new build of toolkit 0.9.2 snapshot, please try to download it again.

**Comment by Kalethars** [comment]
@eduramiba 
0.9.2 Snapshot can't use palette in color partition.

**Comment by Kalethars** [comment]
@eduramiba 
This problem is fixed! Thank you 👍

**Comment by eduramiba** [comment]
Cool! Closing this then
