### ISSUE TITLE
Dynamic node attribute (from csv file) causes unexpected exception

### ISSUE THREAD

**Issue by Bob-boisson** [gephi/gephi#1607]
I imported a csv file having an attribute column named paper that looks like this  <[2006, 2007, 2]; [2009, 2009, 5]; [2011, 2011, 7]; [2013, 2015, 4]> using the data type intervalintergermap (with the import spreadsheet option)

After having enabled the timeline, when I try the resize the window, the filtering dynamic range start to compute without ending and it throws the unexpected error "paper is not a sortable column)
![filtering_dynamic_range](https://cloud.githubusercontent.com/assets/23218202/19936985/e44ea6e8-a0f5-11e6-8b65-1b7a901f53fa.png)

![exception](https://cloud.githubusercontent.com/assets/23218202/19936988/e8ef0d6e-a0f5-11e6-97ed-15bcaa91cda4.png)

![exception3](https://cloud.githubusercontent.com/assets/23218202/19937021/0d2d9286-a0f6-11e6-87d8-98aa07801cb7.png)

Also if I press the stop filtering button in the overview panel (remember it tries to filter the dynamic range indefinitely) then the exception changes to: 
![exception4](https://cloud.githubusercontent.com/assets/23218202/19937101/449b7f76-a0f6-11e6-81d7-e34a40e6f724.png)

![exception5](https://cloud.githubusercontent.com/assets/23218202/19937104/47bcabe4-a0f6-11e6-80d2-66b9ea22befc.png)

here is the file I try to load in and play with
[node_test_extract_close_bound_2.txt](https://github.com/gephi/gephi/files/567109/node_test_extract_close_bound_2.txt)

**Comment by eduramiba** [comment]
This will be fixed with https://github.com/gephi/graphstore/issues/130 Similar to #1612

**Comment by eduramiba** [comment]
Fixed, will be released with next updates.

**Comment by Bob-boisson** [comment]
great, do we have a time window for the next updates ? just to know if we are talking weeks or months ?

**Comment by eduramiba** [comment]
Hi, I think I can upload new updates this week :)

**Comment by Bob-boisson** [comment]
wow that would be super nice and quick ! thank you very much fro your hard work ;)

**Comment by eduramiba** [comment]
Hi,
Updates for this are already available.

**Comment by Bob-boisson** [comment]
super, just tried it and it works well ;)
