### ISSUE TITLE
Can I output the graph to json using the toolkit 0.9.1?

### ISSUE THREAD

**Issue by ZhitongLei** [gephi/gephi#1608]
Can I output the graph to json using the toolkit 0.9.1? 
It seems that the Exporter only support gexf and pdf.

**Comment by eduramiba** [comment]
Hi,
This is not a core feature of Gephi.
You can check this plugin https://gephi.org/plugins/#/plugin/jsonexporter-plugin source code: https://github.com/oxfordinternetinstitute/gephi-plugins/tree/jsonexporter-plugin/modules/JsonExporter/src/main/java/uk/ac/ox/oii/jsonexporter

**Comment by ZhitongLei** [comment]
Get it. Thanks.

**Comment by lapsus63** [comment]
If you're not using Netbeans, you may have to create manually the following file in your environment. The ServiceProvider won't generate it.

File `META-INF/services/org.gephi.io.exporter.spi.GraphFileExporterBuilder` :
`uk.ac.ox.oii.jsonexporter.JSONExporterBuilder`

Nota : The builder should be renamed to ExporterBuilderJSON to be consistent with other builders (I'm using version 0.9.2 of gephi-toolkit)
