### ISSUE TITLE
Dynamic graph with YEAR attribute

### ISSUE THREAD

**Issue by Kittydeena** [gephi/gephi#1611]
i want to make my graph dynamic, but i donot have start and end date,its coauthorship network which contains year attribute when authors published their paper.
can any one tel me how does i make it time evolvng graphT

**Comment by eduramiba** [comment]
Gephi now supports timestamps for dynamics as well ([check blog post](https://gephi.wordpress.com/2015/11/02/announcing-gephi-0-9-release-date/)).

We still need to update wiki and documentation about this. Meanwhile, I attach a GEXF file example that uses timestamps instead of intervals (exported from Gephi 0.9.1 after generating a dynamic network).

[dynamic.gexf.zip](https://github.com/gephi/gephi/files/571769/dynamic.gexf.zip)

**Comment by Kittydeena** [comment]
but i dont have time stamps, i just have year in which two authors published together, doesnt that make it dynamic in nature?  but how does gephi take that into consideration for making it time evolving graph? i dont see any tutorial specifying only year as criteria for making it dynamic rather every turial talk about start and end data

**Comment by eduramiba** [comment]
The years can be the timestamps as they are, you will see the year numbers in the timeline.

**Comment by Kittydeena** [comment]
i have created my own dataset with source target and year(1952,1953,...2002) attribute, how do i make it dynamic now? once i imported it in gephi,its not showing time line?

**Comment by eduramiba** [comment]
These would be the steps to import it as CSV:

1. New project
2. Go to data laboratory
3. Click on **Configuration** button. Then select 'Timestamps' as Time representation
4. Import Spreadsheet
5. Select your file and import it

The file has to have the following format:

```csv
source,target,timeset
1,2,"[2009, 2012, 2015]"
3,2,"[2008, 2011, 2016]"
```

Specially make sure the third column is called timeset. If everything is correct, it will be imported as 'TimestampSet' in the import spreadsheet wizard.

**Comment by Kittydeena** [comment]
1,2,"[2001]"
i have time stamp for each edge, like paper is published in one particular year cnt write more then one year

**Comment by eduramiba** [comment]
Sure, no problem, that was just an example. A single timestamp is valid too.
You can also omit [ and ], they will be added automatically.

So you can import this:

```csv
source,target,timeset
1,2,2012
2,3,2014
```

**Comment by Kittydeena** [comment]
thats perfect, is there any option is gephi to do regression correlation? or to fit power law gaussian etc ?

**Comment by Kittydeena** [comment]
another thing how does we select edges based on edges, for example in citation network ; how do we select an edge based on its weight ( attribute), i dont see any option in gephi to visualize edges based on weights

**Comment by eduramiba** [comment]
About correlation and fitting, not available as far as I know. Only statistic is Average Degree, which shows degree distributions but only linear at the moment.

You can use the 'Edges > Edge Weight' filter to filter edges based on weight.
