### ISSUE TITLE
Exporting data tables with the automatically added [Nodes] and [Edges] tags does not work

### ISSUE THREAD

**Issue by zackbatist** [gephi/gephi#1613]
Tried exporting tables of nodes and edges, and had to remove the [Nodes] and [Edges] suffixes tha are automatically added to the file names. Not doing so resulted in the contents of the File Name field being copied over to the Files of Type field in the save dialog. Using 0.9.1 on Linux Mint Sarah.

**Comment by eduramiba** [comment]
Hi,
I can't reproduce this, can you show an screenshot?

**Comment by eduramiba** [comment]
I can now reproduce it, seems to be a Linux-specific problem, need to investigate or workaround.

**Comment by zackbatist** [comment]
Apologies for the very late reply. It seems to be an issue with the square brackets. If you add a character after the predefined file name then the issue persists, but if you remove the square brackets it works fine.

**Comment by eduramiba** [comment]
This no longer applied to spreadsheet export in 0.9.2.
