### ISSUE TITLE
modulairty( epsilon)

### ISSUE THREAD

**Issue by Kittydeena** [gephi/gephi#1614]
what does epsilon mean in modularity function of gephi
i m getting value 0 for modeulairyt in coauthorship network
what insights does it give
am i doing mistake in setting epsilon value
as far as i know modulairity gives us community structure,...correct me if i m wrong

**Comment by eduramiba** [comment]
When modularity value changes less than `epsilon` in an iteration, it's considered to have converged, and then the algorithm finishes.
