### ISSUE TITLE
displaying pics with nodes as label 

### ISSUE THREAD

**Issue by Kittydeena** [gephi/gephi#1615]
is there any option in gephi to display images with nodes instead of labels.

**Comment by eduramiba** [comment]
Only available with a plugin for the moment: https://marketplace.gephi.org/plugin/image-preview/
Note it won't work in 0.9.1 yet, only 0.8.2

**Comment by Kittydeena** [comment]
but that cant work with latest gephi version right...i  m asking about latest gephi version . 0.9.

**Comment by eduramiba** [comment]
Right, it needs to be adapted yet.
