### ISSUE TITLE
Node Labels

### ISSUE THREAD

**Issue by dmdevasto** [gephi/gephi#1617]
The settings that I select for the node labels in the overview window (to node size, etc) will not transfer to the preview window. The only way that I can get the node labels to show up in the preview window is to manually check the box under the settings tab. The node labels appear, but they are only configured as set in the settings tab. Help!

**Comment by eduramiba** [comment]
Hi,
This is the normal behaviour of Gephi at the moment. It could help to do some settings synchronization but at the moment they can't be matched one to one.

**Comment by dmdevasto** [comment]
Thanks for the response. So, if I'm understanding you correctly, it's basically pointless to use the options in graph view (in the overview window) to configure the labels?

**Comment by eduramiba** [comment]
Well, only for preview, they are useful in overview for visualization and interaction.

**Comment by dmdevasto** [comment]
Ultimately, I want to export the visualizations to .pdf or .png. In which case, what I see in preview is what I get, right?

**Comment by eduramiba** [comment]
Right, you will need to configure everything in preview for exporting. Fortunately its options are more complete and powerful.

**Comment by dmdevasto** [comment]
Gotcha. Thanks!
