### ISSUE TITLE
Increased border color customization [Feature request]

### ISSUE THREAD

**Issue by Esoppant** [gephi/gephi#1618]
The idea is to offer in Preview the same border colorisation that is default in Overview. Currently, one can configure "Parent" (same color as the node) or "Custom". We could add a 3rd option.

### Definition of done
- Extend the node border color editor with a default "Parent Darker" option that follows the Overview settings .
- (optional) Add another option following the wishlist idea, with the ability customize the saturation/brightness on top

### Original bug report

I believe having more than "Parent" and "Custom" in the border color options would be a nice move for better visualization. If I'm not mistaken, the only possible way to give individual borders to nodes with different colors is by using black borders with black background and reducing opacity, which creates the illusion of a darker shade on the edges (If I _am_ mistaken, I'd be glad to know if there is a more ideal way).

A saturation and/or brightness slider that adds or removes a set amount of saturation/brightness from the parent color, and applies this color to the border would be perfect. Or if a slider is a complicated feature to implement in such a way; it could be preset radio buttons like "parent - 30 saturation", "parent - 30 brightness".

**Comment by Splines** [comment]
I really like the border/stroke of the nodes in the Overview tab. They are a darker version of the fill color:

![image](https://user-images.githubusercontent.com/37160523/173933688-c404090f-4084-4f7c-89fa-2fffbdad8460.png)

However, this is not the case in the preview tab, even with Border color set to "parent":

![image](https://user-images.githubusercontent.com/37160523/173933697-a3bb5494-1e5d-4032-8d20-c1cac7d70fa1.png)
