### ISSUE TITLE
Self loop edges display

### ISSUE THREAD

**Issue by Pulmarin** [gephi/gephi#1619]
I believe there is a visualization problem with self loop edges on Gephi v0.9.1 : when displayed in the overview window they are normally represented (the little "crowns" at the top of some nodes), but when displayed in the export window, the self loop edge is represented by a thick and straight line that goes nowhere, which is way less aesthetic. This bug didn't exist in v0.8.2, which i used to use.

**Comment by jbliesener** [comment]
See also #1480, second item
