### ISSUE TITLE
SOLVED!import-error that used to work! "Found row(s) with empty Source and/or Target columns"

### ISSUE THREAD

**Issue by BallsofNorway** [gephi/gephi#1621]
*CRISIS at hand while home EXAMN*

![image](https://cloud.githubusercontent.com/assets/22032743/20455517/1554bb40-ae5e-11e6-8d47-c3e04b17036c.png)

There is no row with empty source or target columns !

I'v used 17 h to make these spreadsheets and some how during the last 10 h of data plotting, it stoped working. 

Is there a limit? 

Nobody seems to be able to correct this error, 

because gephi and edges_spreadsheet worked earlier on, but not when all data was put in.

![image](https://cloud.githubusercontent.com/assets/22032743/20455514/ef6869d6-ae5d-11e6-9dc7-d465dc9852bf.png)

This is the nodes and sources spreadsheet from my University of Bergen folder

http://folk.uib.no/akv092/stuff/207/done_207_nodes_authors.csv
and 
http://folk.uib.no/akv092/stuff/207/done_%20207_edges.csv

The "old" edge file seems to work., why is that?
(http://folk.uib.no/akv092/stuff/207/edges.csv file from when i was half done )  

![image](https://cloud.githubusercontent.com/assets/22032743/20455529/60f0ddb8-ae5e-11e6-9333-0badc1c62876.png)

Can anybody help me to understand where the problem is?

Something is not right,  but me and my professor + masterstudents cant find it?

Please help me... 

thanx alot :)

**Comment by BallsofNorway** [comment]
AAAaarrrrrrggg. 

The error was on line 599. 

found it after copying data in to notepad++

**Comment by duncdrum** [comment]
sometimes there are errors introduced to csv if for example they move across platforms, say from csv created in MSExcell on Win to LO on linux. Can you open your csv in a texteditor (show invisibles) and see if there are any hidden characters (newline, eol, etc) that mess with the import.

**Comment by BallsofNorway** [comment]
Tnx :)
