### ISSUE TITLE
Setting label position

### ISSUE THREAD

**Issue by melounovnik** [gephi/gephi#1622]
Is there any possibility how to change default label position above the nodes, at least manually? I'd appreciate if the labels were e. g. placed on the top of the nodes or on the top-right of the nodes for improving their readability.
Thanks!

**Comment by eduramiba** [comment]
This is a wishlist issue #560. Meanwhile you could export to SVG and move label layers manually in inkscape or similar.

**Comment by melounovnik** [comment]
So still a wish... :( But thank you for your answer and a helpful idea!
