### ISSUE TITLE
Visualization and parallel edges

### ISSUE THREAD

**Issue by dmdevasto** [gephi/gephi#1624]
Importing CSV spreadsheet to 0.9.1 and it doesn't appear that the parallel/multi-edges are being shown. If I add edge labels, I can see the overlapping label text from the different edges in the preview screen, but this is not very helpful visually. Is there any support for visualizing these multi-edges? I've also been playing around with merging the weights of the multi-edges, but from what I can tell that isn't yet supported either.

**Comment by jbliesener** [comment]
See also #1480

**Comment by dmdevasto** [comment]
Yes! Sounds like we are in the same boat.

**Comment by eduramiba** [comment]
Closing as duplicate of #1480
