### ISSUE TITLE
Linux error

### ISSUE THREAD

**Issue by augustgs** [gephi/gephi#1626]
On linux lsb_release: 
Distributor ID:	Ubuntu 
Description:	Ubuntu 15.10 
Release:	15.10 
Codename:	wily 

 when i want to install a plugin on gephy it hangs and freezes and i cant do nothing more... how could i solve this ?

**Comment by eduramiba** [comment]
Hi,
Please include your messages.log file from [gephi user directory](https://github.com/gephi/gephi/wiki/Troubleshooting)

**Comment by augustgs** [comment]
Updated Java to 1.8 again and worked
