### ISSUE TITLE
can gephi analyze data from cdr "call detail records" in a redhat linux?

### ISSUE THREAD

**Issue by abumregha** [gephi/gephi#1628]
can gephi analyze data from cdr "call detail records" in a redhat linux?
I am trying to install it on a machine with redhat, and access it from the web, is it possible?

**Comment by eduramiba** [comment]
Not directly, you will have to transform them to one of the supported formats: https://gephi.org/users/supported-graph-formats/

**Comment by abumregha** [comment]
OK, as a matter of fact, cdr are stored an a CSV format :)

**Comment by eduramiba** [comment]
Oh I see, something like this? http://www.voip-info.org/wiki/view/Asterisk+cdr+csv

Then, it should be easy to import using spreadsheet format as an edges table. Change 'src' to 'source' and 'dest' to 'target'.

**Comment by abumregha** [comment]
I don't really have enough experience in this but: can i install gehpi on a  redhat server and access it from the web?
If not, what would you recommend as an alternative to gephi

**Comment by eduramiba** [comment]
Gephi does not have a web interface, but some options are:

* Maybe X-Forwarding/VNC works with Gephi, not sure how usable
* Using the gephi toolkit to script gephi usage (only valid if you want to automatize something)
