### ISSUE TITLE
0.9.1 on windows freeze at 'starting modules'

### ISSUE THREAD

**Issue by szrlee** [gephi/gephi#1631]
###java is the latest version.
![qq 20161213212031](https://cloud.githubusercontent.com/assets/6252426/21141824/3b65e5a0-c17a-11e6-8b8d-26e49df2b227.png)

**Comment by eduramiba** [comment]
Hi,
Can you share your messages.log file (see https://github.com/gephi/gephi/wiki/Troubleshooting)?

Also try to update your graphic cards drivers and run Gephi as admin.

**Comment by Aluus** [comment]
Try JDK 1.7 may solve your problem. To me, this method worked.

**Comment by eduramiba** [comment]
Does it work for anyone with latest 0.9.2 SNAPSHOT? https://github.com/gephi/gephi#nightly-builds
It uses a newer Netbeans RCP version.

**Comment by eduramiba** [comment]
Might be related to #1748

**Comment by mauriciogruppi** [comment]
I had the same issue running Gephi 0.9.1 on Windows 10 x64. I got it working after installing JDK 8 x64. Make sure you run the x64 gephi binary under <gephi location>/bin/gephi64.exe.
I was trying to execute it through the shortcut and it never worked because it pointed me to the gephi.exe file.

Good luck!

**Comment by eduramiba** [comment]
Closing old issue

**Comment by phyrwork** [comment]
Closed with no fix?

**Comment by eduramiba** [comment]
Reopening as it still happens to some people.

**Comment by gerardorosiles** [comment]
Having same issue. I tried different versions of JDK vi setting
jdkhome="C:\Program Files\Java\jdk1.8.0_141"

in conf file. Tried jdk version 141, 152 and 161 with no luck. I tried running elevated and it did not work.

**Comment by jsalbr** [comment]
Is there a solution to this issue or a workaround? I'm still facing the same issue on Windows 10 with jdk1.8.0_171. No errors in messages.log.

**Comment by nayomnik** [comment]
Most recently I have added to NetBeans j2me plugin , then after installation of related J2ME sdk it started stick on that forever "starting modules.." I simply uninstalled that j2me sdk outside and netbeans now starts ok again.

**Comment by mnemalur** [comment]
I used to run on Gephi 09.1 and things were all fine. I tried to upgrade to 0.92 and it shows this "Starting Modules forever.  I tried to search and change the JDK HOME path as suggested and still no luck. 
Is this bug still open?

**Comment by jsalbr** [comment]
Killing the process jogamp_exe_tst* brings up the main screen for me. See https://github.com/gephi/gephi/issues/1868

**Comment by nayomnik** [comment]
You should keep only one jdk version.You cannot track all path to right JDK variables inside the SDKs or outside it. Then the system will ask you to show path to right place.( I had such problem with other kind of SDK though.)

**Comment by mbastian** [comment]
Closing this old issue as the new releases (>= 0.9.3) embed the Java JRE by default, most likely resolving these kind of incompatibility issues. If it persists, please reopen. Thank you.
