### ISSUE TITLE
gephi 0.9.1 freezes for dynamical graphs

### ISSUE THREAD

**Issue by frbkrm** [gephi/gephi#1633]
Hi! 

No matter which machine I use, gephi freezes when I try to work with dynamical graph (e.g. running modularity, layout etc.). I read somewhere that gephi 0.9.1 does not support gexf 1.2. Is that true? If that is the case, I don't find a proper link to download gexf 1.3. It seems that gephi 0.9 for dynamical graphs are still very buggy and there are not enough documentations to get around this problem. 

Any help appreciated.

**Comment by eduramiba** [comment]
Hi,
It supports all versions of gexf, but it's true that there are some stability problems with dynamic graphs in Gephi 0.9.1.

You can try [0.9.2-SNAPSHOT nightly build](https://github.com/gephi/gephi#nightly-builds), it may work better.

Also, can you provide a file and steps to reproduce?

**Comment by frbkrm** [comment]
Here is the gexf file that I want to use in gephi:
[graph_w_time.gexf.zip](https://github.com/gephi/gephi/files/652258/graph_w_time.gexf.zip)

**Comment by eduramiba** [comment]
Hi,
I am able to load that graph and run Force Atlas 2 and the timeline at the same time in Gephi 0.9.1 (with updates installed).

Modularity also works.

**Comment by frbkrm** [comment]
could you also try noverlap and colour the nodes based on the modularity. That is usually where my gephi freezes.

**Comment by eduramiba** [comment]
Right, there seems to be a deadlock sometimes. We need to investigate the problem.

**Comment by eduramiba** [comment]
Please try again with [new 0.9.2-SNAPSHOT nightly build](https://github.com/gephi/gephi#nightly-builds) as soon as the [travis job](https://travis-ci.org/gephi/gephi/builds/184076693) ends

**Comment by eduramiba** [comment]
Did it work?

**Comment by frbkrm** [comment]
Sorry for late reply. 
I downloaded the latest nightly build gephi. Right now my problem is to run the gephi. When I run "$ ./bin/gephi --jdkhome /usr/lib/jvm/java-7-oracle" in the terminal, I get a lengthy java error and my knowledge is not enough to figure out the problem :S

**Comment by eduramiba** [comment]
Can you post the full error?

**Comment by frbkrm** [comment]
In my other linux machine where I haven't messed up the java, the gephi nightly build is working! I can now work with dynamical networks without it crashes or freezes. Great!
To run the gephi in terminal I write: $ LIBGL_ALWAYS_SOFTWARE=1 ./bin/gephi
Are the changes now implemented in the official release of the Gephi?

**Comment by eduramiba** [comment]
Yes, just install latest updates in your Gephi 0.9.1 (Help - Check for Updates)

**Comment by fabian-rudolf** [comment]
Gephi still appears to freeze in version 0.9.2 for dynamic graphs with timeset intervals, a calculated modularity and while running OpenOrd for example.
