### ISSUE TITLE
Can't access Update Center URL: Fatal alert received

### ISSUE THREAD

**Issue by bnj-cooley** [gephi/gephi#1635]
Each time I try to install a plugin I get the following error message:

Unable to connect to the Gephi Update Center because of Received fatal alert: close_notify

I have version 9.1 of Gephi installed and am running macOS 10.12.1. Why can't I connect to the Update Center URL?

**Comment by eduramiba** [comment]
Hi, is it possible that your network is behind a proxy or something? It seems to work fine at the moment.
What is the plugin you are trying to install?

**Comment by cooleyb** [comment]
No I don't think my network is behind a proxy. I'm trying to install
SigmaExporter (9.0) from the 'Available Plugins' section. I tried changing
my proxy settings, but not it's saying 'Networking problem in
https://raw.githubusercontent.com/gephi/gephi-plugins/gh-pages/plugins/0.9.1/sigmaexporter-0.9.0.nbm

**Comment by eduramiba** [comment]
I see, it seems your system is rejecting valid ssl certificates for some reason.
You can try to:

- Update java
- Make sure your system clock is correct
- Make sure nothing is interfering in your network

If it was windows, an antivirus or similar could be the problem too.

**Comment by eduramiba** [comment]
Closing old issue
