### ISSUE TITLE
Ranking operation not working (node color and size)

### ISSUE THREAD

**Issue by alexpGH** [gephi/gephi#1636]
Hi,
- open the file
- activate timeline
- select nodes color or size ranking
- select any attribute, e.g. seqAge
- hit apply or auto apply
-> all nodes have the same size / color

When using the same attribute in a partition appearance mode, it works.
I found that sometimes, when saving and reloading the file, the ranking is displayed correctly.
It seems to be working for non dynamic networks.

My setup (checked for updates today):
 Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_101; Java HotSpot(TM) 64-Bit Server VM 25.101-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_101-b13
System: Linux version 3.16.0-4-amd64 running on amd64; UTF-8; en_US (gephi)

[lineage_5_6_1.gephi.zip](https://github.com/gephi/gephi/files/660314/lineage_5_6_1.gephi.zip)

**Comment by eduramiba** [comment]
It's possible that an exception is happening. Can you try with latest 0.9.2 nightly build? https://github.com/gephi/gephi#nightly-builds
Related issue: https://github.com/gephi/gephi/issues/1633

This fix will be released soon as an update for 0.9.1

**Comment by alexpGH** [comment]
Tested the nightly build a moment ago: it does _not_ solve the problem.
For me, gephi does not freeze (as in the other issue). It's only that the sizes/colours due to ranking are set all the same. The rest is working fine.
Alex

**Comment by eduramiba** [comment]
Hi,
Can you detail the steps you follow and/or show an screenshot of how is your workspace set up please?

**Comment by alexpGH** [comment]
I described the steps in my first post (start gephi, open the file, apply a force layout to get the vertices aligned, then i apply a ranking operation).

For the following screenshot, I applied a ranking in nodesize for seqAge.
The green numbers show the seqAge (the is e.g. one node with age 6). However, all nodes have the same size (the largest value set in the ranking dialogue).

When using partition e.g. on colors the nodes get different colors as expected (screenshot2.png), but when using ranking for colors, the node color is the same for all nodes (screenshot3.png)



![snapshot1](https://cloud.githubusercontent.com/assets/22426715/21356760/0f09e1a6-c6d3-11e6-8a75-f95ff84bd388.png)
![snapshot2](https://cloud.githubusercontent.com/assets/22426715/21356899/8c742692-c6d3-11e6-87cf-c00edd2abb6e.png)
![snapshot3](https://cloud.githubusercontent.com/assets/22426715/21356909/94b62c10-c6d3-11e6-84ce-57c37c2d93d7.png)

**Comment by eduramiba** [comment]
Oh I see, the code for `refresh` at https://github.com/gephi/gephi/blob/86b1b57e8869ddee880a38c9071b68ea1f63d3b6/modules/AppearanceAPI/src/main/java/org/gephi/appearance/AttributeRankingImpl.java when column is not indexed is clearly incorrect. Thanks for the report!

**Comment by eduramiba** [comment]
Please try again with [new 0.9.2-SNAPSHOT nightly build](https://github.com/gephi/gephi#nightly-builds) as soon as the [travis job](https://travis-ci.org/gephi/gephi/builds/185558330) ends

**Comment by alexpGH** [comment]
It Works, thanks!
Is it itended that the edges change color too, when changigng node color via ranking? They seem to get the color of the outgoing node. Can I deactivate this?
Thanks!
Alexander

**Comment by eduramiba** [comment]
Yeah, check https://gephi.org/tutorials/gephi-tutorial-visualization.pdf
