### ISSUE TITLE
Files won't appear after updating Gephi

### ISSUE THREAD

**Issue by annasigler** [gephi/gephi#1637]
Uploading csv or even the example LesMiserables.gexf do not appear in Gephi. The panel on the right shows the number of nodes and edges so obviously the file has been uploaded but nothing appears on the main window - no nodes / edges / graph. This all happened after updating Gephi.

Anyone got any ideas?

Thanks!

**Comment by eduramiba** [comment]
Do you have graph window open? Try to click on Window - Reset Windows

**Comment by annasigler** [comment]
Thank you yes that's it! (Total novice here)

**Comment by eduramiba** [comment]
Cool :smile:
