### ISSUE TITLE
Program crash during manual color selection for nodes

### ISSUE THREAD

**Issue by amarradi** [gephi/gephi#1641]
Hello,

i tried to choose an color for my graph and the program crashed without error. Is there any logfile?

**Comment by eduramiba** [comment]
Yes please include the messages.log files at your user directory (see https://github.com/gephi/gephi/wiki/Troubleshooting).

Also, what were you trying to to? Apply a partition to nodes?

**Comment by amarradi** [comment]
you can close this until i can reproduce this bug, because i have no message log. I only want to set a node with a color.

**Comment by eduramiba** [comment]
But what tool are you using in the program and how? (Appearance window, edit tool, ...)
