### ISSUE TITLE
Presets not working

### ISSUE THREAD

**Issue by FeralWhippet** [gephi/gephi#1643]
Version 0.9.1
Windows 10
Java 8

When I save a preset, quit, restart and reload the workspace I do not see the saved preset. A preset file is created in config/previewpresets but is empty (0 bytes).

Sometimes on attempting to save a preset for the first time it uses the name of the current default selected and sometimes it asks for a new name.

I do see that this kind of thing has been reported in the past but the issues were closed, so am recreating the issue.

**Comment by eduramiba** [comment]
Confirmed, this is not working well. Thanks for the report!

**Comment by eduramiba** [comment]
Fixed in commit 4a5ae9d81e500ac8b85339b4778ad48560387fd8
