### ISSUE TITLE
Edge attributes not imported (or not shown) after DOT import

### ISSUE THREAD

**Issue by samhatchett** [gephi/gephi#1644]
When importing a dotfile, the edge attributes do not appear in the "Laboratory" table, nor are they accessible in the "Appearance" panel. However, the edges do appear colored appropriately (as declared in the dotfile). 

So even thought the colors are correct, there is no way to modify the colors manually, either by editing the table, or by selecting the edge (which does not seem possible to do).

**Comment by samhatchett** [comment]
In case it's helpful, the practical result is that I can't accomplish what I want to do: namely, select certain edges based on properties expressed as attributes, and modify or remove just those edges. If there is another way to accomplish this, then I'd be grateful to learn.

**Comment by eduramiba** [comment]
Hi,
Can you provide a sample dot file with this problem?

Thanks

**Comment by samhatchett** [comment]
sure, see below: simple 3-node graph. 

the edges show up in the color specified (red, black, blue), but edge properties are not viewable/editable in the Laboratory or anywhere else.

thanks!

```
graph G {
	0[label="1", elevation="524.696", measured="false"];
	1[label="11", elevation="603.338", measured="false"];
	2[label="2", elevation="524.696", measured="false"];
	0--1 [label="10", diameter="8", measured="false", color="red"];
	1--2 [label="11", diameter="8", measured="false", color="blue"];
	0--2 [label="12", diameter="8", measured="false", color="black"];
}
```

**Comment by eduramiba** [comment]
@samhatchett Thanks

**Comment by FishOfPrey** [comment]
Just ran across this. I guess the short term answer is to switch to a different [graph format](https://gephi.org/users/supported-graph-formats/) where Gephi supports attributes on edges.

I'm trying GEXF, which seems to be more successful so far.

**Comment by mbastian** [comment]
This is fixed but due to some other error we had to change the edge parsing a bit. Edges like `0--1` won't work anymore. The spaces are necessary: `0 -- 1` works.
