### ISSUE TITLE
Marvel Gephi file link is broken

### ISSUE THREAD

**Issue by maynull** [gephi/gephi#1645]
I am looking for Marvel Social Networks dataset. However link given in here doesn't work : https://github.com/gephi/gephi/wiki/Datasets

I copied the part that I'm looking for:
[GEPHI file.](https://gephi.org/datasets/hero-social-network.gephi) The Marvel Social Network Networks of super heroes, constructed by Cesc Rosselló, Ricardo Alberich, and Joe Miro from the University of the Balearic Islands. Collected by Infochimps and transformed & enhanced by Kai Chang.

Thanks

**Comment by eduramiba** [comment]
Fixed, thanks for the report!
