### ISSUE TITLE
I open gephin, start a new project and I click on data lab but nothing opens.

### ISSUE THREAD

**Issue by ainemw** [gephi/gephi#1649]
## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Can you post an screenshot? Not sure what problem you are trying to describe.

Also please include your messages.log file.

**Comment by ainemw** [comment]
Thank you, I deleted the support script and now it works.

Best regards,
Áine
======================
Dr Áine Macken-Walsh | Sociologist | REDP, Teagasc | Áras uí Mhaoilíosa, Athenry, Co. Galway, Ireland  | Tel.: +353 91 845241 Mob.: +353 87 2480228

https://teagasc.ie/contact/staff-directory/aine-macken-walsh/

<http://www.teagasc.ie/rural-economy/staff/macken_walsh_a.asp>



________________________________

**Comment by Aluus** [comment]
I got the same problem. My os is win7 32bit with JDK 1.7.
When I try Gephi 0.82, after a 5k nodes table loaded, no preview was shown, then I tried 0.91, it even could not open after a few seconds startup interface.

**Comment by eduramiba** [comment]
Sometimes deleting your [user directory](https://github.com/gephi/gephi/wiki/Troubleshooting) helps with problems like this.

**Comment by Aluus** [comment]
thx a lot to eduramiba for replying. 
It's weird, that  Gephi 0.91 can both do the job with JDK 1.7 in win10 64bit , and with JDK1.8 in win7 32bit in the other desktop.
