### ISSUE TITLE
Node size by attribute not listing property

### ISSUE THREAD

**Issue by juanmas07** [gephi/gephi#1650]
<img width="262" alt="screen shot 2017-01-06 at 10 36 18 am" src="https://cloud.githubusercontent.com/assets/2141907/21719341/ff02c512-d3fb-11e6-8a3b-9ba064ad470b.png">

I have several columns with type Integer and Float, but none of these is listed in the node size by attribute windows.

Gephi 0.9.1
macOS 10.11.6

**Comment by eduramiba** [comment]
Have you installed all available updates? (Help - Check for updates)

**Comment by CoKieKola** [comment]
Hi :)  I installed all available updates and am having the same issue

**Comment by eduramiba** [comment]
Can you share a sample dataset with this problem?

**Comment by eduramiba** [comment]
Related thread in Facebook group. I think it's the same issue: https://www.facebook.com/groups/gephi/permalink/10155450561337565/

**Comment by eduramiba** [comment]
Fixed for 0.9.2
