### ISSUE TITLE
Add dynamic edge attribute (weight),using csv file

### ISSUE THREAD

**Issue by ricoi** [gephi/gephi#1653]
Hello,

I'm having problems to add a dynamic edge attribute, using a cvs file.
When I put the dynamic weight the gephi doesn't recognize it (e.g. <[2010.0, 5]; [2011.0, 1]; [2012.0, 8]> ..etc...)
With timestamp row, it only recognizes when I use like this: <[2010.0, 2011.0, 2012.0]>
Some one could help me to put a dynamic weight using a csv file?

**Comment by eduramiba** [comment]
Hi, before importing make sure that your project uses timestamp time representation in the configuration dialog in data laboratory.

**Comment by ricoi** [comment]
Yes, it uses timestamp

**Comment by eduramiba** [comment]
I see, that's strange as the second notation is for intervals and the first one for timestamps. In the second step of the wizard what's the reported type of the weight column?

**Comment by ricoi** [comment]
When I put the row title "Weight", it self fixed the type as Double, and the values change.
When I put another title, I select TimestampIntegerMap

**Comment by eduramiba** [comment]
Oh, I think you might need to convert the weight column first to a dynamic type. So all the steps are:

1. Create project
2. Configure Time Representation = Timestamp
3. In data laboratory, click on "Convert column to dynamic", select Weight, check the "Replace column" option and accept
4. Then, import your spreadsheet

In the future this might be easier when issue #1282 is finished

**Comment by ricoi** [comment]
Ok, thank you for support. 
What value should I use when "Convert column to dynamic"?
I first try "0", then "infinity", in both cases I imported the spreadsheet with row (<[2010.0, 5]; [2011.0, 1]; [2012.0, 8]> ) named "Weight", the type was self attributed as "Timestampdoublemap". The values appear ok, but statiscs don't reconigzed the weigh, so when I calculate e.g. Weight av degree, the values were zero.

**Comment by eduramiba** [comment]
The value is only used when converting existing rows, so no effect on an empty graph.

The Average weighted degree does not support dynamic weights at the moment (it actually causes an exception). Maybe one of the statistics labeled as dynamic is useful.

**Comment by ricoi** [comment]
Ok, Thank you!

**Comment by eduramiba** [comment]
Closing as fixed with #1282 which now should directly support dynamic weights.
