### ISSUE TITLE
importing from database, i want store in database, how to store in database, 

### ISSUE THREAD

**Issue by pradeepkum** [gephi/gephi#1654]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
Gephi works in memory always, it's not intented to be used as a database. You can export parts of your graph database and visualize it with Gephi (for example, using gml format when exporting from Neo4j).
