### ISSUE TITLE
GraphML Importer Attribute Loading Problem

### ISSUE THREAD

**Issue by bassman99** [gephi/gephi#1656]
## Expected Behavior
Ability to handle <data key="labels">value</data> entries in GraphML file, as documented at [https://gephi.org/users/supported-graph-formats/graphml-format/](https://gephi.org/users/supported-graph-formats/graphml-format/)

## Current Behavior
Only handles attributes as described in this forum link: [http://forum-gephi.org/viewtopic.php?f=29&t=5878&p=13712&hilit=graphml#p13712](http://forum-gephi.org/viewtopic.php?f=29&t=5878&p=13712&hilit=graphml#p13712)

## Possible Solution
Deferred to developers...

Greatly increases usefulness of Gephi to entire Neo4j community, which is limited by the availability of free visualization tools.

## Steps to Reproduce

1. Generate GraphML from Neo4j APOC, which results in GraphML format consistent with expected behavior above.
2. Open in Gephi; no attributes!

## Context

Frantically trying to find free visualization tools for use with Neo4j.  This issue is a showstopper (not being a good enough programmer these days to write my own GraphML generator from Neo4j).

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

N/A - Any GraphML file with <data key="labels">value</data> should do fine to reproduce the error.

**Comment by bassman99** [comment]
Here's a sample GraphML file that demonstrates the problem.  Nodes/relationships are loaded fine, but no attributes.
[GraphML.txt](https://github.com/gephi/gephi/files/724343/GraphML.txt)

**Comment by bassman99** [comment]
Of course, please rename "GraphML.txt" to "GraphML.graphml" for loading.  I had to change the file extension so I could upload it.

**Comment by eduramiba** [comment]
Notes: we might assume String type for undeclared attributes, since Neo4j APOC does this, but I am not sure that's valid GraphML according to http://graphml.graphdrawing.org/specification/primer/graphml-primer.html

**Comment by eduramiba** [comment]
Original topic: http://forum-gephi.org/viewtopic.php?f=29&t=5939

**Comment by bassman99** [comment]
The actual XML is getting beyond my expertise, but I posted over at the APOC site (portion of Neo4j that generates the GraphML); perhaps they will chime-in...  [https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/258](url)

**Comment by eduramiba** [comment]
Can you try if this was fixed as indicated in https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/258 please?

**Comment by eduramiba** [comment]
Did it work?

**Comment by bassman99** [comment]
My appologies.  I have abandoned Neo4j and Gephi right now, due to lack of time.
		

		Get Outlook for iOS
	





On Sat, Apr 15, 2017 at 11:04 AM -0400, "Eduardo Ramos" <notifications@github.com> wrote:












Did it work?

**Comment by phelps-sg** [comment]
I am still seeing this issue with APOC 3.1.3.7, despite [neo4j issue 258](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/258) being marked as closed.

**Comment by eduramiba** [comment]
Is it producing the correct output?

**Comment by phelps-sg** [comment]
I am not sure whether the output is correct according to the graphml standard, but Gephi 0.9.1. fails to recognise the node or edge attributes exported by APOC.  A snippet of an exported graph is shown below.  I don't know whether this is a bug in Gephi or a bug in APOC.

~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<node id="n0" labels=":Asset"><data key="labels">:Asset</data><data key="asset_id">Ua8oJEML7KXcvUTzL2g9WvJs9xyXTrj8YvJkzZ</data></node>
<node id="n1" labels=":Transaction"><data key="labels">:Transaction</data><data key="txid">74ac74b7b1fca6557cac3ce4d79a11f63c65d40f51eded347c0c43b532728cef</data></node>
<node id="n2" labels=":BTCAddress"><data key="labels">:BTCAddress</data><data key="hash">1DwmXwjNfFgdzA9yvwGPcu6kfv3znGBN7n</data></node>
<node id="n3" labels=":BTCAddress"><data key="labels">:BTCAddress</data><data key="hash">3KBSjKsSc4VKCfoWnj1fe8XHRhiG52gYZA</data></node>
<node id="n4" labels=":Transaction"><data key="labels">:Transaction</data><data key="txid">6489c12b5c90963cae7edaa0e91554fd29f2737d83d0af7e21732ad081d6481a</data></node>
~~~

**Comment by eduramiba** [comment]
It seems it's still note generating the key headers, that should look like:

```xml
<key id="labels" for="node" attr.name="labels" attr.type="string"/>
```

**Comment by snow-frog** [comment]
has there been any progress at all on this issue? Same problem

**Comment by eduramiba** [comment]
@snow-frog the issue is still open in neo4j https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/466
