### ISSUE TITLE
Automated export (calling scripting pluging from Bash)

### ISSUE THREAD

**Issue by julenl** [gephi/gephi#1657]
Is there a way to call gephi from the terminal (Bash), load a python script (scripting plugin) and exit?
I am trying to transform (export) a gexf file as png or Sigma.js.

**Comment by eduramiba** [comment]
Hi,
You will need to use the [gephi toolkit](https://gephi.org/toolkit) for this.

**Comment by julenl** [comment]
Thanks!
But I still cannot find anywhere how to actually call it (execute the script).
Something like this?
    
    ....gephi-0.9.1/bin/gephi gephi_script.sh

**Comment by eduramiba** [comment]
Sorry that's not possible, you will need some experience programming Java applications. An example: https://github.com/gephi/gephi/wiki/How-to-export-to-PDF-or-SVG

**Comment by julenl** [comment]
Sorry, I was not clear.
I mean, how can I actually run those scripts with gephi, or which executable will take the files containing those (java) scripts.

**Comment by eduramiba** [comment]
Gephi will not execute the scripts, so you don't need the Gephi desktop application at all, instead it will work as a library (the toolkit) so you can integrate it in any Java application.

[Here](https://github.com/gephi/gephi-toolkit-demos) you have a complete application with several examples and a Main.java file which runs the examples.
