### ISSUE TITLE
Export data table with large numbers in metrics rows

### ISSUE THREAD

**Issue by ricoi** [gephi/gephi#1658]
When I export a node table from Gephi, after run every statistcs like page rank, eigenvector, betweenness, etc., the results with large numbers are shown as exponential expression e.g. "1.6772730069394457e-4". 
Is there any way to export the table with large numbers e.g "0.00016772730069394457" ?

* Using "UTF-16LE" encoding. 
 
* Version used: Gephi 0.9.1

**Comment by eduramiba** [comment]
Adding this to 0.9.2 milestone to make sure that numbers are formatted with a maximum number of decimals and with a single number format.
To be implemented with #1282

**Comment by eduramiba** [comment]
Can you please try the latest nightly build (https://github.com/gephi/gephi#nightly-builds)? It should include these changes
