### ISSUE TITLE
Gephi is drawn outside the display

### ISSUE THREAD

**Issue by jamestripp** [gephi/gephi#1660]
## Expected Behavior
When run Gephi should be displayed on within the monitor display area.
## Current Behavior
~30% of the time the Gephi window is drawn in an area left of monitor display. The program icon is displayed in the taskbar but I unable to see the main window. Clicking on the program icon displays the maximisation window but the window moves to the of of the display. Gephi is displayed offscreen.

I have yet to find the exact cause or conditions for replication.
## Possible Solution
Restart Gephi multiple times.

## Steps to Reproduce

1. Start Gephi
2. After splash screen is displayed the window is drawn offscreen.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by peterch405** [comment]
I don't know much about gephi, but this sounds like you might have dual screen set up. Check your display settings in windows?

**Comment by jamestripp** [comment]
Thanks for getting back to me.

I have a single screen setup. I checked this with enabling a two screen setup and with a single screen setup. Unfortunately, the issue continues to occur.

**Comment by mbastian** [comment]
Closing old issue as we can't replicate. Since 0.9.3 version we made some improvements in this domain, please try the new version and reopen if it persists.
