### ISSUE TITLE
DNA - import .CSV (from DNA software) in GEPHI

### ISSUE THREAD

**Issue by geeklight01** [gephi/gephi#1661]
Hello I am a new Gephi user. 
I am trying to import a .CSV file in Gephi and it does not work. This .CSV file was obtained after an exportation of a network I created with the Discourse Network Analyzer from Leifeld. No network appears in Gephi after I uploaded this .CSV file  and I don't understand why. 
Could it be possible that I already did something wrong while exporting? Or that I still have to work on my .CSV before trying to import it in Gephi?
(I am working on Mac)

* Version used: Gephi 0.9.1

**Comment by eduramiba** [comment]
Hi,
What does the CSV look like? Can you share a sample of the file?

**Comment by geeklight01** [comment]
Hi, That's an adjacency matrix. Here' the file : https://www.dropbox.com/s/zlrgocu0xi8vvv1/myfile_gephi.csv?dl=0
thanks for your time!

**Comment by eduramiba** [comment]
The file seems to be incorrectly parsed (maybe due to spaces). This should be fixed in 0.9.2 once we implement #1282 and #1662

**Comment by geeklight01** [comment]
Do you already know when it will be implemented? Does that mean that I cannot do anything to fix it meanwhile? Thank you so much for your help!!

**Comment by eduramiba** [comment]
I just tested and it works correctly in my branch (work in progress) for #1282 

I expect to merge it into Gephi master soon (1-2 weeks). Then you will be able to use it by downloading the 0.9.2-SNAPSHOT nigthly build before it's released.
Otherwise you can only test it at the moment by building [my branch](https://github.com/eduramiba/gephi/tree/spreadsheet-migrate)

**Comment by geeklight01** [comment]
Was it already implemented? Can I already download the 0.9.2-SNAPSHOT nigthly build?
I tried to import this file in gephi: https://www.dropbox.com/s/xuv1yu449btgpu0/test.csv?dl=0
I got a message saying that the importation is successful but no network is displayed. I don't understand why. Could you please help me?

**Comment by eduramiba** [comment]
Hi,
No this is not available yet in snapshot. It will be merged soon.

**Comment by eduramiba** [comment]
Can you please try the latest nightly build (https://github.com/gephi/gephi#nightly-builds)? It should include these changes
