### ISSUE TITLE
Gephi freezing during "Starting modules..."

### ISSUE THREAD

**Issue by syoshio** [gephi/gephi#1663]
## Expected Behavior
Gephi working well
## Current Behavior
Gephi freezes  "Starting modules..."

## Your Environment
Windows 10
Java Version 8 Update 121 (Build 1.8.0_121-b13)

* Version used: Gephi 0.9.1
* Operating System: Windows 1

**Comment by eduramiba** [comment]
Hi,
Can you attach your `messages.log` file please? Located in user directory: https://github.com/gephi/gephi/wiki/Troubleshooting

Also try to update your graphic card drivers.

**Comment by syoshio** [comment]
Thanks eduramiba, I changed jdkhome path and worked !

**Comment by GabrielFerrari** [comment]
Any solution on this question? I have the same situation.
