### ISSUE TITLE
Modules starting.... not.

### ISSUE THREAD

**Issue by arnoutponsioen** [gephi/gephi#1664]
## Expected Behavior
Gephi just starts up fine
## Current Behavior
It seems to 'hang' on 'modules starting up' while showing flash-image during startup process.
Last friday no problems with Gephi. During weekend not used the PC. So I am confused about this problem. I Just updated Java, removed Gephi and reinstalled Gephi manually. But the same problem continues... Gephi won't start up.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
Try to remove your Gephi user directory (check https://github.com/gephi/gephi/wiki/Troubleshooting).
Also please include your messages.log.

**Comment by arnoutponsioen** [comment]
Hi Eduardo.
I removed the user directory and reinstalled, but still the same problem.

Log:

-------------------------------------------------------------------------------
>Log Session: Monday, February 6, 2017 10:21:44 AM CET
>System Info: 
  Product Version         = Gephi 0.9.1 201510222201
  Operating System        = Windows 8.1 version 6.3 running on amd64
  Java; VM; Vendor        = 1.7.0_79; Java HotSpot(TM) 64-Bit Server VM 24.79-b02; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.7.0_79-b15
  Java Home               = C:\Program Files\Java\jdk1.7.0_79\jre
  System Locale; Encoding = nl_NL (gephi); Cp1252
  Home Directory          = C:\Users\Arnout
  Current Directory       = C:\Program Files (x86)\Gephi-0.9.1
  User Directory          = C:\Users\Arnout\AppData\Roaming\.gephi\0.9.1\dev
  Cache Directory         = C:\Users\Arnout\AppData\Roaming\.gephi\0.9.1\dev\var\cache
  Installation            = C:\Program Files (x86)\Gephi-0.9.1\platform
                            C:\Program Files (x86)\Gephi-0.9.1\gephi
                            C:\Program Files (x86)\Gephi-0.9.1\platform
  Boot & Ext. Classpath   = C:\Program Files\Java\jdk1.7.0_79\jre\lib\resources.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\rt.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jce.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.7.0_79\jre\classes;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.7.0_79\jre\lib\ext\zipfs.jar
  Application Classpath   = C:\Program Files (x86)\Gephi-0.9.1\platform\lib\boot.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-modules.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util-lookup.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util-ui.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\org-openide-util.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\boot_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-modules_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util-ui_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\lib\locale\org-openide-util_zh_TW.jar;C:\Program Files\Java\jdk1.7.0_79\lib\dt.jar;C:\Program Files\Java\jdk1.7.0_79\lib\tools.jar
  Startup Classpath       = C:\Program Files (x86)\Gephi-0.9.1\platform\core\asm-all-5.0.1.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\core-base.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\core.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-netbeans-libs-asm.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-openide-filesystems-compat8.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\org-openide-filesystems.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core-base_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\core_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-netbeans-libs-asm_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems-compat8_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ar_SA.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_bg.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ca.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_cs.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_de.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_es.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_fr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_gl_ES.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_in_ID.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_it.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ja.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ko.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_nl_NL.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pl.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pt_BR.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_pt_PT.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ro.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_ru.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_si.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_sq.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_sv.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_tr.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_zh_CN.jar;C:\Program Files (x86)\Gephi-0.9.1\platform\core\locale\org-openide-filesystems_zh_TW.jar;C:\Program Files (x86)\Gephi-0.9.1\gephi\core\locale\core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.JarClassLoader]: Opening C:\Program Files (x86)\Gephi-0.9.1\gephi\modules\ext\org.gephi.graph-api\it-unimi-dsi\fastutil.jar took 1.390 ms
WARNING [org.netbeans.JarClassLoader]: Opening C:\Program Files (x86)\Gephi-0.9.1\gephi\modules\ext\org.gephi.db-drivers\org-postgresql\postgresql.jar took 1.203 ms
WARNING [org.netbeans.JarClassLoader]: Opening C:\Program Files (x86)\Gephi-0.9.1\gephi\modules\ext\org.gephi.db-drivers\mysql\mysql-connector-java.jar took 594 ms
WARNING [org.netbeans.JarClassLoader]: Opening C:\Program Files (x86)\Gephi-0.9.1\gephi\modules\ext\org.gephi.core-library-wrapper\jfree\jcommon.jar took 563 ms
WARNING [org.netbeans.JarClassLoader]: Opening C:\Program Files (x86)\Gephi-0.9.1\gephi\modules\ext\org.gephi.visualization\org-jogamp-gluegen\gluegen-rt-natives-windows-i586.jar took 1.625 ms

**Comment by arnoutponsioen** [comment]
Acutally, I run windows 10. In the log Windows 8.1 is mentioned?

**Comment by eduramiba** [comment]
That's strange. It should work but you can try to update to Java 8 and run Gephi as admin or maybe install it in a folder different than program files.

**Comment by arnoutponsioen** [comment]
Dear Eduardo

I decided to remove Java en Gephi completely and reinstall Gephi in different folder. It now seems works fine again (pfew...) but unfortunately no insight in the reason why it stoped working.

Thanks for your time though!!
