### ISSUE TITLE
Circle layout

### ISSUE THREAD

**Issue by ZeweiSong** [gephi/gephi#1665]
## Expected Behavior
I would like to have a new circle layout that position all nodes in a circle.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi, a plugin already exists for this: https://gephi.org/plugins/#/plugin/circularlayout You can install it easily in `Tools - Plugins` menu inside Gephi.
Does it work for your needs?

**Comment by ZeweiSong** [comment]
Yes, just found out about plugins, thanks!


Zewei


--
Zewei Song
Postdoctoral Associate
University of Minnesota, Twin Cities
Department of Plant Pathology

Email: songzewei@outlook.com
Tel: 612-840-0267
Website: www.songzewei.org
________________________________

**Comment by eduramiba** [comment]
Cool, closing
