### ISSUE TITLE
Gephi worked after fixing the "LIBGL_ALWAYS_SOFTWARE=1" bug, but not anymore.

### ISSUE THREAD

**Issue by JorgeRuizBerlin** [gephi/gephi#1666]
Hi everybody,

after many tries deleting and reinstalling Java, I followed then the instructions in [this thread](https://github.com/gephi/gephi/issues/1192), I solved the crash and Gephi worked for a while. I even opened "Les Miserables" example and saw the graph. But now it doesn't show the graph in Overview, neither in Preview. In Data Laboratory everything seems to be fine. 

What could be wrong? Where can I look at the problem?

Many thanks in advance for your help,
Jorge

* Version used: Gephi 0.9.1
* Operating System: Ubuntu 16.04 LTS

**Comment by eduramiba** [comment]
Try to reset windows (menu Window - Reset windows).
If that does not work, try to remove the whole user directory (check https://github.com/gephi/gephi/wiki/Troubleshooting)

**Comment by JorgeRuizBerlin** [comment]
Thank you, it works now! I thought it was something more complicated because I even restarted the computer.
