### ISSUE TITLE
CSV export of double/float produces wrong values

### ISSUE THREAD

**Issue by exercitussolus** [gephi/gephi#1667]
## Expected Behavior
When opening a CSV file in MS Excel, double/float values are identical to the ones shown in Gephi
## Current Behavior
Values shown in MS Excel are wrong
## Steps to Reproduce

1.
2.
3.
4.

## Context
We compute Pagerank on a graph, which results in a value V for every vertex, with 0 < v < 1, e.g. 0.0005233072. When exporting this to CSV and then opening in MS Excel, the value shows up as 52.33072. Checked the CSV file in a text editor, wrong value is already there, so a Gephi problem.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:
Mac OS

**Comment by eduramiba** [comment]
Hi,
What's the value on the data laboratory table? What kind of CSV export are you using?

**Comment by eduramiba** [comment]
Closing old issue. CSV export has been completely re-done.
