### ISSUE TITLE
StackOverflowError while using GraphStream

### ISSUE THREAD

**Issue by dennwc** [gephi/gephi#1668]
## Expected Behavior

GraphStream runs until server closes connection. All nodes and edges are visible.

## Current Behavior

Stream runs perfectly for few minutes and then `StackOverflowError` is thrown and stream stops. Nodes are loaded only partially.

## Steps to Reproduce

1. Download and unpack [this dataset](https://drive.google.com/open?id=0B_Wk8zx8wZr9N2xPczNZRU92TEU)  (90MB uncompressed).
2. Run `python -m SimpleHTTPServer` in the same directory.
3. Connect to a GraphStream at http://localhost:8000/graphStream.json
4. Exception is thrown at ~182239 nodes and 202202 edges.

## Your Environment

* Version used: Gephi 0.9.1, 0.9.2
* JRE: Oracle Java 8
* Operating System: Ubuntu Linux 16.10

Gephi log: https://gist.github.com/dennwc/56a421ce0f79dc1d2aa01728e67228b8

**Comment by eduramiba** [comment]
Thanks for the detailed report! We will check this as soon as possible.

**Comment by eduramiba** [comment]
This plugin just logs too much info, and the Netbeans RCP IO can't handle it. I think we will remove the logging in this plugin.

**Comment by eduramiba** [comment]
A condition can also be added to avoid this edge case of infinite recursion. But removing the streaming logging will probably improve performance.

**Comment by dennwc** [comment]
@eduramiba Yes I think, it would be better to omit this info from logs. Stream can be quite long in our case.

**Comment by eduramiba** [comment]
Hi,
I uploaded a new version of this plugin 😃 Can you test it please?

**Comment by dennwc** [comment]
@eduramiba Sure! Is it in development branch? Or in official repository for v0.9.1?

**Comment by eduramiba** [comment]
Already deployed for 0.9.1, so just open Gephi and check for updates.

**Comment by dennwc** [comment]
So far so good. Thanks for fixing this :)
