### ISSUE TITLE
biparti graph in gephi

### ISSUE THREAD

**Issue by chezsick** [gephi/gephi#1669]
biparti graph is compose two nodes A B table and one edges, the nodes table behave as a magnet than A never linked to A and B to B, biparti is an missing feature in gephi but not in the web if you searched, so is possible to add feature?

**Comment by eduramiba** [comment]
Hi,
This might help you https://seinecle.github.io/gephi-tutorials/generated-html/k-partite-bi-partite-graph-en.html

**Comment by eduramiba** [comment]
Did it help?

**Comment by chezsick** [comment]
hi ramos, yes but i not use the plugin for the moment, but one day
