### ISSUE TITLE
Frequent crashes with Gephi 0.9.1 on macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by isokrates** [gephi/gephi#1670]
## Expected Behaviour

Not crashing!

## Current Behaviour

Since updating to 0.9.1, Gephi has crashed a lot more when I visualise ForceAtlas2 graphs.

## Steps to Reproduce

Gephi crashes much more than it used to, and at different times. It's not consistent, but recently, the following has caused crashes quite a lot:
1. Generate ForceAtlas2 graph
2. Enable timeline mode
3. Try to change the period

This sometimes causes a crash straight away, and sometimes a little later, when I open QuickTime and try to record. Other times, Gephi crashes when I switch between Overview and Preview mode, or even when I switch from Gephi to Finder and back again. As I say, it happens quite a lot and for different reasons :(

## Context

I'm trying to create a screen recording of the evolution of a ForceAtlas 2 network graph. I have previously accomplished this by using QuickTime to record the screen, then enabling timeline mode in Gephi and dragging it across. This does still work sometimes, but it crashes a *lot* more frequently than it used to.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: macOS Sierra 10.12.3

Apple crash report: https://www.dropbox.com/scl/fi/kjh42lpgha41xhfflmeru/crash.txt?dl=0
Gephi messages.log: https://www.dropbox.com/scl/fi/53s4q9j9x6cejmo605h2g/messages.log

**Comment by eduramiba** [comment]
Hi, this might be a graphic card driver crash in JOGL.

Please try to:
- Make sure your drivers are up to date
- Java is up to date
- Gephi is up to date
- Switch to a secondary graphic card if available (or software rendering)

It's also true that Gephi 0.9.1 has some stability issues (much less if you install latest updates) that we need to improve for future releases. But they only cause exceptions, and not native crashes, which makes the opengl crash more probable.

**Comment by isokrates** [comment]
Sorry for the slow reply, and thanks very much for the troubleshooting steps. It has been OK for the past couple of days, but I'll let you know if it happens again!

**Comment by eduramiba** [comment]
Awesome!

**Comment by isokrates** [comment]
Hi!

I'm afraid the same issue keeps coming back :(

Here's a link to the crash log generated by macOS: https://www.dropbox.com/scl/fi/clwowtheaqw5m7bt3xxxf/gephi_crash.txt?dl=0

It seems to happen when I enable timeline mode, and switch back and forth between preview and overview mode. For instance, if I enable timeline mode, see a preview (and take a screenshot), switch back to overview, change the timeline period, switch back to preview (and take a screenshot), switch back to overview, and change the timeline period, it will almost always crash (sometimes I have to do this a couple of times, but it always seems to end up crashing).

I followed all the steps you gave me above... do you have any other ideas?

Thanks!

**Comment by ByronJames** [comment]
Gephi 0.9.2 here, on a Macbook Pro 13 - all systems up to date (yes, java too) and yes, crashing all the time. Often after switching views or applying filters or adjusting parameters - it's very touchy.
