### ISSUE TITLE
icon pencil for "creating node" and "creating edge" should not be the same?

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#1672]
Suggestion for UI improvment: to have different icons for these two "pencils". At the moment they are the same.

**Comment by jhhb** [comment]
I'd be interested in doing this. Is there a source for the icons Gephi uses? Are they all custom-made?

**Comment by eduramiba** [comment]
We mainly use the fugue icons package.

**Comment by jhhb** [comment]
Ok, great. I'm new to this and know it's a small change but I'd like to try to figure it out this weekend. Thanks!
