### ISSUE TITLE
Graph visualization is not working using Windows 10 / JDK 1.8.0_102

### ISSUE THREAD

**Issue by sastafford** [gephi/gephi#1673]
## Expected Behavior
* Import the Les Miserables graph file or any graphml file
* View graph in workspace

## Current Behavior
* Graph is not being visualized in workspace

## Possible Solution

Verified that graph is see on Windows 7 using same version of Gephi

## Steps to Reproduce

1.
2.
3.
4.

## Context

Verified that data is imported successfully but graph does not show

## Your Environment

* Product Version: Gephi 0.9.1 201510222201
* Java: 1.8.0_102; Java HotSpot(TM) 64-Bit Server VM 25.102-b14
* Runtime: Java(TM) SE Runtime Environment 1.8.0_102-b14
* System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (gephi)
* User directory: C:\Users\username\AppData\Roaming\.gephi\0.9.1\dev
* Cache directory: C:\Users\username\AppData\Roaming\.gephi\0.9.1\dev\var\cache

**Comment by sastafford** [comment]
Some additional log data
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
WARNING [java.util.prefs]: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by eduramiba** [comment]
Hi,
Please try to update your graphic card drivers and Java. Also maybe try to install Gephi outside of program files directory.

**Comment by eduramiba** [comment]
Closing old issue
