### ISSUE TITLE
Question about colouring edges

### ISSUE THREAD

**Issue by lmsimp** [gephi/gephi#1675]
I am new to using Gephi and in addition to sizing the edges of my network based on weight, I'd like to **colour** the edges according to whether an interaction (row item) is a positive or negative interaction.

I have seen on this [cheat sheet](http://www.clementlevallois.net/gephi/tuto/en/gephi_cheat%20sheets_en.pdf) that extra columns can be added to the edge view data table besides id, label, type and weight. 

If I add this information as an extra column in the edge view data table is it then possible to visualise these positive and negative interactions by edge colour in my network?

**Comment by eduramiba** [comment]
Yes it should be possible to use any custom column to color edges.

**Comment by lmsimp** [comment]
Great. How can this be done? Can you point me towards or provide an example? Many thanks.

**Comment by eduramiba** [comment]
You can use any of these formats https://gephi.org/users/supported-graph-formats
Spreadsheet is probably the easiest

**Comment by khasheee** [comment]
While adding custom column in Edge list to color edges as positive or negative, Is there any specificity for column name or values ?
