### ISSUE TITLE
Calculating degree

### ISSUE THREAD

**Issue by lilatsopelakou** [gephi/gephi#1676]
I have this xlsx file which i have conveted into a csv file and i have deleted the first column. I insert it into Gephi and I am running the average degree. But at the data table the degree that it shows for every row  it is wrong. I am thinking that it might be a problem with the data I am inserting.

* Version used: Gephi 0.9.1
* Operating System: Windows 10

[unweighted.xlsx](https://github.com/gephi/gephi/files/790608/unweighted.xlsx)

**Comment by eduramiba** [comment]
Well the headers seem to have dots in their names, and the rows have spaces, so they won't match correctly. What does your CSV look like?

**Comment by lilatsopelakou** [comment]
My csv looks like this I changed the dots into _ but I have the same problem. My output in gephi looks like this. 
![default](https://cloud.githubusercontent.com/assets/22682083/23204527/9d09ada8-f8ef-11e6-8a25-b772a2926272.PNG)


[unweighted1 .xlsx](https://github.com/gephi/gephi/files/792764/unweighted1.xlsx)

**Comment by eduramiba** [comment]
Hi,
It seems you are missing the labels in the left vertical column, you only have the horizontal labels.

**Comment by lilatsopelakou** [comment]
[unweighted 4.xlsx](https://github.com/gephi/gephi/files/792987/unweighted.4.xlsx
Hi, 
Something like this? If I do that Ι get an error.
![1](https://cloud.githubusercontent.com/assets/22682083/23207338/a51d7010-f8f9-11e6-832e-53bbbf3b5acd.PNG)
Thank you so much for your help!!!

**Comment by lilatsopelakou** [comment]
![2](https://cloud.githubusercontent.com/assets/22682083/23208709/b41689da-f8fe-11e6-89f7-0d61334a143d.PNG)

**Comment by eduramiba** [comment]
Hi,
This kind of file is imported with File - Open at the moment, not the spreadsheet import (they will be integrated in a future version)

**Comment by lilatsopelakou** [comment]
Hi, 
With File- Open I get this
![3](https://cloud.githubusercontent.com/assets/22682083/23208864/5ea6d42c-f8ff-11e6-97f6-cf16482a5a97.PNG)

**Comment by eduramiba** [comment]
Does the memory increase button work? Otherwise you need to manually increase it in gephi.conf file under etc folder of Gephi installation directory

**Comment by lilatsopelakou** [comment]
The button is not working I did it manually but i have another error it says that the id can not be empty

**Comment by lilatsopelakou** [comment]
Thank you so much for your help and you support I found it

**Comment by eduramiba** [comment]
Great! In 0.9.2 the GUI and error messages will be more user-friendly
