### ISSUE TITLE
Program keeps crashing and not reading in files correctly

### ISSUE THREAD

**Issue by xhan85** [gephi/gephi#1678]
## Expected Behavior
1. When I import a CSV file of nodes and edges, I should be able to see that the entire file loaded into Gephi.

2. I should see my nodes and edges in the data laboratory.

3. Program froze when I tried to pick a node attribute.
## Current Behavior
1. Under my edges--sometimes it loads 500+ roles (I have 3300+) and then it will load the rest (when I start a new workspace), and some other times it will load all of it but there's no rhyme or reason how many rows it loads. I've restarted my computer--same thing. I can never get all of my data to load in. I've been using Gephi for a long time and all of a sudden it just started doing this so I am not sure why this is happening. I also uninstalled and reinstalled Gephi--same problems.

2. Data Laboratory just never showed up. I ended up uninstalling and reinstalling--it now shows up but before, it just stopped showing up.

3. This was the last thing that happened before I started typing this--there is just something very wrong with the program right now. It's one thing or another and there's no real reason for any of the issues it's suddenly encountering. I have no idea if what I am seeing is actually what I have data for at this point because I don't know if something just stopped working.

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by eduramiba** [comment]
HI,
Can you please try with latest 0.9.2 snapshot (pre-release)? Many stability issues have been fixed. https://github.com/gephi/gephi#nightly-builds Please report any problems.

**Comment by eduramiba** [comment]
Did it work?

**Comment by xhan85** [comment]
It did, thanks!

**Comment by eduramiba** [comment]
Great!
