### ISSUE TITLE
Defaulting to string when importing CSV

### ISSUE THREAD

**Issue by moldham74** [gephi/gephi#1679]
## Expected Behavior

I am hoping this file (in CSV form) would load easily and form a weighted network. Yes it will be fully connected network

## Current Behavior
In the import wizard Gephi it sets the columns as string type. I believe I need to change this to double if I want a weighted network. Surely I do not need to do that for 479 columns as it is a very slow process

While the nodes current load there are no links.

## Possible Solution
Anything helpful would be great

## Context

I can not visualize the network or use Gephi as I would like.

## Your Environment

* Version used: Gephi 0.9.1
[gephihelp.xlsx](https://github.com/gephi/gephi/files/798187/gephihelp.xlsx)

* Operating System:
Mac OS EL Capitan Version 10.11.6

**Comment by eduramiba** [comment]
Hi, this is included in https://github.com/gephi/gephi/issues/532 (already in progress)
