### ISSUE TITLE
No arrows on curve edges, labels collapse when edges are straight

### ISSUE THREAD

**Issue by aramais** [gephi/gephi#1680]
## Problem 
When on preview when edges are rounded arrows are not shown. 

![1](https://cloud.githubusercontent.com/assets/4759508/23362247/f8d5d4ee-fd05-11e6-8e7c-1bbdeece10b9.png)

When I switch to straight edges, labels collapse because they are placed exactly on the center of the edge.  
![2017-02-27 15 57 00-d53rh](https://cloud.githubusercontent.com/assets/4759508/23362249/faa01ee2-fd05-11e6-9433-0b8bd3edbeb2.png)

More preferrably I would like to have arrows on rounded edges, but separating labels would be ok.
## Context
I want to have readeble graph 

## Your Environment
* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by Jeff250** [comment]
Hello aramais,

Sadly, I can't help you with this issue.. However I wanted to ask you how to display the edges weight in the preview mode please ? 
They are displayed for me when I work in the overview but not when I switch to preview mode... 

Thanks in advance

**Comment by aramais** [comment]
You have to check the "Show edge labels" box in "Edge labels preferences" section on the left of preview screen.

**Comment by Aleyasen** [comment]
+1
I have the same issue as @aramais .

**Comment by ryfia** [comment]
+1 I have the same issue.  MacOS, 0.91, clean install

**Comment by Mathildebd** [comment]
+1 I also have this issue with the missing arrows. I see the comments here are relatively new, so I fear this means there is no solution to this problem as it is...? Then I guess I have to switch from Gephi to an R function to produce my network layout, to have it ready for my publication in time.

**Comment by eduramiba** [comment]
@Mathildebd a workaround is export to SVG and fix It in inkscape

**Comment by Mathildebd** [comment]
@eduramiba Okay thanks for the tip! and fast reply! - I am working with it right now, and I see that Inkscape recognize the individual elements (layers). I am however not really familiar with InkScape, is there an easy way to do something like apply arrows to all lines or all elements or something like that? Or do I need to manually go throw them (That would not be so feasible, I might just stick to the linear layout then, but the other layout looks much nicer).

**Comment by eduramiba** [comment]
@Mathildebd well I was thinking about manually moving the labels so they don't overlap

**Comment by Mathildebd** [comment]
@eduramiba Oh okay, but that is not my problem, it is the arrow 'heads' which are missing on the edges when using the 'curved' layout, as described above.

**Comment by eduramiba** [comment]
@Mathildebd that's intended behavior though, the direction of the curves is always clockwise

**Comment by Mathildebd** [comment]
@eduramiba Yaay of cause, I never realized that! Well that is excellent, thank you for pointing that out! I will get right back to the curved layout then :)

**Comment by Zerbembasqwibo** [comment]
Curved lines has no arrows. Clockwise is direction. I found it here:

http://forum-gephi.org/viewtopic.php?f=31&t=1605

I would like to have possibility to have arrows also on curved lines.

**Comment by TheodorRene** [comment]
Is there still no possibility of getting arrows when using curved lines? Checking in since the issue is still open.

**Comment by jacomyma** [comment]
I have addressed this issue in branch u/jacomyma/github_1680 (review pending). Here is what it entailed:
* Rewrite edge drawing to replace Bézier curves by circle arcs
* Now the curved edges are truncated to be border-to-border for directed edges (same as straight edges)
* Now arrows are compatible with curved edges, but the default preset "curved edges" has arrows at 0 for consistency.
Note: none of this entails that displaying arrows with curved edges is a good idea in most situations.
