### ISSUE TITLE
How to use gephi tool for bi-partite graph 

### ISSUE THREAD

**Issue by geekyminhaj** [gephi/gephi#1681]
Is there any way to plot a bi-partite graph? I mean two different vertical lines instead of randomly placing nodes. I have only two type of nodes: domain and IP. I want to use the domain on left side and IP on right side.
Any help would be greatly appreciated.

below is the kind of view I want for my graph.
A   1
B   2
A   3
C   2
C   1

**Comment by seinecle** [comment]
Please ask this question on https://www.facebook.com/groups/gephi/

**Comment by geekyminhaj** [comment]
thanks. Now I have posted on fb page.

**Comment by eduramiba** [comment]
Cool, closing the issue here.
