### ISSUE TITLE
Failed to open download page

### ISSUE THREAD

**Issue by tongkewu** [gephi/gephi#1682]
I cannot open the download page on Mac OX. It says safari can't open the page "http://github-cloud.s3.amazonaws... because the server where the page is located isn't responding. 

What should I do to download Gephi 0.9.1?

**Comment by eduramiba** [comment]
Try https://github.com/gephi/gephi/releases/download/v0.9.1/gephi-0.9.1-macos.dmg if still not working please try again later, it might be a temporary github problem.

**Comment by tongkewu** [comment]
Thanks but still didn't work

**Comment by tongkewu** [comment]
Thanks a lot. It works now!
