### ISSUE TITLE
K-Core filter not working

### ISSUE THREAD

**Issue by melaniewalsh** [gephi/gephi#1685]
## Expected Behavior
The K-Core filter should show nodes with a degree of at least K.

## Current Behavior
When I plug "60" into the K-Core filter, all the nodes in my network disappear even though there are plenty of nodes with degrees above 60. Not sure what the problem is.

* Version used: Gephi 0.9.1

**Comment by peterch405** [comment]
I find that the degree range filter isn't working as I think it should. Unconnected nodes are not removed with degree 1. Also the attributes range filter never seems to finish the filtering so you are unable to export the filtered graph.

**Comment by eduramiba** [comment]
@melaniewalsh Can you provide a graph file to test this?

**Comment by phui** [comment]
Just came across this post from Google search.

K-core is a recursive process. At k=59, your nodes with degree 60 will have less degree because there are additional nodes filtered already. I believe that is why all the nodes disappear.

Correct me if I am wrong.

**Comment by nicky1038** [comment]
> K-core is a recursive process

It is. [k-core organization of complex networks](https://arxiv.org/pdf/cond-mat/0509102v3.pdf)

**Comment by mbastian** [comment]
Closing as k-core is working as expected.
