### ISSUE TITLE
exportFile Error while using gephi-toolkit-0.9.2-20170313.205649-134-all

### ISSUE THREAD

**Issue by Kalethars** [gephi/gephi#1689]
[error message.txt](https://github.com/gephi/gephi/files/840039/error.message.txt)
It's fine when I use gephi-toolkit-0.9.2-20161213.201328-46-all, I want to know what's the difference between these two versions. :) @eduramiba

**Comment by eduramiba** [comment]
Hi,
Can you share some code to reproduce this?

**Comment by eduramiba** [comment]
Did it work with recent version?

**Comment by eduramiba** [comment]
@Kalethars  This should now work with recent commits. Does it work with latest snapshot?

**Comment by eduramiba** [comment]
Closing old issue
