### ISSUE TITLE
node coloring/appearance with multiple attributes - feature request

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#1692]
https://www.facebook.com/photo.php?fbid=10155119106943749&set=gm.10155631762737565&type=3

## Expected Behavior

Bimodal network. Node coloring problem. The two modes are of different type.
1. I would like to color first type of nodes according to attribute x
2. I would like to color second type of nodes according attribute y

Like in this picture. big ones are different type as the smaller ones

## Current Behavior

one can color nodes only by onde attribute at time

## Possible Solution

Could one think of adding more coloring options in the appeareance? Like by having a column in Nodes data table that tells whic type of node it is,

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
A workaround is having in the same string column values like this:

```
x:val1
y:val1
x:val2
y:val2
```

**Comment by mihkal** [comment]
I do not understand how to do this

**Comment by eduramiba** [comment]
I mean you would store in a single column x values for nodes of type 1, and y values nodes of type 2. Also add the `x:` or `y:` prefix to avoid clashes with same values in different columns.
Of course this would be a manual process.

Then, just apply partition based on the single column.

**Comment by mihkal** [comment]
hmm. 10000 nodes. i'll test this

**Comment by eduramiba** [comment]
In fact you can create this column in data laboratory with Merge columns - Join with separator

**Comment by mihkal** [comment]
You missed the point. I need to color node type a according to different
metrics than node type b. Scale is not the same. Like consumers and products

pe 7. hei 2017 klo 23.05 Eduardo Ramos <notifications@github.com> kirjoitti:
