### ISSUE TITLE
Degree Range Settings jumping

### ISSUE THREAD

**Issue by datajournalist12** [gephi/gephi#1694]
The degree range setting (under topology) on 9.1 is jumping in multiples of three. For example, when I push the slider bar, it offers 1, 4, 7, 10, 13 etc. as degree ranges, but does not give the option to select anything between those values (2 or 3 would be my desired setting – just enough to filter out the noise without overdoing it).

Perhaps there is an easy fix, but I haven't spotted it yet. Oddly, this was never an issue until I upgraded to 9.1

**Comment by eduramiba** [comment]
Hi, you can double click on the number and edit it manually.

**Comment by eduramiba** [comment]
Recently improved with #1476
