### ISSUE TITLE
unable to import neo4j 3.1.1 database with gephi 0.8.2 beta

### ISSUE THREAD

**Issue by sushant7aug** [gephi/gephi#1695]
When importing neo4j database in gephi 0.8.2 beta it giving warning with empty message

Current Environment

* Version used: Gephi 0.8.2 beta
* Neo4j: 3.1.1
* Operating System: Windows 7 professional
* JDK:jdk1.7_55

**Comment by eduramiba** [comment]
Hi,
The Neo4j plugin supports up to version 2.1.3 and it can't be updated as is for Gephi 0.9.1, so maybe it could be updated, but only for 0.8.2

I advice you use the Neo4j APOC to export to graphml and load in any Gephi version as explained in https://neo4j.com/blog/apoc-database-integration-import-export-cypher
