### ISSUE TITLE
Gephi 0.9.1, Yifan Hu Multilevel layout not found.

### ISSUE THREAD

**Issue by arron12** [gephi/gephi#1696]
## Expected Behavior
In the layout pane, there should be a YifanHu's Multilevel Layout
## Current Behavior
No YifanHu's Multilevel layout found. I tried installing all plugins but there is no plugin available for this layout anymore.

**Comment by mbastian** [comment]
The Yifan Hu Multilevel layout was removed after version 0.9 as we've stopped supporting hierarchical graphs.
