### ISSUE TITLE
Offer snap & flatpak packages

### ISSUE THREAD

**Issue by rugk** [gephi/gephi#1700]
It would be nice to have snap & flatpak packages for this software…

**Comment by mbastian** [comment]
I made good progress on this. I was able to release a development version on Snapcraft at https://snapcraft.io/gephi. 

Next, we would need to automate that as part of the build process if possible.

**Comment by mbastian** [comment]
FYI I've now enabled automated building on the Snapcraft side so every time we push to the repository it will trigger an "edge" build and release it. Some caveats:
- Given that our Snap is based on the OSS snapshot, it only really makes sense to trigger that build when the "release" GitHub action has successfully completed. The webhook solution on 'push' doesn't achieve that. Maybe there is another way, using GitHub actions.
- We would still need to release stable versions manually but as this doesn't happen often it's ok.

**Comment by rugk** [comment]
Okay snap is ok but mostly for Ubuntu only. What about flatpaks? Or should I open a new issue fot that?

I personally prefer flatpak. In contrast to snap, you can also self-host it, so you stay in control, and it is widely supported. (snap is not so nice to setup in many distros and snap's security depends on AppArmor, which is not always available in many distros)
Also – in contrast to snaps – flatpaks do not only claim to be distro-independent, but [actually are](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/).
Furthermore even [Linux Mint criticizes snap](https://blog.linuxmint.com/?p=3906), because you cannot self-host a snap server as it is proprietary and (thus) also cannot modify the packages that are served centralized by Ubuntu.

**Comment by mbastian** [comment]
Thanks for the context @rugk. It's still a TODO to look into flatpak as well. Seems doable.

**Comment by rugk** [comment]
Yeah, see [also their current adoption comparison in Linux distros](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/).

**Comment by xlejo** [comment]
@rugk A try to port Gephi to Flatpak: https://github.com/xlejo/org.gephi.Gephi

**Comment by mbastian** [comment]
@xlejo That's great I'll try it out!

**Comment by mbastian** [comment]
Hi @xlejo @rugk the flatpak is now officially published at https://flathub.org/apps/details/org.gephi.Gephi

**Comment by ximex** [comment]
@mbastian the flatpak on flathub would need also an update. it's still 0.10.1

**Comment by rugk** [comment]
@ximex Best report this on https://github.com/flathub/org.gephi.Gephi/issues/ aka done so for you here: https://github.com/flathub/org.gephi.Gephi/issues/8
