### ISSUE TITLE
No support for 4K screens

### ISSUE THREAD

**Issue by DieterVC** [gephi/gephi#1702]
## Expected Behavior
Support for 4K screens
## Current Behavior
No support for 4K screens: buttons too small to use.

## Context

I cannot use Gephi on my new Dell XPS15 laptop with 4K touchscreen

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by eduramiba** [comment]
Unfortunately this is a Java issue only fixed in OSX. It seems it's fixed in Java 9 but I have not tested it.

http://openjdk.java.net/jeps/263
https://www.reddit.com/r/java/comments/49ip70/java_swing_is_tiny_on_hidpi_displays_what_can_be/

**Comment by gbolcer** [comment]
Same issue in Java8, Windows 10, x64.  Can you force Gephi to use Java9?

**Comment by eduramiba** [comment]
Try to edit gephi.conf and point jdkhome to your java9 installation.

**Comment by gbolcer** [comment]
Set jdkhome in gephi.conf.  Relauched program.   I then noticed that gephi64 is available.  That seems to have fixed the fontsize.  The one side effect is that the anti-aliasing seems a little off when not zoomed in.

**Comment by archenroot** [comment]
I will test on Gentoo amd64 system. JDK 8 is unusable as stated previously on 4K system.

**Comment by archenroot** [comment]
Still same result, I completely recompile and run under JDK 9.0.4 64 on Gentoo system and after fresh start it looks like this:
![image](https://user-images.githubusercontent.com/553512/36076281-4fb0df0e-0f5a-11e8-9dba-662c77803f30.png)

Do I need to additionally change some settings? I expected auto adjustment...

**Comment by eduramiba** [comment]
Related issue in Netbeans Platform https://netbeans.org/bugzilla/show_bug.cgi?id=252452

You can try to change the `dpiaware` setting and report results.

**Comment by archenroot** [comment]
ok, let me check.

**Comment by archenroot** [comment]
Ok, this is with dpiaware enabled:
![image](https://user-images.githubusercontent.com/553512/36105543-2c5e3248-1015-11e8-9cf9-ebd928554f71.png)

Here without this option in the file:
![image](https://user-images.githubusercontent.com/553512/36105613-51819c2c-1015-11e8-9f4b-b1b6ee9ee82b.png)

And here explicitelly disabled (parameter false):
![image](https://user-images.githubusercontent.com/553512/36105651-7992088c-1015-11e8-92b7-15173139861c.png)

Seems like not having any kind of effect...

**Comment by archenroot** [comment]
Anyone could report his/here observations about this 4k scaling?

**Comment by nlappas** [comment]
I tried in my surface pro 2017, which has a resolution of 2,736x1,824, with Java 9 installed, and gephi is unusably blurry.
