### ISSUE TITLE
gephi 0.9.1 can never increase the memory

### ISSUE THREAD

**Issue by chezsick** [gephi/gephi#1705]
gephi 0.9.1 is always limited in 1.3 GB of memory i cannot increase the memory and big graph is not work it's very frustrating.

**Comment by eduramiba** [comment]
Are you using 32 bit Java? You will need a 64 bit version. Also try to manually edit Xmx parameter in gephi.conf file.

**Comment by chezsick** [comment]
@eduramiba ok, but what is expression to set memory for example 3.2 GB, in gephi.conf and what is the path of the config?

**Comment by eduramiba** [comment]
Check this https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by alekdimi** [comment]
On Ubuntu I've manually edited the Xmx parameter in gephi.conf, and yet gephi 0.9.1 still says max memory is 400MB, even thought I've put:
default_options="--branding gephi -J-Xms512m -J-Xmx11144m -J-Xverify:none...

**Comment by chezsick** [comment]
@alekdimi but me i'm on windows and i modify gephi.conf (1300m to 6500m) in programfiles -> gephi-0.9.1 -> etc and print error "Invalid maximum heap size: -Xmx6500m" when i launch in console 64 bit and path of jre

**Comment by alekdimi** [comment]
I found a possible workaround of a possible bug. When launching gephi from the applications menu, it uses the old setting, but if I launch gephi from the command line, it works.

**Comment by chezsick** [comment]
possible bug, it's very a bug for me :/

**Comment by eduramiba** [comment]
Please try latest 0.9.2 snapshot, I think the problem was https://github.com/gephi/gephi/issues/1748

**Comment by chezsick** [comment]
No, i increase the memory 512 to 4800 for exemple, an error message "could not create the virtual machine, A fatal exception has occurred, this program will exit" + after installation an error message for no path to jdkhome in 64 bit windows so it is precise the path to jdkhome, sorry :(
