### ISSUE TITLE
Gephi-Page Rank Analysis Problem

### ISSUE THREAD

**Issue by sujayGitHub** [gephi/gephi#1706]
Dear Gephi-team,

Today I tried to run a small example with a PageRank analysis. Following sections will help you gain insight into the problem. Also please find the picture attached. 
![gephi-pagerank analysis problem](https://cloud.githubusercontent.com/assets/28266577/25592184/17ab36c8-2eb8-11e7-80cb-0b4461274561.png)

## Expected Behavior
Today I tried to run a small example with a PageRank analysis. Please find the graph attached. As you can see, the numbers don't add up. I used a d of 0.85 and epsilon 0.0001 (default). However, each node's value should be 0.15/7 + the sum of its neighbors' values * 0.85. 

## Current Behavior
You can see that the nodes with no in-going edges have a value of 0.038. This indicates that the number of nodes (n) in the algorithm is set to 4 instead of 7.

## Possible Solution
I assume that you are using as n the number of nodes in the strongly connected component (4), but it should be the number of nodes in the graph (7). Thus, the numbers do not add up - especially, the node with a rank of only 0.19 something should have a much higher ranking. It gets input from a node with rank 0.11 and one with 0.24. 

## Steps to Reproduce

1. Please check the attachment. 

## Your Environment
![gephi-pagerank analysis problem](https://cloud.githubusercontent.com/assets/28266577/25592125/d512ddf2-2eb7-11e7-8e20-a9a3ade55e67.png)

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
The values are actually correct. I also didn't understand the resulting values at first, but after some investigation this is the explanation:

1. It's wanted that the sum of all page ranks is 1.0
2. But some nodes don't have any outgoing edge so they don't contribute to the page rank of any other node (these are called dangling nodes)
3. So the solution is to add a dangling rank of `sum(dangling_node_rank) * d / N` of all dangling nodes to each node

Check this for more info http://www.ccs.neu.edu/home/daikeshi/notes/PageRank.pdf
