### ISSUE TITLE
How to display overview window with toolkit？

### ISSUE THREAD

**Issue by aoyuanbo** [gephi/gephi#1707]
## Expected Behavior
I want display a overview windows like gephi's overview with toolkit.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
Currently Gephi toolkit does not support this because the OpenGL module is not easily reusable, but it's in the wishlist.

**Comment by aoyuanbo** [comment]
Thanks
