### ISSUE TITLE
When exporting CSV for nodes, a header is missing

### ISSUE THREAD

**Issue by Jonty800** [gephi/gephi#1710]
## Expected Behavior
label,custom_column_header,modularity_class
G80,80,0
G70,70,1
G60,60,0
G50,50,0
G40,40,0
## Current Behavior
label,1,modularity_class
G80,80,0
G70,70,1
G60,60,0
G50,50,0
G40,40,0

## Steps to Reproduce

1. Open nodes data table in the data lab
2. Click "Export table"
3. Save that awesome CSV data
4. Open CSV to discover that the header for a custom attribute is just the index for the column header

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by eduramiba** [comment]
Uhmm, I can't reproduce this, I must be missing some step. Do you have latest updates installed?

**Comment by Jonty800** [comment]
Hey @eduramiba,

I have the latest version.
Product Version: Gephi 0.9.1 201510222201
Java: 1.8.0_102; Java HotSpot(TM) 64-Bit Server VM 25.102-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_102-b14
System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (gephi)

I have reproduced this 3 times now, on 2 separate files. I've attached the CSV (with all columns ticked) and  the graph file for this project. 
[test.zip](https://github.com/gephi/gephi/files/974513/test.zip)

**Comment by eduramiba** [comment]
Oh, the thing is that the graphml file has a different value for the id and the title (name) of the colum:

```xml
<key attr.name="test" attr.type="int" for="node" id="1"/>
```

So, Gephi shows the column title in the data table, but when you export data, it will always use the id, as it's the actual unique identifier of the column.

**Comment by Jonty800** [comment]
Oh I understand! My bad, I thought the id field was supposed to be numeric.

So I can use:
`<attribute id="test" title="test" type="integer"/>`

instead of:
`<attribute id="1" title="test" type="integer"/>`

And then assign node attributes by:
`<attvalue for="test" value="1"/>`


Gotcha :)

**Comment by eduramiba** [comment]
Yeah :)
