### ISSUE TITLE
Unresponsive when selecting PageRank Node Attribute

### ISSUE THREAD

**Issue by Damien-D** [gephi/gephi#1713]
## Expected Behavior
When selecting Appearance > Nodes > Attribute > Page Rank I should be able to manipulate colour/size of nodes based on their PageRank value.

## Current Behavior
When selecting Appearance > Nodes > Attribute > Page Rank Gephi freezes completely.

## Possible Solution
Unknown

## Context

1k Nodes / 60k edges

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 7 Pro

**Comment by eduramiba** [comment]
Does this still happen with latest 0.9.2 nightly build? https://github.com/gephi/gephi#nightly-builds

**Comment by eduramiba** [comment]
Any update?

**Comment by eduramiba** [comment]
Closing old issue
