### ISSUE TITLE
Infinite repulsion in ForceAtlas with negative weights

### ISSUE THREAD

**Issue by PZerua** [gephi/gephi#1714]
## Expected Behavior
Make a repulsion based on the absolute difference (from the lower number to the higher number) of the weights.

## Current Behavior
Currently if the graph has edges with negative weights, the graph will expand endlessly.

## Possible Solution

A possible solution could be, for example, if a set of weights between -2 and 2 are given, normalize them between 0 and 1, or sum everything by the absolute of the lower number (making it between 0 and 4). I would love to hear any other solution or any comment about the ideas.

## Steps to Reproduce

Given this graph: [movielens.](https://github.com/gephi/gephi/files/984631/movielens_neg.zip)

1. Select either ForceAtlas or ForceAtlas2 distibutions
2. Run

## Context

The example graph contains a set of users and movies, and the weights represent the user ratings, which are between -2 and 2. I'm a computer science student and I'm intersested on implementing this for learning porpuses with a couple of colleagues.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by jacomyma** [comment]
I suggest this approach: add to Force Atlas 2 a switch to virtually rescale weights from 0 to 1. This way it would also be useful when weights are arbitrarily high. It is also consistent with rescaling the edges in the preview.
Nice to have: options for linear and log scale. Possibly, inverse range (1 to 0, see issue #1816)

**Comment by jacomyma** [comment]
Feature added to Force Atlas 2, see https://github.com/gephi/gephi/commit/86ca06982c752d6d6fbd563adbf0e595c8747cf8
