### ISSUE TITLE
Very slow Preview window rendering on macOS Sierra 

### ISSUE THREAD

**Issue by rmhorne** [gephi/gephi#1715]
## Expected Behavior
Switching between Preview and Overview panes should take some time, but not over a minute.

## Current Behavior
Gephi is performing far slower than it should , especially with switching between the Preview and Overview panes (~ 1 minute or longer). A fresh install of Gephi, increasing memory allocation, and changing the java version did not fix this issue.

## Possible Solution
Unknown

## Steps to Reproduce

1. Open Les Miserables.gefx
2. Click on preview tab
3. Wait a long time for the preview screen to appear and become responsive

## Context

I also set the -J-Xmx memory to the maximum suggested by Gephi (11468), which doe not seem to improve performance at all.
 
I also tried changing the java version from jre1.8.0_74.jre to 1.8.0_131-b11, which also had no impact.

I noticed the "Saving Snapshot" dialog seems to fire off, which also takes a very long time to complete (in some cases several minutes). This does not seem to impact the rendering speed in any appreciable way.

The size of the network does not seem to change this behavior; simply importing ~ 200 nodes (without any edges) and switching to Preview also took ~ 1 minute.

The machine that is experiencing this is able to run other java based applications without noticeable slowdown, and several months ago was also able to run Gephi as well without experiencing slowdown, so this is unlikely a hardware issue.

## Your Environment

* Version used:
Gephi 0.9.1 201510222201

* Operating System:
System: Mac OS X version 10.12.4 running on x86_64; UTF-8; en_US
Runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
Java: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11
Graphics: AMD Radeon R9 M370X 2048 MB
Intel Iris Pro 1536 MB
Memory: 16 GB 1600 MHz DDR3
Processor: 2.5 GHz Intel Core i7

**Comment by eduramiba** [comment]
Uhm, something might be corrupted. Please try to delete your gephi user directory: https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by rmhorne** [comment]
Ah, that worked! I seem to have tried everything but the obvious fix - thanks!

**Comment by eduramiba** [comment]
Great!
