### ISSUE TITLE
EXPORTING Edge Table from Gephi

### ISSUE THREAD

**Issue by DannyM64** [gephi/gephi#1716]
## Expected Behavior
  I expect that when I have the Edge Table in the data laboratory and click the 'export' button that it will export the Edge table and NOT the Node table.  (This has normally been the case in my experience.) 
## Current Behavior
When I try to export the **Edge Table**, Gephi gives me the options of what columns from the Node table to export.  When I export, it exports the Node table.  (This has occured at least a couple of times to me)
## Possible Solution
I've restarted my computer and sometimes that works but sometimes it doesn't.  

The other solution is to export the Node Table (with 'Giant Component' Filter on), start a new Gephi project, import the new 1 component only node table and then import the edge table without creating new nodes.  This is a long workaround. 
## Steps to Reproduce

1. Import Node and Edge Table (with data containing at least two components)
2. Run "Giant Component" Filter
3. Export Edge Table
4.

## Context
I import a node and edge table, then run a filter and some statistics.  I then want to export the **Edge** Table (I only want the edges from the giant component).
When I try to export the Edge Table, Gephi gives me the options of what columns from the Node table to export.   

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 7

**Comment by eduramiba** [comment]
Does it work with 0.9.2 snapshot? https://github.com/gephi/gephi/blob/master/README.md#nightly-builds

**Comment by DannyM64** [comment]
Thanks @eduramiba that seems to have fixed the issue.  

I will let you know if it comes back. (this glitch seems to occur only occasionally for some reason)

**Comment by eduramiba** [comment]
Great, have in mind this is an unreleased version. Please report any other bug you​ may find here.
