### ISSUE TITLE
Plugin 

### ISSUE THREAD

**Issue by lilatsopelakou** [gephi/gephi#1717]
Plugin installer won't let user install the following plugin from downloaded nbm file:

Clique Detector
"Some plugins require plugin x to be installed"
where x = org.gephi.clustering.api / org.gephi.clustering.plugin / org.gephi.data.attributes.api

I've googled installing api's and plugins and found no help.

**Comment by eduramiba** [comment]
It seems you are trying to install a Gephi 0.8.2 plugin into Gephi 0.9.1. That's not supported. All 0.9.1 available plugins at the moment are at the Tools - Plugins menu.
