### ISSUE TITLE
Feature request: copy label name of selected node to clipboard

### ISSUE THREAD

**Issue by geertn444** [gephi/gephi#1720]
When i select a node, i would like to have the possibility to copy its label to the clipboard
Right Click, in menu "Copy To Move To, Settle, Free" add an option: "Copy Labelname to Clipboard"

**Comment by eduramiba** [comment]
I think this is already available if you install the linkfluence plugin

**Comment by geertn444** [comment]
Had a challenge installing this plugin in the 0.9.2-snapshot version, but after figuring out that i had to change the plugin url to -0.9.1- version it worked ! Great ! Thanks.
