### ISSUE TITLE
Sorting Nodes by type in a Circular/Layer Formation

### ISSUE THREAD

**Issue by SacredBlaze25** [gephi/gephi#1721]
Greetings, I'm a Telematic Engineer student and currently I'm performing a class project which involves developing the following feature to Gephi.

The project itself is to develop a feature that allows nodes from any graph to be re-positioned in a Circle or Layer fashion depending on the nodes types in the graph. For example: If we have customers and products in a Gephi graph, the feature should put the products in an inner circle and customers in the output one, or in one line and the other ones above, (trying to minimize crossings).

My friend @IsaacRossell and I are new developing in this software so any kind of advice or guidelines would be greatly appreciated.

Thanks for your time :)

**Comment by eduramiba** [comment]
Hi,
Basically you will need to create a layout plugin.

I recommend you check examples such as Geolayout plugin: https://github.com/gephi/gephi-plugins/tree/geolayout-plugin and the plugins bootcamp https://github.com/gephi/gephi-plugins-bootcamp
