### ISSUE TITLE
Graph window remains after switching to Data Table tab

### ISSUE THREAD

**Issue by OldGuyInTheClub** [gephi/gephi#1725]
## Expected Behavior
See data table clearly

## Current Behavior
When I switch to the Data Table tab, I see the ID column and the tools on the top and the bottom.
Everything else is covered by the graph.  Minimizing/maximizing, resizing the Gephi window, dragging panes around etc. have no effect.  

## Possible Solution
New user trying to learn the package.  Don't have enough experience to suggest a solution.

## Steps to Reproduce

1. Close Gephi/Reopen
2. Load the Les Miserables Dataset
3. Switch to Data Tables tab
4.

## Context
Working through QuickStart guide and having troubles both with this display problem and differences between guide screenshots and Gephi screen appearances.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: macOS Sierra 10.12.5

<img width="1437" alt="gephi_0_9_1_-_project_1_and_new_issue_ _gephi_gephi" src="https://cloud.githubusercontent.com/assets/8139720/26763708/fc088146-490b-11e7-8480-bacc11b64b2d.png">

**Comment by eduramiba** [comment]
Duplicarse oficina #1647
