### ISSUE TITLE
Node colors fade to white regardless of background color choice

### ISSUE THREAD

**Issue by gouldingken** [gephi/gephi#1728]
## Expected Behavior
Nodes should fade "into" the background color - i.e. become blacker on a dark background and become whiter on a white background. This would match the behavior for edges in this mode.

## Current Behavior
Nodes become whiter essentially making them stand out more

## Possible Solution
Adjust fade color to match background color.

## Steps to Reproduce
1. Use the background color icon to change the background color to black (or another dark color)
2. Mouse over any node.
3. Connected nodes will turn white instead of fading into the background.

## Context
When looking at connections in complex networks it is easier to see the edges (particularly thin ones) against a dark background. Edges are clearly legible on mouse-over when a node is highlighted along with its neighbors. However the fact that nodes and edges behave in opposite fashion (nodes get lighter and edges darker) means that the dark background mode is less effective for exploring these relationships.

## Your Environment
* Version used: Gephi 0.9.1
* Operating System: Windows 10

**Comment by gouldingken** [comment]
![image](https://user-images.githubusercontent.com/760010/26846941-4fc6b370-4ac9-11e7-8b43-5f7e42cb4ed8.png)

![image](https://user-images.githubusercontent.com/760010/26846953-5b5b45de-4ac9-11e7-8bb1-289b1ebc18fd.png)

**Comment by eduramiba** [comment]
Thanks for the report, it probably is using alpha channel with white color.

**Comment by gouldingken** [comment]
Thank you for taking care of that so quickly!
