### ISSUE TITLE
Setting graph space size/borders

### ISSUE THREAD

**Issue by pdec** [gephi/gephi#1729]
## Expected Behavior

Option for either setting the graph space borders while opening the graph file or setting those parameters in the Graph window. 

## Current Behavior

The graph space has certain dimensions which cannot be modified. While opening a graph file that has coordinates set for each node the program accumulates nodes beyond the boundaries on borders cutting the layout. The same thing happens while using ForceAtlas2 with really big graphs (thousands of nodes).

## Possible Solution

I would suggest adding an option to Import report window, so there was an extra option under 'More options' where you could also check the option to disable the boundaries (make them infinite or as big as the graph requires) or set custom dimensions values (height / width)

## Steps to Reproduce

1. Generate random graph (20000 nodes, 1e-6 winging probability)
2. Run ForceAtlas2 layout with default settings.
3. Change node size to ~50 so you could easily see the nodes.
4. Unzoom so you could see the boundaries/borders.

## Context

I have written a couple of layouts that group sets of nodes and set coordinates for them in a manner I want to. However while working with big graphs (~20 000 and more nodes) and many groups within attributes I get beyond the set borders. I may overcome this by modifying parameters like node size, distances between the nodes in groups but still I think it would be useful to add such an option in feature releases.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Windows 7 Home Premium SP1, Intel Skylake i7-6700, 16GB RAM, NVIDIA GTX 950

## Examples
Loaded graph file
![loaded_graph_file](https://user-images.githubusercontent.com/23166670/26967018-e267aa06-4cfc-11e7-84a9-fca27cc0ee33.png)
Random graph
![random_graph](https://user-images.githubusercontent.com/23166670/26967019-e26ed056-4cfc-11e7-8c00-ba4cb3f9ed0b.png)

**Comment by ggautreau** [comment]
+1

**Comment by eduramiba** [comment]
Will review for 0.9.2

**Comment by eduramiba** [comment]
Addressing this issue in #1518
