### ISSUE TITLE
Very Lost Newbie: Even Dynamic Graph Example (through Gephi) Doesn't Work with Timeline?

### ISSUE THREAD

**Issue by almjorda** [gephi/gephi#1730]
## Expected Behavior
I want to load a dynamic graph and see it change across a timeline. However, timeline fails to register that I or my data exist. 

## Current Behavior
I am going to give as much detail as possible, but I am sure I am doing something wrong that is pretty simple to solve as I am a total newb to dynamic graphs. 

## Steps to Reproduce

1.My new goal is now just to see what the timeline looks like on my end and learn how to activate it, scroll forward, backward, have it play, etc. So I generate a dynamic graph example within gephi (file>generate>dynamic graph example) 
2.  drag (Filters>dynamic>time interval) into the queries box
3.  click Open Timeline (with the Keep Empty box checked), 
4. check "Set custom bounds" "set play settings" "set time format" settings in the timeline. Press play.
5.  Nothing plays when I press play. 
6. I change "set time format" to "date" as the dynamic graph example contains dates in yyyy-mm-dd format, and then the timeline switches from ranges such as [2002, 2002.5, 2003...] to [0,1,2,3,4,5]. I never see months or years appear on the timeline as I have in tutorials that I have watched. Only integers. 
7. I press play arrow again and it immediately goes from green to white. 
8. I try changing the timeline settings. The "Set Custom Bounds" box always has warnings that I do not understand. Upon opening, the default settings (1970-01-01 to 1970-01-01) produce warnings. That makes sense. The data doesn't have much from the 70's. So I tried changing those values (start: 1970-01-01 to end: 2017-01-01) to make sure to capture the data in the dynamic example spreadsheet and it makes no difference to the error, which is either "Value Needs to Be At Least the Minimum" or "Value can't be more than the maximum" even when I give specific time windows that are smaller than the data set. (See images).
![screen shot 2017-06-10 at 12 57 23 pm](https://user-images.githubusercontent.com/29314777/27004778-83e160f8-4ddd-11e7-9c66-23dacdfdc2cc.png)
![screen shot 2017-06-10 at 1 04 36 pm](https://user-images.githubusercontent.com/29314777/27004777-83e08296-4ddd-11e7-8489-769984a42b6a.png)

9. I have tried  running filters, using different layouts simultaneously, etc, and it all makes no difference what so ever. Green to white play button, no changes on the graph at all. Just a static, boring graph that is not moving. 

What am I doing wrong? I have updated, freshly reinstalled, looked at a nightbuild, etc, and after all of this there has been no change. Thus, I presume there is something simple I am missing and the reinstall was serious overkill. It would be great if someone could point me to a true dummy guide for dynamic graphs, even one with only 5-10 nodes, something extremely simple, just so I can figure out how to make the timeline play on my end. 

## Context

My end goal here is make a dynamic graph of my own data, but I figure that is its own can of worms. I formatted a csv file for a graph of dynamic data to learn via experimentation after watching numerous youtube tutorials and primers and still remaining extremely lost [_e.g. if I wanted import gexf instead of csv, how do I make a gexf file? do I just type it into Notepad++ by hand or is there another program I should use? I see the way to textually format nodes and edges and characteristics but I don't see a suggested program for actually writing this mega file out and saving it as a gexf_]]. 

My current data set is for a contemporary art network in Ghana. I have a start column (dd/mm/yyyy) and an end column (dd/mm/yyyy) for all my edges, which represent when a given connection was made between two actors. I want to see these connections appear, but I imagine I have the format wrong somehow. After trying to merge start and end columns into interval column and failing (the new time interval column just spits out -infinity to infinity no matter what, and I am careful to import as dd/mm/yyyy style...) I decided I would give up on doing it with my data and try a dynamic data set example through gephi. 

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: MAC OS Sierra and Windows 10 (have tried on both)
![screen shot 2017-06-10 at 12 57 23 pm](https://user-images.githubusercontent.com/29314777/27004735-680b8eea-4ddc-11e7-9cd9-ddca0f516e80.png)

**Comment by eduramiba** [comment]
Hi,
I think you are missing to slide the window limit before clicking play, so nothing happens.

What play button does is move the window, and the window is the whole time by default.

You can also check some tutorials here https://seinecle.github.io/gephi-tutorials/

**Comment by eduramiba** [comment]
Did it work?

**Comment by almjorda** [comment]
Hi Eduardo,

Yes and no! The sliding sort of worked, it did slide but then the program
was freezing with my data. I partially resolved by reinstalling. Then,
instead of doing anything at all by csv---importing nodes deleted edge data
and vice versa--- and so I switched over to
Gexf (same issue more or less) and finally decided Gdf is the best for my
data, with tons of timeline data for edges but only a few timeline points
for nodes, but attributes for all of them. There were a bunch of errors,
all my fault, dealing with formatting that GDF made really easy to see and
I sorted almost all of them out. Plus, GDF is super easy for me, a non
programmer, to write and read GDF files.

Now, the timeline feature usually works but still crashes the program on
occasion.

**Comment by eduramiba** [comment]
Glad to hear that! The crashes should be fixed for 0.9.2, can you try with the latest snapshot (pre-release) and report any problems please? Download it at https://github.com/gephi/gephi#nightly-builds

**Comment by ivanuzz** [comment]
Hello, I'm new to Gephi and had the same issue of _almjorda_ with a dynamic graph. I was able to see the dynamics at work by sliding the limit window, but I have another question: Is there any way to see the graph changing over time in the **preview** window (not just in overview)? Any way to see the "animation" in full screen for presentation purposes?

**Comment by eduramiba** [comment]
@ivanuzz Not possible in preview as it's not real time.
I think there is a full screen mode in view menu but you will need to close undesired windows.

**Comment by ivanuzz** [comment]
Thanks a lot, but I don't see a 'View' menu on my version of Gephi 0.9.1 (see attached file 'ViewMenu.png').

Second, I can't figure out how to make nodes size and edges weight to change over time. I found a not-so-elegant solution, by creating different nodes and edges for every timeframe desired, but I believe that the optimal way to do it is by converting these attributes columns (size and weight) to dynamic and specifying the timeframes and values as <[t1, t2, v1]; [t3, t4, v2]>. I did so, but the attributes are not changing in the graph as I hit play in the timeline or move the window limit manually. I set node size as a ranking using my new created attribute _sizedynamic_ and the weights cannot be ranked using _weightsdynamic_, although it was created using the same method used for size.

![viewmenu](https://user-images.githubusercontent.com/13490650/28892724-e5de32c0-779c-11e7-84bf-026868a09990.png)


Thanks in advance for your help.

**Comment by eduramiba** [comment]
@ivanuzz Right, that menu is not implemented yet, but you can still do it with alt + shift + enter. I created an issue for this: #1762
About animated node sizes and colors. you will need to check the apply continuously option in appearance window (ranking or partition). It's a small button on the lower right corner next to apply button.

The weight should automatically change if it's dynamic, but try it with the [latest 0.9.2 snapshot ](https://github.com/gephi/gephi#nightly-builds) since a bug with weight display was fixed.

**Comment by ivanuzz** [comment]
Awesome!! My IT Department won't let me install the 0.9.2 Snapshot, but the node size and color are almost perfectly with 0.9.1.

Thanks!

**Comment by eduramiba** [comment]
Great :)

**Comment by Ani123456789** [comment]
I am trying to explore a network of judicial decisions with a graph in Gephi. It is rather handy but when I want to show how the nodes and the edges in the network are changing over time (whether getting more citations and thus growing) I could not make it work in the dynamique mode. I specify as a start date the time when the event occurred (the judgement was issued) and as end date (present year), I get the dynamique mode and timeline but gephi just calculates what happens with my nodes between the start and the end date. How can I make it calculate the changes of the nodes if for example start date is 1999 and end date is 2018 – what happens with the node between 1999 and 2000, 2000 and 2001, 2001 and 2002, and thus until 2018. Any suggestions are more than welcome! I am a newbie in Gephi. Thank you!
