### ISSUE TITLE
Adjacency Matrix Import - No Preview

### ISSUE THREAD

**Issue by SelimDayanik** [gephi/gephi#1731]
## Expected
Import .csv (semicolon separated) adjacency matrix and gephi display the visual network

## Current Behaviour
Import loads without issue, as it identifies 19 nodes and 84 edges, but does not display anything. I cannot get it to show me a viz regardless of what I try to do!

## Steps to Reproduce

1. File > open
2. Select attached .csv example
3. Load
[GitHub Gephi Example.csv.zip](https://github.com/gephi/gephi/files/1066034/GitHub.Gephi.Example.csv.zip)

![screen shot 2017-06-10 at 19 33 54](https://user-images.githubusercontent.com/24955040/27005295-c3d4df9c-4e13-11e7-8f61-b289e92da885.png)

![screen shot 2017-06-10 at 19 34 31](https://user-images.githubusercontent.com/24955040/27005296-dc6a4e70-4e13-11e7-8751-e700af987896.png)

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Mac OS 10.12.5

**Comment by eduramiba** [comment]
It seems you have closed Graph window. Open it in Window menu or reset windows.

**Comment by SelimDayanik** [comment]
Oh my days!

As if it was that simple! Thank you
