### ISSUE TITLE
export function

### ISSUE THREAD

**Issue by mindoLife** [gephi/gephi#1732]
## Expected Behavior
export the graph properly to pdf/png
## Current Behavior
now it create unreadable exported graphs (attached pdf file)
## Steps to Reproduce

1.create a graph
2.try to export it to pdf or png
3.
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: windows 7
[rami-net.pdf](https://github.com/gephi/gephi/files/1066308/rami-net.pdf)

**Comment by eduramiba** [comment]
Try to use scale weights option in preview. You might have very different weights in your edges.

**Comment by eduramiba** [comment]
Did it work?
