### ISSUE TITLE
How to get node and edge attribute values?

### ISSUE THREAD

**Issue by jimmymathews** [gephi/gephi#1737]
## Expected Behavior

`node.getAttribute("Weight")`

would return the float or double equal to the node's Weight attribute.

## Current Behavior

The return type of Node's getAttribute method is Object. This Object can't be casted to float or double.

## Possible Solution

In the Node and Edge API, or at least in one of the example plugins, explain how to access values from the data table.

## Steps to reproduce

It is not a bug (I think). It is missing documentation.

## Context

I want to get (and not only set) numerical values associated with the graph via custom plugins.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Ubuntu 16.04

**Comment by juliannej** [comment]
Sorry - do you mind sharing why you closed this? Did you find a work-around?

**Comment by juliannej** [comment]
nvm - for any future user:
 e.g.
return (Double) node.getAttribute("weight", interval);

**Comment by jbliesener** [comment]
Suggestion:

if (object instanceof Number) {
  return ((Number)(object)).doubleValue();
} else {
  return null;
}

**Comment by jimmymathews** [comment]
Sorry about that! Let me try to remember.
In my code about this (which now works, I think) I found:

```
w = (Double)n.getAttribute("Weight");
... w.doubleValue() ...
```

I think before I was trying to cast as a literal double, not the Java wrapper Double as in the above. So I probably closed because I decided it was my Java ignorance at fault here, not the Gephi code.
