### ISSUE TITLE
Can not create dmg

### ISSUE THREAD

**Issue by GRCCuser** [gephi/gephi#1741]
## Expected Behavior
Create dmg

## Current Behavior
Command:
```mvn -Pcreate-dmg clean package```

Return error:
Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (create-app-bundle) on project gephi: An Ant BuildException has occured: Warning: Could not find file /../gephi/modules/application/target/Gephi.app/Contents/PlugIns/application/Contents/Home/lib/jli/libjli.dylib to copy.
around Ant part ...copy file="/../gephi/modules/application/target/Gephi.app/Contents/PlugIns/${bundle.jre.name}/Contents/Home/lib/jli/libjli.dylib" todir="/../gephi/modules/application/target/Gephi.app/Contents/PlugIns/${bundle.jre.name}/Contents/MacOS"/... @ 48:351 in /../gephi/modules/application/target/antrun/build-main.xml

This happened after i update my mocOS Sierra on v 10.12.5 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

Macbook pro
Version used: Gephi 0.9.1
Operating System: IOS 
Java version: 1.8.0_131

**Comment by eduramiba** [comment]
Are you using latest master commit?

**Comment by eduramiba** [comment]
https://github.com/gephi/gephi/commit/3439055a92a376a75281c7535bdf7ed34362cdaf

**Comment by GRCCuser** [comment]
no, thank you! But I do not understand the creation dmg. Now i need use something else? 
```
mvn -Pcreate-dmg,deployment clean package
```
