### ISSUE TITLE
Import of GEXF format rearranges order of node attributes

### ISSUE THREAD

**Issue by rwreed** [gephi/gephi#1742]
## Expected Behavior
The attributes should show up in Data Laboratory in the same order they are defined in the GEXF attribute list.

## Current Behavior
The attributes show up in what seems like a random order.  They are actually sorted by hash value of the attribute ID, which is not very useful.

## Possible Solution
In modules/ImportAPI/src/main/java/org/gephi/io/importer/impl/ImportContainerImpl.java
        nodeColumns = new Object2ObjectOpenHashMap<>();
        edgeColumns = new Object2ObjectOpenHashMap<>();

Convert them to Object2ObjectLinkedOpenHashMap instead.

## Steps to Reproduce

1. Open the attached sample GEXF file (remove the .txt extension from the filename first)
[field_ordering.gexf.txt](https://github.com/gephi/gephi/files/1109003/field_ordering.gexf.txt)
2. Go to Data Laboratory.

## Context

When using Gephi to investigate data with a number of relevant attributes, having the attributes scrambled makes it harder to review.  For example, we typically have names and addresses, with separate fields for first name, middle name, last name, etc.  When they are ordered nicely, it's easy to read.

## Your Environment

* Version used: Gephi 0.9.1 201510222201
* Operating System: Windows 7 version 6.1 running on amd64; Cp1252; en_US
* Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

**Comment by eduramiba** [comment]
Thanks for the report and suggested solution!
