### ISSUE TITLE
gephi can not start up,remain “starting module“

### ISSUE THREAD

**Issue by eqmaster** [gephi/gephi#1747]
## Steps to Reproduce

1.start the gephi 0.9.1
2.remain “starting module“
3.i have try to set the /etc/gephi.conf jdkhome,but it doesnot work still

## Context

* Version used: Gephi 0.9.1
* Operating System:window7 x64
* jdk version is jdk1.7.0_55

**Comment by eduramiba** [comment]
Duplicate of #1631
