### ISSUE TITLE
Statistics disabled 

### ISSUE THREAD

**Issue by annak820** [gephi/gephi#1751]
Statistic panel is disabled.

Even when closing/opening from overview or data laboratory.

* Version used: Gephi 0.9.1
* Operating System: Ubuntu 16.04

**Comment by eduramiba** [comment]
What are the steps to reproduce? Can you share the file you are using? Is there anything in user directory logs? See https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by eduramiba** [comment]
Closing old issue
