### ISSUE TITLE
Graph not visible

### ISSUE THREAD

**Issue by ellipsis3** [gephi/gephi#1752]
## Expected Behavior
When uploaded sample file (les miserables), graph should become visible.

## Current Behavior
When uploaded sample file (les miserables), graph is not showing.

## Possible Solution
I've restarted program and my computer. I've also reinstalled gephi and java... still nothing so I don't know what else to do.

## Steps to Reproduce

1. Not sure
2.
3.
4.

## Context

Can't use the program at all

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: MacOS Sierra 10.12.5

**Comment by ellipsis3** [comment]
<img width="2293" alt="screenshot 2017-07-06 09 26 16" src="https://user-images.githubusercontent.com/29951993/27915907-349a2aa2-622d-11e7-9ce5-70d7e73eee66.png">

**Comment by eduramiba** [comment]
Hi,
It seems you closed the graph window. Try to open it again in Window menu.

**Comment by ellipsis3** [comment]
Genius!!!

Thank you.

 

Sent: Thursday, July 06, 2017 at 9:30 AM

**Comment by ellipsis3** [comment]
I may have also closed the module where 'ranking' can be found... how do I open that?
 

Sent: Thursday, July 06, 2017 at 9:30 AM

**Comment by eduramiba** [comment]
That's in appearance window. It will appear when you choose Attribute mode instead of Unique.
