### ISSUE TITLE
Data Laboratory will not display Statistics after deleting column

### ISSUE THREAD

**Issue by gvsbdisco** [gephi/gephi#1754]
I am working through a simple example where I am interested in the main centrality measures of a network (closeness, betweenness etc).  After taking the necessary steps to create the statistics I view them in the data laboratory table.  Then I decided to clean up the table and get rid of some of the measures (so I delete the closeness centrality column for example).  If I re-run the statistics, I can never get the results to show in the data lab window once the relevant column has been deleted (as in, it seems once you delete a column it can't be recreated).  I tried saving the project, re-opening it and still i cannot get the relevant stats to show in the data lab window.  

## Expected Behavior
- Re-running the statistics should re-create the relevant column(s) in the data lab window

## Current Behavior
As described in opening preamble

## Steps to Reproduce
As described in opening preamble.
## Your Environment

* Version used: Gephi 0.9.1
* Operating System:
Windows 10 64 bit

**Comment by eduramiba** [comment]
Hi,
This might be a small bug with chosen visible columns. Please try to make the column visible by clicking in the small icon with a lightbulb in data laboratory top right corner

**Comment by gvsbdisco** [comment]
oh geez.....thanks so much.  That was the problem.
