### ISSUE TITLE
Invisible nodes in preview

### ISSUE THREAD

**Issue by siyuma0212** [gephi/gephi#1763]
## Expected Behavior
Display the visualisation of the graph in preview
## Current Behavior
Only edges are visible. Cannot display the nodes.
## Context
Hi there, I am trying to read a .csv file and construct the graph manually. I think I got the data loaded into graph model correct. It now can display the edges in the preview but nodes are invisible. I have no idea how to solve it. Could you give me some suggestions about that?
`
package org.gephi.toolkit.demos;

import com.csvreader.CsvReader;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;
import org.gephi.datalab.api.datatables.DataTablesController;
import org.gephi.graph.api.Column;
import org.gephi.graph.api.DirectedGraph;
import org.gephi.graph.api.Edge;
import org.gephi.graph.api.GraphController;
import org.gephi.graph.api.GraphModel;
import org.gephi.graph.api.Node;
import org.gephi.io.importer.api.Container;
import org.gephi.io.importer.api.ImportController;
import org.gephi.io.processor.plugin.DefaultProcessor;
import org.gephi.layout.plugin.AutoLayout;
import org.gephi.layout.plugin.force.StepDisplacement;
import org.gephi.layout.plugin.force.yifanHu.YifanHuLayout;
import org.gephi.layout.plugin.forceAtlas.ForceAtlasLayout;
import org.gephi.preview.api.*;
import org.gephi.preview.types.DependantColor;
import org.gephi.preview.types.DependantOriginalColor;
import org.gephi.preview.types.EdgeColor;
import org.gephi.project.api.ProjectController;
import org.gephi.project.api.Workspace;
import org.gephi.toolkit.demos.plugins.preview.PreviewSketch;
import org.openide.util.Lookup;

/**
 *
 * @author Mathieu Bastian
 */
public class PreviewJFrame {

    public void script() {

        //Init a project - and therefore a workspace
        ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
        pc.newProject();
        Workspace workspace = pc.getCurrentWorkspace();

        //Get a graph model - it exists because we have a workspace
        GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel(workspace);
        Column tag = graphModel.getNodeTable().addColumn("tag",String.class);
        Column address = graphModel.getNodeTable().addColumn("address",String.class);
        Column branch  = graphModel.getNodeTable().addColumn("branch",String.class);
        Column trunk = graphModel.getNodeTable().addColumn("trunk",String.class);
        Column bundle = graphModel.getNodeTable().addColumn("bundle",String.class);
        Column currentIndex = graphModel.getNodeTable().addColumn("currentIndex",Integer.class);
        Column lastIndex = graphModel.getNodeTable().addColumn("lastIndex",Integer.class);
        Column value = graphModel.getNodeTable().addColumn("value",Long.class);
        Column timestamp = graphModel.getNodeTable().addColumn("timestamp",Long.class);
        
        
        String filename = "/Users/cecilia/Documents/iota/data/from0407.csv";
        int i = 0;
        DirectedGraph directedGraph = graphModel.getDirectedGraph();
        try{
            CsvReader records = new CsvReader(filename);
                     
            records.readHeaders();
            while(records.readRecord() && i<40)
            {

                System.out.println(i);
                String hash = records.get("hash");
                Node n = graphModel.factory().newNode(hash);
                n.setLabel(hash);
                n.setX((float) ((0.01 + Math.random()) * 1000) - 500);
                n.setY((float) ((0.01 + Math.random()) * 1000) - 500);

                String edge1 = records.get("branch");
                String edge2 = records.get("trunk");
                
                Node n1 = graphModel.factory().newNode(edge1);
                n1.setLabel(edge1);
                n1.setX((float) ((0.01 + Math.random()) * 1000) - 500);
                n1.setY((float) ((0.01 + Math.random()) * 1000) - 500);
                
                Node n2 = graphModel.factory().newNode(edge2);
                n2.setLabel(edge2);
                n2.setX((float) ((0.01 + Math.random()) * 1000) - 500);
                n2.setY((float) ((0.01 + Math.random()) * 1000) - 500);
                i++;
                
                if(directedGraph.getNode(n.getId()) == null)
                {
                    directedGraph.addNode(n);
                    //graphModel.getGraph().getNode(n.getId());
                    n.setAttribute(address,records.get("address"));
                    n.setAttribute(tag,records.get("tag"));
                    n.setAttribute(bundle, records.get("bundle"));
                    n.setAttribute(branch, records.get("branch"));
                    n.setAttribute(trunk, records.get("trunk"));
                    n.setAttribute(currentIndex, Integer.parseInt(records.get("currentIndex")));
                    n.setAttribute(lastIndex, Integer.parseInt(records.get("lastIndex")));
                    n.setAttribute(timestamp, Long.parseLong(records.get("timestamp")));
                    n.setAttribute(value, Long.parseLong(records.get("value")));
                    
                    //System.out.println("a");
                }
                else
                {
                    n = directedGraph.getNode(n.getId());
                }
                System.out.println(directedGraph.getNode(hash).getLabel());
                System.out.println(directedGraph.getNode(hash).getAttribute(trunk));
                if(directedGraph.getNode(n1.getId()) == null)
                {
                    directedGraph.addNode(n1);
                }
                else
                {
                    n1 = directedGraph.getNode(n1.getId());
                }
                if(directedGraph.getNode(n2.getId()) == null)
                {
                    directedGraph.addNode(n2);
                }
                else
                {
                    n2 = directedGraph.getNode(n2.getId());
                }
                if(directedGraph.getEdge(n,n1)== null)
                {   
                    Edge e1 = graphModel.factory().newEdge(n, n1, true);
                    directedGraph.addEdge(e1);
                    //System.out.println("33");
                }
                
                if(directedGraph.getEdge(n,n2) == null)
                {
                    Edge e2 = graphModel.factory().newEdge(n, n2, true);
                    directedGraph.addEdge(e2);
                }
            }
            records.close();
        }catch (FileNotFoundException e) {
            System.out.println(e.toString());
        } catch (IOException e) {
            System.out.println(e.toString());
        }
        
        
        System.out.println("Nodes: " + graphModel.getGraph().getNodeCount() + " Edges: " + graphModel.getGraph().getEdgeCount());
 
        PreviewController previewController = Lookup.getDefault().lookup(PreviewController.class);
        PreviewModel previewModel = previewController.getModel();
        //previewModel.getProperties().putValue(PreviewProperty.SHOW_NODE_LABELS, Boolean.TRUE);
        previewModel.getProperties().putValue(PreviewProperty.DIRECTED, Boolean.TRUE);
        previewModel.getProperties().putValue(PreviewProperty.NODE_BORDER_COLOR,new DependantColor(Color.WHITE));
        previewModel.getProperties().putValue(PreviewProperty.NODE_LABEL_COLOR, new DependantOriginalColor(Color.WHITE));
        previewModel.getProperties().putValue(PreviewProperty.NODE_OPACITY,100);
        previewModel.getProperties().putValue(PreviewProperty.EDGE_COLOR, new EdgeColor(Color.GRAY));
        previewModel.getProperties().putValue(PreviewProperty.EDGE_CURVED, Boolean.FALSE);
        //previewModel.getProperties().putValue(PreviewProperty.EDGE_OPACITY, 100);
        previewModel.getProperties().putValue(PreviewProperty.EDGE_RADIUS, 10f);
        previewModel.getProperties().putValue(PreviewProperty.BACKGROUND_COLOR, Color.BLACK);

        //New Processing target, get the PApplet
        G2DTarget target = (G2DTarget) previewController.getRenderTarget(RenderTarget.G2D_TARGET);
        final PreviewSketch previewSketch = new PreviewSketch(target);
        previewController.refreshPreview();

        //Add the applet to a JFrame and display
        JFrame frame = new JFrame("Test Preview");
        frame.setLayout(new BorderLayout());

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(previewSketch, BorderLayout.CENTER);

        frame.setSize(1024, 768);
        
        //Wait for the frame to be visible before painting, or the result drawing will be strange
        frame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                previewSketch.resetZoom();
            }
        });
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        PreviewJFrame previewJFrame = new PreviewJFrame();
        previewJFrame.script();
        
        System.out.println("finished");
    }

}
`
## Your Environment

* Version used: Gephi 0.9.1
* Operating System: MACOS

**Comment by eduramiba** [comment]
Does setting a size of 10.0 to nodes work?

**Comment by siyuma0212** [comment]
Hi @eduramiba , thanks for the reply. Do you mean to set the node opacity to 10.0 in preview setting?

**Comment by eduramiba** [comment]
I mean n.setSize to each node. Default size 1.0 might be too small. Are edges visible?

**Comment by siyuma0212** [comment]
@eduramiba I have tried n.setSize(10) but there is no change. Yes edges are visible. Here is the preview I have got now.
![1](https://user-images.githubusercontent.com/25327394/28941961-93c3ebd8-7891-11e7-9f90-6526f8482ee6.jpeg)

**Comment by eduramiba** [comment]
Oh, your nodes must hace default black color and mix with the background then

**Comment by siyuma0212** [comment]
OH! Thanks so much! I think I have got the node visible now. Here is the output. However, the graph still seems a little bit strange with edges not link to the nodes.
![2](https://user-images.githubusercontent.com/25327394/28942253-8fddccd6-7892-11e7-8f03-42cb8621177c.jpeg)

**Comment by eduramiba** [comment]
Yeah that is normal, just set EDGE_RADIUS to 0.

**Comment by siyuma0212** [comment]
@eduramiba Thanks very much for your patience and help.
