### ISSUE TITLE
Labels are invisible!

### ISSUE THREAD

**Issue by geersk** [gephi/gephi#1764]
I am new to Gephi ... everything looks great, but I cannot make the labels visible. I am following the instructions, and pushing the right button, but no dice. I am using Windows 10 Pro. What am I missing?

Thanks!

KG

**Comment by geersk** [comment]
Now I have labels in Overview, but not in preview or exporting ...

**Comment by eduramiba** [comment]
Did you check the show node labels option in preview?

**Comment by geersk** [comment]
Yes!

**Comment by geersk** [comment]
Anything else to check?
Thanks :)

**Comment by eduramiba** [comment]
Can you show an screenshot of all the preview options and data laboratory nodes table?
Make sure the data is filled in 'Label' column.

**Comment by geersk** [comment]
Got it - works now, thank you!
