### ISSUE TITLE
Preview image tiny - why?

### ISSUE THREAD

**Issue by geersk** [gephi/gephi#1769]
Maybe there are small nodes far out that I cannot see?

Thanks!

**Comment by eduramiba** [comment]
Yeah, probably. Try to export to svg and open with inkscape

**Comment by geersk** [comment]
Thanks - but no way to find the lost node in Gephi?

**Comment by eduramiba** [comment]
Setting a black background might help find them

**Comment by geersk** [comment]
Awesome thanks!
