### ISSUE TITLE
Gephi only capture one edges after imported the spreadsheet

### ISSUE THREAD

**Issue by Charlieykl** [gephi/gephi#1772]
## Expected Behavior
After imported the spreadsheet, it should show all the edges as per the csv spreadsheet for edges table.

## Current Behavior
However, after imported, the edges table only captured the first line of the csv file and dropping the rest of the lines.

## Possible Solution
I have double check the header of the csv file as well as to clear any hidden spaces as possible, still it is not working after several attempts to reupload. Please advise.

## Steps to Reproduce

1.
2.
3.
4.

## Context
Attached a copy of spreadsheet for your information.
[Test_CSV.zip](https://github.com/gephi/gephi/files/1224114/Test_CSV.zip)

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
All your edges have the same id ('5'). You can either not import the id column at all or provide different ids for each edge.

**Comment by eduramiba** [comment]
Also, have in mind that spreadsheet import does not support color, size or position definition.

**Comment by Charlieykl** [comment]
Thanks for the solution! Eduardo
It works for me now. However, by installed additional plugins, Gephi is able to read the color code from the csv spreadsheet and give color to the chart accordingly.
