### ISSUE TITLE
freezing while is  Initializing modules

### ISSUE THREAD

**Issue by Ilanfigueiredo** [gephi/gephi#1773]
## Expected Behavior
successfully installed
## Current Behavior
not installed
## Possible Solution

Gephis version for 32 bits Operational System?

## Steps to Reproduce

1.Download Gephi 0.9.1
2.Run the installer (gephi-0.1.1-windows)
3.Freeze while is initializing modules
4.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Widows 8. 32 bits operational system.

**Comment by eduramiba** [comment]
Can you test with latest 0.9.2 SNAPSHOT? https://github.com/gephi/gephi#nightly-builds

**Comment by eduramiba** [comment]
Closing as duplicate of #1631
