### ISSUE TITLE
Question: Can I fork the gephi repository and run a Travis build without interfering with the official nightly repository?

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi#1775]
## Expected Behavior
I fork the gephi repository, integrate it with my travis-ci account and run a build. No interference with official Sonatype repository

## Current Behavior
Don't know, I'm afraid to test it. All sonatype keys and access data seem to be contained in the github repository. Could it be that my travis build overwrites an official nightly build on Sonatype?

## Possible Solution
Make sure that forked repository builds don't interfere with official nightly builds. Separate sonatype access credentials from official repository build.

## Context
I was about to test a build and everything was already running on travis-ci, when I noticed that my patch might get uploaded to the Sonatype nightly gephi repository. I cancelled the build and decided to ask first.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System:

**Comment by eduramiba** [comment]
Hi,
There is no credentials in our git repository, we have them defined in travis, so it's safe to fork the repository, you will not be able to deploy anything.

**Comment by jbliesener** [comment]
Will do then. I'll let you know afterwards. Testing a small change with the Windows Setup.

**Comment by jbliesener** [comment]
OK, I found the hidden environment variables. Won't help me, though, as the build process stops with an invalid decryption of the pubring.gpg.enc file. Same thing would happen with the secretring.gpg.enc file later.

I'd have to generate a new keyring in order to be able to run the build, but I don't know what keys are in it. From what I see from the commit that @mbastian did, the gpg key name is hardcoded in lines 57 and 58 of .travis.yml, so I'd like to suggest defining this keynames as an environment-variable as well.

**Comment by eduramiba** [comment]
The easiest option would be to modify travis file si it only does install phase, not deploy. And also without deployment profile (enables gpg sign).
