### ISSUE TITLE
plug in gephi

### ISSUE THREAD

**Issue by guntaku92** [gephi/gephi#1776]
Hello. I have a problem with plug-ins of gephi. When I click on "check for updates" in the "Updates" section and on "find updates" in "Available plugins", a window appears with the following messages
"Could not connect to Gephi Update Center due to https://raw.githubusercontent.com/…/netbeans_si…/updates.xml" and
"Check the proxy settings or try again later. The server may not be available at this time. Also make sure the firewall is not blocking network traffic."
I do not understand how to fix it. Can you show me through screenhoot how to fix it?

**Comment by eduramiba** [comment]
What version are you using?

**Comment by guntaku92** [comment]
Gephi 0.9.2 - SNAPSHOT

**Comment by eduramiba** [comment]
Ok, then that's normal. We have not published 0.9.2 yet so no plugins are available. You can meanwhile force to use the 0.9.1 plugins url by modifying in Tools - Plugins - Settings
