### ISSUE TITLE
Statistics Question

### ISSUE THREAD

**Issue by maggie-oneil** [gephi/gephi#1778]
Hi there - 

No error to report, but I am trying to get a better understanding of how the graph statistics features work, and have been tasked with doing some of these statistics by hand for small networks. I have the equations for closeness centrality, and betweeness centrality, but can't find any documentation on what specific algorithm is being used to calculate eccentricity. If you could point me in the right direction, that'd be great. Thanks!

**Comment by eduramiba** [comment]
Hi,
As described in the statistics report, the algorithm is Ulrik Brandes, A Faster Algorithm for Betweenness Centrality, in Journal of Mathematical Sociology 25(2):163-177, (2001)
