### ISSUE TITLE
Unable to launch 0.8.2 on windows 10

### ISSUE THREAD

**Issue by kjyoo88** [gephi/gephi#1786]
## Expected Behavior
I installed 0.8.2 on window 10 because I want hiveplot layout plugin which is only available to this version. 

## Current Behavior
When I tried to launch the program, the logo appears but then after a few second, it stops while 'loading cached objects' and I'm unable to open the program.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.8.2
* Java version: version 8 update 144
* Operating System:  Windows 10

**Comment by eduramiba** [comment]
Hi, Gephi 0.8.2 only supports Java 7 or less.
