### ISSUE TITLE
Can not install gephi 0.9.3 in Win 10

### ISSUE THREAD

**Issue by kimyoungjin06** [gephi/gephi#1793]
## Steps to Reproduce

1. I did use gephi 0.9.1 in Win 10 with error "can not load openGL"??
2. Download gephi 0.9.3 from this repository
3. Can not start install application with error message "Windows cannot access the specified device, path, or file. You mat not have the appropriate permissions to access the item.
4. Get same error message with "Run as administrator"

## Context

I say in above tap. Why... cannot install...??

## Your Environment

* Version used: Gephi 0.9.3
* Java version: 8 update 144
* Operating System: Win 10

**Comment by eduramiba** [comment]
Hi,
The installer is the same as 0.9.2, and there is no real difference between 0.9.2 (just released) and 0.9.3-SNAPSHOT.
If you have problems with install permissions, I suggest you use the .tar.gz distribution as it works in any OS.
