### ISSUE TITLE
Resizing edge sizes changes edge weight values

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#180]
Hi,

I _think_ this is a bug: I'm working with network data where (in addition to weight), edges have a number of other attributes. 

As a simplified example, my data would say that an edge from node A to node B is 30% of type X, and 70% of type Y, etc. - in other words:

source       target       weight       type_x       type_y
A              B              10             0.3            0.7
C              D              4               0.5            0.5

The edge dataset imports into Gephi's Data Laboratory perfectly well (with the type_x / type_y columns imported as column type 'Float', for example), and I can create a network map without problems (e.g. with standard settings using Force Atlas 2).

However, if I then try to use the Ranking tab to change the size (thickness) of the network edges so that edge size is according to the value in type_x or type_y, while the Force Atlas 2 algorithm is still running, the whole network graph changes shape.

I'm not completely sure if this is a bug or a feature. As I understand it, the changes made in the Ranking tab should be completely cosmetic, and have nothing to do with the underlying (mathematical) structure of the network itself: for example, I can set node sizes according to various metrics, but that doesn't mean that the nodes will change position and become more or less central to the network. 

I _think_ the same should apply here: the positioning of the nodes in an attraction/repulsion-based network graph like Force Atlas (2) should always simply be based on the _weight_ of the edges between them, and should be independent of how (i.e. based on what data) these edges are displayed. So, two nodes with a weighty edge between them would be close together, and if I chose to display only those edges as thick which have a high score on some other metric, that should not affect the positioning of those edges relative to one another.

Or, perhaps, it would be useful to choose which edge metric (weight or something else) Gephi's algorithms use to calculate the position of nodes in the graph visualisation, independent of which metric is used to calculate the visual thickness of the edges as they are displayed ?

I hope this makes sense - happy to provide further information...

Axel Bruns

---

Imported from Launchpad using lp2gh.
- date created: 2011-06-30T07:31:54Z
- owner: a-bruns
- assignee: mathieu.bastian
- the launchpad url was https://bugs.launchpad.net/bugs/803763

**Comment by ColinWilder** [comment]
I seem to have a similar problem:  I cannot figure out how to vary the size/thickness of the edges in Overview/Appearance/Edges by Weight. The option just does not appear, the way it does in /Nodes. Any ideas?
