### ISSUE TITLE
Not able to find the neo4j plugin in gephi 0.9.2

### ISSUE THREAD

**Issue by rameshthangam1** [gephi/gephi#1800]
## Steps to Reproduce

1.Click for plugins under tools and select available plugins
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Duplicate of #1404

**Comment by syntheticperson** [comment]
Will there be a neo4j plugin for gephi?
