### ISSUE TITLE
[solved] 0.9.2 stable Linux build crash to desktop during splash screen

### ISSUE THREAD

**Issue by scheckley** [gephi/gephi#1803]
## Expected Behavior
Gephi runs on Ubuntu 16.04
## Current Behavior
Gephi freezes during "Starting modules" splash screen

## Steps to Reproduce

1. Install Gephi for Linux on Ubuntu 16.04 (Mint 18.2)
2. run gephi binary in ~/gephi/bin

## Possible resolution

Unknown, but Gephi 0.9.2 **does** launch using software rendering mode for the desktop so I am suspecting a problem with the AMD GPU driver. Also launches fine on Intel GPU with the same OS. 

## Context
Gephi doesn't launch on Ubuntu 16.04 with an AMD GPU

## Your Environment
Linux Mint 18.2 (Ubuntu Xenial). AMD 270x, Intel i5 3570k, 16gb ram
* Version used: Gephi 0.9.2
* Java version: openjdk 8
* Operating System: Linux Mint 18.2 (with latest updates)

Gephi log file:
-------------------------------------------------------------------------------
>Log Session: Saturday, September 30, 2017 3:48:11 PM BST
>System Info: 
  Product Version         = Gephi 0.9.2 201709241107
  Operating System        = Linux version 4.11.12-xanmod16 running on amd64
  Java; VM; Vendor        = 1.8.0_131; OpenJDK 64-Bit Server VM 25.131-b11; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 1.8.0_131-8u131-b11-2ubuntu1.16.04.3ppa1-b11
  Java Home               = /usr/lib/jvm/java-8-openjdk-amd64/jre
  System Locale; Encoding = en_GB (gephi); UTF-8
  Home Directory          = /home/
  Current Directory       = /home/xxx/gephi-0.9.2/bin
  User Directory          = /home/xxx/.gephi/0.9.2/dev
  Cache Directory         = /home/xxx/.gephi/0.9.2/dev/var/cache
  Installation            = /home/xxx/gephi-0.9.2/platform
                            /home/xxx/gephi-0.9.2/gephi
                            /home/xxx/gephi-0.9.2/platform
  Boot & Ext. Classpath   = /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar
  Application Classpath   = /home/xxx/gephi-0.9.2/platform/lib/boot.jar:/home/xxx/gephi-0.9.2/platform/lib/org-openide-modules.jar:/home/xxx/gephi-0.9.2/platform/lib/org-openide-util.jar:/home/xxx/gephi-0.9.2/platform/lib/org-openide-util-lookup.jar:/home/xxx/gephi-0.9.2/platform/lib/org-openide-util-ui.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ar_SA.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_bg.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ca.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_cs.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_de.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_es.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_fr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_in_ID.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_it.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ja.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ko.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_pl.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_pt_PT.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ro.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_ru.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_si.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_sq.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_sv.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_tr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/boot_zh_TW.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_bg.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ca.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_cs.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_de.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_es.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_fr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_in_ID.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_it.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ja.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ko.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_pl.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ro.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_ru.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_si.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_sq.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_sv.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_tr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ar_SA.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_bg.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ca.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_cs.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_de.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_es.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_fr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_in_ID.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_it.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ja.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ko.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_de.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_es.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_it.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_si.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_pl.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_pt_PT.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ro.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_ru.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_si.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_sq.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_sv.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_tr.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-ui_ja.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-ui_ru.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/dt.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
  Startup Classpath       = /home/xxx/gephi-0.9.2/platform/core/core-base.jar:/home/xxx/gephi-0.9.2/platform/core/asm-all-5.0.1.jar:/home/xxx/gephi-0.9.2/platform/core/org-openide-filesystems.jar:/home/xxx/gephi-0.9.2/platform/core/org-netbeans-libs-asm.jar:/home/xxx/gephi-0.9.2/platform/core/core.jar:/home/xxx/gephi-0.9.2/platform/core/org-openide-filesystems-compat8.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ca.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ro.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_pt_PT.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems-compat8_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_bg.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_it.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core-base_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_fr.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_sv.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ja.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_si.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_sq.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_sv.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ar_SA.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core-base_ja.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_in_ID.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-netbeans-libs-asm_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_tr.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_bg.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core-base_ru.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_zh_CN.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ro.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ru.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_tr.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ar_SA.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_it.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_pl.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ko.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_de.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_fr.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_nl_NL.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_cs.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems-compat8_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_sq.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_es.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems-compat8_ja.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_si.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-netbeans-libs-asm_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_pt_PT.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core-base_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ja.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_zh_TW.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_de.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_pl.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-netbeans-libs-asm_ja.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems-compat8_ru.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_in_ID.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_cs.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_ko.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_pt_BR.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ru.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_es.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_gl_ES.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-openide-filesystems_ca.jar:/home/xxx/gephi-0.9.2/platform/core/locale/core_zh_TW.jar:/home/xxx/gephi-0.9.2/platform/core/locale/org-netbeans-libs-asm_ru.jar:/home/xxx/gephi-0.9.2/gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
WARNING [null]: Last record repeated again.
java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 
	at com.jogamp.opengl.GLProfile.computeProfileMap(GLProfile.java:2071)
	at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1954)
	at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1842)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at org.gephi.visualization.Installer.restored(Installer.java:55)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:436)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:420)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:440)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eduramiba** [comment]
It seems your graphic card drivers are broken. Please try with latest mesa drivers (even beta) or force software rendering.

**Comment by scheckley** [comment]
apologies, yes - local problem due to podako ati drivers. clean OS install has solved it. thanks for the quick response and help.

**Comment by uguerrero** [comment]
I'm using latest mesa driver and Linux Mint 18.3
I use a workaround because it seems that gephi only support version 1.30 of GLSL
I use the following environment variable when starting gephi:
`MESA_GLSL_VERSION_OVERRIDE=130 ./bin/gephi`
thanks to @oddish2211 [original](https://github.com/winder/Universal-G-Code-Sender/issues/795#issuecomment-345505387)
