### ISSUE TITLE
Cannot install Gephi for Windows 

### ISSUE THREAD

**Issue by RobJouvenaar** [gephi/gephi#1804]
## Expected Behavior
Flawless install
## Current Behavior
Error: java cannot find 1.8 or higher

## Steps to Reproduce
Have installed Java 1.8. Re-installed Gephi, Turned Off/on ect. 
After start Gehpi: java error...

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: Win10

**Comment by eduramiba** [comment]
Duplicate of #1787
