### ISSUE TITLE
Timeline Settings Missing

### ISSUE THREAD

**Issue by bhughesshelton** [gephi/gephi#1807]
## Expected Behavior
There should be a cogwheel button to adjust settings for timeline animation.
## Current Behavior
The cogwheel timeline animation button does not appear.
## Steps to Reproduce

1. Load dynamic graph from .gephi file, or generate dynamic graph example
2. Enable Timeline
3.  [Screenshot:](https://i.imgur.com/aYaolGa.png)
4.

## Context

Animations play a bit too fast to make any sense of them. 
## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_131
* Operating System: Linux Mint 18.1 Serena

**Comment by eduramiba** [comment]
That's strange, there is a settings button for that but it seems it's not fitting in your window system or something.

**Comment by bhughesshelton** [comment]
Thanks for the reply. That was my first thought as well, as I've noticed some unusual window behavior before, but neither shrinking the window, nor setting it to fullscreen makes the button apprear. I will try to replicate on another machine, but all my computers are on Mint 18.1.

**Comment by eduramiba** [comment]
In my experience swing implementation in some Linux window systems often uses too much width or height, making elements disappear. Maybe we should add more margin.

Please report if you can fix It.

**Comment by bhughesshelton** [comment]
Tested on other machines all running Mint 18.1, and confirmed the same behavior across all. Settings button does appear running in Windows VM. As much as I'd like to help, I'm sorry to say that my Java skills are too poor to assist with a fix.

**Comment by eduramiba** [comment]
I will try adding some margin and report back with a test build for you.

**Comment by vitorhorta** [comment]
Any updates on this issue? I'm facing the same behaviour here. No settings button :(

**Comment by eduramiba** [comment]
Not yet sorry

**Comment by bhughesshelton** [comment]
The button is actually there, it's just really small and difficult to see. If you hover over the area, it will appear as a tiny lighter grey bar. See [this image](https://imgur.com/jlQcgr1)

**Comment by mbastian** [comment]
In the upcoming 0.9.3 release we're using the [FlatLaf](https://www.formdev.com/flatlaf/) as default so I think this issue should be fixed as well. You can already try it out via the nighly builds and let me know if the problem persiste.
• [gephi-0.9.3-SNAPSHOT-linux.tar.gz](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=linux&p=tar.gz) (Linux)
