### ISSUE TITLE
Access denied?

### ISSUE THREAD

**Issue by arnoutponsioen** [gephi/gephi#1808]
## Expected Behavior
Saving a new or adjusted gephi file, or exporting in PNG/PDF 

## Current Behavior
While saving, I get an error: access denied
This error occured since I upgraded tot 0.9.2
When installing new version of gephi, I found the same 'access denied' error (see included screenshot).
![knipsel](https://user-images.githubusercontent.com/17899995/31175505-c0b0e6ba-a90f-11e7-87a9-c9d0c10c440b.PNG)

## Possible Solution
Tried to downgrade to 0.9.1 and installed linux version tar.gz on desktop. Same error...

## Steps to Reproduce
1. create new file
2. save or export PNG/PDF
3. error: access denied

## Context

Try to save gephi-files, but can't do that anymore. Same error every time.

## Your Environment
* Version used: Gephi 0.9.2
* Java version: 8 update 121
* Operating System: Windows 10

**Comment by eduramiba** [comment]
You might also have some broken antivirus, please try to disable It.

**Comment by eduramiba** [comment]
Did it work?

**Comment by arnoutponsioen** [comment]
Hi Eduardo. That seems to be the solution. I added gephi.exe to be trusted, and then it worked fine!

**Comment by eduramiba** [comment]
Great!
