### ISSUE TITLE
CSV files are no longer imported correctly when double quotes inside strings are delimited with backslashes

### ISSUE THREAD

**Issue by bjoernross** [gephi/gephi#1812]
## Expected Behavior
Gephi 0.9.2 should be able to import CSV files in which double quotes inside strings are escaped with backslashes (see below for an example). This worked in 0.9.1 but no longer does.

Also, an error message should be shown when an IOException occurs while reading a CSV file.

## Current Behavior
Since 0.9.2, CSV files are only imported correctly when double quotes inside strings are escaped with double quotes. When another character is used, the import fails, beginning with the first line to contain the escaped quotes.

No error message is shown. The rest of the file is simply ignored. This means that when importing a file with 100,000 edges you may end up with 10,000 and not know why.

## Possible Solution

When importing a CSV file, let the user set the escape character, just like the user can currently set the field delimiter, or auto-detect. 

[Pass this parameter](https://github.com/gephi/gephi/blob/0.9.2/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/spreadsheet/SpreadsheetUtils.java) to CSVFormat’s withEscape function.

## Steps to Reproduce

1. Create a file with the following content:
```
 "Source";"Target"
 "Dwayne \"The Rock\" Johnson";"John Cena"
```
2. Data Laboratory -> Import Speadsheet -> Select File, import as Edges List
3. No data is shown in the preview. After clicking 'Finish' Gephi reports a successful import of zero edges and zero nodes.

## Context
In CSV files, some people escape quotes inside strings with backslashes (see above). Some people escape them with double quotes:

```
 "Source";"Target"
 "Dwayne ""The Rock"" Johnson";"John Cena"
```

Gephi 0.9.1 expected the former; Gephi 0.9.2 expects the latter (as does Excel). I haven't seen this change documented anywhere. It means that, for example, some scripts written for older versions of Gephi that produce CSV files for import into Gephi are now broken.

## Your Environment

* Version used: Gephi 0.9.2
* OS: I have tested this on macOS and Windows.

Relevant part of `messages.log`:
```
SEVERE: IOException reading next record: java.io.IOException: (line 2) invalid char between encapsulated token and delimiter
SEVERE [null]: Last record repeated 4 more times.
INFO [DefaultProcessor]: # Nodes loaded: 0
INFO [DefaultProcessor]: # Edges loaded: 0
```

**Comment by eduramiba** [comment]
Thanks for the report!

**Comment by bjoernross** [comment]
It looks like if you simply [pass the backslash as an escape character](https://github.com/bjoernross/gephi/commit/9f154acbd3f5cb1987abf459c33e42cbf91293c0), both examples will work. So this might actually already be the solution for my use case.

Of course, the separate issue remains that the user should always be notified if something goes wrong during import.

**Comment by eduramiba** [comment]
Yeah I think I will do that, to not over-complicate the GUI.

**Comment by eduramiba** [comment]
Fix commited, please try with 0.9.3-SNAPSHOT when the travis job ends https://travis-ci.org/gephi/gephi/builds/285083055

**Comment by bjoernross** [comment]
Works great! Thank you.

**Comment by eduramiba** [comment]
Great! This will be part of future in-app updates of Gephi 0.9.2
