### ISSUE TITLE
Import CSV Edgelist

### ISSUE THREAD

**Issue by rschroedy** [gephi/gephi#1814]
## Expected Behavior

Import CSV edgelist into blank network with edges containing names.

## Current Behavior

It tells me I need to have a column named 'Source' and 'Target' filled with node ids.

## Possible Solution

Hopefully I don't have to use just numbers for node id's. In the past it has been able to figure it out on it's own.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 144
* Operating System: OS X El Capitan 10.11.6

The file I uploaded is my csv saved as a txt because I cannot upload a csv file into github.
[test.txt](https://github.com/gephi/gephi/files/1373644/test.txt)

**Comment by eduramiba** [comment]
Hi,
Your file contains the BOM (byte order mark) at the beginning of it, which adds some non-printable characters to `Source` column and it looks like `Source` but is not.

You should remove it with an editor like notepad++.

How are you creating this file?

This seems to be a common issue with users in Gephi now, we will need to add some logic to the parser so it does not fail with a BOM. I created an issue for this #1815

**Comment by eduramiba** [comment]
Example of fixed file: 
[test.txt](https://github.com/gephi/gephi/files/1374442/test.txt)

**Comment by rschroedy** [comment]
I saved it using Mac's Excel "CSV UTF-8 (Comma delimited) (.csv)" format in the Common Format section. But if you save it just as "Comma Separated Values (.csv)" in the Specialty Format section it looks as though it isn't with BOM. So I'll do that from now on.
