### ISSUE TITLE
无法在同一个工作区添加点和边的电子表格

### ISSUE THREAD

**Issue by debrali** [gephi/gephi#1818]
## Expected Behavior
希望在同一个工作区添加点和边的电子表格
## Current Behavior
在输入点的电子表格后，再输入边的电子表格，会自动添加到一个新的工作区中，而不是原来的工作区
## Possible Solution
之前的版本都是正常的，看来是新版本的bug

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Please report issues in english
