### ISSUE TITLE
Preview node rendering problems

### ISSUE THREAD

**Issue by jgosmann** [gephi/gephi#1820]
## Expected Behavior
The preview properly renders the graph.

## Current Behavior
Some nodes are rendered as giant filled circles or polygons. Screenshot:
![spectacle lh5134](https://user-images.githubusercontent.com/850157/31512638-af98fc6e-af59-11e7-93f6-6bb460708f65.png)

## Steps to Reproduce

I can provide the gephi-file for which that occurs, but GitHub won't let met attach it.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: jre1.8.0_144
* Operating System: [Chakra OS](https://chakralinux.org/) (similar to Arch linux), kernel 4.12.4-1-CHAKRA

[messages.log](https://github.com/gephi/gephi/files/1380304/messages.log)

**Comment by eduramiba** [comment]
You must have some very disproportionate weights, try to enable rescale weights option in preview.

**Comment by jgosmann** [comment]
Thanks you, that fixed the problem! 😄

**Comment by eduramiba** [comment]
Great!
