### ISSUE TITLE
Can't build a dynamic graph from several sequence numbered files

### ISSUE THREAD

**Issue by Brandonage** [gephi/gephi#1824]
## Expected Behavior

Trying to import a set of sequence numbered gephx files in order to build a dynamic graph. There should be a button to import these several graphs into a dynamic graph according to https://github.com/gephi/gephi/wiki/Import-Dynamic-Data#use-time-frame-import-with-several-static-files

## Current Behavior

I can't see the button anywhere

## Possible Solution

This is more a request for guidance than a bug or an issue. I might be doing something wrong or what I'm trying to achieve is not possible 

## Steps to Reproduce

- I go to File -> Open and I select all the files and open them like in the open.png attachment
![open](https://user-images.githubusercontent.com/12024997/31820415-83488ad2-b5a1-11e7-8949-51b9921ea092.png)

- This opens a window like in the import_report.png attachment. It doesn't seem to detect that it's a dynamic graph as seen in the import_report attachment below.
![import_report](https://user-images.githubusercontent.com/12024997/31820419-87e28e6c-b5a1-11e7-8a6b-a714349ee75e.png)

## Context

Trying to import a set of sequence numbered gephx files in order to build a dynamic graph that allow me to see how the network evolves

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_131
* Operating System: Mac OS X El Capitan

**Comment by eduramiba** [comment]
Hi,
This is not the way to do it since 0.9.0. Check https://github.com/gephi/gephi/issues/1546
In summary: your gexf files have to provide the timestamp and then import all files and choose 'Merge into new workspace'
