### ISSUE TITLE
Dynamic Edge Values are not taken into Consideration for Layout by Force Layout, Force Layout 2 and FruRein

### ISSUE THREAD

**Issue by jdsalaro** [gephi/gephi#1829]
Force Layout, Force Layout 2 and FruRein do not take dynamic edge values into consideration for force/repulsion calculations when using intervals, this isn't the case when using timestamps.  

Acording to @eduramiba, the weight is calculated differently for the visualization using intervals:
https://github.com/gephi/gephi/blob/2b9a7c8eed39ec43017639dbbb44175cbd953572/modules/VisualizationImpl/src/main/java/org/gephi/visualization/bridge/DataBridge.java#L246

[samples.zip](https://github.com/gephi/gephi/files/1423586/samples.zip)

However, when using timestamps, all three algorithms work as expected. 
Here's a working example:

https://streamable.com/4bzij

Here one can see that for intervals, the edge weights are not considered for force calculation:

FruRein: https://streamable.com/zzgdm
ForceAtlas2: https://streamable.com/osvku
ForceAtlas: https://streamable.com/6mg62

**Comment by eduramiba** [comment]
Thanks for the report!

**Comment by mbastian** [comment]
Thanks, according to the current code and the 0.9.2 release this should wok just fine with both intervals and timestamp supported. If that's still an issue for you, please reopen. Thanks

Also note that FruRein doesn't not support edge weights at all.
