### ISSUE TITLE
Is it possible to export a graph from Gephi to orientDB ? 

### ISSUE THREAD

**Issue by invokerk** [gephi/gephi#1830]
This is not an issue, it's more like a query : 
I'm new to gephi and orientdb and I would like some advice about the below task.

Currently there is a way to stream the orientDB graph into Gephi (using a plugin) but is there a way by which I can export a graph ( created via Gephi or by importing a CSV file into gephi) to orientDB ?

My environment:
-----------------
* Version used: Gephi 0.9.2
* Java version: 8_151
* Operating System: Ubuntu 16.04
* orientdb: 2.2.29 community version

Any advice is much appreciated.

**Comment by eduramiba** [comment]
I think spreadsheet export could work with http://orientdb.com/docs/last/Import-from-CSV-to-a-Graph.html

**Comment by invokerk** [comment]
Yeah, I found that this was the only way. Thanks !
