### ISSUE TITLE
I cannot install Gephi!!!!

### ISSUE THREAD

**Issue by ChristianEskelundHansen** [gephi/gephi#1833]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
You will need to be more specific

**Comment by ChristianEskelundHansen** [comment]
When I try to install Gephi 0.9.2. for Windows - due to a big task I have - everytime the program refuses to launch and states "cannot find Java 1.8. or higher". But I have just installed the latest version of Java!!!

**Comment by eduramiba** [comment]
Oh I see, check issue #1787
