### ISSUE TITLE
com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice

### ISSUE THREAD

**Issue by dragonxtek** [gephi/gephi#1836]
## Expected Behavior
Gephi should show the graph
## Current Behavior
When I run gephi a warning window appears:
![unexpected exception_318](https://user-images.githubusercontent.com/10552658/32568472-1a2d71d8-c49d-11e7-94e2-bf626c1704a3.png)
The message.log is the following:

> com.jogamp.opengl.GLException: Profile GL2 is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x3bc32701, isOwner false, <79f70ffe, 1507ffab>[count 0, qsz 0, owner <NULL>]]], but: []

Graph tab freeze in "Initializing..." message and doesn't show the graph
![selection_317](https://user-images.githubusercontent.com/10552658/32568447-091dcbae-c49d-11e7-98e6-37217cd38357.png)

## Possible Solution
I tried run gephi with java 8, 9 and opensdk 8 without luck.

## Steps to Reproduce

1. Run gephi 
2. I have dual screen (I read that it appear only on dual screen on linux)

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 and 9
* Operating System: Ubuntu 16.04

**Comment by eduramiba** [comment]
I suggest you use latest Mesa drivers or force software rendering with env variable `LIBGL_ALWAYS_SOFTWARE=1`

**Comment by dragonxtek** [comment]
I used: 

> export LIBGL_ALWAYS_SOFTWARE=1 

and I have the same issue after execute gephi

**Comment by eduramiba** [comment]
Do the gephi logs regarding opengl change if you use that line or not? Maybe it's not using software rendering if nvidia drivers are in use.

**Comment by dragonxtek** [comment]
I fixed the issue!
Was a problem with nvidia drivers. I was searching by opengl compatibility and when I tried to execute glxgears I had this problem:
`X Error of failed request: BadValue (integer parameter out of range for operation)`
To solve it, is recommended upgrade nvidia drivers
Now I have Nvidia driver 384.90

![selection_335](https://user-images.githubusercontent.com/10552658/33187838-8219dce6-d073-11e7-964a-4d376c60fe10.png)

**Comment by eduramiba** [comment]
Great!

**Comment by packmad** [comment]
I have fixed it with:
```
$ export MESA_LOADER_DRIVER_OVERRIDE=i965
$ ./gephi
```

**Comment by stheid** [comment]
However, i would consider that a workaround and not fixed.

**Comment by sgrubsmyon** [comment]
I'd like to add: I have this issue on a Toshiba Portégé laptop with Intel Corporation UHD Graphics 620 (rev 21) graphics card running an up-to-date Arch (Manjaro) linux with `libva-intel-driver` installed, glxgears running just fine. Hardware video acceleration works, as confirmed by running `mpv --hwdec=auto <video_filename>` (see https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Verification).

Using
```
$ export MESA_LOADER_DRIVER_OVERRIDE=i965
$ ./gephi
```

or 

```
$ MESA_LOADER_DRIVER_OVERRIDE=i965 ./gephi
```

makes it work, but is not very intuitive.

**Comment by packmad** [comment]
> However, i would consider that a workaround and not fixed.

If it works, it is fixed  😂

**Comment by stheid** [comment]
It does not work. it only works if you google it and find this issue which tells you which magic environment variables you have to set when you execute it from the console. It does not work out-of-the-box.

**Comment by packmad** [comment]
> It does not work. it only works if you google it and find this issue which tells you which magic environment variables you have to set when you execute it from the console. It does not work out-of-the-box.

Yes man, that was irony... why so serious?
