### ISSUE TITLE
Regression setting node color by partition

### ISSUE THREAD

**Issue by fungs** [gephi/gephi#1838]
When nodes are colored based on a set of different strings in a column, there should be an option how to treat empty strings (missing values). I usually set them to gray, depending on the color scheme.

## Expected Behavior

In 0.9.1, the empty string would appear as an option for manual color selection.

## Current Behavior

In 0.9.2 nodes are colored simply black. No option to change this anyhow (other than setting a pseudo-value in the table cells).

## Possible Solution

The solution in 0.9.1 worked but even better would be a general option to set the color for empty tables because you have to reset this value for every attribute manually.

## Steps to Reproduce

1. Load a node table with a colum with values "a", "b" and ""
2. Color nodes by rank with any palette

## Context

I have to go back to 0.9.1 for coloring my graphs.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java version "1.8.0_151", Java(TM) SE Runtime Environment (build 1.8.0_151-b12), Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
* Operating System: Linux 64bit

**Comment by mbastian** [comment]
Thank you for the report, the fix will be included in the upcoming 0.9.3 release. The Appearance module will offer a button to turn on/off using missing values.
