### ISSUE TITLE
Gephi plugin - Make changes to labels visible

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1842]
## Expected Behavior
I am currently writing a plugin for Gephi. Gephi is integrated into NetBeans as a platform.
In this plugin changes should be made in the labels of the nodes and then made visible under Overview -> Nodes -> Partition -> Select Attributes in the graph.

## Current Behavior
After the plugin has been executed, the changes to the labels are visible in Data Lab. 
But in the Overwiew there is no way to assign a specific color or size to the node of the label, depending on the changed labels.

## Possible Solution

Did I forget anything in the implementation?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: JDK 8
* Operating System: NetBeans 8.2

**Comment by eduramiba** [comment]
Hi,
I think you can change the visualization attributes of labels with `node.getTextProperties()`. See https://gephi.org/graphstore/apidocs/index.html

Anyway, what do you mean Gephi is integrated in Netbeans? For making a plugin you should follow this simple process explained here: https://github.com/gephi/gephi-plugins

**Comment by MK2345** [comment]
Thank you for the quick answer.
Gephi is integrated as an platform in NetBeans.
I have change the labels with node.setLabel(....).
Now I tried to insert a column in the nodeTable, which is also displayed in Gephi, but the new values of
the labels will not be entered there.

**Comment by eduramiba** [comment]
Can you share your code?

**Comment by MK2345** [comment]
The code should not be visible on the Internet because it is a University project.
Key parts of the code would be:


public void execute(GraphModel graphModel){

     Graph graph = graph.Model.getGraph();

     Node[] nodes = graph.getNodes().toArray();

      ...

     boolean changed = true;

     while(changed){

          for (Node n: nodes){ .... n.setLabel(rando);

 
     //here should be a method() to check the graph if a change of the labels occured
 





 

Gesendet: Mittwoch, 15. November 2017 um 13:39 Uhr
Von: "Eduardo Ramos" <notifications@github.com>
An: gephi/gephi <gephi@noreply.github.com>
Cc: MK2345 <lapsus4@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [gephi/gephi] Gephi plugin - Make changes to labels visible (#1842)
Can you share your code?

**Comment by eduramiba** [comment]
The overview automatically shows the current label by default, you don't have to do anything for it to show the correct value after you do a `setLabel`

I am really trying to understand what you are trying to do but I don't get the problem. Also, why Gephi as a platform in Netbeans? I am not even sure that will work fine and is not the intended use case of Gephi.

By looking at #1844, if what you are trying to do is show a custom column as the label in overview, then either simply configure overview to show that column as the node text (can be done in overview settings panel (small button at the down-right corner), or listen to changes in a column with a column observer (check example code in data laboratory used for refreshing the table when column values change https://github.com/gephi/gephi/blob/master/modules/DesktopDataLaboratory/src/main/java/org/gephi/desktop/datalab/DataTablesObservers.java)

**Comment by MK2345** [comment]
ok, in the code changes on the labels are to be made.  Here I have a while loop in which  after each iteration by the for loop is to  check whether changes were made to the labels. The change of the labels does happen by an algorithm which called label propagation, which is used to discover communities. In this algorithm, the labels are changing. Only when all communities have been discovered, the labels are not changed further. Here then the termination of the while loop would have to be done. I would like to do this by comparing the graph with its state before the last iteration through the loop. If no change has occurred to the graph (labels), the while loop should be aborted.

**Comment by eduramiba** [comment]
Then, probably this line is what you need: https://github.com/gephi/gephi/blob/master/modules/DesktopDataLaboratory/src/main/java/org/gephi/desktop/datalab/DataTablesObservers.java#L135

**Comment by MK2345** [comment]
Thank you very much, but in the closed #1844 I hoped for another possibility, because this seemed a bit complicted. 
Ok, how do I program this? I tried that, but it does not work for me. My Code is as follows

public void execute(GraphMode graphModel){
      Table nodeTable = graphModel.getNodeTable();

      Column col = nodeTable.getColumn(prob);
      if (col == null) {
         col = nodeTable.addColumn(prob, String.class);
      }
      // I think a have to set here the ColumnObserver, but how do I do that?

     while(change) {
           for(Node n : nodes){
                  .......
           } //end of for loop. Here I have to test if something has changed 

Could you help me again?

**Comment by MK2345** [comment]
ok, on the first position in the code above I set:
ColumnObserver observer = col.createColumnObserver(true);

On the second position in the code above I have set:
if (observer.hasColumnChanged()){
   change = true;
}else{
   change = false;
}

But the while loop doesn't stop. What could be the reason.

**Comment by eduramiba** [comment]
Well, your while loop always evaluates to true unless you change `changed` variable inside the loop.

**Comment by MK2345** [comment]
change changed inside the while loop but outside the for loop. That should be right.

**Comment by eduramiba** [comment]
Sorry but you will need to debug your code, it's doing an infinite loop, and that has nothing to do with the observer. Checking the observer outside the loop does not make any sense for your use case.

**Comment by eduramiba** [comment]
Closing as not an issue with Gephi but a coding question instead.

**Comment by eduramiba** [comment]
Closing as not an issue with Gephi but a coding question instead.
