### ISSUE TITLE
Visualising labels of Nodes

### ISSUE THREAD

**Issue by jlminel** [gephi/gephi#1843]
## Expected Behavior
After uploading nodes and edges, vizualize a graph with labels nodes

## Current Behavior
Uploading a nodes file with Label. fine.
Uploading a edges file. Fine
But when I return back in the nodes table, all the labels of nodes vanished. It stays only the Id nodes

## Steps to Reproduce

1.
2.
3.
4.

## Context

To buils a graph
## Your Environment

* Version used: Gephi 0.9.2
* Java version:  8
* Operating System: 
Windows 7

**Comment by jlminel** [comment]
Sorry, I just read the https://gephi.wordpress.com/2017/09/26/gephi-0-9-2-a-new-csv-importer/, so it works fine fine with an Append workspace
best

**Comment by eduramiba** [comment]
Make sure to select append to existing workspace, otherwise you are creating a new workspace.

**Comment by eduramiba** [comment]
Right :)
