### ISSUE TITLE
Gephi Plugin

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1844]
## Expected Behavior
I am currently writing a plugin for Gephi.  I'm looking for a way to check the graph if a change has occurred, e.g. regarding the labels. If possible without using the "observer" and the "hasGraphChanged()" method. Does anyone have a tip? Unfortunately, I am a beginner in working with plugins and Gephi.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by MK2345** [comment]
Key parts of the code would be:

public void execute(GraphModel graphModel){
     Graph graph = graph.Model.getGraph();
     Node[] nodes = graph.getNodes().toArray();
      ...
     boolean changed = true;
     while(changed){
          for (Node n: nodes){ .... n.setLabel(rando);
 
     //here should be a method() to check the graph if a change of the labels occured

**Comment by eduramiba** [comment]
Closing this and keeping the conversation in #1842
