### ISSUE TITLE
query the content of a column

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1845]
## Expected Behavior
I am writing a plugin for Gephi. Is there a way to query the contents of a special column in the table?
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Check
https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/Node.html ---> https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/Element.html#getAttribute-org.gephi.graph.api.Column-

**Comment by eduramiba** [comment]
Also, https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/GraphModel.html#getNodeTable-- for example

**Comment by eduramiba** [comment]
Closing as answered #1846
