### ISSUE TITLE
How to get node attribute values?

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1846]
## Expected Behavior
node.getAttribute("Number")
would return the integer to node's Number attribute. 

## Current Behavior
The return type of Node's getAttribute methode is Object. This Object can't be casted to integer
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
Columns do have a type, but it's dynamic ([and stated when creating the column](https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/Table.html#addColumn-java.lang.String-java.lang.Class-)).
So, when you create a column with Integer.class type, then you can safely cast values returned by `getAttribute()` to `Integer` (NOT `int`, unless you are sure the value is never null).

Examples of usage here: https://github.com/gephi/gephi/blob/master/modules/DataLaboratoryAPI/src/main/java/org/gephi/datalab/impl/AttributeColumnsControllerImpl.java

**Comment by MK2345** [comment]
Thank you
