### ISSUE TITLE
Arrange panels in Gephi

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1847]
## Expected Behavior
I wrote a plugin for Gephi. When I start Gephi and click on one of the panels, then the panel of statistics narrows and the panel of partition and ranking gets bigger.  
## Possible Solution
I assume that there is a way to change it in the UI (User Interface), but I don't know how. Does anyone have a hint?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Not sure what you mean, can you show a screenshot?

**Comment by MK2345** [comment]
![screenshot2](https://user-images.githubusercontent.com/24621381/32943887-e8bb36b0-cb8d-11e7-8ebd-d944de0c4d58.PNG)

**Comment by eduramiba** [comment]
You should be able to resize each panel to whatever size you need. Also try Window menu - reset windows

**Comment by MK2345** [comment]
When I reset the window, it is even worse. 
![screenshot3](https://user-images.githubusercontent.com/24621381/32944339-8621aed8-cb8f-11e7-8e83-c61cf640cd4f.PNG)


Wenn I start Gephi everything looks normal as usual, only when I click in, then the panels are moved.

**Comment by MK2345** [comment]
I think there must be a way to arrange the panels in the code I wrote.

**Comment by eduramiba** [comment]
The layout of standard panels is coded in modes, wich are used by TopComponents: https://github.com/gephi/gephi/tree/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/DesktopBranding/src/main/resources/org/gephi/branding/desktop
https://github.com/gephi/gephi/blob/297792defceaf86e07bb4668c06ec2f3b0ac08a3/modules/DesktopAppearance/src/main/java/org/gephi/desktop/appearance/AppearanceTopComponent.java#L79

Anyway, please try to follow the supported way of coding plugins and running them: https://github.com/gephi/gephi-plugins#run-gephi-with-plugin

I still don't know why or how you code your plugin using Gephi as a Netbeans platform, but we can't give support to that as it's not the intended use.
