### ISSUE TITLE
Cannot find Java 1.8 or higher

### ISSUE THREAD

**Issue by jcatumba** [gephi/gephi#1849]
## Expected Behavior
Software open without errors.

## Current Behavior
Window appears with the message "Cannot find Java 1.8 or higher".

## Steps to Reproduce
1. Open Gephi Windows

* Version used: Gephi 0.9.2
* Java version: Version 8 Update 151 (Compilation 1.8.0_151-b12)
* Operating System: Windows 8.1 Pro N

![gephierror](https://user-images.githubusercontent.com/1387668/32970959-25adad02-cbb9-11e7-8ba5-7c0f42324277.PNG)

**Comment by eduramiba** [comment]
Duplicate of #1787
