### ISSUE TITLE
determine the edge type of an edge

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1850]
## Expected Behavior
If I want to determine the edge type of an edge. Which integer number corresponds to a non-directional, which of a directed edge, when I use graph.getEdges(....,....).
Unfortunately I can not take that from the documentation.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
You can use edge.isDirected()

**Comment by MK2345** [comment]
Yes, thank you. But if I wanted to determine all directed edges starting from a certain node n, I would like to use graph.getEdges(n,    Integer number) to determine only the directed edges. I think this would be easier.
Because there are also nodes with many edges.

**Comment by eduramiba** [comment]
Hi, that gephi integer is for the edge type/kind, not for directedness. So you need to use isDirected

**Comment by MK2345** [comment]
ok, Thank you
