### ISSUE TITLE
Gephi 0.9.2 hangs in Welcome screen

### ISSUE THREAD

**Issue by dstefane** [gephi/gephi#1851]
## Current Behavior
After starting Gephi 0.9.2 it shows the Welcome dialogue, which cannot be closed. Also no item within the Welcome dialogue can be selected. This behaviour occurs no matter if I started Gephi as regular or admin OS user on Windows 7 (64 bit).

## Context

Gephi is unusable

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_102
* Operating System: Windows 7 (64 bit)

**Comment by eduramiba** [comment]
Can you try to update java, your graphics card drivers please?
Also attach gephi logs: https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by dstefane** [comment]
Hi, I have updated to latest Java 8 (64 bit) on Windows 7 (64 bit), but the problem remains. See logs attached.
 

Gesendet: Donnerstag, 23. November 2017 um 13:13 Uhr
Von: "Eduardo Ramos" <notifications@github.com>
An: gephi/gephi <gephi@noreply.github.com>
Cc: dstefane <dstefane@web.de>, Author <author@noreply.github.com>
Betreff: Re: [gephi/gephi] Gephi 0.9.2 hangs in Welcome screen (#1851)


Can you try to update java, your graphics card drivers please?
Also attach gephi logs: https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by eduramiba** [comment]
Hi,
You will need to attach logs in github. Also make sure about drivers, they are a typical cause of problems.

**Comment by dstefane** [comment]
[messages.log](https://github.com/gephi/gephi/files/1499655/messages.log)
[messages.log](https://github.com/gephi/gephi/files/1499657/messages.log)

**Comment by eduramiba** [comment]
It stops right after opengl info is logged, did you check the drivers at http://www.nvidia.com/object/nvs-310-graphics-card.html ?

**Comment by dstefane** [comment]
Hi, I have updated the NVIDIA drivers now to the latest version (22.21.13.8590 from October, 3oth 2017), but the problem is kind of the same. I can close the welcome screen, but when I choose a menu, e.g. tools, then gephi freezes and I cannot even close it. I have to use task manager to kill the process. As I said, similar as before. See attached log.
[messages.log](https://github.com/gephi/gephi/files/1499716/messages.log)

**Comment by eduramiba** [comment]
Too bad! Maybe it does not support OpenGL 2 or something... Actually I am working on a new version of our OpenGL engine to modernize it.

But until it is released (will probably take months), I suggest you run Gephi in a virtual machine or try another graphics card or computer.

**Comment by dstefane** [comment]
Well, I am not sure that this is related to the graphics card. Looks more like a permission problem to me.
I do not (and will not) have another graphics card to try.

**Comment by dragonxtek** [comment]
I have another issue with OpenGL 2 in linux and I have a GeForce GTX 950 with driver version 375.66. Please check the issue https://github.com/gephi/gephi/issues/1836

**Comment by dstefane** [comment]
Hi, i installed Gephi 0.9.2 now on another computer (Lenovo T430 Laptop (Intel HD graphics 4000), Windows 7, 32 bit) after I had updated Java (1.8.0_151) and graphics driver to the latest version (10.18.10.4491). The problem is the exact same like on my other workstation described before, i.e. Gephi hangs in welcome screen. See log attached. 
[messages.log](https://github.com/gephi/gephi/files/1501841/messages.log)
Any idea?

**Comment by arpicheck** [comment]
Hi,
Gephi 0.9.2 also freezes on my computer, but not always.
Here are my observations:

At start-up modules are loading fine, and then the main UI appears, finally the welcome screen too.
-Now, sometimes, after a while (5-10 secs) an authentication window appears. In this case, a cancel is enough to launch Gephi.
-But in other cases, this authentication windows never appears, and the welcome screen is kept busy.

So, pretty sure, that this thread with graphics drivers is a dead one, or at least not the only one, as Gephi starts sometimes fine.

The first time I'll get the login window again, I'll share, what I can find out about it.

Also, I'd like to mention, that if I erase the cache folder, it helps. (But this one is not acceptable.)

**Comment by arpicheck** [comment]
This (not too talkative) dialog pops up sometimes. 
![arequ](https://user-images.githubusercontent.com/13888766/51020942-5b1af000-1580-11e9-978e-cd25adadd786.png)

What I figured out from the logs is, that this issue might have a connection to auto-update, as the log lacks auto-update related lines, when Gephi freezes.

The missing section of logs starts like this:

WARNING [org.netbeans.core.NbAuthenticator]: No authentication set while requesting https://raw.githubusercontent.com/gephi/gephi/gh-pages/latest
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url

**Comment by eduramiba** [comment]
Yeah I think it may be related to system proxy settings, do you use a proxy?

**Comment by arpicheck** [comment]
Yes, but please, don't forget that sometimes even without erasing my gephi cache Gephi does start up well.

**Comment by arpicheck** [comment]
Also, could you light me up, what does require authentication when the above dialog appears? :)

**Comment by eduramiba** [comment]
As you can see, https://raw.githubusercontent.com/gephi/gephi/gh-pages/latest is completely public. The problem seems to be that Netbeans Platform detects the operative system configure http proxy and wants to use it, but does not have the credentials.

I will try to make this work in that case, as this connection is only for checking for Gephi updates.

**Comment by arpicheck** [comment]
Nice, even if it sounds like a hack :)
By the way! Don't you plan to introduce a switch for auto-update check? (Or is there such a switch somewhere, only I can't find it?)

**Comment by eduramiba** [comment]
Well, once there is a new version, Gephi will inform you and let you enable an option to never check it again. This option only appears in that case, but you can manually disable it by creating a file in your gephi user directory (https://github.com/gephi/gephi/wiki/Troubleshooting):

So, create a file at `C:\Users\your_username\AppData\Roaming\.gephi\0.9.2\dev\config\Preferences\org\gephi\desktop\branding.properties` with the following contents:

```
check_latest_version=false
```

**Comment by arpicheck** [comment]
I'll check it, thanks!

**Comment by arpicheck** [comment]
@eduramiba , regarding the check_latest_version setting you mentioned, it works like a charm. I can get trough the project selection window. Unfortunately, there is still something Gephi tries to check on the net, when I finally start a project, so Gephi gets stuck anyway.

What I can do is that I disable my network -> start Gephi -> start the project -> enable network, which is pretty awkward, in my opinion.

**Comment by arpicheck** [comment]
OK, I've found a workaround.

In the gephi.conf, include (or modify) 
-J-Dplugin.manager.check.interval=NEVER
at the default_options.

Although, I don't know if NEVER is a good value, or just causes a fallback to default, but seemingly it does work for me.

**Comment by matangi2020** [comment]
> I was able to fix the issue by removing the non-windows files in C:\Program Files\Gephi-0.9.2\gephi\modules\ext\org.gephi.visualization\org-jogamp-jogl.

This worked for me.

**Comment by mbastian** [comment]
I've reviewed this thread and the topics is a mixed big of common startup problems like OpenGL drivers and network connection issues (proxies). I suggest to try again with the most recent Gephi version (0.9.4) and see if the problems persist. If you don't mind, please create new issue.
