### ISSUE TITLE
Modularity of network with two communities

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1852]
## Current Behavior
Hello, 
I have an undirected network with nodes A, B, C, D, E and edges A-B, A-C, B-C, B-D, D-E. Gephi gives a value of 0.22 through the Modularity statistics application.
I used the algorithm without randomizing and without edge weight, only the resolution 1.0.
I received the two communities A, B, C and D, E.
If I try to recalculate the modularity myself, I come to a value of 0.277777777.
Can someone explain to me with which formula the modularity is calculated or how to get the value 0.22?

Thanks in advance
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by MK2345** [comment]
Hello, I have no problems getting the same results because I've already disabled randomization.
I would have been interested in the formula for which the modularity is calculated, since the result differs from my own calculation.

**Comment by eduramiba** [comment]
Oh, this is the code: https://github.com/gephi/gephi/blob/master/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/Modularity.java

Make sure you don't have parallel edges, as their weights will be summed

**Comment by MK2345** [comment]
Thank you very much
