### ISSUE TITLE
Edges CSV not importing 

### ISSUE THREAD

**Issue by Katregner** [gephi/gephi#1855]
## Expected Behaviour
I expect to see the data from the edges spreadsheet (source;target;type) in the Edges tab of the Data Laboratory in Gephi after importing this through the "Import Spreadsheet" function. 

## Current Behaviour 
The imported data does not appear in the 'Edges' tab of the Data Laboratory. While clicking through the 'import spreadsheet' function, everything works as it should e.g. I can see the edges data in the preview and all columns appear to be recognised correctly. The problem occur when clicking 'finish' as nothing happens as a consequence. 

## Suggested Fix/Ideas
I read somewhere online that this may be linked to the CSV file containing hidden **BOM** characters. I got someone to help me remove them but either he didn't remove them correctly (hard to tell, since they're not visible..) or this didn't fix the problem/wasn't what was causing it. 

Also, since I have no problems uploading the nodes CSV (and I created them in the same way that I created the edges CSV), I find it hard to believe that one CSV would have hidden characters and the other one doesn't.  

Oddly, uploading edges CSVs from past projects works fine 90% of the time. I sometimes experience the same behaviour described above for these older files but after trying a couple of times, suddenly the edges appear in the data lab. 

## Your Environment

* Version used: Gephi 0.9.1
* Java version: 
* Operating System: MacOSSierra Version 10.12.6

**Comment by eduramiba** [comment]
Hi,
Please use latest 0.9.2 version, and make sure to install updates after first start of the program (Help - Check for updates)

**Comment by eduramiba** [comment]
Also, 0.9.2 with recent updates supports CSV with BOM without problems, you won't need to remove it.

**Comment by eduramiba** [comment]
Did it work?

**Comment by Katregner** [comment]
Hi Eduardo,

Thanks for your tip. I wasn't aware of there being a newer version. I've
installed it and am still having problems getting the nodes & edges CSVs
into Gephi. Attaching a screenshot of the nodes uploader. I selected
'semicolon' as separator, specified I want to import the data as nodes and
UTF-8 as Chartset. Usually this would show me the data split into distinct
columns in the preview but now it stubbornly remains in the same column.

Any other tips you could give me?

Thanks,
Katharina

**Comment by eduramiba** [comment]
Hi, you will need to attach the screenshot in github. You should probably not change the options at all, as they are autodetected.

**Comment by Katregner** [comment]
Hey Eduardo, 

Using the default import options (comma, adjacent table & UTF-8) hasn't solved it. 

Perhaps if will be helpful if I explain the steps I'm taking to create the nodes & edges CSVs (the import of neither file is working). 

Our starting point is an excel spreadsheet, downloaded from social analytics platform Brandwatch, containing data points for conversations on Twitter (interactions = retweets & replies). The initial spreadsheet contains columns for a heap of metrics of which we are extracting & concatenating the few that we need for the nodes (user ID, Label, Type of author (i.e individual or an organisation), Follower count and an impact metric) and edges (source, target and type of interaction (i.e. retweet or reply). We're using semicolons as separators. 

Once concatenated, we're deleting empty rows and saving the data in two CSV files (nodes, edges). 

Am attaching screenshots for the edges & nodes CSV. 

In Gephi, whichever options I select in the first 'import spreadsheet' screen, the preview never shows that the data has been split into separate columns. Also attaching a screenshot for this using both the default setting and the ones I have been in the past. 

Let me know if you need anything else. 

Thanks, 
Kat 

<img width="532" alt="edges" src="https://user-images.githubusercontent.com/33958909/33423785-23746570-d5ba-11e7-90ca-5bd7941c0dca.png">
<img width="880" alt="nodes" src="https://user-images.githubusercontent.com/33958909/33423786-238e8266-d5ba-11e7-9f22-7c508b5dec05.png">

![import settings used so far](https://user-images.githubusercontent.com/33958909/33423945-a22ac026-d5ba-11e7-824e-c2dc80d805ea.png)
![default import setting](https://user-images.githubusercontent.com/33958909/33423951-a4f083ae-d5ba-11e7-9b0a-8bb5dc85406b.png)

**Comment by Katregner** [comment]
I attached the nodes screenshot twice. Here's the edges one. 

<img width="834" alt="edges" src="https://user-images.githubusercontent.com/33958909/33424045-ec7a2dce-d5ba-11e7-8efb-d05af0164e63.png">

**Comment by eduramiba** [comment]
Are you sure your semicolon characters are standard semicolons? Please review that and attach a sample file zipped

**Comment by Katregner** [comment]
Brilliant, thanks for the tip! I got it to work using commas instead of
semicolons.

I now have another question. It appears that some of the nodes were
imported as type 'null'. This was not one of the type variables I specified
in the csv. I already tried deleting all empty rows in the csv but that
didn't help.

Further, when filtering out unconnected nodes using the giant component, it
removes all nodes that are not type 'null'. In the preview, I switched on
the node labelling option and saw that none of the type 'null' nodes had
any labels.

Any thoughts on what could be causing this?

Thank you,
Kat

**Comment by Katregner** [comment]
I think the issue may arise while importing the edges. I notice that when adding edges, Gephi reformats some of the nodes to look as they do in the top half of the table shown in the screenshot. 

I tried the 'graph type' and 'edges merge strategy' combinations that I would like to use (directed graph, merge edges as sum) as well as some alternatives but this doesn't seem to solve the issue. 

<img width="1246" alt="screen shot 2017-11-30 at 21 37 47" src="https://user-images.githubusercontent.com/33958909/33453648-bd4291a2-d616-11e7-9158-4ef1283c0c1e.png">

**Comment by eduramiba** [comment]
Hi,
Not sure what you mean by null, but looking at the last screenshot, it seems you are not using the same node ids in nodes and edges CSVs.

For correctly referencing nodes in edges CSV you have to use the id (never the label, only the id is unique).

So, for example:

Nodes table
--------------------
```CSV
id,label,type
user1,something,type1
user2,xyz,type2
```

Edges table
--------------------
```CSV
source,target,type,twitter_type
user1,user2,Directed,tweet
user2,user1,Directed,retweet
```

As you can see, 'Type' column in edges is reserved for directedness.

**Comment by Katregner** [comment]
Hi Eduardo, 

Still not working :/ 

Here's screenshots of my edges & nodes CSV. I followed the structure you listed above. 
I start by uploading the nodes. This works fine. 
When I add the edges, it reformats the nodes to look as in the top half of the last screenshot I sent yesterday (i.e. It removes data from all columns and replaces the ID values with the node label).
Please note: I am not giving the nodes numeric ID values myself (as you can see from my nodes screenshot). 

Is there perhaps a step by step guide for uploading data to gephi 9.2 that you could share? I had a look but couldn't find anything online. 

Thanks for your patience. 

<img width="850" alt="screen shot 2017-12-01 at 14 53 40" src="https://user-images.githubusercontent.com/33958909/33485655-75d64570-d6a7-11e7-9073-c89efde764ed.png">

<img width="743" alt="screen shot 2017-12-01 at 14 56 16" src="https://user-images.githubusercontent.com/33958909/33485742-d5c265e0-d6a7-11e7-92e7-3e1d6a9503c6.png">

**Comment by eduramiba** [comment]
Remember that the id column must be exactly `id` not `userid`

**Comment by Katregner** [comment]
I renamed the nodes 'userID' column to 'ID' and am still seeing the same behaviour. Uploading nodes works fine until I upload edges. Then the nodes look as follows (Screenshot 1)

Also, when I save the nodes CSV with an 'ID' column I get the error message below when I try and re-open that file on my desktop. I found a thread/fix online which said to not use 'ID' but 'UserID', hence why I was using 'UserID' in the first place. 

<img width="1244" alt="screen shot 2017-12-01 at 15 56 09" src="https://user-images.githubusercontent.com/33958909/33488190-2ecb1e9a-d6b0-11e7-938b-6b56182a7d47.png">

<img width="472" alt="screen shot 2017-12-01 at 15 54 04" src="https://user-images.githubusercontent.com/33958909/33488177-21fe6eb0-d6b0-11e7-858d-67bcf62e39fe.png">

**Comment by eduramiba** [comment]
Make sure you choose append to workspace during import report or it will create another workspace with edges info only instead.

Not sure about the excel problem but it won't affect Gephi.

**Comment by Katregner** [comment]
Still no luck. I chose 'append to workspace' and saw that yes, it does add the edges correctly but it also creates a new node (the target). 

In the preview, this new node is what's causing there to be 'null' values. It has no meta data attached and is unconnected

**Comment by eduramiba** [comment]
Make sure all source and target id references exist in your nodes file, otherwise missing nodes will be created empty

**Comment by Katregner** [comment]
It's working now! Thanks for your help and latic

**Comment by Katregner** [comment]
It's working now! Thanks for all your help and support :))

**Comment by eduramiba** [comment]
Great, you are welcome :)

**Comment by fajarberlian** [comment]
Please, Help…
My Gephi 0.9.2 suddenly closed (no errror notif) when i click file > import speadsheet. Thanks…

**Comment by hannahbav** [comment]
Hi - I have followed the same suggestions as Katregner but mine is still not working. I believe the set up is all correct:
![image](https://user-images.githubusercontent.com/49622124/99589283-ac4d6380-29e3-11eb-9a47-6129bbf3d4d7.png)

**Comment by eduramiba** [comment]
Hi @hannahbav , make sure your csv does not have trailing whitespace or similar.
You can also use .xlsx files

**Comment by kathwhittey** [comment]
Just commenting for anyone having this problem in a mac:

I saved the .csv from excel into a text edit file and saved is as a .csv from text edit and then it imports fine into Gephi!
