### ISSUE TITLE
Import data from a jtable to the overview of gephi

### ISSUE THREAD

**Issue by RobertoPazMartinez** [gephi/gephi#1857]
## Current Behavior

I make a plugin where I add a panel that makes a query to the database and the data it brings me, placed them in a table (jtable de java), what I want to do is to be able to select one or several records in the table and send them to the overview of gephi, if this is possible or someone has done something similar could help me please thanks greetings

* Version used: Gephi 0.9.2
* Operating System: Linux

**Comment by eduramiba** [comment]
Hi,
Gephi already has support for importing data from several databases (File - Import database...). If your database is not in the list, a `DatabaseImporter` plugin can be created.

If you still need to do it from the jtable, you will need to use some custom code that directly appends data to the `Graph` via `GraphController`. Example: https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/ManualGraph.java

**Comment by RobertoPazMartinez** [comment]
Hi, thanks for the example, I have a problem the plugin that I am developing does not recognize the libraries that I need to use the import

import org.gephi.graph.api.*;
import org.gephi.project.api.ProjectController;
import org.gephi.project.api.Workspace;
import org.openide.util.Lookup;

How can I make use of the gephi libraries?

Thank's

**Comment by eduramiba** [comment]
Are you developing the plugin based on instructions at https://github.com/gephi/gephi-plugins ?
You will need to add necessary dependencies to your module's pom.xml. Some examples: https://github.com/gephi/gephi-plugins/tree/master-forge/modules

**Comment by eduramiba** [comment]
Did it work?

**Comment by RobertoPazMartinez** [comment]
I already added the dependencies, but I still can not find a way to send the records of my table to the gephi workspace, Thank's

**Comment by eduramiba** [comment]
Check some code example here: https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/ManualGraph.java

**Comment by RobertoPazMartinez** [comment]
Do you know where I find the code of the module to add node that has the gephi

**Comment by RobertoPazMartinez** [comment]
I already found the code but i have a problem with the .getGraphModel

**Comment by eduramiba** [comment]
What is the problem?
