### ISSUE TITLE
Script for getting edges in shortest path

### ISSUE THREAD

**Issue by GuillaumeVGeo** [gephi/gephi#1859]
(following this discussion : http://forum-gephi.org/viewtopic.php?f=7&t=2917&p=14756#p14756)

## Expected Behavior
It should exist a filter to display only the nodes involved in a "shortest path" from one node to another

## Current Behavior
Currently the Gephi can find automatically the shortest path but it can only change the color of the nodes involved.

## Possible Solution
As Gephi can already automatically find the shortest path, I assume that most of the work required is already done.

## Context
Big potential for the interest of Gephi software

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 144
* Operating System:  Windows 8.1

**Comment by worknet-bienew** [comment]
It will be great to see this feature added.

**Comment by evlacho** [comment]
Yes I would love this feature too. I would also like the ability to calculate the short path between more than two nodes

**Comment by valkom1** [comment]
+1

**Comment by mbastian** [comment]
Thanks for the idea, this feature will be included in the 0.10.0 release.

<img width="741" alt="Screenshot 2022-11-12 at 21 05 07" src="https://user-images.githubusercontent.com/234813/201492528-680da6d6-01c5-4c6d-99e7-250f62b4dda7.png">
