### ISSUE TITLE
Save node color setting when you save the project.

### ISSUE THREAD

**Issue by valflanza** [gephi/gephi#1861]
## Expected Behavior
Save node color palette set up with the project
## Current Behavior
The palette settings does not saved with the project file
## Possible Solution
Save the node color palettes when you save the project.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Oracle Java 1.8
* Operating System: Linux Debian

**Comment by BonnieSchrack** [comment]
Yes, please, please, please! This is a major trouble for my work!  I try to use a plug-in, but it's not the easiest thing to apply. Please make the colors, as displayed in the graph, an integral part of the Save.

**Comment by peterch405** [comment]
I second this. Much needed feature!

**Comment by gingergenius** [comment]
Not only color settings are lost, but all appearance settings - sizes too.

**Comment by galkamax** [comment]
This would be really helpful

**Comment by BTDohertyGit** [comment]
Absolutely agree.

**Comment by rothstem02** [comment]
Any updates on this?

**Comment by mbastian** [comment]
This is now implemented and will be included in the upcoming 0.9.3 release.

**Comment by beavisbee** [comment]
I am using version 0.10 and the colors are still not saved. Can anyone advise what I am missing?

**Comment by wuhwyy** [comment]
this feature is still missing in the version 0.10.1 202301172018

**Comment by abbeythorpe** [comment]
Using Gephi 0.9.7 and still having this issue.

Device: MacBook Pro 13-in 2019
macOS: Ventura 13.6.1
Gephi: 0.9.7

**Comment by ChathuZ** [comment]
I think after 10 years, the issue still exists. Im organising 12 figures. 9 taxa in each. copy pasting hex codes 12X9. What a waste of time.
