### ISSUE TITLE
Convert a graph to a directed graph

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1863]
## Expected Behavior
Hello, Is there a way to convert a graph which has been instantiated with

"Graph graph = graphModel.getGraph()"

into a directed graph later in the code?

Thanks in advance

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Yeah https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/GraphModel.html#getDirectedGraph--

**Comment by eduramiba** [comment]
And you can also do graph.getModel().getDirectedGraph()
https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/Graph.html#getModel--

**Comment by MK2345** [comment]
Many Thanks for the quick help.
