### ISSUE TITLE
Use timezone in GEXF import, export and Create time interval in Data Laboratory

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1864]
Also, exporting to gexf in 'Date' mode for time representation will lose the timezone, so we need to be sure this works fine with all cases and exporting and importing does not change the data.

Original forum post http://forum-gephi.org/viewtopic.php?f=23&t=6349&p=14767#p14767

**Comment by mbastian** [comment]
Hi, I've made a number of fix to properly support timezones:
- GEXF import now uses the <graph> timezone attribute when the timezone is missing in the dateTime string. The latter still takes precedence when provided (e.g. 2012-01-12T15:00:00.000**-08:00**).
- GEXF export will always add the timezone attribute, for reference. The timezone is already included in the attribute value so it's redundant but it doesn't hurt.
- DataLab create interval action will use the graph configuration timezone.
