### ISSUE TITLE
convert an undirected graph to a directed one, the edges still remain undirected

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1871]
## Expected Behavior
Hello, I would like to convert an undirected graph to a directed one, so that all undirected edges are subsequently directed edges. For example when I have an undirected edge from node A to B, it should become two edges, an edge A-> B and an edge B-> A.
Is there a function to convert the edges to undirected edges?

Thanks in advance

## Current Behavior
When I convert an undirected graph to a directed one, the edges still remain undirected.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
This is the intended behavior, I think you will need to do some processing with antes external tool or the jython scripting plugin.
