### ISSUE TITLE
Change the attribute of a node if only the node-id is given

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1873]
## Expected Behavior
Hello,
is there a way to change the attribute of a node if only its ID is given?

Thanks in advance
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
What do you mean? In custom code?

**Comment by MK2345** [comment]
I have a TreeMap in which is only the Node-id's and the labels of nodes stored.
And I want to change the node attributes based on the id's.

**Comment by eduramiba** [comment]
Not sure I understand, but you can get the node by id and change it https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/Graph.html#getNode-java.lang.Object-

**Comment by MK2345** [comment]
Oh yes, thank you, it works with that
