### ISSUE TITLE
Database Import Wrong Time Zone Exception

### ISSUE THREAD

**Issue by simonzettler** [gephi/gephi#1875]
## Expected Behavior
Database import like in Version 0.9.1
## Current Behavior
Exception Message: "The server time zone value 'Mitteleuropäische Zeit' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specific time zone value if you want to utilize time zone support.
## Possible Solution
when starting the jdbc driver set serverTimezone=UTC?

## Steps to Reproduce

1. Import Database in Gephi
2. Test connection to localhost MySQL database. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 9.0.1
* Operating System: Windows 10

**Comment by eduramiba** [comment]
Our only change is that we updated the mysql driver, can it be a server problem?

**Comment by eduramiba** [comment]
Related https://stackoverflow.com/questions/26515700/mysql-jdbc-driver-5-1-33-time-zone-issue

**Comment by simonzettler** [comment]
In my database connection code I also updated the mysql connector version from 6.0.2 to 6.0.6 and get some error. So I changed the code from this:

jdbc:mysql://"+host+":"+port+"/"+database+
                        "?allowMultiQueries=true&useUnicode=true&useJDBCCompliantTimezoneShift=true" +
                        "&useLegacyDatetimeCode=false&serverTimezone=UTC
&autoReconnect=true&useSSL=false


to that:

jdbc:mysql://"+host+":"+port+"/"+database+
                        "?allowMultiQueries=true&useUnicode=true" +
                        "&useJDBCCompliantTimezoneShift=true" +
                        "&useLegacyDatetimeCode=false" +
                        "&serverTimezone=UTC

maybe something like that is also the solution for the gephi mysql driver?

**Comment by eduramiba** [comment]
Yeah I guess we could do that, or maybe just allow any custom jdbc url as an advanced option.

**Comment by eduramiba** [comment]
Also, you can try to append ```?whatever``` to the database name in the Gephi UI, since that will just be appended to the jdbcURL (see https://github.com/gephi/gephi/blob/6efb108718fa67d1055160f3a18b63edb4ca7be2/modules/DBDrivers/src/main/java/org/gephi/io/database/drivers/SQLUtils.java#L68)

**Comment by simonzettler** [comment]
Ah i see! Thanks! When i add ?serverTimezone=UTC to my database name it works!

**Comment by eduramiba** [comment]
Haha great!

**Comment by pokes135** [comment]
Thanks eduramiba, I know it's an old post but you saved my day.

**Comment by Clancy9536** [comment]
Thanks! It's also worked for me.
