### ISSUE TITLE
Changes in labels not rendered in preview mode

### ISSUE THREAD

**Issue by WouterSpekkink** [gephi/gephi#1877]
## Expected Behavior
In the data laboratory, when changing the label text settings (e.g., adding more variables to the nodes labels), this should change the labels in both the Overview window, and the Preview window.
 
## Current Behavior
Changes in label text settings are visible in the Overview window, but not in the Preview window. In general, chaning text settings for labels does not seem to have an effect on the labels that are rendered in the preview window.

## Possible Solution
My best guess is that the problem occurs somewhere in the NodeLabelBuilder of the preview plugin (NodeLabelBuilder.java). It could be that the first of the following statements returns null, causing nodeColumns to be set to null as well:

VisualizationController vizController = Lookup.getDefault().lookup(VisualizationController.class);
Column[] nodeColumns = vizController != null ? vizController.getNodeTextColumns() : null;

Because that would cause the for-loop in the below not to be triggered.

private String getLabel(Node n, Column[] cols, GraphView view) {
        String str = "";
        if (cols != null) {
            int i = 0;
            for (Column c : cols) {
                if (i++ > 0) {
                    str += " - ";
                }
                Object val = n.getAttribute(c, view);
                str += val != null ? val : "";
            }
        }
        if (str.isEmpty()) {
            str = n.getLabel();
        }
        if (str == null) {
            str = "";
        }
        return str;
    }

## Steps to Reproduce

1. Open label text settings in Overview window
2. Check additional boxes in Nodes tab.
3. Observe in Overview window that labels have been changed.
4. Refresh image in Preview Window.
5. Observe that the labels have not been changed in the Preview Window.

## Context

I am reporting mostly for someone else.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_151
* Operating System: Linux Ubuntu 16.04 LTS

Problem has also been observed on Windows 7.

**Comment by eduramiba** [comment]
Thanks for the report!

**Comment by WouterSpekkink** [comment]
Anytime :)

**Comment by WouterSpekkink** [comment]
Just exploring a little further, I found that the same problem occurs with edge labels. I also think that the problem is not in the fragment of code I included in the original report. Maybe the problem occurs much earlier, when the text of the labels is set. It is a bit difficult for me to trace where the label data retrieved by the renderes eventually comes from.

**Comment by BonnieSchrack** [comment]
I was the person who originally pointed out this problem. I'm Windows 10. This bug won't allow one to display anything but the "Label" field as the label of the nodes (haven't been using edge labels). Yes, I can merge some columns when importing data, but that's only a work-around.

 I'm also now having a problem that the Preview window shows nothing, even though I can successfully export files that show what would have been in the Preview window (still limited to the Label field). The empty Preview may not happen under most circumstances - I'll close and restart Gephi, and that may resolve it. But when one isn't specifically trying to close Preview, it should have a display. It now has only the background color.

**Comment by tautme** [comment]
I am experiencing a problem in the preview window as the label is being blocked behind the node.

![image](https://user-images.githubusercontent.com/15580867/36124214-de56e720-1014-11e8-8fbd-6d84ed19307c.png)

**Comment by eduramiba** [comment]
@tautme You changed the order of preview renderers, reset them at the preview configuration tab.

**Comment by tautme** [comment]
Restoring the renderer order... puts them in this order. 

![image](https://user-images.githubusercontent.com/15580867/36223349-c3b30bd0-1189-11e8-8ba4-8304126cd14e.png)

What is the correct order?

**Comment by eduramiba** [comment]
Restoring the order will set the correct order always, but just know that the polygon shaped nodes plugin will not correctly render nodes in PDF or SVG (it replaces the 'Default nodes' renderer but does not implement PDF or SVG).

**Comment by BonnieSchrack** [comment]
How is it going, is there any hope of getting 0.9.2 to produce node labels
with more than one element, not only in the Preview window, but in the
output (PDF, etc)?

This is an illustration of how having the nodes labeled by both their names
and by the group numbers (for the modularity classes), as well as being
identified by colors, helps the user keep straight who belongs to which
group, especially since some of the colors may be similar between groups.

\\\

​
As it stands now, I have to re-open each graph in 0.9.1 to get the numbers
in, one more step in an already lengthy process.

Bonnie

**Comment by eduramiba** [comment]
@BonnieSchrack this is planned for 0.9.3 but no progress yet

**Comment by mbastian** [comment]
This issue is fixed, and will be included in the upcoming 0.9.3 release. Thanks for the report!
