### ISSUE TITLE
Appending new data

### ISSUE THREAD

**Issue by mozhouipsos** [gephi/gephi#1879]
## Expected Behavior
the size will be summed with the new import sheet
## Current Behavior
Will take the new size replace the old size
## Possible Solution
add the new size to the old size

## Steps to Reproduce

1.import a node sheet
2.import a different node sheet with the same node but different size
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
You want some arbitrary column of of your nodes to be summed?

**Comment by mozhouipsos** [comment]
When it says append/merge, I just assumed that the size would be summer. Or at least be able to choose to sum or keep the old size.

**Comment by mozhouipsos** [comment]
Same goes the edge size as well.

**Comment by eduramiba** [comment]
But you can't import the node size in a spreadsheet since it's not a column but a property of the node

**Comment by eduramiba** [comment]
Duplicated edges weight can actually be summed choosing that strategy during import

**Comment by eduramiba** [comment]
There is also a detect and merge node duplicates feature in data laboratory that will allow you to sum an arbitrary column, but the merging must be based in a column different than id (since it's effectively unique).

**Comment by eduramiba** [comment]
In summary, if you import ids that already exist in the graph, you will update/replace data because ids are unique and if your data uses ids you must ensure that (they are optional).

Duplicates are merged based on source and target for edges, and any column you want for nodes.

**Comment by mozhouipsos** [comment]
ok. it was a bit counter intuitive. I'll figure out a workaround. Thank you

**Comment by eduramiba** [comment]
Great!
