### ISSUE TITLE
Where can I find The class DynamicModel and AttributeModel

### ISSUE THREAD

**Issue by Alvinsjq** [gephi/gephi#1884]
## Expected Behavior
I am trying to run the toolkit-demo program and wanna implement a dynamic graph.
## Current Behavior
So, I have found the website [How to execute a metric over time](https://github.com/gephi/gephi/wiki/How-to-execute-a-metric-over-time) and learn to run it.
However, I found that is different from the code in the file DynamicMetric in toolkit-demo. And I cannot find the class  **DynamicModel** and **AttributeModel**. 
**Are these classes not in the toolkit?**
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
Sorry, this example is old and needs to be reviewed, the graph core was changed in Gephi 0.9+
You can use dynamics directly in the graph Node/Edge For example https://gephi.org/graphstore/apidocs/org/gephi/graph/api/Element.html#getAttribute-org.gephi.graph.api.Column-org.gephi.graph.api.Interval-

**Comment by eduramiba** [comment]
This example code might help https://github.com/gephi/gephi/tree/master/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/dynamic

**Comment by Alvinsjq** [comment]
Ok, Thank you!
And, recently I want to implement a java program that can display a graph model one node by node.
So, Can toolkit preview a graph (not export), especially a subgraph in a Jframe or Applet?

**Comment by eduramiba** [comment]
Sure, check this https://github.com/gephi/gephi-toolkit-demos/blob/master/src/main/java/org/gephi/toolkit/demos/PreviewJFrame.java
