### ISSUE TITLE
Dynamic attributes for dynamic network not properly merged with multiple files

### ISSUE THREAD

**Issue by arjunsraman** [gephi/gephi#1885]
@eduramiba I have a series of graphs that have the following architecture: 
Column 1: ID
Column 2: Label
Column 3: timeset
Column 4: eigencentrality (defined as dynamic variable and timestamped with the same time as in the timeset column)
Column 5: modularity class (defined as dynamic variable and timestamped with the same time as in the timeset column)

Now, I open multiple .gexf files, gephi combines the timeset columns just fine (<[2001.0 2002]> for instance), but for some reason, gephi doesn't do the same for eigencentrality or modularity class. It only includes the most recent timepoint (see attached example). Do you know how I could correct this? Thanks
[example.pdf](https://github.com/gephi/gephi/files/1598447/example.pdf)

**Comment by eduramiba** [comment]
Mmm I think it should work. Can you provide the gexf files? Are you using 0.9.2 with updates installed?

**Comment by arjunsraman** [comment]
I'm using 0.9.3. Are there any other updates that are needed?



Attached are the gexf files that I simultaneously open in gephi to make a dynamic graph. Thank you so much for looking into this. 

[month1a.txt](https://github.com/gephi/gephi/files/1600434/month1a.txt)
[month2a.txt](https://github.com/gephi/gephi/files/1600436/month2a.txt)

And here is the output graph from opening the above two graphs and merging into one workspace. 
[month1_2_output.txt](https://github.com/gephi/gephi/files/1600454/month1_2_output.txt)

**Comment by eduramiba** [comment]
Thanks, I will test it. `TimeMap` merging is implemented at https://github.com/gephi/gephi/blob/5a789b169d5f12423f5d0584db39baea48598160/modules/ProcessorPlugin/src/main/java/org/gephi/io/processor/plugin/AbstractProcessor.java#L239 but maybe an unknown exception is being silenced in the catch block.

**Comment by mbastian** [comment]
Hi, I've made a fix for this issue. It will be included in the upcoming 0.9.3 release. Thanks a lot for the detailed report.

**Comment by eduramiba** [comment]
@mbastian thanks for the fix!
