### ISSUE TITLE
node ranking menu not filling

### ISSUE THREAD

**Issue by GregOldham** [gephi/gephi#1887]
## Expected Behavior
when attempting to set the color or size of nodes based on the ranking all available attributes of the nodes should be available in the drop down menu.
## Current Behavior
the ranking drop-down menu is either empty or only has the dashed lines available even after the network diameter has been calculated. 
## Steps to Reproduce

1.open data file with nodes and edges
2. have appearance window set to adjust the coloring of the nodes
3. calculate the network diameter
4. attempt to set the node size by any of the attributes calculated during the network diameter calculations
5. ranking menu will be empty or will not contain the centrality.
6. with e the size selection open select the option other than ranking (my appearance window won't open correctly at the moment.
7. re-select the ranking option
8. the menu now contains all the centrality scores

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java 8 update 151
* Operating System: windows 10, mac OS X 10.13.2

  could not locate this file.

**Comment by mbastian** [comment]
This has been fixed as part of the rewrite of the core appearance module in 0.9.3 release. Closing.
