### ISSUE TITLE
Missing edges after importing

### ISSUE THREAD

**Issue by dth1692** [gephi/gephi#1891]
## Expected Behavior
Expected to find edges in the data laboratory after uploading an edge list from Excel.
## Current Behavior
There are missing edges in my data.  All the nodes are imported, but some nodes are reported without any edges, some nodes have most edges with a few missing, some edge weights are lower than they should be.  In NodeXL my data shows 9.929 edges.  Gephi is showing 9,531.
## Possible Solution
I am not a tech person by any means, so I'm not sure what to do.  Google says BOM text may cause the issue, but I saw another forum say it no longer matters

## Context

Data is incomplete and therefore not usable

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: Windows 10

**Comment by eduramiba** [comment]
Hi,
BOM should not be a problem anymore, but make sure your Gephi 0.9.2 is up to date (Help menu, check for updates).

Do you get any warning or error during import report? Can you share your file for testing? Also, review what edge merge strategy is being used (sum, min, max, no merge...) during import report.

**Comment by dth1692** [comment]
Updating it worked- thanks.  I downloaded the Gephi yesterday, so I expected it to be up to date and did not check it.

**Comment by eduramiba** [comment]
Great, closing!
