### ISSUE TITLE
twitter streaming plugin - lists

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#1896]
## Expected Behavior

https://help.twitter.com/en/using-twitter/twitter-lists

In twitter users can create lists of users.
It would be great to be able to manage list on ones (or follow other peoples lists) Twitter account and have possibility to follow them all at once

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
@totetmatt Probably knows if this is possible

**Comment by totetmatt** [comment]
Import users from list > Looks feasible, at least for public lists. I would keep the managing of the list to twitter.

Feature can be clause and will be tracked here
https://github.com/totetmatt/gephi-plugins/issues/8

**Comment by eduramiba** [comment]
Great! Closing this one then

**Comment by mihkal** [comment]
wonderful :)

ma 15. tammik. 2018 klo 15.41 Eduardo Ramos <notifications@github.com>
kirjoitti:
