### ISSUE TITLE
Problem With timestamp and geolayout

### ISSUE THREAD

**Issue by anca912** [gephi/gephi#1899]
hi to all, sorry for the request.
I would like to start implementing a dynamic network coupled with a geolayout. 
The problems I encounter are the following:
1.  I can not figure out which format I have to enter for the time when import the file as csv format.
2. Whe I try to import a spredsheet in xlsx format I've problem with the double variable for the latitude and longitude caracter. 
2. When I try to apply the geolayout algorithm it hangs for hours without getting anything.

These are my data

[semplificazione iniziale gephi.xlsx](https://github.com/gephi/gephi/files/1642446/semplificazione.iniziale.gephi.xlsx)

## Your Environment

* Version used: Gephi 0.9.2
* Java version 8: 
* Operating System Windows 10 Pro 64 bit:

**Comment by eduramiba** [comment]
Hi,
Datetimes must be in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format. For example:
```
2013-11-25T00:00:00Z
2013-11-25T02:00:00+02:00
```

For your lat and long, use dot ('.') instead of comma for numbers formatting. For example
```
40.415363
-3.707398
```

**Comment by anca912** [comment]
Ok thanks, and when I declare the variable which kind of timestamp I've to use for the iso 8601?

**Comment by anca912** [comment]
Issue{message=[Record #18] Error when parsing value '2013-11-25 00:00:00' as a 'TimestampSet' for column 'DATA_PRELI', level=SEVERE}	SEVERE

**Comment by eduramiba** [comment]
You should name your column `timeset` and Gephi will auto-declare the column type as TimestampSet.

If a node/edge as multiple timestamps, you need to separate them by comma.

**Comment by eduramiba** [comment]
You are missing the `T` in the ISO 8601 format.

**Comment by eduramiba** [comment]
Take into account that, if you don't specify a timezone, the default timezone of the graph configuration will be assumed, which I think defaults to your computer timezone.

**Comment by anca912** [comment]
I've used the excel data, but there isn't any kind of command to trasform it in iso 8601! Is It necessary to use python to convert it?

**Comment by anca912** [comment]
I'm Italian, how can trasform it in excel?

**Comment by eduramiba** [comment]
This might help https://stackoverflow.com/questions/27388761/how-to-convert-a-date-in-excel-to-iso-8601-format/29134725

I think we will add support in future versions to not include the `T`, as it seems to be confusing.

**Comment by eduramiba** [comment]
Good luck!

**Comment by anca912** [comment]
OBJECTID | Lat_mercato | Long_mercato | Dat_prel
-- | -- | -- | --
12533 | 1889091.75876185 | 4911639.72208944 | 2013-11-25T00:00:00
12534 | 1889091.75876185 | 4911639.72208944 | 2013-11-25T00:00:00
12535 | 1886463.38201959 | 4910910.57719474 | 2013-11-25T00:00:00
12536 | 1886463.38201959 | 4910910.57719474 | 2013-11-25T00:00:00
12537 | 1886463.38201959 | 4910910.57719474 | 2013-11-25T00:00:00
12538 | 1883865.92760548 | 4909735.95974407 | 2013-11-25T00:00:00
12539 | 1883865.92760548 | 4909735.95974407 | 2013-11-25T00:00:00
12540 | 1883865.92760548 | 4909735.95974407 | 2013-11-25T00:00:00
12541 | 1882072.44593097 | 4909371.45193576 | 2013-11-25T00:00:00
12542 | 1882072.44593097 | 4909371.45193576 | 2013-11-25T00:00:00
12543 | 1881206.62853506 | 4907630.10265328 | 2013-11-25T00:00:00
12544 | 1881206.62853506 | 4907630.10265328 | 2013-11-25T00:00:00
12545 | 1881206.62853506 | 4907630.10265328 | 2013-11-25T00:00:00
12546 | 2038878.31853511 | 4846757.51938931 | 2013-11-25T00:00:00
12547 | 2041135.62956593 | 4846113.68673259 | 2013-11-25T00:00:00
12548 | 2040733.64263954 | 4847159.93701577 | 2013-11-25T00:00:00
12549 | 2039125.69493394 | 4847039.21057126 | 2013-11-25T00:00:00
12550 | 2039589.52540345 | 4845268.71877310 | 2013-11-25T00:00:00
12551 | 2039836.90291547 | 4840683.02703557 | 2013-11-25T00:00:00
12552 | 2041692.22701990 | 4840843.89205784 | 2013-11-25T00:00:00
12553 | 2044660.74714545 | 4840964.54219495 | 2013-11-25T00:00:00
12554 | 2046701.60410560 | 4839878.74006853 | 2013-11-25T00:00:00

I've this but I don't know how I've to import

**Comment by anca912** [comment]
Issue{message=problem with line 1: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 2: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 3: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 4: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 5: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 6: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 7: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 8: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 9: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 10: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 11: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 12: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 13: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 14: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 15: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 16: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 17: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 18: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 19: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 20: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING	
Issue{message=problem with line 21: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING

**Comment by eduramiba** [comment]
Maybe the timezone is mandatory, I don't remember, try using `2013-11-25T00:00:00Z`

**Comment by anca912** [comment]
Sorry, but I've the same error

**Comment by eduramiba** [comment]
This works for me just fine

[test.xlsx](https://github.com/gephi/gephi/files/1642760/test.xlsx)

**Comment by anca912** [comment]
No, also your file report this essor: 
Issue{message=problem with line 1: time not formatted correctly. It was skipped in the conversion, level=WARNING}	WARNING

**Comment by eduramiba** [comment]
Not sure what are you doing, here are my steps:

![1](https://user-images.githubusercontent.com/197285/35098023-df26fa6c-fc52-11e7-8e7f-aab2aa00683d.jpg)
![2](https://user-images.githubusercontent.com/197285/35098030-e475c64c-fc52-11e7-97ba-2f02c835e49e.jpg)
![3](https://user-images.githubusercontent.com/197285/35098031-e7b42254-fc52-11e7-95aa-2608436a6b9b.jpg)
![4](https://user-images.githubusercontent.com/197285/35098037-eb3af04c-fc52-11e7-823e-0b298bcb4772.jpg)

**Comment by anca912** [comment]
Perfect, for your test.xlsx, now try for my with your modifies. 

Thanks!

**Comment by eduramiba** [comment]
Fine too:

[test.xlsx](https://github.com/gephi/gephi/files/1642810/test.xlsx)

![test](https://user-images.githubusercontent.com/197285/35098403-3fcf990e-fc54-11e7-8ade-5a094afb5f6c.jpg)

**Comment by anca912** [comment]
![image](https://user-images.githubusercontent.com/35560205/35098708-98b71ed8-fc55-11e7-9c6a-316b5b3a6c2d.png)
It's wonderful but there is a problem with the dynamic. time is recognized but in the conversion hasn't the same content from excel

**Comment by eduramiba** [comment]
Yeah that's a known problem but just change the time representation in the Config dialog to datetime.

**Comment by anca912** [comment]
Ok I've seen! The use of timeline presupposes that the nodes have date different right?

**Comment by eduramiba** [comment]
Yeah I guess if all have same date it's useless

**Comment by anca912** [comment]
Great Eduardo! 👍 I've the last question! When I'm trying to use geolayout the algorithm doesn't stop and produce any kind of results. 
![image](https://user-images.githubusercontent.com/35560205/35099337-e7fb1a88-fc57-11e7-8254-db31963e5ea7.png)

**Comment by eduramiba** [comment]
It seems you closed the graph window, please reopen it in Window menu.

**Comment by anca912** [comment]
![image](https://user-images.githubusercontent.com/35560205/35099617-f2853320-fc58-11e7-9913-5f1d46bdbdaa.png)

**Comment by eduramiba** [comment]
Oh, your latitude and longitude values don't seem correct, they are too big. I thinks values must be between -180 and 180 degrees.

Also, if you want the layout to stop, uncheck the `Looping` option.

**Comment by anca912** [comment]
I've cecked the Coordinate System in wgs 84 and the coordinate in Mercatore coincide.

**Comment by anca912** [comment]
I've a problem with the transformation of the coordinate in excel from number in text

**Comment by eduramiba** [comment]
I think you will need to input decimal degrees.

**Comment by anca912** [comment]
But for Mercatore is impossible to input decimal degrees

**Comment by eduramiba** [comment]
As explained here, in this plugin lat and long must be in degrees:

https://gephi.wordpress.com/2010/05/17/map-geocoded-data-with-gephi

**Comment by anca912** [comment]
![image](https://user-images.githubusercontent.com/35560205/35107468-4b36ed0c-fc71-11e7-9028-1075eaa59711.png)
I think there is a problem with the definition of Mercatore standard, infact in the database of the airlines the Coordinate System is wgs 84 and not Mercatore. 
However, I've used it and in the first time it works.
