### ISSUE TITLE
Gephi 0.9.2. - exporting to new workspace after applying filter does not work

### ISSUE THREAD

**Issue by Marmeladenbrot** [gephi/gephi#1900]
Probably the same bug as in 0.9.1. - https://github.com/gephi/gephi/issues/1482

## Expected Behavior
Getting a new workspace with the filtered values

## Current Behavior
Task never completes according to the bar graph in the lower right corner of the screen. A new workspace tab appears, but the data table is empty.

## Steps to Reproduce

1. Open graph file (https://www.dropbox.com/s/8iym8b1v0ed0740/Start%20-%20Layout%20OpenOrd.gephi?dl=0)
2. apply Giant Component filter (not tried other because takes too long with my file)
3. Export to to new workspace
4. Get new workspace that remains empty while the export task never completes according to the bar graph in the lower right corner.

## Context

Getting the filtered data into a new workspace

## Your Environment

* Version used: Gephi 0.9.2
* Java version: x64 @ Version 8 Update 151
* Operating System: Windows 10 Professional x64
* RAM: 16GB, 12GB for gephi in config file
* SSD: Samsung 850 Evo 500GB
* CPU: Ryzen 5 1600 - 6 cores, 12 threads

**Comment by mbastian** [comment]
Hi, I'm trying to reproduce this issue but unfortunately I haven't been able to yet. The file link is now broken, would you mind sending it again @Marmeladenbrot ? Thank you!

**Comment by mbastian** [comment]
As I didn't hear back I'll close this one. Feel free to reopen when needed.

**Comment by sercankiyak** [comment]
Hi, I am also having a similar issue with Windows 11. Gephi 9.7. It is not exactly the same message as above so here you go:

java.lang.ClassCastException: class org.gephi.graph.api.types.TimestampSet cannot be cast to class org.gephi.graph.api.types.TimeMap (org.gephi.graph.api.types.TimestampSet and org.gephi.graph.api.types.TimeMap are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @51088d84)
	at org.gephi.graph.impl.AttributesImpl.getAttributes(AttributesImpl.java:225)
	at org.gephi.graph.impl.ElementImpl.getAttributes(ElementImpl.java:414)
	at org.gephi.graph.impl.GraphBridgeImpl.copyAttributes(GraphBridgeImpl.java:203)
	at org.gephi.graph.impl.GraphBridgeImpl.copyNodes(GraphBridgeImpl.java:110)
	at org.gephi.filters.FilterControllerImpl$2.run(FilterControllerImpl.java:381)
[catch] at java.base/java.lang.Thread.run(Unknown Source)

The new workspace is also created but it is empty. I am using the data I acquired via Twitter Streamer V2 (bu also previously the older one, the same issue). Timestamp is mentioned in the above message, so I wonder if that is the problem. Thanks
