### ISSUE TITLE
Using the method getNeighbors(Node node, int type)

### ISSUE THREAD

**Issue by MK2345** [gephi/gephi#1901]
## Expected Behavior
How can I use the method getNeighbors (Node node, int type) for a given node to determine all descendant nodes or predecessor nodes.
What value would I have to enter in type, e.g. to get all successor nodes?

Thanks in advance.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
The type makes reference to edge [type/kind of relationship](https://gephi.org/gephi/0.9.2/apidocs/org/gephi/graph/api/GraphModel.html#addEdgeType-java.lang.Object-) (for example friend, or family), so what you need to use is `getEdges(node)` and then filter them by source/target node.
