### ISSUE TITLE
Problem with Map of Countries

### ISSUE THREAD

**Issue by anca912** [gephi/gephi#1903]
## Expected Behavior
I want to insert a map of a region with the use of MoC plugin. 

## Current Behavior
I try to use the guide: https://marketplace.gephi.org/plugin/maps-of-countries/
but:
![image](https://user-images.githubusercontent.com/35560205/35273309-6d29d83c-0038-11e8-99bd-3dd9f68e43db.png)

## Steps to Reproduce

1. Use geolayout, and insert lat and long 
2. Try to use MoC but in my windows don't appear

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8.1
* Operating System: Windows 10 Pro X64

**Comment by eduramiba** [comment]
Sorry we have to remove that old site and link to https://gephi.org/plugins/#/plugin/mapofcountries

What do you mean your windows don't appear?

**Comment by anca912** [comment]
Yes appear but I've truble with MoC. When I use geolayout the point appeare but is impossibile to visualize the map of region:
![image](https://user-images.githubusercontent.com/35560205/35274197-802149ea-003b-11e8-8357-302629e33327.png)
Moreover there isn't a map o Apulia region in Italy:
![image](https://user-images.githubusercontent.com/35560205/35274270-c39eda20-003b-11e8-848c-85a11bcc9a27.png)

**Comment by eduramiba** [comment]
I guess you have to use a greater scale or something. @seinecle what is the correct use?

**Comment by mbastian** [comment]
Closing old issue.
