### ISSUE TITLE
allow gephi to use local profile instead of roaming profile

### ISSUE THREAD

**Issue by geertn444** [gephi/gephi#1904]
## Expected Behavior
- Use local profile

## Current Behavior
- uses roaming profile location AppData\Roaming
## Steps to Reproduce

1.
2.
3.
4.

## Context

Gephi saves data in AppData\Roaming\.Gephi by default.
This is part of the roaming profile and in our corporate environments roaming profiles are limited in size (quota) because they are replicated.
This prevents us from depoying Gephi on a large number of workstations.
Solution: give user the option to choose AppData\Local\.Gephi instead.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: Windows 7

**Comment by eduramiba** [comment]
You can change `default_userdir` in file `gephi.conf` under "__gephi_install_dir__\etc" directory.
