### ISSUE TITLE
Node lossing when export the graph as PDF or SVG

### ISSUE THREAD

**Issue by hacwoo** [gephi/gephi#1907]
## Current Behavior
When I export my graph to PDF or SVG, I find that there have no node in the file, just edges and labels

## Possible Solution
I roll-back my gephi to 0.9.1, and it solved!

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: window 10 /Ubuntu 16.04

**Comment by eduramiba** [comment]
Hi,
Did you install this plugin? https://gephi.org/plugins/#/plugin/polygon-shaped-nodes
It breaks PDF and SVG export, for any version.

**Comment by hacwoo** [comment]
Thank you, it solved!

**Comment by saladedefruit** [comment]
Hello all,
I am having a similar issue myself. I am trying to export to PDF and/or SVG a graph with a lot of nodes and edges, but the nodes and their labels just do not appear. Exporting to PNG works sometime, and I can always do it through screenshot, but this format isn't ideal for me.

I have tried a lot of options found on the few posts around this issue but nothing worked (#1760, #1759 and so on). I uninstalled the Polygon plugin, I tried exporting graphs with less nodes and no overlap into PDF, but none of these options worked. I can get the labels to appear by themselves if I select show labels in preview, but I still can't get the nodes to appear in PDF. 

Any ideas?

Thanks for your time. 

![forceatlas2 strongergravity](https://user-images.githubusercontent.com/36054592/37123352-ea4bb4fa-2231-11e8-9fa3-572cd8a961e3.png)
[Workspace1.pdf](https://github.com/gephi/gephi/files/1791222/Workspace1.pdf)

[Untitled.pdf](https://github.com/gephi/gephi/files/1791236/Untitled.pdf)
![untitled](https://user-images.githubusercontent.com/36054592/37123598-d99eb0de-2232-11e8-8e94-35c155309a38.png)

**Comment by hacwoo** [comment]
Have you tried gephi 0.9.1?

**Comment by saladedefruit** [comment]
Hello hacwoo, thanks for your message. 

Yes, I have tried gephi 0.9.1 unfortunately and it displays the same results as those posted in the above using 0.9.2 and 0.9.3.

**Comment by saladedefruit** [comment]
Hello all,
Just an update on my situation for future references: going in "Preview" and "manage renderers" and selecting "Default nodes" seems to fix the problem. 
Cheers!
