### ISSUE TITLE
Crash when exporting VNA graph file

### ISSUE THREAD

**Issue by wrwishart** [gephi/gephi#1909]
## Expected Behavior
export graph file in VNA (netdraw) format
## Current Behavior
says file successfully exported but freezes upon completion and resulting file cannot be read by Netdraw
## Steps to Reproduce

1.open dataset 
2. select file, export, graph, VNA
3.program no longer responsive
4.

## Context

I'm trying to get my data set with attributes into netdraw or ucinet for additional statistical tests.
I also am unable to successfully open the resulting file in netdraw. It gives me a "not a valid integer value" error, followed by a "access violation at address..." error. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 161
* Operating System: occurs on MacOS 10.12.6 and Windows7 

[messages.log](https://github.com/gephi/gephi/files/1682046/messages.log)

**Comment by eduramiba** [comment]
Forum post http://forum-gephi.org/viewtopic.php?f=29&t=6404

**Comment by wrwishart** [comment]
When I removed the "color" and XY attributes in the export options Gephi still became unresponsive after file export complete message, but Netdraw could successfully import the file without problem.

**Comment by mbastian** [comment]
Fix will be included in the 0.9.3 release. Thanks for reporting!
