### ISSUE TITLE
Link not working: Datasets - GEXF file. CLASS OF 1880/81

### ISSUE THREAD

**Issue by X174517** [gephi/gephi#1913]
## Expected Behavior
I'm trying to download the file from: https://github.com/gephi/gephi/wiki/Datasets corresponding to "Class of 1880/81".

## Current Behavior
   "Secure connection failure" error. 

## Your Environment

* Browser: Chrome, Firefox
* Operating System: Ubuntu 17.04

**Comment by eduramiba** [comment]
Works fine for me at the moment: http://www.org-soz.uni-wuppertal.de/fileadmin/soziologie/org-soz/files/Heidler_et_al_2013_Relationship_patterns_in_the_19th_century.gephi
