### ISSUE TITLE
Nodes disappear in exported file

### ISSUE THREAD

**Issue by tautme** [gephi/gephi#1914]
## Expected Behavior
When exporting from the preview window, I expect to see the nodes in the exported svg/pdf/png. 

## Current Behavior
The exported pdf is missing all of the nodes. The preview window shows the nodes but the exported file does not.

![image](https://user-images.githubusercontent.com/15580867/36227463-c5450324-1196-11e8-9c5e-8cf439dd1478.png)

## Possible Solution
Could this be a preview renderers order problem?

![image](https://user-images.githubusercontent.com/15580867/36225130-4f0e4596-118f-11e8-953d-5e15e836de58.png)

I have installed all of the layout plugins. Could there be a bug from one of them?

## Steps to Reproduce
1. Open Sample "Les Miserables.gexf" and select graph type "mixed."
2. In the preview pane de-select curved edges and refresh preview.
3. Export pdf and save

## Your Environment

* Version used: Gephi 0.9.2
* Java version: "1.8.0_161"
* Operating System: Windows 10 Enterprise

**Comment by eduramiba** [comment]
This is a known bug created by the polygon shaped nodes plugin:

https://github.com/gephi/gephi/issues/1907
