### ISSUE TITLE
Import csv dialog ignore "Graph Type" setting

### ISSUE THREAD

**Issue by tkopecek** [gephi/gephi#1924]
## Expected Behavior
When I import edges csv without 'Type' field, edges should be treated according to 'Graph Type' setting in import wizard.

## Current Behavior
'Graph Type' is ignored. All edges are treated as directed which leads to loss of edges when I try merge strategy as "Don't merge"

## Possible Solution

I've quickly gone through code and https://github.com/gephi/gephi/blob/b6c1a346dd6184fe500515b7996b90d0348b2bcf/modules/ImportPlugin/src/main/java/org/gephi/io/importer/plugin/file/spreadsheet/process/ImportEdgesProcess.java#L109 sets default edge type as DIRECTED during `execute()`. So, in this pass is duplicit edge ignored and method is never called again. Wizard dialog is displayed _after_ this call, so changes of value have no more effect on container content.

## Steps to Reproduce

csv content:

    Id,Source,Target,timeset,Label
    1,1,2,"<[2017,2018)>","Label 1"
    2,2,1,"<[2017,2018)>","Label 2"

1. Open this csv
2. Select 'Comma', 'Edges table' in first page of wizard (defaults)
3. Use defaults for second screen (import settings 2/2), press 'Finish'
4. Select 'Graph Type' undirected
5. Select 'Merge Strategy' Don't Merge
6. Press ok
7. Check that only first edge was imported instead of both

## Context

I want to import graph with multiple (seemingly same) edges. Difference in edges is in private attributes, so I don't need to get these data merged or ignored.

## Your Environment

* Version used: Gephi 0.9.2 (same behaviour with current master)
* Java version: OpenJDK Runtime Environment 1.8.0_161-b14
* Operating System: F27

**Comment by eduramiba** [comment]
Mmm but you can't have two undirected edges that are opposite, they are incompatible and that's why the second edge can't be created (I think you will get a warning after import).

You should import them as directed or use the same source and target pair for undirected edges.

**Comment by eduramiba** [comment]
But maybe we could import the second undirected reversed, so they become compatible. I will think about that

**Comment by tkopecek** [comment]
Where should be such warning? I've not seen it anywhere - just generic info, that there are parallel edges and I should select merge strategy.
BTW, I've just tried with same source/target and it behaves the same - second edge is lost.

**Comment by eduramiba** [comment]
Right, I just tried importing your data and there is no warning, this should be reviewed.

Buf if I import this:

```csv
Id,Source,Target,timeset,Label
1,1,2,"<[2017,2018)>","Label 1"
2,1,2,"<[2017,2018)>","Label 2"
```

Thin it works fine:

![1](https://user-images.githubusercontent.com/197285/37062340-708aa4a0-2196-11e8-8571-b87495e21d72.png)

![2](https://user-images.githubusercontent.com/197285/37062349-7559f9a4-2196-11e8-93a7-db30925f1d2c.png)

Importing your data unchanged as directed also works.

**Make sure your gephi is up to date in Help menu, too**

**Comment by mbastian** [comment]
Hi, I've reviewed this thread and I'm definitely seeing the gap in clarity.  When one selects "undirected" for a graph that has mutual directed edges, some edges will be discarded. This has nothing to do with the edge merge strategy actually. However, this might be confusing and it would be good to somehow inform the user what is happening.

Besides that, did I get it right that there isn't any other issue?

**Comment by mbastian** [comment]
Update: I made a small change that would update the number of edges on the report when the "Undirected" graph type is selected. Not super visible but hopefully it gets noticed.

**Comment by mbastian** [comment]
Yes, that is correct. We are a bit limited technically in the sense that the Issues and Warnings you see on the report panel must be generated during the import process, not after. Ideally, we would only trigger a warning when the user selects "Undirected". But we could also trigger a warning like "Mutual edges detected, resulting in some edges not being imported when undirected" but I don't like it because it will be confusing as "Directed" is the default option.

**Comment by mbastian** [comment]
Hi, I almost forgot that we actually have the ability to show a report after the processor step. I've made a change so that it also now includes warning about mutual edges being deleted. See screenshot. This should hopefully make it clearer.

<img width="571" alt="Screenshot 2022-06-19 at 21 26 04" src="https://user-images.githubusercontent.com/234813/174497437-60b84621-c910-49de-9742-60e2bd866376.png">

**Comment by tkopecek** [comment]
Nice, that would work! Thanks!
