### ISSUE TITLE
I can't show my graphic in Sigma.js 

### ISSUE THREAD

**Issue by zakisaoud77** [gephi/gephi#1928]
## Expected Behavior
I have exported my network to Sigma.JS Format.
When i open the file with Ghrom it dosen't showying for me.
How i can fix my problem ?

I can't preview my  second network also , what is the solution for that ?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Make sure you are not just opening `index.html` in chrome, that does not work. You need a server (locally one such as python simple http server https://stackoverflow.com/questions/7943751/what-is-the-python-3-equivalent-of-python-m-simplehttpserver)

Check https://gephi.org/plugins/#/plugin/sigmaexporter

**Comment by zakisaoud77** [comment]
Hi Thank you for your answer, but I didn't understand why i need server ? i have seen video in youtube, and it work without run a server !

**Comment by eduramiba** [comment]
Chrome won't open local files for security. Try a simple server or maybe Firefox

**Comment by zakisaoud77** [comment]
I mean it open, but it not show the graphe. I have problem also with big network, i can't preview it in Gephi, what i should do ?

**Comment by eduramiba** [comment]
Can you show screenshots?

**Comment by zakisaoud77** [comment]
![untitled 1](https://user-images.githubusercontent.com/31625000/37242988-4b5688e6-2472-11e8-80ee-fcfc00af902d.jpg)

**Comment by eduramiba** [comment]
But please show the address bar and the browser.

**Comment by zakisaoud77** [comment]
![untitled 2](https://user-images.githubusercontent.com/31625000/37243005-add5cd74-2472-11e8-95ac-236f3922e9a8.jpg)
In Mozila Firefox it work, but i want to show it in Chrom

**Comment by eduramiba** [comment]
It might be the same for firefox, can't open `file://` local files.

Check this guide: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

**Comment by eduramiba** [comment]
Did it work?

**Comment by zakisaoud77** [comment]
Hi it work without your instruction, i just made mistake in graph arcs. hih

**Comment by eduramiba** [comment]
Great, closing!

**Comment by dedenhabibi** [comment]
@eduramiba Thank you. Your solution succeed. I use Visual Studio Code with extension 'Live Server' (https://ritwickdey.github.io/vscode-live-server/)

**Comment by kcmagnus** [comment]
I have the same problem. Can someone tell me how to solve it?
