### ISSUE TITLE
Exporting the Data file of modularity classe in Gephi

### ISSUE THREAD

**Issue by zakisaoud77** [gephi/gephi#1929]
## Expected Behavior
Good morning,

How i can export the data of my modularity classe result in Gephi ?

Thank you 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Do you mean with the toolkit or desktop application?

You can just export a CSV spreadsheet export should be fine (File menu - Export graph file...)

**Comment by zakisaoud77** [comment]
Hi, 

I am using the desktop application. Juste i would like to extract the classes of the modularity classe  algorithme. And not the graphe data because i have these data before.

**Comment by eduramiba** [comment]
Just the different values set?

Well, you can do that in excel I guess, remove other columns and keep only unique values.

**Comment by zakisaoud77** [comment]
I want to exctract the values set ( the classes ) with the user ID in each classe. With your method of exporting the graph, i didn't get this information in the exported file.

**Comment by eduramiba** [comment]
The user id? Do you mean the node id?

That should be included when exporting the nodes table spreadsheet (make sure nodes table is selected in export spreadsheet dialog options)

**Comment by zakisaoud77** [comment]
Yes The nodes IDs. Ok i will try that.

**Comment by eduramiba** [comment]
Sure, in export graph file dialog:

![imagen](https://user-images.githubusercontent.com/197285/37291618-493a9bb2-260f-11e8-8b7c-04e18a9cc190.png)

**Comment by zakisaoud77** [comment]
I don' have modularity classes in my options, why  ? maybe i should create colone in my input cvs file and name it modularity class ?
![image](https://user-images.githubusercontent.com/31625000/37291837-d381e10e-260f-11e8-94db-f8599f0a691b.png)

**Comment by zakisaoud77** [comment]
Ok i will try it, thank you

**Comment by zakisaoud77** [comment]
Thanks it wok for me , but do you know what mean the option "nodecolor-multimode" ?

**Comment by eduramiba** [comment]
It's a column created by the multimode networks plugin when you click on "Graph coloring" to check if it's a bipartite network.

**Comment by zakisaoud77** [comment]
ok thanks

**Comment by s-tikhomirov** [comment]
Facing the same issue, but don't see the necessary options in the export menu as on @eduramiba 's screenshot (in the menu I choose File - Export - Graph file):

![Screenshot from 2019-10-10 17-35-48](https://user-images.githubusercontent.com/7126627/66583950-83259700-eb84-11e9-8bcf-9d01a2c6c9c4.png)
