### ISSUE TITLE
Show the edges direction in the Preview Menu

### ISSUE THREAD

**Issue by zakisaoud77** [gephi/gephi#1932]
## Expected Behavior
Hello
I have created an oriented graph in Gephi, and i would like to show the edges' directions in the preview menu, because now it show but the edges don't have direction. What i would like do?

Thank you.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Are they undirected or directed?

If curved, they direction is clockwise, and  arrow can't be shown at the moment.

**Comment by zakisaoud77** [comment]
Yes is directed. So i can't show it at the moment ? :(

**Comment by eduramiba** [comment]
Well it is show, by curve clockwise direction.

Also, you can disable curved edges in preview and then an arrow will appear.

**Comment by zakisaoud77** [comment]
Wherre i can find the clockwise direction option ? is an option or what ?
How i can disable curved edges ?

**Comment by eduramiba** [comment]
To disable curved edges go to preview settings panel and look for the edges curved option.
Clockwise direction is not an option, though, can't be changed.

**Comment by zakisaoud77** [comment]
OK i work with disabled curved edges, thanks

**Comment by eduramiba** [comment]
Great!
