### ISSUE TITLE
Show the edges direction in the Sigma.js Template

### ISSUE THREAD

**Issue by zakisaoud77** [gephi/gephi#1933]
## Expected Behavior
Hello,

I would like to show the edges' directions of my network in the Sigma.js template. How i can do ?

Thank you.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,

Please ask in the original plugin author for help: https://gephi.org/plugins/#/plugin/sigmaexporter

I think you will need to change something in a `config.json` file or similar.

**Comment by zakisaoud77** [comment]
Ok i will ask him. Thanks

**Comment by eduramiba** [comment]
Great!
