### ISSUE TITLE
Display the edges "directions" in the Sigma.js File in Gephi

### ISSUE THREAD

**Issue by zakisaoud77** [gephi/gephi#1938]
## Expected Behavior
Hello,

I would like to show the edges' directions of my network in the Sigma.js File. How i can do ?

Thank you (Stille waiting the answer).

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Duplicate of #1933
