### ISSUE TITLE
Gephi Geo Layout plugin shows wrong drop down menu

### ISSUE THREAD

**Issue by oliai** [gephi/gephi#1942]
## Steps to Reproduce

1.
2.
3.
4.

## Context:  Trying to create a geographical layout

 I cannot select the needed option in order to create the geographical layout and complete the project.  

## Your Environment

* Version used: Gephi 0.9.2
* Java version:   10 (64 bit)
* Operating System:  Windows 10

**Comment by oliai** [comment]
![geo layout error](https://user-images.githubusercontent.com/27318048/37871980-9bc34af4-2fca-11e8-8aff-b77502f58f1d.JPG)

**Comment by eduramiba** [comment]
It just shows attributes in your nodes table for you to choose, but it seems you don't have lat and long data in your nodes at all.
