### ISSUE TITLE
Citation for PageRank algorithm

### ISSUE THREAD

**Issue by sk721** [gephi/gephi#1944]
## Expected Behavior

When excecuting the PageRank Algorithmus a PageRank Report Page is shown. At the bottom under the heading "Algorithm:" the Source might be more accurate if it cites the actual source as: 
"Page, Lawrence and Brin, Sergey and Motwani, Rajeev and Winograd, Terry (1999) The PageRank Citation Ranking: Bringing Order to the Web. Technical Report. Stanford InfoLab."

## Current Behavior

When excecuting the PageRank Algorithmus a PageRank Report Page is shown. At the bottom under the heading "Algorithm:" the Source is given as: 
"Sergey Brin, Lawrence Page, The Anatomy of a Large-Scale Hypertextual Web Search Engine, in Proceedings of the seventh International Conference on the World Wide Web (WWW1998):107-117"

## Possible Solution

Change citation

## Steps to Reproduce

1. On the right sight choose the "Statistics" tab 
2. Press "Run" next to "PageRank"
3. Press "OK"
4. Scroll down the page to the bottom below the graph

## Context

The currently cited paper includes the following passage: "This ranking is called PageRank and is described in detail in [7]."
and
"[7] L. Page, S. Brin, R. Motwani and T. Winograd, The PageRank citation ranking: bringing order to the Web, Manuscript in Progress. http://google.stanford.edu/-backruh/pageranksub.ps"

I think therefore that this would make a better source for reference. I myself am trying to understand the PageRank implementation in Gephi and might have missed something. I'm glad for any feedback. 

The source I found (that is not a manuscript in progress) is found on http://ilpubs.stanford.edu:8090/422/
and has the citation: 
"Page, Lawrence and Brin, Sergey and Motwani, Rajeev and Winograd, Terry (1999) The PageRank Citation Ranking: Bringing Order to the Web. Technical Report. Stanford InfoLab."

I therefore propose using this citation. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by chihabalili** [comment]
give me the link plz =)

**Comment by eduramiba** [comment]
https://www.facebook.com/groups/gephi/

**Comment by chihabalili** [comment]
thank you

**Comment by jacomyma** [comment]
Well spotted @sk721! Fixed.
