### ISSUE TITLE
Gephi UI nearly unresponsive with large network (100% CPU utilization on one core)

### ISSUE THREAD

**Issue by KallyopeBio** [gephi/gephi#1947]
## Expected Behavior
I am loading a large network of 384K nodes and 9.4 million edges. Obviously, I expect this to challenge the software, but the UI is nearly unresponsive with this network loaded. For instance, it takes about 10 minutes just to recenter the graph view on the network. I disabled node and edge labels, disabled visualization of the edges, disabled anti-aliasing, and generally tried to turn off any feature that I thought could be computationally expensive. But these actions did not appear to make any difference. 

This problem happens under Ubuntu 16.04. Running the same network, on the same computer, but using Windows 10 (the machine dual boots under either Ubuntu or Windows 10), the UI is much more responsive. Instead of 10 minutes (under Ubuntu), the same UI operations now take about 1-2 seconds. That's about as fast as I would expect for a network this large. 

## Current Behavior
The UI is extremely slow to respond--about 10 minutes, regardless of the user action. One core on my machine is running at 100% utilization, non-stop. This is true even when Gephi is not executing any tasks. There is a background process that's maxing out the CPU. I've attached the log file. I'm happy to provide the network I'm using, if that will help. There are a number of prints in the log file pertaining to slowness. 

## Steps to Reproduce

1. Just load a large network. That's all. Start Gephi and then import the nodes and edges spreadsheets. The problem occurs right away.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
* Operating System: Linux Ubuntu 16.04
[messages.log](https://github.com/gephi/gephi/files/1866852/messages.log)

**Comment by KallyopeBio** [comment]
The problem persists even after switching to the oracle version of Java (using the same version of Java and netbeans as on the Windows machine)

**Comment by eduramiba** [comment]
We expect to improve rendering engine performance and responsiveness in a future version. Meanwhile you can try to use a more powerful computer, as some users have been able to render 30 million edges or more.

**Comment by KallyopeBio** [comment]
Keep in mind, it's not the hardware. Because I ran the same scenario twice _on the same machine_. When booting from Windows, it works fine. When booting from Ubuntu, and using the Ubuntu build of Gephi, it's much slower. 

I have 60 GB of RAM on my machine, which is more than Gephi needs in this scenario. I've tested machines with between 8 and 16 cores, but Gephi only uses one core during the slowness. On the Windows/Ubuntu dual boot machine, I have an NVIDIA Titan graphics card, which is a top-of-the-line graphics card. Which attributes of my system do you suggest I improve?

**Comment by eduramiba** [comment]
Oh I see, I advice you to use Windows if possible, as OpenGL drivers are often more optimized.
The Gephi build is identical for both systems.

Our current engine implementation uses the fixed pipeline of OpenGL, which is very CPU intensive and non-parallel. This will change in a future version.

**Comment by KallyopeBio** [comment]
OK. I'm experimenting with different Netbeans and Gephi Look&Feel settings. They make an appreciable difference in performance, for some reason I don't understand. I'll post here once again when I've found the combination of settings that maximizes performance on Linux. 

The reason why I won't switch to Windows is simply that my Windows machine is my personal computer. The machines I have in the lab all run on Linux.

**Comment by KallyopeBio** [comment]
Alright, I've now got the performance on my Ubuntu installation to be similar to the Windows machine. Probably the most important change I made was to uninstall the openjdk that ships with Ubuntu, and to replace it with the Oracle Java jdk, as Gephi instructions elsewhere suggest. Then, I also turned off anti-aliasing and pretty much any other setting in Gephi that I thought could slow performance.

**Comment by blas-ko** [comment]
Hello! I have the exact same performance issue (also using Ubuntu 16.04), but I'm kinda noobie here...

Which version of Oracle Java jdk should I use? How do I tell gephi to use that instead of openjdk? 

Thanks in advance.

**Comment by eduramiba** [comment]
@blas-ko You need to uncomment and change `jdkhome` line to point to the jdk you need. See https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by blas-ko** [comment]
Thanks a lot! It worked. :)
