### ISSUE TITLE
Alpha values is ignored when displaying node color

### ISSUE THREAD

**Issue by anastazie** [gephi/gephi#1949]
## Expected Behavior
I want nodes to be transparent, so when several nodes are on top of each other, you can see through them.

## Current Behavior
All nodes have the same not transparent color regardless alpha value
## Steps to Reproduce

Here is the example graph
```
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.3draft"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.gexf.net/1.3draft
       http://www.gexf.net/1.3draft/gexf.xsd"
      xmlns:viz="http://www.gexf.net/1.2draft/viz"
      version="1.3">
<graph mode="dynamic" defaultedgetype="directed">
<nodes>
<node id="1">
<viz:color r="255" g="0" b="0" a="0.9"/>
</node>
<node id="2">
<viz:color r="255" g="0" b="0" a="0.5"/>
</node>
<node id="3">
<viz:color r="255" g="0" b="0" a="0.3"/>
</node>
</nodes>
</graph>
</gexf>
```

## Context
I am using very dense layout (Graphviz plugin, sfdp, overlaps allowed). I want to be adle to see all overlaped nodes.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: openjdk version "1.8.0_151"
* Operating System:  Ubuntu 16.04

Thanks,
Anastazie

**Comment by nannabarnkob** [comment]
Hi Anastazie

Just came across your issue when trying to make this work as well. I found out that you cannot see the opacity in the preview, but it will show when you export your graph to pdf, at least when ticking off Per-node opacity in the 'Nodes' panel. 

A subset of my gexf-file looks like this: 
```
<?xml version='1.0' encoding='utf-8'?>
<gexf xmlns:viz="http://www.gexf.net/1.2draft/viz" version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static" name="">
    <attributes class="node" mode="static">
      <attribute id="0" title="Label" type="string" />
    </attributes>
    <meta>
      <creator>NetworkX 2.2</creator>
      <lastmodified>11/03/2019</lastmodified>
    </meta>
    <nodes>
      <node id="695_A01" label="695_A01">
        <viz:color a="0.5" b="255" g="0" r="0" />
        <attvalues>
          <attvalue for="0" value="695_A01" />
        </attvalues>
      </node>
</nodes>
</graph>
</gexf>
```
I am using:
- Gephi version 0.9.2 
- Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b0 
- System: Mac OS X version 10.14.3 running on x86_64; UTF-8. 

Maybe this helps you or someone else who ended up here. 

Best, 
Nanna

**Comment by mbastian** [comment]
Hi, by default in Preview the option "Per Node Opacity" is turned off but if you turn it on it should use the opacity value of your nodes.

<img width="343" alt="Screenshot 2022-03-04 at 19 14 52" src="https://user-images.githubusercontent.com/234813/156819762-530cab41-6d9e-424e-aaba-d24613429f13.png">
