### ISSUE TITLE
Possible to export node coordinates?

### ISSUE THREAD

**Issue by sacrilicious** [gephi/gephi#1952]
## Expected Behavior
Export calculated coordinates of nodes after layout is finalized.

## Current Behavior
Unable to export calculated coordinates of nodes.

## Possible Solution
Add an option to export X/Y coordinates for each node. 

This would allow for the node positions to be merged into the data that feeds into Tableau. 

Some forums linked to this plugin, but it is long out of date:
https://gephi.org/plugins/#/plugin/recast-column

## Context
I am looking into the possibility of importing social network coordinates into Tableau in order to allow end users to have an interactive figure.

I have tried exporting in various formats, but as far as I can tell there isn't one that contains the coordinates as determined by the various layout options. 

The data is structured in pairs (Every connection / edge has 2 lines of data: one for the source and one for the target), with each line being mapped and a path being drawn between them. It is a bit of a workaround in Tableau as it results in multiple overlapping nodes and the network wouldn't adapt to filters in Tableau, but it would allow them to more easily find and highlight points of interest than a static image.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: jre1.8.0_161
* Operating System: Windows 7 Enterprise

**Comment by eduramiba** [comment]
Hi,
You can export to gexf and it will include that data, but it's XML and you will need to process it.

**Comment by sacrilicious** [comment]
Thanks! It looks like I can import it into excel to create a line listing, and then import into SAS (or other software) to pull out the ID and related coordinates. It's a bit of a process switching between formats and applications but it will get the job done.

**Comment by eduramiba** [comment]
Awesome!

**Comment by csanhuezalobos** [comment]
Do you have a script to get the positions of the final visualization? I couldn't import in excel to get a line listing as you described. Any ideas?

**Comment by sacrilicious** [comment]
Hi Csanhuezalobos,

Unfortunately I do not have a script for this. It required a manual multi-step process. 

The process used was:

1. In Gephi, File>Export Graph File>Save as .gexf file
2. In Excel, open the .gexf file (you may get several warnings during this process, click OK for each to continue).
The resulting spreadsheet will be broken into 3 sections: stratifying variables that were in Gephi, node info, and edge info. Each of these sections will have its own variables that are applicable to it. 

So depending on what you wanted to do with the exported data, you will use these different sections. 

In my case, because I was wanting to pull it into Tableau for an interactive SNA, I used the gephi-generated node coordinates from the node info section in the .gexf file and match them back into the data feeding into Tableau (which required a bunch of other prep/structuring).

**Comment by Talamantez** [comment]
From Gephi, if you activate Tools > Plugins > Available Plugins > JSON exporter, then you can choose File > export > Graph file, and choose the 'JSON Graph File' option.  This allows you to side-step processing a gexf file.

**Comment by mbastian** [comment]
Thanks, let me summarise.

### Definition of done
- Possibility to export node coordinates. Those columns could be shown as part of the export column chooser. Those columns should be disabled by default.
