### ISSUE TITLE
Unable to launch Gephi on Windows 7

### ISSUE THREAD

**Issue by zurbo97** [gephi/gephi#1954]
## Expected Behavior

Click on Gephi icon to launch

## Current Behavior

After appearing to load the application fails to launch.

I tried changing java path in gephi.conf as follows:

```
# default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
jdkhome="C:\Program Files (x86)\Java\jre1.8.0_161"
```

...but no luck there either.

Also not finding anything in the log file (completely empty), assuming I should be looking here:
C:\Users\<User>\AppData\Roaming\.gephi\0.9.2\dev\var\log

## Steps to Reproduce

1. Download Gephi
2. Attempt to run Gephi

## Your Environment

* Version used: Gephi 0.9.2
* Java version: jre1.8.0_161
* Operating System: Windows 7

**Comment by EffectiveLabs** [comment]
I have the same issue on Windows 10

**Comment by ericmubo** [comment]
Had the same issue on Win 10 and jre1.8.0_171 32bits.
Installed 64-bit Java, works perfectly now.
Thanks to zurbo97 for the hint (pointing to x86/32bit Java).

**Comment by wetneb** [comment]
This should be solved by the inclusion of a JRE in in the Windows distribution. Check out the new release coming soon!
