### ISSUE TITLE
gephi 0.9.2 does not display the appearance in the overview window with Mac

### ISSUE THREAD

**Issue by pw225** [gephi/gephi#1955]
## Expected Behavior
I want to import LesMiserables.gexf in order to reproduce the graph and work on it. The data is being imported correctly as I can see all the information about the nodes and edges in the data laboratory but I can't see anything in the overview. Please help as I have no idea as to what I should do. I rebooted my computer, uninstalled and reinstalled Gephi but without seeing any difference. Could be a problem with Java but not sure what should be done about it. Tried to reinstall an older version but didn't seem to help. Anyone also had the same problem?

See the screenshots attached.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Version 8 update 171
* Operating System: macOS 10.13.4

![screen shot 2018-04-17 at 22 56 23](https://user-images.githubusercontent.com/38478018/38901734-4a34804e-4295-11e8-956e-a415c007b9e2.png)
![screen shot 2018-04-17 at 22 56 36](https://user-images.githubusercontent.com/38478018/38901737-5322b5ea-4295-11e8-8e3e-651f9fbdbf90.png)
![screen shot 2018-04-17 at 22 56 52](https://user-images.githubusercontent.com/38478018/38901742-573c5bea-4295-11e8-8740-0673293d34db.png)

**Comment by eduramiba** [comment]
It seems you closed the Graph window, please try to reopen it or reset windows in Window menu.

**Comment by pw225** [comment]
How embarrassing. Works! Thank you!
