### ISSUE TITLE
Cannot reopen tabs in overview 

### ISSUE THREAD

**Issue by cannyasj** [gephi/gephi#1958]
I accidentally closed the tabs in the overview section and not reopen them. What should I do?

![screen shot 2018-04-21 at 9 23 46 pm](https://user-images.githubusercontent.com/38599610/39091659-c1879e18-45ad-11e8-8b18-518957c9f32d.png)

**Comment by eduramiba** [comment]
You can reset them in the Window menu

**Comment by cannyasj** [comment]
Where can I find the window menu?

**Comment by eduramiba** [comment]
It should be in the menu bar like other applications
