### ISSUE TITLE
Gephi Graph not showing up

### ISSUE THREAD

**Issue by siriusblac37** [gephi/gephi#1959]
## Expected Behavior
Graph should show up.

## Current Behavior
Process hanging at 'Graph Initialization step

## Steps to Reproduce

1. Open "Les Miserables.gexf" file (or any other graph file)
2. The Graph window will be showing "Initializing..". But nothing happens. Graph never shows up.

## Context
Basic task of gephi

## Your Environment

-------------------------------------------------------------------------------
>Log Session: Wednesday, April 25, 2018 at 3:05:15 PM Central European Summer Time
>System Info:
  Product Version         = Gephi 0.9.2 201709241107
  Operating System        = Linux version 4.13.0-39-generic running on amd64
  Java; VM; Vendor        = 10.0.1; Java HotSpot(TM) 64-Bit Server VM 10.0.1+10; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 10.0.1+10
  Java Home               = /usr/lib/jvm/java-10-oracle
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /root

**Comment by eduramiba** [comment]
Oh also java 10 or 9 support is not tested, try 8

**Comment by siriusblac37** [comment]
Yup works with java 8! Thanks..
