### ISSUE TITLE
Unable to launch Gephi on Ubuntu 18.04

### ISSUE THREAD

**Issue by sergiomelo37** [gephi/gephi#1962]
The Gephi 0.9.2 doesn't start.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java-8-oracle
* Operating System: ubuntu 18.04

**Comment by eduramiba** [comment]
Does it crash? Make sure to have up to date opengl drivers. Please try to install latest mesa drivers (even beta, but after 17.0, they work really well).

If still not working, try to force software rendering.

**Comment by sergiomelo37** [comment]
It worked. I've enabled my NVIDIA drive in the "Additional Drives" tab in the "Programs and Updates" software of UBUNTU 18.04. Worked perfectly. Thank you.
![captura de tela de 2018-05-05 09-59-44](https://user-images.githubusercontent.com/38961653/39664097-2779606e-504c-11e8-9539-d08491f1cbe5.png)

**Comment by eduramiba** [comment]
Great!

**Comment by shiwakant** [comment]
Nvidia 390 driver has some issues and not letting my GTX 950 come out of sleep(Blank screen and non functional keyboard).

**Comment by arsalanrajabi90** [comment]
I'm using Linux 18.04 and gephi 0.9.2. There is apparently a problem with plugins. It's only showing Updates tab, and not showing the other tabs (Available Plugins, Downloaded, Installed, Settings). 

How should I fix this?

**Comment by eduramiba** [comment]
@arsalanrajabi90 That's really strange, did all modules load correctly? Please try to download again Gephi and clean up the Gephi user directory: https://github.com/gephi/gephi/wiki/Troubleshooting

**Comment by MohammadHeydari** [comment]
I got the same error. 
I already set the nVidia Driver as mentioned above. 
can you help me out to solve the issue?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/mohammad/Downloads/Compressed/gephi-0.9.2-linux/gephi-0.9.2/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Gtk-Message: 21:07:02.389: Failed to load module "canberra-gtk-module"
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by eduramiba** [comment]
@MohammadHeydari Please make sure to run Gephi with Java 8. Newer versions are not supported yet.

**Comment by s-tikhomirov** [comment]
Still get this error on Ubuntu 18.04.3 after

* updating the drivers to the latest version (nvidia-driver-430) as described by @sergiomelo37 
* installing Java 8 alongside Java 11 as described [here](https://askubuntu.com/questions/1133216/downgrading-java-11-to-java-8)

When I add
```
jdkhome="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"
```
to `etc/gephi.conf` though, I get
```
Cannot find java. Please use the --jdkhome switch.
```
The command
```
./bin/gephi --jdkhome /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

yields the same error. What does it mean to use the `--jdkhome` switch then?

**Comment by eduramiba** [comment]
Hi @s-tikhomirov `jdkhome` should be the directory of jdk (`/usr/lib/jvm/java-8-openjdk-amd64`) and not the `java` binary in it.

**Comment by s-tikhomirov** [comment]
Thanks a lot, @eduramiba , it worked!
