### ISSUE TITLE
How to refer to another column's value in the Data Table Editor (Excel-like workflow)

### ISSUE THREAD

**Issue by tbop** [gephi/gephi#1964]
## Expected Behavior
I am creating extra columns to determine extra attributes that should be computed depending on other dynamical values (such as Degree).

For instance I'm adding the column Dynamic_Value to my Nodes and I want this column to automatically compute for each node $Degree/$Out-Degree.

How can I do this?

**Comment by eduramiba** [comment]
Not implemented or planning to implement, please use excel for that.

Also, maybe you can use the Scripting plugin to create and fill that column: https://github.com/gephi/gephi/wiki/Scripting-Plugin

**Comment by tbop** [comment]
Ok thanks!
