### ISSUE TITLE
Set up was unable to create directory

### ISSUE THREAD

**Issue by KirtiMakwana** [gephi/gephi#1965]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Operating system? Anyway, make sure the installer has permissions to write files where you are trying to install.

**Comment by KirtiMakwana** [comment]
When I install it.. the system shows an error - " The system was unable to create the directory"
![new bitmap image](https://user-images.githubusercontent.com/39092686/39762496-b80d4c98-52d2-11e8-8f42-fae3837fc627.jpg)

**Comment by eduramiba** [comment]
Try one of these:

* Run as administrator
* Install on a user folder where you have permissions
* Download the .tar.gz and just extract and run gephi64.exe in bin folder: https://github.com/gephi/gephi/releases/download/v0.9.2/gephi-0.9.2-sources.tar.gz

**Comment by KirtiMakwana** [comment]
#eduramiba... is Microsoft Windows OS... and the I have all the administrator rights to install all the software.

**Comment by eduramiba** [comment]
Did it work?

**Comment by KirtiMakwana** [comment]
Yes..

Thanks

**Comment by eduramiba** [comment]
Great!
