### ISSUE TITLE
Node size ranking just on filtered nodes

### ISSUE THREAD

**Issue by jorgealemangonzalez** [gephi/gephi#1968]
## Expected Behavior

When you change the size of the nodes depending on some ranking attribute, it should only consider the visible ( =filtered ) nodes. Same if you filter the graph after a ranking sizeing have been made, the sizes must be recomputed to reflect the new sizing depending only on the filtered nodes.

## Current Behavior

When you do a sizeing based on some ranking, it calculates the size of all the nodes in the graph, not only the filtered (= visible) ones.

## Steps to Reproduce

1.
2.
3.
4.

## Context

When there are nodes with high ranking differences and you set the size based on that raking, it is difficult to see the smallest ones. So maybe the biggest ones are not important and you want to make a filter. The result is that the size of the filtered nodes is really similar, because of the high differences with the bigger ones (which are no more in the view, the have been filtered).

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: Windows 10

Team: @tzadro @guinii

**Comment by mbastian** [comment]
Hi, we've made some [improvements](https://github.com/gephi/gephi/issues/2146) in the Appearance implementation and this should no longer be an issue. One can toggle between the global (all) and local (filtered) modes to calculate ranking boundaries.
