### ISSUE TITLE
Export Bug。Formate：PDF。circles are not shown，edges are ok

### ISSUE THREAD

**Issue by xilenovo** [gephi/gephi#1969]
## Expected Behavior
Export in PDF with circles 
## Current Behavior
no circles
## Possible Solution
PNG's DPI  is not enough

## Steps to Reproduce

1.sorry, I think I‘ve made it clear above~ Thx
2.
3.
4.

## Your Environment
win10 , Chinese
* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
This is a problem caused by the polygon shaped nodes plugin: https://github.com/gephi/gephi/issues/1907
