### ISSUE TITLE
Error trying to open Gephi project

### ISSUE THREAD

**Issue by cmilhorance** [gephi/gephi#1971]
## Current Behavior
I try to open an old gephi project. The software is launched, but the project does not open. Nothing happens. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: windows 10

**Comment by aldou** [comment]
Duplicate of issue #1997 
Check the workaround explained over there.

**Comment by wetneb** [comment]
Closing as duplicate of #1997.
