### ISSUE TITLE
Gephi 0.9.2 stuck while starting modules

### ISSUE THREAD

**Issue by borisy42** [gephi/gephi#1974]
## Expected Behavior
Start Gephi app

## Current Behavior
Gehpi splash screen is stuck at "Staring modules..." stage

## Steps to Reproduce

1. Start Gephi 0.9.2
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2 201709241107
* Java version: 1.8.0_162; Java HotSpot(TM) 64-Bit Server VM 25.162-b12; Oracle Corporation
* Operating System: Windows 10 version 10.0 running on amd64 (Build 14393)

[messages.log](https://github.com/gephi/gephi/files/2089279/messages.log)

**Comment by eduramiba** [comment]
Please try the usual recommendations:

https://github.com/gephi/gephi/issues/1831
https://github.com/gephi/gephi/issues/1631
https://github.com/gephi/gephi/issues/1905
https://github.com/gephi/gephi/issues/1664

**Comment by jsalbr** [comment]
Hi, I'm still getting this issue, like many others I suppose and posted a question in #1631.
I'm using Windows 10 with jdk1.8.0_171. 

Interestingly, after about an hour of hanging, Gephi continued working.

Message log does not show any errors. It stops after printing the classpath in System Info, then continues with a warning. Unfortunately, the log does not contain timestamp per line.

Find the complete log attached, maybe it helps identifiying the issue.
[messages.log](https://github.com/gephi/gephi/files/2155312/messages.log)

**Comment by Andrew-Michael** [comment]
I solving  deleting non-native system operational library jar. I left the following libraries "jogl-all-natives-windows-amd64, jogl-all-natives-windows-i586, jogl-all" in the org-jogamp-jogl folder and "gluegen-rt-natives-windows-amd64, gluegen -rt-natives-windows-i586, gluegen-rt "folder in org-jogamp-gluegen.
{Directory_install}\gephi\modules\ext\org.gephi.visualizatio.

**Comment by beralves** [comment]
Finally a solution that works! Thank you @Andrew-Michael 

> I solving deleting non-native system operational library jar. I left the following libraries "jogl-all-natives-windows-amd64, jogl-all-natives-windows-i586, jogl-all" in the org-jogamp-jogl folder and "gluegen-rt-natives-windows-amd64, gluegen -rt-natives-windows-i586, gluegen-rt "folder in org-jogamp-gluegen.
> 
> > > > On {Directory_install}\gephi\modules\ext\org.gephi.visualizatio.

**Comment by EricSP2** [comment]
I've deleted the JAR's Andrew susggested and it doesn't work...

I've also added all the following exclusions to the Trend Micro AV:

*\USERS\*\JOGAMP_EXE_TST*.EXE
*\USERS\*\APPDATA\LOCAL\TEMP\1\JOGAMP_EXE_TST*.EXE
*\Windows\Prefetch\GEPHI64.EXE-*.pf
*\USERS\*\AppData\Local\temp\jogamp_exe_tst*.exe

Directories:

*\USERS\*\AppData\Roaming\.gephi\*\dev\lock
*\USERS\*\AppData\Local\temp\1\jogamp_0000
*\USERS\*\AppData\Local\temp\1\hsperfdata_*
*\USERS\*\AppData\Local\temp\1\jna-*
*\Program Files\Gephi-*
*\Program Files (x86)\Gephi-*

And even still, it doesn't load properly, but as soon as I turn off the AV it loads PRESTO....

Am I missing anything?

**Comment by hodzanassredin** [comment]
Solved by removing jogl-all-natives-windows-i586.jar and gluegen-rt-natives-windows-i586.jar

**Comment by NuansaGIS** [comment]
> Saya memecahkan penghapusan jar perpustakaan operasional sistem non-asli. Saya meninggalkan perpustakaan berikut "jogl-all-natives-windows-amd64, jogl-all-natives-windows-i586, jogl-all" di folder org-jogamp-jogl dan "gluegen-rt-natives-windows-amd64, gluegen -rt-natives-windows-i586, gluegen-rt "folder di org-jogamp-gluegen.
> 
> > > > Pada {Directory_install} \ gephi \ modules \ ext \ org.gephi.visualizatio.

Terimakasih ini sangat Membantu

**Comment by jayssie1212** [comment]
Thanks a lot, perfect solution for me. @Andrew-Michael

**Comment by Trixx-Darthor** [comment]
This solution did not work for me on:
Win10 64x
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
16 GB RAM

I tried different combinations of deleted files to no avail.
