### ISSUE TITLE
Modularity index groups are allways 0-index based.

### ISSUE THREAD

**Issue by jorgealemangonzalez** [gephi/gephi#1977]
## Expected Behavior
Each time you execute the modularity algorithm it should ask you for an index (k) from which the algorithm will start adjudging indexes to groups. The output will be k-based instead of 0-based.

## Current Behavior
The output of this algorithm is allways 0-based, it always starts with 0.

## Possible Solution
To have an input box to insert k and then after the algorithm runs add this number to all indexes. Resulting in a k-index based list.

## Steps to Reproduce

1. Go to Statistics -> Modularity -> Execute -> Accept
2. The algorithm creates N groups and gives a 0-index based ID
3. Filter some nodes
4. Go to Statistics -> Modularity -> Execute -> Accept
5. The algorithm creates N groups and gives a 0-index based ID (There is no way of changing the index in which it starts)
6. Stop the filter
7. The groups with the same ID will be mixed.

## Context
Filtering and runing the modularity algorithm inside different groups (Man , Women)
## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: Windows 10

Team: @tzadro @guinii

**Comment by jacomyma** [comment]
I reimplemented @jorgealemangonzalez's solution from PR https://github.com/gephi/gephi/pull/1978 in commit https://github.com/gephi/gephi/commit/4b9b81d6e9dcf317e74ec54fe3d288ec4bc09296. Thanks to him and kudos!
