### ISSUE TITLE
Gephi (0.9.1 AND 0.9.2) freeze on "Starting Modules" (MEMORY AND JAVA FIXES APPLIED, STILL DOESN'T WORK)

### ISSUE THREAD

**Issue by LCSFan** [gephi/gephi#1981]
## Expected Behavior
I launch Gephi (both 0.9.1 and 0.9.2) from the bin .exe (using the x64 version to match my OS). I've modified the config file to increase the memory and switch to a x64 copy of Java. 

My AV is off, I ran it as administrator. 

## Current Behavior

It quickly loads, at first, then freezes on the "Starting modules" page. 

## Possible Solution

Insufficient memory? I get the little swirling circle on my mouse when it reaches this phase, then nothing happens. 

## Steps to Reproduce

1. Start Gephi (from the x64 .exe)
2. Wait
3. Nothing, it freezes

## Your Environment

* Version used: Gephi 0.9.2 AND 0.9.1, both do the same.
* Java version: I've tried a bunch, but I'm currently pointing at "C:\Program Files\Java\jre1.8.0_171"
* Operating System: Win 7 Pro, x64, 3.7 GB usable memory

**Comment by eduramiba** [comment]
Usually this is caused by the graphics card drivers, please try to update them and make sure your system is using the correct graphics card in case you have more than one.

**Comment by LCSFan** [comment]
Thanks for the suggestion! 

My graphic drivers are up to date, however, it's not a very powerful graphic device (internal laptop graphics,  Intel HD 5500), and I suspect I may need to find a desktop to make Gephi work.
