### ISSUE TITLE
Dynamic Graph - how to use time format "yy:mm:dd: hh:mm:ss"?

### ISSUE THREAD

**Issue by Marmeladenbrot** [gephi/gephi#1984]
The official forum is down and the facebook group is useless so I ask here, if there is a normal way/location to ask Gephi questions please link them.

I want to create a retweet network from some .csv file with twitter data. I know how to create a network from this .csv format.
This data has also timestamps in the format "2018-02-25 03:44:34" and I would like to use this timestamps to create a dynamic graph where I can see the network changes over time.

All tutorials/guides don't seem to use timestamps at all but rather some weird format like here (https://github.com/gephi/gephi/issues/1303), is my format even useable for a dynamic graph and if yes how does it need to be formatted?

Thanks in advance and best regards
Marmeladenbrot

**Comment by eduramiba** [comment]
Hi,
You can enter [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) timestamps in the column and should be parsed correctly, so your datetime is almost correct.

I think we will add support for parsing your date format directly in the future.

**Comment by Marmeladenbrot** [comment]
Thank you,

then I just need to parse my time format into the ISO format (some Python magic should do the trick) and it will work. That's great to hear.

**Comment by eduramiba** [comment]
Great!

**Comment by Marmeladenbrot** [comment]
I know have Edges and Nodes created from my .csv file.

The time format is in ISO 8601.

`Source,Target,Timestamp
37956761,1734940808,2018-02-25T08:10:17Z
4046578499,1734940808,2018-02-25T08:14:55Z
127196685,1734940808,2018-02-25T08:31:50Z`

But when I import this Edges into Gephi it is not recognized as a dynamic graph and the timestamps are in a weird format like

> <[1519546217000.0]>
> <[1519546495000.0]>
> <[1519547510000.0]>

What did I do wrong?

**Comment by eduramiba** [comment]
Yeah that's fine, it's the milliseconds unix timestamp. It's just a visualization configuration that Gephi is not picking up automatically at the moment, but you can change the time representation in the Configuration dialog in data laboratory so it shows datetime instead.

**Comment by eduramiba** [comment]
Hi,
At the moment, the only standard dynamic column is the 'timeset' column. Please try to name your column 'timeset' instead of Timestamp, the data should appear next to the label column.

**Comment by Marmeladenbrot** [comment]
Ah I see, after changing my csv header for that field I can now click "Enable Timeline" in the bottom.

But when I try to play the sequence I get an error message: "Cannot animate timeline without an animation interval. Set one before clicking a play button"

I have set an interval via "Set custom bounds..." (first to last timestamp) and set Speed and Step Size via "Set play settings...". Even if I change the interval from one day after the first timestamp to the last the error remains.

All google results lead to the forum which is down.

What am I missing to get the play button to work?

Google leads me to this: https://github.com/gephi/gephi/blob/master/modules/DesktopTimeline/src/main/resources/org/gephi/desktop/timeline/Bundle_ja.properties (line 10) and it seems there is a typo as well ("playButton.intevalNotSet")

My Graph file: https://www.dropbox.com/s/mv5tppxnb94ief6/fixed_tweets_johanniter_datensatz1_retweet_fulltext_Without_Johnnys.gephi?dl=0

**Comment by eduramiba** [comment]
Hi, you just need to drag the play window start and end bounds so they don't cover the whole timeline.

**Comment by Marmeladenbrot** [comment]
Ah, now that makes sense ... hurray, it works. Thanks a lot.

But another problem approached. Fix one, get one it seems.

I have duplicate Nodes but with different timestamps because I extract the Nodes+Edges from a large (2,5Gb) csv file.
If I import my nodes.csv file those Nodes get merged into one single Node but the timestamp information from the duplicate Nodes are lost without any chance to prevent this.

For Edges this seems to be fixed (https://github.com/gephi/gephi/issues/1282) but not for Nodes. Is it possible to enable the same merging strategy for Nodes?

**Comment by eduramiba** [comment]
Hi, the merge strategy affect only edge weights.

Nodes are merged if their ids are the same (is that your case?), and I thought timestamps were already being merged correctly for nodes too, or at least it should be working fine, I will have to test it.

Here we detect and merge nodes by id: https://github.com/gephi/gephi/blob/master/modules/ProcessorPlugin/src/main/java/org/gephi/io/processor/plugin/DefaultProcessor.java#L193

Here the timeset attribute is merged as in edges: https://github.com/gephi/gephi/blob/master/modules/ProcessorPlugin/src/main/java/org/gephi/io/processor/plugin/AbstractProcessor.java#L183

**Comment by Marmeladenbrot** [comment]
Yes, the IDS are the same. I counted the number of distinct IDs in my node file via Tableau and got 195.475 unique nodes (from ~2,11 million nodes in total in the node file).

But when I load the node file in Gephi I get a lot of duplicate warnings (that's expected) but also an error: "[Record #7,706] The record is inconsistent. Skipping record"
When I look into my nodes file at line 7707 (because of header line) I can't find anything wrong with the line or the lines before and after.

And when import the nodes Gephi only gives me ~4k nodes instead of 195k in the preview screen before you click "Okay" to finalize the import.
And the timestamps are not merged. For edges they are but the edge weight is not merged, every edge is "1.0" while there are duplicate edges in there so some edge weights should be 2, 3 or higher.

Also, when I import the edge file it creates ~190k missing nodes even when "creating missing nodes" is disabled when importing Edges/Nodes?

Edge file: https://www.dropbox.com/s/x1eyyv0w184humx/fixed_tweets_krisenarten_datensatz2_retweet_fulltext_Edges.csv?dl=0

Node file: https://www.dropbox.com/s/qcispiey9ildzmb/fixed_tweets_krisenarten_datensatz2_retweet_fulltext_Nodes.csv?dl=0

Gephi is up to date, 64bit, has 11gb RAM in the config file.

**Comment by Mohammadsalehkohandel** [comment]
Hi, I try to set Date Time with format Y-m-dTH:M:fZ' but gephi only display date, how can I fix that ?
