### ISSUE TITLE
'Interval' not copied to new workspace  

### ISSUE THREAD

**Issue by piranha32** [gephi/gephi#1988]
When part of a dynamic graph is copied in "Data Laboratory" to a new graph, values in "Interval" column are copied a blank.
## Expected Behavior
Values of intervals copied to new workspace

## Current Behavior
Blanks instead of proper interval values after copuing to new workspace

## Steps to Reproduce

1. Load dynamic graph with intervals defined in spells.
2. In Data Laboratory select several nodes.
3. Right-click on the selected nodes, "Copy to...", and "New Workspace"

## Context
The bug makes it difficult to analyse dynamic graphs. As a workaround for the bug the full dynamic graph can be saved to a new file, and non-selected nodes deleted (inverse of selection of nodes), but that adds a lot of unnecessary work.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_162; Java HotSpot(TM) 64-Bit Server VM 25.162-b12
* Operating System:  Linux, MacOS
![screenshot_20180630_171608](https://user-images.githubusercontent.com/680825/42129095-4ab6dab6-7c89-11e8-8b1d-0437420c3300.png)
![screenshot_20180630_171558](https://user-images.githubusercontent.com/680825/42129096-4ac048da-7c89-11e8-9ed1-6bd2344dbad6.png)

**Comment by lipchev** [comment]
Quite annoying...all other time-set values are copied correctly. I tried creating a copy of my interval column but that inevitably results in a cast exception when copying/moving/creating workspace from filter:

> org.gephi.graph.api.types.IntervalSet cannot be cast to org.gephi.graph.api.types.TimeMap

My best workaround is to copy the interval column to a new string column, and in the new workspace do a 'Copy data to other column" filling in the interval with my string column values.

**Comment by mbastian** [comment]
Thanks for the report, this issue is now fixed and will be included in the upcoming 0.9.3 release.
