### ISSUE TITLE
Gephi can not open a file: nothing happens.

### ISSUE THREAD

**Issue by RRKLRRKL** [gephi/gephi#1990]
## Expected Behavior
Open file.

## Current Behavior
Empty views.

## Possible Solution
Rewrite Gephi code and add the feature to open a Gephi file.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by aldou** [comment]
Duplicate of issue #1997 
Check the workaround explained over there.

**Comment by wetneb** [comment]
Closing as duplicate of #1997 then.
