### ISSUE TITLE
gephi macos unable to load libjogl_awt.jnilib

### ISSUE THREAD

**Issue by ghost** [gephi/gephi#1992]
-------------------------------------------------------------------------------
>Log Session: Thursday, July 5, 2018 9:25:26 AM CST
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Mac OS X version 10.12.6 running on x86_64
  Java; VM; Vendor        = 1.6.0_65; Java HotSpot(TM) 64-Bit Server VM 20.65-b04-468; Apple Inc.
  Runtime                 = Java(TM) SE Runtime Environment 1.6.0_65-b14-468
  Java Home               = /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
  System Locale; Encoding = zh_CN (gephi); EUC_CN
  Home Directory          = /Users/baixiaoqiang
  Current Directory       = /
  User Directory          = /Users/baixiaoqiang/Library/Application Support/gephi/0.8.2/dev
  Cache Directory         = /Users/baixiaoqiang/Library/Application Support/gephi/0.8.2/dev/var/cache
  Installation            = /Applications/Gephi.app/Contents/Resources/gephi/gephi
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
                            /Applications/Gephi.app/Contents/Resources/gephi/platform
  Boot & Ext. Classpath   = /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsfd.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar:/System/Library/Frameworks/JavaVM.framework/Frameworks/JavaRuntimeSupport.framework/Resources/Java/JavaRuntimeSupport.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/ui.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/laf.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/sunrsasign.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jsse.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/jce.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/charsets.jar:/System/Library/Java/Extensions/MRJToolkit.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/apple_provider.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/ext/sunpkcs11.jar
  Application Classpath   = /Applications/Gephi.app/Contents/Resources/gephi/platform/lib/boot.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-modules.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util-lookup.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/org-openide-util.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/boot_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/dt.jar
  Startup Classpath       = /Applications/Gephi.app/Contents/Resources/gephi/platform/core/core.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/org-openide-filesystems.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/core_zh_TW.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_de.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_es.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_it.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_si.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/Applications/Gephi.app/Contents/Resources/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/Applications/Gephi.app/Contents/MacOS/../Resources/gephi/bin/../gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
SEVERE [org.netbeans.core.modules]
java.lang.NullPointerException
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.getSuperIdentity(AutoupdateSettings.java:435)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings.generateIdentity(AutoupdateSettings.java:136)
	at org.netbeans.modules.autoupdate.ui.actions.AutoupdateCheckScheduler.signOn(AutoupdateCheckScheduler.java:110)
	at org.netbeans.modules.autoupdate.ui.actions.Installer.restored(Installer.java:63)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:469)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:392)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:103)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:344)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:619)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:607)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:603)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:623)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:341)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1179)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1002)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:296)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:169)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:695)

**Comment by eduramiba** [comment]
Does this happen with Gephi 0.9.2?
