### ISSUE TITLE
Dynamic Gephi Data Format

### ISSUE THREAD

**Issue by juliannej** [gephi/gephi#1998]
Is it possible to use the built in dynamic features Gephi provides with a data format like this:

ID, Name, 0h, 0.5h, 3h
1, Foo, 0.123, -0.345, 0.333

I am trying to look at the change over time but my time intervals are exclusively column names.. I am hoping to not have to transform the data to 3 lines per entry because there are 25,000 entries and the edges table relies on that ID, so that would have to be totally redone too. 

* Version used: Gephi 0.9.2

**Comment by eduramiba** [comment]
Hi,
This kind of format is not supported by Gephi, you could transform it to dynamic number notation as explained in https://gephi.org/users/supported-graph-formats/spreadsheet or use GEXF

**Comment by eduramiba** [comment]
Hi,
Not sure what you mean with repeated ids.

You just need to change that data to something like this.

Nodes:

```csv
id,label,dynamic_thing
1,Foo,"[2018-07-21T00:00:00, 0.123]; [2018-07-21T00:30:00, -0.345]; [2018-07-21T03:00:00, 0.333]"
```

Edges:
```csv
source,target
1,2
2,5
1,...
```

No need to provide ids for edges unless you want to.

**Comment by juliannej** [comment]
Thank you so much for the information! So helpful. It makes sense now :)

**Comment by juliannej** [comment]
Hi - I want to use those decimal numbers to change node color or size over time, but it is not showing me the dynamic_stuff attribute in the ranking section for the nodes. I am confused about how to access those values.

I formatted it as you suggested:


id,label,dynamic_thing
1,Foo,"[2018-07-21T00:00:00, 0.123]; [2018-07-21T00:30:00, -0.345]; [2018-07-21T03:00:00, 0.333]"

The values I want to use for ranking the nodes are: 0.123, -0.345, 0.333.

**Comment by eduramiba** [comment]
Hi,
When importing that data, make sure the column is imported as type `TimestampDoubleMap` (which means a dynamic timestamp-based double precision decimal).

Then, in appearance window, when you apply the style, make sure to click on the small 'apply continuously' button, so when you play with the timeline, the appearance is re-applied for the visualized time window.

Make also sure to configure time format to 'Datetime' in the timeline, so data make sense (yeah, this needs improved usability).

Then, just make a small timeline window by dragging the edges and slide it or hit play.

**Comment by juliannej** [comment]
As things are written - with the double quotes, it seems unable to accept that as a TimestampDoubleMap, and I don't see how to write it into the CSV not as a string (I am using pandas).

**Comment by juliannej** [comment]
`new_df.loc[n] = pd.Series({'SPOT': row[1], 'Label': row[2], 'Dynamic_data': \
      "[2018-07-21T00:00:00, " + str(row[3]) + "]; " + \
      "[2018-07-21T00:30:00, " + str(row[4]) + "]; " + \
      "[2018-07-21T03:00:00, " + str(row[5]) + "]; " + \
      "[2018-07-21T06:00:00, " + str(row[6]) + "]; " + \
      "[2018-07-21T12:00:00, " + str(row[7]) + "]" })`

This is how I have written the data. The original rows are the decimal numbers, as discussed before.

**Comment by juliannej** [comment]
As you can see, I have been relying on strings.

**Comment by eduramiba** [comment]
If you use a CSV writing library, it should take care of the quotes automatically. They are necessary in CSV so commas inside values are not interpreted as column separations.

So, in your code, you should not need to add quotes at all, just write the value.

**Comment by juliannej** [comment]
I wasn't able to exclude the quotes - it seemed to be an error interpreting the timestamp value. Could you write an example line of what you mean?

**Comment by juliannej** [comment]
Nevermind - I got it to work with the strings.

**Comment by juliannej** [comment]
This has been very helpful - thank you
