### ISSUE TITLE
Cannot communicate with Java on my computer

### ISSUE THREAD

**Issue by mquandt** [gephi/gephi#2001]
## Expected Behavior
Download Gephi onto my computer.
## Current Behavior
When installation finishes and tries to launch, I receive an error message: "Cannot find Java 1.8 or higher." I have Java 1.8 (re-installed today), and I've rebooted my computer multiple times, uninstalled and reinstalled Java and Gephi, and made sure to clean out any old versions of Java.
## Possible Solution
Somehow permission isn't being given for Gephi to access my other programs.

## Steps to Reproduce

1. Download Gephi installer
2. Install Gephi; have the "launch Gephi" box checked when clicking "finish" on installer.
3.
4.

## Context
Attempting to create social network analysis of research exemplars for the purpose of a publication in the journal Molecular Cell. Thank you for your help!

## Your Environment
Medical school campus

* Version used: Gephi 0.9.2
* Java version: 1.8 (updated today)
* Operating System: Windows 10 Enterprise 2015 LTSB 64-bit 8 GB Installed RAM

**Comment by eduramiba** [comment]
Duplicate of #1787 Please try the suggestions there
