### ISSUE TITLE
Geo Layout gives no latitude longitude when edges are added

### ISSUE THREAD

**Issue by ArSunnyBansal** [gephi/gephi#2003]
Till the point I add nodes, geo layout gives the option to select latitude longitude from my attribute data. And it shows my nodes as per their location.
Once I add edges, the geo layout does not give the option to select latitude longitude from my attribute data. In the drop down list in front of latitude and longitude in the geo layout there is nothing.
Please help!

**Comment by wetneb** [comment]
hello! It seems unlikely that we can fix this issue without having a sample file. Therefore I am closing this issue for now but would be happy to reopen it if you can provide a sample file. Thank you!
