### ISSUE TITLE
Bundle issue

### ISSUE THREAD

**Issue by juliannej** [gephi/gephi#2008]
I am making a gephi plugin that is a modification on the FA2 algorithm a la the multi gravity plugin. I am trying to launch my plugin and getting an error. My plugin is called node-weight, but I left classes (ForceAtlas2 and associated classes) with their original names. I am looking for any leads broad or specific on what I might do to correct this issue.

Thanks!

## Expected Behavior
To be able to launch Gephi and load a graph without it crashing
## Current Behavior
I am able to launch Gephi with my plugin, but when I load in the les miserables data, I get an error:

[INFO] SEVERE [global]
[INFO] Offending classloader: ModuleCL@4dc8e26a[imperial.node.weight]
[INFO] Offending classloader: ModuleCL@4dc8e26a[imperial.node.weight]
[INFO] Caused: java.util.MissingResourceException: No such bundle org.gephi.layout.plugin.NodeWeight.Bundle

## Possible Solution
I have a bundle file (I think) at NodeWeight/src/main/resources/org/gephi/plugins/layout/NodeWeight/Bundle.properties

## Your Environment

*Version used: Gephi 0.9.2
*Java version: 1.8.0_171
*Operating System: Mac OS 10.13.6

My Bundle.properties file (I have not filled in the description yet - let me know if this could be the source of the problem? ie the description not matching what I had written when generating plugin with maven:
`#OpenIDE-Module-Display-Category=Layout
#OpenIDE-Module-Long-Description=\
#    Example of Layout Plugins:\n<ul>\n<li><b>Grid Layout:</b> Place all nodes in a simple grid. \
#    Users can configure the size of the area and the speed.\
#    </li>\n<li><b>Sorted Grid Layout:</b> Same example as Grid Layout but users can sort nodes with an attribute column.\
#    </li>\n</ul>
#OpenIDE-Module-Name=NodeWeight
#OpenIDE-Module-Short-Description=add node weight to FA2 algorithm

NodeWeight.name=Node Weight
NodeWeight.description=Quality layout: a linear-attraction linear-repulsion model with few approximations (BarnesHut). Speed automatically computed.

`

Full error:

 `Annotation: Offending classloader: ModuleCL@2311cdb[imperial.node.weight]
Annotation: Offending classloader: ModuleCL@2311cdb[imperial.node.weight]
Annotation: Offending classloader: ModuleCL@2311cdb[imperial.node.weight]
Offending classloader: ModuleCL@2311cdb[imperial.node.weight]
Offending classloader: ModuleCL@2311cdb[imperial.node.weight]
Caused: java.util.MissingResourceException: No such bundle org.gephi.layout.plugin.NodeWeight.Bundle
	at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
	at org.openide.util.NbBundle.getBundle(NbBundle.java:399)
	at org.openide.util.NbBundle.getMessage(NbBundle.java:642)
	at org.gephi.layout.plugin.NodeWeight.ForceAtlas2Builder.getName(ForceAtlas2Builder.java:63)
	at org.gephi.desktop.layout.LayoutPanel$4.compare(LayoutPanel.java:232)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at org.gephi.desktop.layout.LayoutPanel.refreshChooser(LayoutPanel.java:229)
	at org.gephi.desktop.layout.LayoutPanel.refreshModel(LayoutPanel.java:202)
	at org.gephi.desktop.layout.LayoutPanel.refreshModel(LayoutPanel.java:189)
	at org.gephi.desktop.layout.LayoutTopComponent.refreshModel(LayoutTopComponent.java:122)
	at org.gephi.desktop.layout.LayoutTopComponent.access$100(LayoutTopComponent.java:68)
	at org.gephi.desktop.layout.LayoutTopComponent$1.select(LayoutTopComponent.java:93)
	at org.gephi.project.impl.ProjectControllerImpl.fireWorkspaceEvent(ProjectControllerImpl.java:330)
	at org.gephi.project.impl.ProjectControllerImpl.openWorkspace(ProjectControllerImpl.java:274)
	at org.gephi.project.impl.ProjectControllerImpl.openProject(ProjectControllerImpl.java:233)
	at org.gephi.project.impl.ProjectControllerImpl.newProject(ProjectControllerImpl.java:118)
	at org.gephi.desktop.project.ProjectControllerUIImpl.newProject(ProjectControllerUIImpl.java:494)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:585)
	at org.gephi.desktop.importer.DesktopImportControllerUI.finishImport(DesktopImportControllerUI.java:549)
	at org.gephi.desktop.importer.DesktopImportControllerUI.access$100(DesktopImportControllerUI.java:101)
	at org.gephi.desktop.importer.DesktopImportControllerUI$8.run(DesktopImportControllerUI.java:340)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.importer.DesktopImportControllerUI$8.run(DesktopImportControllerUI.java:343)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:275)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by eduramiba** [comment]
Hi, this usually means you changed the package of the classes but not the path to the bundle resources, they must coincide so `NBBundle.getMessage` can find the right `Bundle.properties` file for the requested class.

**Comment by juliannej** [comment]
Is this the block of code I would want to look at? From ForceAtlas2.java. I have modeled this off of the multi-gravity code, and I can see no differences between this and their version of this.

```java
    @Override
    public LayoutProperty[] getProperties() {
        List<LayoutProperty> properties = new ArrayList<LayoutProperty>();
        final String FORCEATLAS2_TUNING = NbBundle.getMessage(getClass(), "ForceAtlas2.tuning");
        final String FORCEATLAS2_BEHAVIOR = NbBundle.getMessage(getClass(), "ForceAtlas2.behavior");
        final String FORCEATLAS2_PERFORMANCE = NbBundle.getMessage(getClass(), "ForceAtlas2.performance");
        final String FORCEATLAS2_THREADS = NbBundle.getMessage(getClass(), "ForceAtlas2.threads");

        try {
            properties.add(LayoutProperty.createProperty(
                    this, Double.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.scalingRatio.name"),
                    FORCEATLAS2_TUNING,
                    "ForceAtlas2.scalingRatio.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.scalingRatio.desc"),
                    "getScalingRatio", "setScalingRatio"));

            properties.add(LayoutProperty.createProperty(
                    this, Boolean.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.strongGravityMode.name"),
                    FORCEATLAS2_TUNING,
                    "ForceAtlas2.strongGravityMode.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.strongGravityMode.desc"),
                    "isStrongGravityMode", "setStrongGravityMode"));

            properties.add(LayoutProperty.createProperty(
                    this, Double.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.gravity.name"),
                    FORCEATLAS2_TUNING,
                    "ForceAtlas2.gravity.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.gravity.desc"),
                    "getGravity", "setGravity"));

            properties.add(LayoutProperty.createProperty(
                    this, Boolean.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.distributedAttraction.name"),
                    FORCEATLAS2_BEHAVIOR,
                    "ForceAtlas2.distributedAttraction.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.distributedAttraction.desc"),
                    "isOutboundAttractionDistribution", "setOutboundAttractionDistribution"));

            properties.add(LayoutProperty.createProperty(
                    this, Boolean.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.linLogMode.name"),
                    FORCEATLAS2_BEHAVIOR,
                    "ForceAtlas2.linLogMode.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.linLogMode.desc"),
                    "isLinLogMode", "setLinLogMode"));

            properties.add(LayoutProperty.createProperty(
                    this, Boolean.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.adjustSizes.name"),
                    FORCEATLAS2_BEHAVIOR,
                    "ForceAtlas2.adjustSizes.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.adjustSizes.desc"),
                    "isAdjustSizes", "setAdjustSizes"));

            properties.add(LayoutProperty.createProperty(
                    this, Double.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.edgeWeightInfluence.name"),
                    FORCEATLAS2_BEHAVIOR,
                    "ForceAtlas2.edgeWeightInfluence.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.edgeWeightInfluence.desc"),
                    "getEdgeWeightInfluence", "setEdgeWeightInfluence"));

            properties.add(LayoutProperty.createProperty(
                    this, Double.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.jitterTolerance.name"),
                    FORCEATLAS2_PERFORMANCE,
                    "ForceAtlas2.jitterTolerance.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.jitterTolerance.desc"),
                    "getJitterTolerance", "setJitterTolerance"));

            properties.add(LayoutProperty.createProperty(
                    this, Boolean.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.barnesHutOptimization.name"),
                    FORCEATLAS2_PERFORMANCE,
                    "ForceAtlas2.barnesHutOptimization.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.barnesHutOptimization.desc"),
                    "isBarnesHutOptimize", "setBarnesHutOptimize"));

            properties.add(LayoutProperty.createProperty(
                    this, Double.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.barnesHutTheta.name"),
                    FORCEATLAS2_PERFORMANCE,
                    "ForceAtlas2.barnesHutTheta.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.barnesHutTheta.desc"),
                    "getBarnesHutTheta", "setBarnesHutTheta"));

            properties.add(LayoutProperty.createProperty(
                    this, Integer.class,
                    NbBundle.getMessage(getClass(), "ForceAtlas2.threads.name"),
                    FORCEATLAS2_THREADS,
                    "ForceAtlas2.threads.name",
                    NbBundle.getMessage(getClass(), "ForceAtlas2.threads.desc"),
                    "getThreadsCount", "setThreadsCount"));

        } catch (Exception e) {
            Exceptions.printStackTrace(e);
        }

        return properties.toArray(new LayoutProperty[0]);
    }
```

**Comment by juliannej** [comment]
Turns out my file hierarchy didn't match the package I was naming at the top of all my files. Thank you for your help!

**Comment by eduramiba** [comment]
The thing is that getClass() is dependent on your package. I would need to see your whole code. But it's very probable that your package of bundles and classes is not the same.

**Comment by eduramiba** [comment]
Haha right, that's it!
