### ISSUE TITLE
Gephi doesn't show labels

### ISSUE THREAD

**Issue by butterstulle93** [gephi/gephi#2016]
Hey,

i imported in Gephi a node and a edge excel file but in Gephi it is not possible to see the labels of the nodes.

I attached the excel sheets, so maybe you can tell me where is my fault. 

Thank you very much :)

[Edge.xlsx](https://github.com/gephi/gephi/files/2306343/Edge.xlsx)
[Node.xlsx](https://github.com/gephi/gephi/files/2306344/Node.xlsx)

**Comment by eduramiba** [comment]
Hi,
Works fine for me in Gephi 0.9.2 Did you enable labels in overview/preview? They are not visible by default.

**Comment by wetneb** [comment]
Closing this as not reproducible then.
