### ISSUE TITLE
copy to new workspace produce a "The configurations don't match" error

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#2020]
java.lang.RuntimeException: The configurations don't match
	at org.gephi.graph.impl.GraphBridgeImpl.verifyCompatibility(GraphBridgeImpl.java:239)
	at org.gephi.graph.impl.GraphBridgeImpl.copyNodes(GraphBridgeImpl.java:58)
	at org.gephi.filters.FilterControllerImpl$2.run(FilterControllerImpl.java:369)
[catch] at java.lang.Thread.run(Unknown Source)

## Possible Solution

scandinvian letters perhaps in twitter data?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Thanks for the report!

**Comment by MiguelGomezC** [comment]
What about the solution?? hehehhehehehehheheh XDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by mbastian** [comment]
Thanks for the report. This fix will be included in the upcoming 0.9.6 update.
