### ISSUE TITLE
Import issue from Excel

### ISSUE THREAD

**Issue by vikidachs** [gephi/gephi#2026]
I am using gephi 9.2 and use excel (2016) to create the necessary matrix and export it to a .csv I have previously been using a British version of excel, in which the command for multiply matrix is =mmult, and haven't experienced any problems: the import works. 
However, using a Danish version of excel, which is all I have available currently, in which the multiple matrix command is mprodukt, Gephi is unable to import it. For an earlier version (8.2), Gephi would report a runtime error and in 9.2 it creates a netwoks consisting of some but not all of the nodes and connect them in a peculiar way.
Any suggestions to what I can do differently? How can I fix this?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
We use [Apache POI](https://poi.apache.org) for importing excel files, and its compatibility with excel is good but not perfect.

If you are finding problems importing some files, the best option is to export them into a CSV file from excel itself and import that CSV into gephi.
