### ISSUE TITLE
Can I only use Intel(R) HD Graphics now?

### ISSUE THREAD

**Issue by ooof** [gephi/gephi#2027]
![2018-09-12 18-39-40](https://user-images.githubusercontent.com/392785/45420907-02187980-b6be-11e8-8ce4-f847b4057d10.png)
I installed gephi 0.9.2 on Ubuntu 16.04. I would like to ask: Is it possible to use Intel HD instead of NVIDIA discrete graphics?

-------------------

Sorry, can I ignore the format below.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
You can, but that depends on your own linux configuration and what graphics cards its using when you have two.

It's actually tricky to configure and sometimes won't work... You can try with https://bumblebee-project.org or similar. In windows it will work easily, just run Gephi with nvidia card.

**Comment by ooof** [comment]
Is the new version of Gephi easy to use?

**Comment by eduramiba** [comment]
Sure, very similar to 0.9.0 and 0.9.1 but with some usability and bug fixes.

**Comment by ooof** [comment]
thank .
