### ISSUE TITLE
Ignoring GraphML desc standard tags

### ISSUE THREAD

**Issue by sebkajeka** [gephi/gephi#2030]
## Expected Behavior

Load a GraphML desc element as a name

## Current Behavior

Ignoring the desc tags within a GraphML document. A Desc tag should map to a name. Currently a "label" attribute is needed in order to assign to name, which does not conform to GraphML standard and breaks compatibility between different Graph software (Cytoscape requires a "name" attribute, again non-standard).

Note the desc tag in the following schema:

http://graphml.graphdrawing.org/specification/schema_element.xsd.htm

## Possible Solution

Use desc tags as labels.

## Steps to Reproduce

```

<graphml>
    <graph edgedefault="directed">
        <key id="x" attr.name="x" attr.type="float" for="node"/>
        <key id="y" attr.name="y" attr.type="float" for="node"/>
        <key id="z" attr.name="z" attr.type="float" for="node"/>
        <node id="n0">
            <desc>Node Name One</desc>
            <data key="x">-19.0759</data>
            <data key="y">-27.3243</data>
            <data key="z">38.8582</data>
        </node>
        <node id="n1">
            <desc>Node Name Two</desc>
            <data key="x">-6.64716</data>
            <data key="y">-38.1986</data>
            <data key="z">33.7861</data>
        </node>
        <edge id="e0" source="n0" target="n1">
        </edge>
    </graph>
</graphml>
```

1. Open the provided GraphML file
2. Notice that labels do not match the desc tag but use ID instead

## Context

GraphML compatiblity between graphing software is broken due to the de-facto introduction of a "name" attribute with various possible identifiers. This has fragmented the standard when desc is clearly specified as the correct solution.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 10
* Operating System: W10

**Comment by mbastian** [comment]
Makes sense, thanks for reporting! This is now added and will be included in the 0.9.3 release.

Interoperability is definitely important so feel free to suggest additional improvements in this direction.
