### ISSUE TITLE
Manual range setting in node coloring using Ranking

### ISSUE THREAD

**Issue by lihaone2** [gephi/gephi#2031]
I'm trying to color the nodes based on one numeric node attribute using "Ranking" (range: -0.5~1), gephi automatically use the maximum and minimum values of this attribute as the range in coloring. Is there a way to manually set the range to, for example -1, 0, 1, regardless of the values in the attribute? 

In other words, I would like to color the nodes with attribute =1 as green, nodes with attribute=0 as white, nodes with attribute=-0.5 as light red.

Also, is it possible for gephi to export the color code for this? Thanks! 

![image](https://user-images.githubusercontent.com/40858304/45819561-eaa44680-bce4-11e8-8ae4-e726fe20ce36.png)

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 8 update 171
* Operating System: Mac High Sierra 10.13.5

**Comment by eduramiba** [comment]
Hi,
Maybe you can use partition mode instead, ranking is continuous, partition is discrete and you can give each different value a color.

It's not possible to export these colors at the moment.

**Comment by lihaone2** [comment]
Thanks eduramiba for the quick reply. 
I have 400 unique values, so giving each value a color would be difficult...

**Comment by eduramiba** [comment]
Oh then your scale is continuous. Well, then you should limit your column range the the min and max you need (-1, 1)... Or maybe it works if you apply an attribute filter to the graph for the wanted range and then apply the appearance on the filtered graph. That would leave nodes with values out of the range uncolored.

**Comment by eduramiba** [comment]
But your whole graph data goes to -0.5 only, why would you need -1 there?

**Comment by lihaone2** [comment]
I would like to color nodes with attribute=0 as white, and separate the positive and negatives.

**Comment by eduramiba** [comment]
Maybe you can apply coloring and then filter by attribute=0 and apply a different coloring, not sure if that's possible though. Another way if you don't need proportional color would be having an extra attribute that has only 3 values: negative, zero, positive and use partition.

**Comment by lihaone2** [comment]
Thanks eduramiba for the suggestions, I will try this out.
