### ISSUE TITLE
arrange z-index of nodes based on node attribute

### ISSUE THREAD

**Issue by lihaone2** [gephi/gephi#2032]
Is it possible to set the z-index/z position of nodes based on one continuous node attribute? I'm using fruchterman reingold layout algorithm, so there is no place to change the z-index as in other layout algorithms, like Geo layout. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Java 8 update 171
* Operating System: Mac High Sierra 10.13.5

**Comment by eduramiba** [comment]
Hi,
The drawing order of nodes cannot be configured, and you can change the z position of the node but I think they are drawn in 2d only.

**Comment by lihaone2** [comment]
Am I correct that the "layers" of the nodes are fixed in gephi, and I cannot move one node over another?

**Comment by eduramiba** [comment]
Right, they are just drawn in the order they were added to the graph. Maybe the future visualization engine will allow using z coordinate of the node as a 2d z-index.

**Comment by lihaone2** [comment]
I see. Would it work if I export the network to gexf and load into R to redraw the network? I know some R packages can handle the drawing order of nodes.

**Comment by eduramiba** [comment]
Yeah I guess it's possible in R
