### ISSUE TITLE
Black screen in overview - Cannot visualize my graphs

### ISSUE THREAD

**Issue by yacbouj** [gephi/gephi#2035]
Hi, 
I just reinstalled Gephi on a new computer after not using it for over a year.
Every thing goes fine except that I cannot visualize any of my graphs in the overview tab. It only shows a black screen with barely visible white edges and nodes

I updated my graphic card's drivers, not sure what else I could try.
Preview seems to work sometimes (depending on the graph)

screenshot :  https://imgur.com/tEvCjsL

* Version used: Gephi 0.9.2
* Java version: 1.8 
* Operating System: Windows 10 - 64bits

Hope someone can help!
Many thanks

**Comment by yacbouj** [comment]
Bump!

**Comment by eduramiba** [comment]
This is usually caused bad/outdated graphics card drivers.

**Comment by kuriimutaiyaki** [comment]
Hello, 

I have the same issue. Gephi and Java version, and OS are the same as OP. Graphics Driver is up to date (last update 6/12/19).  

Is there a way to fix this problem?

Thank you 

![image](https://user-images.githubusercontent.com/51934580/59644387-8d2d1100-9121-11e9-8464-0e9adc9b156a.png)

**Comment by ITAYC0HEN** [comment]
Same here after updating Windows 10 to Insiders build.

**Comment by ITAYC0HEN** [comment]
Solved by updating the Graphic drivers as recommended by @eduramiba

**Comment by racingkoala** [comment]
I had to restore back to an older display driver to fix the problem. Windows 10, Intel 630 adapter.

**Comment by g3rfx** [comment]
What driver version did work for you? @ITAYC0HEN @ramadap

**Comment by ITAYC0HEN** [comment]
Simply updated my current one using the default interface of devmgmt.msc

**Comment by m4chi** [comment]
I have a whitescreen in the overview/graph window after performing a filter for an ego-network. Restarting the system and gephi do not help, all other workspaces in the project display normally. Something is broken but I have no idea what. Does anybody have a fix?
gephi 0.9.2, ubuntu 18.4...

**Comment by EfthymiaKostaki** [comment]
I have the same issue as well on MacOS only a black screen is displayed.

**Comment by cvanelteren** [comment]
I have a similar issue where I boots up as a blank screen
![20210430_11h37m03s_grim](https://user-images.githubusercontent.com/19485143/116677572-a69f7500-a9a8-11eb-93b2-e5f3d5e14f6a.png)

**Comment by mbastian** [comment]
Closing as related to OpenGL drivers, which are required for Gephi to work.

Regarding the filter issue reported by @m4chi, I made a separate issue here: https://github.com/gephi/gephi/issues/2534
