### ISSUE TITLE
`.gexf` export locations contain ceiling/floor effects.

### ISSUE THREAD

**Issue by IanMcDowell** [gephi/gephi#2037]
## Expected Behavior

`.gexf` export should contain true location without ceiling/floor effects.

## Current Behavior

After running ForceAtlas2 on a large network with ~13500 nodes and ~300K edges, I exported the graph by clicking through `File | Export | Graph file | GEXF |  Full (The complete graph is exported)`.

The resultant file contains positions with all unique x coordinates and unique y coordinates except for the max and the min which are repeated between 75 and 150 times. Subtracting the two yields 50,000, suggesting that this is the limit of the unidimensional span of mappable space in Gephi.

## Possible Solution

Extend the limit to an arbitrarily high number. Presumably, Gephi's engine doesn't require this, afterall, the Graph view didn't show me any strange border effects.

## Steps to Reproduce

1. Download [STRING](https://stringdb-static.org/download/protein.links.v10.5/9606.protein.links.v10.5.txt.gz) and import as network
2. Run ForceAtlas2 at Scaling >50 and Gravity <20 until convergence.
3. Export as gexf

## Your Environment

* Version used: Gephi 0.9.2
* Operating System: OSX

**Comment by eduramiba** [comment]
Hi,
This is a known problem and will be fixed in the future: #1518
