### ISSUE TITLE
Exception when changing renderer configuration

### ISSUE THREAD

**Issue by thomai-d** [gephi/gephi#2045]
## Expected Behavior
No exception :)

## Current Behavior
```
SEVERE [global]
java.lang.NullPointerException
	at org.gephi.preview.plugin.renderers.EdgeLabelRenderer.preProcess(EdgeLabelRenderer.java:122)
	at org.gephi.preview.PreviewControllerImpl.refreshPreview(PreviewControllerImpl.java:185)
	at org.gephi.preview.PreviewControllerImpl.refreshPreview(PreviewControllerImpl.java:117)
	at org.gephi.desktop.preview.PreviewUIControllerImpl$2.run(PreviewUIControllerImpl.java:196)
[catch] at java.lang.Thread.run(Thread.java:748)
```

Preview is "Refreshing" infinitely.

## Steps to Reproduce

1. Open any graph
2. Go to preview
3. Enable "Show labels" in "Edge labels" group
4. Go to "Manage Renderers"
5. Move "Default edge labels to the bottom"

Result:
![grafik](https://user-images.githubusercontent.com/24974298/47615116-174d3a00-daab-11e8-83ce-0a3a8bb33725.png)

## Context

Actually I was trying to show edge labels (value of weight) in the PNG export.
Labels are never shown. No matter which setting I change.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_172; Java HotSpot(TM) 64-Bit Server VM 25.172-b11; Oracle Corporation
* Operating System: Windows 10 Pro

**Comment by MadcowD** [comment]
Same error on linux same gephi version.

**Comment by mbastian** [comment]
Fixed this issue. Now one can show the edge labels without the edges and/or have the edge label renderer ahead of the edge renderer in the stack.
