### ISSUE TITLE
After upgrade data laboratory shows nothing in my workplace.

### ISSUE THREAD

**Issue by Rafanand** [gephi/gephi#2048]
## Expected Behavior
Show the Edges and Nodes tabs

## Current Behavior
The window below the "workplace1" tab shows nothing

## Possible Solution
how about the old ui? :)

## Steps to Reproduce

1. this morning I was asked to upgrade the plugins
2. upgrade
3. open old workplace
4. note that the Overview shows the node and edges as before
5. click on "Data Laboratory"
6. notthing to see here, move along

## Context

modify my data

## Your Environment

* Version used: Gephi 0.9.2
Java: 1.8.0_172; Java HotSpot(TM) 64-Bit Server VM 25.172-b11
Runtime: Java(TM) SE Runtime Environment 1.8.0_172-b11
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (gephi)

-------------------------------------------------------------------------------
>Log Session: Monday, October 29, 2018 12:13:58 PM PDT
>System Info: 
  Product Version         = Gephi 0.9.2 201709241107
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 1.8.0_172; Java HotSpot(TM) 64-Bit Server VM 25.172-b11; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_172-b11
  Java Home               = C:\Program Files\Java\jdk1.8.0_172\jre
  System Locale; Encoding = en_US (gephi); Cp1252
  Home Directory          = C:\Users\arafanel
  Current Directory       = C:\Program Files\Gephi-0.9.2
  User Directory          = C:\Users\arafanel\AppData\Roaming\.gephi\0.9.2\dev
  Cache Directory         = C:\Users\arafanel\AppData\Roaming\.gephi\0.9.2\dev\var\cache
  Installation            = C:\Program Files\Gephi-0.9.2\platform
                            C:\Program Files\Gephi-0.9.2\gephi
                            C:\Program Files\Gephi-0.9.2\platform
  Boot & Ext. Classpath   = C:\Program Files\Java\jdk1.8.0_172\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_172\jre\classes;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_172\jre\lib\ext\zipfs.jar
  Application Classpath   = C:\Program Files\Gephi-0.9.2\platform\lib\boot.jar;C:\Program Files\Gephi-0.9.2\platform\lib\org-openide-modules.jar;C:\Program Files\Gephi-0.9.2\platform\lib\org-openide-util-lookup.jar;C:\Program Files\Gephi-0.9.2\platform\lib\org-openide-util-ui.jar;C:\Program Files\Gephi-0.9.2\platform\lib\org-openide-util.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ar_SA.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_bg.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ca.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_cs.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_de.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_es.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_fr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_it.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ja.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ko.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_pl.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_pt_PT.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ro.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_ru.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_si.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_sq.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_sv.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_tr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\boot_zh_TW.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ar_SA.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_bg.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ca.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_cs.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_de.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_es.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_fr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_it.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ja.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ko.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_pl.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_pt_PT.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ro.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_ru.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_si.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_sq.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_sv.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_tr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-modules_zh_TW.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_bg.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_ca.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_cs.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_de.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_es.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_fr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_it.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_ja.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_ko.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_pl.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_ro.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_ru.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_si.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_sv.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_tr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-ui_ja.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-ui_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-ui_ru.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util-ui_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ar_SA.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_bg.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ca.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_cs.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_de.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_es.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_fr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_it.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ja.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ko.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_pl.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_pt_PT.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ro.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_ru.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_si.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_sq.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_sv.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_tr.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\lib\locale\org-openide-util_zh_TW.jar;C:\Program Files\Java\jdk1.8.0_172\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_172\lib\tools.jar
  Startup Classpath       = C:\Program Files\Gephi-0.9.2\platform\core\asm-all-5.0.1.jar;C:\Program Files\Gephi-0.9.2\platform\core\core-base.jar;C:\Program Files\Gephi-0.9.2\platform\core\core.jar;C:\Program Files\Gephi-0.9.2\platform\core\org-netbeans-libs-asm.jar;C:\Program Files\Gephi-0.9.2\platform\core\org-openide-filesystems-compat8.jar;C:\Program Files\Gephi-0.9.2\platform\core\org-openide-filesystems.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core-base_ja.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core-base_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core-base_ru.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core-base_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ar_SA.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_bg.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ca.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_cs.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_de.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_es.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_fr.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_it.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ja.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ko.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_pl.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_pt_PT.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ro.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_ru.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_si.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_sq.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_sv.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_tr.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\core_zh_TW.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-netbeans-libs-asm_ja.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-netbeans-libs-asm_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-netbeans-libs-asm_ru.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-netbeans-libs-asm_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems-compat8_ja.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems-compat8_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems-compat8_ru.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems-compat8_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ar_SA.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_bg.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ca.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_cs.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_de.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_es.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_fr.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_gl_ES.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_in_ID.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_it.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ja.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ko.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_nl_NL.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_pl.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_pt_BR.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_pt_PT.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ro.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_ru.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_si.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_sq.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_sv.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_tr.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_zh_CN.jar;C:\Program Files\Gephi-0.9.2\platform\core\locale\org-openide-filesystems_zh_TW.jar;C:\Program Files\Gephi-0.9.2\gephi\core\locale\core_gephi.jar
-------------------------------------------------------------------------------
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.33.1 201609300101]
	org.openide.util [9.7.1 201609300101]
	org.openide.util.ui [9.6.1 201609300101]
	org.openide.modules [7.48.1 201609300101]
	org.netbeans.api.annotations.common/1 [1.27.1 201609300101]
	org.openide.filesystems [9.10.1 201609300101]
	org.openide.awt [7.67.1 201609300101]
	org.netbeans.api.progress/1 [1.47.1 201609300101]
	org.netbeans.api.progress.nb [1.47.1 201609300101]
	org.openide.dialogs [7.42.1 201609300101]
	org.openide.nodes [7.45.1 201609300101]
	org.openide.windows [6.75.1 201609300101]
	org.netbeans.modules.editor.mimelookup/1 [1.40.1 201609300101]
	org.openide.text [6.67.1 201609300101]
	org.netbeans.swing.tabcontrol [1.56.1 201609300101]
	org.netbeans.swing.outline [1.34.1 201609300101]
	org.openide.explorer [6.62.1 201609300101]
	org.openide.actions [6.39.1 201609300101]
	org.netbeans.modules.queries/1 [1.43.1 201609300101]
	org.netbeans.api.templates [1.7.1 201609300101]
	org.openide.filesystems.nb [9.9.1 201609300101]
	org.openide.loaders [7.66.1 201609300101]
	org.netbeans.api.intent [1.2.1 201609300101]
	org.netbeans.api.io [1.3.1 201609300101]
	org.openide.io [1.49.1 201609300101]
	org.openide.filesystems.compat8 [9.9.1 201609300101]
	org.netbeans.swing.plaf [1.41.1 201609300101]
	org.netbeans.spi.quicksearch [1.27.1 201609300101]
	org.netbeans.modules.templates/1 [1.7.1 201609300101]
	org.netbeans.libs.asm [5.3.1 201609300101]
	org.netbeans.bootstrap/1 [2.76.1 201609300101]
	org.netbeans.core.startup.base [1.62.1.1 1 201609300101]
	org.netbeans.core.startup/1 [1.62.1.1 201609300101]
	org.netbeans.modules.settings/1 [1.49.1 201609300101]
	org.netbeans.modules.sendopts/2 [2.35.1 201609300101]
	org.netbeans.modules.sampler [1.14.1 201609300101]
	org.netbeans.modules.progress.ui [1.33.1 201609300101]
	org.netbeans.modules.keyring [1.24.1 201609300101]
	org.netbeans.core/2 [3.51.1 201609300101]
	org.netbeans.modules.options.api/1 [1.45.1 201609300101]
	org.netbeans.modules.options.keymap [1.37.1 201609300101]
	org.netbeans.libs.jna/1 [1.44.1 201609300101]
	org.netbeans.modules.masterfs/2 [2.55.1.2 2 201609300101]
	org.netbeans.modules.masterfs.windows [1.16.1 201609300101]
	org.netbeans.modules.masterfs.ui [2.3.1.2 201609300101]
	org.netbeans.modules.masterfs.nio2 [1.15.1 201609300101]
	org.netbeans.modules.keyring.fallback [1.8.1 201609300101]
	org.netbeans.modules.keyring.impl [1.24.1 201609300101]
	org.netbeans.modules.autoupdate.services [1.52.1 201609300101]
	org.netbeans.modules.autoupdate.ui [1.45.1 201609300101]
	org.netbeans.modules.autoupdate.cli [1.13.1 201609300101]
	org.netbeans.libs.jna.platform/1 [1.14.1 201609300101]
	org.netbeans.core.windows/2 [2.81.1 201609300101]
	org.netbeans.core.ui/1 [1.45.1 201609300101]
	org.netbeans.core.output2/1 [1.41.1 201609300101]
	org.netbeans.core.network [1.10.1 201609300101]
	org.netbeans.core.nativeaccess/1 [1.31.1 201609300101]
	org.netbeans.core.multitabs/1 [1.12.1.1 1 201609300101]
	org.netbeans.core.io.ui/1 [1.30.1 201609300101]
	org.gephi.core.library.wrapper [0.9.2 0.9.2 201709241108]
	org.gephi.utils.longtask [0.9.2 0.9.2 201709241107]
	org.gephi.project.api [0.9.2.1 0.9.2 201711180139]
	org.gephi.graph.api [0.9.2 0.9.2 201709241107]
	org.gephi.utils [0.9.2 0.9.2 201709241108]
	org.gephi.ui.library.wrapper [0.9.2 0.9.2 201709241109]
	org.gephi.lib.validation [0.9.2 0.9.2 201709241109]
	org.gephi.ui.utils [0.9.2 0.9.2 201709241110]
	org.gephi.ui.components [0.9.2 0.9.2 201709241111]
	org.gephi.db.drivers [0.9.2 0.9.2 201709241110]
	org.gephi.io.importer.api [0.9.2.2 0.9.2 201711180141]
	org.gephi.mostrecentfiles.api [0.9.2 0.9.2 201709241113]
	org.gephi.desktop.project [0.9.2 0.9.2 201709241113]
	org.gephi.welcome.screen [0.9.2 0.9.2 201709241114]
	org.gephi.datalab.api [0.9.2 0.9.2 201709241109]
	org.gephi.visualization.api [0.9.2 0.9.2 201709241109]
	org.gephi.tools.api [0.9.2 0.9.2 201709241112]
	org.gephi.gleem [0.9.2 0.9.2 201709241113]
	org.gephi.visualization [0.9.2 0.9.2 201709241113]
	org.gephi.ui.propertyeditor [0.9.2 0.9.2 201709241116]
	org.gephi.algorithms.plugin [0.9.2 0.9.2 201709241113]
	org.gephi.tools.plugin [0.9.2 0.9.2 201709241114]
	org.gephi.statistics.api [0.9.2 0.9.2 201709241111]
	org.gephi.statistics.plugin [0.9.2 0.9.2 201709241111]
	org.gephi.filters.api [0.9.2 0.9.2 201709241112]
	org.gephi.appearance.api [0.9.2 0.9.2 201709241112]
	org.gephi.filters.plugin [0.9.2.1 0.9.2 201711180143]
	org.gephi.timeline.api [0.9.2 0.9.2 201709241112]
	org.gephi.statistics.plugin.ui [0.9.2 0.9.2 201709241111]
	org.gephi.settings.upgrader [0.9.2 0.9.2 201709241111]
	org.gephi.project.ui [0.9.2 0.9.2 201709241110]
	org.gephi.io.processor.plugin [0.9.2.2 0.9.2 201711180141]
	org.gephi.processor.plugin.ui [0.9.2 0.9.2 201709241110]
	org.gephi.batik.wrapper [0.9.2 0.9.2 201709241108]
	org.gephi.preview.api [0.9.2 0.9.2 201709241108]
	org.gephi.preview.plugin [0.9.2 0.9.2 201709241109]
	org.gephi.io.exporter.api [0.9.2 0.9.2 201709241108]
	org.gephi.io.exporter.preview [0.9.2 0.9.2 201709241108]
	org.gephi.preview.export.ui [0.9.2 0.9.2 201709241109]
	org.gephi.perspective.api [0.9.2 0.9.2 201709241118]
	org.gephi.layout.api [0.9.2 0.9.2 201709241115]
	org.gephi.layout.plugin [0.9.2 0.9.2 201709241116]
	org.gephi.io.importer.plugin [0.9.2.2 0.9.2 201711180146]
	org.gephi.io.generator.api [0.9.2 0.9.2 201709241115]
	org.gephi.io.generator.plugin [0.9.2 0.9.2 201709241115]
	org.gephi.io.exporter.plugin [0.9.2.1 0.9.2 201711180145]
	org.gephi.import.plugin.ui [0.9.2.1 0.9.2 201711180147]
	org.gephi.gephi.branding [0.9.2 0.9.2 201709241107]
	org.gephi.generator.plugin.ui [0.9.2 0.9.2 201709241115]
	org.gephi.desktop.banner [0.9.2 0.9.2 201709241119]
	org.gephi.filters.plugin.ui [0.9.2 0.9.2 201709241119]
	org.gephi.filters.impl [0.9.2.1 0.9.2 201711180147]
	org.gephi.export.plugin.ui [0.9.2 0.9.2 201709241118]
	org.gephi.directory.chooser [0.9.2 0.9.2 201709241121]
	org.gephi.desktop.tools [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.timeline [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.statistics [0.9.2 0.9.2 201709241115]
	org.gephi.desktop.recent.files [0.9.2 0.9.2 201709241118]
	org.gephi.desktop.progress [0.9.2 0.9.2 201709241114]
	org.gephi.desktop.io.export [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.preview [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.layout [0.9.2 0.9.2 201709241119]
	org.gephi.desktop.import [0.9.2 0.9.2 201709241120]
	org.gephi.desktop.generate [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.filters [0.9.2 0.9.2 201709241122]
	org.gephi.desktop.datalab [0.9.2 0.9.2 201709241116]
	org.gephi.desktop.context [0.9.2 0.9.2 201709241114]
	org.gephi.desktop.branding [0.9.2 0.9.2 201709241114]
	org.gephi.appearance.plugin [0.9.2 0.9.2 201709241116]
	org.gephi.appearance.plugin.ui [0.9.2 0.9.2 201709241117]
	org.gephi.desktop.appearance [0.9.2 0.9.2 201709241117]
	org.gephi.datalab.plugin [0.9.2 0.9.2 201709241119]
	nl.cloudfarming.client.lib.platform.l10n [1.1 1.1-NB80 201411231331]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.windows.WindowsNetworkProxy]: Windows system proxy resolver: auto detect
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.gephi.ui.upgrader.Upgrader.getCurrentVersion(Upgrader.java:123)
INFO: Current Version is 092
Diagnostic information
Input arguments:
	-Xms64m
	-Xmx512m
	-Xverify:none
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-XX:MaxPermSize=384m
	-Dnetbeans.user.dir=C:\Program Files\Gephi-0.9.2\bin
	-Djdk.home=C:\Program Files\Java\jdk1.8.0_172
	-splash:C:\Users\arafanel\AppData\Roaming\.gephi\0.9.2\dev\var\cache\splash.png
	-Djdk.launcher.addexports.0=java.desktop/sun.awt=ALL-UNNAMED
	-Djdk.launcher.addexports.1=java.base/jdk.internal.jrtfs=ALL-UNNAMED
	-Djdk.launcher.addexports.2=java.desktop/java.awt.peer=ALL-UNNAMED
	-Djdk.launcher.addexports.3=java.desktop/com.sun.beans.editors=ALL-UNNAMED
	-Djdk.launcher.addexports.3=java.desktop/sun.awt.im=ALL-UNNAMED
	-Djdk.launcher.addexports.4=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
	-Djdk.launcher.addexports.5=java.management/sun.management=ALL-UNNAMED
	-Dnetbeans.home=C:\Program Files\Gephi-0.9.2\platform
	-Dnetbeans.user=C:\Users\arafanel\AppData\Roaming\.gephi\0.9.2\dev
	-Dnetbeans.default_userdir_root=
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=C:\Users\arafanel\AppData\Roaming\.gephi\0.9.2\dev\var\log\heapdump.hprof
	-Dsun.awt.keepWorkingSetOnMinimize=true
	-Dnetbeans.dirs=C:\Program Files\Gephi-0.9.2\platform;C:\Program Files\Gephi-0.9.2\gephi
	exit
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 64.0MB maximum 455.5MB
Non heap memory usage: initial 2.4MB maximum -1b
Garbage collector: PS Scavenge (Collections=8 Total time spent=0s)
Garbage collector: PS MarkSweep (Collections=2 Total time spent=0s)
Classes: loaded=5533 total loaded=5533 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 8,468,852,736
INFO [null]: Total physical memory 8,468,852,736
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance], but some are: [ToggleFullScreenAction.shadow]
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
WARNING [java.util.prefs]: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO: GL_VENDOR: Intel
INFO: GL_RENDERER: Intel(R) HD Graphics 620
INFO: GL_VERSION: 4.5.0 - Build 23.20.16.4973
INFO: GL_SURFACE_SCALE: 1
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled

**Comment by Rafanand** [comment]
yes, the window was closed.  But why?  

I was open automatically when I tried "file -> generate -> [pick one]"

**Comment by eduramiba** [comment]
Not sure why it was closed, it sometimes happens to users but is easily solved.
Looks like a bug in Netbeans RCP.
