### ISSUE TITLE
Graph never shows up

### ISSUE THREAD

**Issue by ilknur-tr** [gephi/gephi#2054]
## Current Behavior

Open any other graph file
![edges table](https://user-images.githubusercontent.com/45282583/48932750-897c3780-ef0e-11e8-9c4c-8b6401c61077.png)
![nodes table](https://user-images.githubusercontent.com/45282583/48932752-8a14ce00-ef0e-11e8-8d6e-3e147babfcd6.png)
![graph](https://user-images.githubusercontent.com/45282583/48932778-a57fd900-ef0e-11e8-9661-66e21e1eb75f.png)

The Graph window will be showing "Initializing..". But nothing happens. Graph never shows up.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: Version 8 update 181 (build 1.8.0_181-b13)
* Operating System: Windows10 pro , version 1709

**Comment by eduramiba** [comment]
Hi,
Try to update your graphics card drivers.

**Comment by ilknur-tr** [comment]
> Hi,
> Try to update your graphics card drivers.

Thank you.
