### ISSUE TITLE
Backgroung freezing

### ISSUE THREAD

**Issue by Dylanleg** [gephi/gephi#2058]
## Current Behavior

![graph](https://user-images.githubusercontent.com/43991981/49366979-05cf0180-f6eb-11e8-8300-44548cbb6cfe.PNG)

The graph works but my background is crashing when I launch a project. I reinstalled Gephi 0.9.2 but the problem is still here.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: Windows 10

**Comment by eduramiba** [comment]
This should work fine in the next visualization engine, with better compatibility checks (still far from release) but for the moment try to update your graphics card drivers and make sure you are using the best card with Gephi in case you have 2 cards in your computer.

**Comment by eduramiba** [comment]
Great :)
