### ISSUE TITLE
Graph on Gephi not showing up on Mac 

### ISSUE THREAD

**Issue by Alhujaylan** [gephi/gephi#2059]
## Expected Behavior
Graph working
## Current Behavior
Graph not working 
## Steps to Reproduce

1.
2.
3.
4.

## Context

I have received  this message 

A java.lang.NullPointerException exception has occurred.

	Click Show Details or see the messages.log file located in your /Users/mac/Library/Application Support/gephi/0.9.2/dev/var/log folder.
## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
* Operating System: 
x os el capitan 10.11.6

**Comment by daviddias** [comment]
I see the same happening with Mojave https://github.com/gephi/gephi/issues/2075

**Comment by franzesilva** [comment]
Same happening with Mojave. 10.14.5 (18F132)

**Comment by wetneb** [comment]
Thank you for this report!
Unfortunately, without more details about the issue, it is unlikely we can reproduce it. it would be very helpful to have a sample graph file to reproduce the bug. I am closing this for now, but can reopen the ticket if you can provide such a sample file. Thanks!
