### ISSUE TITLE
liststring in filters/queries values just listed as array.tostring

### ISSUE THREAD

**Issue by kyleboyle** [gephi/gephi#2061]
## Expected Behavior

I expected to be able to work with the list items as a set (eg does it contain a specific value or not)

## Steps to Reproduce
![screen shot 2018-12-10 at 11 05 20 am](https://user-images.githubusercontent.com/6877108/49740885-9cf80400-fc6b-11e8-8686-d19f30b73a71.png)
```
<attribute id="2" title="suppressedTypes" type="liststring"/>
```
## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: macos

**Comment by mbastian** [comment]
There is indeed some gaps in filtering array columns. There isn't any filters that work with the elements IN the list.

### Definition of done
- Add a new 'Contains' category under 'Attributes' designed to only work with list columns. Only nodes/edges with the provided string as one of the element in the list would be returned. The UI could be either the same as 'Equal'.
- Add a new 'Partition for lists' category under Attributes designed to work like a partition filter but with the elements in the list flattened. So for instance if a graph has 2 nodes with a list column with [a,b] and [a,b,c] the partition chooser would have 3 items a, b and c. Having percentages would be nice to have.

**Comment by mbastian** [comment]
I completed the work:
- New "List Contains" filter under Attributes. Exact match on the list element, based on the user input. Only one element can be matched.
- New option on the existing "Partition" filter. When the attribute is a list, one can right click and select the "Flatten list" option, which will allow the selection of elements in the list.

<img width="300" alt="Screenshot 2022-11-25 at 20 02 22" src="https://user-images.githubusercontent.com/234813/204042972-b8a7276a-9232-49b9-9c41-d8f4f706ff17.png">

One can use this example GEXF with a list attribute for testing
[test.gexf.zip](https://github.com/gephi/gephi/files/10094756/test.gexf.zip)
