### ISSUE TITLE
Bug with GEPHI 0.9.2 on Windows 10 Enterprise 

### ISSUE THREAD

**Issue by BaptisteHamburg** [gephi/gephi#2074]
## Expected Behavior

I would like to start GEPHI version 0.9.2 but it does not work. When I launch the program, the starting windows open and GEPHI is opening the different modules but the program doesn't start. 

## Current Behavior

I have tried to change the Startup Settings for GEPHI 0.9.2, which are:

(#) ${HOME} will be replaced by user home directory according to platform
default_userdir="${HOME}/.${APPNAME}/0.9.2/dev"
default_mac_userdir="${HOME}/Library/Application Support/${APPNAME}/0.9.2/dev"

(#) options used by the launcher by default, can be overridden by explicit
(#) command line switches
default_options="--branding gephi -J-Xms64m -J-Xmx512m -J-Xverify:none -J-Dsun.java2d.noddraw=true -J-Dsun.awt.noerasebackground=true -J-Dnetbeans.indexing.noFileRefresh=true -J-Dplugin.manager.check.interval=EVERY_DAY"
(#) for development purposes you may wish to append: -J-Dnetbeans.logger.console=true -J-ea

(#) default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
jdkhome="C:\Program Files (x86)\Java\jre1.8.0_201\"

(#) clusters' paths separated by path.separator (semicolon on Windows, colon on Unices)
(#)extra_clusters=

... but it doesn't work.

N.B. I change the (#) for the description, the ( ) are not included in the script.

## Possible Solution

I think, the path should be changed, but I don't know how... Thank you much in advance!

## Steps to Reproduce

1.
2.
3.
4.

## Context

I am trying to open GEPHI 0.9.2 to work on Social Network Analysis for my Phd Thesis. It's quite urgent!

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_201b09
* Operating System: Windows 10 Entreprise 2016 LTSB

**Comment by chhh** [comment]
@BaptisteHamburg Try editing `<gephi-install-dir>/etc/gephi.conf`, uncomment `jdkhome` there and supply your jdk or jre there like so:  
`jdkhome="C:\Programs\Java\oracle-jdk-8"`

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) embed Java (JRE11) on Linux/Windows/MacOS so no need anymore to install Java separately. This should solve most Java compatibility issues.
