### ISSUE TITLE
Can't Downlaod for Mac OS

### ISSUE THREAD

**Issue by aaronraptor** [gephi/gephi#2077]
## Expected Behavior
When I click on .dmg file, I was expecting the program's download to begin

## Current Behavior
Pop-up that states: "The following disk images couldn't be opened."

## Steps to Reproduce

1.
2.
3.
4.

## Context

I'm just looking to try this program. I'm been looking for a program that could perform these exact tasks, so I'm excited to use this. I'm not a programmer. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: I'm not sure how to check this, everything on my computer should be up to date
* Operating System: MacOZ Mojave 

<img width="416" alt="screen shot 2019-02-03 at 9 20 33 pm" src="https://user-images.githubusercontent.com/47308298/52185189-7a154680-27fb-11e9-896a-83ed45bf07d5.png">

**Comment by wetneb** [comment]
It seems like your dmg file is corrupt, how about trying to download it again? Closing for now as it does not seem like something we can fix.
