### ISSUE TITLE
Miserable performance on potent hardware /w Gephi 0.9.2

### ISSUE THREAD

**Issue by NetwarSystem** [gephi/gephi#2079]
I have recently moved from a MacBook Pro to an HP Z620. The new system has dual Xeon processors and 128 gig of ram. I'm driving a 4k monitor at 3840x2160 using an Nvidia GTX 1030 and I recently attached a smaller 1080x1920 display which I am using in portrait mode. I'm using Ubuntu 18.04 and I have the recommended Nvidia driver #390. Given that the machine has an enormous amount of ram compared to the Mac I used -J-Xms8192m -J-Xmx16384m for settings in gephi.conf.

I have made a lot of adjustments to the user interface in terms of fonts and such, including installing the Gnome Tweaks utility.

When I launch Gephi the initial load a project dialog box is the normal size, but has very large fonts. If I expand it, this only partially corrects the problem. Issues like this occur in other dialogs, too.

I have a file with 112k nodes and about 325k edges which I'm importing from CSV. If I wasn't familiar with the interface I would not be able to do this at all - the issues with large fonts in normal sized windows that don't correct upon resizing are numerous.

Once the file is imported, Gephi becomes 'grabby' regarding the mouse and keyboard. It'll hang for long periods of time during which I can not shift to other applications.

This makes me very sad, as I was very much looking forward to Force Atlas 2 with 32 threads. Here's the most recent log file - is there anything I can do to make Gephi behave in this environment?

https://gist.github.com/NetwarSystem/da7a0ac075ed6e368f59022fb34a9796

**Comment by eduramiba** [comment]
We are working on it:

https://gephi.wordpress.com/2019/02/02/exploring-the-dystopian-future-of-a-javascript-gephi/
https://github.com/gephi/viz-engine

**Comment by NetwarSystem** [comment]
That took less than sixty seconds to get an answer :-)

If I can manage to build the viz-engine, I get some Gephi functions, but not yet node names? That would be a show stopper for me.

The networks I am working with are getting progressively larger, I'm already running distributed Elasticseaerch to handle the text data, and I'm about to start on the path to a Neo4j implementation. I think I will create an OSX virtual machine and see if I can make Gephi behave in that.

Thanks for all that you guys do, I know this is a tough, multifaceted problem.
