### ISSUE TITLE
Export SDG/PDF/PNG - not displaying correctly

### ISSUE THREAD

**Issue by sarahking345** [gephi/gephi#2082]
On exporting a directed network visualisation - all export options (SDG, PNG, PDF), display differently to what I see on Overview tab in Gephi. Specifically; node labels are removed, arrows removed, node and edge colour removed, edges are no longer straight (are curved).  Export doesn't resemble what is displayed on overview panel.

## Expected Behavior
That the exported visualisation is identical to the visualisation displayed in Overview panel.

## Current Behavior
Not exporting visualisation correctly 

## Possible Solution
No idea - help! Is this a bug or do I need to change a setting somewhere so I can export my visualisations? Is this a Java issue?

## Steps to Reproduce

1. File/Export/SVG/PDF/PNG
2. Choose any one of those options
3. Save and open file
4. See that it doesn't represent the coloured, labelled, directed network visualisation graph displaying in Gephi in the Overview tab

## Context

This is a big issue for me. If I can't export my visualisations I need to learn another package. I have already spent a year+ working my data on Gephi for my PhD. I am reluctant to move platforms at this stage of my research.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 181
* Operating System: Windows 7

**Comment by eduramiba** [comment]
Hi,
Unfortunately this is the expected behavior of Gephi at the moment.
For preview, separate settings (with some sample presets) are available at the preview settings window in Preview tab.

This is something we want to unify in the future, though.

**Comment by sarahking345** [comment]
Hi Eduramiba,
Thanks for your comment :)

Is there an alternative way I can export Gephi social network diagrams with good quality for a journal or thesis?
In the preview tab - nothing displays. It looks like this is a known bug too - http://forum-gephi.org/viewtopic.php?f=4&t=6644
But if I fix it, does that mean I can export a PNG or SVG?

Alternatively, can I export diagrams by downloading an earlier version? (If that's available?). Will this work better on a Mac?
Many thanks,
Sarah

**Comment by H-Rao** [comment]
Hello @eduramiba 
Thanks for the comment, but it is 2021 now the same issue persists!
Has it been considered in the recent releases?

**Comment by eduramiba** [comment]
Hello @H-Rao 

This has not been changed yet, and we are executing first a Gephi sustainability plan. With the future visualization engine (https://github.com/gephi/viz-engine) this could be a chance to finally make the settings shared across overview and preview, since the rendering in the new engine is extensible and flexible.

**Comment by H-Rao** [comment]
Thanks @eduramiba. Looking forward to that!

**Comment by SpinnerK** [comment]
Hello, @eduramiba,

I am having the same issue and was wondering if this had been fixed now?

Thank you.

**Comment by y-sheng** [comment]
Mine exported fine in png format but not pdf. :(

**Comment by SpinnerK** [comment]
Apparently Gephi's PDF export does not work properly yet.
What you can do is increase the resolution of the PNJ export.
You can do that by clicking on "export" then "options" then write bigger numbers. 
I used 8000 and 6000 and found it perfect.

**Comment by gulelmo** [comment]
I had the same problem exporting pdf, the solution was uninstall all plugins ans export pdf correctly. Cheers!!
