### ISSUE TITLE
Import error in 0.9.2

### ISSUE THREAD

**Issue by jcmundy** [gephi/gephi#2083]
## Expected Behavior
When I import a csv edge file, as Undirected and don't merge, it should retain all rows.
## Current Behavior
Despite showing all rows before I import, it is dropping a certain number (the same every time) of rows.  It drops the same rows every time, and I cannot tell any reason why those.  If I add the column "Type" to my csv and add "Undirected" to each row, it instead imports all rows without dropping any. 
## Possible Solution
It appears that something is going wrong with the combined selection of Undirected and do not merge.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: mac

INFO [AppendProcessor]: # Nodes loaded: 3,890
INFO [AppendProcessor]: # Edges loaded: 6,992
INFO [AppendProcessor]: # Nodes loaded: 3,890
INFO [AppendProcessor]: # Edges loaded: 6,759
* the number of edges in these should be the same.

**Comment by wetneb** [comment]
Hello, thank you for this report!
It is unlikely that we can reproduce this bug without a sample file. Therefore I am closing this issue for now, but can happily reopen it if you can share a sample file.
