### ISSUE TITLE
seeing a grey screen with no options to look at anything

### ISSUE THREAD

**Issue by bacheled** [gephi/gephi#2085]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by bacheled** [comment]
Missing the "appearance tab" or anything below workspace, just dark grey window with nothing. What do I need to do to see options.

**Comment by wetneb** [comment]
Hello, thank you for this report!
It is unlikely we can reproduce this issue without some precise information about your operating system and Java version, so I am closing this for now. If you still have this issue, feel free to get back to us and we can reopen this.
