### ISSUE TITLE
Cannot find AttributeController

### ISSUE THREAD

**Issue by cosminvlaicu** [gephi/gephi#2086]
## Expected Behavior
no error on line
AttributeModel attributeModel = Lookup.getDefault().lookup(AttributeController.class).getModel();
## Current Behavior
AttributeModel.class cannot be found with Maven

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am trying to use Gephi for automatically generating a graph. I am using Gephi Toolkit version 0.9.2 with Maven in Netbeans. The only problem in the code is the following line:
AttributeModel attributeModel = Lookup.getDefault().lookup(AttributeController.class).getModel();

Also the package: **import org.gephi.data;** cannot be found.

Netbeans cannot find AttributeController.class, and this happens even if I put this single line in my code. Do you have any fixes ? 

When I'm switching to 0.9.1 the entire code (and even the demos from github online tutorials) behaves very strangely (multiple packages cannot be found).

## Your Environment
* NetBeans IDE 8.1 (Build 201510222201) with Maven
* Version used: Gephi 0.9.2
* Java version: 1.8.0_91; Java HotSpot(TM) 64-Bit Server VM 25.91-b14
* Operating System: Mac OS X version 10.14.4 running on x86_64; UTF-8; en_US (nb)

**Comment by mbastian** [comment]
Closing old issue. Seems like you were trying to use 0.8 documentation while having 0.9 APIs. See API changes on https://gephi.org/gephi/0.9.2/apidocs/. Search for "Complete rewrite of the GraphAPI"
