### ISSUE TITLE
Illegal access operation warning and installation improvement

### ISSUE THREAD

**Issue by MrMorals** [gephi/gephi#2087]
## Expected Behavior
I unzipped gephi in a folder. Then in the terminal I went to the unzipped folder and executed gephi by using ./bin/gephi I expect the gephi application to start up without showing any issues.

## Current Behavior
After executing the command Gephi starts up, that is good. However in the terminal it shows: 
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/me/Programs/gephi-0.9.2-linux/gephi-0.9.2/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/me/Programs/gephi-0.9.2-linux/gephi-0.9.2/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

## Possible Solution

I do not know about the above. However, it is quite cumbersome to have to navigate to the right folder and execute in the commandline to start up the application. Therefore, I would love it if Gephi would be packaged as a Snap application.

## Steps to Reproduce

1. Download and unzip gephi in a folder in home directory.
2. In the unzipped folder open the bin folder in the terminal, execute ./gephi
3. Watch the terminal output.

## Context
This issue scared me, because it seems like the program might contain some mallicious code connecting to a malicious domain. Also I find it cumbersome that the application is not just installable as a Snap or something, and dockable in Favourites for frequent use.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: openjdk version "10.0.2" 2018-07-17
* Operating System: Ubuntu 18.04.2 LTS

**Comment by eduramiba** [comment]
Hi,
Gephi has not been adapted to Java 9+ yet. You will need to use Java 8

**Comment by MrMorals** [comment]
While not taking away that Gephi should definitely be adapted to use recent java versions that are aparently default in use by current OSs, I will share some of my steps in switching to java 8 to get Gephi working (because visualisation did not work). It wasn't easy for me. I think that a fast solution is needed: either the instructions for switching back to an older java version should be more clearly outlined on the https://gephi.org/users/install/ page, or Gephi should be adapted to newer java very quickly.

Java 10 doesn’t work for Giphy yet. So switch to Java 8 (aparently this only switches JRE, not JDK or something):
https://askubuntu.com/questions/272187/setting-jdk-7-as-default
also copy the path of the chosen java version

change the path of the java version to the chosen path to Java 8
https://vitux.com/how-to-setup-java_home-path-in-ubuntu/

Start up gephi by from the bin folder in gephi executing (as specified in the Gephi installation instructions: https://gephi.org/users/install/)
`./gephi --jdkhome $JAVA_HOME`

Note: ./gephi now does not work anymore and gives:
`Cannot find java. Please use the --jdkhome switch.`
I do not know if I broke my system by switching java version using `update-alternatives` instead of using the `update-java-alternatives` as specified in the first step. However the last method gives me an error:
`my@computer:~$ update-java-alternatives -l
java-1.11.0-openjdk-amd64      1101       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64       1081       /usr/lib/jvm/java-1.8.0-openjdk-amd64
my@computer:~$ sudo update-java-alternatives -s
[sudo] password for w: 
Sorry, try again.
[sudo] password for w: 
usage: update-java-alternatives [--jre-headless] [--jre] [--plugin] [-v|--verbose]
           -l|--list [<jname>]
           -s|--set <jname>
           -a|--auto
           -h|-?|--help
my@computer:~$ sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for mozilla-javaplugin.so
update-java-alternatives: plugin alternative does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/IcedTeaPlugin.so
`
If anybody knows why, please do let me know.

**Comment by MrMorals** [comment]
After restarting my computer I cannot run gephi anymore. Upon checking the $JAVA_HOME I can see that it is now empty and and the $PATH hasn't got java appended to it anymore. Following the steps I mention above gets it working again. 

However, this means that I have to do the above steps **all over again, every time after a restart, to run Gephi** on Ubuntu 18.04.2 LTS. Could anyone please help me and others running up-to-date Ubuntu and want to use Gephi by: either adding to the instructions for switching back to an older java version and making them more clear on the https://gephi.org/users/install/ page, or adapt Gephi for use with newer java?

**Comment by eduramiba** [comment]
Hi, Sorry for the inconvenience.
We will update documentation to make it more clear until Gephi can work with Java 9 or newer.

I suggest you export `JAVA_HOME` in your `.bashrc` or just edit the `jdkhome` in `gephi-0.9.2/etc/gephi.conf` so it points to the java version that you want Gephi to use (and remember to uncomment the `jdkhome` line by removing the `#` prefix).

**Comment by MrMorals** [comment]
Hi Eduramiba,

Thank you for your comments :)
I already had the line in the gephi.conf edited last time so that is said: 
`jdkhome="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"` without the hash
This line was still the same today, but it did not help apparently.

As for 'export JAVA_HOME in your .bashrc', I do not have enough experience with JAVA_HOME or .bash-rc to know what you mean by this. Could you elaborate or give instructions for that please? Thank you very much!

**Comment by eduramiba** [comment]
Hi,
The path for jdkhome should be `jdkhome="/usr/lib/jvm/java-8-openjdk-amd64/` (or `jdkhome="/usr/lib/jvm/java-8-openjdk-amd64/jre`, not sure)

For bashrc, check this example https://learn.adafruit.com/an-illustrated-guide-to-shell-magic-typing-less-and-doing-more/customize-your-bashrc

**Comment by MrMorals** [comment]
It seems that `jdkhome="/usr/lib/jvm/java-8-openjdk-amd64/"` did the trick indeed. Thanks!

**Comment by wetneb** [comment]
Closing this since Gephi is now compatible with Java 11.

**Comment by hpcpony** [comment]
Just downloaded 0.9.5 and get this:

```
libEGL warning: DRI2: failed to authenticate
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.core.windows.view.ui.MainWindow (jar:file:/opt/gephi-0.9.5/platform/modules/org-netbeans-core-windows.jar!/) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.netbeans.core.windows.view.ui.MainWindow
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
According to the "About" popup it's using Java 11.0.15 and runtime OpenJDK 11.0.15+10 so it seems like this shouldn't be an issue.

Things seem to be working fine, it's just kinda annoying and sounds like something someone will eventually want to fix.

**Comment by gaardhus** [comment]
I'm getting the same error, with a fresh install on Ubuntu. It works when I use the default Ubuntu desktop, but when I use sway as my WM i get the error:

```
~/Downloads/gephi-0.10.1 ❯ bin/gephi                                                                                                                                                               
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.core.windows.view.ui.MainWindow (jar:file:/home/gaardhus/Downloads/gephi-0.10.1/platform/modules/org-netbeans-core-windows.jar!/) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.netbeans.core.windows.view.ui.MainWindow
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
