### ISSUE TITLE
Not all selected nodes/edges are moved/copied to new workspace

### ISSUE THREAD

**Issue by jbliesener** [gephi/gephi#2088]
## Expected Behavior
When selecting and copying/moving nodes to other workspaces, all selected nodes and edges should be copied, independently from zoom level and pan location.

## Current Behavior
Not all selected nodes are copied, only those in vincinity of the currently viewed area. 

This occurs, because the iterators in OcTree only iterate over visible octants. If the user changed zoom level or pan location between the node/edge selection and the copy operation, some of the selected nodes can be in invisible octants and therefore will not be returned on engine.getSelectedNodes, leading to them not being copied/moved.

This happens as well if the nodes are selected from a plugin with VizualizationController.selectNodes(), which is my specific use case. However, the root problem is that OcTree.OctantIterator does not iterate over invisible octants. 

## Possible Solution
Use different iterator in OcTree to get selected nodes.

## Steps to Reproduce

See attached video

## Context

My plugin selects nodes in the graph with VizualizationController.selectNodes(). Some of these nodes are on screen, others are not. Trying to copy all selected nodes to a new workspace results in not all nodes being copied.

Tracing down the problem, I disovered that although all NodeModels are correctly marked as selected when SelectionManager.selectNodes() calls engine.selectModels (https://github.com/gephi/gephi/blob/c1d40ce28b482a42e08177f2f6f998da59967cf4/modules/VisualizationImpl/src/main/java/org/gephi/visualization/api/selection/SelectionManager.java#L167), calling engine.getSelectedNodes() immediately afterwards can return a different number. Tracking it down further reveals that OcTree.OctantIterator does not return nodes in invisible octants.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System:  Windows 10
[Video copy node issue.zip](https://github.com/gephi/gephi/files/2963040/Video.copy.node.issue.zip)

**Comment by jbliesener** [comment]
Any comment on this?

**Comment by mbastian** [comment]
Thank you, good catch! I've merged your PR. It will be included in the upcoming 0.9.3 release. Cheers,
