### ISSUE TITLE
Problem with shorcut (when selecting file)

### ISSUE THREAD

**Issue by pdeman** [gephi/gephi#2090]
## Expected Behavior
open file explorer without error
## Current Behavior
generate the following error for any location I go (C:, MyDocuments, etc ...)
![2019-03-20 09_07_03-Open](https://user-images.githubusercontent.com/16150529/54668718-d99b8d00-4aef-11e9-8ada-21cf28cfe725.png)

## Steps to Reproduce

1.Install java v8 update 201
2.install gephi 0.9.2
3.open graph file or import or open, anything needing a file explorer

## Context
importing a csv of my network ...

## Your Environment

* Version used: Gephi 0.9.2
* Java version: C:\Program Files\Java\jre1.8.0_201
* Operating System: windows server 2019

**Comment by eduramiba** [comment]
It seems you have some problematic file/shortcut/drive in your system with that name. Can you try to remove it?

**Comment by pdeman** [comment]
remove what ? I didn't understand

**Comment by eduramiba** [comment]
`RemoteDesktopLocker.exe - Shortcut.Ink` it's something strange that I don't know what can be, but it's causing the problem.

**Comment by pdeman** [comment]
it's related to the remote desktop control of windows.

**Comment by eduramiba** [comment]
Please try to temporarily remove it just to check if it's actually causing the problem.

**Comment by pdeman** [comment]
yes it works when removed.

**Comment by eduramiba** [comment]
I see, is it completely necessary to have it where it was? You can try to move it to some other folder so it does not cause problems. Not sure why it's causing that problem though.

**Comment by pdeman** [comment]
no I moved it, I don't need to put it back where it was. so problem not solved but not fixed I guess. but it's fine by me.

**Comment by eduramiba** [comment]
Great!
