### ISSUE TITLE
Export to PDF should support transparent background

### ISSUE THREAD

**Issue by aparamon** [gephi/gephi#2093]
## Current Behavior
Preview export to PDF always saves background rect.

## Expected Behavior
There should be an option to have transparent background, like when exporting PNG.

## Your Environment
* Product Version: Gephi 0.9.2 201709241107
* Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
* Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
* System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (gephi)
* User directory: C:\Users\paramon\AppData\Roaming\.gephi\0.9.2\dev
* Cache directory: C:\Users\paramon\AppData\Roaming\.gephi\0.9.2\dev\var\cache

**Comment by mbastian** [comment]
Makes sense, let me summarise.

### Definition of done
- Add option to PDF configuration panel for transparent background. Makes sure this configuration is also saved in preferences like the others.
- Modify PDF export accordingly

**Comment by Meta-Ace** [comment]
To my understanding and through trial and error this feature does not seem possible! I have exported images from other programs with a "transparent" background, and when the PDF is opened, they white rectangle is drawn in. Changing the alpha to 0 and making the canvas transparent both still resulted in the white rectangle being drawn. I believe this is due to the fact that PDF requires there to be a canvas, as opposed to PNG which acts as a bitmap. This is my current understanding, if you know otherwise please feel free to reach out

**Comment by mbastian** [comment]
Thanks @Meta-Ace. How did you actually check whether the PDF has transparent background? In which program? Based on my own research it does seem that PDFs can have transparent backgrounds.

**Comment by Meta-Ace** [comment]
Come had a program that already supported exporting transparent backgrounds, I don't know which exactly and we selected transparent background for PDF and when we opened it it was a white background. I would have to ask him which program it was.

**Comment by mbastian** [comment]
Hi again, I did a bit more research and was able to create PDF with transparent background. I think you didn't have the proper software to actually check that it's transparent - hence the confusion. I found this trick with Acrobat Reader settings. If you check this it will show a grid when transparent

<img width="436" alt="Screenshot 2022-09-05 at 20 48 25" src="https://user-images.githubusercontent.com/234813/188502190-edcdc30c-5c91-44cd-9672-a8fd1c024f10.png">

Then by commenting out line `size.setBackgroundColor(new BaseColor(col.getRed(), col.getGreen(), col.getBlue()));` on `PDFExporter` class you should get a transparent background.

**Comment by mbastian** [comment]
Added new checkbox in PDF config menu
<img width="327" alt="Screenshot 2022-10-08 at 20 51 50" src="https://user-images.githubusercontent.com/234813/194723090-aa0d389c-6c17-4ef9-8290-6d7ae8e8f1e9.png">
