### ISSUE TITLE
Display glitch in Gephi Mac 0.9.2

### ISSUE THREAD

**Issue by danmeek** [gephi/gephi#2097]
**The content of a Graph window in Preview mode remains visible when the window is changed, obscuring other UI elements.**

## Expected Behavior

Changing from a Graph window back to a Preview window should hide the contents of the Graph window.

## Current Behavior

The contents of the Graph window persist and obscure UI in the Preview window.

## Steps to Reproduce

1. Delete the Gephi library folder, download and install Gephi 0.9.2 on MacOS Mojava 10.14.3.
2. Open an existing Gephi file, open the Preview mode, hit Refresh to generate a preview.
3. Open a Graph window alongside the existing Preview window.
4. Switch from the Graph window back to the Preview window.

Screenshot: 

<img width="1485" alt="Screen Shot 2019-04-12 at 11 48 05 AM" src="https://user-images.githubusercontent.com/26449951/56059213-98368000-5d31-11e9-9cac-684df3ed4e7c.png">

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_144
* Operating System: MacOS Mojave 10.14.3

[messages.log](https://github.com/gephi/gephi/files/3074774/messages.log)

**Comment by danmeek** [comment]
Bump! Is Gephi for Mac being actively maintained?

**Comment by eduramiba** [comment]
Yes. We are in the process of migrating to a new visualization engine and expect this bug to be fixed in the future.

**Comment by danmeek** [comment]
Thank you for that information. I'm working on a project using network analysis to visualise markets in disability services, and I'm hoping to deliver visualisations in the next month or so. Are you able to say whether Gephi is likely to be fixed in that timeframe? This bug completely disables the entire interface — there's nothing the user can do to fix it and it recurs after a restart.

**Comment by eduramiba** [comment]
Sorry it can't be available so soon. I recommend you use Windows for Gephi meanwhile.

**Comment by danmeek** [comment]
Then I would request you identify and fix this particular display bug, which renders Gephi 0.9.2 unusable for Mac users. I understand that you'd rather put your efforts into the more radical fix, totally redoing the visualisation engine. But in the meantime, all the Mac users are in trouble. These are people who have been encouraged to learn Gephi by its evangelists, who have invested their time in learning how to use it, who are counting on it to get their projects done.

**Comment by eduramiba** [comment]
Sorry it's far from trivial and prorably not possible with the old JOGL opengl implementation we use in Gephi 0.9.2. The switch to LWJGL is what is in progress for the new visualization engine, and that takes time.

**Comment by danmeek** [comment]
We're just talking about the content of the Graph window not continuing to display when the user switches to the Preview window. To my knowledge this problem did not occur with earlier Gephi for Mac versions. What changed with 0.9.2 that prevents this being fixable?

**Comment by eduramiba** [comment]
Hi,
As far as I know, this has been happening to some Macs since a long time ago, and it does not depend on Gephi version, as we didn't change anything in that matter.
Can you test if it happens with Gephi 0.9.1 or even 0.9.0?

The second problem is I cannot even build or test software for OSX because I don't own a Mac. Even virtualization is not possible. I could build software for almost any OS, just not OSX...

When we release the new engine, I will make sure to test it in some friend's Mac.

**Comment by Mrinal-1996-oss** [comment]
So, I am facing the problem with my GEPHI not opening up. It says that the application cannot  be opened.When I looked up , it said that I had to change the gephi.conf file and change the jdkhome space in the folder.So , I did the following:
jdkhome="/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home/".
But,I still seem to not be able to open up my GEPHI file.Could you tell me why this is happening?
Hoping to hear from you, soon

**Comment by danmeek** [comment]
Closing unfixed
