### ISSUE TITLE
No mode indicator in Appearance panel in Gephic Mac 0.9.2

### ISSUE THREAD

**Issue by danmeek** [gephi/gephi#2098]
**It is nearly impossible to know which mode is selected in the appearance window.**

## Expected Behavior

The selected mode should be highlighted in some way. E.g. if Edges is active, then the selector for Edges would be shaded.

## Current Behavior

At present, the only indication is that the 'Size' icon appears when the Nodes sub-panel is active and not when Edges is active. Similar problem with Unique, Partition and Ranking sub-sub-panels.

**Screenshot: can you guess which panel is active?**

<img width="305" alt="Screen Shot 2019-04-12 at 11 49 04 AM" src="https://user-images.githubusercontent.com/26449951/56059836-18a9b080-5d33-11e9-875f-079ccf6fa840.png">

## Context

Causing problems trying to collaborate with team members using Gephi on the same project.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: MacOS Mojave 10.14.3

**Comment by tillgrallert** [comment]
Bump. Same here on macOS Mojave 10.14.6, Java 1.8 and Gephi 0.9.2

**Comment by danmeek** [comment]
That's literally by design it seems. Earlier versions had it. I've raised
other more serious bugs and been told they won't be fixed til the renderer
is replaced, no timeline to do that. I've stopped using Gephi altogether.

**Comment by eduramiba** [comment]
Mmm this seems a problem with styling and should be fixed for next version, thanks for the report.

**Comment by mbastian** [comment]
Thanks for the report, this seems to originate with a [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8250953) that unfortunately is still open. 

I tried a few things without success but as a workaround I'm bolding the text so one can at least see what's selected
<img width="262" alt="Screenshot 2021-12-23 at 14 08 31" src="https://user-images.githubusercontent.com/234813/147245386-0e9b4911-fe39-4b08-be91-5365cd3e0e66.png">

**Comment by mbastian** [comment]
Hopefully that's sufficient for now until we have a more permanent solution. The fix will be included in the 0.9.3 version.

**Comment by mbastian** [comment]
Actually, I did another pass and was able to finally fix the issue with another workaround. It will be included in the next 0.9.3 release.
