### ISSUE TITLE
Neighbors Network filter freezes with max depth

### ISSUE THREAD

**Issue by lame-impala** [gephi/gephi#2099]
## Expected Behavior
I have a trivial circular graph defined with four nodes. Neighbors Network filter with max depth setting run when all nodes are visible should simply leave all nodes visible

## Current Behavior
Filter hangs for infinity

## Possible Solution
In the function that actually performs filtering, keep track of the visited nodes and check whether each candidate has been visited before adding it into neighbors array
  
public Graph filter(Graph) {
  ...
  Collection<Node> nodes = graph.getNodes().toCollection();
  Set<Node> seen = new HashSet(nodes);
  ...
  for (Node n : nei) {
  //Extract all neighbors of n
  for (Node neighbor : mainGraph.getNeighbors(n)) {
    if (!seen.contains(neighbor)) {
      neighbours.add(neighbor);
        seen.add(neighbor);
        result.add(neighbor);
    }
  }
  ...
}

## Steps to Reproduce

1. Create graph from the data in the attached file

[test.txt](https://github.com/gephi/gephi/files/3076822/test.txt)

2. run Neighbors Network filter

* Version used: Gephi 0.9.2
* Java version: 1.8.0_171
* Operating System: Ubuntu

**Comment by BenWeigt** [comment]
Still an issue 12mo later

**Comment by mbastian** [comment]
Thanks for the report - I do appreciate the details - this has been fixed in master now and will be included in the next 0.9.3 release
