### ISSUE TITLE
Preview not displayed

### ISSUE THREAD

**Issue by uocmar** [gephi/gephi#2100]
Hi,

I cannot see the graph in the preview, I suppose there is a bug. Could you help me, please?

Thanks!
M

**Comment by foreveryoung123456** [comment]
so do i,i do not konw how to solve out this problem.

**Comment by foreveryoung123456** [comment]
well,i think i have known how to do.
Firstly,click the "reset window"in the preview,then you will find the graph

**Comment by tautme** [comment]
I find this happen after I have saved and reopened multiple times. Instead of opening the file from your saved version, open gephi first with a blank project and open your file from the File - Open menu.

**Comment by wetneb** [comment]
Thank you for this report!
Unfortunately, this is not specific enough for us to understand how to reproduce this issue and fix any corresponding bug. Happy to reopen the issue if you can provide a sample file with which the bug happens.
