### ISSUE TITLE
Cant concrete execution /bin/gephi for installation: Inconsistency detected by ld.so: dl-lookup.c

### ISSUE THREAD

**Issue by DChaps13** [gephi/gephi#2102]
## Context
Hi, I tried to download gephi for Ubuntu but when i executed: ./bin/gephi
it gave me this error:
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

I havent found anything similar for fixing this, help pls

## Your Environment
* Version used: Gephi 0.9.2
* Java version: openjdk version "11.0.2"
* Operating System: Ubuntu 18.04

**Comment by eduramiba** [comment]
Hi,
Gephi 0.9.2 only works with Java 8

**Comment by ricmarto** [comment]
Hi, I am facing the same problem. I have both Java 11 and 8 installed in Ubuntu and currently using Java 8 and still gephi is unable to launch. Could you provide a step-by-step solution for this?

**Comment by eduramiba** [comment]
@ricmarto You can try to uncomment and specify `jdkhome` in `gephi.conf` file in Gephi directory.

**Comment by acriptis** [comment]
Where is gephi.conf placed?
I've checked ~/.gephi:
```
alx@x3:~/gephi-0.9.2$ ll ~/.gephi/
total 12
drwxrwxr-x  3 alx alx 4096 Dec 12 18:31 ./
drwxr-xr-x 67 alx alx 4096 Dec 12 18:31 ../
drwxrwxr-x  3 alx alx 4096 Dec 12 18:31 0.9.2/
alx@x3:~/gephi-0.9.2$ ll ~/.gephi/0.9.2/
total 12
drwxrwxr-x 3 alx alx 4096 Dec 12 18:31 ./
drwxrwxr-x 3 alx alx 4096 Dec 12 18:31 ../
drwxrwxr-x 4 alx alx 4096 Dec 12 18:32 dev/
alx@x3:~/gephi-0.9.2$ ll ~/.gephi/0.9.2/dev/
total 20
drwxrwxr-x 4 alx alx 4096 Dec 12 18:32 ./
drwxrwxr-x 3 alx alx 4096 Dec 12 18:31 ../
-rw-rw-r-- 1 alx alx    0 Dec 12 18:32 .lastModified
drwxrwxr-x 2 alx alx 4096 Dec 12 18:31 config/
-rw--w---- 1 alx alx   18 Dec 12 18:43 lock
drwxrwxr-x 4 alx alx 4096 Dec 12 18:31 var/
alx@x3:~/gephi-0.9.2$ ll ~/.gephi/0.9.2/dev/config/
total 8
drwxrwxr-x 2 alx alx 4096 Dec 12 18:31 ./
drwxrwxr-x 4 alx alx 4096 Dec 12 18:32 ../

```

and there is no gephi.conf in installation directory as well...

**Comment by eduramiba** [comment]
It's in install directory and then `etc` folder.

**Comment by acriptis** [comment]
Thanks @eduramiba !

**Comment by anki-code** [comment]
Run Gephi on Ubuntu 20.04:
```
cd /tmp \
    && apt install openjdk-8-jdk openjdk-8-jre \
    && wget https://github.com/gephi/gephi/releases/download/v0.9.2/gephi-0.9.2-linux.tar.gz \
    && tar -zvxf gephi-0.9.2-linux.tar.gz -C /opt
    && rm gephi-0.9.2-linux.tar.gz
    
cd /opt/gephi-0.9.2/bin && ./gephi
```

**Comment by Ziip-dev** [comment]
Same problem on Ubuntu 18.04 despite having defined `jdkhome` in `gephi.conf`:

**gephi.conf**
`# default location of JDK/JRE, can be overridden by using --jdkhome <dir> switch
jdkhome=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/`

**~/gephi-0.9.2$ ./bin/gephi**
`Cannot find java. Please use the --jdkhome switch.`

The result is the same if I add the jdkhome argument to the script call

**Comment by Ziip-dev** [comment]
> Run Gephi on Ubuntu 20.04:
> 
> ```
> sudo bash
> cd /tmp \
>     && apt install openjdk-8-jdk openjdk-8-jre \
>     && wget https://github.com/gephi/gephi/releases/download/v0.9.2/gephi-0.9.2-linux.tar.gz \
>     && tar -zvxf gephi-0.9.2-linux.tar.gz -C /opt
>     && rm gephi-0.9.2-linux.tar.gz
>     
> cd /opt/gephi-0.9.2/bin && ./gephi
> ```

by the way I have tried those steps and it still produces the same error than the very first post of this issue :/
Thanks for your help

**Comment by RudolfCardinal** [comment]
With Gephi 0.9.2 and Ubuntu 20.04.1, with a system default (``java --version``) of OpenJDK 11.0.8, but with OpenJDK8 installed (``sudo apt install openjdk-8-jdk openjdk-8-jre``), the suggestion of editing ``etc/gephi.conf`` before running ``bin/gephi`` works, but the line required is ``jdkhome="/usr/lib/jvm/java-8-openjdk-amd64"``.

**Comment by pmansfilmn** [comment]
I got gephi working on Fedora 34 by installing these packages:
```
java-1.8.0-openjdk-headless-1.8.0.302.b08-2.fc34.x86_64
java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64
java-1.8.0-openjdk-devel-1.8.0.302.b08-2.fc34.x86_64
```

then updating alternatives to look like this:
```
# update-alternatives  --list | egrep -E "java|jdk|jre"
java_sdk_1.8.0        	auto  	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64
jre_1.8.0_openjdk     	auto  	/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64
jre_11                	auto  	/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-4.fc34.x86_64
java_sdk_17           	auto  	/usr/lib/jvm/java-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64
javac                 	manual	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64/bin/javac
java_sdk_openjdk      	auto  	/usr/lib/jvm/java-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64
jre_17                	auto  	/usr/lib/jvm/java-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64
jre_1.8.0             	auto  	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64/jre
java_sdk_17_openjdk   	auto  	/usr/lib/jvm/java-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64
java                  	manual	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64/jre/bin/java
jre_11_openjdk        	auto  	/usr/lib/jvm/jre-11-openjdk-11.0.12.0.7-4.fc34.x86_64
jre_openjdk           	auto  	/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-4.fc34.x86_64
jre_17_openjdk        	auto  	/usr/lib/jvm/jre-17-openjdk-17.0.0.0.35-1.rolling.fc34.x86_64
java_sdk_1.8.0_openjdk	auto  	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-2.fc34.x86_64
```
