### ISSUE TITLE
Fails to Load File Upon Opening

### ISSUE THREAD

**Issue by hydroboy407** [gephi/gephi#2103]
## Expected Behavior
Open gexf file with gephi

## Current Behavior
Opens the program, but does not load the file

## Possible Solution
Have gephi load file

## Steps to Reproduce

1. Make sure gephi is not running
2. Click to open file in gephi
3. Gephi does not load file

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: MacOS 10.13.6

**Comment by wetneb** [comment]
Thank you for this report! It seems unlikely that we can reproduce and fix this issue without a sample file where the issue happens. Therefore I am tentatively closing this, happy to reopen the issue if you can provide a file.
