### ISSUE TITLE
Gephi 0.92 works GREAT on Ubuntu Budgie VM

### ISSUE THREAD

**Issue by NetwarSystem** [gephi/gephi#2104]
* Version used: Gephi 0.9.2
* Java version: openjdk-8-jre
* Operating System: Ubuntu Budgie 18.04 under VirtualBox

I have been using Gephi since 2014, primarily on OSX, and I've been very sad since getting a Xeon workstation with a 4k display running Ubuntu. Gephi interface was an absolute mess.

I periodically try new Debian derived distros running under VirtualBox. Today's lucky winner was Ubuntu Budgie, and as always, I reach for Gephi first - it's the acid test for user interface stuff.

And with the exception of the library of predefined spline choices, it's working pretty smoothly for me. This has not been the case with other distros I've tried, so much so that it's worthy of announcing here.

Per an earlier post, I know that the dev team is considering massive changes in the user interface specifically because of issues like this. In the mean time, if Gephi+Budgie works, that's a big relief.

**Comment by eduramiba** [comment]
Haha awesome!
