### ISSUE TITLE
 build fails: v0.9.2-47-g56b8733f0

### ISSUE THREAD

**Issue by yurivict** [gephi/gephi#2106]
I tried to create the FreeBSD for gephi but the build fails:
https://people.freebsd.org/~yuri/gephi-build-failure.log

**Comment by eduramiba** [comment]
Hi, we don't support FreeBSD yet, and JOGL does not support FreeBSD.
Maybe when we migrate to LWJGL3 with the new [viz-engine](https://github.com/gephi/viz-engine) https://github.com/LWJGL/lwjgl3/issues/421
