### ISSUE TITLE
How to make one Source have multiple Targets?

### ISSUE THREAD

**Issue by dhsdshdhk** [gephi/gephi#2107]
For example, I have an csv file like this:
Source Target
s1 t1;t2;t3
s2 a
s3 b
s4 c

How do I make s1 have as target t1, t2 and t3?
Or do I have to write s1 three times, one for each target?

**Comment by eduramiba** [comment]
In that format (spreadsheet), you need to repeat `s1` as source once per target.
But check other CSV formats such as adjacency list: https://gephi.org/users/supported-graph-formats/csv-format/

https://gephi.org/users/supported-graph-formats/
