### ISSUE TITLE
Black screen faint graph glitching - Overview

### ISSUE THREAD

**Issue by kuriimutaiyaki** [gephi/gephi#2110]
Hello, I have been using Gephi 0.9.2 for a while now and I haven't had any issues until yesterday. After updating my Lenovo laptop, Gephi's Overview Tab glitches and am unable to proceed with my research. 

Graphics Driver is up to date and working properly. Has anyone found a fix? Thank you for your time.

![image](https://user-images.githubusercontent.com/51934580/59700756-e8eead00-91a8-11e9-9d46-b79b35526f57.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8 update 211
* Operating System:  Windows 10

**Comment by jszurdi** [comment]
I have the same problem! Did you find a solution?

**Comment by kuriimutaiyaki** [comment]
> I have the same problem! Did you find a solution?
I had to revert the Display Driver update. I'm not sure what kind of computer/OS you have but I'm currently running on the following version and everything is working fine:

![image](https://user-images.githubusercontent.com/51934580/60619370-66134800-9d8d-11e9-9cc7-f2d67b2d31f6.png)

**Comment by jszurdi** [comment]
Lenovo with Windows 10. I have driver 26.20.100.6859. DO I have to revert to the version you mentioned?

Thank you for the help!

**Comment by kuriimutaiyaki** [comment]
> Lenovo with Windows 10. I have driver 26.20.100.6859. DO I have to revert to the version you mentioned?
> 
> Thank you for the help!

I also have a Lenovo and W10. Depending on your device model you'll need to find the PREVIOUS display driver version and download it from the Lenovo official site: https://pcsupport.lenovo.com/us/en/

Once downloaded, Remove and Delete the current Display Driver, then execute the file you got from the Lenovo website and your laptop will restart with that particular Display Driver version.
