### ISSUE TITLE
generatePalette is wrong

### ISSUE THREAD

**Issue by CymricNPG** [gephi/gephi#2112]
https://github.com/gephi/gephi/blob/c1d40ce28b482a42e08177f2f6f998da59967cf4/modules/AppearancePlugin/src/main/java/org/gephi/appearance/plugin/palette/PaletteManager.java#L117

The code makes no sense:

     public Palette generatePalette(int colorCount, Preset preset) {
        int quality = 50;
        if (colorCount > 50) {
            quality = 25;
        } else if (colorCount > 100) {
            quality = 10;
        } else if (colorCount > 200) {
            quality = 5;
        } else if (colorCount > 300) {
            quality = 2;
        }

I think it should be:

    var quality = 50
    if (colorCount > 300) {
        quality = 2
    } else if (colorCount > 200) {
        quality = 5
    } else if (colorCount > 100) {
        quality = 10
    } else if (colorCount > 50) {
        quality = 25
    }

**Comment by mbastian** [comment]
This was fixed in #2363, closing
