### ISSUE TITLE
Can't install/run Gephi on Mac

### ISSUE THREAD

**Issue by PeterGray1** [gephi/gephi#2114]
## Expected Behavior

Gephi installs and runs

## Current Behavior

Gephi appears to install but does not run.

## Steps to Reproduce

1. Trying to install Gephi 0.9.2 on a Mac with all software up to date. 
2. I click the dmg, it appears to extract correctly. 
3. When I click on "Gephi 0.9.2" in the sidebar, and I get the message: 

"“Gephi 0.9.2” can’t be opened because the original item can’t be found."

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: OS X 10.14.15

**Comment by mbastian** [comment]
Closing as this issue can't be reproduced. Please try again with the latest version 0.9.5 and reopen if it persists.
