### ISSUE TITLE
Error: Cannot find Java 1.8 or higher Windows 10

### ISSUE THREAD

**Issue by itchygrub** [gephi/gephi#2116]
install latest version Java
Edit
C:\ugsplatform-2.0.0-stable3\ugsplatform\etc\ugsplatform.conf
ADD -> jdkhome="C:\Program Files\Java\jdk-10.0.2"
reboot PC or Laptop
Start UGS

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi, at the moment Gephi only works with Java 8 and not higher
