### ISSUE TITLE
streaming graph from neo4j browser loads but freezes

### ISSUE THREAD

**Issue by mjkhn452** [gephi/gephi#2127]
I'm using Gephi's streaming plugin to visualize a graph from neo4j. My expectation is that the query in neo4j streams to gephi such that I can see and manipulate the graph, calculate statistics, etc. 

What's actually happening is that the graph is imported, but whenever I zoom in or move around, the graph freezes, or the image of the graph copies itself over with every attempt to zoom or move the graph. 

## Steps to Reproduce

1. In Gephi, I stream to "http://localhost:8081", I don't need authentication
2. I turn the Master Server on and it connects (green light)
3. In neo4j browser, my query is as follow:
match path = (s:System)<-[:HAS_SYSTEM]-(a:Activity)-[:HAS_INPUT]->(i:InputOutput)
CALL apoc.gephi.add('http://localhost:8081', 'workspace1', path, 'weight') yield nodes
RETURN *

* Version used: Gephi 0.9.2
* Java version: 1.8.0_211
* Operating System: Windows

[gephi log.txt](https://github.com/gephi/gephi/files/3436021/gephi.log.txt)

**Comment by mbastian** [comment]
Closing old issue. You might want to checkout the new Neo4j plugin that was just released https://gephi.org/plugins/#/plugin/neo4j-plugin
