### ISSUE TITLE
Implementation of new community detection algorithm Leiden

### ISSUE THREAD

**Issue by Marmeladenbrot** [gephi/gephi#2129]
Paper: https://www.nature.com/articles/s41598-019-41695-z
Java code: https://github.com/CWTSLeiden/networkanalysis

At the moment the code only supports undirected networks and each edge can only exist once in the graph according to the docs.

Maybe this new approach for community detection could be included in Gephi.

**Comment by eduramiba** [comment]
Hi,
This is already available as an official plugin in Gephi 0.9.2. You can install it in tools menu.

**Comment by Marmeladenbrot** [comment]
Thanks, didn't check the plugin section, my bad.

Is there a way to color nodes depending on the Leidenalgo results? I can choose the normal Modularity check if I analyse the graph with it but I can't choose Leiden, whether I choose CPM or Modularity?

**Comment by eduramiba** [comment]
You can partition by the `Cluster` column that it creates, just like modularity class.
Also make sure that you play with the Resolution parameter to Leiden algorithm, as it affects results very much.
