### ISSUE TITLE
Unexpected behaviour at node table when importing edge list

### ISSUE THREAD

**Issue by blas-ko** [gephi/gephi#2133]
## Expected Behavior
I have an edge list of the type *source, target, source*. When I import it to Gephi, I expect that the node table to have id as an integer number and the label as the actual label of my nodes, i.e. the names provided in *source* and *target*  

## Current Behavior
The node table has the source/target names as the id column, and it has the label column empty.

## Possible Solution
id should go from 1 to N and label should have the actual name of the nodes.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
* Operating System: Ubuntu 16.04

**Comment by eduramiba** [comment]
Hi,
This could be done automatically by Gephi when a missing node it's created (copy the id value to the label column).
But anyway it's very easy to do in data laboratory. Just click on the Copy to another column feature and copy data from `id` to `label`.
