### ISSUE TITLE
TSV Data import causes error because of inconsistency which cannot be found

### ISSUE THREAD

**Issue by slinssen** [gephi/gephi#2134]
## Expected Behavior
I'm trying to import a tsv dataset into gephi. It should work fine, because the dataset seems fine, even though it's quite large. See here: https://www.upf.edu/web/mtg/lastfm360k
 
## Current Behavior
The import crashes at line 6484 without a reason.
The error message I get is the following: "Issue{message=[Record #6,484] The record is inconsistent. Skipping record, level=SEVERE}	SEVERE"
When I look into the dataset the line seems fine without any inconsistency.
Gephi imports all data in front of the line 6484, which looks fine. But it doesn't continue with the import of the rest of the dataset.

## Possible Solution
I already removed possible bom, even though that should not be the reason of the error.

## Steps to Reproduce

1. Load dataset
2. Rename header lines (with the exception of musicbrainz-artist-id)
3. Import speadsheat (hide musicbrainz-artist-id)

## Context

I'm trying to work with the dataset and apply some filters to look at the network.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 8
* Operating System: macOS 10.14.6

**Comment by eduramiba** [comment]
Thanks for the report, I will try to reproduce it.

**Comment by slinssen** [comment]
I think I solved it myself: The data was inconsistent because it has some " signs in it. I will delete those and try to import again. Hopefully it will work

**Comment by eduramiba** [comment]
Great! Please reply with your results :)
