### ISSUE TITLE
Gephi freezes on second export

### ISSUE THREAD

**Issue by m4chi** [gephi/gephi#2137]
## Expected Behavior

Export to cdv as many times as needed

## Current Behavior

Export successful the first time, but Gephi freezes every time I export the same project a second time.

## Possible Solution
My current solution is to close Gephi and restart it every time I want to export part of a project.

## Steps to Reproduce

1. Export project data table to csv.
2. Press "Export table/Tabelle Exportieren" to export project data to csv a second time.

## Context

I am trying to export slices of my project data from Gephi to work on them outside of the project and later reimport them.

## Your Environment

* Version used: Gephi 0.9.2 201709242018
* Java version: 1.8.0_144
* Operating System: Mac OS X Version 10.14.6

[messages.log](https://github.com/gephi/gephi/files/3581779/messages.log)

**Comment by UTH-Tuan** [comment]
I am having the same issue.

**Comment by eduramiba** [comment]
Thank you both for your report. Adding to 0.9.3

**Comment by UTH-Tuan** [comment]
It appears the issue might be due to an outdated look and feel library (com.sun.java.swing.plaf.window). Since Java 9 or 10 that library import has been deprecated.  I am able to export when I change the look and feel appearance from the native to metal or nimbus.

**Comment by wonheecho** [comment]
> It appears the issue might be due to an outdated look and feel library (com.sun.java.swing.plaf.window). Since Java 9 or 10 that library import has been deprecated. I am able to export when I change the look and feel appearance from the native to metal or nimbus.

Thanks for this comment, I also found this thread when I ran into a similar issue. Can you elaborate on how to change the "look and feel?" I'm relatively new, so I can't fully comprehend what you mean by changing the UI / outdated library.

**Comment by mbastian** [comment]
Hi, I was not able to reproduce this issue. Would you mind trying again with the latest nightly build?
[gephi-0.9.3-SNAPSHOT-windows.exe](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=windows&p=exe) (Windows)

[gephi-0.9.3-SNAPSHOT-macos.dmg](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=macos&p=dmg) (Mac OS X)

[gephi-0.9.3-SNAPSHOT-linux.tar.gz](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.3-SNAPSHOT&c=linux&p=tar.gz) (Linux)

In any event, in the upcoming 0.9.3 release we integrated the FlatLaf look-and-feel by default so if that was the cause of the issue it should work now
