### ISSUE TITLE
Gephi 0.9.x cannot be started on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by ooof** [gephi/gephi#2138]
I reinstalled the system and configured it as follows:

 

- Ubuntu 18.04.3 LTS ,  Kernel 5.0.0-27-generic

- Graphics Card：NVIDIA(R) GeForce(R) 930M

- java -version

```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

- Gephi 0.9.2  

I tried using the built-in graphics card (Intel Corporation Skylake GT2 [HD Graphics 520]), tried the Nvidia(R) GeForce(R) 930M nvidia-driver-430 and nvidia-driver-390 drivers, and tried the Nouveau display. Driver.

Also used a higher version of Java.

Also used Gephi 0.9.1.

But Gephi can't always start. After executing ./gephi, wait a while and return to the command line.

I don't know if anyone has successfully run Gephi 0.9.x on Ubuntu 18.04.3 LTS.

I hope someone has solved this problem, thank you.

**Comment by ooof** [comment]
I don't know why, I can use it later.
Now my kernel version is: 5.0.0-29-generic
java -version
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
Please cancel this question.

**Comment by wetneb** [comment]
Closing as requested.
