### ISSUE TITLE
Node betweenness is negative for big graphs when normalized

### ISSUE THREAD

**Issue by wackyworm** [gephi/gephi#2139]
For big graphs, more than 50K nodes, the betweenness value is negative and incorrect when normalized because of integer overflow in this line:

https://github.com/gephi/gephi/blob/56b8733f03a3aaaa4bcc3ca63744c803f9d7a4c3/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/GraphDistance.java#L365

(n - 1) * (n - 2) is bigger than integer max value for n > 50K, producing negative numbers

**Comment by eduramiba** [comment]
Thanks for your report, adding to 0.9.3 milestone
