### ISSUE TITLE
Wrong wiki for Closeness centrality?

### ISSUE THREAD

**Issue by lorpac** [gephi/gephi#2151]
Hello,
I suspect that the wiki for the [closeness centrality](https://github.com/gephi/gephi/wiki/Closeness-Centrality) is wrong: it says that the closeness centrality is calculated as "The average distance from a given node to all other nodes in the network.", while in the reported [wikipedia page](https://en.wikipedia.org/wiki/Closeness_centrality) it is defined as the inverse of that. The definition in Wikipedia is, to my knowledge, also the accepted one by the community, even though incoherences are occasionally found. A quick look to the surce code (org.gephi.statistics.plugin.GraphDistance.java) makes me think that Wikipedia's definition is actually implemented in Gephi. Could you please confirm?

**Comment by jacomyma** [comment]
The wiki is indeed wrong, I confirm that the Wikipedia definition is used. The normalized version is used (N/Sum).
The sum of distances is done here: https://github.com/gephi/gephi/blob/master/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/GraphDistance.java#L260
... and the inversion there:
https://github.com/gephi/gephi/blob/master/modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/GraphDistance.java#L270
Wiki edited, thanks!
