### ISSUE TITLE
Java not installed error

### ISSUE THREAD

**Issue by Physalis87** [gephi/gephi#2160]
## Expected Behavior
I have installed Java 10 and expect to start Gephi.
## Current Behavior
Gephi starts with the the error message "Cannot find Java 1.8 or higher
[Screenshot](https://ibb.co/wYKcpHy)
## Steps to Reproduce

1. Open Gephi after installation
2. 
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 10.0.2 (64-Bit)
* Operating System: Windows 10

**Comment by eduramiba** [comment]
At the moment Gephi can only work with Java 8 exactly.

**Comment by Physalis87** [comment]
Installing Java 8 fixed the problem. Thank you!

**Comment by joshpowlison** [comment]
This should be a null issue. [0.9.0 started including the Java environment](https://github.com/gephi/gephi/issues/748#issuecomment-164172828) so separate installation wasn't necessary; 0.9.1 works fine as well without pre-installing Java. The issue started in 0.9.2.

Also, this error is now listed in a few separate different reports; we need to merge these or remove some.

Error #2160 
Error #2169

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) embed Java (JRE11) on Linux/Windows/MacOS so no need anymore to install Java separately. This should solve most Java compatibility issues.
