### ISSUE TITLE
Preview / Export hides node labels under nodes

### ISSUE THREAD

**Issue by Marmeladenbrot** [gephi/gephi#2165]
#Expected Behavior
Labels are over the nodes

## Current Behavior
Labels are under the nodes. Preview windows and PNG export cover the node labels so a part of the label is hidden.
Also when exporting to PDF or SVG the nodes disappear, showing only the edges and labels.

Example PNG: https://uni-duisburg-essen.sciebo.de/s/soGRbUg5C7CSDM6
Example PDF: https://uni-duisburg-essen.sciebo.de/s/dMc383YBCxtLCow

I use the Polygon plugin to change the node shape.

## Steps to Reproduce

1. Gephi file: https://uni-duisburg-essen.sciebo.de/s/cRUqbKMQxlV5dYs
2. Go to Preview window
3. View Preview, nodes cover labels
4. Export to PNG (nodes cover labels), export to PDF/SVG (nodes disappear)

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_241 64bit
* Operating System: Windows 10 Pro 64bit

**Comment by eduramiba** [comment]
Hi,
I think this happens due to the custom shapes nodes plugin.
Please make sure in preview that the order of renderers (in manage renderers tab) is correct, so labels end up over nodes.

**Comment by Marmeladenbrot** [comment]
Order of renderes was the problem, thanks a lot for your help.

**Comment by eduramiba** [comment]
Great!
