### ISSUE TITLE
permanent Black screen in graph window of gephi 

### ISSUE THREAD

**Issue by hardat** [gephi/gephi#2175]
I am unable to change the background of gephi's graph window, which is black. Moreover, the network starts shaking and leaves trails when I zoom in or out.
<img width="904" alt="gephi" src="https://user-images.githubusercontent.com/10692974/75821199-d4e4ed00-5dc3-11ea-9040-38b08b66f7b2.PNG">

**Comment by eduramiba** [comment]
Duplicate of #2126
