### ISSUE TITLE
CSV Edges file not importing because Gephi does not detect Source and Target columns

### ISSUE THREAD

**Issue by helenacaecilia** [gephi/gephi#2178]
## Expected Behavior
I expect to see the data from the edges spreadsheet (source;target;type) in the Edges tab of the Data Laboratory in Gephi after importing this through the "Import Spreadsheet" function.

## Current Behavior
Hi all! 

I am trying to make a network visualization in Gephi for my master’s thesis, but my Edges files won’t import. The Nodes file works fine, but the Edges file won’t import because Gephi does not detect the Source and Target. The csv file contains different columns (Source, Target, Type and Weight), and the source and target columns have ids of the nodes. I tried the same thing using a csv file with just the source and target columns. Either way, Gephi tells me that "Edges Table needs a Source and Target column with node ids,” while I do have columns with those exact names. 

Is there anyone who could help me out? I would be so grateful!   

## Possible Solution
I heard that spaces can cause issues, but I cannot detect any in my Edges file. 

## Your Environment

* Version used: Gephi 0.9.2
![Gephi](https://user-images.githubusercontent.com/62215393/76707577-9539d180-66f0-11ea-8194-de7c1396c137.jpeg)

**Comment by eduramiba** [comment]
Hi,
Please make sure there are no leading spaces or tabs before the Source or Target column names, they should be trimmed.

**Comment by Sim-Xuesi** [comment]
Hi, I faced this problem as well. This resource has helped me greatly: http://forum-gephi.org/viewtopic.php?t=2763

I used Notepad++ to change the encoding to UTF 8 and imported the files again
![image](https://user-images.githubusercontent.com/43160618/76990871-9d5d6f80-6983-11ea-814f-0efcca720aeb.png)
