### ISSUE TITLE
Include JRE in Windows/Linux release

### ISSUE THREAD

**Issue by tushev** [gephi/gephi#2183]
Hi everyone,

_'Cannot find Java 1.8 or higher' is nearly a household word here._
To deal with the bug, (on windows) I just modify gephi shortcut to use %JAVA_HOME% environment variable like (pay attention to the trailing slash):
`"C:\Program Files\Gephi-0.9.2\bin\gephi64.exe" --jdkhome "%JAVA_HOME%\"`

**But really, do we really need to do stuff like this in 2020?**

### What I suggest is:

- Either to check JAVA_HOME environment variable automatically
- Or allow to use ${JAVA_HOME} in gephi.conf (and ship this value for default)
- or - best of all - **ship free JRE with gephi**

I confirm that gephi successfully runs with AdoptOpenJDK release of JRE 8:
![image](https://user-images.githubusercontent.com/18406797/80570273-ee956000-8a13-11ea-8388-8ff2b3173b8f.png)
AdoptOpenJDK is a project that provides binaries of OpenJDK.
They release free versions of JRE here: [https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/) and here: [https://adoptopenjdk.net/releases.html](https://adoptopenjdk.net/releases.html)
![image](https://user-images.githubusercontent.com/18406797/80570779-d40fb680-8a14-11ea-9117-dad3d21da67c.png)

Many apps that use Java come bundled with JRE like Matlab, or IntelliJ IDEA etc...
Why not make a separate windows build for gephi that has built-in JRE with it?

### It is extremely important because support of Java 8 SE ends for personal use ends in December 2020 
Correct me if I'm wrong, but after that date end-users won't be able to install Java (or they will have to install unsupported version with potential security vulnerabilities). Commercial users already have to pay for Java JRE. 

By bundling free OpenJDK's JRE with Gephi, we can greatly improve user experience, provide them with all the necessary stuff (handy, if user has Java 11, and Gephi requires JRE 8), as well as we can help people to avoid potential licensing issues (if Gephi is used in commercial environment) .

**Comment by osh4** [comment]
I would love that

**Comment by eduramiba** [comment]
Yes, this is what we want to end up doing. We already did it for Mac OS

**Comment by AndreaRe9** [comment]
Hi everyone,
Since I have encountered this bug trying to install the last version of Gephi for Windows (0.9.2), would you @eduramiba mind if I try to solve the problem, using @tushev suggestions?

**Comment by wetneb** [comment]
Closing as a duplicate of #2336, which was implemented yesterday.
