### ISSUE TITLE
Hyperedge/Hypergraph support

### ISSUE THREAD

**Issue by s5bug** [gephi/gephi#2187]
Right now, only unary edges are supported. I love the look of the edges in the "Directed Sourced Hypergraphs" of [this paper](https://arxiv.org/pdf/1804.09408.pdf) and have wanted to generate my own graphs to SVGs that look like that and haven't found any tool that can do so.

**Comment by mohawk2** [comment]
There is a proposal (and work in progress) to make Graphviz support directed hypergraphs, albeit looking a bit different: https://gitlab.com/graphviz/graphviz/-/issues/1911

**Comment by mbastian** [comment]
You're right we don't support hypergraphs. We also don't plan to anytime soon so I think we should close this issue. The graphviz discussion is quite informative, thank you @mohawk2 for that. While there is certainly some use-cases for hypergraphs, it doesn't seem large enough to motivate seriously looking into that given the complexity involved. We're talking about the core graph structure, which has implications throughout the entire software stack. We don't even properly support multigraphs yet in the visualisation, which are much more common.
