### ISSUE TITLE
Arrow in only one direction for a mutual edge between two nodes?

### ISSUE THREAD

**Issue by davidr-cpu** [gephi/gephi#2188]
I imported a csv-file as a matrix and selected the graph-type as directed. All of my nodes are connected in both directions(between 0.8 and 0.01). Thus, all my edges have arrows in both directions. Is there a way to display only one arrow for a mutual edge between two nodes? For example, If node As weight on B is 0.3, and node Bs weight on A is 0.6, I want the arrow to point in the direction of A, since the net effect is going in the direction from B to A. Thank You very much!

**Comment by eduramiba** [comment]
Hi David,
Sorry, this is not supported by Gephi.

**Comment by eduramiba** [comment]
But you could probably easily pre-process your file to calculate the desired results and load them in Gephi.
For example export edges table to CSV and work with that file.

**Comment by davidr-cpu** [comment]
Thank you for your comment. I tried to pre-process my file in excel, but when I import a file with just the "net effect" between e.g. node A and B, my graph looks very different, because then the locations of the nodes also just depend on the net effect between the two nodes rather then the total weight between the nodes. (Example: The net effect is the same in both cases: 1.) Node As weight on B is 0.3 and Bs weight on A is 0.6 compared 2.) As weight on B is 0.1 and Bs weight on A is 0.4) I can't think of any other way to capture both effects in my graph.
