### ISSUE TITLE
Gephi's Data viewing screen is completely black and doesn't seem to be working?

### ISSUE THREAD

**Issue by verakee** [gephi/gephi#2196]
## Expected Behavior
A white screen with data visualization 
## Current Behavior
A black screen with no visualization 
## Possible Solution
Tried changing the background color, it's not working so it's definitely something else

## Context

use  Twitter Streaming Importer to visualize data, but data screen is not working

![image](https://user-images.githubusercontent.com/61382273/84534264-9ced2000-acb7-11ea-93ef-4643556ccb0e.png)

## Environment

* Version used: Gephi 0.9.2
* Java version: version 8
* Operating System: Windows 10

**Comment by RodrigoSilvaC** [comment]
Were you able to fix it? I am experiencing the same problem

**Comment by eduramiba** [comment]
Sorry, not yet but please read https://github.com/gephi/gephi/issues/2126

**Comment by mayankachandrashekar** [comment]
Check this response. This works.
https://github.com/gephi/gephi/issues/2126#issuecomment-596110591
