### ISSUE TITLE
How to make the label to the top? 

### ISSUE THREAD

**Issue by LiZhihua1982** [gephi/gephi#2201]
## Expected Behavior
How to make the label to the top? 
## Current Behavior
![image](https://user-images.githubusercontent.com/38903973/87121741-72928080-c2be-11ea-9f98-40385389e47d.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8
* Operating System: window 10

**Comment by eduramiba** [comment]
Labels on top is the default. Make sure renderers in the manage renderers are in the correct order.

**Comment by eduramiba** [comment]
Did it work?

**Comment by wetneb** [comment]
Given that there has not been any response for more than a year, I am closing this.
