### ISSUE TITLE
ForceAtlas2 double repulsion forces in some nodes

### ISSUE THREAD

**Issue by wackyworm** [gephi/gephi#2202]
This code should not be executed when Barnes-Hut is enabled because every node is calculated independently against the regions, it produces that some nodes receive double repulsion forces. It is OK when Barnes-Hut is NOT enabled since not all the pairs of nodes are computed for optimization.

https://github.com/gephi/gephi/blob/5ca963aae3d15cd7685f69c1d54ee1d9b2aa7746/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/ForceFactory.java#L145-L146

It should be fixed in all the repulsion classes defined in ForceFactory

**Comment by jacomyma** [comment]
After investigation, Wackyworm is wrong. But that's far from obvious!

In the case of node-region repulsion, each node looks against each region. So each node pairs is repulsed from the standpoint of each node differently. https://github.com/gephi/gephi/blob/5ca963aae3d15cd7685f69c1d54ee1d9b2aa7746/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/NodesThread.java#L81-L84

In the case of node-node repulsion, it's done both at once, hence the discrepancy observed by Wackyworm. Note in the line below that the index of node 2 is always below node 1, so the pair is only checked once:
https://github.com/gephi/gephi/blob/5ca963aae3d15cd7685f69c1d54ee1d9b2aa7746/modules/LayoutPlugin/src/main/java/org/gephi/layout/plugin/forceAtlas2/NodesThread.java#L88

By the way, I actually tried without those lines, and they indeed a discrepancy between with and without the BarnesHut. There is always a little difference, but it's clear that those lines are necessary. Example:

With the lines, BarnesHut enabled:
![image](https://user-images.githubusercontent.com/158525/156223682-c0786dcb-0b7c-4117-976d-3b652025194f.png)

With the lines, BarnesHut disabled:
![image](https://user-images.githubusercontent.com/158525/156223721-cbc8cc66-3294-4a91-9010-acafc772796b.png)

Without the lines, BarnesHut enabled:
![image](https://user-images.githubusercontent.com/158525/156223776-13bfa460-764e-4d66-8d53-cd75cef74387.png)

Without the lines, BarnesHut disabled:
![image](https://user-images.githubusercontent.com/158525/156223821-0fe50c5c-0139-4677-bbe5-35b08347d95c.png)
