### ISSUE TITLE
Broken dataset link - Class of 1880/81

### ISSUE THREAD

**Issue by LakeYin** [gephi/gephi#2215]
When I try to click the link at https://github.com/gephi/gephi/wiki/Datasets corresponding to the Class of 1880/81 dataset, I get "Not Found The requested URL was not found on this server." as a response. 

I realize that this issue was raised before at https://github.com/gephi/gephi/issues/1913 but two years have passed since then.

**Comment by wetneb** [comment]
This link now works for me.
