### ISSUE TITLE
Mac gephi quit unexpectedly

### ISSUE THREAD

**Issue by Canhui-Chen** [gephi/gephi#2217]
Just cannot open Gephi. Maybe about Java? Or maybe my beta version MacOs? I don't know, totally have no idea. It reported that Gephi quit unexpectedly and let me reopen it. I tried so many times but it didn't work. 
Could anyone tell me why?
Below is a part of report.

## Context

Process:               java [1075]
Path:                  /Applications/Gephi.app/Contents/PlugIns/jre1.8.0_144.jre/Contents/Home/bin/java
Identifier:            net.java.openjdk.cmd
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [606]
Responsible:           java [1075]
User ID:               501

Date/Time:             2020-10-17 10:19:51.135 +0800
OS Version:            macOS 11.0 (20A5395g)
Report Version:        12
Bridge OS Version:     5.0 (18P50402b)
Anonymous UUID:        C5411ADA-13B7-ED37-D9F6-AD0847220AD4

Time Awake Since Boot: 47 seconds

System Integrity Protection: enabled

Crashed Thread:        32  Java: main

Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
-[NSOpenGLContext setView:] must be called from the main thread.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.0_261
* Operating System: MacOS 11.0 Beta (20A5395g)

**Comment by easilydone** [comment]
I'm getting exactly the same error on exactly the same beta version of macOS; feels it's probably an incompatibility going on, how to fix it is the question I guess. I've reported it to Apple as it feels like a wider Java issue but it's beyond me.

**Comment by jeremyreffin** [comment]
See issue #2222 for solution

**Comment by 7homasSutter** [comment]
Same problem here. The solution of #2222 does not work for me but it seems to be a Java related problem because the java control panel won't start neither.

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) may have fixed this issue. Please try it and re-open this issue if it still doesn't work. Thank you!
