### ISSUE TITLE
Rendering graphs does not work when Nimbus Look-and-feel is set

### ISSUE THREAD

**Issue by kubajal** [gephi/gephi#2237]
## Expected Behavior

A graph should be rendered in the _Preview_ tab.

## Current Behavior

A graph is not rendered in the _Preview_ tab.

## Steps to Reproduce

1. set Look and Feel to _Nimbus_ in **Tools** > **Options** > **Appearance** > **Preffered look and feel: Nimbus** 
2. restart Gephi
3. load a graph (_Nodes Table_ from a CSV file and _Edges Table_ from another CSV file.   

## Context

I am trying to set a darker theme. The default Windows-style look and feel is white and too bright for me. _Nimbus_ look and feel seems to be the darkest one out of all available interface themes. Unfortunately, when I set it, graph drawing does not work for me.

## Your Environment

* Version used: Gephi 0.9.2 201709241107
* Java version: 1.8.0_281; Java HotSpot(TM) 64-Bit Server VM 25.281-b09 (**runtime**: Java(TM) SE Runtime Environment 1.8.0_281-b09)
* Operating System: Windows 10 version 10.0 running on amd64; Cp1250; en_US (gephi)

**Attachment: [messages.log](https://github.com/gephi/gephi/files/5905558/messages.log)**

**Comment by mbastian** [comment]
Thanks for the report, in the upcoming 0.9.3 release we'll provide the [FlatLaf](https://www.formdev.com/flatlaf/) look and feel by default on all platforms. It has both a light and dark version, which hopefully would work out fine for you.
