### ISSUE TITLE
trying to install gephi on fedora 33

### ISSUE THREAD

**Issue by hadiobeid** [gephi/gephi#2242]
## Expected Behavior
downloaded the zip file from the website and extracted it then ran ./bin/gephi in the terminal as requisted. the this error showed up:
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/.../gephi-0.9.2/platform/lib/boot.jar) to field java.net.URL.handler

WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release

Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion 

after trying the solution here: https://github.com/gephi/gephi/issues/2087 

i tried to ran ./bin/gephi again and this error appeared:
 Cannot find java. Please use the --jdkhome switch.
same error when i ran 
"/bin/gephi --jdkhome $JAVA_HOME switch"
"/bin/gephi --jdkhome $JAVA_HOME"
"/bin/gephi  $JAVA_HOME"
## Steps to Reproduce

1.
2.
3.
4.

## Context
im trying to install it for a university course so it will be really helpful if it was solved fast.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: java 8
* Operating System:  fedora 33

**Comment by lehkost** [comment]
A multi-step solution to this known problem is provided [**here**](https://linuxanteportas.wordpress.com/2020/12/25/running-gephi-on-fedora-33/). Hope this is helpful…

**Comment by mbastian** [comment]
Closing as this should be fixed in the 0.9.3 release. We do package the proper JRE in the Linux package as well now.
