### ISSUE TITLE
Labels not showing in preview

### ISSUE THREAD

**Issue by Joost1105** [gephi/gephi#2256]
Hi,

I have an issue with showing labels on my preview and print, they are not showing. I've been working simultaneously on another file that is almost exactly the same: same input, same settings and options where I don't have this problem so I don't see what I am doing wrong
![image](https://user-images.githubusercontent.com/81633335/113002974-9494a180-9172-11eb-9510-e946b2864ee0.png)
![image](https://user-images.githubusercontent.com/81633335/113003037-a37b5400-9172-11eb-9c58-bf80c6ad1fb5.png)

What am I doing wrong?
Best,
Joost

* Version used: Gephi 0.9.2
* Java version: 
* Operating System: Windows 10

**Comment by eduramiba** [comment]
Please check in data laboratory that the label column contains data.
Also in preview (manage renderers tab) make sure the labels are over the nodes.

**Comment by Joost1105** [comment]
Thanks for your reply, I did both already.

![image](https://user-images.githubusercontent.com/81633335/113004619-08837980-9174-11eb-8a3b-1d05e0ebc9e4.png)
![image](https://user-images.githubusercontent.com/81633335/113004701-16d19580-9174-11eb-807f-62e2055d3297.png)

**Comment by eduramiba** [comment]
Not sure what can be the problem. Does changing the font to different one help? Also try with different color instead of original.

**Comment by Joost1105** [comment]
Changing the font did the trick, when changing it back to what I first had it also showed up this time, thanks for your help!

**Comment by lsukharn** [comment]
I have the same problem. Gephi 0.10. Changing fond and font color did not help - I still cannot see the labels. (I checked, I have labels and they are on top of everything)

**Comment by lsukharn** [comment]
I just reloaded the *.graphml file and ran stats/other things to modify the graph again. Now I see the labels. So, maybe something went wrong with the first set up. It might be a bug inside Gephi though, because I ran a routine transformation pipeline that usually works well.
