### ISSUE TITLE
gephi does not build: broken netbeans artifactory url

### ISSUE THREAD

**Issue by csabahruska** [gephi/gephi#2261]
Problem: Gephi does not build on a (java) clean machine.
used command: `(jdkhome="/home/csaba/java/jdk8u282-b08" mvn -e clean install)`
broken link:  https://bits.netbeans.org/nexus/content/groups/netbeans/
```
Repository decommissioned. Please refer to https://netbeans.apache.org/about/oracle-transition.html for more information.
```
see: https://netbeans.apache.org/about/oracle-transition.html

## Your Environment

* Version used: Gephi 0.9.2
* Java version: jdk8u282-b08
* Operating System: Ubuntu 16.04

**Comment by mbastian** [comment]
This is now fixed. We removed that repository as all the necessary artifacts are now on Maven Central. Thanks!
