### ISSUE TITLE
White screen on boot

### ISSUE THREAD

**Issue by cvanelteren** [gephi/gephi#2268]
## Expected Behavior
- Running `gephi --jdkhome "/usr/lib/jvm/java-8-openjdk" `
- Boot up the interface
## Current Behavior
Shows white scre
![20210430_11h37m03s_grim](https://user-images.githubusercontent.com/19485143/116677800-e9f9e380-a9a8-11eb-891b-1964891156a8.png)
en

## Possible Solution
None?

## Steps to Reproduce

1. `yay install gephi`
2. `Running `gephi --jdkhome "/usr/lib/jvm/java-8-openjdk" `

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:  `Linux g14 5.11.16-arch1-1-g14 #1 SMP PREEMPT Thu, 29 Apr 2021 13:43:37 +0000 x86_64 GNU/Linux`

**Comment by somed00d** [comment]
Any ideas on this? Experiencing the same thing on: `Linux XXX 5.16.9-arch1-1 #1 SMP PREEMPT Fri, 11 Feb 2022 22:42:06 +0000 x86_64 GNU/Linux
`

I could have swore I had it working out-of-the-box around early last year. From what I've seen from other posts, it might be related to the GPU, drivers and OpenGL setup. I was using an Nvidia card last year. Now am on Intel integrated.

```bash
> glxinfo | grep OpenGL                                                                             
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 21.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 21.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

Anywhere this would be logged? Nothing popping up in `~/.gephi`

**Comment by Lxtharia** [comment]
Hi, i had the same problem on sway. Try running it with this enviromental variable:
```bash
export _JAVA_AWT_WM_NONREPARENTING=1 gephi
```
or set it in your .bashrc

https://github.com/swaywm/sway/wiki#issues-with-java-applications

**Comment by Henriquelay** [comment]
Thank you so much @Lxtharia !!! That did it for me. I'm also using Sway.

**Comment by cvanelteren** [comment]
For me this problem went away automatically after a bunch of system updates.

**Comment by Exagone313** [comment]
I can still reproduce this on Arch Linux with gephi package 0.10.1-2.

Setting `_JAVA_AWT_WM_NONREPARENTING=1` solved it.

**Comment by kockahonza** [comment]
Can confirm this very much still happens on Arch with any of the following: the gephi package, the gephi-git package or the downloaded binaries from the gephi website. It would be great if this was at least pinned somewhere (or not closed) as it took me ages to find.
