### ISSUE TITLE
OpenOrd layout algorithm not working on Gephi toolkit

### ISSUE THREAD

**Issue by axololtl1997** [gephi/gephi#2283]
I have been trying to use the Gephi toolkit to automatically layout gexf graphs according to the OpenOrd Algorithm. However, it seems to start running, and then gets stuck after a few seconds. This doesn't occur for other layout algorithms, such as Yifan Hu or Fruchterman-Reingold.

## Expected Behavior
The code runs as normally, completing the AutoLayout Execution, and going on to the next step.

## Current Behavior
The execution gets stuck after a few seconds.
On some preliminary anlysis with jstack, one can see that the main thread is put on wait indefinitely with the message:
main" #1 prio=5 os_prio=0 cpu=750.00ms elapsed=13.88s tid=0x0000015e07f37000 nid=0x2fe4 in Object.wait()  [0x00000036d17fe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.11/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@11.0.11/Object.java:328)
        at org.gephi.layout.plugin.openord.Combine.waitForIteration(Combine.java:172)
        - waiting to re-lock in wait() <0x0000000086e283a8> (a java.lang.Object)
        at org.gephi.layout.plugin.openord.OpenOrdLayout.goAlgo(OpenOrdLayout.java:264)
        at org.gephi.layout.plugin.AutoLayout.execute(AutoLayout.java:126)
        at org.gephi.toolkit.demos.WithAutoLayout.script(WithAutoLayout.java:106)
        at org.gephi.toolkit.demos.Main.main(Main.java:28)

 

## Possible Solution
This implies that the error has something to do with this section of the code in OpenOrdLayout.java 

public void goAlgo() {        if (firstIteration) {            for (int i = 0; i &lt; numThreads; ++i) {                Thread t = new Thread(workers[i]);                t.setDaemon(true);                t.start();            }            firstIteration = false;        }        
combine.waitForIteration();    }

So, after the first iteration, there is some problem in the  combine.waitForIteration() line.

## Steps to Reproduce

1. Include an OpenOrdLayout object in the code 
2.Call an AutoLayout on the above object
3.Execute the script

## Context

I am trying to take an already existing gexf file, and automatically run it through the toolkit to get a gexf file with coordinates obtained from the OpenOrd layout, instead of doing it manually

## Your Environment

* Version used: Gephi 0.9.2
* Java version:  openjdk version "11.0.11" 2021-04-20
* Operating System: Win10

**Comment by jbliesener** [comment]
Works here.

This is the code I'm using:

```java
                OpenOrdLayout openOrd = new OpenOrdLayout(null);
                openOrd.resetPropertiesValues();
                openOrd.setRandSeed(1L);
                if (numThreads != -1) {
                    openOrd.setNumThreads(numThreads);
                }
                openOrd.setNumIterations(LAYOUT_ITERATIONS);
                openOrd.setGraphModel(graphModel);
                openOrd.initAlgo();
                for (int i = 0;
                        i < LAYOUT_ITERATIONS
                        && openOrd.canAlgo();
                        i++) {
                    openOrd.goAlgo();

                    if (cancel) {
                        openOrd.endAlgo();
                        return;
                    }
                }

                openOrd.endAlgo();

                log.fine("OpenOrd layout completed, waiting 1 second before starting Noverlap");

                // HACK: Wait for OpenOrd workers to terminate
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    // ignore
                }
```

**Comment by axololtl1997** [comment]
Hello!
I have tried working on your suggestions, but it hasn't been working for me, I'm afraid. I've appended my code below, could you tell me where the problem could be?
`public void script() {
        //Init a project - and therefore a workspace
        ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
        pc.newProject();
        Workspace workspace = pc.getCurrentWorkspace();

        //Generate a new random graph into a container
        ImportController importController = Lookup.getDefault().lookup(ImportController.class);
        Container container;
        try {
            //File file = new File(getClass().getResource("/lesmiserables.gml").toURI());
            InputStream stream = this.getClass().getClassLoader().getResourceAsStream("lesmiserables.gml");
            File file = new File("a.gml ");
            FileUtils.copyInputStreamToFile(stream, file);
            container = importController.importFile(file);
            container.getLoader().setEdgeDefault(EdgeDirectionDefault.DIRECTED);   //Force DIRECTED
            container.getLoader().setAllowAutoNode(false);  //Don't create missing nodes
        } catch (Exception ex) {
            ex.printStackTrace();
            return;
        }

        //Append container to graph structure
        importController.process(container, new DefaultProcessor(), workspace);

        //See if graph is well imported
        GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel();
        DirectedGraph graph = graphModel.getDirectedGraph();
        System.out.println("Nodes: " + graph.getNodeCount());
        System.out.println("Edges: " + graph.getEdgeCount());

        //Layout for 1 minute
        OpenOrdLayout openOrd = new OpenOrdLayout(null);
        openOrd.resetPropertiesValues();
        openOrd.setRandSeed(1L);
        openOrd.setNumThreads(Runtime.getRuntime().availableProcessors()-1);
        openOrd.setNumIterations(1200);
        openOrd.setGraphModel(graphModel);
        openOrd.initAlgo();
        for (int i = 0; i < LAYOUT_ITERATIONS && openOrd.canAlgo(); i++) {
            openOrd.goAlgo();
            if (cancel) {
                openOrd.endAlgo();
                 return;
            }
        }
        openOrd.endAlgo();
        log.fine("OpenOrd layout completed, waiting 1 second before starting Noverlap");
        // HACK: Wait for OpenOrd workers to terminate
        try {
           Thread.sleep(1000);
        } catch (InterruptedException e) {
             // ignore
        }

        //Export
        ExportController ec = Lookup.getDefault().lookup(ExportController.class);
        try {
            ec.exportFile(new File("resulting.gexf"));
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        System.exit(0);
    }`

This is the output that I get:
`Jun 18, 2021 7:17:46 PM org.netbeans.modules.masterfs.watcher.Watcher getNotifierForPlatform
INFO: Native file watcher is disabled
Jun 18, 2021 7:17:46 PM org.gephi.io.processor.plugin.DefaultProcessor process
INFO: # Nodes loaded: 77
Jun 18, 2021 7:17:46 PM org.gephi.io.processor.plugin.DefaultProcessor process
INFO: # Edges loaded: 254
Nodes: 77
Edges: 254
Jun 18, 2021 7:17:46 PM org.gephi.layout.plugin.openord.Control initParams
INFO: Real iterations 150
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Entering liquid stage...
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Liquid stage completed in 0 seconds, total energy = 2758.088867
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Entering expansion stage...
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Expansion stage completed in 0 seconds, total energy = 899.182678
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Entering cool-down stage...
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Cool-down stage completed in 0 seconds, total energy = 487.864899
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Entering crunch stage...
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Crunch stage completed in 0 seconds, total energy = 245.098480
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Entering simmer stage...
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Simmer stage completed in 0 seconds, total energy = 0.020148
Jun 18, 2021 7:17:47 PM org.gephi.layout.plugin.openord.Control udpateStage
INFO: Layout completed in 0 seconds with 752 iterations
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openide.util.RequestProcessor$TopLevelThreadGroup (file:/C:/Users/munch/toolkit/target/pack/lib/gephi-toolkit-0.9.2-all.jar) to method sun.awt.AppContext.getAppContext()
WARNING: Please consider reporting this to the maintainers of org.openide.util.RequestProcessor$TopLevelThreadGroup
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

Also, how would I get it to work with AutoLayout()? Also, is it working for you on Gephi Toolkit 0.9.2?
Thanks, A.K.

**Comment by jbliesener** [comment]
Sorry, I can't run your code here at this moment. But from the log file it looks as if it's running - actually very quickly: The total energy does change and it all happens in less than a second. 

The total number of iterations is less than the 1200 you specified.

Maybe you can upgrade the log.fine to a log.info, so that you will be able to see if the layout actually terminated successfully. Maybe your problem isn't with the layout, but with the subsequential export

**Comment by axololtl1997** [comment]
Hello! So I did as you said,  and then, what I did was transfer the code from an auxilliary class to the main class itself, and that somehow fixed the problem?
So the code you mentioned did work, with some caveats:
1) The autolayout still does not work even in this case with openord.
2) How would you determine the number of iterations needed for say, a graph with 30k nodes and 200k edges, roughly? Or as you mentioned, is 1200 iterations a good enough upper bound?
Thank you very much, A.K.

**Comment by jbliesener** [comment]
No idea about AutoLayout, never used it.

I think there's no general rule of thumb on how many interations you specify. I never tried and it worked fine with the 1200 I'm using.

Sorry for not being able to provide any additional information, I don't have a runtime environment here that would allow me to reproduce the situation. I was just copying blocks of code from my GitLab repository.

**Comment by axololtl1997** [comment]
Yeah, no problem. Thanks for the help!
