### ISSUE TITLE
Define fixed code style

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2337]
Code styling should be defined and enforced so we're all on the same code style. I don't have a specific preference for a style but we should make sure this isn't an issue for new contributors submitting PRs

### Definition of done
* Codestyle is defined for the entire repository independent of IDEs
* At least Netbeans and IntelliJ should be able to easily work with the code style (ideally fully automated)

**Comment by wetneb** [comment]
I would love to do the same for OpenRefine, so I am interested in learning what tools are available for this in the Java ecosystem. Are you considering enforcing this in the CI?

**Comment by mbastian** [comment]
Ok, I'm done with this task. In summary:

1. Created `checkstyle.xml` and `checkstyle-suppressions.xml` at the root of the repository
2. Configure the `pom.xml` to use the Maven CheckStyle plugin and configure it to fail the build in case of errors.
3. Reformatted and cleanup the entire code base except the Visualization and Tools modules (WIP in another branch that we don't want to break).
4. Wrote basic [documentation](https://github.com/gephi/gephi/wiki/Code-Style) how to configure IDE (IntelliJ only for now)

So going forward, the build should **fail** in case of formatting errors.

The actual code style is a modified version of the default Google code style (the usual convention checkstyle recommend) but slighly adapted to Gephi so it better matches what we had so far. Check the `checkstyle.xml` file for detailes.

Also note that not many violations are throwing **errors** at the moment. Most violations are **warnings** and cleaning that up would require some additional effort. Only errors would fail the build.  We can easily tweak that in the `checkstyle.xml` file.
