### ISSUE TITLE
Migrate from Transifex to Weblate

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2339]
We would like to move From Transifex to Weblate to facilitate localization.

### Definition of done
* We do one last import from Transifex using the ad-hoc scripts to make sure we captured any recent translations
* We have a Weblate project with automated push/pull mechanism setup
* Workflows are tested and validated
* Transifex scripts are removed
* Wiki is updated

### Links
* https://github.com/gephi/gephi/wiki/Localization
* https://www.transifex.com/gephi/gephi/dashboard/
* https://hosted.weblate.org/

**Comment by wetneb** [comment]
I would recommend using Weblate too actually! It is an amazing service which has a lot of advantages over Transifex:
* the translations come directly in your repository, no need to do the update yourself. You can configure it to either push directly to your master branch or to submit pull requests.
* as a consequence, commits which contribute translations are correctly attributed to your translators. That helps grow your number of contributors and correctly acknowledge the source of those translations.
* it's open source, so if for some reason the service goes away you could host Weblate yourself and keep the same workflow

**Comment by mbastian** [comment]
Update from progress:
- I've setup the project on Weblate: https://hosted.weblate.org/projects/gephi/
- I've requested the free access to them, following the guidelines. I'm waiting for their reply.

Let's not modify the Weblate project quite yet. Once approved, I'll do another round of testing and deprecate the Transifex.

**Comment by mbastian** [comment]
I had a look at the Transifex languages that are incomplete.
- Catalan (60%)
- Hebrew (12%)
- Italian (15%)
- Dutch (35%)
- Turkish (16%)
- Traditional Chinese (15%)

Without importing those languages to Weblate we would loose these translations, which isn't ideal. We should look into how to import those too.

**Comment by mbastian** [comment]
OK, all the existing translations for those languages were added in 199e72d6b3e73f5a5aafed97613b5a8795f217e6. 

We should no longer be editing the Transfifex as this was a one-off import.

**Comment by comradekingu** [comment]
@mbastian It is a good idea to freeze the Transifex project.
Also look through the comments to see if there are any bugs reported before removing it fully.

**Comment by mbastian** [comment]
@comradekingu I could not find how to lock/freeze the entire Transifex project... Any idea? Thanks!

**Comment by comradekingu** [comment]
@mbastian 

Click the project
Click on Resources.
Pick the resource
Click "Settings" from three vertical dots on the right
Uncheck "Your translators can translate resource strings" in the popup

**Comment by mbastian** [comment]
Done, migration to Weblate is complete: https://hosted.weblate.org/projects/gephi/

I tested the integration and all seems good.
