### ISSUE TITLE
Update crash reporter and make it GDPR compliant

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2340]
The Gephi crash reporter sends crashes to our [Sentry account](https://sentry.io/organizations/gephi/issues/?project=85815). This needs some maintenance as we should be using the sentry-java library and also make sures there are no PII in the report (like username).

### Definition of done
* Crash reporter uses the recommended Sentry library
* Crash reports are GDPR compliant

**Comment by wetneb** [comment]
I am having a go at the update (first bullet point).
