### ISSUE TITLE
Add a way to install Gephi on linux on the webpage

### ISSUE THREAD

**Issue by Yquetzal** [gephi/gephi#2358]
There are several issues with installing Gephi on linux. I have several classes with students where I ask them to install it, all of them are not computer scientists, and it's always complicated, I need to point to threads that explain how to do it by pointing to other threads...
Plus there are different problems such as not finding java 1.8 (I know, not start a thread about it...), AND another one where the visualisation  get stuck at "initialising", for which I'm not sure of the solution myself.

These problems have been here for several years.

I know a new version of Gephi is hoped for soon, but in the meantime, could it be possible to have a clear official page on how to solve those typical problems, to which I could point the students to ?

**Comment by wetneb** [comment]
In the next release, the Linux package will include a Java Runtime Environment, hopefully that will help.
If you want to propose changes to the website, feel free to submit a pull request to https://github.com/gephi/gephi.github.io
