### ISSUE TITLE
Preview function: Preview does not work

### ISSUE THREAD

**Issue by nana-marinbio** [gephi/gephi#2384]
### Discussed in https://github.com/gephi/gephi/discussions/2383

<div type='discussions-op-text'>

<sup>Originally posted by **nana-marinbio** December 15, 2021</sup>
Hi all,
I am using Gephi 0.9.2 with a Mac and just went through the tutorial. The preview option does not work, the window is totally gray. I set the zoom at 25% and lower but it didn't help.
How can I fix this? TKS!
![Captura de Tela 2021-12-15 às 15 36 56](https://user-images.githubusercontent.com/20118652/146245375-a33b72c7-eae2-4740-a96b-08c1a632a75d.png)
</div>

**Comment by mbastian** [comment]
Closing this issue. Let us know is this is still happening in the latest release. We've made some reliability improvements in this module since this was opened. Thank you
