### ISSUE TITLE
PDF export - Label can be outside of the builded document

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#239]
I use the preview window to create a pdf document.
On the preview window I see all nodes and all node labels.
But on my pdf document, the label at the extreme right is cutted.

---

Imported from Launchpad using lp2gh.
- date created: 2010-05-01T07:22:21Z
- owner: aurelienb
- the launchpad url was https://bugs.launchpad.net/bugs/572825

**Comment by cdgoodwin** [comment]
Has there been any progress on this fix? I'm encountering this same problem with the most recent version of Gephi. 

Additionally, I'm having trouble figuring out how exactly to change the margin sizes when exporting my SVG/PDF/PNG file for the workaround. (Doubtless it's somewhere obvious I'm missing)

Thanks!

**Comment by eduramiba** [comment]
Hi, you can find it in the save dialog options.

**Comment by cdgoodwin** [comment]
Thank you; I found the Options button in the export dialog box. :D
