### ISSUE TITLE
Didn't receive activating email

### ISSUE THREAD

**Issue by khatereKhanjankhani** [gephi/gephi#2404]
Dear Sir or Mam
I registered to gephi forum, but unfortunately I didn't receive the activating email. I also checked my spam too and leave a message to *count us* in gephi website.
I have some questions about gephi. Were can I ask my question?🤔
Thank you for your time and answer.

**Comment by seinecle** [comment]
Hi,
The Gephi forum is closed. You can use either the [discussion panel here on Github](https://github.com/gephi/gephi/discussions) or join the Facebook group: https://www.facebook.com/groups/gephi
