### ISSUE TITLE
Gephi crashing after activating Label text option

### ISSUE THREAD

**Issue by baldozafloja** [gephi/gephi#2409]
When i activate the option of viewing labels names, it automaticly closes Gephi.
Any help is welcome, thanks!

**Comment by seinecle** [comment]
Hi, 
Sorry to come back to you so late. Is your issue still happening? 
Can you please provide some information about your version of Gephi and your operating system?

**Comment by baldozafloja** [comment]
Hi,
Don't worry. I'm a sporadic gephi user, so i forgot the issue.
It happened that the 0.10 version was available, and worked a lot better
for me.
I've Ubuntu 20.04 and was using the previous version of gephi (don't
remember the number right now).
Thanks for the response and we are in touch,
Hug,
Daniel

**Comment by seinecle** [comment]
Ok super!
