### ISSUE TITLE
Windows said cannot find Java 1.8 or high

### ISSUE THREAD

**Issue by kitty2022v** [gephi/gephi#2413]
Do I need to download for Java 1.8?

**Comment by alelom** [comment]
You just need to install Java.

https://www.java.com/en/download/manual.jsp

Choose Windows Offline (64bit).

**Comment by Theklopez** [comment]
same issue, thanks for sharing that specific link and which one to choose. 

Java's automatic recommendation doesn't work, but the Windows Offline (64bit) works!!

**Comment by mbastian** [comment]
Hi, thanks for your report. The latest version of Gephi ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) embed Java on Windows as well so no need anymore to install Java separately.
