### ISSUE TITLE
Cannot apply appearance options only on filtered set of elements

### ISSUE THREAD

**Issue by zebra-ok** [gephi/gephi#2422]
## Expected Behavior
When I filter or select a subset of my nodes, I expect that the appearance options (size, color) only apply to the currently available/selected elements.
## Current Behavior
The appearance options applies to all nodes, even with active filter, or while having only a few nodes selected.
## Steps to Reproduce

1. Select / Filter some nodes
2. Apply appearance option (e.g. size or color)
3. Notice, that the appearance option was applied to ALL elements, not only the selected/filtered ones

## Context

I want to rank the size of my nodes, but want to do this in a more granular way. Therefore, I want to define a subset of nodes, for which the size should be a unique number, and another set of nodes, where the size depends on an attribute.

## Your Environment

* Version used: Gephi 0.9.2 Nightly with latest commit on 30.01.22
* Java version: openjdk 11.0.14
* Operating System: Fedora Linux 35

**Comment by mbastian** [comment]
Hi, I think this was fixed as part of the ([0.9.3](https://github.com/gephi/gephi/releases/tag/v0.9.3)) release. Please try again and reopen the issue if this is still a problem. Thank you!
