### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by GrimPixel** [gephi/gephi#2433]
## Expected Behavior

Starts like normal.

## Current Behavior

Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

## Steps to Reproduce

1. Download from the website or install from Arch repository
2. Open it from terminal

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 13
* Operating System: Arch Linux

**Comment by navalinovian** [comment]
duplicate of https://github.com/gephi/gephi/issues/2242
