### ISSUE TITLE
Bug UI Gephi on Mac

### ISSUE THREAD

**Issue by tiotim** [gephi/gephi#2435]
Dear friends, 

Working in Gephi has become impossible on my Macbook because of a visual bug. Every time I open a project the graph overlaps my screen. See the video I attached to see what I mean. 

I have looked up previous bug reports but haven't found a solution to this problem. Does that mean there is currently no solution to this bug for mac users? 

https://user-images.githubusercontent.com/79206964/156773664-f538255d-f160-433b-845d-a5c646f6f115.mov

**Comment by vpozdnyakov** [comment]
the same. it can be fixed by closing and opening "graph" window

**Comment by mbastian** [comment]
Hi and thanks for the report. Please try again with the latest version ([0.9.3](https://gephi.org/users/download/)) as we've made numerous changes to dependencies. Don't hesitate to reopen if the issue persists.
