### ISSUE TITLE
Report when opening a graph shows arguments instead of string

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#2453]
## Expected Behavior
There should be a string shown

## Current Behavior
We see handlebars for arguments that should have been replaced by strings

## Possible Solution
Not sure if this is in Gephi itself or in the internationalization property for French? (see screenshot: I have a French locale).

## Steps to Reproduce

1. Have a computer localized in French - but maybe any locale reproduces the bug
2. Open Gephi, choose the Miserables default graph
3. When the report window opens, choose the tab "report" (rapport in French)
4. See the bug

## Context

* Version used: Gephi 0.9.3
* Java version: 
* Operating System: Windows

![image](https://user-images.githubusercontent.com/1244100/160425023-a483d1de-c709-483c-a1bd-47157b2e2969.png)

**Comment by mbastian** [comment]
Thanks @seinecle! I've corrected the problem. For the record, this didn't require a code change, just an edit on Weblate: https://hosted.weblate.org/translate/gephi/io-importer-impl/fr/?sort_by=-priority%2Cposition&offset=6
