### ISSUE TITLE
add a link in the language menu -> to the platform to help with internationalization

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#2454]
I struggle to find the link to the platform where we can contribute to the localization of Gephi. If there was a link to it directly from the languages menu of Gephi, it would probably incentivize users to visit it and contribute.

**Comment by mbastian** [comment]
Good idea, should be easy enough to add a menu item that links to https://hosted.weblate.org/projects/gephi/

**Comment by luke-wagner** [comment]
Hi, I would like to try my hand at solving this issue.

**Comment by luke-wagner** [comment]
Fix for this issue: #2914

**Comment by mbastian** [comment]
Thanks @luke-wagner for the contribution
