### ISSUE TITLE
A better graph search function and highlighting

### ISSUE THREAD

**Issue by jacomyma** [gephi/gephi#2466]
I am just keeping track here of a demand that randomly appeared from a confirmed user.

It came from a Gephi that randomly appeared on Hacker News.
https://news.ycombinator.com/item?id=30915870#30929160

It's valuable because because those circles are not too close to the team (as Granovetter says, the strength of weak ties!). The original comment just mentions "My only quibble would be a better graph search function and highlighting."

**Comment by mbastian** [comment]
Progress made:
- New menu Tools > Search that opens a search dialog
- Search dialog allows to type text and browse results
- `SearchProvider` SPI to provide search in different places (id, label, columns etc.)
- Implement Id and Label providers. Supports "Equals", "StartsWith", "Contains"
- Search happens in parallel (multi-threaded) while aggregation and prioritisation is thread-safe
- Filtering for only some categories (nodes, edges)
- When selecting results, graph and datalab highlights (if window open)
- When clicking results, graph center on element
- When right-clicking results, the "Data Laboratory" context menu is shown (minus some manipulators that weren't relevant)
- Search dialog closes when it looses focus or when ESC is hit on keyboard
- Search dialog can be moved around when dragging it
- Ability to create a filter based on the search query, if Nodes or Edges category is selected. Filter can't be modified but would persist in the project as normally.
- Basic unit tests

Not done
- [ ]  API Documentation / Javadoc
- [ ] Search in columns

Implementation is modular but as this is experimental everything is in one `DesktopSearch` folder. Once we want to turn this into an official API, it would be very easy.

**Comment by mbastian** [comment]
Added documentation. Only remaining task is search within the columns. Let's leave that for a future update.

**Comment by seinecle** [comment]
👍👍👍
