### ISSUE TITLE
combining gexf files hangs in 093

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#2476]
## Expected Behavior

joining multiple gexf files as one hangs in 093

## Current Behavior

092 imports ok

## Steps to Reproduce

open files and add to one workspace
data sent to @jacomyma

**Comment by mbastian** [comment]
Hi @mihkal I've made a fix for this issue but I'm not 100% sure it would work in all cases. It does fix it on my machine. Would you mind trying the latest nightly build and let me know?
[gephi-0.9.4-SNAPSHOT-windows-x64.exe](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.4-SNAPSHOT&c=windows-x64&p=exe) (Windows)

[gephi-0.9.4-SNAPSHOT-macos-x64.dmg](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.4-SNAPSHOT&c=macos-x64&p=dmg) (Mac OS X)

[gephi-0.9.4-SNAPSHOT-linux-x64.tar.gz](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.gephi&a=gephi&v=0.9.4-SNAPSHOT&c=linux-x64&p=tar.gz) (Linux)

Thank you!
