### ISSUE TITLE
Icon for MacOS Big Sur/Monterey

### ISSUE THREAD

**Issue by mikima** [gephi/gephi#2480]
The icon on MacOS is out of scale compared to the ones used in the new version of the os. I know, not a big issue but simple to fix.

### Proposed solution
Attached is the icon redesigned using the latest macOS guidelines https://developer.apple.com/design/resources/#macos-apps

[gephi.icns.zip](https://github.com/gephi/gephi/files/8481127/gephi.icns.zip)

**Comment by mbastian** [comment]
Thanks a lot 🥇 Indeed, easy to fix 👍
