### ISSUE TITLE
Unable to import any spreadsheet into Gephi

### ISSUE THREAD

**Issue by con1003** [gephi/gephi#2492]
Hi there,

I am new to Gephi, so this could be an oversight on my part - apologies if so. 

I have prepared my nodes and edges sheets in both .csv and .xls format, but whenever I click "Import Spreadsheet" from the Data Laboratory tab, the "Open" dialogue box fails to generate any clickable files. I have also exported the .csv sheets from the Les Mis tutorial, and not even this file displays when I attempt to import.
<img width="1379" alt="Screenshot 2022-04-18 at 10 56 33" src="https://user-images.githubusercontent.com/103931441/163792181-dda19b06-3a7b-43aa-8cc3-7acca36edf5c.png">
 I will attach photos below.

## Expected Behavior

The "Open" dialogue box should allow me to open .csv spreadsheet files.

## Current Behavior

The "Open" dialogue box displays empty folders.

## Steps to Reproduce

1. Open new project
2. Click on "Import Spreadsheet"
3. For me, no files appear 
4.

## Context

I am trying to visualise a social network

## Your Environment

* Version used: Gephi 0.9.3
* Operating System: MacOS

**Comment by eduramiba** [comment]
See #2467
