### ISSUE TITLE
Unable to set range for the Partition Count filter on Component ID

### ISSUE THREAD

**Issue by adonig** [gephi/gephi#2493]
## Expected Behavior

The slider should display a minimum and a maximum for the Partition Count filter on the column Component ID.

## Current Behavior

Both minimum and maximum are NaN. I can't set the range manually.

## Steps to Reproduce

1. Import a graph. Mine had 55k nodes, 31k edges and lots of components with only 2 nodes.
2. Run the Connected Components algorithm.
3. Add a Partition Count filter on the column Component ID.
4. Try to set the filter range.

## Context

I'm trying to get rid of all components with less than three nodes.

## Your Environment

* Version used: Gephi 0.9.4
* Operating System: macOS Monterey 12.3.1

**Comment by mbastian** [comment]
Thanks for the report. I can indeed reproduce it.
