### ISSUE TITLE
Add Romanian as supported localization 🇷🇴

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2494]
The translation has been completed recently so we should add it to the list of supported translations. It might be good to have it quickly reviewed by someone else before shipping to make sure it's good quality.

cc @FluffyPanda69 who did all the localisation work!

**Comment by mbastian** [comment]
@FluffyPanda69 In the language selection menu, what should we put? "Română"? Thanks, just want to make sure :)

**Comment by FluffyPanda69** [comment]
@mbastian That's correct, thanks for adding it. I'll look over it again once the new release goes live to make sure everything looks right.

**Comment by mbastian** [comment]
Thanks, you can also now download the [nightly build](https://github.com/gephi/gephi#nightly-builds) and try it out. The language has been added to the menu. Cheers,
