### ISSUE TITLE
No graphs on Mac

### ISSUE THREAD

**Issue by rubensyanes** [gephi/gephi#2508]
## Expected Behavior
I expcted to wath the graph in both window: overview and preview

## Current Behavior
Both windows stay blank

## Steps to Reproduce

1. Install the version 0.9.4
2. Run it and open any project
3. Data is there, but no graphs
4.

## Your Environment

* Version used: Gephi 0.9.4
* Operating System: Mac Os Catalina 10.15.7
<img width="1280" alt="Captura de Pantalla 2022-04-23 a la(s) 3 17 38 a  m" src="https://user-images.githubusercontent.com/1066698/164882638-53a4c563-0233-4628-8154-2fd50f9c2310.png">
<img width="1280" alt="Captura de Pantalla 2022-04-23 a la(s) 3 17 19 a  m" src="https://user-images.githubusercontent.com/1066698/164882642-8672cc94-69d0-4142-b6a3-cce590eaa5da.png">
<img width="1280" alt="Captura de Pantalla 2022-04-23 a la(s) 3 17 31 a  m" src="https://user-images.githubusercontent.com/1066698/164882643-97f0f230-62af-4de9-961f-6af17c76e175.png">

**Comment by mbastian** [comment]
Hi and thanks for the report. Pretty strange. 
- Did you see any exception/error reported at startup? Alternatively you can find the log file and see if there is an error there at `~/Library/Application Support/gephi/0.9/var/log/messages.log`
- Did you try to wipe your user preferences? Delete folder `~/Library/Application Support/gephi/0.9`?

**Comment by rubensyanes** [comment]
It did work!
I deleted the aforementioned folder and ran the program again, skipping the step when Gephi asks to import previous versions materials, and worked fine.

Thanks a lot!

**Comment by rubensyanes** [comment]
Correction. After I followed the previous steps, the program did work well only the first time I open a project. But if I tried to open a second or third project, the visualization problem started again.
so, I deleted again the folder  ~/Library/Application Support/gephi/0.9 and restarted the program, but this time I said yes to import data from other versions, and it seems to work fine now.
