### ISSUE TITLE
MacOS: Gatekeeper prevents versions 0.9.4 and 0.9.5 to open without malware warning

### ISSUE THREAD

**Issue by zz-xiao** [gephi/gephi#2532]
“Gephi” cannot be opened because the developer cannot be verified.

**Comment by Simounawind** [comment]
there's a easy way to solve this problem as well as similars problems that occur to others apps :
1. Open the Terminal on your mac, 终端 in Chinese
2. print `sudo xattr -rd com.apple.quarantine ` make sure there's a space after the word quarantine
3. Open your Finder, find the app in your app list
4. drag this app into Terminal window, make sure again that there's a space between quarantine and your app
5. Enter, then print the password of ur Macbook
6. Voilà, problem solved !

**Comment by mbastian** [comment]
Hi, thanks for the report. The problem has been resolved and the next release (0.9.6) shouldn't have this issue anymore.
