### ISSUE TITLE
SHA256 Hash info of gephi-0.9.5-windows-x64.exe

### ISSUE THREAD

**Issue by SKJAIN2022** [gephi/gephi#2540]
Dear Team,

As digital Signature is missing, we need SHA256 Hash info of gephi-0.9.5-windows-x64.exe, downloaded from https://gephi.org/ or https://github.com/gephi/gephi/releases/download/v0.9.5/gephi-0.9.5-windows-x64.exe

Thanks in advance
Sunil

**Comment by mbastian** [comment]
Hi, you can find the source of origin for release binaries directly on Maven Central: https://repo1.maven.org/maven2/org/gephi/gephi/0.9.5/

It includes all signatures.

**Comment by SKJAIN2022** [comment]
Thanks a lot for 

> Hi, you can find the source of origin for release binaries directly on Maven Central: https://repo1.maven.org/maven2/org/gephi/gephi/0.9.5/
> 
> It includes all signatures.

Thanks a lot!!
