### ISSUE TITLE
Can't add new nodes since latest Gephi update

### ISSUE THREAD

**Issue by 30063446** [gephi/gephi#2564]
## Expected Behavior
In saved projects, Add node in Data Laboratory-> type in Label -> should come up as a new row in Data Table and shown in Overview

## Current Behavior
After clicking on Add Node, typing in Label and clicking yes, no new row is added in Data Table nor in Overview
Works with New Projects but not with Saved Projects

Specifications:
Product Version: Gephi 0.9.6 202206221744
Java: 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10
Runtime: OpenJDK Runtime Environment 11.0.15+10
System: Windows 11 version 10.0 running on amd64; Cp1252; en_AU (gephi)

**Comment by michaela-marincic** [comment]
I seem to be having the same problem.

**Comment by mbastian** [comment]
Duplicate ot #2557
