### ISSUE TITLE
Newly added columns do not automatically appear in the Appearance Partition menu

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2568]
## Expected Behavior

The newly added column shows up in the Partition menu.

## Current Behavior

When empty, the column do not show up in the Partition combo menu. When filled with their first value, they fail to appear. 

## Steps to Reproduce

1. Open sample graph like Les Miserables
2. Go to Data Laboratory and add a new column
3. Go to Partition and check that the column is not there (normal, as it's empty so there is nothing to partition)
4. Go back to Data Lab and add a value for a node
5. Go back to Partition and see that the column is still not there.

## Your Environment

* Version used: Gephi 0.9.6
* Operating System: Mac OS X

**Comment by Sijing98** [comment]
I think this bug still same here. I can't see the newly added column even in data laboratory.
