### ISSUE TITLE
Add field to input numbers for filtering 

### ISSUE THREAD

**Issue by SandroMartens** [gephi/gephi#2571]
I want to filter my nodes by some node property. But if I want to enter some numerical value, that slider is really inaccurate and I dont get my value in. For example I can't enter values `< 71`. 

### Proposed solution

Implement an Input field for numerical values.

### Additional context

![image](https://user-images.githubusercontent.com/66642986/180656409-a2f71ea3-6957-422c-aca0-9391a9ae1f53.png)
![image](https://user-images.githubusercontent.com/66642986/180656681-d7333341-06b1-4152-b744-3741a31d8040.png)

**Comment by mbastian** [comment]
Hi @SandroMartens, when you click on the actual number under the slider you can edit. Click on it, enter your number and then hit Enter.

**Comment by tommv** [comment]
This seems to be a UI problem: it is indeed possible to edit the actual number under the slider, but it this possibility is not suggested in the interface (one has to know that this is possible).

**Comment by mbastian** [comment]
Yes @tommv that is correct. Any suggestions how to fix this?

**Comment by comeb-cnil** [comment]
Sliders in Blender (3D software) are quite intuitive I think. Click on the slider let you edit the value:

![Image](https://user-images.githubusercontent.com/107397274/187630549-90e72957-ecd1-4af9-9fe5-24e35ed2146a.gif)

**Comment by comeb-cnil** [comment]
Sliders in Blender (3D software) are quite intuitive I think. Click on the slider let you edit the value:

![Image](https://user-images.githubusercontent.com/107397274/187630549-90e72957-ecd1-4af9-9fe5-24e35ed2146a.gif)
