### ISSUE TITLE
DisplayVersion not populated when installing on Windows

### ISSUE THREAD

**Issue by asjimene** [gephi/gephi#2575]
## Expected Behavior
DisplayVersion should be recorded in the Windows registry when installing Gephi. 

## Current Behavior
DisplayVersion is not set in the Windows registry when installing Gephi

## Possible Solution
It seems that InnoSetup is being used to build this installer, InnoSetup should put the DisplayVersion in the Windows registry as long as it is specified in the setup file: https://jrsoftware.org/ishelp/index.php?topic=setup_appversion

I do believe AppVersion just needs to be added to this file: https://github.com/gephi/gephi/blob/master/modules/application/src/main/app-resources/gephi.iss

## Steps to Reproduce

1. Install Gephi on a Windows device
2. Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{51722911-C391-4118-97BF-B50100D2AB15}_is1 (this is the path on the latest snapshot)
3. The standard DisplayVersion registry value is missing

![image](https://user-images.githubusercontent.com/3790176/181831485-647e9c01-8757-4896-8640-357820f63622.png)

## Context

DisplayName and DisplayVersion registry values are useful for detection when deploying software to an enterprise. They also help with software inventory in general. It is Microsoft best practices to include the DisplayName and DisplayVersion when installing software on Windows Operating Systems. https://docs.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key

## Your Environment

* Version used: Gephi 0.9.7-snapshot (64-bit)
* Operating System: Windows 10

**Comment by mbastian** [comment]
Hi @asjimene and thanks for the detailed report! 

I've added the `DisplayVersion` thanks to your instructions. Please download the latest build at https://github.com/gephi/gephi#nightly-builds and let me know if it works as expected. Thanks!

**Comment by asjimene** [comment]
This is perfect! Just tested it and thank you
![RemoteDesktopManagerFree_jjhmKGAvRI](https://user-images.githubusercontent.com/3790176/182643095-a56b0257-80cf-444c-a901-37d44924fce3.png)
!
