### ISSUE TITLE
Show node labels in data table edges

### ISSUE THREAD

**Issue by ChildishGiant** [gephi/gephi#2576]
When editing edges between nodes I always have to refer back to the nodes tab to see what the ID of the source and target refers to.
![image](https://user-images.githubusercontent.com/13716824/183289655-383a5f75-a832-493a-aefb-c4d142eb938f.png)

### Proposed solution
An optional column for "Source label" and the same for "Target label" in the edges data table.

**Comment by mbastian** [comment]
Hi @ChildishGiant, this option already exists. In the Data Laboratory Configuration you have a checkbox specifically for that purpose.
<img width="463" alt="Screenshot 2022-08-10 at 08 19 24" src="https://user-images.githubusercontent.com/234813/183829455-a894a266-76b4-43d7-adba-bcbc7f30a5f8.png">
