### ISSUE TITLE
Preview doesn't get Overview's background color

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#258]
The Preview module doesn't synchronize it's background color with Overview.

---

Imported from Launchpad using lp2gh.
- date created: 2010-07-12T08:23:32Z
- owner: mathieu.bastian
- assignee: mathieu.bastian
- the launchpad url was https://bugs.launchpad.net/bugs/604510

**Comment by jersub** [comment]
Do we really want this behavior? The current Preview is designed to have its own set of parameters. Synchro with the Overview should be an option, just as the node label color for instance.

**Comment by mbastian** [comment]
I agree, it should be an option but the parameters should be separated.

**Comment by jersub** [comment]
What do you mean by "the parameters should be separated"?

Wouldn't it be better to configure the Preview background color in the left grid instead of the bottom toolbar? The toolbar would be for navigation i.e. zooming while the grid would be for any graphical setting.

**Comment by mbastian** [comment]
Yes, it would be better to also have the background color on the side.
