### ISSUE TITLE
Better icon management

### ISSUE THREAD

**Issue by iosonosempreio** [gephi/gephi#2613]
Related to #2610. We should find a better way to handle icons behaviour because they are currently scattered across several different modules and folder, making them very hard to maintain.

### Proposed solution

Create a module that collects all icons, technical requirements, and control behaviors.

E.g., it can:
- Export individual icons to be imported into other modules;
- Provide variations of icons according to light/dark themes;
- Load themes are designed for visual impairment, children, or, more generally, for better diversity (i.e. RTL).

### Alternatives considered

Just replacing `.png` with `.svg` as attempted during the GephiWeek2022 is a first step but would not improve maintenance or give possibility to switch themes.

### Additional context

We could build on top of an existing icon library to optimise maintenance efforts. We could add icons related to network graphs if needed (pull request).

**Comment by mbastian** [comment]
Hi @iosonosempreio and thanks for your thoughts. 

It is possible to have all icons in a single module, and have all other modules depend on it to access them. I don't see major drawbacks of this approach. It would require some work up-front to change all the icons paths but afterwards it would be much easier to change the icons.

How would you organise the icons in there? everything in one folder or some kind of hierarchy?

**Comment by mbastian** [comment]
Hey @iosonosempreio @jacomyma the codebase now includes a [centralised directory](https://github.com/gephi/gephi/tree/master/modules/DesktopIcons/src/main/resources) where all the icons are. It should hopefully help migrate them faster.
