### ISSUE TITLE
Silent install not working with 0.9.7 build

### ISSUE THREAD

**Issue by LeeViewB** [gephi/gephi#2614]
## Expected Behavior
When using these arguments: /VERYSILENT /SUPRESSMSGBOXES /NORESTART
... to install the app silently, it should install silently. 

## Current Behavior
Trying to install version 0.9.7 silently with the following arguments (/VERYSILENT /SUPRESSMSGBOXES /NORESTART), however it doesn't work, as I am presented with the dialog from the attached screenshot.
This wasn't the case with older versions.

## Possible Solution
Include a fix in a future release. :) 

## Steps to Reproduce

1. Run an elevated CMD
2. gephi-0.9.7-windows-x64.exe /VERYSILENT /SUPRESSMSGBOXES /NORESTART
3. Prompt appears
![dialog](https://user-images.githubusercontent.com/31350302/188153701-5cb3061d-26f4-4eee-a080-9c2bca4dc4b3.png)

**Comment by mbastian** [comment]
Thanks a lot for the report. This seems like a regression since #2507. I'll investigate

**Comment by LeeViewB** [comment]
adding /ALLUSERS fixes this issue
