### ISSUE TITLE
Digital signature for installer

### ISSUE THREAD

**Issue by LeeViewB** [gephi/gephi#2615]
Please digitally sign your installer. When downloaded, browsers complain about this fact and try to block the download.
This could be an issue, potentially, if the installer is distributed via various Device Management solutions (Intune, SCCM, etc) and if customers have some security in place not to allow unsigned executables to run.

**Comment by mbastian** [comment]
Agreed, let me look into this

**Comment by mbastian** [comment]
Update:
- I've obtained a 1 year Code Signing certificate from [Sectigo](https://sectigo.com/). Wasn't a very smooth process but got it done. In the future, we should consider 3 years certificates to avoid the pain on a yearly basis.
- I was able to manually sign an executable on my Windows 10 machine.

To do:
- Automate as part of the CI process

**Comment by mbastian** [comment]
Update: I've added the codesigning step to GitHub actions so the installers we produce are automatically signed. 

It's not an EV certificate though so it would still need quite a few installs until the Windows Defender considers it safe. But it's the best we can do. EV certificates are too expensive and can't be setup on GitHub Actions as you need a USB dongle.
