### ISSUE TITLE
Add JSON Exporter

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#2674]
Gephi doesn't support JSON as an import/export format. We should try to fill that gap. For now, only focus on Export.

Now the essential question, is which format do we want to export to. There a few options and ultimately I think we should support all of them, or at least more than one to cover the most ground possible:
- [Graphology format](https://graphology.github.io/serialization.html#format), which originally was Signa.js' format
- Cytoscape and others have created a [JGF standard](https://jsongraphformat.info/).
- Clone of GEXF format, but in JSON. There is no definition but essentially following the XML specs.
- [NetworkX formats](https://networkx.org/documentation/stable/reference/readwrite/json_graph.html#)

### Proposed solution

Stick to the Graphology format as the first option.

Use the [JSON Exporter plugin](https://github.com/gephi/gephi-plugins/tree/jsonexporter-plugin/modules/JsonExporter) as inspiration and improve it. This was based on Sigma.js parser originally and written by @computermacgyver.

### Alternatives considered

[JSONLines](https://jsonlines.org/)/[ndjson](http://ndjson.org/) could also be an option, in combination with any of the format. Essentially representing the graph as a stream of nodes/edges. This wouldn't allow for graph-level configurations.

### Additional context

If you're aware of any other relevant JSON graph format, let me know.

FYI @jacomyal @Yomguithereal @jacomyma

**Comment by seinecle** [comment]
There is the vosviewer json file format. Not the most universal, adding it here for completeness:

https://app.vosviewer.com/docs/file-types/json-file-type/

**Comment by mbastian** [comment]
Added a format combo so that we can support multiple formats down the line. For now, I just implemented Graphology one but it shouldn't be too much work to add more.
<img width="326" alt="Screenshot 2022-10-28 at 21 01 05" src="https://user-images.githubusercontent.com/234813/198712651-6564b667-1f4a-482f-97f3-6d6228e8964d.png">

**Comment by Yomguithereal** [comment]
Regarding position, do you avoid `z` when all `z` are irrelevant (which seems to be the case in most Gephi usecases). I am asking because I often encounter gexf files having z positions even if they are all zero. But it might be something of the past, I did not check recently.

Out of curiosity, how did you choose to handle:

1. conflicting attribute names and gexf viz namespace values?
2. dynamics?

**Comment by mbastian** [comment]
> Regarding position, do you avoid `z` when all `z` are irrelevant (which seems to be the case in most Gephi usecases). I am asking because I often encounter gexf files having z positions even if they are all zero. But it might be something of the past, I did not check recently.

Yes, I don't export Z if irrelevant. GEXF export in Gephi does the same. Maybe some other exporters are still exporting Z.

> Out of curiosity, how did you choose to handle:
> 
> 1. conflicting attribute names and gexf viz namespace values?

Good point. It could be a problem for the edge type column as in Gephi that column is called "kind". I guess we should ignore those columns and throw a warning. I'll change that.

> 2. dynamics?

If the "Dynamics" checkbox is checked we serialize to string the dynamic attributes. For instance `"score": "\u003c[2002.0, 4]; [2004.0, 1]; [2006.0, 2]; [2011.0, 0]; [2012.0, 4]; [2014.0, 4]\u003e"`. If not checked, we use the current estimator to get a single value for that column. We do the same for CSV export.
