### ISSUE TITLE
Inconsistent Chinese formatting on UI

### ISSUE THREAD

**Issue by chakkk309** [gephi/gephi#2680]
There is a format inconsistency problem in Chinese display, which may cause misunderstanding to users.
The Chinese format on the button of the popup is inconsistent, “bubaocun" should be changed to "不保存".

## Expected Behavior
![image](https://user-images.githubusercontent.com/60494790/198870749-6ecf876a-3889-4b9b-9c07-cebbbce28b17.png)

## Current Behavior

![2e2346846716904ab0a2e40210df5ac](https://user-images.githubusercontent.com/60494790/198870573-605c13e1-6c6c-47f4-a1f5-8ba3a7d9bdc9.png) 

## Possible Solution
It seems like the  **CloseProject_confirm_doNotSave**  in `Bundle_zh_CN.properties` should be modified to match the other attributes.

```
CloseProject_confirm_title = \u201c\u5173\u95ed\u7a0b\u5e8f\u201d
CloseProject_confirm_message=<html><b>\u60f3\u4fdd\u5b58\u7a0b\u5e8f\u5417\uff1f</b><br><\u5b57\u4f53\u5927\u5c0f="-2">\u5982\u679c\u4e0d\u4fdd\u5b58\u4fee\u6539\uff0c\u4fe1\u606f\u5c06\u4f1a\u4e22\u5931\u3002</html>
CloseProject_confirm_save = \u4fdd\u5b58
CloseProject_confirm_doNotSave = bubaocun
CloseProject_confirm_cancel = \u53d6\u6d88
```

## Steps to Reproduce

1. select Chinese in language settings
2. create a workplace (not saved)
3. try to new other project
4. a pop-up box prompts: whether to save the project

## Your Environment

* Version used: Gephi 0.9.7
* Operating System: Windows 10 
* Gephi Language：Chinese

**Comment by mbastian** [comment]
Hi @chakkk309 good find. You can actually directly edit that yourself on weblate, see https://hosted.weblate.org/translate/gephi/desktop-project/zh_Hans/?checksum=93a5fd83cf4720d4&q=CloseProject_confirm_doNotSave&sort_by=-priority%2Cposition#suggestions

**Comment by chakkk309** [comment]
> Hi @chakkk309 good find. You can actually directly edit that yourself on weblate, see https://hosted.weblate.org/translate/gephi/desktop-project/zh_Hans/?checksum=93a5fd83cf4720d4&q=CloseProject_confirm_doNotSave&sort_by=-priority%2Cposition#suggestions

Thank you very much! I got it :)

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/231892735-657f66fd-302b-4966-94c1-a415e76659ef.png)

I also meet with this issue today, and found it was first caught in Oct, 31, 2022.

Today is 14, Apr, 2023, when will we see the fixed version?

**Comment by LaoshuBaby** [comment]
> I've encountered this issue as well using Gephi 0.10.1 for Mac OS (Apple Silicon). The "Do Not Save" button mistakenly displays as "bubaocun". Hope this can be fixed soon.

![图片](https://github.com/gephi/gephi/assets/42690037/9f2c81a8-86e6-4dd1-96d1-b84022da5463)

Translation had been fixed 6 months ago but it haven't been synced with this repository, or still haven't release a new major version.
