### ISSUE TITLE
Gephi 0.9.7 gets stuck when opening with MacOS Ventura

### ISSUE THREAD

**Issue by mirkohu** [gephi/gephi#2685]
## Steps to Reproduce

1. Install Gephi 0.9.7
2. Update to MacOS Ventura

## Context

 I was trying to open the application, but it opens and gets stuck showing "Initializing..."
## Your Environment

* Version used: Gephi 0.9.7
* Operating System: MacOS Ventura

**Comment by webphile94** [comment]
Same here :(

**Comment by maximelat** [comment]
same here :/

**Comment by gslanzon** [comment]
Same here

**Comment by abuzar-rasool** [comment]
same here :(

**Comment by mbastian** [comment]
Duplicate of #2546, and please fill this [questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSfBzLAiebu8hVISiWJ1SlAza3TNlO96EEArWD1uVhCIipytiQ/viewform?usp=sf_link) about this issue. We need your help.
