### ISSUE TITLE
OpenGL not using Nvidia but UHD graphics

### ISSUE THREAD

**Issue by laxris** [gephi/gephi#2704]
## Expected Behavior

Gephi runs and uses my nvidia card for openGL

## Current Behavior

Gephi is super slow, chokes up the whole computer, and takes significantly longer to do anything than on comparatively much worse hardware.

I have a Dell XPS 15 with a gtx 1650ti. In the settings, it seems it's also not using the nvidia card at a..

![image](https://user-images.githubusercontent.com/4000627/204083020-a9857e3d-85d1-43ef-98fb-9a271da7c8ed.png)

I checked and re-installed the newest drivers.

## Steps to Reproduce

1. download and run
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.7
* Operating System: Window 11pro 21h2
* I have a Dell XPS 15 with a gtx 1650ti.

**Comment by totetmatt** [comment]
Hi, sometime on laptop windows / nvidia doesn't pick up automatically gephi as software that uses heavily GPU.

Could you try to configure via the control panel of Nvida to force / bind gephi for a "Nvidia High Performance" profile ?

**Comment by laxris** [comment]
Oh that's amazing, that actually seems to have solved the problem. It
identifies the card now and is much faster.

Maybe configuring the program as high performance could be added to the FAQ
about GPU issues?

Thanks again for your help, I appreciate it!

**Comment by laxris** [comment]
Sucessfully resolved by configuring gephi as high performance in the nividia settings.
