### ISSUE TITLE
issues with loading loading *.gephi and workspaces with gephi-0.10.0-SNAPSHOT

### ISSUE THREAD

**Issue by carloalbertobono** [gephi/gephi#2717]
## Expected Behavior
Each project opens on load, additionally loaded projects are managed in new workspaces

## Current Behavior
*.gephi files are not loaded consistently
This happened to me only with the gephi-0.10.0-SNAPSHOT *.dmg from #2546
Video:
https://user-images.githubusercontent.com/90251890/210407054-7f690699-f6b5-4ae3-8a03-0f26cad239b8.mp4

## Notes
Happens with *.gephi files which showed no issue in the preceding versions.
Could it just be the file got corrupted while playing at reproducing the issue mentioned in #2546 ?
Example file:
[testout.gephi.zip](https://github.com/gephi/gephi/files/10338534/testout.gephi.zip)
Loading the *.gexf files from the welcome screen works just fine.
Additional workspaces are created consistently, but dissolve as soon as the *.gephi project is loaded.
 
## Steps to Reproduce

1. Load a *.gephi file
2. The graph is not shown
3. Load the *.gephi file, which prompts for saving the previous workspace
4. Again, the graph is not shown
5. Close the workspace
6. The graph is now visible, no workspace tab is ostensibly open

## Your Environment

* Version used: gephi-0.10.0-SNAPSHOT 
* Operating System: Monterey 12.6 Silicon (M1 Max)

**Comment by mok33** [comment]
I have the same issue when I build master (last commit c7e7e68e49cf0fa69d70e2a539c283c5d89d7f40). I tried importing the miserable template graph but I got an empty screen.

**Comment by mbastian** [comment]
Hi @carloalbertobono @mok33 you had two separate issues:
- @carloalbertobono A bug I introduced recently
- @mok33 A problem in the FR translation

Both are corrected. You can re-install the latest development build and try again. Thank you!

**Comment by mok33** [comment]
Hi @mbastia, thanks a lot ! I appreciat your help. 
Just another small issue, now I can no longer open .gefx file with gephi by double clicking on it. It opens the file loading window instead.

**Comment by carloalbertobono** [comment]
Hi @mbastian, great, I cloned and built 0.10.0 and can confirm that the issue looks gone

**Comment by mbastian** [comment]
> Hi @mbastia, thanks a lot ! I appreciat your help. Just another small issue, now I can no longer open .gefx file with gephi by double clicking on it. It opens the file loading window instead.

Thanks again, I fixed this issue as well.
