### ISSUE TITLE
Infinite loop when opening project

### ISSUE THREAD

**Issue by BaptisteHamburg** [gephi/gephi#2730]
Hello!
I have downloaded the new Gephi 0.10 Version, however when I started Gephi and open my latest project, the interface did not show the graphic and some buttons were moving... it seems to be a beta version problem that is possibly instable.
Could you find a solution!
Thanks
Baptiste

**Comment by fernandaalvaf** [comment]
https://user-images.githubusercontent.com/83588057/212052697-bf7c1f7e-a849-4b39-9a76-6a48d16bb216.mp4

Hello, 

I think I have the same problem. I attached a recording of the problem to this message in the hope that it is somehow helpful.
Any tips towards a fix (even a temporary workaround) to this would be highly appreciated. Thanks!

Best,

Fernanda

**Comment by BaptisteHamburg** [comment]
Hello Fernanda,

Thank you for your message, and yes it is exactly the same bug, with the flittering bar down the menu.

It would be very useful to fix this bug quickly!

Best regards

Baptiste

Von: Fernanda Alvares Freire ***@***.***>
Gesendet: den 12 januari 2023 12:18
An: gephi/gephi ***@***.***>
Cc: BaptisteHamburg ***@***.***>; Author ***@***.***>
Betreff: Re: [gephi/gephi] Bug with New Gephi 0.10 (Issue #2730)


https://user-images.githubusercontent.com/83588057/212052697-bf7c1f7e-a849-4b39-9a76-6a48d16bb216.mp4<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F83588057%2F212052697-bf7c1f7e-a849-4b39-9a76-6a48d16bb216.mp4&data=05%7C01%7C%7Ce88c2623d697442b6f5308daf48eb0e2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638091190941525518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aMsZogibbNTbC4FKsjMc0CZ1WmiJEQYRueFSCQKJDAA%3D&reserved=0>

Hello,

I think I have the same problem. I attached a recording of the problem to this message in the hope that it is somehow helpful.
Any tips towards a fix (even a temporary workaround) to this would be highly appreciated. Thanks!

Best,

Fernanda

-

**Comment by totetmatt** [comment]
Hey @BaptisteHamburg @fernandaalvaf  , thanks a lot for you report.

Could you give us more detail on which OS you are running on ?

**Comment by BaptisteHamburg** [comment]
Hey Matthieu,

I am running Gephi 0.10 on Windows 10 Enterprise, version 21H2, and with a Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2.90 GHz.

Do you need more information?

Best regards

Baptiste

Von: Matthieu Totet ***@***.***>
Gesendet: den 12 januari 2023 12:26
An: gephi/gephi ***@***.***>
Cc: BaptisteHamburg ***@***.***>; Mention ***@***.***>
Betreff: Re: [gephi/gephi] Bug with New Gephi 0.10 (Issue #2730)


Hey @BaptisteHamburg<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBaptisteHamburg&data=05%7C01%7C%7Ceb458115583e48227ed508daf48fc6ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638091195601918380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E13s9DOhaA1MwrOQnbIkIuJWyXC876OIoFryysEIwsA%3D&reserved=0> @fernandaalvaf<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffernandaalvaf&data=05%7C01%7C%7Ceb458115583e48227ed508daf48fc6ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638091195601918380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E%2B9iHxla5NKj%2FQTdRq%2FEdBsYKum%2F4KM6wF85rQnERXg%3D&reserved=0> , thanks a lot for you report.

Could you give us more detail on which OS you are running on ?

-

**Comment by fernandaalvaf** [comment]
Hello,

Thanks for the swift reply!
I am also running Gephi on Windows: Windows 11 Home, v. 21H2, 64-bit.

Best,

Fernanda

**Comment by DejanP86** [comment]
Hello, I have a similar problem - whenever I run Gephi 0.10 it erases the gephi project I open...file goes from 400kB to 1kB....

**Comment by totetmatt** [comment]
Hi @DejanP86 , it looks more related to this issue :) https://github.com/gephi/gephi/issues/2731

**Comment by DejanP86** [comment]
Thanks @totetmatt, I read it too quickly.

**Comment by mbastian** [comment]
Thanks for the report, the issue has been fixed. Please upgrade 0.10.1 (via Gephi > Check for Updates).

**Comment by BaptisteHamburg** [comment]
Hey Matthieu,

Could you find a solution for this problem?

It seems that the problem is linked with files created under previous versions, since the projects associated with GEPHI, like "Les Misérables" work perfectly. Might it be a problem with the transfer of configuration from the older version of GEPHI?

Best regards

Baptiste

Von: Baptiste Aguila
Gesendet: den 12 januari 2023 12:29
An: gephi/gephi ***@***.***>; gephi/gephi ***@***.***>
Cc: Mention ***@***.***>
Betreff: AW: [gephi/gephi] Bug with New Gephi 0.10 (Issue #2730)

Hey Matthieu,

I am running Gephi 0.10 on Windows 10 Enterprise, version 21H2, and with a Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz - 2.90 GHz.

Do you need more information?

Best regards

Baptiste

Von: Matthieu Totet ***@***.******@***.***>>
Gesendet: den 12 januari 2023 12:26
An: gephi/gephi ***@***.******@***.***>>
Cc: BaptisteHamburg ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Betreff: Re: [gephi/gephi] Bug with New Gephi 0.10 (Issue #2730)


Hey @BaptisteHamburg<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBaptisteHamburg&data=05%7C01%7C%7Ceb458115583e48227ed508daf48fc6ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638091195601918380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E13s9DOhaA1MwrOQnbIkIuJWyXC876OIoFryysEIwsA%3D&reserved=0> @fernandaalvaf<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffernandaalvaf&data=05%7C01%7C%7Ceb458115583e48227ed508daf48fc6ac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638091195601918380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E%2B9iHxla5NKj%2FQTdRq%2FEdBsYKum%2F4KM6wF85rQnERXg%3D&reserved=0> , thanks a lot for you report.

Could you give us more detail on which OS you are running on ?

-

**Comment by BaptisteHamburg** [comment]
Dear Matthieu,

Yes, and it works again, thank you!

Best regards

Baptiste

Von: Matthieu Totet ***@***.***>
Gesendet: den 18 januari 2023 16:41
An: gephi/gephi ***@***.***>
Cc: BaptisteHamburg ***@***.***>; Mention ***@***.***>
Betreff: Re: [gephi/gephi] Infinite loop when opening project (Issue #2730)


@BaptisteHamburg<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBaptisteHamburg&data=05%7C01%7C%7Cfddb25cd61044dc6557208daf96a6b7d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638096532708972130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AahWgoaeWcXT2C1NdnoZAZ%2FH45XHx%2FD%2FwCgOyI4znSI%3D&reserved=0> Did you updated to the new Gephi v.10.1 from yesterday ? Are you observing the same behavior with this new version ?

-
