### ISSUE TITLE
Projects do not save. 

### ISSUE THREAD

**Issue by MelitaThomas** [gephi/gephi#2733]
I have created a project, added nodes and edges, manipulated it, and saved the graphs as ,pdf, but once i have closed the project, no matter how many times, and in how many places it has been saved, it is always empty when I reload it - no nodes or edges. This is Gephi 0.10.0 running Windows 11. This happens whether I close the programme and try to reopen it from the file (which exists in saved location) or even if I close it whilst leaving Gephi running and then try to reopen it. The name of the project is there, but there is no content.

**Comment by nlafferriere** [comment]
I have the same problem in Windows 11

**Comment by Duvuki** [comment]
I have same issue when saving to .gephi format. 
OS ver: Ubuntu 20.04.5 LTS

**Comment by mbastian** [comment]
Duplicate #2731
