### ISSUE TITLE
Recovering wiped .gephi file caused by Gephi 0.10 bug

### ISSUE THREAD

**Issue by ForkedLightning** [gephi/gephi#2736]
Gephi 0.10 overwrote my .gephi file with a blank file yesterday. Does Gephi keep a temporary file containing the data anywhere else for recovery?

I lost a year's worth of work and I don't have access to the original dataset anymore.

Why did the devs push this to release and notified users to upgrade even though such a major bug was known for days? Take it down immediately.

**Comment by seinecle** [comment]
Absolutely sorry for the issue. A fix has been pushed.
