### ISSUE TITLE
Cannot saved .gephi file in newest OS (common issue had been reported for many people previously)

### ISSUE THREAD

**Issue by suiweikang** [gephi/gephi#2749]
Current Behavior
When saving a .gephi file, the document seems to be saved (its number of kilobytes increases), but when you leave the project, the document loses its content (while still existing, but a few hundred bytes). When you open it again, it is an empty project. It seems that Geohi 0.10.1 still have bug of saving in newest OS (Mac OS Monterey 13.2）

Your Environment
Version used: Gephi 0.10.1
Operating System: Mac OS Monterey 13.2

**Comment by mbastian** [comment]
Hi @suiweikang, we had an issue in 0.10.0 but it was corrected in 0.10.1. I'm not able to reproduce this issue anymore. Can you be more specific on the exact steps you're taking to reproduce this issue on your side? Thank you!

**Comment by suiweikang** [comment]
@mbastian. My operating system is Mac OS 13.2 (22D49)(M1 chip). When I saved the file of Gephi, it was found to be an empty file. May I ask if you have the same operating system as mine? Maybe this bug not be encountered by all operating systems.
Or could I send a video of my operation to you?
Thank you very much.

**Comment by totetmatt** [comment]
@suiweikang We need to know exactly the steps you do so we can reproduce and investigate the bug. A video screen capture would be a great help .

**Comment by suiweikang** [comment]
I don't know how to send video through github, could you provide an mail for me, i will send it to you mail.

**Comment by suiweikang** [comment]
@mbastian I don't know how to send video through github, could you provide an mail for me, i will send it to you mail.

**Comment by mbastian** [comment]
@suiweikang Sure, feel free to send to mathieu.bastian [at] gephi.org

**Comment by mbastian** [comment]
@suiweikang I haven't heard back. I have the same OS and I can't reproduce this issue. Please reopen if it's still an issue.
