### ISSUE TITLE
include release of jar into the github workflow

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [gephi/gephi#2751]
### Proposed solution
add the jar to the github release

### Additional context
it would be great if its possible because sometimes I want to use gephi with my own jdk.

**Comment by seinecle** [comment]
Hi, can you just use the Gephi toolkit, which is Gephi packaged as a single jar in a headless version?

**Comment by mbastian** [comment]
We already publish all artefacts (including JARs) to Maven central. Publishing them as well to GitHub seems superfluous and additional maintenance work.
