### ISSUE TITLE
Overview window not working properly

### ISSUE THREAD

**Issue by ngmaclaren** [gephi/gephi#2799]
## Expected Behavior
Interactive view of graph in the Overview window.

## Current Behavior
Graph image is mostly not present. If I do something that forces a window refresh (not sure if those are the right terms), like resizing the right sidebar, then the network flash on screen. I can operate on the network by using the Appearance or Layout tab, and I can produce an image in the Preview window.

## Steps to Reproduce

1. Open Gephi
2. Load a graph or .gephi file
3. Open Overview window
4. To see the graph image flash on screen, resize a sidebar.

## Your Environment

* Version used: Gephi 0.10.1
* Operating System: Manjaro Linux

-------------------------------------------------------------------------------
>Log Session: Thursday, April 6, 2023 at 9:13:42 PM Eastern Daylight Time
>System Info: 
  Product Version         = Gephi 0.10.1 202301172018
  Operating System        = Linux version 5.13.19-2-MANJARO running on amd64
  Java; VM; Vendor        = 11.0.17; OpenJDK 64-Bit Server VM 11.0.17+8; Eclipse Adoptium
  Runtime                 = OpenJDK Runtime Environment 11.0.17+8
  Java Home               = /home/neil/gephi-0.10.1/jre-x64/jdk-11.0.17+8-jre
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /home/neil
  Current Directory       = /home/neil/gephi-0.10.1/bin
  User Directory          = /home/neil/.gephi/0.10
  Cache Directory         = /home/neil/.cache/gephi/0.10
  Installation            = /home/neil/gephi-0.10.1/extra
                            /home/neil/gephi-0.10.1/gephi
                            /home/neil/gephi-0.10.1/platform
                            /home/neil/gephi-0.10.1/platform
  Boot & Ext. Classpath   = 
  Application Classpath   = /home/neil/gephi-0.10.1/platform/lib/boot.jar:/home/neil/gephi-0.10.1/platform/lib/org-openide-modules.jar:/home/neil/gephi-0.10.1/platform/lib/org-openide-util.jar:/home/neil/gephi-0.10.1/platform/lib/org-openide-util-lookup.jar:/home/neil/gephi-0.10.1/platform/lib/org-openide-util-ui.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ar_SA.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_bg.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ca.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_cs.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_de.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_es.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_fr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_gl_ES.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_in_ID.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_it.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ja.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ko.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_nl_NL.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_pl.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_pt_BR.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_pt_PT.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ro.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_ru.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_si.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_sq.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_sv.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_tr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_zh_CN.jar:/home/neil/gephi-0.10.1/platform/lib/locale/boot_zh_TW.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_bg.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ca.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_cs.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_de.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_es.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_fr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_in_ID.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_it.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ja.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ko.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_pl.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ro.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_ru.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_si.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_sq.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_sv.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_tr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ar_SA.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_bg.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ca.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_cs.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_de.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_es.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_fr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_gl_ES.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_in_ID.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_it.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ja.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ko.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_de.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_es.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_it.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_si.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_nl_NL.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_pl.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_pt_BR.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_pt_PT.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ro.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_ru.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_si.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_sq.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_sv.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_tr.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_zh_CN.jar:/home/neil/gephi-0.10.1/platform/lib/locale/org-openide-util_zh_TW.jar
  Startup Classpath       = /home/neil/gephi-0.10.1/platform/core/org-netbeans-libs-asm.jar:/home/neil/gephi-0.10.1/platform/core/asm-9.3.jar:/home/neil/gephi-0.10.1/platform/core/core.jar:/home/neil/gephi-0.10.1/platform/core/asm-commons-9.3.jar:/home/neil/gephi-0.10.1/platform/core/asm-tree-9.3.jar:/home/neil/gephi-0.10.1/platform/core/core-base.jar:/home/neil/gephi-0.10.1/platform/core/org-openide-filesystems.jar:/home/neil/gephi-0.10.1/platform/core/org-openide-filesystems-compat8.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_sv.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ru.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ko.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_zh_CN.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ro.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ca.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_in_ID.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_cs.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_pt_PT.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_pl.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_fr.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_zh_CN.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_it.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_bg.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_nl_NL.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ro.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ar_SA.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_gl_ES.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_in_ID.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_fr.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ru.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ja.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_cs.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_es.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_bg.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_nl_NL.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_zh_TW.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_gl_ES.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_tr.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_si.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_zh_TW.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_pl.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_sv.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ko.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_de.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_sq.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_ca.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_de.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ar_SA.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_si.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_it.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_pt_PT.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_ja.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_pt_BR.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_pt_BR.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_es.jar:/home/neil/gephi-0.10.1/platform/core/locale/core_sq.jar:/home/neil/gephi-0.10.1/platform/core/locale/org-openide-filesystems_tr.jar:/home/neil/gephi-0.10.1/gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.52 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.util [9.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.util.ui [9.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.modules [7.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.annotations.common/1 [1.46 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems [9.30 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.awt [7.86 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.progress/1 [1.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.progress.nb [1.66 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.dialogs [7.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.nodes [7.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.windows [6.95 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.batik.read [1.11.0.1 1 Netbeans/netbeans-TLP/netbeans/release160-11-on-20221119]
	org.openide.util.ui.svg [1.12 Netbeans/netbeans-TLP/netbeans/release160-11-on-20221119]
	org.netbeans.modules.editor.mimelookup/1 [1.58 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.text [6.86 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.scripting [1.15 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.tabcontrol [1.75 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.outline [1.52 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.explorer [6.80 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.actions [6.57 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.queries/1 [1.61 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.templates [1.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems.nb [9.28 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.loaders [7.88 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.intent [1.20 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.api.io [1.21 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.io [1.67 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.openide.filesystems.compat8 [9.27 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.plaf [1.60 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring [1.42 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.asm [5.21 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.bootstrap/1 [2.96 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.startup.base [1.80.0.1 1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.startup/1 [1.80.0.1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.sampler [1.32 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core/2 [3.69 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.spi.quicksearch [1.45 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.options.api/1 [1.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.flatlaf/1 [1.12 2.6 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.laf.flatlaf [1.11 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.swing.laf.dark/1 [2.13.0.2 2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.templates/1 [1.25 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.settings/1 [1.67 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.sendopts/2 [2.54 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.progress.ui [1.51 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.print [7.44 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.options.keymap [1.55 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs/2 [2.73.0.2 2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.ui [2.21.0.2 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.nio2 [1.33 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.jna/2 [2.13 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.masterfs.linux [1.31 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring.fallback [1.26 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.keyring.impl [1.42 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.janitor [1.11 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.favorites/1 [1.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.services [1.73 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.cli [1.32 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.windows/2 [2.103 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.ui/1 [1.63 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.osgi [1.40 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.felix [2.33 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.autoupdate.ui [1.64 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.modules.core.kit [1.49 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.libs.jna.platform/2 [2.13 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.output2/1 [1.60 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.network [1.30 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.nativeaccess/1 [1.49 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.multitabs/1 [1.30.0.1 1 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.netbeans.core.io.ui/1 [1.48 16-321935444b183aea1c4ff255d8d2ab8d50c60606]
	org.gephi.core.library.wrapper [0.10.1 0.10.1 202301172022]
	org.gephi.utils.longtask [0.10.1 0.10.1 202301172022]
	org.gephi.project.api [0.10.1 0.10.1 202301172023]
	org.gephi.graph.api [0.10.1 0.10.1 202301172023]
	org.gephi.utils [0.10.1 0.10.1 202301172023]
	org.gephi.ui.library.wrapper [0.10.1 0.10.1 202301172022]
	org.gephi.ui.utils [0.10.1 0.10.1 202301172024]
	org.gephi.desktop.icons [0.10.1 0.10.1 202301172022]
	org.gephi.ui.components [0.10.1 0.10.1 202301172025]
	org.gephi.db.drivers [0.10.1 0.10.1 202301172022]
	org.gephi.io.importer.api [0.10.1 0.10.1 202301172024]
	org.gephi.mostrecentfiles.api [0.10.1 0.10.1 202301172022]
	org.gephi.desktop.project [0.10.1 0.10.1 202301172026]
	org.gephi.welcome.screen [0.10.1 0.10.1 202301172027]
	org.gephi.datalab.api [0.10.1 0.10.1 202301172024]
	org.gephi.visualization.api [0.10.1 0.10.1 202301172025]
	org.gephi.tools.api [0.10.1 0.10.1 202301172024]
	org.gephi.visualization [0.10.1 0.10.1 202301172027]
	org.gephi.algorithms.plugin [0.10.1 0.10.1 202301172023]
	org.gephi.tools.plugin [0.10.1 0.10.1 202301172029]
	org.gephi.statistics.api [0.10.1 0.10.1 202301172024]
	org.gephi.statistics.plugin [0.10.1 0.10.1 202301172028]
	org.gephi.filters.api [0.10.1 0.10.1 202301172023]
	org.gephi.appearance.api [0.10.1 0.10.1 202301172023]
	org.gephi.filters.plugin [0.10.1 0.10.1 202301172030]
	org.gephi.timeline.api [0.10.1 0.10.1 202301172030]
	org.gephi.statistics.plugin.ui [0.10.1 0.10.1 202301172029]
	org.gephi.settings.upgrader [0.10.1 0.10.1 202301172022]
	org.gephi.batik.wrapper [0.10.1 0.10.1 202301172022]
	org.gephi.preview.api [0.10.1 0.10.1 202301172024]
	org.gephi.preview.plugin [0.10.1 0.10.1 202301172026]
	org.gephi.io.exporter.api [0.10.1 0.10.1 202301172023]
	org.gephi.io.exporter.preview [0.10.1 0.10.1 202301172028]
	org.gephi.preview.export.ui [0.10.1 0.10.1 202301172029]
	org.gephi.perspective.api [0.10.1 0.10.1 202301172022]
	org.gephi.layout.api [0.10.1 0.10.1 202301172025]
	org.gephi.layout.plugin [0.10.1 0.10.1 202301172027]
	org.gephi.io.importer.plugin [0.10.1 0.10.1 202301172026]
	org.gephi.io.generator.api [0.10.1 0.10.1 202301172026]
	org.gephi.io.generator.plugin [0.10.1 0.10.1 202301172027]
	org.gephi.io.exporter.plugin [0.10.1 0.10.1 202301172024]
	org.gephi.import.plugin.ui [0.10.1 0.10.1 202301172028]
	org.gephi.generator.plugin.ui [0.10.1 0.10.1 202301172028]
	org.gephi.desktop.window [0.10.1 0.10.1 202301172027]
	org.gephi.filters.plugin.ui [0.10.1 0.10.1 202301172030]
	org.gephi.filters.impl [0.10.1 0.10.1 202301172030]
	org.gephi.export.plugin.ui [0.10.1 0.10.1 202301172026]
	org.gephi.desktop.tools [0.10.1 0.10.1 202301172029]
	org.gephi.desktop.timeline [0.10.1 0.10.1 202301172030]
	org.gephi.desktop.statistics [0.10.1 0.10.1 202301172026]
	org.gephi.datalab.plugin [0.10.1 0.10.1 202301172029]
	org.gephi.desktop.io.export [0.10.1 0.10.1 202301172025]
	org.gephi.desktop.datalab [0.10.1 0.10.1 202301172028]
	org.gephi.desktop.search [0.10.1 0.10.1 202301172030]
	org.gephi.desktop.preview [0.10.1 0.10.1 202301172027]
	org.gephi.desktop.layout [0.10.1 0.10.1 202301172027]
	org.gephi.desktop.import [0.10.1 0.10.1 202301172028]
	org.gephi.desktop.generate [0.10.1 0.10.1 202301172028]
	org.gephi.desktop.filters [0.10.1 0.10.1 202301172025]
	org.gephi.desktop.context [0.10.1 0.10.1 202301172025]
	org.gephi.desktop.branding [0.10.1 0.10.1 202301172029]
	org.gephi.appearance.plugin [0.10.1 0.10.1 202301172024]
	org.gephi.appearance.plugin.ui [0.10.1 0.10.1 202301172027]
	org.gephi.desktop.appearance [0.10.1 0.10.1 202301172028]
	nl.cloudfarming.client.lib.platform.l10n [1.1 1.1-NB80 201411231331]
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: no suitable found, using fallback.
INFO [org.netbeans.core.network.proxy.fallback.FallbackNetworkProxy]: Fallback system proxy resolver: no http_proxy variable found
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO: Current Version is gephi
Diagnostic information
Input arguments:
	-Djdk.home=/home/neil/gephi-0.10.1/jre-x64/jdk-11.0.17+8-jre
	-Dnetbeans.dirs=/home/neil/gephi-0.10.1/extra:/home/neil/gephi-0.10.1/gephi:/home/neil/gephi-0.10.1/platform:
	-Dnetbeans.home=/home/neil/gephi-0.10.1/platform
	-Dsun.java2d.metal=true
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dapple.awt.graphics.UseQuartz=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dnetbeans.winsys.hideEmptyDocArea=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-Dapple.awt.application.appearance=system
	--add-opens=java.base/java.net=ALL-UNNAMED
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	--add-opens=java.desktop/javax.swing=ALL-UNNAMED
	--add-opens=java.base/java.nio=ALL-UNNAMED
	--add-exports=java.desktop/sun.awt=ALL-UNNAMED
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/home/neil/.gephi/0.10/var/log/heapdump.hprof
	-Djava.security.manager=allow
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 250.0MB maximum 3980.0MB
Non heap memory usage: initial 7.3MB maximum -1b
Garbage collector: G1 Young Generation (Collections=7 Total time spent=0s)
Garbage collector: G1 Old Generation (Collections=0 Total time spent=0s)
Classes: loaded=9312 total loaded=9312 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 16,686,002,176
INFO [null]: Total physical memory 16,686,002,176
INFO: Detected encoding UTF-8 in XML file
INFO: GL_VENDOR: Intel
INFO: GL_RENDERER: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
INFO: GL_VERSION: 4.6 (Compatibility Profile) Mesa 23.0.1
INFO: GL_SURFACE_SCALE: 1
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/View/ marked with the position attribute: [org-netbeans-core-windows-actions-ToggleFullScreenAction.instance\position], but some are: [ToggleFullScreenAction.shadow]
INFO [DefaultProcessor]: # Nodes loaded: 1,249
INFO [DefaultProcessor]: # Edges loaded: 8,500
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'PreviewSettingsTopComponent'. Reason: Top component PreviewSettingsTopComponent could not be located or loaded from Components folder.

**Comment by ngmaclaren** [comment]
Update: opened Gephi 0.10 on a Ubuntu machine and it works just fine.

**Comment by Sirvy** [comment]
Exactly same problem on Kubuntu.

**Comment by Sirvy** [comment]
This solved it for me:
`
export LIBGL_ALWAYS_SOFTWARE=1
`

**Comment by ngmaclaren** [comment]
In your .bashrc?

**Comment by ngmaclaren** [comment]
> This solved it for me: `export LIBGL_ALWAYS_SOFTWARE=1`

Awesome---for me as well. I wrote `LIBGL_ALWAYS_SOFTWARE=true` in `/etc/environment`. See [here](https://wiki.archlinux.org/title/OpenGL) and [here](https://wiki.archlinux.org/title/Environment_variables) for Arch Linux users.

**Comment by ngmaclaren** [comment]
Follow-up: other software doesn't cooperate with this setting, so @Sirvy's solution may be better.
