### ISSUE TITLE
Unable to open file saved from Gephi Lite

### ISSUE THREAD

**Issue by qkhanhpro** [gephi/gephi#2907]
I am using https://gephi.org/gephi-lite/
To create a graph.

I try to open that graph in Gephi PC (https://github.com/gephi/gephi/releases/download/v0.10.1/gephi-0.10.1-windows-x64.exe)

But it fail to open. The file is attached

The error: 
Issue{message=Chinese.gexf failed to import due to the following error: java.lang.IllegalArgumentException: Invalid index 0; current element has only 0 attributes, level=SEVERE}	SEVERE	

[Chinese.txt](https://github.com/gephi/gephi/files/15152011/Chinese.txt)

**Comment by mbastian** [comment]
Hi @qkhanhpro, closing the issue here as this was fixed in gephi-lite.
