### ISSUE TITLE
Gephi keeps crashing when going from Overview to Preview

### ISSUE THREAD

**Issue by rebecca-borges** [gephi/gephi#2911]
Mac Sonoma 14.4.1
Product Version: Gephi 0.10.1 202301172018
Java: 11.0.17; OpenJDK 64-Bit Server VM 11.0.17+8
Runtime: OpenJDK Runtime Environment 11.0.17+8
System: Mac OS X version 14.4.1 running on x86_64; UTF-8; en_GB (gephi)

Thanks!

**Comment by CurtLH** [comment]
I'm having the same issue and it's making the tool unusable. I doesn't seem to be related to the size of the graph I'm trying to visualize, so I'm not sure what to do in this situation.

**Comment by CurtLH** [comment]
It seems like this is a known issue.  Check out https://github.com/gephi/gephi/issues/2546 for more info.

**Comment by nabsiddiqui** [comment]
@rebecca-borges. I have found that going to Window -> Reset Windows works to fix this or Window -> Data Table or Preview.


Recently, in #2546 many people have mentioned closing any background utilities (Contexts, Magnet, Rectangle, AltTab, etc.) seems to fix many issues. You may want to try that on Mac OS X in general.

In terms of the specific issue of switching between Preview and Data Table, I found that this was related to older plugins. Try to delete the community plugins you have. I don't remember the exact plugin that was causing me issues. I want to say it was the Multimode Networks Transformation Plugin. I'm sorry to the developers of that plugin if I am remember incorrectly.
