### ISSUE TITLE
Color the edge with the opposite node color when selected in Overview

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#292]
see http://forum.gephi.org/viewtopic.php?f=31&t=774

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-11-23T05:05:28Z
 * owner: mathieu.bastian
 * the launchpad url was https://bugs.launchpad.net/bugs/680366

**Comment by csabahruska** [comment]
The correct link for the discussion:
http://forum-gephi.org/viewtopic.php?f=31&t=774
