### ISSUE TITLE
Data Lab: float/double values not truncated on Linux

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#307]
Floating-point numbers are correctly truncated to 4 digits on Windows for display, however it doesn't work on Linux/Ubuntu 8.10. One should investigate if this bug occurs also on other Linux distributions.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-03-12T21:33:52Z
 * owner: sebastien.heymann
 * assignee: eduramiba
 * the launchpad url was https://bugs.launchpad.net/bugs/734037

**Comment by eduramiba** [comment]
Fixed in 0.9.1
