### ISSUE TITLE
Data lab columns size and position reset after each refresh on MacOSX

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#316]
Data lab columns' size and position are reset each time the lab is refreshed. This is very annoying when switching from view or workspace or update values in the data lab.

Here is an example when switching view
1) Goto data lab
2) Change one column size and/or position
3) Goto Overview 
4) Goto data lab
5) Column which size/position have been modified is reset

Here is another example when modifying a boolean value
1) Generate a dynamic graph
2) Goto data lab
3) Add a new column of type Boolean
4) Change this new column's size and/or position (extend it and/or move it before score column for instance)
5) Change one value of this column (from false to true): the column size and position are reset

This "bug" is reproducible on gephi 07 beta and gephi 08 alpha on Mac OS X

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-04-14T08:03:42Z
 * owner: sebastien-hertz
 * assignee: eduramiba
 * the launchpad url was https://bugs.launchpad.net/bugs/760445

**Comment by eduramiba** [comment]
This is fixed in 0.9 as we no longer use Outline table and only JXTable.
