### ISSUE TITLE
mouse does not respond after access to data laboratory if node pencil is activated

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#325]
I'm using Gephi 0.8 on windows xp.
If I access the data laboratory while the option "node pencil" is activated, I won't be able to manipulate the graph when I go back to the Overview window. Only the mouse wheel is responding. In order to manipulate it again, I need to select one of the three first options (direct selection, rectangle or drag), access the data lab again, and go back to the Overview window.

Way to reproduce the bug:
- open any graph in Gephi.
- select the node pencil mode
- click on the Data Laboratory tab
- click on the Overview tab
- You souldn't be able to manipulate the graph anymore (even not to move with the right mouse click)
- select one of the first three modes: direct selection, rectangle selection or drag
- click on the Data Laboratory tab
- click on the Overview tab
- you should be able to manipulate the graph again.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-05-25T10:19:16Z
 * owner: gautier-krings
 * assignee: eduramiba
 * the launchpad url was https://bugs.launchpad.net/bugs/788034

**Comment by eduramiba** [comment]
Closing old issue, seems to be fixed in 0.9.
