### ISSUE TITLE
Some files still AGPL

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#345]
I see Eduardo has just updated all the files to the new dual license. There's a few that have been missed:

gephi/DesktopProject/src/org/gephi/desktop/project/ProjectControllerUIImpl.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/ConnectedComponents.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/ClusteringCoefficient.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/GraphDistance.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/ClusteringCoefficientBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/GraphDistanceBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/HitsBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/DensityBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/ModularityBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/EigenvectorCentralityBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/DegreeBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/builder/PageRankBuilder.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/PageRank.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/Hits.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/EigenvectorCentrality.java: AGPL (v3 or later) 
gephi/StatisticsPlugin/src/org/gephi/statistics/plugin/Modularity.java: AGPL (v3 or later) 
gephi/StatisticsPluginUI/src/org/gephi/ui/statistics/plugin/GraphDensityUI.java: AGPL (v3 or later) 
gephi/CollectionUtils/src/org/gephi/utils/collection/avl/SimpleAVLTree.java: AGPL (v3 or later) 
gephi/CollectionUtils/src/org/gephi/utils/collection/avl/ParamAVLTree.java: AGPL (v3 or later)

---

Imported from Launchpad using lp2gh.
- date created: 2011-10-02T23:21:03Z
- owner: rockclimb
- assignee: eduramiba
- the launchpad url was https://bugs.launchpad.net/bugs/864941

**Comment by comradekingu** [comment]
@mbastian It is not possible to go from AGPLv3+ to GPLv3+ or CCDL. (Unless the copyright-holder(s) all agree).
