### ISSUE TITLE
Import links french version

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#439]
When exporting/importing a link table (laboratory data) in the French translation is bug.
When we export the column is called "Destination"and when we imports with Gephi the column is called "Target".

It is not a big problem just change the name of the column in the csv file, I just wanted to do reporting.

---

Imported from Launchpad using lp2gh.
- date created: 2011-09-07T08:17:36Z
- owner: lenier-benoit
- the launchpad url was https://bugs.launchpad.net/bugs/843662

**Comment by eduramiba** [comment]
This was indirectly fixed in 0.9 module migration to graphstore.
