### ISSUE TITLE
Infinite loop while opening a project...

### ISSUE THREAD

**Issue by cybertib** [gephi/gephi#450]
Hello, 

I've built a project using 0.7 version, and it worked pretty well under 0.8a version. However, it doesn't open correctly under 0.8b version. 

The problem is that I have a loading bar at the bottom right on the screen, and it never finishes. Then, I cannot modify or save my file. 

Cheers, 
Thibault

**Comment by mbastian** [comment]
Closing, this should be fixed in 0.9 as the project IO has been rewritten from scratch.
