### ISSUE TITLE
Colors in partition filter inconsistent with real partition colors

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#455]
The colors used in the partition filter panel are different from the colors used on the graph. As it's not possible now to match them due to the limitations of the architecture, we could remove the displayed colors and replace them color boxes by checkboxes, indicating whether the partition is displayed or not.

**Comment by mbastian** [comment]
This has been fixed in trunk and will be included in the upcoming 0.9 release. The filter picks up the colors used in partition. If the colors are changed in partition while the filter already exists one can Right click on the filter panel and do "Refresh".
