### ISSUE TITLE
Pies don't hide if you select another partition

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#457]
Once you display Pie, it does not consistently go away after clicking Hide Pie. 

This sequence reliably produces it:
partition/Nodes/Select a partition/Show Pie
Now change the partition type from the menu
Now try to hide the pie: it won't go away. 

It may go away when switching to another OS X application or doing something else that causes re-rendering. But selecting back there, the pie comes back even though we have clicked Hide Pie.

Furthermore, trying to show the pie for a different partition it is still stuck on the first partition's pie. 

This suggests a rendering bug. 

OS X 10.6.8 (on MacPro, MacBookPro, and MacBook). 
Gephi 0.8 Beta

**Comment by mbastian** [comment]
We've refactored the partition module into something called appearance and for now removed the pie altogether so closing as won't fix. We may bring them back in a better version later.
