### ISSUE TITLE
Shapes for displaying partitions

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#460]
We'd like to be able to display partitions using shapes as well as colors. This currently can be done under Ranking but not Partition. The situation: 
- We are using color to display the Modularity Class (indicating the discovered communities) 
- We want to also visualize node type to see how the node types distribute across the communities. (We have Actor, Discussion, Chat and File nodes and want to display a different shape for each).

**Comment by eduramiba** [comment]
Closing as duplicate of #1291
