### ISSUE TITLE
Open recent files does not update

### ISSUE THREAD

**Issue by githof** [gephi/gephi#467]
Hi,

My recent files menu has not been updated for at least three or four launches of the application, which may be within a couple of weeks.

  Product Version         = Gephi 0.8 beta
  Operating System        = Mac OS X version 10.6.8 running on x86_64
  Java; VM; Vendor        = 1.6.0_26; Java HotSpot(TM) 64-Bit Server VM 20.1-b02-384; Apple Inc.
  Runtime                 = Java(TM) SE Runtime Environment 1.6.0_26-b03-384-10M3425

**Comment by mbastian** [comment]
Closing, old issue.
