### ISSUE TITLE
Partition not applicable after filtering

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#471]
The network colors are not applied after deactivating a filter.

Way to reproduce:
- Filter a network, e.g. by degree. Keep the button "Filter" activated.
- Partition a network on an attribute, and Apply.
- Deactivate the filter.
- Apply the partition again: nothing happens.

Workaround:
Select another partition parameter, than select the previous one, and apply. It is really annoying if we set custom colors to partitions, because they are lost. Btw, we should consider to add a kind of stylesheet to facilitate the design process.

**Comment by mbastian** [comment]
This is fixed in new appearance module, to be included in 0.9 release.
