### ISSUE TITLE
BOM missing in exported GEXF and .Gephi

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#474]
Gephi uses the BOM (Bite Order Mark) to detect if an imported GEXF is in UTF-8.

However the GEXF Exporter does not write the BOM, so encoding errors appear if one opens the exported file.

EDIT: this issue appear also on .gephi files. Maybe an updated lib is causing this? It is okay on Gephi 0.8 Alpha, and the code of these exporters were not been modified since then.

**Comment by mbastian** [comment]
I'm against adding the BOM to every exported file as this isn't something recommended (see here: http://unicode.org/faq/utf_bom.html#BOM) at this point. It could be an option thought.

**Comment by seinecle** [comment]
Hi,
Old issue... any fix? I try to open in Gephi, a gexf file originally created with Gephi and I have encoding issues, wondering if this comes from there.

**Comment by eduramiba** [comment]
Since XML files include the encoding in its header:

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

I think we should extend https://github.com/gephi/gephi/blob/master/modules/Utils/src/main/java/org/gephi/utils/CharsetToolkit.java `guessEncoding` to take that into account.
