### ISSUE TITLE
No way to reset workspace layout

### ISSUE THREAD

**Issue by Snurb** [gephi/gephi#480]
Hi,

there currently seems to be no functioning way to reset the layout of the Gephi workspace to the default (and dragging the tabs doesn't seem to work very well - in Overview, there is no way to drag the graph tab itself, and it seems to be impossible to drag other tabs to the right of the graph tab). 

As a stopgap, is there any other way to do a hard reset of the workspace layout to the Gephi defaults (e.g. by manually deleting or modifying a config file)? It's frustrating to have to work with a messed-up layout...

Axel Bruns

**Comment by Euphorbium** [comment]
It has been 4 years. Still no new development?

**Comment by mbastian** [comment]
Seems to work again, we're bringing it back in 0.9.
