### ISSUE TITLE
Preview Fails Silently and Randomly

### ISSUE THREAD

**Issue by emeeks** [gephi/gephi#481]
I've noticed that preview will fail to show anything on Refresh about 20% of the time and the only way for it to work is by restarting Gephi.  It happens with different graphs on my system, and there's no error that I can find.  Not a very good bug report, I know, but I'll try to find more details.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
