### ISSUE TITLE
ForceAtlas2 layout generates different result on toolkit

### ISSUE THREAD

**Issue by kaabr** [gephi/gephi#491]
Hi,

I am trying to use the toolkit with the ForceAtlas2 layout and the results are pretty different from the platform. I tried it both ways with different exporters, page sizes, parameters and multiple "goAlgo" executions. As far as I can see, YifanHu behaves ok.

The code is akin to the "simple headless example", with the modifications below:

<code>ForceAtlas2 fa2Layout = new ForceAtlas2(new ForceAtlas2Builder());
        fa2Layout.setGraphModel(graphModel);
        fa2Layout.resetPropertiesValues();
        fa2Layout.setEdgeWeightInfluence(1.0);
        fa2Layout.setGravity(1.0);
        fa2Layout.setScalingRatio(2.0);
        fa2Layout.setBarnesHutTheta(1.2);
        fa2Layout.setJitterTolerance(0.1);</code>

<code>for (int i = 0; i < 100 && fa2Layout.canAlgo(); i++) 
            fa2Layout.goAlgo();</code>

<code>PDFExporter pdfExporter = new PDFExporter();
        pdfExporter.setPageSize(PageSize.A4);
        pdfExporter.setLandscape(Boolean.FALSE);</code>

Investigating further, I noticed that YifanHuProportional has the same issue. An important observation is that I used the "buildLayout" method as follows:

<code>YifanHuProportional pLayout = new YifanHuProportional();
        YifanHuLayout layout = pLayout.buildLayout();
        layout.setGraphModel(graphModel);
        layout.resetPropertiesValues();
        layout.setOptimalDistance(400f);
        layout.setBarnesHutTheta(1.2f);
        layout.setRelativeStrength(0.5f);</code>

TIA, 

Célio.

**Comment by wetneb** [comment]
It looks like that could indeed be the cause of the issue. We can reopen this issue if that is not the case.
