### ISSUE TITLE
Case sensitivity option

### ISSUE THREAD

**Issue by Snurb** [gephi/gephi#499]
Hi,

is there any chance of adding a switch in Gephi to make it treat node names/IDs/labels as case-sensitive (or not) ? 

Currently, names are case-sensitive by default - 'NodeX' is seen as different from 'nodex'. In many cases, this is undesirable: in working with my Twitter datasets, for example, I'm often dealing with data where various capitalisations of usernames are present (and used interchangeably).

Switching Gephi to be case-insensitive would be especially useful for the node/edge import functions in the Data Laboratory, to avoid creating additional nodes when layering multiple datasets with different capitalisations on top of one another.

Thanks,

Axel Bruns

**Comment by DGScofield** [comment]
Hello there,
Is the merge ignoring text case feature available in the current version (0.9.2)? Where is it located?

**Comment by eduramiba** [comment]
@DGScofield Yes, go to data laboratory, click on "More actions" and then "Detect and merge node duplicates"
