### ISSUE TITLE
Problem starting Gephi

### ISSUE THREAD

**Issue by tobywuan** [gephi/gephi#501]
This is the error report given in the log file. PLEASE HELP - e-mail please j.se.tobon.conde@gmail.com

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000077030895, pid=4500, tid=3440
#
# JRE version: 7.0_02-b13
# Java VM: Java HotSpot(TM) 64-Bit Server VM (22.0-b10 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ntdll.dll+0x50895]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x0000000008a3f800):  JavaThread "main" [_thread_in_Java, id=3440, stack(0x00000000097b0000,0x00000000098b0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0xffffffffffffffff

Registers:
RAX=0x00000000098ae9a8, RBX=0x0000000000000002, RCX=0x00000000098aea78, RDX=0x00000000098ae9e8
RSP=0x00000000098ae998, RBP=0x000007fee8c68430, RSI=0x0000000000000020, RDI=0x0000000000000000
R8 =0x00000000098a6000, R9 =0x0000000000000003, R10=0x0000000000000000, R11=0x000000000000451a
R12=0x0000000000000000, R13=0x0000000000000050, R14=0x0000000000000003, R15=0x0000000008a3f800
RIP=0x0000000077030895, EFLAGS=0x0000000000010202

Top of Stack: (sp=0x00000000098ae998)
0x00000000098ae998:   0000000000000202 0000000076feb239
0x00000000098ae9a8:   000007fffff8e000 00000000098aeb01
0x00000000098ae9b8:   0000000000000000 00000000098aeba0
0x00000000098ae9c8:   0000000000000000 000000000000000b
0x00000000098ae9d8:   0000000008988690 0000000000000001
0x00000000098ae9e8:   00000000098b0000 00000000098a6000
0x00000000098ae9f8:   00000000029c743a 00000000029c73d0
0x00000000098aea08:   0000000000000000 0000000000000000
0x00000000098aea18:   00000000098af200 00000000098af2b0
0x00000000098aea28:   00000000029961b4 0000000002995350
0x00000000098aea38:   0000000000000000 0000000061c814b6
0x00000000098aea48:   00000000098af2b0 00000000098af230
0x00000000098aea58:   0000be42557bf258 0000000002a08750
0x00000000098aea68:   0000000008a3db70 0000000061c81aab
0x00000000098aea78:   00000000098aebd8 00000000dae3d887
0x00000000098aea88:   00000000000000b6 000000000660c370 

Instructions: (pc=0x0000000077030895)
0x0000000077030875:   d0 00 00 00 4c 89 a1 d8 00 00 00 4c 89 a9 e0 00
0x0000000077030885:   00 00 4c 89 b1 e8 00 00 00 4c 89 b9 f0 00 00 00
0x0000000077030895:   0f ae 81 00 01 00 00 0f 29 81 a0 01 00 00 0f 29
0x00000000770308a5:   89 b0 01 00 00 0f 29 91 c0 01 00 00 0f 29 99 d0 

Register to memory mapping:

RAX=0x00000000098ae9a8 is pointing into the stack for thread: 0x0000000008a3f800
RBX=0x0000000000000002 is an unknown value
RCX=0x00000000098aea78 is pointing into the stack for thread: 0x0000000008a3f800
RDX=0x00000000098ae9e8 is pointing into the stack for thread: 0x0000000008a3f800
RSP=0x00000000098ae998 is pointing into the stack for thread: 0x0000000008a3f800
RBP=0x000007fee8c68430 is an unknown value
RSI=0x0000000000000020 is an unknown value
RDI=0x0000000000000000 is an unknown value
R8 =0x00000000098a6000 is pointing into the stack for thread: 0x0000000008a3f800
R9 =0x0000000000000003 is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x000000000000451a is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000050 is an unknown value
R14=0x0000000000000003 is an unknown value
R15=0x0000000008a3f800 is a thread

Stack: [0x00000000097b0000,0x00000000098b0000],  sp=0x00000000098ae998,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ntdll.dll+0x50895]  RtlCaptureContext+0x85

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
v  blob 0x00000000029c74ff
j  java.util.Properties$LineReader.readLine()I+62
j  java.util.Properties.load0(Ljava/util/Properties$LineReader;)V+7
j  java.util.Properties.load(Ljava/io/InputStream;)V+10
j  java.util.logging.LogManager.readConfiguration(Ljava/io/InputStream;)V+13
j  org.netbeans.core.startup.TopLogging.<init>()V+139
j  org.netbeans.core.startup.TopLogging.initialize(Z)V+67
j  org.netbeans.core.startup.TopLogging.initialize()V+1
j  org.netbeans.core.startup.CLIOptions.initialize()V+0
j  org.netbeans.core.startup.Main.start([Ljava/lang/String;)V+92
j  org.netbeans.core.startup.TopThreadGroup.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
=>0x0000000008a3f800 JavaThread "main" [_thread_in_Java, id=3440, stack(0x00000000097b0000,0x00000000098b0000)]
  0x0000000008633000 JavaThread "Secure CLI Port" daemon [_thread_in_native, id=1632, stack(0x0000000009420000,0x0000000009520000)]
  0x00000000089fe000 JavaThread "CLI Requests Server" daemon [_thread_in_native, id=212, stack(0x0000000009580000,0x0000000009680000)]
  0x0000000008343000 JavaThread "Active Reference Queue Daemon" daemon [_thread_blocked, id=4780, stack(0x0000000007d80000,0x0000000007e80000)]
  0x000000000828e800 JavaThread "Timer-0" daemon [_thread_blocked, id=4456, stack(0x0000000007730000,0x0000000007830000)]
  0x000000000661c000 JavaThread "Service Thread" daemon [_thread_blocked, id=3796, stack(0x0000000007ea0000,0x0000000007fa0000)]
  0x000000000661b000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=4784, stack(0x0000000007c10000,0x0000000007d10000)]
  0x0000000006616000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=4388, stack(0x00000000072b0000,0x00000000073b0000)]
  0x0000000006613800 JavaThread "Attach Listener" daemon [_thread_blocked, id=3916, stack(0x0000000007a20000,0x0000000007b20000)]
  0x0000000006608000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=4540, stack(0x0000000007850000,0x0000000007950000)]
  0x0000000006509000 JavaThread "Finalizer" daemon [_thread_blocked, id=4744, stack(0x0000000006eb0000,0x0000000006fb0000)]
  0x0000000006501800 JavaThread "Reference Handler" daemon [_thread_blocked, id=4872, stack(0x0000000006d10000,0x0000000006e10000)]
  0x000000000223c000 JavaThread "main" [_thread_blocked, id=2780, stack(0x00000000027d0000,0x00000000028d0000)]

Other Threads:
  0x00000000064ed800 VMThread [stack: 0x0000000006ae0000,0x0000000006be0000] [id=4448]
  0x0000000007fc3000 WatcherThread [stack: 0x0000000008460000,0x0000000008560000] [id=4408]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap
 PSYoungGen      total 19136K, used 5602K [0x00000000f5560000, 0x00000000f6ab0000, 0x0000000100000000)
  eden space 16448K, 34% used [0x00000000f5560000,0x00000000f5ad8bb8,0x00000000f6570000)
  from space 2688K, 0% used [0x00000000f6810000,0x00000000f6810000,0x00000000f6ab0000)
  to   space 2688K, 0% used [0x00000000f6570000,0x00000000f6570000,0x00000000f6810000)
 PSOldGen        total 43712K, used 0K [0x00000000e0000000, 0x00000000e2ab0000, 0x00000000f5560000)
  object space 43712K, 0% used [0x00000000e0000000,0x00000000e0000000,0x00000000e2ab0000)
 PSPermGen       total 21248K, used 5197K [0x00000000dae00000, 0x00000000dc2c0000, 0x00000000e0000000)
  object space 21248K, 24% used [0x00000000dae00000,0x00000000db313558,0x00000000dc2c0000)

Code Cache  [0x0000000002990000, 0x0000000002c00000, 0x0000000005990000)
 total_blobs=257 nmethods=32 adapters=178 free_code_cache=48670Kb largest_free_block=49818752

Dynamic libraries:
0x000000013f750000 - 0x000000013f783000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\javaw.exe
0x0000000076fe0000 - 0x0000000077189000 	C:\Windows\SYSTEM32\ntdll.dll
0x0000000076b60000 - 0x0000000076c7f000 	C:\Windows\system32\kernel32.dll
0x000007fefd6e0000 - 0x000007fefd74c000 	C:\Windows\system32\KERNELBASE.dll
0x000007fefe3c0000 - 0x000007fefe49b000 	C:\Windows\system32\ADVAPI32.dll
0x000007fefe320000 - 0x000007fefe3bf000 	C:\Windows\system32\msvcrt.dll
0x000007fefd940000 - 0x000007fefd95f000 	C:\Windows\SYSTEM32\sechost.dll
0x000007fefdd40000 - 0x000007fefde6d000 	C:\Windows\system32\RPCRT4.dll
0x0000000076900000 - 0x00000000769fa000 	C:\Windows\system32\USER32.dll
0x000007fefd960000 - 0x000007fefd9c7000 	C:\Windows\system32\GDI32.dll
0x000007fefe130000 - 0x000007fefe13e000 	C:\Windows\system32\LPK.dll
0x000007fefd870000 - 0x000007fefd939000 	C:\Windows\system32\USP10.dll
0x000007fefbe40000 - 0x000007fefc034000 	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_fa396087175ac9ac\COMCTL32.dll
0x000007fefe030000 - 0x000007fefe0a1000 	C:\Windows\system32\SHLWAPI.dll
0x000007fefd310000 - 0x000007fefd367000 	C:\Windows\system32\apphelp.dll
0x000007fef4850000 - 0x000007fef48aa000 	C:\Windows\AppPatch\AppPatch64\AcLayers.DLL
0x000007fef5ec0000 - 0x000007fef5f31000 	C:\Windows\system32\WINSPOOL.DRV
0x000007fef9180000 - 0x000007fef9198000 	C:\Windows\system32\MPR.dll
0x000007fee8bf0000 - 0x000007fee9057000 	C:\Windows\AppPatch\AppPatch64\AcXtrnal.DLL
0x000007feeeb00000 - 0x000007feeeb51000 	C:\Windows\AppPatch\AppPatch64\AcGenral.DLL
0x000007fefd2e0000 - 0x000007fefd305000 	C:\Windows\system32\SspiCli.dll
0x000007fefda50000 - 0x000007fefdc53000 	C:\Windows\system32\ole32.dll
0x000007fefe4a0000 - 0x000007feff228000 	C:\Windows\system32\SHELL32.dll
0x0000000073e50000 - 0x0000000073e53000 	C:\Windows\system32\sfc.dll
0x000007fef98e0000 - 0x000007fef98f0000 	C:\Windows\system32\sfc_os.DLL
0x000007fefc780000 - 0x000007fefc79e000 	C:\Windows\system32\USERENV.dll
0x000007fefd440000 - 0x000007fefd44f000 	C:\Windows\system32\profapi.dll
0x000007fefc6e0000 - 0x000007fefc6f8000 	C:\Windows\system32\dwmapi.dll
0x000007fefda20000 - 0x000007fefda4e000 	C:\Windows\system32\IMM32.DLL
0x000007fefde70000 - 0x000007fefdf79000 	C:\Windows\system32\MSCTF.dll
0x00000000621a0000 - 0x0000000062271000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\msvcr100.dll
0x0000000061ac0000 - 0x000000006219a000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\server\jvm.dll
0x000007fefa8d0000 - 0x000007fefa8d9000 	C:\Windows\system32\WSOCK32.dll
0x000007fefd9d0000 - 0x000007fefda1d000 	C:\Windows\system32\WS2_32.dll
0x000007fefe020000 - 0x000007fefe028000 	C:\Windows\system32\NSI.dll
0x000007fefb260000 - 0x000007fefb29b000 	C:\Windows\system32\WINMM.dll
0x00000000771b0000 - 0x00000000771b7000 	C:\Windows\system32\PSAPI.DLL
0x0000000065ca0000 - 0x0000000065caf000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\verify.dll
0x00000000627d0000 - 0x00000000627f8000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\java.dll
0x00000000627b0000 - 0x00000000627c5000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\zip.dll
0x000007fefd370000 - 0x000007fefd37f000 	C:\Windows\system32\CRYPTBASE.dll
0x000007fefbcb0000 - 0x000007fefbd06000 	C:\Windows\system32\uxtheme.dll
0x000007fefdc60000 - 0x000007fefdd37000 	C:\Windows\system32\OLEAUT32.dll
0x000007fefe140000 - 0x000007fefe317000 	C:\Windows\system32\SETUPAPI.dll
0x000007fefd4f0000 - 0x000007fefd526000 	C:\Windows\system32\CFGMGR32.dll
0x000007fefd750000 - 0x000007fefd76a000 	C:\Windows\system32\DEVOBJ.dll
0x000007feff250000 - 0x000007feff2e9000 	C:\Windows\system32\CLBCatQ.DLL
0x000007fefb7b0000 - 0x000007fefb8dc000 	C:\Windows\system32\propsys.dll
0x000007fefc2f0000 - 0x000007fefc31d000 	C:\Windows\system32\ntmarta.dll
0x000007fefd810000 - 0x000007fefd862000 	C:\Windows\system32\WLDAP32.dll
0x0000000062790000 - 0x00000000627a9000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\net.dll
0x000007fefcc70000 - 0x000007fefccc5000 	C:\Windows\system32\mswsock.dll
0x000007fefcc60000 - 0x000007fefcc67000 	C:\Windows\System32\wship6.dll
0x0000000061aa0000 - 0x0000000061ab1000 	C:\Program Files\Java\jdk1.7.0_02\jre\bin\nio.dll
0x000007fefa8f0000 - 0x000007fefa917000 	C:\Windows\system32\IPHLPAPI.DLL
0x000007fefa8e0000 - 0x000007fefa8eb000 	C:\Windows\system32\WINNSI.DLL
0x000007fefa390000 - 0x000007fefa3a8000 	C:\Windows\system32\dhcpcsvc.DLL
0x000007fefa370000 - 0x000007fefa381000 	C:\Windows\system32\dhcpcsvc6.DLL
0x000007fefccd0000 - 0x000007fefcce7000 	C:\Windows\system32\CRYPTSP.dll
0x000007fefc9d0000 - 0x000007fefca17000 	C:\Windows\system32\rsaenh.dll
0x000007fefbdc0000 - 0x000007fefbdd5000 	C:\Windows\system32\NLAapi.dll
0x000007fef5fb0000 - 0x000007fef5fc5000 	C:\Windows\system32\napinsp.dll
0x000007fef5fd0000 - 0x000007fef5fe9000 	C:\Windows\system32\pnrpnsp.dll
0x000007fefcaf0000 - 0x000007fefcb4b000 	C:\Windows\system32\DNSAPI.dll
0x000007fef5f60000 - 0x000007fef5f6b000 	C:\Windows\System32\winrnr.dll
0x000007fefc5d0000 - 0x000007fefc5d7000 	C:\Windows\System32\wshtcpip.dll
0x000007fef5fa0000 - 0x000007fef5fa8000 	C:\Windows\system32\rasadhlp.dll
0x000007fefa3c0000 - 0x000007fefa413000 	C:\Windows\System32\fwpuclnt.dll

VM Arguments:
jvm_args: -Xms64m -Xmx512m -Dsun.java2d.noddraw=true -Dsun.awt.noerasebackground=true -Dnetbeans.user.dir=C:\Windows\system32 -Djdk.home=C:\Program Files\Java\jdk1.7.0_02 -Dnetbeans.home=C:\Program Files (x86)\Gephi\platform -Dnetbeans.user= -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=\var\log\heapdump.hprof -Dnetbeans.system_http_proxy=DIRECT -Dsun.awt.keepWorkingSetOnMinimize=true -Dnetbeans.dirs=C:\Program Files (x86)\Gephi\gephi 
java_command: org/netbeans/Main --branding gephi
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
USERNAME=s136269
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows Vista , 64 bit Build 6002 Service Pack 2

CPU:total 4 (2 cores per cpu, 2 threads per core) family 6 model 42 stepping 7, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, ht

Memory: 4k page, physical 8369056k(5657680k free), swap 16736264k(13917644k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (22.0-b10) for windows-amd64 JRE (1.7.0_02-b13), built on Nov 17 2011 13:51:15 by "java_re" with unknown MS VC++:1600

time: Mon Dec 19 11:44:28 2011
elapsed time: 1 seconds

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
