### ISSUE TITLE
Chinese font not embedded in PDF output

### ISSUE THREAD

**Issue by yannis1962** [gephi/gephi#502]
I use Chinese characters in the label of my graph, using font SimSun. They display fine in gephi's interface but the font is not exported in the PDF file (so that my graph in the PDF file is completely empty of labels). The only font included in the PDF file is Helvetica.

How can I embed fonts in the PDF files produced by gephi?

Thanks in advance

**Comment by yeli0823** [comment]
你好！我想问一下这个中文pdf无法显示是怎么解决的呢？
