### ISSUE TITLE
Overview's graph area does not redraw edges automatically

### ISSUE THREAD

**Issue by neuma** [gephi/gephi#513]
Gephi 0.8 beta on Win7 64bit

When generating a dynamic graph example, the edges contain a dynamic weight attribute. Using the timeline slider, the graph gets updated and the thickness of each edge changes according to its current weight. That's cool.

However, I created a gexf file, containing a dynamic weight attribute. Using again the timeline's slider, it does not update the graph's area automagically. I need to tick one of the other buttons, e.g. "Show Hulls" to get the graph updated. The graph shows up correctly though, but the auto-redrawing is missing. What's the trick?

Update: The labels, e.g. the dynamic weight, is updated automatically.

I added an example file just in case I missed something.

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gexf xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.gexf.net/1.2draft/gexf.xsd" xmlns:ns2="http://www.gexf.net/1.2draft/viz" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <graph timeformat="double" defaultedgetype="directed" idtype="string" mode="dynamic">
        <attributes class="edge" mode="dynamic">
            <attribute id="weight" title="Count" type="float"/>
        </attributes>
        <nodes>
            <node id="11">
                <position x="1000.0" y="1000.0" z="0.0"/>
            </node>
            <node id="12">
                <position x="1000.0" y="2000.0" z="0.0"/>
            </node>
            <node id="21">
                <position x="2000.0" y="1000.0" z="0.0"/>
            </node>
            <node id="22">
                <position x="2000.0" y="2000.0" z="0.0"/>
            </node>
        </nodes>
        <edges>
            <edge id="1112" label="network link" source="11" target="12" weight="1.0">
                <attvalues>
                    <attvalue for="weight" value="116" start="0.0"/>
                    <attvalue for="weight" value="1" start="10.0"/>
                    <attvalue for="weight" value="1" start="20.0"/>
                    <attvalue for="weight" value="1" start="30.0"/>
                    <attvalue for="weight" value="1" start="40.0"/>
                    <attvalue for="weight" value="1" start="50.0"/>
                    <attvalue for="weight" value="1" start="60.0"/>
                    <attvalue for="weight" value="1" start="70.0"/>
                    <attvalue for="weight" value="1" start="80.0"/>
                    <attvalue for="weight" value="69" start="100.0"/>
                </attvalues>
            </edge>
            <edge id="1121" label="network link" source="11" target="21" weight="1.0">
                <attvalues>
                    <attvalue for="weight" value="151" start="0.0"/>
                    <attvalue for="weight" value="862" start="10.0"/>
                    <attvalue for="weight" value="652" start="20.0"/>
                    <attvalue for="weight" value="302" start="30.0"/>
                    <attvalue for="weight" value="269" start="40.0"/>
                    <attvalue for="weight" value="250" start="50.0"/>
                    <attvalue for="weight" value="119" start="60.0"/>
                    <attvalue for="weight" value="201" start="70.0"/>
                    <attvalue for="weight" value="1008" start="80.0"/>
                    <attvalue for="weight" value="1274" start="100.0"/>
                </attvalues>
            </edge>
            <edge id="1211" label="network link" source="12" target="11" weight="1.0">
                <attvalues>
                    <attvalue for="weight" value="1" start="0.0"/>
                    <attvalue for="weight" value="1" start="10.0"/>
                    <attvalue for="weight" value="1" start="20.0"/>
                    <attvalue for="weight" value="1" start="30.0"/>
                    <attvalue for="weight" value="1" start="40.0"/>
                    <attvalue for="weight" value="1" start="50.0"/>
                    <attvalue for="weight" value="1" start="60.0"/>
                    <attvalue for="weight" value="1" start="70.0"/>
                    <attvalue for="weight" value="1" start="80.0"/>
                    <attvalue for="weight" value="69" start="100.0"/>
                </attvalues>
            </edge>
            <edge id="2212" label="network link" source="22" target="12" weight="1.0">
                <attvalues>
                    <attvalue for="weight" value="1" start="0.0"/>
                    <attvalue for="weight" value="1" start="10.0"/>
                    <attvalue for="weight" value="1" start="20.0"/>
                    <attvalue for="weight" value="1" start="30.0"/>
                    <attvalue for="weight" value="215" start="40.0"/>
                    <attvalue for="weight" value="1" start="50.0"/>
                    <attvalue for="weight" value="1" start="60.0"/>
                    <attvalue for="weight" value="1" start="70.0"/>
                    <attvalue for="weight" value="1" start="80.0"/>
                    <attvalue for="weight" value="1" start="100.0"/>
                </attvalues>
            </edge>
            <edge id="2221" label="network link" source="22" target="21" weight="1.0">
                <attvalues>
                    <attvalue for="weight" value="1" start="0.0"/>
                    <attvalue for="weight" value="560" start="10.0"/>
                    <attvalue for="weight" value="503" start="20.0"/>
                    <attvalue for="weight" value="153" start="30.0"/>
                    <attvalue for="weight" value="366" start="40.0"/>
                    <attvalue for="weight" value="116" start="50.0"/>
                    <attvalue for="weight" value="116" start="60.0"/>
                    <attvalue for="weight" value="151" start="70.0"/>
                    <attvalue for="weight" value="374" start="80.0"/>
                    <attvalue for="weight" value="1" start="100.0"/>
                </attvalues>
            </edge>
        </edges>
    </graph>
</gexf>
```

and the log...

---

> Log Session: Thursday, January 19, 2012 3:21:28 PM CET
> System Info: 
>   Product Version         = Gephi 0.8 beta
>   Operating System        = Windows 7 version 6.1 running on x86
>   Java; VM; Vendor        = 1.6.0_18; Java HotSpot(TM) Server VM 16.0-b13; Sun Microsystems Inc.
>   Runtime                 = Java(TM) SE Runtime Environment 1.6.0_18-b07
>   Java Home               = C:\Program Files (x86)\Java\jdk1.6.0_18\jre
>   System Locale; Encoding = de_DE (gephi); Cp1252
>   Home Directory          = C:\Users\user
>   Current Directory       = C:\Program Files (x86)\Gephi
>   User Directory          = C:\Users\user\AppData\Roaming.gephi\dev
>   Installation            = C:\Program Files (x86)\Gephi\gephi
>                             C:\Program Files (x86)\Gephi\platform
>   Boot & Ext. Classpath   = C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\classes;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\jre\lib\ext\sunpkcs11.jar
>   Application Classpath   = C:\Program Files (x86)\Gephi\platform\lib\boot.jar;C:\Program Files (x86)\Gephi\platform\lib\org-openide-modules.jar;C:\Program Files (x86)\Gephi\platform\lib\org-openide-util-lookup.jar;C:\Program Files (x86)\Gephi\platform\lib\org-openide-util.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ar_SA.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ca.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_cs.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_de.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_es.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_fr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_in_ID.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_it.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ja.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ko.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_pl.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_pt_PT.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ro.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_ru.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_sq.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_sv.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_tr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\boot_zh_TW.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ar_SA.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ca.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_cs.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_de.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_es.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_fr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_in_ID.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_it.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ja.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ko.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_pl.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_pt_PT.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ro.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_ru.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_sq.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_sv.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_tr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-modules_zh_TW.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_ca.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_cs.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_de.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_es.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_fr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_in_ID.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_it.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_ja.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_ko.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_pl.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_ro.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_ru.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_sv.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_tr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ar_SA.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ca.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_cs.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_de.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_es.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_fr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_in_ID.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_it.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ja.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ko.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_pl.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_pt_PT.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ro.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_ru.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_sq.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_sv.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_tr.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\lib\locale\org-openide-util_zh_TW.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\lib\dt.jar;C:\Program Files (x86)\Java\jdk1.6.0_18\lib\tools.jar
> ##   Startup Classpath       = C:\Program Files (x86)\Gephi\platform\core\core.jar;C:\Program Files (x86)\Gephi\platform\core\org-openide-filesystems.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ar_SA.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ca.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_cs.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_de.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_es.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_fr.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_in_ID.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_it.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ja.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ko.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_pl.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_pt_PT.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ro.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_ru.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_sq.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_sv.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_tr.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\core\locale\core_zh_TW.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ar_SA.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ca.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_cs.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_de.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_es.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_fr.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_gl_ES.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_in_ID.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_it.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ja.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ko.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_nl_NL.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_pl.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_pt_BR.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_pt_PT.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ro.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_ru.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_sq.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_sv.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_tr.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_zh_CN.jar;C:\Program Files (x86)\Gephi\platform\core\locale\org-openide-filesystems_zh_TW.jar;C:\Program Files (x86)\Gephi\gephi\core\locale\core_gephi.jar
> 
> WARNING [org.netbeans.core.modules]: the modules [org.gephi.desktop.preview, org.gephi.ui.exporter.plugin, org.gephi.ui.filters.plugin, org.gephi.ui.statistics.plugin] use org.jdesktop.layout which is deprecated: Use javax.swing.GroupLayout instead. (In form editor: select Form ... in Inspector; change Layout Generation Style to Standard Java 6 code.)
> Loading native libraries
> INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
>     org.openide.util.lookup [8.8.1 201107282000]
>     org.openide.util [8.15.1 201107282000]
>     org.openide.modules [7.23.1 201107282000]
>     org.openide.filesystems [7.47.1 201107282000]
>     org.openide.awt [7.31.2 201109141524]
>     org.netbeans.api.progress/1 [1.24.1 201107282000]
>     org.openide.dialogs [7.20.1 201107282000]
>     org.openide.nodes [7.21.1 201107282000]
>     org.openide.windows [6.40.1 201107282000]
>     org.netbeans.modules.editor.mimelookup/1 [1.22.1 201107282000]
>     org.openide.text [6.37.1 201107282000]
>     org.netbeans.swing.tabcontrol [1.25.1 201107282000]
>     org.netbeans.swing.outline [1.14.1 201107282000]
>     org.openide.explorer [6.35.1 201107282000]
>     org.openide.actions [6.22.1 201107282000]
>     org.netbeans.modules.queries/1 [1.23.1 201107282000]
>     org.openide.loaders [7.21.1 201107282000]
>     org.openide.io [1.27.1 201107282000]
>     org.netbeans.swing.plaf [1.20.2 201108310202]
>     org.netbeans.swing.dirchooser [1.1 111004]
>     org.netbeans.api.annotations.common/1 [1.9.1 201107282000]
>     org.netbeans.spi.quicksearch [1.10.1 201107282000]
>     org.netbeans.bootstrap/1 [2.40.1 201107282000]
>     org.netbeans.core.startup/1 [1.31.1 201107282000]
>     org.netbeans.modules.settings/1 [1.31.1 201107282000]
>     org.netbeans.modules.sendopts/2 [2.13.1 201107282000]
>     org.netbeans.modules.progress.ui [1.16.1 201107282000]
>     org.netbeans.modules.print [7.9.1 201107282000]
>     org.netbeans.modules.keyring [1.6.1 201107282000]
>     org.netbeans.core/2 [3.25.2 201108310202]
>     org.netbeans.modules.options.api/1 [1.22.1 201107282000]
>     org.netbeans.modules.options.keymap [1.14.1 201107282000]
>     org.netbeans.libs.jna/1 [1.14.1 201107282000]
>     org.netbeans.modules.masterfs/2 [2.32.2 201108310202]
>     org.netbeans.modules.keyring.impl [1.3.2 201108310202]
>     org.netbeans.modules.favorites/1 [1.25.1 201107282000]
>     org.netbeans.modules.editor.mimelookup.impl/1 [1.14.1 201107282000]
>     org.netbeans.modules.autoupdate.services [1.26.1 201107282000]
>     org.netbeans.modules.autoupdate.ui [1.23.1 201107282000]
>     org.netbeans.libs.junit4 [1.13 201104080000]
>     org.netbeans.core.windows/2 [2.28.1 201107282000]
>     org.netbeans.core.ui/1 [1.27.1 201107282000]
>     org.netbeans.core.nativeaccess/1 [1.12.1 201107282000]
>     org.netbeans.core.io.ui/1 [1.12.1 201107282000]
>     org.joda.time [1.0 111004]
>     org.jfree [1.0 111004]
>     org.jdesktop.swingx [1.6.1 111004]
>     org.jdesktop.layout/1 [1.17.1 201107282000]
>     org.gephi.utils.longtask [0.8.0.2 111004]
>     org.gephi.project.api [0.8.0.2 111231]
>     org.gephi.graph.api [0.8.0.3 111231]
>     org.gephi.data.attributes.api [0.8.0.4 111231]
>     org.gephi.lib.javacsv [2.0 111004]
>     org.gephi.dynamic.api [0.8.0.3 111231]
>     org.gephi.utils [0.8 111004]
>     org.gephi.datalab.api [0.8.0.8 111231]
>     org.gephi.visualization.api [0.8.0.1 111004]
>     org.gephi.tools.api [0.8.0.1 111004]
>     org.gephi.lib.validation [0.4 111004]
>     org.gephi.ui.utils [0.8 111004]
>     org.gephi.lib.gleem [1.0 111004]
>     org.gephi.lib.jogl [1.1.0.2 111004]
>     org.gephi.utils.collection [0.8.0.1 111004]
>     org.gephi.lib.flamingo [5.0.1 111004]
>     org.gephi.lib.commons.codec [1.4 111004]
>     org.gephi.ui.components [0.8.0.4 111231]
>     org.gephi.lib.commonscompress [1.1 111004]
>     org.gephi.io.database.drivers [0.8.0.2 111231]
>     org.gephi.io.importer.api [0.8.0.2 111004]
>     org.gephi.desktop.mrufiles.api [0.8 111004]
>     org.gephi.desktop.project [0.8.0.1 111004]
>     org.gephi.visualization [0.8.0.6 120101]
>     org.gephi.ui.workspace [0.8.1.0 111004]
>     org.gephi.statistics.api [0.8.1.1 111004]
>     org.gephi.statistics.plugin [0.8.0.4 111231]
>     org.gephi.ui.statistics.plugin [0.8.0.3 111004]
>     org.gephi.lib.jcalendar [1.0 111004]
>     org.gephi.lib.javamail [1.0 111004]
>     org.gephi.io.spigot.plugin [0.8.0.1 111231]
>     org.gephi.ui.spigot.plugin [0.8 111004]
>     org.gephi.ranking.api [0.8.1.2 111231]
>     org.gephi.ranking.plugin [0.8.1.1 111004]
>     org.gephi.ui.ranking.plugin [0.8.1.1 111004]
>     org.gephi.ui.propertyeditor [0.8.1 111231]
>     org.gephi.ui.project [0.8 111004]
>     org.gephi.lib.beansbinding [1.2.1 111004]
>     org.gephi.io.processor.plugin [0.8 111004]
>     org.gephi.ui.processor.plugin [0.8 111004]
>     org.gephi.partition.api [0.8 111004]
>     org.gephi.partition.plugin [0.8 111004]
>     org.gephi.ui.partition.plugin [0.8 111004]
>     org.gephi.io.importer.plugin [0.8.0.5 111004]
>     org.gephi.ui.importer.plugin [0.8.0.2 111004]
>     org.gephi.io.generator.api [0.8 111004]
>     org.gephi.io.generator.plugin [0.8.0.1 111004]
>     org.gephi.ui.generator.plugin [0.8 111004]
>     org.gephi.filters.api [0.8.0.3 111231]
>     org.gephi.timeline [0.8 111004]
>     org.gephi.filters.plugin [0.8.0.4 111231]
>     org.gephi.ui.filters.plugin [0.8.0.3 111231]
>     org.gephi.lib.itext [5.0.1 111004]
>     org.gephi.io.exporter.api [0.8 111004]
>     org.gephi.lib.batik [1.7 111004]
>     org.gephi.lib.processing [1.5.1 111004]
>     org.gephi.preview.api [0.8.1.4 120107]
>     org.gephi.io.exporter.preview [0.8.0.4 120107]
>     org.gephi.ui.exporter.preview [0.8.0.1 111004]
>     org.gephi.lib.staxutils [1.0 111004]
>     org.gephi.io.exporter.plugin [0.8.0.3 111004]
>     org.gephi.ui.exporter.plugin [0.8.0.3 111004]
>     org.gephi.lib.timing [1.1 111004]
>     org.gephi.ui.components.SplineEditor [0.8.0.1 111004]
>     org.gephi.algorithms [0.8.0.1 111231]
>     org.gephi.perspective.api [0.8 111231]
>     org.gephi.desktop.perspective [0.8.2 111231]
>     org.gephi.tools.plugin [0.8.0.2 120101]
>     org.gephi.preview.plugin [0.8.1.3 120107]
>     org.gephi.layout.api [0.8.0.1 111004]
>     org.gephi.layout.plugin [0.8.0.3 111004]
>     org.gephi.graph.dhns [0.8.0.5 111231]
>     org.gephi.filters [0.8.0.3 111231]
>     org.gephi.dynamic [0.8.0.3 111004]
>     org.gephi.desktop.welcome [0.8.0.1 111004]
>     org.gephi.desktop.tools [0.8.0.3 111004]
>     org.gephi.desktop.timeline [0.8 111004]
>     org.gephi.desktop.statistics [0.8.1 111004]
>     org.gephi.desktop.spigot [0.8 111004]
>     org.gephi.desktop.recentfiles [1.0.1 111004]
>     org.gephi.desktop.ranking [0.8.1.2 120101]
>     org.gephi.desktop.progress [0.8.0.3 111004]
>     org.gephi.desktop.io.export [0.8.0.1 111004]
>     org.gephi.desktop.preview [0.8.1.3 120107]
>     org.gephi.desktop.partition [0.8 111004]
>     org.gephi.desktop.layout [0.8.0.3 120101]
>     org.gephi.desktop.importer [0.8.0.1 111004]
>     org.gephi.desktop.hierarchy [0.8 111004]
>     org.gephi.desktop.generate [0.8 111004]
>     org.gephi.desktop.filters [0.8.0.1 120101]
>     org.gephi.desktop.datalab [0.8.0.7 120101]
>     org.gephi.desktop.context [0.8 111004]
>     org.gephi.clustering.api [0.8 111004]
>     org.gephi.desktop.clustering [0.8 111004]
>     org.gephi.datalab.plugin [0.8.0.8 120101]
>     org.gephi.data.attributes [0.8.0.2 111231]
>     org.gephi.clustering.plugin [0.8 111004]
>     org.gephi.branding.desktop [0.8.0.6 120101]
> org.netbeans.core.windows.view.ui.MainWindow$4[null.nbGlassPane,0,0,0x0,invalid,hidden,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]
> GL_VENDOR: NVIDIA Corporation
> GL_RENDERER: Quadro FX 770M/PCI/SSE2
> GL_VERSION: 3.0.0
> Diagnostic information
> Input arguments:
>     -Xms64m
>     -Xmx512m
>     -Dsun.java2d.noddraw=true
>     -Dsun.awt.noerasebackground=true
>     -Dnetbeans.user.dir=F:\p_run
>     -Djdk.home=C:\Program
>     Files
>     (x86)\Java\jdk1.6.0_18
>     -splash:C:\Users\user\AppData\Roaming.GEPHI\dev\var\cache\splash.png
>     -Dnetbeans.home=C:\Program
>     Files
>     (x86)\Gephi\platform
>     -Dnetbeans.user=C:\Users\user\AppData\Roaming.GEPHI\dev
>     -XX:+HeapDumpOnOutOfMemoryError
>     -XX:HeapDumpPath=C:\Users\user\AppData\Roaming.GEPHI\dev\var\log\heapdump.hprof
>     -Dnetbeans.system_http_proxy=DIRECT
>     -Dsun.awt.keepWorkingSetOnMinimize=true
>     -Dnetbeans.dirs=C:\Program
>     Files
>     (x86)\Gephi\gephi
> Compiler: HotSpot Tiered Compilers
> Heap memory usage: initial 64,0MB maximum 455,1MB
> Non heap memory usage: initial 18,2MB maximum 112,0MB
> Garbage collector: PS Scavenge (Collections=3 Total time spent=0s)
> Garbage collector: PS MarkSweep (Collections=0 Total time spent=0s)
> Classes: loaded=4907 total loaded=4907 unloaded 0
> INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 4.294.967.295
> INFO [null]: Gesamter physischer Speicher 4.294.967.295
> WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/Window/ marked with the position attribute: [TimelineAction.shadow], but some are: [ClusteringAction.shadow, ContextAction.shadow, DataTableAction.shadow, FiltersAction.shadow, GraphAction.shadow, HierarchyAction.shadow, LayoutAction.shadow, PartitionAction.shadow, PreviewAction.shadow, PreviewSettingsAction.shadow, RankingAction.shadow, StatisticsAction.shadow, WelcomeAction.shadow, Separator3.instance, CloseWindowAction.shadow, MaximizeWindowAction.shadow, org-netbeans-core-windows-actions-UndockAction.shadow, Separator4.instance, Separator4_1.instance]
> # Nodes loaded: 4
> # Edges loaded: 5
> 
> WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_desktop_update_center.instance: url_key attribute deprecated in favor of url
> WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_desktop_update_center_1.instance: url_key attribute deprecated in favor of url

**Comment by spmallette** [comment]
According to the label, this issue was fixed for 0.8.1.  i'm using 0.8.2 and see a similar issue with the streaming plugin when sending edge updates - the "Overview" doesn't refresh unless I manually do it (e.g. clicking the "Show Hulls" button).  This might be an unrelated issue and perhaps related to the streaming plugin, but I thought I'd start by just commenting here first - any guidance?
