### ISSUE TITLE
Suggestions: improvements to spreadsheet import

### ISSUE THREAD

**Issue by arc12** [gephi/gephi#532]
These are some small points but each time I import they make me think "this could be more smooth", less effort and less likely that I make a mistake.
1. for node import, the weight has default type = String. Suggest: it should default to float since weight will normally be a continuous numeric value
2.  When importing either a nodes or edges CSV, use the column heading names to automatically select the correct value for "As table:" drop-down when a CSV file is chosen.

Gephi is great, many thanks.

Adam

**Comment by jbliesener** [comment]
As this is still open, can I just submit a suggestion? When detecting column types, maybe, we also could implement some heuristics and use the column names to detect whether the spreadsheet represents nodes or edges. "Source" and "Target" or "From" and "To" clearly represent edges, while a spreadsheet with less than three columns only can contain nodes.

**Comment by eduramiba** [comment]
This is being implemented in #1282 :)

**Comment by eduramiba** [comment]
Can you please try the latest nightly build (https://github.com/gephi/gephi#nightly-builds)? It should include these changes

**Comment by wraybowling** [comment]
I can confirm that the nightly build works at importing CSVs in the matrix format

**Comment by eduramiba** [comment]
Great!
