### ISSUE TITLE
Edge filter reduces displayed thickness of UNfiltered edges

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#538]
Briefly, if you are displaying edges of different thickness according to weight and apply an edge weight filter, some of the edges that are NOT filtered nevertheless get reduced in thickness. The filter should simply remove the filtered items, not change the display of unfiltered items. 

In more detail: Lacking the ability to put attachments here, I need you to step through this to reproduce. Load this VNA (or any graph with various weights on edges): 

    *Node data
    ID
    1
    2
    3
    4
    5

    *Tie data
    FROM TO strength
    1 2 1
    1 3 2
    1 4 4
    1 5 8

Lay it out so the nodes are distinct and set the display to show the edges with different thicknesses. 

Now create an edge weight filter (dragging Edges/Edge Weight into Queries). 

If you apply the filter to remove edges of weight 1 or 2, the edges of weight 8 stay the same thickness but the other UNfiltered edges get thinner, making them appear as if they have lower weight than in the original display. 

This is obviously the wrong behavior -- the filter should simply drop the items not meeting the criteria, not change the display of those that do -- and it makes it hard to use the filter to discern structure that one then sees in the original graph. 

Thanks again, 
Dan

**Comment by mbastian** [comment]
This is now fixed and it will be released as part of the 0.9 version. The edge weight thickness is based on a rescaling that requires to know the min/max weight values. Gephi formerly updated these bounds based on the visible graph rather than the main graph. We now only update bounds based on the main graph.
