### ISSUE TITLE
Data laboratory max columns unintuitive

### ISSUE THREAD

**Issue by kijoshua** [gephi/gephi#590]
I was about to submit a bug about how the data laboratory couldn't access more than 20 columns.  Clicking on the "grid with a wand button" only listed the first 20 fields in my dataset.  Same issue when right clicking the column headers.  But then I clicked on the "lightbulb with a plus sign on it" and discovered yet another "choose columns" bit, this time showing all the fields.  

That's 3 ways to change the visible columns, two of which only show the "current 20" and fail to provide any indication that to get at the rest you need to find the third approach.  

Perhaps a "choose more columns" entry in the first two approaches, as a shortcut to the third approach, would be a simple fix.  Maybe eventually remove the column limit and add a horizontal scroll bar.

**Comment by chomwitt** [comment]
As a new user i found about the table headers limit 3-4 days after starting learning gephi!!
Interestingly two Packt books dont mention that! (i hope they give a good sales part to the project because it seems is in disintegration phase)
