### ISSUE TITLE
Graphical Crash

### ISSUE THREAD

**Issue by thrainng** [gephi/gephi#591]
Contents of logfile:

A fatal error has been detected by the Java Runtime Environment:

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x5b12e7c1, pid=1476, tid=5372

JRE version: 6.0_29-b11
Java VM: Java HotSpot(TM) Client VM (20.4-b02 mixed mode, sharing windows-x86 )
Problematic frame:
C  [aticfx32.dll+0x2e7c1]

If you would like to submit a bug report, please visit:
  http://java.sun.com/webapps/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x06588800):  JavaThread "AWT-EventQueue-1" [_thread_in_native, id=5372, stack(0x09060000,0x09260000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x00000140

Registers:
EAX=0x00000008, EBX=0x0925e85c, ECX=0x0000000b, EDX=0x00000000
ESP=0x0925de50, EBP=0x0925de5c, ESI=0x0c132898, EDI=0x0c1307d0
EIP=0x5b12e7c1, EFLAGS=0x00010202

Top of Stack: (sp=0x0925de50)
0x0925de50:   0925e85c 0c1307d0 0925e85c 0925e7f0
0x0925de60:   5b12ce9c 400000c0 5e658344 01f3da78
0x0925de70:   02100210 400000c0 00000000 0925de88
0x0925de80:   00000960 400000c0 00000001 08e70000
0x0925de90:   0000000b 00000002 00000008 00000008
0x0925dea0:   0144f27d 00002471 00000001 00000001
0x0925deb0:   0000f5c3 00000001 00001b95 00005ffc
0x0925dec0:   00000001 d80805ff 00000206 03f6fd3d 

Instructions: (pc=0x5b12e7c1)
0x5b12e7a1:   5b 68 88 00 00 00 6a 08 52 8b f8 ff 15 b4 60 15
0x5b12e7b1:   5b 8b f0 85 f6 74 1b 8b 47 24 8b 4f 14 83 c0 08
0x5b12e7c1:   8b 80 38 01 00 00 50 8b c7 e8 21 ff ff ff 8b f0
0x5b12e7d1:   eb 02 33 f6 8b fe e8 74 4e 01 00 85 c0 7c 1d 53 

Register to memory mapping:

EAX=0x00000008 is an unknown value
EBX=0x0925e85c is pointing into the stack for thread: 0x06588800
ECX=0x0000000b is an unknown value
EDX=0x00000000 is an unknown value
ESP=0x0925de50 is pointing into the stack for thread: 0x06588800
EBP=0x0925de5c is pointing into the stack for thread: 0x06588800
ESI=0x0c132898 is an unknown value
EDI=0x0c1307d0 is an unknown value

Stack: [0x09060000,0x09260000],  sp=0x0925de50,  free space=2039k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [aticfx32.dll+0x2e7c1]  gslCfxExit+0xe1
C  [aticfx32.dll+0x2ce9c]  OpenAdapter+0xdfcc
C  [atigktxx.dll+0x4fe4]  XopOpenLinkedAdapter+0xa44
C  [atigktxx.dll+0x1689]  SetThunkProxyBypassMode+0x33f

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.opengl.impl.windows.WGL.ChoosePixelFormat0(JLjava/nio/ByteBuffer;)I+0
j  com.sun.opengl.impl.windows.WGL.ChoosePixelFormat(JLcom/sun/opengl/impl/windows/PIXELFORMATDESCRIPTOR;)I+13
j  com.sun.opengl.impl.windows.WindowsDummyGLDrawable.<init>()V+93
j  com.sun.opengl.impl.windows.WindowsGLDrawable.choosePixelFormat(Z)V+160
j  com.sun.opengl.impl.windows.WindowsOnscreenGLDrawable.lockSurface()I+230
j  com.sun.opengl.impl.windows.WindowsOnscreenGLContext.makeCurrentImpl()I+4
j  com.sun.opengl.impl.GLContextImpl.makeCurrent()I+56
j  com.sun.opengl.impl.GLDrawableHelper.invokeGL(Ljavax/media/opengl/GLDrawable;Ljavax/media/opengl/GLContext;Ljava/lang/Runnable;Ljava/lang/Runnable;)V+308
j  javax.media.opengl.GLCanvas.maybeDoSingleThreadedWorkaround(Ljava/lang/Runnable;Ljava/lang/Runnable;)V+36
j  javax.media.opengl.GLCanvas.display()V+9
j  javax.media.opengl.GLCanvas.paint(Ljava/awt/Graphics;)V+125
j  sun.awt.RepaintArea.paintComponent(Ljava/awt/Component;Ljava/awt/Graphics;)V+6
j  sun.awt.RepaintArea.paint(Ljava/lang/Object;Z)V+326
j  sun.awt.windows.WComponentPeer.handleEvent(Ljava/awt/AWTEvent;)V+107
j  java.awt.Component.dispatchEventImpl(Ljava/awt/AWTEvent;)V+853
j  java.awt.Component.dispatchEvent(Ljava/awt/AWTEvent;)V+2
j  java.awt.EventQueue.dispatchEventImpl(Ljava/awt/AWTEvent;Ljava/lang/Object;)V+41
j  java.awt.EventQueue.access$000(Ljava/awt/EventQueue;Ljava/awt/AWTEvent;Ljava/lang/Object;)V+3
j  java.awt.EventQueue$1.run()Ljava/lang/Void;+12
j  java.awt.EventQueue$1.run()Ljava/lang/Object;+1
v  ~StubRoutines::call_stub
J  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object;
j  java.security.AccessControlContext$1.doIntersectionPrivilege(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;Ljava/security/AccessControlContext;)Ljava/lang/Object;+28
j  java.security.AccessControlContext$1.doIntersectionPrivilege(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object;+6
j  java.awt.EventQueue$2.run()Ljava/lang/Void;+11
j  java.awt.EventQueue$2.run()Ljava/lang/Object;+1
v  ~StubRoutines::call_stub
J  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;)Ljava/lang/Object;
j  java.security.AccessControlContext$1.doIntersectionPrivilege(Ljava/security/PrivilegedAction;Ljava/security/AccessControlContext;Ljava/security/AccessControlContext;)Ljava/lang/Object;+28
j  java.awt.EventQueue.dispatchEvent(Ljava/awt/AWTEvent;)V+73
j  org.netbeans.core.TimableEventQueue.dispatchEvent(Ljava/awt/AWTEvent;)V+17
j  java.awt.EventDispatchThread.pumpOneEventForFilters(I)Z+204
j  java.awt.EventDispatchThread.pumpEventsForFilter(ILjava/awt/Conditional;Ljava/awt/EventFilter;)V+30
j  java.awt.EventDispatchThread.pumpEventsForHierarchy(ILjava/awt/Conditional;Ljava/awt/Component;)V+11
j  java.awt.EventDispatchThread.pumpEvents(ILjava/awt/Conditional;)V+4
j  java.awt.EventDispatchThread.pumpEvents(Ljava/awt/Conditional;)V+3
j  java.awt.EventDispatchThread.run()V+9
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0658a800 JavaThread "Keep-Alive-Timer" daemon [_thread_blocked, id=5272, stack(0x0afe0000,0x0b1e0000)]
  0x0658a000 JavaThread "Dynamic Model EventDispatchThread" daemon [_thread_blocked, id=6844, stack(0x07570000,0x07770000)]
  0x06589c00 JavaThread "Flushing caches" [_thread_blocked, id=2648, stack(0x094e0000,0x096e0000)]
  0x06589400 JavaThread "Inactive RequestProcessor thread [Was:Folder recognizer/org.openide.loaders.FolderList$ListTask]" daemon [_thread_blocked, id=3896, stack(0x092a0000,0x094a0000)]
  0x06589000 JavaThread "TimerQueue" daemon [_thread_blocked, id=6456, stack(0x08220000,0x08420000)]
=>0x06588800 JavaThread "AWT-EventQueue-1" [_thread_in_native, id=5372, stack(0x09060000,0x09260000)]
  0x06588000 JavaThread "Thread-2" daemon [_thread_blocked, id=2100, stack(0x08e60000,0x09060000)]
  0x06587c00 JavaThread "Image Fetcher 0" daemon [_thread_blocked, id=4560, stack(0x08c60000,0x08e60000)]
  0x0645fc00 JavaThread "AWT-Windows" daemon [_thread_in_native, id=4360, stack(0x08020000,0x08220000)]
  0x0643f000 JavaThread "AWT-Shutdown" [_thread_blocked, id=3252, stack(0x07e20000,0x08020000)]
  0x0643bc00 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=3564, stack(0x07c20000,0x07e20000)]
  0x0638a800 JavaThread "Inactive RequestProcessor thread [Was:System clipboard synchronizer/org.netbeans.NbClipboard]" daemon [_thread_blocked, id=5884, stack(0x07330000,0x07530000)]
  0x0638a000 JavaThread "CLI Requests Server" daemon [_thread_in_native, id=4756, stack(0x07130000,0x07330000)]
  0x06388800 JavaThread "Active Reference Queue Daemon" daemon [_thread_blocked, id=4936, stack(0x06bd0000,0x06dd0000)]
  0x05b7d000 JavaThread "RequestProcessor queue manager" daemon [_thread_blocked, id=5564, stack(0x05d90000,0x05f90000)]
  0x020b8000 JavaThread "Low Memory Detector" daemon [_thread_blocked, id=764, stack(0x05710000,0x05910000)]
  0x020ab400 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=3864, stack(0x054d0000,0x056d0000)]
  0x020aa400 JavaThread "Attach Listener" daemon [_thread_blocked, id=668, stack(0x05290000,0x05490000)]
  0x020a9400 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=5660, stack(0x05050000,0x05250000)]
  0x0209dc00 JavaThread "Finalizer" daemon [_thread_blocked, id=1860, stack(0x04e10000,0x05010000)]
  0x0209c400 JavaThread "Reference Handler" daemon [_thread_blocked, id=6616, stack(0x04c10000,0x04e10000)]
  0x0220dc00 JavaThread "main" [_thread_blocked, id=6472, stack(0x00090000,0x00290000)]

Other Threads:
  0x02060c00 VMThread [stack: 0x04a10000,0x04c10000] [id=848]
  0x020c9400 WatcherThread [stack: 0x05950000,0x05b50000] [id=4852]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap
 def new generation   total 19712K, used 14929K [0x14570000, 0x15ad0000, 0x1f010000)
  eden space 17536K,  76% used [0x14570000, 0x1528ada8, 0x15690000)
  from space 2176K,  69% used [0x158b0000, 0x15a298f0, 0x15ad0000)
  to   space 2176K,   0% used [0x15690000, 0x15690000, 0x158b0000)
 tenured generation   total 43712K, used 16209K [0x1f010000, 0x21ac0000, 0x34570000)
   the space 43712K,  37% used [0x1f010000, 0x1ffe4648, 0x1ffe4800, 0x21ac0000)
 compacting perm gen  total 20480K, used 20334K [0x34570000, 0x35970000, 0x38570000)
   the space 20480K,  99% used [0x34570000, 0x3594bad8, 0x3594bc00, 0x35970000)
    ro space 10240K,  51% used [0x38570000, 0x38a9d0b8, 0x38a9d200, 0x38f70000)
    rw space 12288K,  54% used [0x38f70000, 0x39609570, 0x39609600, 0x39b70000)

Code Cache  [0x028e0000, 0x02bc0000, 0x048e0000)
 total_blobs=1743 nmethods=1361 adapters=315 free_code_cache=30545536 largest_free_block=320

Dynamic libraries:
0x00400000 - 0x00468000 	C:\Program Files (x86)\Gephi\bin\gephi.exe
0x77810000 - 0x77990000 	C:\WINDOWS\SysWOW64\ntdll.dll
0x753d0000 - 0x754e0000 	C:\WINDOWS\syswow64\kernel32.dll
0x773c0000 - 0x77406000 	C:\WINDOWS\syswow64\KERNELBASE.dll
0x76e50000 - 0x76efc000 	C:\WINDOWS\syswow64\msvcrt.dll
0x77100000 - 0x771a0000 	C:\WINDOWS\syswow64\ADVAPI32.DLL
0x76bd0000 - 0x76be9000 	C:\WINDOWS\SysWOW64\sechost.dll
0x76530000 - 0x76620000 	C:\WINDOWS\syswow64\RPCRT4.dll
0x75370000 - 0x753d0000 	C:\WINDOWS\syswow64\SspiCli.dll
0x75360000 - 0x7536c000 	C:\WINDOWS\syswow64\CRYPTBASE.dll
0x77230000 - 0x77330000 	C:\WINDOWS\syswow64\USER32.dll
0x767b0000 - 0x76840000 	C:\WINDOWS\syswow64\GDI32.dll
0x76bc0000 - 0x76bca000 	C:\WINDOWS\syswow64\LPK.dll
0x76c00000 - 0x76c9d000 	C:\WINDOWS\syswow64\USP10.dll
0x76da0000 - 0x76e00000 	C:\WINDOWS\system32\IMM32.DLL
0x76cd0000 - 0x76d9c000 	C:\WINDOWS\syswow64\MSCTF.dll
0x10000000 - 0x1004c000 	C:\Program Files (x86)\Gephi\platform\lib\nbexec.dll
0x720d0000 - 0x7211c000 	C:\WINDOWS\system32\apphelp.dll
0x6d7f0000 - 0x6da9f000 	C:\Program Files (x86)\Java\jre6\bin\client\jvm.dll
0x74e30000 - 0x74e62000 	C:\WINDOWS\system32\WINMM.dll
0x7c340000 - 0x7c396000 	C:\Program Files (x86)\Java\jre6\bin\MSVCR71.dll
0x6d700000 - 0x6d723000 	C:\Program Files (x86)\Java\jre6\bin\splashscreen.dll
0x6d7a0000 - 0x6d7ac000 	C:\Program Files (x86)\Java\jre6\bin\verify.dll
0x6d320000 - 0x6d33f000 	C:\Program Files (x86)\Java\jre6\bin\java.dll
0x6d7e0000 - 0x6d7ef000 	C:\Program Files (x86)\Java\jre6\bin\zip.dll
0x6d600000 - 0x6d613000 	C:\Program Files (x86)\Java\jre6\bin\net.dll
0x76620000 - 0x76655000 	C:\WINDOWS\syswow64\WS2_32.dll
0x777e0000 - 0x777e6000 	C:\WINDOWS\syswow64\NSI.dll
0x74ba0000 - 0x74bdc000 	C:\WINDOWS\system32\mswsock.dll
0x72220000 - 0x72226000 	C:\WINDOWS\System32\wship6.dll
0x6d620000 - 0x6d629000 	C:\Program Files (x86)\Java\jre6\bin\nio.dll
0x745e0000 - 0x745fc000 	C:\WINDOWS\system32\iphlpapi.dll
0x745d0000 - 0x745d7000 	C:\WINDOWS\system32\WINNSI.DLL
0x72750000 - 0x7275d000 	C:\WINDOWS\system32\dhcpcsvc6.DLL
0x72730000 - 0x72742000 	C:\WINDOWS\system32\dhcpcsvc.DLL
0x74b90000 - 0x74b95000 	C:\WINDOWS\System32\wshtcpip.dll
0x745b0000 - 0x745c6000 	C:\WINDOWS\system32\CRYPTSP.dll
0x74570000 - 0x745ab000 	C:\WINDOWS\system32\rsaenh.dll
0x744f0000 - 0x74507000 	C:\WINDOWS\system32\USERENV.dll
0x74a40000 - 0x74a4b000 	C:\WINDOWS\system32\profapi.dll
0x6e410000 - 0x6e420000 	C:\WINDOWS\system32\NLAapi.dll
0x72290000 - 0x722a0000 	C:\WINDOWS\system32\napinsp.dll
0x72270000 - 0x72282000 	C:\WINDOWS\system32\pnrpnsp.dll
0x74600000 - 0x74644000 	C:\WINDOWS\system32\DNSAPI.dll
0x72260000 - 0x72268000 	C:\WINDOWS\System32\winrnr.dll
0x72230000 - 0x72251000 	C:\Program Files (x86)\Bonjour\mdnsNSP.dll
0x722a0000 - 0x722a6000 	C:\WINDOWS\system32\rasadhlp.dll
0x721e0000 - 0x72218000 	C:\WINDOWS\System32\fwpuclnt.dll
0x6d000000 - 0x6d14c000 	C:\Program Files (x86)\Java\jre6\bin\awt.dll
0x700a0000 - 0x700f1000 	C:\WINDOWS\system32\WINSPOOL.DRV
0x76f00000 - 0x7705c000 	C:\WINDOWS\syswow64\ole32.dll
0x719c0000 - 0x71a44000 	C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.17514_none_ec83dffa859149af\COMCTL32.dll
0x72130000 - 0x72143000 	C:\WINDOWS\system32\DWMAPI.DLL
0x72050000 - 0x720d0000 	C:\WINDOWS\system32\uxtheme.dll
0x6d230000 - 0x6d27f000 	C:\Program Files (x86)\Java\jre6\bin\fontmanager.dll
0x77060000 - 0x770ef000 	C:\WINDOWS\syswow64\OLEAUT32.DLL
0x754e0000 - 0x7612a000 	C:\WINDOWS\system32\shell32.dll
0x764d0000 - 0x76527000 	C:\WINDOWS\syswow64\SHLWAPI.dll
0x637c0000 - 0x637c8000 	C:\Program Files (x86)\Gephi\gephi\modules\lib\windows-i586\gluegen-rt.dll
0x08ae0000 - 0x08b2d000 	C:\Program Files (x86)\Gephi\gephi\modules\lib\windows-i586\jogl.dll
0x5b1a0000 - 0x5b268000 	C:\WINDOWS\system32\OPENGL32.dll
0x5d3b0000 - 0x5d3d2000 	C:\WINDOWS\system32\GLU32.dll
0x5c1e0000 - 0x5c2c7000 	C:\WINDOWS\system32\DDRAW.dll
0x5e470000 - 0x5e476000 	C:\WINDOWS\system32\DCIMAN32.dll
0x768f0000 - 0x76a8d000 	C:\WINDOWS\syswow64\SETUPAPI.dll
0x76b90000 - 0x76bb7000 	C:\WINDOWS\syswow64\CFGMGR32.dll
0x76790000 - 0x767a2000 	C:\WINDOWS\syswow64\DEVOBJ.dll
0x6d350000 - 0x6d356000 	C:\Program Files (x86)\Java\jre6\bin\jawt.dll
0x06ed0000 - 0x06ed5000 	C:\Program Files (x86)\Gephi\gephi\modules\lib\windows-i586\jogl_awt.dll
0x6d550000 - 0x6d559000 	C:\Program Files (x86)\Java\jre6\bin\management.dll
0x6d1a0000 - 0x6d1c3000 	C:\Program Files (x86)\Java\jre6\bin\dcpr.dll
0x6d560000 - 0x6d5f3000 	C:\Program Files (x86)\Java\jre6\bin\mlib_image.dll
0x6d780000 - 0x6d788000 	C:\Program Files (x86)\Java\jre6\bin\sunmscapi.dll
0x76670000 - 0x7678d000 	C:\WINDOWS\syswow64\CRYPT32.dll
0x76660000 - 0x7666c000 	C:\WINDOWS\syswow64\MSASN1.dll
0x0b1e0000 - 0x0bf9d000 	C:\WINDOWS\system32\ig4icd32.dll
0x5e650000 - 0x5e65b000 	C:\WINDOWS\system32\atigktxx.dll
0x751d0000 - 0x751d9000 	C:\WINDOWS\system32\VERSION.dll
0x5b100000 - 0x5b196000 	C:\WINDOWS\system32\aticfx32.dll
0x770f0000 - 0x770f5000 	C:\WINDOWS\system32\PSAPI.DLL

VM Arguments:
jvm_args: -Xms64m -Xmx512m -Dsun.java2d.noddraw=true -Dsun.awt.noerasebackground=true -Dnetbeans.indexing.noFileRefresh=true -Dnetbeans.user.dir=C:\Program Files (x86)\Gephi\bin -Djdk.home=C:\Program Files (x86)\Java\jre6 -Dnetbeans.home=C:\Program Files (x86)\Gephi\platform -Dnetbeans.user=C:\Users\admin.reyniro\AppData\Roaming\.gephi\0.8.1\dev -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Users\admin.reyniro\AppData\Roaming\.gephi\0.8.1\dev\var\log\heapdump.hprof -Dnetbeans.system_http_proxy=DIRECT -Dsun.awt.keepWorkingSetOnMinimize=true -Dnetbeans.dirs=C:\Program Files (x86)\Gephi\gephi 
java_command: <unknown>
Launcher Type: generic

Environment Variables:
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\PCXTools;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\VisualSVN\bin
USERNAME=admin.reyniro
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 7 , 64 bit Build 7601 Service Pack 1

CPU:total 4 (4 cores per cpu, 1 threads per core) family 6 model 42 stepping 7, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt

Memory: 4k page, physical 8208708k(5938448k free), swap 16415568k(13706760k free)

vm_info: Java HotSpot(TM) Client VM (20.4-b02) for windows-x86 JRE (1.6.0_29-b11), built on Oct  3 2011 01:01:08 by "java_re" with MS VC++ 7.1 (VS2003)

time: Fri Apr 13 13:31:46 2012
elapsed time: 2 seconds

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
