### ISSUE TITLE
Confusing CSV imports

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#599]
File > Open and DataLab > Import Spreadsheet both import CSV files. However these files have totally different formats.

I propose to split the File > Open CSV to different file extensions for a better clarity:
- .edgelist
- .adjacency
- .mixedlist
- .matrix

See https://gephi.org/users/supported-graph-formats/csv-format/

Therefore, the name "CSV" will be reserved for the Data Lab, avoiding many confusions for users.

**Comment by eduramiba** [comment]
This is now more clear with #1155
