### ISSUE TITLE
Problems related to saving/reloading a .gephi file

### ISSUE THREAD

**Issue by rd2** [gephi/gephi#602]
Gephi 0.8.1 Beta / Linux x64 / Java 1.7

Gephi appears to have a problem closing/reloading its data files (.gephi) and this causes several follow-up issues.

1) When I work on a project, I close it (File -> Close Project), then close Gephi, then start Gephi again.
--> Gephi restarts loading the file I had closed previously. I expect that it should have "forgotten this file by now.
In this scenario, the views at least for the start are viewable, but they degrade after several times of switching.

2) When I work on a project, I close Gephi w/o first closing the project. I then restart Gephi.
--> Gephi starts and loads the file which was loaded before I closed it.

In this scenario, there are various follow-up issues which appear to be related to incorrect saving/loading of .gephi files:
- It will not display the graphs i either [Overview] or [Preview] correctly, instead, it will clutter these canvases with the background. Even after several renew attempts and switching views, no way :-( 
- The [Preview] almost never displays its contents correctly. It is either blank or cluttered. This problem is new since 0.8.1.
- The [Preview] apparently uses other fonts than the [Overview] of the Graph.
- The settings in "Presets" are always forgotten and reset after reload of the graph. It forget set fonts, sizes, colores ... and resets everything to some defaults.
- Gephi always (re)sets the fonts in [Preview] to Arial, but there is no Arial font installed on this system.
- There is no way to save a new/modified preset.
- "Refresh" will orften result in a blank preview and no way to recover from this state.
- In [Preview] there are two tabs, "Preview" and "Graph". It is not clear why the "Graph" tab is there.
- The "Show Hulls" and "Show Edge Labels" buttons seem to have no effect.
- In some cases (not clearly reproducible) the preview freezes with the wheel spinning top-left. Gephi has to be restarted.

**Comment by mbastian** [comment]
Closing old issue. Please try again with latest 0.9.0 release and open new issues if needed. Thanks.
