### ISSUE TITLE
Cluttered Preview before first Refresh

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#605]
This is a visual bug, but many users have thought it weird (me too, especially when showing demos): 

When going to Preview for the first time, the visualization panel has glitches. One click on Refresh removes the glitches, however it would greatly improve the user experience to remove this glitches, or at best to render the network automatically when the user arrives for the first time.

Notice that glitches never appear again during the execution of the Gephi instance.

**Comment by jersub** [comment]
On latest master I don't have any glitches anymore under Linux (X11, GNOME 3). Let's check with Windows and Mac OS.

**Comment by mbastian** [comment]
No problem on Mac OS on my side.

**Comment by eduramiba** [comment]
I think this is fixed in 0.9. I have not seen it happen again either.
