### ISSUE TITLE
Auto-apply on dynamic Partition

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#606]
An auto-apply button, with automatic transformation would be very important for the analysis of dynamical networks. This button exists for Ranking, but not for Partition.

This is of paramount importance when looking at the evolution of communities.

However I remember that a refactoring of the Partition module and API is needed. What is our plan?

**Comment by jonathancardoso** [comment]
Hi, what is the evolution of this issue? Do you intend to provide this feature any time soon?

**Comment by mbastian** [comment]
This has been implemented in the new appearance module, shipping in 0.9 release.
