### ISSUE TITLE
HITS wrongly calculating hub value in directed graphs

### ISSUE THREAD

**Issue by tniedabylski** [gephi/gephi#620]
HITS algorithm implementation calculates hub of node X as sum of authorities of nodes pointing to node X. Instead, it should be sum of authorities the node X points to.
This bug results in hubs and authorties having same, wrong values in directed graphs. As HITS on undirected graphs makes little sense, this renders the algorithm practically useless.

Possible solution (I am not familiar with Gephi API though):
In StatisticsPlugin / src / org / gephi / statistics / plugin / Hits.java, line 207:
```java
temp_hubs[n_index] += authority[target_index];
```
shoulde be changed to
```java
temp_hubs[target_index] += authority[n_index];
hub_sum += authority[n_index];
```

Plus proper initialization of ```temp_hubs```

**Comment by eduramiba** [comment]
Closing old issue. See #1290
