### ISSUE TITLE
Cannot ungroup partition after applying filter

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#635]
Bad interaction between partition grouping and partition filtering ... To reproduce: 
0. Load a graph that has modularity partition computed. 
1. Using the Partition tool on the left, select Modularity Class and click on "Group" 
2. Using the Filters tool on the right, apply a modularity class filter to show just one partition. 
3. At this point, "Ungroup" has been disabled. 
* Turning the filter off does not bring "Ungroup" back in the Partition pane. 
* Re-selecting Modularity Class as the Partition brings back the label, but now it says "Group" when it should say "Ungroup". 
  - Selecting "Group" groups the groups! (Both in the graph view and data laboratory, where we now have a folder of folders.) 
  - Then it displays "Ungroup" but selecting that just takes us back to the groups, not the ungrouped graph. 

At this point I cannot recover the main graph, and I have to close the project and start over to get it back. 

Note that if you do it in the other order ...
1. Apply a modularity class filter to show just one partition. 
2. Using the Partition tool on the left, select Modularity Class and click on "Group" 
At this point, "Ungroup" is visible and you can ungroup it.  The problem is only when the filter is applied after a grouping

**Comment by mbastian** [comment]
Closing this issue as the support for grouping has been removed from now in version 0.9.1. Thanks for the report, we'll need to keep that in mind when we revisit this topic.
