### ISSUE TITLE
Cannot move view after Data Lab usage

### ISSUE THREAD

**Issue by aurelienb** [gephi/gephi#643]
After following steps, I cannot use right click to move the graph:
1. import full base from Neo4j (1.8 milestone 3)
2. ok (without modification) to traversal option
3. set partition color
4. change node size (with entrance degree, there is also a bug here, but I am still diving how to reproduce + turn around it)
5. filter on range label (also a UX bug probably)
6. show label (nothing visible as my label column is empty)
7. go to data lab (sorry for translation, I usually use it in french)
8. copy data from column ABC to column label
9. go back to view, I have the bug, I cannot move the view with the right click

**Comment by eduramiba** [comment]
Closing old issue
