### ISSUE TITLE
Exception in Preview and Export

### ISSUE THREAD

**Issue by ChrisWellington** [gephi/gephi#644]
This issue has occurred on two computers (Windows and Linux) and happens frequently. I am working with dynamic graphs originally written in GEXF and imported to Gephi. These graphs use grouped nodes, which may be related to the issue. 

**Symptoms:** the error itself, which comes up only when entering preview mode, *and then that the preview does not display any edges*. The nodes and labels display properly, but no edges show up, even after refreshing. The options for "show edges" are checked. In the exported files (SVG and PDF), the edges are also missing. Once this happens one time in a file, I can no longer do exports from that file (even after restarting Gephi). Even a way to fix damaged files would be greatly appreciated! 

Though I have not found a minimal example, I have been able to reproduce it multiple times on some relatively small files. I'll try to submit one and, if that does not work, am more than happy to provide it. The displayed error is below: 

"NegativeArraySizeException at org.gephi.preview.plugin.builders.EdgeBuilder.getItems"

```java.lang.NegativeArraySizeException
[catch] at org.gephi.preview.plugin.builders.EdgeBuilder.getItems(Unknown Source)
	at org.gephi.preview.PreviewControllerImpl.refreshPreview(Unknown Source)
	at org.gephi.preview.PreviewControllerImpl.refreshPreview(Unknown Source)
	at org.gephi.desktop.preview.PreviewUIControllerImpl$2.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:662)
```

Here are two example files: the file before entering preview mode, and then the same file after entering preview mode and generating the error described. 

* https://docs.google.com/open?id=0ByKQq8mchaG-d19XUFJnMkRBaDQ (pre-error)
* https://docs.google.com/open?id=0ByKQq8mchaG-MjRIcjhwMHd6RTg (post-error)

**Comment by mbastian** [comment]
This should be fixed with Gephi 0.9.0. Closing this issue, please reopen if it still doesn't work.
