### ISSUE TITLE
opening a .dot or .csv file deletes it on linux

### ISSUE THREAD

**Issue by rodvprt** [gephi/gephi#653]
When attempting to open a .dot or .csv file for input, absolutely nothing happens (no further dialog), and the file is deleted.

version info:

Product Version: Gephi 0.8.1 beta 201202141941
Java: 1.6.0_22; Java HotSpot(TM) 64-Bit Server VM 17.1-b03
System: Linux version 2.6.32 running on amd64; UTF-8; en_US (gephi)

**Comment by cheaphomemadeacid** [comment]
confirmed, experiencing the same issue (version 082)

**Comment by luileito** [comment]
Confirmed, too. Using v0.8.2 on Ubuntu 14.04 with OpenJDK 1.7.0_79

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
