### ISSUE TITLE
support of additional attributes in gml import and export

### ISSUE THREAD

**Issue by MatatTHC** [gephi/gephi#662]
It would be nice if the gml parser would understand some reasonable graph attributes, e.g. edge color, edge width. E.g., color, coulour, width, ... . The idea is that the gml standard allows arbitrary attributes. Thus if a parser understands it its fine otherwise unknown attributes are supposed to be ignored. The same principle applies to the output as well. So you could also save colour, width, ... in gml export. 

See also https://forum.gephi.org/viewtopic.php?f=30&t=2024 .

**Comment by mbastian** [comment]
The GML parser already supports colors but only in rgb format (comma separated) and I created #1146 to add the support for color names and hex/oct codes. It also supports node width through the 'w' attribute (both import and export). The edge weight is supported through the 'value' or 'weight' attribute (both import and export). Now, I created #1147 to address the addition of edge color parsing.

I'm closing this ticket as issues are tracked elsewhere. If there are other attributes you would like to add to the GML parser/exporter please open a ticket per attribute with a reference to this ticket. Thanks!
