### ISSUE TITLE
Gephi Toolkit: save project as .gephi

### ISSUE THREAD

**Issue by ghost** [gephi/gephi#668]
Hello everyone,
I’m using the gephi toolkit and implement in java. Right now I have created a gephi project and did some fancy graphical stuff. Exporting the results in a pdf or gexf seems to work as well. But I want to save the whole project, not just the graph.
To do so I am doing this:
ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
pc.newProject();
…
File file = new File("newProject.gephi");
pc.saveProject(pc.getCurrentProject(), file).run();

but I experience the following error:

Aug 30, 2012 10:59:19 AM org.openide.util.NbPreferences getPreferencesProvider
Warnung: NetBeans implementation of Preferences not found

Someone have an idea to solve this problem?

p.s.: My IDE is Eclipse but in NetBeans the problem looks the same!

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
