### ISSUE TITLE
Color palette not showing when right click on it on ubuntu with oracle jdk

### ISSUE THREAD

**Issue by mrbarletta** [gephi/gephi#673]
Ubuntu 12.04 with 1.6.0-35 oracle jdk

Right clicking in the color icon  of the text/nodes does not show the palette.

Other palettes shows up, like the ranking color palette  chooser. 

What works?  - everything else - Worked perfect for the entire SNA course assignment except for this little thing.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
