### ISSUE TITLE
Data graphs not appearing.

### ISSUE THREAD

**Issue by AshShields** [gephi/gephi#676]
Gephi 0.8.1 beta
Linux Mint 13

Upon installation and running any of the network overview reports, the html graphs would not appear. The reported data would appear in the data lab, but the graphs simply showed an "image missing" image.

However, issue has now been seemingly resolved with no action on my part (aside from potentially toggling on the node labels) and is not reproducible.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
