### ISSUE TITLE
probable bug on strong / weak component stat panel 

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#677]
To reproduce:

create a graph with:

3 nodes A, B and C

3 edges:
A->B
B->A
A->C

I expect to find one strongly connected component (the set A, B) and 1 weakly connected component (A,B,C). The report from the stats panel finds a different result and it is not clear why?
See the pictures of the graph and the stat report here:
https://forum.gephi.org/viewtopic.php?f=32&t=2235&start=0

**Comment by wetneb** [comment]
I get the following results:
```
Number of Weakly Connected Components: 1
Number of Strongly Connected Components: 2
```
Those are consistent with the graph. There are indeed two strongly connected components { a,b } and { c }.
