### ISSUE TITLE
White blank window overlapping Gephi window

### ISSUE THREAD

**Issue by jwencelius** [gephi/gephi#678]
Starting Gephi on my computer a white and blank window appears and overlaps over the Gephi window making it impossible to use the software for me.
I have updated Java to the last version but the same bug keeps on coming up.

Any ideas?

Cheers,

Jean

**Comment by eduramiba** [comment]
This seems like an opengl problem.
Does it still happen with Gephi 0.8.2 and with the latest graphic card drivers?

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
