### ISSUE TITLE
Panel provided by a layout plugin cannot fit to its container

### ISSUE THREAD

**Issue by uraj** [gephi/gephi#682]
When a layout plugin wants to provide its own panel to replace the default property sheet, the panel does not as well as the default one to its container. This can be fixed by setting a LayoutManager (i.e., `BorderLayout`) for `org.gephi.desktop.layout.LayoutPanel.layoutProvidedPanel`

**Comment by mbastian** [comment]
Is this still happening? Thanks.

**Comment by mbastian** [comment]
Closing stale issue
