### ISSUE TITLE
Edges don't respect 3D (z) axis when vertices are displayed as Disk 2d

### ISSUE THREAD

**Issue by GaretJax** [gephi/gephi#689]
Edges don't follow nodes when those are placed into the 3rd dimension (z != 0) and nodes are displayed as 2D disks:

![Bug](http://cl.ly/image/130P1c1c1v3O/Screen%20Shot%202012-11-07%20at%2012.51.40%20.png)

Everything works when using Rectangle or Sphere 3d shapes.

**Comment by mbastian** [comment]
Closing this issue as we've removed the support for 3d graphs for now in Gephi 0.9.1.
