### ISSUE TITLE
Edge Ranking module does not update an attribute range in response to attribute edits in Data Laboratory

### ISSUE THREAD

**Issue by andygarcia** [gephi/gephi#705]
1. Generate a random graph
2. In the Ranking module, click Edges, then click the attribute dropdown and select Weight. Note that apply is greyed out since there is no variation in the WEIGHT attribute, all set to 1.
3. Click on Data Laboratory, and edit at least one edge's WEIGHT to something other than 1.
4. Click back to Overview, and notice that the scale for the WEIGHT attribute in the edge ranking module has not updated to reflect the change and still reads 1.0 for both min/max.

Clicking on the Node tab in Ranking, and then back to the Edge tab will register the change as will selecting another edge attribute (if exists) in the dropdown and then reselecting WEIGHT.

**Comment by mbastian** [comment]
This shouldn't happen anymore with the appearance module in Gephi 0.9.1. Closing.
