### ISSUE TITLE
Some problems with 0.8.2 Beta

### ISSUE THREAD

**Issue by alezonin** [gephi/gephi#716]
Hi all, I've recently installed 0.8.2 on windows xp. Some problems appears:

1) Pop-up screen at starts says that there is a new release to install (0.8.2)..... but I've done it!
2) Clicking on File Menu I have no way to open existing files on my pc

Someone could help? Some screenshot follows.

A.Z

![ScreenShot1](https://f.cloud.github.com/assets/3184609/42892/995c6f08-5658-11e2-9477-356f0472f384.PNG)
![ScreenShot2](https://f.cloud.github.com/assets/3184609/42896/b699ad38-5658-11e2-9037-5469fb2da836.PNG)

**Comment by mbastian** [comment]
Closing old issue, not relevant since 0.9.0 release.
