### ISSUE TITLE
GEXF import error (accents messed up if first accent does not arrive early enough)

### ISSUE THREAD

**Issue by ghost** [gephi/gephi#725]
Using Gephi 0.8.2 201210100934, when importing a GEXF (version 1.2) file, the "label" attribute of the "node" element is improperly decoded from UTF-8 (accents are messed up) if the first accent arrives too late in the file. 

Making the GEXF file a bit smaller before the offending node (by removing some random unrelated node or even some inside elements) fixes the problem.

I have generated a small (~4500 bytes) GEXF file tho reproduce this issue:

https://gist.github.com/4575591

The last name ("Pare") finishes with an accented "e". This accent is messed up when importing the file (for example in the "data laboratory") but if some random node before that is removed then everything goes smoothly. 

A simple workaround is to add an XML comment containing an accent at the beginning of the file. Something like:

The correct encoding is of course specified in the first line of the GEXF file:

<?xml version="1.0" encoding="UTF-8"?>

I have not looked at the code but it looks like the importer tries to re-guess the encoding maybe based on the first 4096 bytes.

**Comment by mcmahonc** [comment]
All I can say is that I have been scratching my head on this for hours as the UTF-8 was clearly added correctly to the gexf file, I added the comment  to my file and all of the non-ASCII characters arrived in tact. Thank you so much for that tip! Its a large file so it saved me hours of manually fixing in the data laboratory
