### ISSUE TITLE
No suitable driver for jdbc:sqlite

### ISSUE THREAD

**Issue by leonsas** [gephi/gephi#727]
Importing edge lists from SQLite is not working, with error message:

```
 No suitable driver for jdbc:sqlite:<path to db>
```

Following same steps work fine for 0.8.1, but fails on 0.8.2 (even the Test Connection).
This is on a Windows 7, x64.

Log file at http://pastebin.com/bzihfD43

**Comment by zhanwv** [comment]
this update from 0.8.2 to 0.8.2.1 is not downloadable from the plugin tools. 
Could you please direct me to the right update path. 

Current update information as below: 
Installed version: 0.8.2 Available version: 0.8.2.1 Author: Gephi Consortium Date: 1/20/13 Source: Gephi Update Center Homepage: http://gephi.org/modules/db-drivers  
Plugin Description
Database Drivers (MySQL, PostgreSQL, SQLite, Teradata, SQLServer)
