### ISSUE TITLE
No graph shown in overview

### ISSUE THREAD

**Issue by mikeg-de** [gephi/gephi#733]
Out of nowhere the graph blinks only a millisecond when opening the file. Applying a new layout, filtering or reseting zoom, color, colors etc. won't fix it but there's no issue while opening e.g. Les Miserables.

OSX 10.7.5
java version "1.6.0_37"
Java(TM) SE Runtime Environment (build 1.6.0_37-b06-434-11M3909)
Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01-434, mixed mode)

On startup the concole shows me four lines of java issues:
29.01.13 08:45:32,354 [0x0-0x77077].org.gephi: Jan 29 08:45:32 java[3193] <Error>: CGContextGetCTM: invalid context 0x0
29.01.13 08:45:32,354 [0x0-0x77077].org.gephi: Jan 29 08:45:32 java[3193] <Error>: CGContextSetBaseCTM: invalid context 0x0
29.01.13 08:45:32,354 [0x0-0x77077].org.gephi: Jan 29 08:45:32 java[3193] <Error>: CGContextGetCTM: invalid context 0x0
29.01.13 08:45:32,354 [0x0-0x77077].org.gephi: Jan 29 08:45:32 java[3193] <Error>: CGContextSetBaseCTM: invalid context 0x0

When i check the java control panel it's shown version 1.7.0_11 … I'll try to install a separate version and report later.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.

**Comment by ishaniGupta27** [comment]
I am facing same issue with 0.9.2 version on Mac.

**Comment by duncdrum** [comment]
@ishaniGupta27 what is your java version? Open Application > utilities > terminal 
```bash
java -version
```

**Comment by Vadi** [comment]
That "Graph" menu item in Windows menu never looked like a menu item. I was thinking it is a Menu Group until I came across this issue. Please add an icon like rest of the menu item or it should be explicit 🙏🏻

**Comment by higorsmonteiro** [comment]
I am having the same issue. I tried different gephi versions, tried reinstalling java, tried the 'Graph' option, tried the 'Reset Window', tried deleting the .gephi folder, but until now I got nothing showing in the overview, even though the 'preview' window is working fine. I am on the new ubuntu, btw.
