### ISSUE TITLE
NumberFormatException when loading dot file containing "[H,S,V]" colors

### ISSUE THREAD

**Issue by Zeex** [gephi/gephi#739]
When I open a dot file in Gephi the following error occurs:

```
java.lang.RuntimeException: java.lang.NumerFormatExceptIion: For input string: "0.6,"
```

The file I'm trying to load contains several lines that look something like this:

```
"main" [color="0.6, 0.1, 1", shape=octagon];
```

(GraphViz opens the same file without errors)

**Comment by mbastian** [comment]
This is still happening, reopening.
