### ISSUE TITLE
Filters/Attributes/Partition/Modularity in 0.8.2 "sticks" 

### ISSUE THREAD

**Issue by suthers** [gephi/gephi#741]
After upgrade to 0.8.2, doing something I have done repeatedly as part of my research: 
(1) compute modularity classes of a large graph; 
(2) use Filters/Attributes/Partition/Modularity to look at partitions. 
... it appeared to hang (not update the display). 

The next day, several students in my class reported having the same problem (obviously on different machines and graphs). 

Tonight, trying to reproduce this systematically it seems to be 'sticking' rather than 'hanging'. Working with a fresh download of your heroes graph from the Gephi data wiki, I did modularity partitioning and then applied the modularity filter as above. Clicking various partitions on and off, eventually one of the following happens (in multiple sessions, quitting Gephi between trials): 

A. The filter stops updating when I select new partitions. This is not just a graph display refresh: Data Laboratory also got "stuck" on the selection even when I changed filters. 

B. When I turn the filter off, the graph is not restored (the filter is not turned off), including in Data Laboratory. 

In case B, I deleted the filter and then created a new one. This time, only the modularity classes that had been selected when it got 'stuck were given as options. 

This is the major operation I use in my current analysis, so I am stuck with 0.8.1 until this is fixed. 

I tried to reproduce this with other filters but no "luck" yet.

**Comment by eduramiba** [comment]
Closing old issue, try with next version 0.9.2
