### ISSUE TITLE
How to change color of the edge between two nodes?

### ISSUE THREAD

**Issue by nakulk** [gephi/gephi#743]
After shortest path algorithm i need to change edges color between two nodes. I am using 
Edge edge = model.getGraph().getEdge(nn, ni);
edge.getEdgeData().setColor(0,0.5f,0);
It's showing neither an error nor making any changes in graph. Could you please suggest me any another solution for this?

**Comment by xiaoY-Fighter** [comment]
hello,eduramiba
the website you gived above is closed now
can you tell me how to solve that problem?
thank you!

**Comment by xiaoY-Fighter** [comment]
hello,eduramiba
the website you gived above is closed now
could you tell me how to solve that problem
