### ISSUE TITLE
No way to filter out nodes that do not have a particular value?

### ISSUE THREAD

**Issue by jukkahuhtamaki** [gephi/gephi#750]
I have been struggling with the same issue reported in Gephi forums: trying to use NOT operator with Library>Attributes>Equals filter as there does not seem to be any other intuitive way for filtering out nodes that do not a particular value. Is this a bug or a feature - and how would one go about the probem?   

http://forum.gephi.org/viewtopic.php?t=2422

**Comment by rahulgithub** [comment]
Running into same issue. Need to remove certain nodes only and keep the rest. I would think its a standard operation and there should have been a fix by now.

**Comment by mbastian** [comment]
I confirmed this is fixed
