### ISSUE TITLE
buggy file name in Export table feature

### ISSUE THREAD

**Issue by mef** [gephi/gephi#752]
The default file name for Export table feature (exporting nodes from data laboratory) causes the save window not to save the file:

Here is what happens when I click "Save" button without modifying the default file name:
- the "File of Type" list value is updated (with full file name instead of 'CSV (*csv)' extension),
- the list of files in current folder gets emptied (no file existing with that extension)
- no file gets written at all
- no error message appears
  Clicking again on 'save' has no action.

This seems to be caused by the square brackets "[Nodes]" included in the default name, removing them solves the problem.

This happens to me on crunchbang linux 'Waldorf', which is basically a Debian testing with openbox window manager.

Environment:
Product Version: Gephi 0.8.2 201210100934
Java: 1.7.0_07; Java HotSpot(TM) 64-Bit Server VM 23.3-b01
System: Linux version 3.7.0-6.dmz.1-liquorix-amd64 running on amd64; UTF-8; en_US (gephi)

**Comment by mbastian** [comment]
Closing old issue, this has been resolved when we aligned the export table feature to use the Exporter API. From version 0.9.2 onward I believe.
