### ISSUE TITLE
Curved Arrow Tips

### ISSUE THREAD

**Issue by MathiasRiechert** [gephi/gephi#753]
Hello, I do really need the arrow tips for curved edges, as well as be able to specify the amout of curvedness. Is this on plan for the future or is there a plug-in for doing that?

I already wrote an application for graph visualization with curved arrows (with tips), where the amount of curvedness could be determined - and thought about implementing this to the graph engine in gephi - where would i have to start if i wanted to implement that myself?

Many thanks in advance!
Mathias

**Comment by Frodox** [comment]
> Hello, I do really need the arrow tips for curved edges, as well as be able to specify the amout of curvedness. Is this on plan for the future or is there a plug-in for doing that?

+1, I also would like to see this feature. It's not comfortable for me to look "clockwise" and "counterclock" to determine dependency

**Comment by fabricehong** [comment]
+1 ! it would be extremely handy. Articles readers are not necessarly aware of those conventions.

Moreover, you nearly always need the curved edge features in directed graph where nodes have mutual directed edges (with straight edges, edges overlaps).
