### ISSUE TITLE
WTF: Gephi deletes my GML file

### ISSUE THREAD

**Issue by muelli** [gephi/gephi#757]
I'm trying to load the file provided here: http://spark-public.s3.amazonaws.com/sna/datasets/week1/LadaFacebookAnon.gml (sha256:6fd9c8dbb75415006af1db1c85664477771931c568cbd33e073e9597b3717deb)

I downloaded the recent Gephi from the website (0.8.2), and opened the file. Gephi doesn't seem to react, i.e. I don't receive an update to the UI, esp. no data is loaded or anything. In addition, and that's scary, it unlinks the file!

I didn't expect Gephi to delete files at all. And I expected it to open the file just fine. Python's networkx does.

**Comment by manuel-delverme** [comment]
still bugged, it's getting pretty annoying.

**Comment by eduramiba** [comment]
Related issue: #1041
