### ISSUE TITLE
Make partition colors persistent with the attribute column

### ISSUE THREAD

**Issue by ld26464** [gephi/gephi#760]
Gephi 8.1 
Color attributes are regenerated every time you enter a given partition parameter subpage, even if they have been applied to the graph.

They should be persistant, including any changes that are made with the color selector tool. 

This means that there is no way to know what the colors are attributes of if you select another of the pulldowns and then return to the first, even if no changes are made.

**Comment by mbastian** [comment]
This is now fixed in trunk with the new Appearance module (replaces ranking & partition). Colors are directly attached with the column so there's no color setting lost when manipulating the module. It will be included in the upcoming 0.9 release.
