### ISSUE TITLE
Graph Toolbar items overlap on smaller screen sizes

### ISSUE THREAD

**Issue by Experimenter** [gephi/gephi#765]
For smaller screens on netbooks and 12 inch laptops the  Graph window toolbar icons overlap making items like edit unreachable. The image should provide you a better idea of the problem. THis is a full screen view and you can see the icons on the left toolbar of the graph window overlapping.

![Screenshot - Sunday 17 March 2013 - 12:02:50 IST](https://f.cloud.github.com/assets/3885174/267223/e3cb9882-8e68-11e2-8c7a-7ae845b1bbf1.png)

**Comment by mbastian** [comment]
To accommodate this issue, we've now made the Edit tool first on the toolbar as it tends to be used the most. It will be included in the next 0.9.3 release.
