### ISSUE TITLE
Gephi crashes the Java Runtime Environment

### ISSUE THREAD

**Issue by swaprava** [gephi/gephi#772]
I downloaded the latest version of gephi and uncompressed it to get the binaries. I'm using Ubuntu 12.04. When I run gephi from terminal and load the example les miserable file for viewing, I see the following log on the terminal:

$ ./gephi
Loading native libraries
Current Version is 082
# Nodes loaded: 77
# Edges loaded: 254
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdca0ea8c58, pid=10527, tid=140585693677312
#
# JRE version: 7.0_15-b20
# Java VM: OpenJDK 64-Bit Server VM (23.7-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libX11.so.6+0x33c58]  XQueryExtension+0x28
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#

**Comment by eduramiba** [comment]
Gephi is not tested with openjdk, and oracle jdk is recommended.
