### ISSUE TITLE
ID attribute missing in gexf export

### ISSUE THREAD

**Issue by davidmam** [gephi/gephi#776]
I imported a network via gml, then exported to gexf to be able to manipulate the data programatically. The gexf export has no ID attribute for the <edge> elements though it does have the source, target and label.

**Comment by neil-rubens** [comment]
In my case, node attribute goes missing after gexf export.

**Comment by mbastian** [comment]
@neil-rubens Can you provide an example? Also, did you make sure to check the "export attributes" checkbox in export options?

**Comment by neil-rubens** [comment]
@mbastian thank you for the quick reply.

I am using toolkit jar; importing a gexf graph, applying a filter, exporting it to a different gexf.

Examining the before and after gexf; I noticed the `attributes` part of the `graph` header ; somehow disappears:

```xml
    <attributes class="node" mode="static">
      <attribute id="type" title="type" type="string"></attribute>
    </attributes>
```

The node data in gexf; still contains the column `type`; but this attribute is no longer accessible (probably due to missing the needed header).

I'll try to replicate it on a toy example and will submit more details.

## GEXF Before

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2" xmlns:viz="http://www.gexf.net/1.2draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd">
  <meta lastmodifieddate="2015-10-28">
    <creator>Gephi 0.8.1</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="undirected" mode="static">
    <attributes class="node" mode="static">
      <attribute id="type" title="type" type="string"></attribute>
    </attributes>
    <nodes>
      <node id="418569" label="L1">
        <attvalues>
          <attvalue for="type" value="c"></attvalue>
        </attvalues>
        <viz:size value="1.0"></viz:size>
        <viz:position x="-230.28314" y="338.39166" z="0.0"></viz:position>
        <viz:color r="153" g="153" b="153"></viz:color>
      </node>
       ..............
```

## GEXF After


```xml
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2" xmlns:viz="http://www.gexf.net/1.2draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd">
  <meta lastmodifieddate="2015-10-28">
    <creator>Gephi 0.8.1</creator>
    <description></description>
  </meta>
  <graph defaultedgetype="undirected" mode="static">
    <nodes>
      <node id="418569" label="L1">
        <attvalues>
          <attvalue for="type" value="c"></attvalue>
        </attvalues>
        <viz:size value="1.0"></viz:size>
        <viz:position x="-230.28314" y="338.39166" z="0.0"></viz:position>
        <viz:color r="153" g="153" b="153"></viz:color>
      </node>
       ..............
```

**Comment by neil-rubens** [comment]
@mbastian I tried the same procedure on a toy example; and it did work.  If I figure out, what have made my case different; I'll update the issue.

**Comment by neil-rubens** [comment]
@mbastian Sorry; the error was on my part; I've made a utility function `importGraph`; but there I have accidentally called `projectController.newProject()`  (even though `newProject()` was already called in the main body); removing it fixed the problem.
