### ISSUE TITLE
Cannot open Gephi project in 0.8.1 Beta

### ISSUE THREAD

**Issue by sigpwned** [gephi/gephi#777]
I'm running Gephi 0.8.1 Beta while 0.8.2 Beta is having issues running on Macs with JDK 7 installed.

I can successfully save a project, but I cannot open it afterwards. I did not have this problem in Gephi 0.8.0 Beta. Gephi tells me "The project file couldn't be opened. Please check the file has.gephi extension." (The file does have a `.gephi` extension; I had just saved it with the same version of Gephi.) Here's a screenshot of the error:

![Screen Shot 2013-04-27 at 4 28 25 PM](https://f.cloud.github.com/assets/1236302/435053/5aeb02a0-af92-11e2-945f-faf8ed366671.png)

I've uploaded an example of a project that I saved but cannot load [here](https://dl.dropboxusercontent.com/u/67939891/Gephi%20Project%20Load%20Error.gephi).

Also, Gephi is wonderful! By far the best thing out there for network analysis. You guys have done great work!

**Comment by mbastian** [comment]
This issue is fixed in 0.9.0, closing.
