### ISSUE TITLE
Can't connect to Gephi's Updates Centre!

### ISSUE THREAD

**Issue by aalhaimi** [gephi/gephi#779]
Hello,
Gephi version: 0.8.2
Platform: Mac

I'm using my default proxy settings on Gephi. I can't check software updates due to failing to connect to the updates server. To make sure the problem is not from my side, I installed Gephi 0.8 and checked for updates... I was able to connect to the server and to get the list of updates. 
Thanks!

![screen shot 2013-05-21 at 1 49 36 pm](https://f.cloud.github.com/assets/4491274/543629/27c1b274-c23f-11e2-8f15-0fe0e0bcba1b.png)

**Comment by joeyfezster** [comment]
Again seeing the same issue from two different machines.
using default proxy, getting the exact same message as above (windows and ubuntu)
