### ISSUE TITLE
Gephi freezes when importing a graph while Timeline is on

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#783]
Way to reproduce:
1. Import a dynamic graph
2. Enable the timeline
3. Import a dynamic graph again.

The UI gets frozen

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.

**Comment by mars0i** [comment]
Thanks very much—Thank you for Gephi.  Will do.

Marshall
