### ISSUE TITLE
installation in debian crunchbang linux

### ISSUE THREAD

**Issue by carbonmetrics** [gephi/gephi#791]
Gephi was running, but now fails to start up. 
I see: a splash screen and then nothing, or a window with only the buttons overview/data laboratory/preview. 

system is Debian Crunchbang 64 bit, gephi 0.8.2. i was [unsuccesfully] trying to install rJava in R 3.0.1, java still in mode:
* 0            /usr/lib/jvm/java-6-openjdk/jre/bin/java   1061      auto mode

logfile is below as per bug report instructions. 
there are several warnings, but i don't understand any of them.

Henk

----------------------------------------
-------------------------------------------------------------------------------
>Log Session: Monday, June 10, 2013 4:07:31 PM CEST
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Linux version 2.6.32-5-amd64 running on amd64
  Java; VM; Vendor        = 1.6.0_26; Java HotSpot(TM) 64-Bit Server VM 20.1-b02; Sun Microsystems Inc.
  Runtime                 = Java(TM) SE Runtime Environment 1.6.0_26-b03
  Java Home               = /usr/lib/jvm/java-6-sun-1.6.0.26/jre
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /home/henk
  Current Directory       = /home/henk
  User Directory          = /home/henk/.gephi/0.8.2/dev
  Cache Directory         = /home/henk/.gephi/0.8.2/dev/var/cache
  Installation            = /home/henk/apps/gephi/gephi
                            /home/henk/apps/gephi/platform
                            /home/henk/apps/gephi/platform
  Boot & Ext. Classpath   = /usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/resources.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/rt.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/jsse.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/jce.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/charsets.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/modules/jdk.boot.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/classes:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib/ext/sunjce_provider.jar
  Application Classpath   = /home/henk/apps/gephi/platform/lib/boot.jar:/home/henk/apps/gephi/platform/lib/org-openide-modules.jar:/home/henk/apps/gephi/platform/lib/org-openide-util.jar:/home/henk/apps/gephi/platform/lib/org-openide-util-lookup.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ar_SA.jar:/home/henk/apps/gephi/platform/lib/locale/boot_bg.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ca.jar:/home/henk/apps/gephi/platform/lib/locale/boot_cs.jar:/home/henk/apps/gephi/platform/lib/locale/boot_de.jar:/home/henk/apps/gephi/platform/lib/locale/boot_es.jar:/home/henk/apps/gephi/platform/lib/locale/boot_fr.jar:/home/henk/apps/gephi/platform/lib/locale/boot_gl_ES.jar:/home/henk/apps/gephi/platform/lib/locale/boot_in_ID.jar:/home/henk/apps/gephi/platform/lib/locale/boot_it.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ja.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ko.jar:/home/henk/apps/gephi/platform/lib/locale/boot_nl_NL.jar:/home/henk/apps/gephi/platform/lib/locale/boot_pl.jar:/home/henk/apps/gephi/platform/lib/locale/boot_pt_BR.jar:/home/henk/apps/gephi/platform/lib/locale/boot_pt_PT.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ro.jar:/home/henk/apps/gephi/platform/lib/locale/boot_ru.jar:/home/henk/apps/gephi/platform/lib/locale/boot_si.jar:/home/henk/apps/gephi/platform/lib/locale/boot_sq.jar:/home/henk/apps/gephi/platform/lib/locale/boot_sv.jar:/home/henk/apps/gephi/platform/lib/locale/boot_tr.jar:/home/henk/apps/gephi/platform/lib/locale/boot_zh_CN.jar:/home/henk/apps/gephi/platform/lib/locale/boot_zh_TW.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_bg.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ca.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_cs.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_de.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_es.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_fr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_it.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ja.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ko.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_pl.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ro.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_ru.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_si.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_sq.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_sv.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_tr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_bg.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ca.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_cs.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_de.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_es.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_fr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_it.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ja.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ko.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_pl.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ro.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_ru.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_si.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_sq.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_sv.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_tr.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/home/henk/apps/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/java-6-sun/lib/dt.jar:/usr/lib/jvm/java-6-sun/lib/tools.jar
  Startup Classpath       = /home/henk/apps/gephi/platform/core/core.jar:/home/henk/apps/gephi/platform/core/org-openide-filesystems.jar:/home/henk/apps/gephi/platform/core/locale/core_cs.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_de.jar:/home/henk/apps/gephi/platform/core/locale/core_es.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/home/henk/apps/gephi/platform/core/locale/core_zh_CN.jar:/home/henk/apps/gephi/platform/core/locale/core_ca.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/home/henk/apps/gephi/platform/core/locale/core_nl_NL.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_si.jar:/home/henk/apps/gephi/platform/core/locale/core_pt_BR.jar:/home/henk/apps/gephi/platform/core/locale/core_sv.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/home/henk/apps/gephi/platform/core/locale/core_ru.jar:/home/henk/apps/gephi/platform/core/locale/core_in_ID.jar:/home/henk/apps/gephi/platform/core/locale/core_pt_PT.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_it.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_es.jar:/home/henk/apps/gephi/platform/core/locale/core_ar_SA.jar:/home/henk/apps/gephi/platform/core/locale/core_ja.jar:/home/henk/apps/gephi/platform/core/locale/core_si.jar:/home/henk/apps/gephi/platform/core/locale/core_ko.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/home/henk/apps/gephi/platform/core/locale/core_sq.jar:/home/henk/apps/gephi/platform/core/locale/core_fr.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/home/henk/apps/gephi/platform/core/locale/core_gl_ES.jar:/home/henk/apps/gephi/platform/core/locale/core_it.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/home/henk/apps/gephi/platform/core/locale/core_tr.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/home/henk/apps/gephi/platform/core/locale/core_de.jar:/home/henk/apps/gephi/platform/core/locale/core_bg.jar:/home/henk/apps/gephi/platform/core/locale/core_ro.jar:/home/henk/apps/gephi/platform/core/locale/core_pl.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/home/henk/apps/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/home/henk/apps/gephi/platform/core/locale/core_zh_TW.jar:/home/henk/apps/gephi/bin/../gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.15.2 201210100934]
	org.openide.util [8.25.2 201210100934]
	org.openide.modules [7.32.1 201210100934]
	org.openide.filesystems [7.62.1 201210100934]
	org.netbeans.api.annotations.common/1 [1.14.1 201210100934]
	org.openide.awt [7.46.1 201210100934]
	org.netbeans.api.progress/1 [1.28.1 201210100934]
	org.openide.dialogs [7.25.1 201210100934]
	org.openide.nodes [7.28.1 201210100934]
	org.openide.windows [6.55.2 201210100934]
	org.netbeans.modules.editor.mimelookup/1 [1.26.1 201210100934]
	org.openide.text [6.49.3 201210100934]
	org.netbeans.swing.tabcontrol [1.36.1 201210100934]
	org.netbeans.swing.outline [1.20.1 201210100934]
	org.openide.explorer [6.45.1 201210100934]
	org.openide.actions [6.26.1 201210100934]
	org.netbeans.modules.queries/1 [1.28.1 201210100934]
	org.openide.loaders [7.37.3 201210100934]
	org.openide.io [1.31.2 201210100934]
	org.netbeans.swing.plaf [1.25.1 201210100934]
	org.netbeans.spi.quicksearch [1.14.1 201210100934]
	org.netbeans.bootstrap/1 [2.52.3 201210100934]
	org.netbeans.core.startup/1 [1.40.1 201210100934]
	org.netbeans.modules.settings/1 [1.35.1 201210100934]
	org.netbeans.modules.sendopts/2 [2.22.1 201210100934]
	org.netbeans.modules.sampler [1.1.1 201210100934]
	org.netbeans.modules.progress.ui [1.20.1 201210100934]
	org.netbeans.modules.print [7.13.1 201210100934]
	org.netbeans.modules.keyring [1.11.1 201210100934]
	org.netbeans.core/2 [3.33.1 201210100934]
	org.netbeans.modules.options.api/1 [1.26.1 201210100934]
	org.netbeans.modules.options.keymap [1.19.2 201210100934]
	org.netbeans.modules.masterfs/2 [2.38.2 201210100934]
	org.netbeans.libs.jna/1 [1.21.1 201210100934]
	org.netbeans.modules.masterfs.linux [1.1.1 201210100934]
	org.netbeans.modules.keyring.impl [1.7.1 201210100934]
	org.netbeans.modules.favorites/1 [1.29.1 201210100934]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.18.1 201210100934]
	org.netbeans.modules.autoupdate.services [1.33.2 201210100934]
	org.netbeans.core.ui/1 [1.31.1 201210100934]
	org.netbeans.modules.autoupdate.ui [1.27.3 201210100934]
	org.netbeans.libs.osgi [1.9.1 201210100934]
	org.netbeans.libs.felix [2.3.1 201210100934]
	org.netbeans.core.windows/2 [2.49.3 201210100934]
	org.netbeans.modules.core.kit [1.16.1 201210100934]
	org.netbeans.core.output2/1 [1.26.1 201210100934]
	org.netbeans.core.netigso [1.16.1 201210100934]
	org.netbeans.core.nativeaccess/1 [1.16.1 201210100934]
	org.netbeans.core.io.ui/1 [1.16.1 201210100934]
	org.gephi.utils.longtask [0.8.2 0.8.2 201301031858]
	org.gephi.project.api [0.8.2 0.8.2 201301031858]
	org.gephi.core.library.wrapper [0.8.2 0.8.2 201301031858]
	org.gephi.utils [0.8.2 0.8.2 201301031858]
	org.gephi.graph.api [0.8.2 0.8.2 201301031858]
	org.gephi.data.attributes.api [0.8.2 0.8.2 201301031858]
	org.gephi.lib.validation [0.8.2 0.8.2 201301031858]
	org.gephi.ui.utils [0.8.2 0.8.2 201301031900]
	org.gephi.ui.library.wrapper [0.8.2 0.8.2 201301031859]
	org.gephi.ui.components [0.8.2 0.8.2 201301031900]
	org.gephi.workspace.ui [0.8.2 0.8.2 201301031903]
	org.gephi.db.drivers [0.8.2.1 0.8.2 201301202012]
	org.gephi.dynamic.api [0.8.2 0.8.2 201301031859]
	org.gephi.io.importer.api [0.8.2 0.8.2 201301031859]
	org.gephi.mostrecentfiles.api [0.8.2 0.8.2 201301031902]
	org.gephi.desktop.project [0.8.2 0.8.2 201301031902]
	org.gephi.welcome.screen [0.8.2 0.8.2 201301031902]
	org.gephi.datalab.api [0.8.2 0.8.2 201301031859]
	org.gephi.visualization.api [0.8.2 0.8.2 201301031859]
	org.gephi.tools.api [0.8.2 0.8.2 201301031901]
	org.gephi.utils.collection [0.8.2 0.8.2 201301031901]
	org.gephi.gleem [0.8.2 0.8.2 201301031901]
	org.gephi.visualization [0.8.2 0.8.2 201301031902]
	org.gephi.ui.propertyeditor [0.8.2 0.8.2 201301031904]
	org.gephi.algorithms.plugin [0.8.2 0.8.2 201301031901]
	org.gephi.tools.plugin [0.8.2 0.8.2 201301031902]
	org.gephi.timeline [0.8.2 0.8.2 201301031901]
	org.gephi.statistics.api [0.8.2 0.8.2 201301031901]
	org.gephi.statistics.plugin [0.8.2 0.8.2 201301031901]
	org.gephi.statistics.plugin.ui [0.8.2 0.8.2 201301031901]
	org.gephi.ranking.api [0.8.2 0.8.2 201301031900]
	org.gephi.spline.editor [0.8.2 0.8.2 201301031901]
	org.gephi.spigot.plugin [0.8.2 0.8.2 201301031900]
	org.gephi.spigot.plugin.ui [0.8.2 0.8.2 201301031900]
	org.gephi.settings.upgrader [0.8.2 0.8.2 201301031900]
	org.gephi.ranking.plugin [0.8.2 0.8.2 201301031900]
	org.gephi.ranking.plugin.ui [0.8.2 0.8.2 201301031900]
	org.gephi.project.ui [0.8.2 0.8.2 201301031900]
	org.gephi.io.processor.plugin [0.8.2 0.8.2 201301031859]
	org.gephi.processor.plugin.ui [0.8.2 0.8.2 201301031859]
	org.gephi.preview.api [0.8.2 0.8.2 201301031858]
	org.gephi.preview.plugin [0.8.2 0.8.2 201301031859]
	org.gephi.io.exporter.api [0.8.2 0.8.2 201301031858]
	org.gephi.io.exporter.preview [0.8.2 0.8.2 201301031858]
	org.gephi.preview.export.ui [0.8.2 0.8.2 201301031859]
	org.gephi.perspective.api [0.8.2 0.8.2 201301031906]
	org.gephi.partition.api [0.8.2 0.8.2 201301031904]
	org.gephi.partition.plugin [0.8.2 0.8.2 201301031907]
	org.gephi.partition.plugin.ui [0.8.2 0.8.2 201301031907]
	org.gephi.layout.api [0.8.2 0.8.2 201301031903]
	org.gephi.layout.plugin [0.8.2 0.8.2 201301031904]
	org.gephi.io.importer.plugin [0.8.2 0.8.2 201301031905]
	org.gephi.io.generator.api [0.8.2 0.8.2 201301031903]
	org.gephi.io.generator.plugin [0.8.2 0.8.2 201301031903]
	org.gephi.io.exporter.plugin [0.8.2 0.8.2 201301031903]
	org.gephi.import.plugin.ui [0.8.2 0.8.2 201301031906]
	org.gephi.graph.dhns [0.8.2 0.8.2 201301031905]
	org.gephi.gephi.branding [0.8.2 0.8.2 201301031857]
	org.gephi.generator.plugin.ui [0.8.2 0.8.2 201301031903]
	org.gephi.filters.api [0.8.2 0.8.2 201301031904]
	org.gephi.filters.plugin [0.8.2 0.8.2 201301031905]
	org.gephi.desktop.perspective [0.8.2 0.8.2 201301031906]
	org.gephi.filters.plugin.ui [0.8.2 0.8.2 201301031906]
	org.gephi.filters.impl [0.8.2 0.8.2 201301031905]
	org.gephi.export.plugin.ui [0.8.2 0.8.2 201301031905]
	org.gephi.dynamic.impl [0.8.2 0.8.2 201301031907]
	org.gephi.directory.chooser [0.8.2 0.8.2 201301031908]
	org.gephi.desktop.tools [0.8.2 0.8.2 201301031908]
	org.gephi.desktop.timeline [0.8.2 0.8.2 201301031908]
	org.gephi.desktop.statistics [0.8.2 0.8.2 201301031904]
	org.gephi.desktop.spigot [0.8.2 0.8.2 201301031904]
	org.gephi.desktop.recent.files [0.8.2 0.8.2 201301031906]
	org.gephi.desktop.ranking [0.8.2 0.8.2 201301031904]
	org.gephi.desktop.progress [0.8.2 0.8.2 201301031903]
	org.gephi.desktop.io.export [0.8.2 0.8.2 201301031906]
	org.gephi.desktop.preview [0.8.2 0.8.2 201301031907]
	org.gephi.desktop.partition [0.8.2 0.8.2 201301031905]
	org.gephi.desktop.layout [0.8.2 0.8.2 201301031907]
	org.gephi.desktop.import [0.8.2 0.8.2 201301031907]
	org.gephi.desktop.hierarchy [0.8.2 0.8.2 201301031906]
	org.gephi.desktop.generate [0.8.2 0.8.2 201301031904]
	org.gephi.desktop.filters [0.8.2 0.8.2 201301031908]
	org.gephi.desktop.datalab [0.8.2 0.8.2 201301031905]
	org.gephi.desktop.context [0.8.2 0.8.2 201301031903]
	org.gephi.clustering.api [0.8.2 0.8.2 201301031904]
	org.gephi.desktop.clustering [0.8.2 0.8.2 201301031906]
	org.gephi.desktop.branding [0.8.2 0.8.2 201301031903]
	org.gephi.datalab.plugin [0.8.2 0.8.2 201301031907]
	org.gephi.clustering.plugin [0.8.2 0.8.2 201301031908]
	org.gephi.attributes [0.8.2.1 0.8.2 201301202126]
INFO [org.netbeans.core.windows.persistence]: [PersistenceManager.getTopComponentForID] Problem when deserializing TopComponent for tcID:'GraphTopComponent'. Reason: Cannot create instance of org.gephi.visualization.component.GraphTopComponent

msg
Caused: java.lang.IllegalArgumentException: GLDrawableFactory.chooseGraphicsConfiguration() was not used when creating this Component
	at com.sun.opengl.impl.x11.X11GLDrawableFactory.getGLDrawable(X11GLDrawableFactory.java:238)
	at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:142)
	at javax.media.opengl.GLCanvas.<init>(GLCanvas.java:90)
	at org.gephi.visualization.swing.GraphCanvas.<init>(GraphCanvas.java:70)
	at org.gephi.visualization.config.VizCommander.createCanvas(VizCommander.java:54)
	at org.gephi.visualization.VizController.initInstances(VizController.java:138)
	at org.gephi.visualization.VizController.getInstance(VizController.java:94)
	at org.gephi.visualization.component.GraphTopComponent.<init>(GraphTopComponent.java:99)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:355)
	at java.lang.Class.newInstance(Class.java:308)
	at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:227)
Caused: java.io.IOException: Cannot create instance of org.gephi.visualization.component.GraphTopComponent
	at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.defaultInstanceCreate(XMLPropertiesConvertor.java:229)
	at org.netbeans.modules.settings.convertors.XMLPropertiesConvertor.read(XMLPropertiesConvertor.java:98)
	at org.netbeans.modules.settings.InstanceProvider$InstanceCookieImpl.instanceCreate(InstanceProvider.java:310)
[catch] at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentPersistentForID(PersistenceManager.java:571)
	at org.netbeans.core.windows.persistence.PersistenceManager.getTopComponentForID(PersistenceManager.java:681)
	at org.netbeans.core.windows.PersistenceHandler.getTopComponentForID(PersistenceHandler.java:489)
	at org.netbeans.core.windows.PersistenceHandler.initModeFromConfig(PersistenceHandler.java:449)
	at org.netbeans.core.windows.PersistenceHandler.load(PersistenceHandler.java:214)
	at org.netbeans.core.windows.WindowSystemImpl.load(WindowSystemImpl.java:81)
	at org.netbeans.core.GuiRunLevel$InitWinSys.run(GuiRunLevel.java:234)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
	at java.awt.EventQueue.access$000(EventQueue.java:84)
	at java.awt.EventQueue$1.run(EventQueue.java:602)
	at java.awt.EventQueue$1.run(EventQueue.java:600)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:158)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
ALL [null]: org.netbeans.modules.settings.InstanceProvider@71e2b67c[org.openide.loaders.InstanceDataObject@62d5163a[MultiFileObject@1aa632be[Windows2Local-overview/Components/GraphTopComponent.settings]], MultiFileObject@79f71773[xml/lookups/org_gephi_visualization_component/Graph.instance]]
WARNING [org.netbeans.TopSecurityManager]: use of system property netbeans.user has been obsoleted in favor of InstalledFileLocator/Places at org.gephi.ui.upgrader.Upgrader.getCurrentVersion(Upgrader.java:123)
Diagnostic information
Input arguments:
	-Djdk.home=/usr/lib/jvm/java-6-sun
	-Dnetbeans.dirs=/home/henk/apps/gephi/bin/../gephi:/home/henk/apps/gephi/bin/../platform:
	-Dnetbeans.home=/home/henk/apps/gephi/platform
	-Xms64m
	-Xmx512m
	-Xverify:none
	-Dsun.java2d.noddraw=true
	-Dsun.awt.noerasebackground=true
	-Dnetbeans.indexing.noFileRefresh=true
	-Dplugin.manager.check.interval=EVERY_DAY
	-XX:+HeapDumpOnOutOfMemoryError
	-XX:HeapDumpPath=/home/henk/.gephi/0.8.2/dev/var/log/heapdump.hprof
Compiler: HotSpot 64-Bit Tiered Compilers
Heap memory usage: initial 64.0MB maximum 455.1MB
Non heap memory usage: initial 23.2MB maximum 130.0MB
Garbage collector: PS Scavenge (Collections=4 Total time spent=0s)
Garbage collector: PS MarkSweep (Collections=1 Total time spent=0s)
Classes: loaded=5107 total loaded=5107 unloaded 0
INFO [org.netbeans.core.ui.warmup.DiagnosticTask]: Total memory 16,832,765,952
INFO [null]: Total physical memory 16,832,765,952
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center.instance: url_key attribute deprecated in favor of url
WARNING [org.netbeans.modules.autoupdate.updateproviders.AutoupdateCatalogFactory]: Services/AutoupdateType/org_gephi_branding_update_center_1.instance: url_key attribute deprecated in favor of url
INFO [org.netbeans.core.ui.focus]: External Changes Refresh on focus gain disabled

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
