### ISSUE TITLE
Gephi behaves strange after deleting all nodes via streaming while running a layout algorithm or filter

### ISSUE THREAD

**Issue by jankantert** [gephi/gephi#794]
After deleting all nodes via streaming while running a layout algorithm or filter gephi will no longer render a graph. Screen will stay white. Sometimes rendering will start again after stopping the layout.

Setup: Ubuntu 13.04, Quad Core i7-2640, 8GB Ram, Gephi 0.8.2

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
