### ISSUE TITLE
Gephi Context is incorrect when working as streaming client

### ISSUE THREAD

**Issue by jankantert** [gephi/gephi#795]
When streaming nodes and edges to gephi with gephi as a client node count in the Context Tab on the right will not get updated. This works correctly when gephi acts as a streaming server.

Setup: Ubuntu 13.04, Quad Core i7-2640, 8GB Ram, Gephi 0.8.2

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
