### ISSUE TITLE
Import csv edge list with weights

### ISSUE THREAD

**Issue by Ram-Z** [gephi/gephi#796]
Add support for csv files in format:
node, node, weight

**Comment by haanns** [comment]
I've tried this method, but Gephi still seems to treat my weight column as a node. Is there a special process I should be following?

**Comment by CoKieKola** [comment]
I'm having an issue where it's simply not loading the dataset with weights. Came across this thread in a quick google search to troubleshoot. From what I can tell my data is formatted correctly and shows up correctly in the preview.

**Comment by eduramiba** [comment]
@CoKieKola are you using spreadsheet import and selecting edges table in the first wizard step?

**Comment by CoKieKola** [comment]
Yes, for some reason I'm able to load the nodes just fine, but when I click "finish" on the edges table nothing happens. I'm currently installing updates to see if that helps 
![capture](https://cloud.githubusercontent.com/assets/14849699/22176967/2f90a094-dfe3-11e6-8bf8-901d461ecb48.PNG)

**Comment by offero** [comment]
> Yes, for some reason I'm able to load the nodes just fine, but when I click "finish" on the edges table nothing happens. I'm currently installing updates to see if that helps
> ![capture](https://cloud.githubusercontent.com/assets/14849699/22176967/2f90a094-dfe3-11e6-8bf8-901d461ecb48.PNG)

This is exactly what is happening to me at the moment.
