### ISSUE TITLE
Gephi 0.8.2 Beta: Crashes on RHEL 64bit

### ISSUE THREAD

**Issue by kirsn** [gephi/gephi#797]
I downloaded and extracted the 0.8.2 beta archive ()
Then performed the following steps, and the issues I see.  But before that, this is my system information. 
Thanks,
Kiran

--SYS INFO------------------------------------------------------
[skiran@oc6688120108 bin]$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseWorkstation
Description:    Red Hat Enterprise Linux Workstation release 6.4 (Santiago)
Release:        6.4
Codename:       Santiago

[skiran@oc6688120108 bin]$ java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxa6460sr13ifix-20130303_02(SR13+IV37419))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr13-20130114_134867 (JIT enabled, AOT enabled)
J9VM - 20130114_134867
JIT  - r9_20130108_31100
GC   - 20121212_AA)
JCL  - 20130303_02

--ISSUE--------------------------------------------------

[skiran@oc6688120108 gephi]$ cd bin/
[skiran@oc6688120108 bin]$ ll
total 325600
-rw-------. 1 skiran skiran 534470656 Jun  7 16:12 core
-rwxrwxrwx. 1 skiran skiran      2346 Jan  4 00:39 gephi
-rwxrwxrwx. 1 skiran skiran   1448960 Jan  4 00:39 gephi64.exe
-rwxrwxrwx. 1 skiran skiran    477184 Jan  4 00:39 gephi.exe
[skiran@oc6688120108 bin]$ ./gephi
Jun 12, 2013 1:40:52 PM org.openide.util.lookup.implspi.ActiveQueue reportError
WARNING: Cannot hack ReferenceQueue to fix bug #206621!
Throwable occurred: java.lang.NoSuchFieldException: lock
        at java.lang.Class.getDeclaredFieldImpl(Native Method)
        at java.lang.Class.getDeclaredField(Class.java:575)
        at org.openide.util.lookup.implspi.ActiveQueue$Impl.<clinit>(ActiveQueue.java:82)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
        at org.openide.util.lookup.implspi.ActiveQueue.queue(ActiveQueue.java:70)
        at org.openide.util.lookup.AbstractLookup.activeQueue(AbstractLookup.java:753)
        at org.openide.util.lookup.AbstractLookup.access$600(AbstractLookup.java:80)
        at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1351)
        at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1334)
        at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:490)
        at org.openide.util.Lookup.lookupResult(Lookup.java:243)
        at org.openide.util.Lookup.lookupAll(Lookup.java:263)
        at org.netbeans.MainImpl$BootClassLoader.allCLIs(MainImpl.java:362)
        at org.netbeans.CLIHandler.initialize(CLIHandler.java:383)
        at org.netbeans.MainImpl.execute(MainImpl.java:190)
        at org.netbeans.MainImpl.main(MainImpl.java:85)
        at org.netbeans.Main.main(Main.java:78)
Loading native libraries
Current Version is 082
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
Handler1=00007FC2EC6D8A40 Handler2=00007FC2EC391FF0 InaccessibleAddress=00007FC2BE266000
RDI=00007FC2BE265FA0 RSI=0000000000000000 RAX=00007FC2BE2617A0 RBX=00007FC2BE2A5500
RCX=0000000000000000 RDX=0000000000000000 R8=000000000003F498 R9=00000000000C0000
R10=0000000000000000 R11=0000003389283F5A R12=00007FC23C51DC40 R13=00007FC23C9AF6E0
R14=00007FC23C872440 R15=00007FC23C872458
RIP=0000003389284478 GS=0000 FS=0000 RSP=00007FC2BE261758
EFlags=0000000000210206 CS=0033 RBP=00007FC2BE2617A0 ERR=0000000000000006
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FC2BE266000
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
xmm2 0000000200000001 (f: 1.000000, d: 4.243992e-314)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 3c3c006325005f5f (f: 620781376.000000, d: 1.517965e-18)
xmm5 00000000befffeb0 (f: 3204448000.000000, d: 1.583208e-314)
xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm9 0000000042580000 (f: 1113063424.000000, d: 5.499264e-315)
xmm10 0000000043b02000 (f: 1135616000.000000, d: 5.610689e-315)
xmm11 3fe0000000000000 (f: 0.000000, d: 5.000000e-01)
xmm12 00000000426d0000 (f: 1114439680.000000, d: 5.506064e-315)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 00000000426d0000 (f: 1114439680.000000, d: 5.506064e-315)
xmm15 0000000044a92800 (f: 1151936512.000000, d: 5.691323e-315)
Module=/lib64/libc.so.6
Module_base_address=0000003389200000
Target=2_40_20130114_134867 (Linux 2.6.32-358.6.1.el6.x86_64)
CPU=amd64 (8 logical CPUs) (0x3ddada000 RAM)
----------- Stack Backtrace -----------
(0x0000003389284478 [libc.so.6+0x84478])
(0x00007FC2BD4B7F24 [i965_dri.so+0x53f24])
brw_vs_precompile+0xab (0x00007FC2BD4B89AB [i965_dri.so+0x549ab])
brw_link_shader+0x385 (0x00007FC2BD4F01C5 [i965_dri.so+0x8c1c5])
_mesa_glsl_link_shader+0xfe (0x00007FC2BD0BA97E [libdricore9.0.0.so.1+0x20097e])
(0x00007FC2BCFC120C [libdricore9.0.0.so.1+0x10720c])
_mesa_meta_glsl_Clear+0x45b (0x00007FC2BD0B3D7B [libdricore9.0.0.so.1+0x1f9d7b])
(0x00007FC2BD498B03 [i965_dri.so+0x34b03])
Java_com_sun_opengl_impl_GLImpl_glClear__I+0x1b (0x00007FC2BDACDEC9 [libjogl.so+0x53ec9])
(0x00007FC2EC6EE895 [libj9vm24.so+0x2a895])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2013/06/12 13:41:16 - please wait.
JVMDUMP032I JVM requested System dump using '/home/skiran/programs/open/gephi/bin/core.20130612.134116.29857.0001.dmp' in response to an event
JVMDUMP032I JVM requested Java dump using '/home/skiran/programs/open/gephi/bin/javacore.20130612.134116.29857.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/skiran/programs/open/gephi/bin/javacore.20130612.134116.29857.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/skiran/programs/open/gephi/bin/Snap.20130612.134116.29857.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/skiran/programs/open/gephi/bin/Snap.20130612.134116.29857.0003.trc
JVMDUMP013I Processed dump event "gpf", detail "".
./../platform/lib/nbexec: line 568: 29857 Segmentation fault      "/usr/lib/jvm/java-1.6.0-ibm.x86_64/bin/java" -Djdk.home="/usr/lib/jvm/java-1.6.0-ibm.x86_64" -classpath "/home/skiran/programs/open/gephi/platform/lib/boot.jar:/home/skiran/programs/open/gephi/platform/lib/org-openide-modules.jar:/home/skiran/programs/open/gephi/platform/lib/org-openide-util.jar:/home/skiran/programs/open/gephi/platform/lib/org-openide-util-lookup.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ar_SA.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_bg.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ca.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_cs.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_de.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_es.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_fr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_gl_ES.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_in_ID.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_it.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ja.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ko.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_nl_NL.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_pl.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_pt_BR.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_pt_PT.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ro.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_ru.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_si.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_sq.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_sv.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_tr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_zh_CN.jar:/home/skiran/programs/open/gephi/platform/lib/locale/boot_zh_TW.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_bg.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ca.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_cs.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_de.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_es.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_fr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_it.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ja.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ko.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_pl.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ro.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_ru.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_si.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_sq.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_sv.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_tr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_bg.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ca.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_cs.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_de.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_es.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_fr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_it.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ja.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ko.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_pl.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ro.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_ru.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_si.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_sq.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_sv.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_tr.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/home/skiran/programs/open/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/java-1.6.0-ibm.x86_64/lib/dt.jar:/usr/lib/jvm/java-1.6.0-ibm.x86_64/lib/tools.jar" -Dnetbeans.system_http_proxy="DIRECT" -Dnetbeans.system_http_non_proxy_hosts="" -Dnetbeans.dirs="./../gephi:./../platform:" -Dnetbeans.home="/home/skiran/programs/open/gephi/platform" '-Xms64m' '-Xmx512m' '-Xverify:none' '-Dsun.java2d.noddraw=true' '-Dsun.awt.noerasebackground=true' '-Dnetbeans.indexing.noFileRefresh=true' '-Dplugin.manager.check.interval=EVERY_DAY' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home/skiran/.gephi/0.8.2/dev/var/log/heapdump.hprof" org.netbeans.Main --userdir "/home/skiran/.gephi/0.8.2/dev" "--branding" "gephi" 0<&0
[skiran@oc6688120108 bin]$

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
