### ISSUE TITLE
gephi crashes on lubuntu 12.10 64-bit

### ISSUE THREAD

**Issue by bbutler-tssg** [gephi/gephi#799]
I have tried to run gephi (v0.8.2beta), downloaded and installed as per the recommendations in [gephi install instructions][1].

My OS is lubuntu 12.10 3.5.0-32-generic 64-bit. I installed Oracle Java JDK [using the PPA described here][2]

The problem shows up shortly after starting gephi, when the screen freezes. Back on the terminal an error log is written with the following text:

    Problematic frame:
    C  [nouveau_dri.so+0xd337b]  std::vector<int, std::allocator<int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, unsigned long, int const&)+0x1cbb

The only way to recover is to kill the java process, at which point lubuntu's error reporting process starts and notes that

    The crashed program seems to use third-party or local libraries:

    ..../gephi/platform/modules/lib/amd64/linux/libjnidispatch-340.so
    ..../gephi/gephi/modules/lib/linux-amd64/libgluegen-rt.so
    ..../gephi/gephi/modules/lib/linux-amd64/libjogl_awt.so
    ..../gephi/gephi/modules/lib/linux-amd64/libjogl.so

It appears that the *native* libraries (above) supplied with gephi do not work with the gephi code running on the Oracle JVM.

I tried again on a different development machine, running the same OS and software, but different hardware. The result was the same.

Therefore it seems to be a problem with gephi-0.8.2 when installed on a 64-bit linux host.

  [1]: https://gephi.org/users/install/
  [2]: http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
