### ISSUE TITLE
Null Pointer Exception + grey screen

### ISSUE THREAD

**Issue by desjarjo** [gephi/gephi#802]
Hi.
I'm on Mac 10.8.4 with Intel HD Graphics 4000 and NVIDIA GeForce GT 650M.

I was building a web of nodes and connection with Gephi 0.8.2 beta since three weeks when I saved to go lunch. when I came back a Null Pointer Exception happened and I can't reopen the file now.
Last job I did was a preview. I don't know if I executed my changes of preview or not.
Is there anyway I can retrieve the data I worked so long to establish?

Also, I can't actually reinstall Gephi. The 0.8.2 version that is now on the web, never opens the software properly. It starts but nothing is loading and we can't access to the file menu, nothings appears in the file drop-down menu.

Can't you help me fast?

Please write to me @ desjar@hotmail.com

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
