### ISSUE TITLE
Cannot Open Saved Files

### ISSUE THREAD

**Issue by daMogli** [gephi/gephi#807]
I use the Neo4j plugin and import a graph db I make. Then after modifying I save the project as a gephi file. When I try to open the project again I get an error message stating that I cannot open the file:

The project file couldn't be opened. Please check the file has .gephi extension. 

NullPointerException - null

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
