### ISSUE TITLE
UNION filter does not work

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi#809]
I create a UNION filter, and drag in it two filters (attribute equal filter on nodes).

=> after filtering, nothing happens.

When used individually, the 2 attribute filters work.

This issue has also been reported on the forum:
https://forum.gephi.org/viewtopic.php?f=30&t=2543&p=8402&hilit=union#p8402

Best,

Clement

**Comment by mbastian** [comment]
This is fixed and will be included in 0.9
