### ISSUE TITLE
crashing when importing from database

### ISSUE THREAD

**Issue by robec1982** [gephi/gephi#810]
Hi,

I have recently intalled the 0.8.2 version of Gephi and it has an odd behavior when trying to get nodes and edges from MySQL database. Actually when I try to append nodes and edges by this way it sometimes crashes if I have not created a new workspace.

I'm running the 32bit version of Gephi in a 64bit Windows PC with Update 25 of JVM 7, also for 64bit.

Kind regards,
Roberto Carlos

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
