### ISSUE TITLE
IllegalArgumentException - [255,255,255] when trying to open a project

### ISSUE THREAD

**Issue by SebGR92** [gephi/gephi#812]
Hello -

I can't open my gephi project anymore (see screenshot). Any idea?

Windows 7
Product Version: Gephi 0.8.2 201210100934
Java: 1.7.0_25; Java HotSpot(TM) Client VM 23.25-b01
System: Windows 7 version 6.1 running on x86; Cp1252; en_FR (gephi)

![image](https://f.cloud.github.com/assets/5222010/954747/375ef050-041d-11e3-825f-ad6a5c549744.png)

Of course, I forgot to mention than my project has the .gephi extension. And this project has been saved from Gephi itself.

**Comment by suburbera** [comment]
Hi, i've tried every workaround suggested here but still, i can't open my .gephi file. 
Any other suggestion?

**Comment by ad2114** [comment]
I've already got my jdkhome set to Java 6 in gephi.conf, but am still getting the error message. Is there another fix?

**Comment by mbastian** [comment]
Closing as this has been fixed through the introduction of a new save/load module in Gephi 0.9.0. Thanks for your patience on this annoying bug.
