### ISSUE TITLE
Networkx gexf parser conflict with gephi importer

### ISSUE THREAD

**Issue by gdbassett** [gephi/gephi#818]
Please reference bug (https://github.com/networkx/networkx/issues/947#issuecomment-24035837) in the networkx project.  To summarize, networkx will export gex and graphml files with multiple attributes with the same name or the same case insensitive name.  Gephi ignores the all but the first occurrence of the attribute name causing loss of attributes during export/import.

I have tried validating the gexf file using:
```
xmllint --noout --schema gexf.xsd mynetwork.gexf
```
however xmllint fails to import the necessary dependencies from gexf.net.  Because I am having trouble validating the file I'm not sure if this is a gephi or a networkx issue.

**Comment by mbastian** [comment]
Hi, this is a bug in Gephi and has been fixed. Patch will be included in 0.9 release. The unicity of an attribute column should only be based on the "id". I tried your example in trunk and it works now.
