### ISSUE TITLE
Cannot open .gephi files saved with filters

### ISSUE THREAD

**Issue by Acotnoir** [gephi/gephi#820]
I have Gephi, 0.8.2-beta installed, yet I cannot open any previous projects that were saved with filters.  I recreated one of the projects and did not build any filters, and I can open it just fine.  Any with filters are giving me the NullPointerException - null error.  Is this related to running Java 7 instead of 6?  I see an unresolved issue with this.

**Comment by mbastian** [comment]
This has been fixed in Gephi 0.9.0. Closing.
