### ISSUE TITLE
Double clicking Gephi file gives erratic behavior on Windows 7.

### ISSUE THREAD

**Issue by andygarcia** [gephi/gephi#829]
Windows 7 x64
Gephi 0.8.2 beta

1. Install Gephi 0.8.2-beta.
2. Start Gephi, create a new project, import nodes, edges from CSV format, create different visualizations, export PNGs, etc.
3. Save file as .gephi format.
4. Close Gephi
5. Double click .gephi file

At this point I'm expecting to return to Gephi in the main graph view with my previously created graph. Instead I get this:

![croppercapture 1](https://f.cloud.github.com/assets/908596/1204011/49c4ab70-255d-11e3-9bf3-943eb5364695.png)

Some observations at this point:

- The dialog has no entry on the taskbar.
- While flows.gephi is the file I double clicked, it seems to only be showing up by virtue of being a recent file.
- Clicking on flows.gephi asks if I want to save the current file or not (which file is this?).
- Clicking do not save causes the dialog to close and it leaves an unaccessible instance of Gephi running in the background.
- Clicking cancel closes the dialog box and leaves Gephi running in the smallest window size possible:

![croppercapture 2](https://f.cloud.github.com/assets/908596/1204035/c533e410-255d-11e3-9a7a-1e116d9ee399.png)

Enlarging this window gives access to a Gephi that is unresponsive doing anything other than being closed.

I notice that the "Open at Startup" is enabled on the Welcome dialog, perhaps disabling this will do something:

1. Close the messed up Gephi instance.
2. Restart via Gephi icon.
3. Uncheck "Open at Startup" on welcome.
4. Close Gephi
5. Double click a .gephi file:

![croppercapture 3](https://f.cloud.github.com/assets/908596/1204070/5620bf02-255e-11e3-8907-0357b56b14d1.png)

This is reproducible every time and I've been seeing all of the above behavior since my first experiences with Gephi, which was around 0.6.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
