### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by ellajakobson** [gephi/gephi#834]
Hi I paid the donation and downloaded gephi for my macbook air, and I did untick the little box in security settings to enable downloads from other suppliers than mac - the gephi does not install!! I click on the insrtall icon, then I get "open" - I click to open and then the icon disappears without a trace....

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
