### ISSUE TITLE
Error and file deletion when importing non-gzipped .gexf files (0.8.2-beta, Linux)

### ISSUE THREAD

**Issue by timholy** [gephi/gephi#835]
I'm on Kubuntu 12.04. I downloaded the [Linux binary](https://gephi.org/users/download/). Rendering `Les Miserables.gexf` as a sample (as presented in the "Welcome to Gephi" start wizard) works fine.

However, rendering a `.gexf` file fails for me. (It appears that there is no file called `Les Miserables.gexf` in the download, so I'm guessing this is stored in some other format.) I tried a few `.gexf` files, including the one in listing 1 in [the primer](http://gexf.net/1.2draft/gexf-12draft-primer.pdf) as well as [this one](http://gephi.org/datasets/LesMiserables.gexf). Nothing appears on the screen, but even more strangely the file itself gets deleted, and I have to download it again.

However, if I gzip the file first, then it works fine.

**Comment by eduramiba** [comment]
Related issue: #1041
