### ISSUE TITLE
Clearly present the range bound numbers as editable on Filter UI

### ISSUE THREAD

**Issue by ghost** [gephi/gephi#838]
(This is more of a usability case than an actual bug.)

I am using Windows 7. When I apply a filter, such as degree, I receive a slider to play with. It took me a while before I understood that I could also change the numbers below the slider. I believe it would be a lot clearer if the numbers had a lighter rectangle background.

**Comment by mbastian** [comment]
I agree, it's really not obvious that one can double-click on the numbers

**Comment by eduramiba** [comment]
To be addressed in #1476
