### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by caar2000** [gephi/gephi#839]
I have the correct java version 
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-457-11M4509)

I tried the workaround in the forum and this do not solve the issue.

Do you have time to fix this issue?

Regards
Carlos

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
