### ISSUE TITLE
Why gephi slow down when I show the node labels?

### ISSUE THREAD

**Issue by aisensiy** [gephi/gephi#845]
I have a network with 1882 nodes and 2612 edges. It works well without the labels of nodes. But when I toggle the labels. The network preview become super slow. The whole view just stopped. Every animation takes 3 or 4 seconds. So I have to hide the labels or I can not continue my work.

I use macbook air with 4GB memory and 4 cores. And the label is Chinese. And the gephi version is 0.8.2. Hope someone can help me.

Thanks in advance.

**Comment by mbastian** [comment]
Please try again with the new 0.9.1 version. I suspect it might have improved the rendering speed on Mac OS X. Closing.
