### ISSUE TITLE
Problems runn ing it in Mac OSX Maverick

### ISSUE THREAD

**Issue by gangolly** [gephi/gephi#846]
Doesn't seem to open in Maverick.

Shalll appreciate help

Jagdish

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
