### ISSUE TITLE
Incorrect edge weight values when importing large GEXF file

### ISSUE THREAD

**Issue by timbunce** [gephi/gephi#859]
I have a GEXF file where all the edges (4272 of them) have weight="1" or weight="2".

When I load it and view the data in the laboratory a small percentage (about 120) have weights between 4 and 156.

I've uploaded [the GEXF file](https://www.dropbox.com/s/nqur25c3uc3gmtb/gephi_weight_bug_example_sizeme2.gexf).

**Comment by mbastian** [comment]
This has been fixed, the wording now says weights are "merged"
