### ISSUE TITLE
Scaling factors for expension/contraction

### ISSUE THREAD

**Issue by kludikovsky** [gephi/gephi#860]
(Note: Just new to this program, so forgive me if I am wrong.)

The scaling factors for the expansion and contraction seem to be directly linked. So when changing one the other seems to change to the same value, resulting that expansion and contraction do the identical thing.

Possibly the intention was to have the one as the reverse (1/x) of the other, or have two different variables.

**Comment by AritzBi** [comment]
This keeps happening in 0.9 and 0.9.1, if you firstly choose contraction then the expansion will work as a contraction and in reverse other happens the same.
