### ISSUE TITLE
Reusable Modularised Components

### ISSUE THREAD

**Issue by sirinath** [gephi/gephi#867]
Is it possible that Graphi be made into modules which can be separately downloaded from Maven Central so that the particular functionality can be used with your application.

Also the components can have their own tutorials.

**Comment by mbastian** [comment]
Yes, this will be the default in the next version.

**Comment by sirinath** [comment]
Can you consider moving to ASL 2.0 which is more business friendly than the current choice?

**Comment by techtonik** [comment]
And also make those modules easy to write without Maven or recompilation (Jython).

**Comment by mbastian** [comment]
@techtonik Easy to write? Can you explain I'm not sure I understand.

**Comment by techtonik** [comment]
@mbastian I mean allow plugins in Python-like scripting language instead of Java. Those that don't require compilation,
