### ISSUE TITLE
Gephi 8.2 Beta

### ISSUE THREAD

**Issue by JETrimble** [gephi/gephi#869]
I have a Macintosh Pro with OS X 10.8.5 and I am not able to open Gephi 8.2 beta. I have a Macintosh Air with OS X 10.8.5 and I am able to open it. Can't seem to understand the source of the problem.
Thanks for you assistance....
--Joseph T.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
