### ISSUE TITLE
Output interactive, embeddable JavaScript visualizations

### ISSUE THREAD

**Issue by brylie** [gephi/gephi#880]
It would be great to output Gephi graphs as interactive, embeddable JavaScript visualizations. For example, exporting a Gephi graph to D3.js or ngraph:
http://d3js.org
https://github.com/anvaka/ngraph
https://github.com/anvaka/ngraph/tree/master/examples/fabric.js/Node%20and%20Browser

**Comment by eduramiba** [comment]
Try this plugin https://marketplace.gephi.org/plugin/sigmajs-exporter/
