### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Karwan86** [gephi/gephi#884]
Thank you very much for offering this software. I am PG student in the university of exeter. Now, I am doing aaresearch and using this sofware. Thanks

Kind regards
Karwan Ali

**Comment by eduramiba** [comment]
![funny-cat-pics-internet-high-five](https://cloud.githubusercontent.com/assets/197285/9500412/9659c7ae-4c25-11e5-9bfc-ddf7a98fbbf6.jpg)
