### ISSUE TITLE
Excel import docs are incorrect

### ISSUE THREAD

**Issue by techtonik** [gephi/gephi#888]
https://gephi.org/users/supported-graph-formats/spreadsheet/

I don't know if this page is linked from site, but it is the first on Google. Docs say that the format is not CSV, but it is CSV. After reading the doc, people are trying to rename .xsls files to .csv  The doc can surely be improved, but I don't know where is the source for it.

**Comment by eduramiba** [comment]
Now imporoved and unified with #1282
