### ISSUE TITLE
Changing gephi.conf Mac OSX

### ISSUE THREAD

**Issue by mrte90** [gephi/gephi#889]
When I tried to change gephi.conf to allow import of a large data text file (500mb+), but it keeps telling me that "gephi has been damaged and cannot be opened". I viewed the instructions and only  edited the -xms section of the txt file. help please!

Thanks

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
