### ISSUE TITLE
Gephi 0.8.2 doesn't open graphs

### ISSUE THREAD

**Issue by deemeetree** [gephi/gephi#891]
Gephi 0.8.2 doesn't open graphs on my computer, Mac OS X 10.9.1 with the latest Java (from Oracle).

The file itself is read (the dialog shows the number of nodes and edges, etc.), but when I click OK to open it in the Graph pane, the spinning wheel is circling endlessly.

I have Gephi 0.7 beta installed and that opens the graphs fine.

What might be the problem?

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
