### ISSUE TITLE
General Usage and OrientDB streaming didn't work

### ISSUE THREAD

**Issue by eptx** [gephi/gephi#893]
1)Using OSX 10.9.1
App hung often requiring a force quit.

2) Installed streaming plugin to connect to OrientDB 1.7
Url in browser brought back data but Gephi hung and reported error:
"Command not found: POST.gephi/GratefulDeadConcerts/sql/select from V"
Here's the url hitting an OrientDB out-of-box demo database:
http://localhost:2480/gephi/GratefulDeadConcerts/sql/select%20from%20V
(couldn't find a way to edit the url?)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
