### ISSUE TITLE
Update  OS X Installation Instructions

### ISSUE THREAD

**Issue by pbronez** [gephi/gephi#895]
The [installation instructions](http://gephi.org/users/install/) for OS X are insufficient to get mac users up and running with Gephi on OSX 10.8 or newer. The instructions should be updated with a concise version of the procedure detailed in issue #748 until a new release fixes the problems.

## Procedure
Issue #748 boils down to essentially:

- Delete `/users/.../Library/Application Support/gephi/ ` if present
- Install [Apple's Java 6 release](http://support.apple.com/kb/DL1572?viewlocale=en_US)
- Download Gephi, extract to `Applications` directory (*do NOT open it from the DMG window*)
- Modify `/Applications/Gephi.app/Contents/Resources/gephi/etc/gephi.conf`  to include `jdkhome="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"` or similar
- Launch Gephi from the Applications folder and load a sample graph to confirm installation was successful.

Note that even when these procedures are successful, there are still other usability bugs on OS X. For example, you can't drag to pan the preview window.

## Impact
There are many open issues regarding this bug, including: #443, #485, #726, #728, #816, #817, #821, #834, #842, #848, #846, #875, #879, #889 . This issues should all be closed or marked as duplicates with pointers to #748 as a solution.

## Background
Newer versions of OS X no longer include JRE 6, and Gephi is not fully compatible with JRE 7. Thus OS X users must install an old version of Java and modify Gephi's code to point to the old JRE.

Similarly, Gephi stores configuration information in `/users/.../Library/Application Support/gephi/ `. This information needs to be deleted, if present, before installing Gephi. Failing to do so will cause Gephi to work from its DMG but not from the Applications folder.

**Comment by gmhoward** [comment]
Instructions by @pbronez worked on my Mac with OS X Mavericks (10.9.5), and installing Gephi 0.8.2. Only had to change location of JDK Home:
```jdkhome = "/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home"```

Thanks!

**Comment by mbastian** [comment]
Closing as we finally solved this with Gephi 0.9.0. Thanks for your help on putting these instructions here in the meantime.
