### ISSUE TITLE
Cannot compile VisualizationImpl module in master branch 

### ISSUE THREAD

**Issue by markfarrell** [gephi/gephi#901]
Hi, 

My build fails when running 'mvn clean install' with the log:

    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR]      /users/m4farrel/gephi/modules/VisualizationImpl/src/main/java/org/gephi/visualization/ bridge/DataBridge.java:[187,33] error: cannot find symbol
    [INFO] 1 error
    [INFO] -------------------------------------------------------------

Here is my system information, if it is relevant:

    Linux gwem 3.5.0-47-generic #71-Ubuntu SMP Wed Feb 19 00:00:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eduramiba** [comment]
Already fixed.
