### ISSUE TITLE
GEXF (Export -> Graph File)

### ISSUE THREAD

**Issue by mmorini** [gephi/gephi#904]
Dear all,

I think I might have found a tiny bug in Gephi's "Export -> Graph
file..." function, when writing gexf files.

If I've understood correctly, gephi, by default, writes "1.2draft" XML
Schema files. We've had problems transporting such files into LANL's
networkx python package, which led to some investigation.

Apparently, while 1.2draft files require RGBA color representation,
gephi exports RGB (no alpha channel information) only, in conformity with
1.1draft.

Hope this helps.

-M

**Comment by mbastian** [comment]
Hi, I'm not sure when this was corrected by the GEXF export does export to RGBA. It does however omit the "A" if the alpha is equal to 1.0. Maybe that could be the source of the issue.
