### ISSUE TITLE
Error while exporting a graph as a GML file

### ISSUE THREAD

**Issue by ghost** [gephi/gephi#905]
I'm just learning how to use the toolkit, and need to work with GML files. While going through the basic toolkit tutorial, I attempted to export a simple graph using the example provided

ExportController ec = workspace.getLookup().lookup(ExportController.class);
try {
	ec.exportFile(new File("test.gexf"), workspace);
} catch (IOException e) {
	e.printStackTrace();
}

That ran quite allright. However, when executing it with .gml, I kept receiving the exception:
Exception in thread "main" java.lang.NullPointerException
	at org.gephi.io.exporter.plugin.ExporterGML.execute(ExporterGML.java:119)
	at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:131)
	at org.gephi.io.exporter.impl.ExportControllerImpl.exportFile(ExportControllerImpl.java:97)
	at Tryouts.main(Tryouts.java:49)

As far as I could tell, the problem is, that ExporterGML.execute() uses the variable 'progressTicket' which is actually never set. I tried generating a ProgressTicket on my own by using 
ProgressTicketProvider progressProvider = Lookup.getDefault().lookup(ProgressTicketProvider.class);

as in the example of the wiki, but 'progressProvider' was always 'null'.

**Comment by mbastian** [comment]
This issue has been fixed in commit ded902078dda471ff65708544804fc9b53f393f7 and the patch will be included in the upcoming 0.9 release. Thanks for reporting.
