### ISSUE TITLE
Crash at startup on Ubuntu 14.04, intel integrated graphics

### ISSUE THREAD

**Issue by alain40** [gephi/gephi#909]
-------------------------------------------------------------------------------
>Log Session: Wednesday, April 23, 2014 11:25:58 AM PDT
>System Info: 
  Product Version         = Gephi 0.8.2 201210100934
  Operating System        = Linux version 3.13.0-24-generic running on amd64
  Java; VM; Vendor        = 1.8.0_05; Java HotSpot(TM) 64-Bit Server VM 25.5-b02; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_05-b13
  Java Home               = /usr/lib/jvm/java-8-oracle/jre
  System Locale; Encoding = en_US (gephi); UTF-8
  Home Directory          = /home/alain
  Current Directory       = /home/alain/Scripts.Programs/gephi/bin
  User Directory          = /home/alain/.gephi/0.8.2/dev
  Cache Directory         = /home/alain/.gephi/0.8.2/dev/var/cache
  Installation            = /home/alain/Scripts.Programs/gephi/gephi
                            /home/alain/Scripts.Programs/gephi/platform
                            /home/alain/Scripts.Programs/gephi/platform
  Boot & Ext. Classpath   = /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar
  Application Classpath   = /home/alain/Scripts.Programs/gephi/platform/lib/boot.jar:/home/alain/Scripts.Programs/gephi/platform/lib/org-openide-modules.jar:/home/alain/Scripts.Programs/gephi/platform/lib/org-openide-util.jar:/home/alain/Scripts.Programs/gephi/platform/lib/org-openide-util-lookup.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ar_SA.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_bg.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ca.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_cs.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_de.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_es.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_fr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_it.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ja.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ko.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_pl.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_pt_PT.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ro.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_ru.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_si.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_sq.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_sv.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_tr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/boot_zh_TW.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ar_SA.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_bg.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ca.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_cs.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_de.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_es.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_fr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_it.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ja.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ko.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_pl.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_pt_PT.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ro.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_ru.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_si.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_sq.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_sv.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_tr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-modules_zh_TW.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ar_SA.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_bg.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ca.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_cs.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_de.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_es.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_fr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_it.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ja.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ko.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_bg.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_ca.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_cs.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_de.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_es.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_fr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_it.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_ja.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_ko.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_pl.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_ro.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_ru.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_si.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_sv.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_tr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_pl.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_pt_PT.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ro.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_ru.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_si.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_sq.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_sv.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_tr.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/lib/locale/org-openide-util_zh_TW.jar:/usr/lib/jvm/java-8-oracle/lib/dt.jar:/usr/lib/jvm/java-8-oracle/lib/tools.jar
  Startup Classpath       = /home/alain/Scripts.Programs/gephi/platform/core/core.jar:/home/alain/Scripts.Programs/gephi/platform/core/org-openide-filesystems.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_cs.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ro.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_de.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_es.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ca.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_it.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_zh_TW.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ko.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_pt_PT.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ro.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_pl.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_fr.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_si.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_tr.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ja.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ru.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_bg.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_pl.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ca.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_pt_PT.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_tr.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_sv.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_sv.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_it.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_si.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_es.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_cs.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_sq.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_fr.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_de.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ru.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_pt_BR.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ko.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ar_SA.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_zh_TW.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_ja.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_gl_ES.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_nl_NL.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_in_ID.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_bg.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_ar_SA.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/core_zh_CN.jar:/home/alain/Scripts.Programs/gephi/platform/core/locale/org-openide-filesystems_sq.jar:/home/alain/Scripts.Programs/gephi/bin/./../gephi/core/locale/core_gephi.jar
-------------------------------------------------------------------------------
java.lang.IllegalStateException: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:423)
	at org.openide.util.WeakListenerImpl.create(WeakListenerImpl.java:164)
	at org.openide.util.WeakListeners.create(WeakListeners.java:271)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:125)
	at org.openide.filesystems.MultiFileObject.<init>(MultiFileObject.java:142)
	at org.openide.filesystems.MultiFileSystem.getMultiRoot(MultiFileSystem.java:267)
	at org.openide.filesystems.MultiFileSystem.findResource(MultiFileSystem.java:355)
	at org.openide.filesystems.FileUtil.getConfigFile(FileUtil.java:2276)
	at org.openide.filesystems.FileUtil.getConfigRoot(FileUtil.java:2306)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:158)
	at org.netbeans.core.startup.Main.start(Main.java:305)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class org.openide.filesystems.$Proxy0 with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:398)
	at org.openide.util.WeakListenerImpl$ProxyListener.<init>(WeakListenerImpl.java:413)
	... 12 more

------------------------------------------------------------------------------------------------------------OS:

Linux 3.13.0-24-generic amd64
Java:

version: 24.51-b03
OpenJDK 64-Bit Server VM, Oracle Corporation
OpenGL version:

2.1 Mesa 10.1.0
Vendor:

Intel Open Source Technology Center
Renderer:

Mesa DRI Intel(R) G45/G43

Mr. MyOGL
Shading language:

1.20
OpenGL extensions:

 GL_3DFX_texture_compression_FXT1
 GL_AMD_seamless_cubemap_per_texture
 GL_AMD_shader_trinary_minmax
 GL_ANGLE_texture_compression_dxt3
 GL_ANGLE_texture_compression_dxt5
 GL_APPLE_object_purgeable
 GL_APPLE_packed_pixels
 GL_APPLE_vertex_array_object
 GL_ARB_ES2_compatibility
 GL_ARB_clear_buffer_object
 GL_ARB_color_buffer_float
 GL_ARB_copy_buffer
 GL_ARB_debug_output
 GL_ARB_depth_buffer_float
 GL_ARB_depth_clamp
 GL_ARB_depth_texture
 GL_ARB_draw_buffers
 GL_ARB_draw_elements_base_vertex
 GL_ARB_draw_instanced
 GL_ARB_explicit_attrib_location
 GL_ARB_fragment_coord_conventions
 GL_ARB_fragment_program
 GL_ARB_fragment_program_shadow
 GL_ARB_fragment_shader
 GL_ARB_framebuffer_object
 GL_ARB_framebuffer_sRGB
 GL_ARB_get_program_binary
 GL_ARB_half_float_pixel
 GL_ARB_half_float_vertex
 GL_ARB_instanced_arrays
 GL_ARB_internalformat_query
 GL_ARB_invalidate_subdata
 GL_ARB_map_buffer_alignment
 GL_ARB_map_buffer_range
 GL_ARB_multisample
 GL_ARB_multitexture
 GL_ARB_occlusion_query
 GL_ARB_occlusion_query2
 GL_ARB_pixel_buffer_object
 GL_ARB_point_parameters
 GL_ARB_point_sprite
 GL_ARB_provoking_vertex
 GL_ARB_robustness
 GL_ARB_sampler_objects
 GL_ARB_seamless_cube_map
 GL_ARB_shader_bit_encoding
 GL_ARB_shader_objects
 GL_ARB_shader_texture_lod
 GL_ARB_shading_language_100
 GL_ARB_shadow
 GL_ARB_sync
 GL_ARB_texture_border_clamp
 GL_ARB_texture_compression
 GL_ARB_texture_compression_rgtc
 GL_ARB_texture_cube_map
 GL_ARB_texture_env_add
 GL_ARB_texture_env_combine
 GL_ARB_texture_env_crossbar
 GL_ARB_texture_env_dot3
 GL_ARB_texture_float
 GL_ARB_texture_mirror_clamp_to_edge
 GL_ARB_texture_mirrored_repeat
 GL_ARB_texture_non_power_of_two
 GL_ARB_texture_rectangle
 GL_ARB_texture_rg
 GL_ARB_texture_rgb10_a2ui
 GL_ARB_texture_storage
 GL_ARB_texture_swizzle
 GL_ARB_transpose_matrix
 GL_ARB_vertex_array_bgra
 GL_ARB_vertex_array_object
 GL_ARB_vertex_attrib_binding
 GL_ARB_vertex_buffer_object
 GL_ARB_vertex_program
 GL_ARB_vertex_shader
 GL_ARB_vertex_type_2_10_10_10_rev
 GL_ARB_window_pos
 GL_ATI_blend_equation_separate
 GL_ATI_draw_buffers
 GL_ATI_envmap_bumpmap
 GL_ATI_separate_stencil
 GL_ATI_texture_env_combine3
 GL_ATI_texture_float
 GL_EXT_abgr
 GL_EXT_bgra
 GL_EXT_blend_color
 GL_EXT_blend_equation_separate
 GL_EXT_blend_func_separate
 GL_EXT_blend_minmax
 GL_EXT_blend_subtract
 GL_EXT_compiled_vertex_array
 GL_EXT_copy_texture
 GL_EXT_draw_buffers2
 GL_EXT_draw_instanced
 GL_EXT_draw_range_elements
 GL_EXT_fog_coord
 GL_EXT_framebuffer_blit
 GL_EXT_framebuffer_object
 GL_EXT_framebuffer_sRGB
 GL_EXT_gpu_program_parameters
 GL_EXT_multi_draw_arrays
 GL_EXT_packed_depth_stencil
 GL_EXT_packed_float
 GL_EXT_packed_pixels
 GL_EXT_pixel_buffer_object
 GL_EXT_point_parameters
 GL_EXT_polygon_offset
 GL_EXT_provoking_vertex
 GL_EXT_rescale_normal
 GL_EXT_secondary_color
 GL_EXT_separate_shader_objects
 GL_EXT_separate_specular_color
 GL_EXT_shadow_funcs
 GL_EXT_stencil_two_side
 GL_EXT_stencil_wrap
 GL_EXT_subtexture
 GL_EXT_texture
 GL_EXT_texture3D
 GL_EXT_texture_array
 GL_EXT_texture_compression_dxt1
 GL_EXT_texture_compression_rgtc
 GL_EXT_texture_compression_s3tc
 GL_EXT_texture_cube_map
 GL_EXT_texture_edge_clamp
 GL_EXT_texture_env_add
 GL_EXT_texture_env_combine
 GL_EXT_texture_env_dot3
 GL_EXT_texture_filter_anisotropic
 GL_EXT_texture_integer
 GL_EXT_texture_lod_bias
 GL_EXT_texture_object
 GL_EXT_texture_rectangle
 GL_EXT_texture_sRGB
 GL_EXT_texture_sRGB_decode
 GL_EXT_texture_shared_exponent
 GL_EXT_texture_snorm
 GL_EXT_texture_swizzle
 GL_EXT_vertex_array
 GL_EXT_vertex_array_bgra
 GL_IBM_multimode_draw_arrays
 GL_IBM_rasterpos_clip
 GL_IBM_texture_mirrored_repeat
 GL_INGR_blend_func_separate
 GL_KHR_debug
 GL_MESA_pack_invert
 GL_MESA_texture_signed_rgba
 GL_MESA_window_pos
 GL_MESA_ycbcr_texture
 GL_NV_blend_square
 GL_NV_conditional_render
 GL_NV_depth_clamp
 GL_NV_light_max_exponent
 GL_NV_packed_depth_stencil
 GL_NV_primitive_restart
 GL_NV_texgen_reflection
 GL_NV_texture_env_combine4
 GL_NV_texture_rectangle
 GL_OES_EGL_image
 GL_OES_read_format
 GL_S3_s3tc
 GL_SGIS_generate_mipmap
 GL_SGIS_texture_border_clamp
 GL_SGIS_texture_edge_clamp
 GL_SGIS_texture_lod
 GL_SUN_multi_draw_arrays
Max values:

GL_MAX_LIST_NESTING: 64
GL_MAX_ATTRIB_STACK_DEPTH: 16
GL_MAX_MODELVIEW_STACK_DEPTH: 32
GL_MAX_NAME_STACK_DEPTH: 64
GL_MAX_PROJECTION_STACK_DEPTH: 32
GL_MAX_TEXTURE_STACK_DEPTH: 10
GL_MAX_EVAL_ORDER: 30
GL_MAX_LIGHTS: 8
GL_MAX_CLIP_PLANES: 8
GL_MAX_TEXTURE_SIZE: 8192
GL_MAX_PIXEL_MAP_TABLE: 256
GL_MAX_VIEWPORT_DIMS: 16384
GL_MAX_CLIENT_ATTRIB_STACK_DEPTH: 16
GL_MAX_3D_TEXTURE_SIZE: 256
GL_MAX_ELEMENTS_VERTICES: 3000
GL_MAX_ELEMENTS_INDICES: 3000
GL_MAX_TEXTURE_UNITS: 8
GL_MAX_CUBE_MAP_TEXTURE_SIZE: 2048
GL_MAX_TEXTURE_LOD_BIAS: 14
GL_MAX_DRAW_BUFFERS: 8
GL_MAX_VERTEX_ATTRIBS: 16
GL_MAX_TEXTURE_COORDS: 8
GL_MAX_TEXTURE_IMAGE_UNITS: 16
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: 16384
GL_MAX_VERTEX_UNIFORM_COMPONENTS: 16384
GL_MAX_VARYING_FLOATS: 64
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: 16
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: 32
GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB: 4
GL_MAX_PROGRAM_MATRICES_ARB: 8
GL_MAX_VERTEX_ATTRIBS_ARB: 16
GL_MAX_TEXTURE_COORDS_ARB: 8
GL_MAX_TEXTURE_IMAGE_UNITS_ARB: 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB: 16384
GL_MAX_VARYING_FLOATS_ARB: 64
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB: 16
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB: 32
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS_ARB: 16384
GL_MAX_DRAW_BUFFERS_ARB: 8
GL_MAX_RECTANGLE_TEXTURE_SIZE_ARB: 4096
GL_MAX_TEXTURE_LOD_BIAS_EXT: 14
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT: 16
GL_MAX_SHININESS_NV: 128
GL_MAX_SPOT_EXPONENT_NV: 128
GL_MAX_RECTANGLE_TEXTURE_SIZE_NV: 4096
GL_MAX_TRACK_MATRIX_STACK_DEPTH_NV: 4
GL_MAX_TRACK_MATRICES_NV: 8
GL_MAX_RECTANGLE_TEXTURE_SIZE_EXT: 4096
GL_MAX_DRAW_BUFFERS_ATI: 8
GL_MAX_TEXTURE_COORDS_NV: 8
GL_MAX_TEXTURE_IMAGE_UNITS_NV: 16
GL_MAX_RENDERBUFFER_SIZE_EXT: 8192
GL_MAX_COLOR_ATTACHMENTS_EXT: 8
GL_MAX_VARYING_COMPONENTS_EXT: 64
GL_MAX_ARRAY_TEXTURE_LAYERS_EXT: 512
Current display mode:

1920x1080
Supported display modes:

1920x1080

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
