### ISSUE TITLE
Gephi generates invalid GML files

### ISSUE THREAD

**Issue by count0** [gephi/gephi#919]
Every GML file generated by Gephi contains the "Creator" attribute as follows

```
graph
[
  Creator Gephi
  ...
```

However, this does not conform to the GML syntax, since attribute values can be only of type Integer, Real, String and Lists, and Strings need to be quoted. The correct format would therefore be:

```
graph
[
  Creator "Gephi"
  ...
```

The current Gephi form throws off GML readers which adhere to the strict syntax, such as the one in graph-tool.

**Comment by mbastian** [comment]
Closing as fixed in #920
