### ISSUE TITLE
File can't have repeated column names

### ISSUE THREAD

**Issue by praveenpankaj** [gephi/gephi#921]
Hi

I have a data sheet in csv that has column labels that have both text and numbers to distinguish between the columns. Gephi treats them as identical. Let us say I have a column name with Temperature1 and Temperature2, they are treated as repeated columns than unique.
As the data is obtained from automatic sensors, I don't have any control over these labels and renaming them is impossible as there are many of them. Any help would be appreciated.

Thanks
Praveen

**Comment by eduramiba** [comment]
I wasn't able to reproduce this in Gephi 0.8.2 or 0.9.

Is it possible that the file didn't have a header row with column names and just the values?

**Comment by eduramiba** [comment]
Actually I can reproduce it now in 0.8.2 but not in 0.9 snapshot.
I think I tested it twice in 0.9
