### ISSUE TITLE
Edges between nodes in a hierarchical graph fail to import from GEXF

### ISSUE THREAD

**Issue by Fazerty** [gephi/gephi#929]
The edges are missing when the file http://gexf.net/data/hierarchy1.gexf is imported in gephi.

**Comment by mbastian** [comment]
This is indeed a problem in 0.8.2 as only edges between the leaf level are allowed. Gephi 0.9 removes the support for hierarchical graphs so all nodes in the given will be imported and therefore this should work, but of course without the hierarchy.
