### ISSUE TITLE
Attributes not inserted when importing custom .gexf file

### ISSUE THREAD

**Issue by 1915** [gephi/gephi#931]
I wrote a small script which generated a .gexf-file. The file had several custom attributes for the nodes, which were not inserted even though the file was xml-compliant.

The problem was that gephi expects the <attributes> declaration before the <nodes> but my script wrote the <attributes> last, in the end of the file. Made more sense for me at the time.

Allthough not a very serious issue I think it would be better design to accept the <attributes> data in any order, before or after the <nodes>.

In other news, great software!

**Comment by mbastian** [comment]
Hi, thanks for the suggestion but this is currently not possible as we perform a bunch of verification when values are set and therefore need to have the column definition.
