### ISSUE TITLE
Compilation Failure: Failed to execute compile goal on project utils-longtask

### ISSUE THREAD

**Issue by gupta-ankit** [gephi/gephi#934]
I tried to compile gephi on my machine. I am using Netbeans to manage my projects. When I try to build the project, I get the following compilation errors.

    Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project utils-longtask: Compilation failure

Can someone tell me how to fix this problem?

**Comment by mbastian** [comment]
Closing old issue. This should be resolved.
