### ISSUE TITLE
Headless export to gefx yields empty file

### ISSUE THREAD

**Issue by nicolamr** [gephi/gephi#935]
Following the toolkit instructions to export a graph doesn't work. Resulting file is empty.
https://wiki.gephi.org/index.php/Toolkit_-_Export_graph

This file might be the problematic one, since all the export functionality seems to have been commented out:

https://github.com/gephi/gephi/blob/master/modules/ExportPlugin/src/main/java/org/gephi/io/exporter/plugin/ExporterGEXF.java

**Comment by mbastian** [comment]
This is now fixed in `trunk`. Sorry about that, it was temporary until we finished some other dynamic related things. The exporter now follows the draft 1.3 specifications described in #1152.
