### ISSUE TITLE
Data Laboratory rows issue when finishing edit

### ISSUE THREAD

**Issue by AVermeij** [gephi/gephi#951]
When manually editing attributes in the Data Laboratory and saving the changes by hitting Enter or clicking outside of the edited field, Gephi often (but not always) reshifts the order of the rows, moving the edited row to the bottom of the data. 

This is unwanted behavior in many use cases, especially when there is a need to edit multiple entries after alphabetical sorting of data by clicking column titles. In the current situation, one needs to manually sort and locate the next entry again, instead of simply being able to move down one row after finishing an edit.

Is there a reason for this specific behavior, or should it be fixed?

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
