### ISSUE TITLE
Ejecución del programa principal

### ISSUE THREAD

**Issue by WilliamTorrez** [gephi/gephi#952]
El problema que tengo es el siguiente:
*Al ejecutar el programa Gephi no se ejecuta por completo el programa, creo que hay un error en el arranque del programa para SO Windows. Por favor resuelvan el problema.

Gracias.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
