### ISSUE TITLE
Import Spreadsheet in Data Lab falsifies some data

### ISSUE THREAD

**Issue by Snurb** [gephi/gephi#954]
Hi,

I'm getting some very problematic behaviour when I use Import Spreadsheet in Data Lab to import additional node information into an existing network dataset.

I have a large-ish network (140,450 nodes, 22.8m edges) which has already been visualised. I'm now trying to import additional node attributes into the data table for this network, using Import Spreadsheet to import a CSV file of the following format:

Id, State, Town
2519, WA, Unknown
3570, Vic, Melbourne
3711, Vic, Melbourne
3712, ACT, Canberra
...

The CSV file contains exactly the same IDs as the existing network data, so no new nodes should be created by the import - all that should happen is that my data table gets two more columns, State and Town.

After importing, though, a small number of additional nodes are created which have duplicate IDs, while the corresponding existing nodes in the original network are assigned the wrong values for State and Town - I now have:

Id, Degree, State, Town
2519, 13, NSW, Unknown
2519, 0, WA, Unknown
3570, 372, NSW, Sydney
3570, 0, Vic, Melbourne
...

The first and third of these are nodes from my original network - you can tell because they have a degree value. These have been given incorrect values for State and Town. The second and fourth are newly-created nodes (degree is 0), with the values for State and Town as they should be.

I'm particularly confused by the face that I now have multiple nodes with the same ID - my understanding was that node IDs in Gephi are unique.

I've exported the data table from Gephi and run a comparison between what should have been imported and what was actually imported - in all, this affects around 150 nodes our of the total 140k in my case, and the error is reproducible: it always affects the same nodes. There's a cluster of about 60 of these cases at the start of the ID list (which is sorted smallest to largest); others are scattered throughout the list.

I've also created a separate CSV that contains only the falsely imported nodes, and tried to import only this into the data table - this again results in the creation of duplicate nodes, rather than in the CSV data being added to the existing nodes. I've encountered the same problem when importing other spreadsheets with different additional columns, too.

Help ? While only a relatively small number of nodes are affected in my case, I'm concerned that this issue could cause some significant problems if it happens to affect key nodes in a network. And of course the fact that the affected existing nodes aren't just left alone, but that incorrect State and Town values are assigned to them as well (from who knows where) is particularly concerning, too.

System information:

Product Version: Gephi 0.8.2 201210100934
Java: 1.7.0_65; Java HotSpot(TM) 64-Bit Server VM 24.65-b04
System: Windows 7 version 6.1 running on amd64; Cp1252; en_AU (gephi)

Many thanks in advance, 

Axel Bruns

**Comment by eduramiba** [comment]
Closing old issue, should be fixed with #1282
