### ISSUE TITLE
Gephi should be DPI-aware or offer a DPI setting

### ISSUE THREAD

**Issue by pdbogen** [gephi/gephi#961]
With the growing prevalence of high-DPI / retina screens, it's increasingly important that applications either detect screen DPI, allow a configuration setting to set it, or both; applications that do neither and thus implicitly assume a DPI of 96 are increasingly unusable, and will grow more unusable as pixel densities increase.

**Comment by mbastian** [comment]
Agreed, the experience is poor and blurry otherwise. I have a patch ready to enable high-dpi resolution, automatically adjusting to the screen DPI.
