### ISSUE TITLE
Issues with installing Gephi

### ISSUE THREAD

**Issue by SubashSP** [gephi/gephi#963]
I had installed Gephi but when i try to open it it's not working. Could any one please help me.

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
