### ISSUE TITLE
Duplicate dynamic attribute value in GEFX causes Gephi to fail silently

### ISSUE THREAD

**Issue by Infeligo** [gephi/gephi#964]
When I try to open a GEFX file that has a duplicate attribute value (same value for the same period twice) Gephi does not report any errors and silently fails to load the file.

Here is an example file that causes this problem (a modified version of primer dynamics_openintervals.gexf): http://pastebin.com/gHH7MFFZ

**Comment by mbastian** [comment]
Thanks for the report, this is now fixed and will be included in 0.9 release.
