### ISSUE TITLE
Java error when opening a .csv file 

### ISSUE THREAD

**Issue by zararah** [gephi/gephi#966]
![screen shot 2014-10-21 at 15 45 32](https://cloud.githubusercontent.com/assets/5320182/4720945/e976cb60-5934-11e4-9b3a-d56cfe5869bb.png)

I've installed Gephi 0.8.2-beta but can't seem to open any files. When I select a .csv from 'Open' I get the error above.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
