### ISSUE TITLE
Data laboratory doesn't show anything

### ISSUE THREAD

**Issue by CoDEmanX** [gephi/gephi#968]
If I generate a random graph or load one of the example files and switch to data lab, there's nothing shown but the 3 buttons to switch mode. No context menu either, so should be the same with any graph (also newly created ones).

Latest v0.9 snapshot on Windows 8.1, 64bit

**Comment by eduramiba** [comment]
Hi,
Gephi 0.9 snapshot is still not ready to be usable, and many modules are deactivated.
