### ISSUE TITLE
please deploy a debian package for gephi

### ISSUE THREAD

**Issue by VishwaPrabhakar** [gephi/gephi#976]
having trouble in running in ubuntu 14.04 so it will be much convenient if there is any .deb package

**Comment by PanderMusubi** [comment]
See also https://bugs.launchpad.net/ubuntu/+bug/898642

**Comment by jkufner** [comment]
See also https://wiki.debian.org/Packaging

**Comment by rugk** [comment]
Any news here? Getting it into the official packages would be nice…

But I've read this only works with Java's SDK and not Open JDK, so does it depend on proprietary software? This could be a blocker for including it in Debian…

**Comment by geofurb** [comment]
Can we make this happen? Gephi's a pretty popular tool, and this is a real downside when it comes to keeping it up-to-date.

**Comment by mbastian** [comment]
We have a snapcraft now https://snapcraft.io/gephi

Closing as hopefully snapcraft is enough for Debian. Please reopen otherwise.
