### ISSUE TITLE
Build Problems on Mac OS X 10.10.1 Yosemite

### ISSUE THREAD

**Issue by dbl001** [gephi/gephi#979]
[ERROR] Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.13.3:manifest (default-manifest) on project gephi-branding: Execution default-manifest of goal org.codehaus.mojo:nbm-maven-plugin:3.13.3:manifest failed: Unable to load the mojo 'manifest' in the plugin 'org.codehaus.mojo:nbm-maven-plugin:3.13.3' due to an API incompatibility: 

java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
David-Laxers-MacBook-Pro:gephi davidlaxer$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] gephi
[INFO] Branding
[INFO] LongTaskAPI
[INFO] ProjectAPI
[INFO] GraphAPI
[INFO] ExportAPI
[INFO] CoreLibraryWrapper
[INFO] Utils
[INFO] PreviewAPI
[INFO] PreviewExport
[INFO] ValidationAPI
[INFO] UILibraryWrapper
[INFO] PreviewExportUI
[INFO] VisualizationAPI
[INFO] PreviewPlugin
[INFO] DBDrivers
[INFO] ImportAPI
[INFO] DynamicAPI
[INFO] ProcessorPlugin
[INFO] ProcessorPluginUI
[INFO] ProjectUI
[INFO] UIUtils
[INFO] UIComponents
[INFO] SettingsUpgrader
[INFO] StatisticsAPI
[INFO] StatisticsPlugin
[INFO] StatisticsPluginUI
[INFO] ToolsAPI
[INFO] AlgorithmsPlugin
[INFO] Gleem
[INFO] MostRecentFilesAPI
[INFO] DesktopProject
[INFO] VisualizationImpl
[INFO] WelcomeScreen
[INFO] WorkspaceUI
[INFO] DesktopContext
[INFO] DesktopProgress
[INFO] DesktopBranding
[INFO] LayoutAPI
[INFO] GeneratorAPI
[INFO] GeneratorPlugin
[INFO] GeneratorPluginUI
[INFO] ExportPlugin
[INFO] DesktopStatistics
[INFO] LayoutPlugin
[INFO] DesktopGenerate
[INFO] AppearanceAPI
[INFO] DesktopAppearance
[INFO] ImportPlugin
[INFO] ExportPluginUI
[INFO] DesktopRecentFiles
[INFO] DesktopExport
[INFO] PerspectiveAPI
[INFO] ImportPluginUI
[INFO] DesktopPerspective
[INFO] DesktopLayout
[INFO] DesktopImport
[INFO] DesktopPreview
[INFO] AppearancePlugin
[INFO] AppearancePluginUI
[INFO] DirectoryChooser
[INFO] gephi-app
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gephi 0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 7.4 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 159.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (7 KB at 58.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar (27 KB at 167.6 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gephi-parent ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (generate-modules-xml) @ gephi-parent ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/davidlaxer/gephi/src/main/nbm
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default) @ gephi-parent ---
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.pom (4 KB at 33.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.3/plexus-components-1.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.3/plexus-components-1.3.pom (3 KB at 28.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.pom (3 KB at 16.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.2/plexus-components-1.2.pom (3 KB at 28.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/tukaani/xz/1.2/xz-1.2.pom
Downloaded: http://repo.maven.apache.org/maven2/org/tukaani/xz/1.2/xz-1.2.pom (2 KB at 18.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.jar
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.jar
Downloading: http://repo.maven.apache.org/maven2/org/tukaani/xz/1.2/xz-1.2.jar
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-io/2.0.10/plexus-io-2.0.10.jar (58 KB at 172.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-archiver/2.4.4/plexus-archiver-2.4.4.jar (161 KB at 415.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/tukaani/xz/1.2/xz-1.2.jar (93 KB at 232.1 KB/sec)
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/davidlaxer/gephi/target/gephi-parent-0.9-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ gephi-parent ---
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom (3 KB at 22.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom (2 KB at 4.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom (5 KB at 30.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar (12 KB at 99.8 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar (226 KB at 494.6 KB/sec)
[INFO] Installing /Users/davidlaxer/gephi/pom.xml to /Users/davidlaxer/.m2/repository/org/gephi/gephi-parent/0.9-SNAPSHOT/gephi-parent-0.9-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Branding 0.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.16/maven-surefire-plugin-2.16.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.16/maven-surefire-plugin-2.16.pom (5 KB at 45.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.16/surefire-2.16.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.16/surefire-2.16.pom (19 KB at 172.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.16/maven-surefire-plugin-2.16.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.16/maven-surefire-plugin-2.16.jar (34 KB at 322.3 KB/sec)
Downloading: http://bits.netbeans.org/nexus/content/groups/netbeans/org/testng/testng/6.8.7/testng-6.8.7.jar
Downloading: http://bits.netbeans.org/nexus/content/groups/netbeans/junit/junit/4.10/junit-4.10.jar
Downloading: http://bits.netbeans.org/nexus/content/groups/netbeans/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Downloading: http://bits.netbeans.org/nexus/content/groups/netbeans/com/beust/jcommander/1.27/jcommander-1.27.jar
Downloading: http://bits.netbeans.org/nexus/content/groups/netbeans/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Downloading: http://nexus.gephi.org/nexus/content/repositories/thirdparty/org/testng/testng/6.8.7/testng-6.8.7.jar
Downloading: http://nexus.gephi.org/nexus/content/repositories/thirdparty/junit/junit/4.10/junit-4.10.jar
Downloading: http://nexus.gephi.org/nexus/content/repositories/thirdparty/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Downloading: http://nexus.gephi.org/nexus/content/repositories/thirdparty/com/beust/jcommander/1.27/jcommander-1.27.jar
Downloading: http://nexus.gephi.org/nexus/content/repositories/thirdparty/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Downloading: http://repo.maven.apache.org/maven2/org/testng/testng/6.8.7/testng-6.8.7.jar
Downloading: http://repo.maven.apache.org/maven2/junit/junit/4.10/junit-4.10.jar
Downloading: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Downloading: http://repo.maven.apache.org/maven2/com/beust/jcommander/1.27/jcommander-1.27.jar
Downloading: http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Downloaded: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar (75 KB at 287.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/com/beust/jcommander/1.27/jcommander-1.27.jar (55 KB at 172.3 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/junit/junit/4.10/junit-4.10.jar (248 KB at 775.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/testng/testng/6.8.7/testng-6.8.7.jar (816 KB at 1200.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar (265 KB at 378.8 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gephi-branding ---
[INFO] Deleting /Users/davidlaxer/gephi/modules/branding/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (generate-modules-xml) @ gephi-branding ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (generate-bundles) @ gephi-branding ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (generate-autoudate-urls) @ gephi-branding ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gephi-branding ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gephi-branding ---
[INFO] No sources to compile
[INFO] 
[INFO] --- nbm-maven-plugin:3.13.3:manifest (default-manifest) @ gephi-branding ---
[WARNING] Error injecting: org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo
java.lang.TypeNotPresentException: Type org.codehaus.mojo.nbm.NetBeansManifestUpdateMojo not present
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:462)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:120)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.UnsupportedClassVersionError: org/codehaus/mojo/nbm/NetBeansManifestUpdateMojo : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:242)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
	... 41 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gephi ............................................. SUCCESS [  8.103 s]
[INFO] Branding .......................................... FAILURE [  4.723 s]
[INFO] LongTaskAPI ....................................... SKIPPED
[INFO] ProjectAPI ........................................ SKIPPED
[INFO] GraphAPI .......................................... SKIPPED
[INFO] ExportAPI ......................................... SKIPPED
[INFO] CoreLibraryWrapper ................................ SKIPPED
[INFO] Utils ............................................. SKIPPED
[INFO] PreviewAPI ........................................ SKIPPED
[INFO] PreviewExport ..................................... SKIPPED
[INFO] ValidationAPI ..................................... SKIPPED
[INFO] UILibraryWrapper .................................. SKIPPED
[INFO] PreviewExportUI ................................... SKIPPED
[INFO] VisualizationAPI .................................. SKIPPED
[INFO] PreviewPlugin ..................................... SKIPPED
[INFO] DBDrivers ......................................... SKIPPED
[INFO] ImportAPI ......................................... SKIPPED
[INFO] DynamicAPI ........................................ SKIPPED
[INFO] ProcessorPlugin ................................... SKIPPED
[INFO] ProcessorPluginUI ................................. SKIPPED
[INFO] ProjectUI ......................................... SKIPPED
[INFO] UIUtils ........................................... SKIPPED
[INFO] UIComponents ...................................... SKIPPED
[INFO] SettingsUpgrader .................................. SKIPPED
[INFO] StatisticsAPI ..................................... SKIPPED
[INFO] StatisticsPlugin .................................. SKIPPED
[INFO] StatisticsPluginUI ................................ SKIPPED
[INFO] ToolsAPI .......................................... SKIPPED
[INFO] AlgorithmsPlugin .................................. SKIPPED
[INFO] Gleem ............................................. SKIPPED
[INFO] MostRecentFilesAPI ................................ SKIPPED
[INFO] DesktopProject .................................... SKIPPED
[INFO] VisualizationImpl ................................. SKIPPED
[INFO] WelcomeScreen ..................................... SKIPPED
[INFO] WorkspaceUI ....................................... SKIPPED
[INFO] DesktopContext .................................... SKIPPED
[INFO] DesktopProgress ................................... SKIPPED
[INFO] DesktopBranding ................................... SKIPPED
[INFO] LayoutAPI ......................................... SKIPPED
[INFO] GeneratorAPI ...................................... SKIPPED
[INFO] GeneratorPlugin ................................... SKIPPED
[INFO] GeneratorPluginUI ................................. SKIPPED
[INFO] ExportPlugin ...................................... SKIPPED
[INFO] DesktopStatistics ................................. SKIPPED
[INFO] LayoutPlugin ...................................... SKIPPED
[INFO] DesktopGenerate ................................... SKIPPED
[INFO] AppearanceAPI ..................................... SKIPPED
[INFO] DesktopAppearance ................................. SKIPPED
[INFO] ImportPlugin ...................................... SKIPPED
[INFO] ExportPluginUI .................................... SKIPPED
[INFO] DesktopRecentFiles ................................ SKIPPED
[INFO] DesktopExport ..................................... SKIPPED
[INFO] PerspectiveAPI .................................... SKIPPED
[INFO] ImportPluginUI .................................... SKIPPED
[INFO] DesktopPerspective ................................ SKIPPED
[INFO] DesktopLayout ..................................... SKIPPED
[INFO] DesktopImport ..................................... SKIPPED
[INFO] DesktopPreview .................................... SKIPPED
[INFO] AppearancePlugin .................................. SKIPPED
[INFO] AppearancePluginUI ................................ SKIPPED
[INFO] DirectoryChooser .................................. SKIPPED
[INFO] gephi-app ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.855 s
[INFO] Finished at: 2014-11-25T17:05:51-07:00
[INFO] Final Memory: 22M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:nbm-maven-plugin:3.13.3:manifest (default-manifest) on project gephi-branding: Execution default-manifest of goal org.codehaus.mojo:nbm-maven-plugin:3.13.3:manifest failed: Unable to load the mojo 'manifest' in the plugin 'org.codehaus.mojo:nbm-maven-plugin:3.13.3' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/codehaus/mojo/nbm/NetBeansManifestUpdateMojo : Unsupported major.minor version 51.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:nbm-maven-plugin:3.13.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/davidlaxer/.m2/repository/org/codehaus/mojo/nbm-maven-plugin/3.13.3/nbm-maven-plugin-3.13.3.jar
[ERROR] urls[1] = file:/Users/davidlaxer/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.0/maven-plugin-annotations-3.0.jar
[ERROR] urls[2] = file:/Users/davidlaxer/.m2/repository/org/apache/ant/ant/1.9.2/ant-1.9.2.jar
[ERROR] urls[3] = file:/Users/davidlaxer/.m2/repository/org/apache/ant/ant-launcher/1.9.2/ant-launcher-1.9.2.jar
[ERROR] urls[4] = file:/Users/davidlaxer/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[ERROR] urls[5] = file:/Users/davidlaxer/.m2/repository/org/codehaus/plexus/plexus-archiver/1.2/plexus-archiver-1.2.jar
[ERROR] urls[6] = file:/Users/davidlaxer/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[ERROR] urls[7] = file:/Users/davidlaxer/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[8] = file:/Users/davidlaxer/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[9] = file:/Users/davidlaxer/.m2/repository/org/apache/maven/shared/maven-dependency-analyzer/1.2/maven-dependency-analyzer-1.2.jar
[ERROR] urls[10] = file:/Users/davidlaxer/.m2/repository/asm/asm/3.0/asm-3.0.jar
[ERROR] urls[11] = file:/Users/davidlaxer/.m2/repository/org/apache/maven/shared/maven-filtering/1.0/maven-filtering-1.0.jar
[ERROR] urls[12] = file:/Users/davidlaxer/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.jar
[ERROR] urls[13] = file:/Users/davidlaxer/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar
[ERROR] urls[14] = file:/Users/davidlaxer/.m2/repository/org/codehaus/mojo/nbm-maven-harness/8.0-beta/nbm-maven-harness-8.0-beta.jar
[ERROR] urls[15] = file:/Users/davidlaxer/.m2/repository/org/codehaus/plexus/plexus-io/2.0.2/plexus-io-2.0.2.jar
[ERROR] urls[16] = file:/Users/davidlaxer/.m2/repository/org/codehaus/mojo/nb-shared/1.2/nb-shared-1.2.jar
[ERROR] urls[17] = file:/Users/davidlaxer/.m2/repository/com/google/guava/guava/12.0/guava-12.0.jar
[ERROR] urls[18] = file:/Users/davidlaxer/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.gephi:gephi-parent:0.9-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gephi-branding

**Comment by musically-ut** [comment]
Am facing the same problem with JDK 8.

**Comment by duchatran** [comment]
You need to run JDK 1.7.

**Comment by mbastian** [comment]
That should be fixed, can you please try again?

**Comment by dbl001** [comment]
INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:02 min
[INFO] Finished at: 2015-11-21T09:18:13-08:00
[INFO] Final Memory: 58M/372M
[INFO] ------------------------------------------------------------------------
