### ISSUE TITLE
[export gexf] void attributes are not exported

### ISSUE THREAD

**Issue by pierrempr** [gephi/gephi#985]
Hi,

I have encountered some issues when I exported my graph in the format gexf. My previous structure, which I imported, of data is an gexf graph. I use gephi toolkit to spatialize the graph and add nodes color . Some of attributes values' are void. As in this exemple :

![image](https://cloud.githubusercontent.com/assets/8969214/5488047/13580122-86b9-11e4-9cca-e76a1fec1839.png)

After spatialization and other actions on my graph, i export it in a format gexf. And when I look at the structure of my new file, I noticed that the attributes which have void values are not in. As in the exemple, this is the gexf exported :

![image](https://cloud.githubusercontent.com/assets/8969214/5488053/2ff9755e-86b9-11e4-97c5-f30cda000d4e.png)

-> There are attribute 4/5 and 7 which are missing.

I found where does the issue come from. It's in the code of gephi-toolkit, in the class "ExporterGEXF.java". 
![image](https://cloud.githubusercontent.com/assets/8969214/5488292/fe2e713e-86bb-11e4-9e3f-2beb6533b061.png)
Especially in the method 
![image](https://cloud.githubusercontent.com/assets/8969214/5488308/47e9990c-86bc-11e4-8843-35a28400e453.png)

In this method, all nodes are iterated and for each node all attributes are iterated. Next, the current attribute is tested : if it is not null, we write the attribute in the xml file. If not, the attribute null is ignored.

![image](https://cloud.githubusercontent.com/assets/8969214/5488278/c9089476-86bb-11e4-86ba-dfef555b71e0.png)

I am not going re compil the gephi toolkit, so i will replace all null attributes by a space (string).

==> Now my question is, is it possible to enable this behavior to let all attributes even if they are null ?

**Comment by mbastian** [comment]
Yes this should be possible but I would recommend to add an option for that. Some people might not want null values so it should be configurable.

**Comment by mbastian** [comment]
I've implemented this feature with a new option on GEXF 
<img width="324" alt="Screenshot 2022-10-24 at 22 40 30" src="https://user-images.githubusercontent.com/234813/197625130-126215aa-d391-4dbe-b397-f448a5dde2ce.png">
