### ISSUE TITLE
[Gephi 0.8.2] Layout processes freeze when playing the timeline of dynamic graphs

### ISSUE THREAD

**Issue by markfarrell** [gephi/gephi#986]
Hi, 

Often when I have a dynamic graph opened in my workspace, and am running any layout while playing the timeline, the layout freezes up. I cannot cancel the layout process and have to restart Gephi. Anyone know why this is happening? I don't any evidence of the issue in Gephi's log, unless I'm missing something.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
