### ISSUE TITLE
about gephi 0.8.2 for mac

### ISSUE THREAD

**Issue by nuaaqiulu** [gephi/gephi#987]
My system is mac os 10.10.1, I have installed jre7， but this gephi 0.8.2 cannot run on my macbook !

**Comment by jackiekazil** [comment]
I had the same problem. I documented the solution here: https://medium.com/notes-from-computational-social-science/gephi-is-broken-on-mac-os-97fbaef4305e --- Let me know if that worked for you.

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
