### ISSUE TITLE
Using the Data Laboratory Tab freezes Gephi

### ISSUE THREAD

**Issue by conradarcturus** [gephi/gephi#988]
I am trying to start a new project, but when I click on the Data Laboratory Tab, the whole program freezes and I cannot progress. I have to force quit it.

After reinstalling Gephi, it doesn't even startup without freezing.

I'm using a MacBook Pro Retina 2012.

Let me know if there are any log files that could help.

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
