### ISSUE TITLE
Timeframe for parallel edges support ?

### ISSUE THREAD

**Issue by sterpe** [gephi/gephi#992]
0.8.2.beta reports that `parallel edges are not supported yet,` 

Is there any good work around this issue with gephi: to graph a DFA or other FSM where two or more edges or choices *may* transition from the same current state to the same next state, yet there is unique metadata about the specific transit choice/edge that we need to preserve in the representation.

does `spells` offer anything for this?

**Comment by jockeyyan** [comment]
As you know, parallel edges are not supported, and the writer said maybe spells feature would be added next version.

**Comment by mbastian** [comment]
Hi, multi-graph support is coming in the upcoming 0.9 release. You can have multiple edges between two nodes each with a different type/label (e.g a string or an integer). The support won't be great in the visualization (i.e. edge labels on top of each other) but that should hopefully come in a future release. At least you'll be able to import, manipulate and filter based on the edge type. For vertex symbols, we don't have some reserved type like edges but you can always use attributes and create your own type. For how this changes the GEXF, see #1152. Thanks.

**Comment by sterpe** [comment]
Yes!  Thanks!
