### ISSUE TITLE
When updating the graph visualization settings, can't see changes

### ISSUE THREAD

**Issue by honzapav** [gephi/gephi#994]
Hi, I am having a problem with seeing changes in the graph visualization. I even can't see labels or zoom the graph. I have checked my configuration, did the re-instalation (I have the latest version 0.8.2). You can see my configuration test enclosed.

Many thanks for help.

![karma implementor -- mr myogl -- online](https://cloud.githubusercontent.com/assets/9762266/5627391/a539d632-9597-11e4-82b9-33cc5bea1e6b.png)

**Comment by mbastian** [comment]
Closing old issue. Please try again with the recent 0.9.1 version and reopen if you still have issues. Thanks.
