### ISSUE TITLE
gephi-0.8.2-beta doesn't launch

### ISSUE THREAD

**Issue by vaveryanov** [gephi/gephi#997]
Hi

My laptop dell latitude E6430s, Win7x64, Java jre1.8.0_25 x32
I've installed gephi-0.8.2-beta.
When I launched it, it had had opened first small launching page and disappeared in few seconds. No error message no other signs of life.
I tried to install gephi-0.8.1-beta it was the similar behavior of software.
I've installed Java jre1.8.0_25 for x64, but it didn't work too.

Could you help me to launch of the Gephi?
If you let me know where any log file of gephi, I'll check it.

Thank you in advance.

**Comment by redpoptarts** [comment]
I'm having the same issue.  0.8.2-beta on Windows 7x64.

**Comment by caesar0301** [comment]
The same issue for 0.8.2-beta on Debian and Ubuntu

**Comment by psychemedia** [comment]
Have you tried using an older version of java - jre1.7 or even jre1.6 ?

**Comment by vaveryanov** [comment]
1. I have downloaded and installded
Java SE Runtime Environment 6u38 (jre-6u38-windows-x64.exe)
It is here
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase6-419409.html
2. Installed Gephi-0.8.2
3. Changed configuration file
C:\Program Files (x86)\Gephi-0.8.2\etc\gephi.conf
jdkhome="C:\Program Files\Java\jre6"
4. Launched Gephi
"C:\Program Files (x86)\Gephi-0.8.2\bin\gephi64.exe" 

It works. Thank you! :)

**Comment by bill-e-ghote** [comment]
I don't think much of using obsolete, insecure versions of Java.  When will Gephi be updated to support current release of Java 8?

**Comment by suzizecat** [comment]
Have juste installed Gephi for the first time, and i have the same problem...

**Comment by boite** [comment]
I'm having this problem with Gephi 0.8.2b and Java 8u31 on Win7 x64.

Here's a messages.log which shows the java (x86) exception: https://gist.github.com/boite/3d34d678a1203c3be5d2

    java.lang.IllegalStateException: java.lang.IllegalAccessException:
    Class org.openide.util.WeakListenerImpl$ProxyListener can not access a member of class
    org.openide.filesystems.$Proxy0 with modifiers "public"

I get the same exception if I point `jdkhome` at the x64 java.

**Comment by suzizecat** [comment]
A solution is to download and use the JDK instead of the JRE. The JRE don't make Gephi works, but it's fine with JDK

**Comment by sbrl** [comment]
I am also having this problem. I s there a workaround that doesn't involve installing an older (and potentially vulnerable) version of Java?

**Comment by withforesight** [comment]
had the same problem (on Windows 8.1 32-bit, Java 8 (jre1.8.0_31)
What worked for me was downloading the snapshot version from here:
https://github.com/gephi/gephi (under Nightly Builds)

Also unzipped the snapshot out-side of normal c:\program files ....


other replies in this thread:

https://github.com/gephi/gephi/issues/959#issuecomment-76528242

**Comment by sbrl** [comment]
@MikeBehar Thanks for the reply. If I do that though I get a message 
saying "Please install Java 1.7 or higher". I have the latest version of 
java installed. What is going on here? Perhaps it would be better to 
bundle the correct version of Java with Gephi.....

**Comment by withforesight** [comment]
Bundling it with JAVA is possible but I think that becomes a maintenance
nightmare given the frequency of JAVA updates.

I just installed this nightly build
gephi-0.9-20141206.171424-519  from here: https://github.com/gephi/gephi
unzipped to my M drive (not C;\programs...) then went to gelphi>bin> and
double clicked gelphi.exe and gelphi64.exe and both worked.

Perhaps in your case it is not finding JAVA.  Do you have it set as a path
environmental variable...

Start -> All Apps -> Control panel -> advanced  \System and
Security\System  ... system properties > environment variables

in my case this
shows:C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;.....Program
Files (x86)\nodejs\

**Comment by sbrl** [comment]
Yep, I have "C:\ProgramData\Oracle\Java\javapath" in my PATH.

I still get the message "Cannot find Java 1.7 or higher."

**Comment by withforesight** [comment]
If the nightly build and the latest release both do not work (for you),
then my best guess is that it is some configuration issue on your machine.
Do you have gephi.config? Maybe check
gephi.conf jdkhome="C:\Program Files\Java\jreXx

I don't know if that line in  .config is required or not.  If you have it,
try deleting that line, if you don't have it, try adding that line.  If
that does not work, I am out of ideas. Sorry.

**Comment by sbrl** [comment]
IT WORKS!

Thank you so much for your help. The problem was that I /hadn't/ 
specified the location that I have installed Java to. Specifying it 
works a treat :D

**Comment by jfcastaings** [comment]
Hello,

I would like to apply your advice but I cannot find...gephi.config can you to tell me how to proceed to find it please ?
Thanks a lot

**Comment by withforesight** [comment]
The config file should be here (windows)
*C:\Program Files\Gephi\etc\gephi.conf* and edit file manually.

Also, there is a helpful article here:
https://gephi.github.io/users/install/

Hope this helps.

Mike

**Comment by jfcastaings** [comment]
Thanks a lot for your quick answer withforesight !

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Comment by meenashashidhar** [comment]
I faced similar issue. Gephi 8.2 wasn't launching. 8.2 works only with Java 1.7. I had to uninstall 1.8 and install 1.7 again. Gephi 8.2 launched after installing 1.7 and modifying the config file.

**Comment by cohesif** [comment]
Thanks vaveryanov, your solution worked for me with Gephi 0.9.1 -->
Changed configuration file and replaced " \"  by "/" (C:\ --> C:/)
C:/Program Files (x86)/Gephi-0.9.1/etc/gephi.conf
jdkhome="C:/Program Files (x86)/Java/jre1.8.0_131"

**Comment by vamsikrishnasabbisetty** [comment]
The following resolved my Issue:

1) uninstall older versions of java
2) Installed Java 8
3) Updated jdk path to jdkhome="C:\Program Files\Java\jre1.8.0_161"  in gephi.conf (etc folder)
